### ISSUE TITLE
Providers bocked

### ISSUE THREAD

**Issue by DZMM** [DobyTang/LazyLibrarian#1006]
I'm running version 2542a7df37ed84158fe9d6eb65862cf5db607749 via the linuxserver docker.  I just reinstalled but all my providers are blocked when searching - please see my logs.  I have the same result with torznab and other newznab sources.

Help please

`27-Aug-2017 12:17:24 - DEBUG   :: SEARCHALLBOOKS : Searching 5 nzb results for best eBook match
27-Aug-2017 12:17:24 - DEBUG   :: SEARCHALLBOOKS : NZB author/book Match: 100/60 Rebecca Winters The Billionaires Prize epub at https://api.nzbgeek.info/
27-Aug-2017 12:17:24 - ERROR   :: SEARCHALLBOOKS : Unhandled exception in findBestResult: Traceback (most recent call last):
  File "/app/lazylibrarian/lazylibrarian/resultlist.py", line 183, in findBestResult
    for i in [i for i, x in enumerate(typelist) if x == item]:
TypeError: 'NoneType' object is not iterable

27-Aug-2017 12:17:24 - DEBUG   :: SEARCHALLBOOKS : Using stored capabilities for https://api.nzbgeek.info/
27-Aug-2017 12:17:24 - DEBUG   :: SEARCHALLBOOKS : [IterateOverNewzNabSites] - https://api.nzbgeek.info/
27-Aug-2017 12:17:24 - DEBUG   :: SEARCHALLBOOKS : [NewzNabPlus] searchType [general] with Host [https://api.nzbgeek.info/] mode [nzb] using api [29a08f708df51820634d618e1f94574a] for item [{'bookSub': u'', 'bookid': u'2171850', 'bookName': u'The Vow', 'library': 'eBook', 'authorName': u'Rebecca Winters', 'searchterm': u'Rebecca Winters The Vow'}]
27-Aug-2017 12:17:24 - DEBUG   :: SEARCHALLBOOKS : [NewzNabPlus] - nzb Search parameters set to {'q': u'Rebecca Winters The Vow', 'apikey': u'29a08f708df51820634d618e1f94574a', 't': u'search', 'extended': u'1'}
27-Aug-2017 12:17:24 - DEBUG   :: SEARCHALLBOOKS : [NewzNabPlus] URL = https://api.nzbgeek.info//api?q=Rebecca+Winters+The+Vow&apikey=##################&t=search&extended=1
27-Aug-2017 12:17:29 - ERROR   :: SEARCHALLBOOKS : Error reading data from https://api.nzbgeek.info/: [Errno -3] Try again
27-Aug-2017 12:17:29 - INFO    :: SEARCHALLBOOKS : Blocking provider https://api.nzbgeek.info/ for 60 minutes because [Errno -3] Try again
27-Aug-2017 12:17:29 - DEBUG   :: SEARCHALLBOOKS : Provider Blocklist contains 1 entries
27-Aug-2017 12:17:29 - DEBUG   :: SEARCHALLBOOKS : No data returned from https://api.nzbgeek.info/ for Rebecca Winters The Vow
27-Aug-2017 12:17:29 - INFO    :: SEARCHALLBOOKS : NZB Searches for eBook Rebecca Winters The Vow returned no results.
27-Aug-2017 12:17:29 - DEBUG   :: SEARCHALLBOOKS : No active nzb providers found
27-Aug-2017 12:17:29 - DEBUG   :: SEARCHALLBOOKS : No active nzb providers found
27-Aug-2017 12:17:29 - ERROR   :: SEARCHALLBOOKS : Unhandled exception in search_book: Traceback (most recent call last):
  File "/app/lazylibrarian/lazylibrarian/searchbook.py", line 214, in search_book
    modelist.remove('nzb')
ValueError: list.remove(x): x not in list

27-Aug-2017 12:17:44 - DEBUG   :: CP Server Thread-11 : logfile [/config/log/lazylibrarian.log] does not exist
27-Aug-2017 12:17:44 - DEBUG   :: CP Server Thread-11 : Redacted 0 passwords/apikeys
27-Aug-2017 12:17:44 - DEBUG   :: CP Server Thread-11 : 0 log lines written to /config/log/debug.log
27-Aug-2017 12:17:44 - INFO    :: CP Server Thread-11 : Debug log saved as /config/log/debug.zip
27-Aug-2017 12:17:48 - INFO    :: LOGS : Debug log OFF, loglevel is 0
27-Aug-2017 12:22:06 - DEBUG   :: POSTPROCESS : Checking 2 files in /books_import
27-Aug-2017 12:22:06 - DEBUG   :: POSTPROCESS : Found 0 files marked "Snatched"
27-Aug-2017 12:22:06 - INFO    :: POSTPROCESS : 0 books/mags processed.
27-Aug-2017 12:22:06 - INFO    :: POSTPROCESS : Nothing marked as snatched. Stopping postprocessor.
27-Aug-2017 12:22:06 - DEBUG   :: POSTPROCESS : Stop processDir job
`

**Comment by philborman** [comment]
Upgrade to current version should fix it. There was a bug introduced a couple of days ago, but fixed a few hours later ;-)

**Comment by DZMM** [comment]
ahh that'd explain it!

Thanks
