### ISSUE TITLE
ERROR	Unhandled exception in libraryScan: File "/opt/LazyLibrarian/lazylibrarian/librarysync.py",

### ISSUE THREAD

**Issue by WzL** [DobyTang/LazyLibrarian#1012]
To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log :

```
ERROR | Unhandled exception in libraryScan: Traceback (most recent call last):   File "/opt/LazyLibrarian/lazylibrarian/librarysync.py", line 382, in LibraryScan     for r, d, f in os.walk(startdir):   File "/usr/lib/python2.7/os.py", line 286, in walk     if isdir(join(top, name)):   File "/usr/lib/python2.7/posixpath.py", line 73, in join     path += '/' + b UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 16: ordinal not in range(128)
-- | --
```

During library scan and refresh author, with author "Esther Verhoef", no library is build as a result.

**Comment by philborman** [comment]
ok, found the problem I think, but I can't actually reproduce it here so I'm not totally convinced.
Are you up to a small bit of editing to confirm what I think?
On the line quoted in your debug log, 
File "/opt/LazyLibrarian/lazylibrarian/librarysync.py", 
line 382, in LibraryScan     
for r, d, f in os.walk(startdir): 

change it to os.walk(str(startdir)):

If that fixes it I will push a proper fix later. There are a couple of other places in the code that could hit the same issue. It's a problem when a plain text filename has accented characters that don't fit the default encoding, as os.walk tries to convert them and fails, and it doesn't fail cleanly. 
Adding str() around the os.walk tells it not to convert. That could just push the problem further down the function, but I can't tell here as I can't make it fail with the books in my library.

**Comment by WzL** [comment]
sure, np, just to verify i changed 

for r, d, f in os.walk(startdir):

to 

for r, d, f in os.walk(str(startdir)):

And it worked perfectly! Hitting the " Library scan " and " refresh author"  button did the magic and voila content was found and linked to related items of author. I think fixed succesfully?

**Comment by philborman** [comment]
Excellent, thanks for your help.
I will push a fix shortly.
You might need to remove your changes for the auto-update to work, as git might think we have conflicting changes

**Comment by WzL** [comment]
btw, a lot more books are found now, list grows by the minute o_0
