### ISSUE TITLE
FEAT: How to start as a service/dameon in Windows

### ISSUE THREAD

**Issue by seanvree** [DobyTang/LazyLibrarian#1015]
download https://nssm.cc/download

EDIT:  After you download, right click on NSSM.exe -> Properties -> UNBLOCK. 
NOTE:  SOME A/V software thing NSSM.exe is a virus.  ENSURE to add NSSM.exe to your exclusion list. 

Put nssm.exe in c:\windows\system32

Go to command prompt type:  

```
nssm install lazylibrarian
```

change the following settings:

![lazylibrarian_service](https://user-images.githubusercontent.com/8906637/29867867-c5e4e1f8-8d31-11e7-9784-4a3f9845ae4a.PNG)

Go to services (Start -> Run -> services.msc) change lazylibrarian to automatic. 

Profit:

![lazylibrarian_service2](https://user-images.githubusercontent.com/8906637/29867992-2ece71c0-8d32-11e7-8366-ecd477a5c389.PNG)

**Comment by philborman** [comment]
Excellent, thanks.
I will add this to the wiki

**Comment by seanvree** [comment]
@philborman 

Add these notes as well:

```
EDIT:  After you download, right click on NSSM.exe -> Properties -> UNBLOCK. 
NOTE:  SOME A/V software thing NSSM.exe is a virus.  ENSURE to add NSSM.exe to your exclusion list. 
```

**Comment by philborman** [comment]
ok thanks, done that.
