### ISSUE TITLE
Software update has populated open/have shelf

### ISSUE THREAD

**Issue by sscraggles** [DobyTang/LazyLibrarian#1016]
The last few software updates have populated the open/have shelf config, where I had left it empty because I don't want goodreads having a list of all my books.   This was fine, as I was able to catch it before doing a sync to goodreads, now however there is a scheduled sync.
 
Lazylibrarian obeys an empty config and doesn't sync the entire list of books to goodreads.  Can it be stopped overwriting an empty config.

**Comment by philborman** [comment]
Should be fixed now.

**Comment by sscraggles** [comment]
thats better, thanks
