### ISSUE TITLE
Whats the difference between the GoodReads oAuth secret and GoodReads secret?

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1018]
My GoodReads dev api key only has a single key / secret, but LL has 2 text boxes for secrets?

**Comment by philborman** [comment]
The oauth entries are just if you want to follow authors or sync books to your bookshelves.

**Comment by MrMxyzptlk** [comment]
I should have been more specific...where do I find my GoodReads secret?
I can find my dev secret...

**Comment by MrMxyzptlk** [comment]
grsync.py | get_user_id | 97 | Goodreads sync error: Please authorise first

**Comment by philborman** [comment]
The oauth key/token are different to the developer ones, and you need both sets of keys/tokens if you want to sync authors or bookshelves. 

There is a program in the lazylibrarian folder (goodreads_auth.py) that you can use to get oauth key/token, or if you have used oauth on another program (calibre maybe) you can use those settings

**Comment by MrMxyzptlk** [comment]
Aha! Thanks...

**Comment by MrMxyzptlk** [comment]
I got it to work...
