### ISSUE TITLE
Random characters post update

### ISSUE THREAD

**Issue by bishpuppy** [DobyTang/LazyLibrarian#1019]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
76825d723d2056371783a0ff997bbe37e1a305d4

### Operating system used (windows, mac, linux, NAS type)
Centos 7 minimal

### Interface in use (default, bookstrap)
default

### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
git

After updating to the latest build, the web ui shows random characters, almost looks like wrong encoding.    Can't click on an author from the main page.  Searched for an author that I had and the search was fine, once I clicked on the author, the display went back to the wrong encoding.

This is what I get.

񐁇𠁯񐁧𠀠𠀮􀀮𐁍񀁲󠁩𐀀򵙠񎻡𧨭 | 򀁔􀁥򐁗񀁬𰀠𠁡𰁤𰀠󀁯񐁬񀁣󰁩n𐁐󋵐羋󋧐羋󿿽󿿿󿿿󿿿󖬀
-- | --

urls look like this: 
<host:port>/authorPage?AuthorID=%F1%80%80%B3%F1%B0%80%B6%F0%A0%80%B3%EF%BF%BD%F2%A7%9B%80%E7%BE%8B

**Comment by bishpuppy** [comment]
Note: via API, the results are correct (English / UTF8 encoding).

**Comment by philborman** [comment]
Is it just the default interface, or is bookstrap showing the same problem?
I have just downloaded a fresh copy from git and all seems to be working here.
Something wrong with your update, maybe incomplete or corrupt?
I would try a fresh install, I think.

**Comment by philborman** [comment]
Is it just the default interface, or is bookstrap showing the same problem?
I have just downloaded a fresh copy from git and all seems to be working here.
Something wrong with your update, maybe incomplete or corrupt?
I would try a fresh install, I think.

**Comment by philborman** [comment]
The other option is your database is corrupt. As you are familiar with the api you could check that by listing all authors, api cmd=getIndex

**Comment by bishpuppy** [comment]
default and Bootstrap show the same thing.  via API, the results are correct (I can see the authors name, get the img url etc).  I'll try a fresh DB to see if that helps, if yes, then i'll look into a DB repair.

**Comment by bishpuppy** [comment]
stopped LL, renamed the lazylibrarian.db to lazylibrarian.db.original, started LL and it said it was upgrading to db v22.  Added an author and got the same thing on a fresh db.  

this is what it looks like:  http://i.imgur.com/h49q6dz.png

**Comment by philborman** [comment]
ok so database seems ok, it's some sort of display issue. 
Upgrading to v22 is normal for a new database, when first created the database doesn't have any tables or a version number. v22 is current,

Have you tried reinstalling lazylibrarian from git in case the upgrade didn't complete or was corrupted somehow?

**Comment by bishpuppy** [comment]
I moved all the files to a new directory called 'bad'.  Downloaded the zip from git and extracted it.  copied over the config.ini and same thing.  I looked over the config.ini to see if something was weird but looks normal.  

Below is my config.ini (removing apikey from my newznab server)


----- START OF CONFIG.INI -----
[General]
http_port = 8088
http_host = 0.0.0.0
http_user = admin
http_pass = <REMOVED>
http_root = /lazylibrarian
http_look = default
launch_browser = False
proxy_host = 
proxy_type = 
logdir = /opt/lazylibrarian/Logs
loglevel = 2
match_ratio = 80
imp_onlyisbn = False
imp_preflang = en, eng, en-US
imp_autoadd = 
ebook_type = epub, mobi, pdf
destination_copy = False
download_dir = /media/downloading/completed/Books
imp_monthlang = en_US.utf8
imp_singlebook = False
imp_convert = 
cache_age = 30
alternate_dir = 
mag_type = pdf
bookstrap_theme = slate
loglimit = 500
reject_words = audiobook, mp3
logfiles = 10
logsize = 204800
https_enabled = False
https_cert = 
https_key = 
api_enabled = True
api_key = <REMOVED>
dload_ratio = 90
http_proxy = False
imp_calibredb = 
git_program = 
reject_maxsize = 0
displaylength = 10
imp_autosearch = False
task_age = 0
reject_magsize = 0
mag_age = 31
name_postfix = snr, jnr, jr, sr, phd
dir_perm = 0o755
reject_magmin = 0
mag_single = True
file_perm = 0o644
reject_minsize = 0
ebook_dir = /media/movies/Multimedia/Books
reject_audio = epub, mobi
book_img = 1
audio_dir = 
wall_columns = 6
series_tab = True
audio_tab = True
user_accounts = False
max_pages = 0
audiobook_type = mp3
toggles = True
mag_img = 1
reject_minaudio = 0
imp_autoadd_bookonly = False
blocklist_timer = 3600
reject_maxaudio = 0
author_img = 1
mag_tab = True
admin_email = 
calibre_server = 
calibre_use_server = False
calibre_pass = 
calibre_user = 

[Git]
git_user = dobytang
git_repo = lazylibrarian
git_branch = master
install_type = source
current_version = 76825d723d2056371783a0ff997bbe37e1a305d4
latest_version = 76825d723d2056371783a0ff997bbe37e1a305d4
commits_behind = 1
git_updated = 

[USENET]
nzb_downloader_sabnzbd = False
nzb_downloader_blackhole = True
nzb_blackholedir = /media/downloading/nzb/Books
usenet_retention = 0
nzb_downloader_nzbget = False
nzb_downloader_synology = False

[SABnzbd]
sab_host = 
sab_port = 0
sab_subdir = 
sab_user = 
sab_pass = 
sab_api = 
sab_cat = 

[DLMethod]
use_tor = False
use_nzb = False

[API]
book_api = GoodReads
gr_api = <REMOVED>
gb_api = 
gr_secret = 
gr_sync = False
gr_oauth_token = 
gr_oauth_secret = 
gr_wanted = to-read
gr_owned = owned
gr_follow = False
gr_follownew = False

[NZBMatrix]
nzbmatrix = False
nzbmatrix_user = 
nzbmatrix_api = 

[Newznab2]
enabled = False
host = 
api = 
generalsearch = search
booksearch = book
magsearch = 
bookcat = 7000,7020
magcat = 7010
extended = 1
updated = 
manual = False
audiosearch = 
audiocat = 3030
dlpriority = 0

[Newzbin]
newzbin = False
newzbin_uid = 
newzbin_pass = 

[TORRENT]
tor_downloader_blackhole = False
tor_downloader_utorrent = False
numberofseeders = 10
torrent_dir = 
tor_downloader_transmission = False
tor_downloader_deluge = False
tor_downloader_qbittorrent = False
tor_convert_magnet = False
tor_downloader_rtorrent = False
tor_downloader_synology = False
keep_seeding = True
prefer_magnet = True

[UTORRENT]
utorrent_host = 
utorrent_user = 
utorrent_pass = 
utorrent_label = 
utorrent_port = 0

[KAT]
kat = False
kat_host = kat.cr
kat_dlpriority = 0

[SearchScan]
search_interval = 360
scan_interval = 10
versioncheck_interval = 24
searchrss_interval = 20
goodreads_interval = 48

[LibraryScan]
full_scan = False
notfound_status = Skipped
add_author = False
newbook_status = Skipped
newauthor_status = Skipped
no_future = False
add_series = True
newaudio_status = Skipped
newauthor_books = False

[PostProcess]
ebook_dest_folder = $Author/$Title
ebook_dest_file = $Title - $Author
mag_dest_folder = _Magazines/$Title/$IssueDate
mag_dest_file = $IssueDate - $Title
mag_relative = True
one_format = False

[Twitter]
use_twitter = False
twitter_notify_onsnatch = False
twitter_notify_ondownload = False
twitter_username = 
twitter_password = 
twitter_prefix = LazyLibrarian

[Boxcar]
use_boxcar = False
boxcar_notify_onsnatch = False
boxcar_notify_ondownload = False
boxcar_token = 

[Pushbullet]
use_pushbullet = False
pushbullet_notify_onsnatch = False
pushbullet_notify_ondownload = False
pushbullet_token = 
pushbullet_deviceid = 

[NMA]
nma_enabled = 0
nma_apikey = 
nma_priority = 0
nma_onsnatch = False
use_nma = False
nma_ondownload = False

[NZBGet]
nzbget_host = localhost
nzbget_user = admin
nzbget_pass = <REMOVED>
nzbget_cat = Books
nzbget_priority = 100
nzbget_port = 8086
nzbget_category = 

[Newznab0]
enabled = True
host = https://api.dognzb.cr
api = <REMOVED>
generalsearch = search
booksearch = book
magsearch = 
bookcat = 7000,7020
magcat = 7010
extended = 1
updated = 2017-08-04
manual = False
audiosearch = 
audiocat = 3030
dlpriority = 0

[Newznab1]
enabled = True
host = https://api.nzbgeek.info
api = <REMOVED>
generalsearch = search
booksearch = book
magsearch = 
bookcat = 7000,7020
magcat = 7010
extended = 1
updated = 2017-08-04
manual = False
audiosearch = 
audiocat = 3030
dlpriority = 0

[Newznab3]
enabled = False
host = 
api = 
generalsearch = search
booksearch = book
magsearch = 
bookcat = 7000,7020
magcat = 7010
extended = 1
updated = 
manual = False
audiosearch = 
audiocat = 3030
dlpriority = 0

[Newznab4]
enabled = False
host = 
api = 
generalsearch = search
booksearch = book
magsearch = 
bookcat = 7000,7020
magcat = 7010
extended = 1
updated = 
manual = False
audiosearch = 
audiocat = 3030
dlpriority = 0

[Torznab0]
enabled = False
host = 
api = 
generalsearch = search
booksearch = book
magsearch = 
bookcat = 8000,8010
magcat = 8030
extended = 1
updated = 
manual = False
audiosearch = 
audiocat = 3030
dlpriority = 0

[Torznab1]
enabled = False
host = 
api = 
generalsearch = search
booksearch = book
magsearch = 
bookcat = 8000,8010
magcat = 8030
extended = 1
updated = 
manual = False
audiosearch = 
audiocat = 3030
dlpriority = 0

[Torznab2]
enabled = False
host = 
api = 
generalsearch = search
booksearch = book
magsearch = 
bookcat = 8000,8010
magcat = 8030
extended = 1
updated = 
manual = False
audiosearch = 
audiocat = 3030
dlpriority = 0

[Torznab3]
enabled = False
host = 
api = 
generalsearch = search
booksearch = book
magsearch = 
bookcat = 8000,8010
magcat = 8030
extended = 1
updated = 
manual = False
audiosearch = 
audiocat = 3030
dlpriority = 0

[Torznab4]
enabled = False
host = 
api = 
generalsearch = search
booksearch = book
magsearch = 
bookcat = 8000,8010
magcat = 8030
extended = 1
updated = 
manual = False
audiosearch = 
audiocat = 3030
dlpriority = 0

[TRANSMISSION]
transmission_host = 
transmission_user = 
transmission_pass = 
transmission_port = 0

[DELUGE]
deluge_host = 
deluge_port = 0
deluge_user = 
deluge_pass = 
deluge_label = 

[Pushover]
use_pushover = False
pushover_onsnatch = False
pushover_ondownload = False
pushover_keys = 
pushover_apitoken = 
pushover_priority = 0
pushover_device = 

[AndroidPN]
use_androidpn = False
androidpn_notify_onsnatch = False
androidpn_notify_ondownload = False
androidpn_url = 
androidpn_username = 
androidpn_broadcast = True

[RSS_0]
enabled = False
host = 
dlpriority = 0

[QBITTORRENT]
qbittorrent_host = 
qbittorrent_user = 
qbittorrent_pass = 
qbittorrent_label = 
qbittorrent_port = 0

[TPB]
tpb = False
tpb_host = https://piratebays.co
tpb_dlpriority = 0

[ZOO]
zoo = False
zoo_host = https://zooqle.com
zoo_dlpriority = 0

[TDL]
tdl = False
tdl_host = torrentdownloads.me
tdl_dlpriority = 0

[RTORRENT]
rtorrent_host = 
rtorrent_user = 
rtorrent_pass = 
rtorrent_label = 
rtorrent_dir = 

[SYNOLOGY]
synology_host = 
synology_port = 0
synology_user = 
synology_pass = 
synology_dir = Multimedia/Download
use_synology = False

[EXTRA]
extra = False
extra_host = extratorrent.cc

[GEN]
gen = False
gen_host = libgen.io
gen_dlpriority = 0
gen2_dlpriority = 0
gen2_host = libgen.io
gen2 = False
gen_search = search.php
gen2_search = foreignfiction/index.php

[LIME]
lime = False
lime_host = https://www.limetorrents.cc
lime_dlpriority = 0

[Slack]
use_slack = False
slack_notify_onsnatch = False
slack_notify_ondownload = False
slack_token = 

[Email]
use_email = False
email_notify_onsnatch = False
email_notify_ondownload = False
email_from = 
email_to = 
email_ssl = False
email_smtp_server = 
email_smtp_port = 25
email_tls = False
email_smtp_user = 
email_smtp_password = 
email_sendfile_ondownload = False

[Custom]
custom_notify_onsnatch = False
use_custom = False
custom_script = 
custom_notify_ondownload = False

[WWT]
wwt_dlpriority = 0
wwt = False
wwt_host = https://worldwidetorrents.eu

[Prowl]
prowl_onsnatch = False
prowl_apikey = 
prowl_priority = 0
prowl_ondownload = False
use_prowl = False

------- END OF CONFIG.INI --------

**Comment by philborman** [comment]
Config looks ok. Very odd, no idea what's going on yet. Couple of thoughts that might help find the problem...

1. Is it just the author pages that are wrong, or do you have similar issues with the eBook and Series pages (each uses different code, might narrow it down a bit)

2. Roughly how old was the previous version you upgraded from, so we can look at what changes have been made since then. If you don't know how old it was, on the lazylibrarian git page there is a "code" tab. On the code page is a tab saying "9 releases"
Your current version is the August release. If you download the July release, does the problem go away?
I would run this on a new database or a copy of your working one, keep the original, as the database structure is different.

**Comment by bishpuppy** [comment]
Authors / Books / Series, they all show the same thing.  I don't recall how old the build was.  I just tried the March release with my config.ini and my db and that worked fine.  Clicked on update and that updated to the latest version with no problem.  

Thank you for the solution and fix :)

**Comment by philborman** [comment]
Well, glad it's working, but we still don't now what the problem was.
Lets see if anyone else has similar problems ;-)
