### ISSUE TITLE
Button processing returns to 127.0.0.1

### ISSUE THREAD

**Issue by DK2Maverick** [DobyTang/LazyLibrarian#1020]
To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Headless install running on Ubuntu Server. When I click any button that performs an action like Save Config, Refresh Author, Remove Author from my remote windows pc, the return screen goes back to the localhost address. 

Example:
Sitting on an author page - address is http://downloader:5299/authorPage?AuthorID=7149797

Click Refresh Author and the return page changes to 
http://127.0.0.1:5299/authorPage?AuthorID=7149797

Config has hostname set to downloader

That action that the button was supposed to perform is performed. Author is refreshed, config is saved.

Happen in both interfaces, and happens if I replace the hostname with the servers ip as well.

**Comment by tazboyz16** [comment]
Im having same issues with my Testing VM. Running Ubuntu 16.04.3 fresh install 4 hours ago. Almost every other button was failing reverting back to 127.0.0.1 during my setting up Reverse Proxy. Verified with just using the ip address of server with port, got same results

**Comment by philborman** [comment]
Unable to reproduce it here. 
I see @tazboyz16 is using a reverse proxy, id @DK2Maverick using a reverse proxy too, as it could be related to that. I tried reverse proxy with apache2 and that seems ok, but I haven't tried nginx or others.

**Comment by tazboyz16** [comment]
i think i found my issue. I didnt edit the config for the localhost to 0.0.0.0 to allow outside connections. Strangely it still allowed some ability to it. Might wanna edit the Installation and Daemon wiki to have it under the installs

**Comment by DK2Maverick** [comment]
no I am not. My proxy values are blank.

**Comment by philborman** [comment]
Is this a new install or an upgrade? If it was working on an earlier version it might narrow down where to look. Also is your lazylibrarian localhost set to 0.0.0.0

**Comment by DK2Maverick** [comment]
New install, happened right away. Currently set to 0.0.0.0  I have also tried the hostname and the server ip. No change in effect. Tried Chrome and Firefox, Cleared all cache in both.

I watched the browser work bar as I clicked the save config button.
Address bar says http://downloader:5299/config  - then I click save changes

work bar says:
Sending request to downloader
waiting for downloader
looking up 127.0.0.1
connecting to 127.0.0.1

I'll wait to see if it works for tazboyz16 tonight. if his change works, I will try a reinstall.

**Comment by billbo99** [comment]
When there is no config file to read from the website starts up automatically on 127.0.0.1.   I found you had to save the config file after ensuring its been set to 0.0.0.0,  then restart the website.   After that you can connect to it from a remote computer.

**Comment by DK2Maverick** [comment]
billbo99 was right. A simple restart solved it. Could have sworn I did that, but I guess I did not.  I had not restarted it since the install.  Thank you all for the help.

**Comment by philborman** [comment]
ok thanks. Good to know it's working for you. The code looks like it defaults to 0.0.0.0 if there is no config, but maybe it's not working as expected. I will take another look.
