### ISSUE TITLE
Audiobooks being Postprocessed into a Single MP3?

### ISSUE THREAD

**Issue by grizzlechips** [DobyTang/LazyLibrarian#1021]
Version: 3c7b2291db9090ea6753f3f3a103d7e6f2b9af35
OS: Windows 10
UI: Default
API: Goodreads
Source: GitHub

Hi!  I followed your audiobook settings recommendations per [this issue thread](https://github.com/DobyTang/LazyLibrarian/issues/788#issuecomment-301421672) and it seems to work swimmingly, except for one crucial detail - the postprocessing seems to eliminate all the chapter files and only leave one.

From this, unprocessed: 
![image](https://user-images.githubusercontent.com/6484738/30006875-44239d36-90c8-11e7-9da7-3a7292fa3fb1.png)

To this:
![image](https://user-images.githubusercontent.com/6484738/30006897-8543bbb6-90c8-11e7-81af-f61048d94774.png)

I know I probably have my postprocessing settings set incorrectly, so I'm including a screenshot of them below:
![image](https://user-images.githubusercontent.com/6484738/30006922-f22b6832-90c8-11e7-8240-1ee4372f082c.png)

Also, here's a screenshot of the log where I believe the step is happening, specifically after it's copied all the chapters over and then created a link to the preferred file type:
![image](https://user-images.githubusercontent.com/6484738/30006960-de38bbee-90c9-11e7-83af-ca5c5de1a15a.png)

I'd simply like the chapter files to remain after folder renaming and metadata being fetched.  Is this possible?  Feel free to let me know if you need any more info.

Thanks in advance!

**Comment by grizzlechips** [comment]
I believe I've at least recognized what's going on.  LL is copying each chapter MP3 into the folder, and renaming it as if it were the entire book.  Repeat and overwrite for every single chapter, hence there only being one file in the postprocessed directory.  

I recognized that the final file was the exact same file size as one of the chapters, which clued me in.

So now the question is...  is there a way for me to have LL copy the files over to the postprocessed directory while retaining the individual filenames?

**Comment by philborman** [comment]
Ah - it used to work, but the information in that thread is obsolete. If you switch to the "bookstrap" interface there is a dedicated audiobook mode. All new development is on the bookstrap interface and the default one may be removed at some point. It's using very old libraries that aren't as capable, and it's too much work to maintain two separate codebases. I have just added a note to the old thread.
