### ISSUE TITLE
Localhost redirects to 127.0.0.1

### ISSUE THREAD

**Issue by santino405** [DobyTang/LazyLibrarian#1023]
I've been having an issue where LazyLibrarian would redirect to 127.0.0.1. It would happen some what sporadically. Sometimes when first loading up the webpage http:\\localip:5299\home it would redirect to http:\\127.0.0.1\home causing the webui to not load. If I would re-enter the address it would work. Then sometimes when i would try to add a book i would get take back to the localhost address. It seems like the issue is related to the cherrypy webserver as it seems some headphones web users where experiencing the same thing. Here is a link to that thread.

https://github.com/rembo10/headphones/issues/776

I've taken a look at my logs but nothing is logged when this happens. I have
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1281927/debug.zip)
 upload my debug log but nothing gets logged when the issue occurs. It even happens as I hit "start debug" and "save debug" but the debug log doesn't list anything.

**Comment by philborman** [comment]
Strange, I had another report of the same problem a few days ago, issue 1020, but that was solved by saving the lazylibrarian config file and rebooting.  The headphones problem was back in 2012, so might not be relevant as our cherrypy is more recent than that. I will see if I can find out what was changed in headphones

**Comment by santino405** [comment]
Oh thanks, didn't even realize that thread was that old. It was the only reference i found to what i was experiencing. I'll look over the 1020 issue. I've manually edited the config a few times and blasted the docker config away and recreated it a few times trying older versions of the docker image in case that was causing the issue. Even tried older versions of the docker image.

**Comment by philborman** [comment]
ok, I had a look at what was changed in headphones back then, they added a switch for tools.proxy.on which we already have in lazylibrarian. 
Are you using a proxy, what do you have in your config for...
Server hostname (default is 0.0.0.0)
WebRoot 
Enable Http Proxy
Proxy Host
Proxy Type

**Comment by santino405** [comment]
I am using a proxy below are the following configuration settings i'm using

serverhost name 0.0.0.0
WebRoot /lazylibrarian
Enable http Proxy is on
Proxy Host is blank
Proxy type is blank

The issue does happen when i'm accessing lazylibrarian locally as well as through the proxy. I've also tried playing with the settings to see if that would help i've set the settings to the below and I can't access the service at all

serverhost name (UbuntuserverIP)
webRoot /lazylibrarian
Enabled Http Proxy On
Proxy Host (NginxProxyIP)
Proxy Type http

I've also tried what was done on issue 1020 (enter in the serverhost, save the config and restart the webpage) however it doesn't seem to resolve the issue for me.

The funny thing is that it happens every time I save the config through the UI so makes me think it may be some what related to an issue accessing the config file. However I've checked the docker configuration and permissions all seem to be correct.

I think what i will do is try to install directly on to the server instead of using docker and seeing if that works correctly.

**Comment by philborman** [comment]
As you are on a docker, I think restarting the webpage isn't enough, may need to restart lazylibrarian, or maybe the docker. The cherrypy server reads it's config at boot time, and stays running until lazylibrarian is shut down or restarted, I don't think it reloads any changed values when config is saved. Not sure if it can reload without shutting down.

The headphones change in 2012 was related to a cherrypy setting that we control with "Enable HTTP Proxy" tick box, I'm running behind an apache2 server, and I do not have that box ticked. Seems to make no difference on apache2, Not sure if ngnix needs it, maybe try switching that off, save config, restart.

**Comment by santino405** [comment]
I tried installing it locally last night by doing a git pull and had the same issue. At the end of the day I ended up just going back to running it with in docker. This time I made my config changes and rebooted the docker container it self instead of and it seemed to help, wasn't running into the issue any more. 

However this morning after setting everything thing up I hit "force search" and it happened again. I think for now i'm okay with this as when ever i'm interacting with the rest of the program i'm not running into any issues. 

Not sure if there is something similar between my set up and the other people who where having this issue. However, Thanks for your help!

**Comment by philborman** [comment]
There is something odd going on, but it seems intermittent. I think it's related to reverse proxy with nginx as I have never seen it happen with apache and I've been running lazylibrarian with that for over 2 years. Last night I switched to ngnix and hit the error twice, first time I've ever seen it, but I haven't been able to  reproduce it since then.

**Comment by barbequesauce** [comment]
@santino405 can you share the nginx config, both the server section and the pertinent location section?

**Comment by santino405** [comment]
Yeah sure my nginx config is below. Actually now that you mention that Phil I think i wasn't seeing any problems until i remembered to hit the check box next to "Enable HTTP Proxy" I'll disable that and use it locally and see if I run into the issue again.

worker_processes  1;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
	auth_ldap_cache_enabled on;
	auth_ldap_cache_expiration_time 10000;
	auth_ldap_cache_size 1000;

ldap_server adds {

}


server {
	listen 80;
	server_name serveraddress;
	return 301 https://$host$request_uri;
}

server {
	listen 443 ssl default_server;
	server_name serveraddress;
	ssl_certificate /etc/letsencrypt/live/serveraddress/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/serveraddress/privkey.pem;
	ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
	ssl_prefer_server_ciphers on;
	auth_ldap "Enter AD credentials";
    auth_ldap_servers adds;
	
location / {

	proxy_pass http://192.168.1.20:82;
}

location /lazylibrarian {
	proxy_pass http://192.168.1.20:5299;
	proxy_redirect off;
	proxy_set_header Host $host:$server_port;
	proxy_redirect http:// https://;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
}
}
}

**Comment by barbequesauce** [comment]
In the location section, you have conflicting proxy_redirects. I'd suggest removing the first one (proxy_redirect off;) and leave the second one (proxy_redirect http:// https://;) in place...

**Comment by santino405** [comment]
Thanks i've removed it. I was playing around with the nginx config when i first started having issues and didn't realize. I've gone ahead and turned off the "Enable Http Proxy". I haven't had the issue crop back up yet and interestingly enough my ngnix proxy is still working. I'll report back in if I see it happen again.

**Comment by barbequesauce** [comment]
Yeah. nginx is pretty cool in that you don't always need to tell the proxied app it is being proxied if you get the configuration right...

**Comment by philborman** [comment]
When you tick "Enable Http Proxy" that sets cherrypy tools.proxy.on which expects to find a header "X-Forwarded-Host". If that is not found it seems it sometimes reverts to 127.0.0.1
Apache2 uses header "X-Forwarded-Host", but nginx uses header "Host" instead. 

I can add a config option to allow you to specify the name of the header, or you can just turn off "Enable Http Proxy" as it works ok on both apache and nginx without it. Do we even need "Enable Http Proxy" or should I just remove it and default to False?

I don't know if we can detect automatically which reverse proxy server is in use, or how headphones gets around it, as their code is pretty much the same. I also don't understand why it's an intermittent problem, you would think it would always fail. I found this on stackoverflow...
https://stackoverflow.com/questions/20729678/cherrypy-httpredirect-redirects-to-ip-instead-of-hostname-using-abs-path

**Comment by barbequesauce** [comment]
Your initial statement makes sense - if proxy_redirect is off in nginx, it will not add in the X-Forwarded-Host header. I haven't found a specific bit of documentation that indicates why nginx might be swapping back and forth between the two proxy_redirect lines, but it sure *feels* like that is the problem we're seeing here.

That said, I wouldn't recommend removing components that easily - I think that's asking for trouble in a minor release. Saving that for a major release makes sense to me...

**Comment by Dulanic** [comment]
Same issue here, my buttons like to redirect to 127.0.0.1. Same setup here.

**Comment by barbequesauce** [comment]
Can you post your config to a gist or pastebin please?

**Comment by Dulanic** [comment]
I have done it /w host populated and without.

https://pastebin.com/WHeN1aet

**Comment by philborman** [comment]
The problem is line 35 in your config,
http_proxy = 1
Turn this off in config, save config, restart lazylibrarian and all should be ok.
In lazylibrarian config page, Interface tab, it's the tickbox labelled "Enable http proxy"

**Comment by Dulanic** [comment]
Yeah, I only turned that on after I saw the issue... same issue /w this:

https://pastebin.com/ArzpUZ3F

**Comment by philborman** [comment]
Did you restart lazylibrarian after changing config? The cherrypy webserver needs to restart to get the new http_proxy setting.  That setting tells cherrypy to use the address passed in by the proxy server, and if there is no proxy server it defaults to 127.0.0.1

**Comment by Dulanic** [comment]
More than, I wiped the docker container and created a new one.

**Comment by philborman** [comment]
Might be docker related? @santino405 is also using a docker container. 
Which docker image, is the docker image up to date, is lazylibrarian version current? 
I just tried the docker image linked on the lazylibrarian git page, did the internal update to current, and all seems to work as expected. If we can narrow down what's different we might be able to help more.
What operating system are you on, is it possible to run a git or zip version of lazylibrarian on your machine to see if the problem is still there outside docker?

**Comment by Dulanic** [comment]
Same issue installed without docker. It works on the server itself, but if I connect from another PC, when I click buttons it switches to 127.0.0.1.

**Comment by philborman** [comment]
ok, found it.
I downloaded mate 16.04 for my raspberry pi and watched it fall over straight away.
Problem seems to be when the config.ini file is missing, the webserver gets the wrong startup value for http_proxy. I will get a fix out later today.

**Comment by Dulanic** [comment]
Fix works great. Thanks!
