### ISSUE TITLE
Error when viewing history

### ISSUE THREAD

**Issue by wizzy99** [DobyTang/LazyLibrarian#1026]
Current Version: 97f5ecf37277dbeddca40593bc4a1f325c399f17
Running on fc26

Click on history and immediately get an error.  Nothing gets written to the debug log, but this shows in the browser:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/path/userYYY/LazyLibrarian/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/path/userYYY/LazyLibrarian/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/path/userYYY/LazyLibrarian/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/path/userYYY/LazyLibrarian/lazylibrarian/webServe.py", line 2658, in history
    title = title.replace('.', ' ')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by philborman** [comment]
Well that's interesting. Looks like you downloaded something without a title, shouldn't happen. I'm guessing it might be a corrupt database?  Are you OK with using the api?  If so the api command getHistory will dump the  info that the webpage is trying to show. I can easily trap the entry with the missing title, but is the rest of the data correct...

**Comment by wizzy99** [comment]
Actually looks like there are 12 in history with missing titles.  All of the dates are from January, but this just started happening recently (sometime in the last 2-3 weeks).  I truncated the last couple of columns from this paste.

Status | DownloadID | BookID | Source | NZBmode | AuxInfo | NZBdate | NZBtitle | NZBsize
Processed |   | 202748 |   |   |   | 2017-01-02 15:42:44 |   |  
Processed |   | 13367202 |   |   |   | 2017-01-02 15:42:51 |   |  
Failed |   |   |   |   |   | 2017-01-02 15:43:19 |   |  
Failed |   |   |   |   |   | 2017-01-02 15:43:49 |   |  
Failed |   |   |   |   |   | 2017-01-02 15:44:07 |   |  
Processed |   | 372713 |   |   |   | 2017-01-16 12:58:37 |   |  
Processed |   | 68098 |   |   |   | 2017-01-16 12:58:45 |   |  
Processed |   | 68095 |   |   |   | 2017-01-16 12:59:07 |   |  
Processed |   | 71679 |   |   |   | 2017-01-16 12:59:15 |   |  
Processed |   | 71675 |   |   |   | 2017-01-16 12:59:36 |   |  
Processed |   | 48323 |   |   |   | 2017-01-16 12:59:44 |   |  
Failed |   |   |   |   |   | 2017-01-16 13:00:07 |   |

**Comment by philborman** [comment]
Ok thanks. Not sure how it happened, but there are no more reports of this issue.  Rather than patch lazylibrarian it might be simplest just to delete those entries from your database and tackle it if it happens again. A one line sqlite command will do it... 
sqlite3 lazylibrarian.db 
delete from wanted where NZBtitle is None;
Capital N on None, semicolon on end

**Comment by wizzy99** [comment]
Had to replace None with Null, but all good now. Thanks!
