### ISSUE TITLE
Post Processing Error after Torrent download

### ISSUE THREAD

**Issue by mmwaveguy** [DobyTang/LazyLibrarian#1027]
Torrent file download post processing fails - please help

api:  Goodreads
.git install - most current commit as of today
Current Version: 97f5ecf37277dbeddca40593bc4a1f325c399f17

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1296511/debug.zip)

**Comment by philborman** [comment]
Problem is the long dash characters in the filename. 
Transmission renamed the file from
[Linux Format UK  Issue 226  August 2017] to [Linux Format UK – Issue 226 – August 2017]
where the long dash is not just a simple minus character, so doesn't fit the ascii character set.

I will have to think about the best way to fix it properly, I'm thinking maybe don't rename?

Simple fix for now is to rename the file outside lazylibrarian removing the long dash character and then run postprocess again

**Comment by mmwaveguy** [comment]
OK thanks!

**Comment by philborman** [comment]
This is quite interesting. I've been looking into the error and what to do about it, and I can't reproduce it here at all. The same command here, using the same filename, works fine. It's either a difference between linux and freebsd, or a difference between python versions (I am on 2.7.13, you are on 2.7.9)
The command that fails is os.path.isfile(name)  which complains it can't convert the filename from utf-8 to ascii.

On linux it doesn't try to convert it to ascii as the filename is allowed to remain utf-8, maybe freebsd is different, or the filesystem you use is different?  (I use ext3 on linux)

I can't downgrade my python to 2.7.9 but python 2.7.13 is available for freebsd, which might solve the problem?  Might be worth a try.
