### ISSUE TITLE
Check update fails

### ISSUE THREAD

**Issue by JoeB99** [DobyTang/LazyLibrarian#1028]
FreeNAS 11-U3

Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 97f5ecf37277dbeddca40593bc4a1f325c399f17 : Latest Version: 97f5ecf37277dbeddca40593bc4a1f325c399f17

When clicking the "Check update" button, the following is displayed:
**
Error !

TopLevelLookupException: Cant locate template for uri 'response.html'

return self._load(srcfile, uri) else: raise exceptions.TopLevelLookupException( "Cant locate template for uri %r" % uri) def adjust_uri(self, uri, relativeto): """Adjust the given ``uri`` based on the given relative URI.""" key = (uri, relativeto)
/usr/local/LazyLibrarian/mako/lookup.py, line 259:
"Cant locate template for uri %r" % uri)
/usr/local/LazyLibrarian/lazylibrarian/webServe.py, line 72:
template = _hplookup.get_template(templatename)
**

**Comment by JoeB99** [comment]
Edit: Works as expected with BookStrap interface selected.

**Comment by philborman** [comment]
Ah, that's me being stupid. The default interface is missing a file. response.html and shutdown.html are the same for the default interface, but it needs two copies as they are different files under the bookstrap interface. I have just pushed a fix. Thanks for the bug report.
