### ISSUE TITLE
Author name - the same but different

### ISSUE THREAD

**Issue by DobyTang** [DobyTang/LazyLibrarian#103]
Noticed for one of my authors J. V. Jones, there are 3 different presentations available found so far
J V Jones
J. V. Jones
J.V. Jones

with all 3 having books listed, some similar some unique per author name.

Thoughts regarding putting some form of standardisation/safety on the name to improve matching - eg removing all non alpha numeric characters would give us J V Jones for all 3
or do we need author linking so that a single author id has mutliple id's associated so a single name displays all relevant (matched by user of course).

Thoughts?

**Comment by philborman** [comment]
How about an 'alias' or 'aka' field in authors table. I hit the same problem with James Lovelock vs James E. Lovelock

where googlebooks handles it differently to goodreads. Any suggestions?
we need to avoid un-necessary duplicates of "same book, different author name"

**Comment by tymanthius** [comment]
Yea - I've seen the same issue with Robert Heinlein, Robert A Heinlein, Robert Anson Heinlein.  Sigh.

**Comment by philborman** [comment]
You can work around it in current LazyLibrarian if you manually edit the 
metadata.opf files. Haven't thought up a good way of automating it yet.

It only works if the author you want is in the library in the name 
format you want, (eg Robert A Heinlein)
and that author name has the books showing as attributed to them.

Easiest way to do it is...
1. Move the offending book folders out of your library to somewhere safe
2. Do a "full" library-scan so LL notices they are missing.
3. Modify the offending books opf files.
     You can edit the author name in the metadata files for books you 
have by
     Robert Heinlein and Robert Anson Heinlein (metadata.opf are plain 
text files).
4. Put the book folders back into the library
5. Do another library-scan

they now all get attributed to Robert A Heinlein   !-result-!

On a library scan, LazyLibrarian reads metadata from the book files 
first, then allows the metadata file to override author/title/language. 
Easier to edit the metadata than mess around inside the book itself.

Phil.

**Comment by philborman** [comment]
Current release has book data editing to let you assign the books to a new author. Has to be done per-book, no bulk editing feature yet. I'm marking this closed for now. If bulk editing is needed, it can be done  external to LL using the api, or re-open the ticket and I'll have another look.
