### ISSUE TITLE
Feature Request: Manual search & download

### ISSUE THREAD

**Issue by osinfield** [DobyTang/LazyLibrarian#1031]
Would it be possible to add the ability to manually search and select a download for a book? Sometimes, the book title slightly differs or is much shorter/longer than the full torrent name and so it lowers the match percentage to below thresholds.

**Comment by philborman** [comment]
Already there, each book title has a "manual" button under it's title. You can click on that to search using title, author, or both, and select the best match yourself

**Comment by osinfield** [comment]
@philborman not seeing that option, on either the default or bookstrap theme. Is it only available on certain views? https://imgur.com/a/XHa69

**Comment by philborman** [comment]
Should be there on the ebook page and each authors book list, see screenshots in the wiki. If not there, something is broken :-)

**Comment by osinfield** [comment]
@philborman something broken on my end? What should I be checking?

**Comment by philborman** [comment]
No its a bug in the lazylibrarian webserver. Im away until Wednesday, will push a fix when I get back
