### ISSUE TITLE
Feature Request: Import lists from GoodReads

### ISSUE THREAD

**Issue by osinfield** [DobyTang/LazyLibrarian#1032]
Would be great if we could import lists from GoodReads. I have friends who add books they want to read to a public list I've created and it would save lots of time if I could import directly into LL. Also would great for grabbing other public lists, like "New York Times Best Sellers 2016".

Would be awesome if you could schedule imports for specific lists too!

**Comment by philborman** [comment]
You can import rss feeds from goodreads or use goodreads csv files, details are in the lazylibrarian wiki. No schedule system though.

**Comment by philborman** [comment]
New version now also allows a Goodreads Listopia page to be used as a wishlist. Monitored regularly like an rss feed. Only tested with a couple of public lists so far, untried with private lists. Feedback would be appreciated.

**Comment by osinfield** [comment]
@philborman how do I add a list? Can't seem to see an option to after upgrading.

**Comment by philborman** [comment]
We treat the lists as a type of rss feed, so put something like this in an rss box...
https://www.goodreads.com/list/show/43.Best_Young_Adult_Books

**Comment by osinfield** [comment]
@philborman seems to be working great, thanks! What's a safe limit on how many books in a single list to import? I imagine a list like this could cause problems! https://www.goodreads.com/list/show/1.Best_Books_Ever

**Comment by philborman** [comment]
At the moment we only monitor the first page of each list, so max 100 books. I haven't added multiple page support to the goodreads list routine, but do you want more than the top 100 in a list ?  It's probably a bit like the music charts, the ones lower down the list are either new or aren't that good, but as they get more popular they rise up the list.

The book search routines that return multiple pages have a configurable page limit because the results come back in no particular order. It would be fairly easy to add that same code to the goodreads lists, but is it useful...

**Comment by mccorkled** [comment]
Can you give very specific details on how to get the OAuth working? GoodReads is known for merging lists that people make which defeats the purpose of having my own list. I opened the OAuth py but do not know hat to do with it. I tried to place my key and secret key in various spots within the OAuth py but I cannot get anything to come of it. I just want "My Books" to auto sync. 

Thank you.

**Comment by philborman** [comment]
You don't add anything into the file, you just run the file from the command line, passing your api and secret as parameters to it. For example on my linux box I would open a terminal and do...
python /opt/LazyLibrarian/goodreads_auth.py 123456789  987654321
where my api is 123456789
and my secret is 987654321
(not my real keys!)

This will then print out a link to a web page and wait for a keypress.  
Open the web page in a browser, there is a button there to click to authorise lazylibrarian.
Once you have clicked the button, go back to the terminal and answer 'y' to the prompt.
The terminal will then print out your goodreads oauth token and secret.
Enter these in lazylibrarian config.

I have not documented this as it's hopefully a temporary solution. I hope to integrate it into lazylibrarian but have not managed to do so yet :-)

**Comment by osinfield** [comment]
@philborman optional multiple page support be awesome (per feed?), as I don't want to have to manually edit the book list that I use to gather "requests" from friends, trying to figure out which ones have been added already, etc.

**Comment by mccorkled** [comment]
I did what you suggested and nothing happened. 
![1](https://user-images.githubusercontent.com/13697804/30876709-682a1b9c-a2c5-11e7-9fdc-f869b0bcf9b6.png)

**Comment by philborman** [comment]
@mccorkled  you are not in a terminal there. That is the terminal output from lazylibrarian, not the same thing.
Do you know how to ssh into your synology box?  And the directory where lazylibrarian is installed?

**Comment by philborman** [comment]
@osinfield not sure what you mean. Do you want LL to upload a list to goodreads? At the moment we only read lists, not write to them. We handle ones that already exist in LL, so after the first run we just pick up changes.

**Comment by mccorkled** [comment]
I have before and screwed some things up. I don't want to mess with that again haha. I guess I will just have to be patient until you can get the OAuth working in the GUI. I'm anxious to start getting some books ;)

Thanks.

**Comment by philborman** [comment]
The Priority setting for rss feed is ignored if it's a watchlist, so this changes to Pages in the new version. Default is zero, load all pages, otherwise set to 1 for only the first page (100 books) or 2 for 2 pages, etc. If you set it to too low a value and there are still more pages available you get a warning message in the log. Just needs a bit more testing, should post it tonight.

**Comment by philborman** [comment]
Deleted some comments not relevant to this issue. Can't see how to split them into a separate issue.

**Comment by osinfield** [comment]
@philborman Great work on adding the ability for pagination!

As for my earlier suggestion of having LL update a GoodReads list, don't worry about it - I was thinking that if LL could remove a book from a GR list once it's been added to LL, it would act as a simple & easy to use request system.

**Comment by philborman** [comment]
You don't need to remove the book from the GR list, LL will ignore books already processed.
