### ISSUE TITLE
Feature Request: Delete Providers

### ISSUE THREAD

**Issue by mccorkled** [DobyTang/LazyLibrarian#1034]
I have added a ton of torrent and usenet providers. I have decided to only use a couple of them and now my screen is super cluttered. It would be great to be able to delete providers from the list. I though that unchecking the box and removing the provider details would do this but it was not the case. 

Thank you.

**Comment by philborman** [comment]
At the moment you can only do it by editing the config.ini (while lazylibrarian is NOT running). Would be a useful addition though, and not too hard to do, I think...   Maybe wa can do it automatically every time the config changes? I will take a look.

**Comment by mccorkled** [comment]
Thank you. This would be very convenient.

**Comment by philborman** [comment]
Got a version here working ok, just need to test it a bit more before release. When it saves the config out it strips empty slots and reorders the ones that are left.

**Comment by mccorkled** [comment]
Sounds good!
