### ISSUE TITLE
Usenet-Crawler Not Working

### ISSUE THREAD

**Issue by mccorkled** [DobyTang/LazyLibrarian#1035]
I am using this provider for shows and movies just fine. When I add it to my list of searchers I get an error in the log that no provider is selected.

https://pastebin.com/SDJkrw8b

Thank you.

**Comment by philborman** [comment]
Looks as though the provider is blocked ?
If there was an error on an earlier search ( eg daily limit reached, site is down ) we block the provider for an hour so we don't keep trying. Check your blocklist, there is a button on the end of config->providers page

**Comment by mccorkled** [comment]
Interesting. Apparently that was the issue because this morning they were all snatched. 

Thank you!

**Comment by philborman** [comment]
Not sure, it looks as though sab isn't talking to usenet crawler, or at least usenet crawler isn't replying. Could be you hit your usenet crawler download limit? Some only allow a limited number of downloads per day, or a maximum number of simultaneous downloads. Could also be your usenet crawler credentials, worth double checking.
Eventually lazylibrarian will realise they haven't appeared in the downloads directory and ask sab to cancel them.
