### ISSUE TITLE
Feature Request: Telegram notification

### ISSUE THREAD

**Issue by zuperjotmeil** [DobyTang/LazyLibrarian#1036]
Please add Telegram notifications support

**Comment by philborman** [comment]
I don't use telegram myself, but if you don't mind doing a bit of testing it doesn't look too hard to implement. We can more or less cut and paste the headphones telegram notifier.

**Comment by zuperjotmeil** [comment]
Here is the module, but I don't get to integrate it. There are different approach as used here.

[https://github.com/SickRage/SickRage/blob/master/sickbeard/notifiers/telegram.py](url)

**Comment by philborman** [comment]
There is a version in my git with telegram notifier, untested, obviously.
https://github.com/philborman/LazyLibrarian.git
Can you download that one, turn debug logging on, fill in your telegram token and userid and try the "test" button

**Comment by philborman** [comment]
Tested now, working ok.

**Comment by zuperjotmeil** [comment]
Great work and fast... thanks
