### ISSUE TITLE
Feature Request: File Renamer

### ISSUE THREAD

**Issue by nitrag** [DobyTang/LazyLibrarian#1039]
Expectation: Books which are recognized, but horribly named on the filesystem (my fault) get restructured to proper format Author/Title/Title (or whichever is the standard).

**Comment by philborman** [comment]
Nice idea, easy to do, but would need to be switchable. Problems will occur if you share books with another program (eg calibre) as both need to have the same name. Calibre renames books to it's preferred pattern, we just keep the filename in our database.

**Comment by nitrag** [comment]
What do you mean by "switchable"? This option would be like a force-rename to standardize the format before importing into other programs.

My problem is LazyLibrarian can identify some of my books but the format is different for each book. Would be nice to automatically fix the format to whatever preferred pattern since it knows the correct file/track/names/etc. Oh and update IDv3 tags too if possible.

**Comment by philborman** [comment]
Switchable in the sense that you can turn it off. We already force a rename on files we download ourselves, but if the files are not ours, ie a library scan of existing books, we don't force a rename. Lots of users have books in calibre libraries, calibre also renames its books. Two programs renaming the same books is asking for trouble, so you need to be able to turn off lazylibrarian renaming if using calibre.

Audiobook renaming is also tricky, there doesn't seem to be a standard format. We just rely on the directory name, which we control. The files within that are not renamed, and Id3  tags are used to get info for our database. Could be improved, but at the moment we don't modify any files, only database entries and filenames. Any embedded metadata in ebooks or audiobooks is treated as read only. Ebooks have metadata written to an opf file, which is easily modified.  could maybe do the same for audiobooks?

**Comment by philborman** [comment]
New version has a switch in config to rename existing books on libraryscan. Only ebooks, and only renames the files, not the directory. It won't rename the files if it thinks the directory is shared with calibre. Will probably push the new version tonight, just testing a few other changes first.

**Comment by nitrag** [comment]
Instead on libraryscan, can you make it more forceful? How about in the `Mark selected as [Rename]  Go` dropdown?

**Comment by philborman** [comment]
Could do, means you manually have to select them though, current method is automatic

**Comment by nitrag** [comment]
Up to you, you were worried about people having their stuff overwritten. I noticed you mentioned eBooks above. Will this apply to Audiobooks as well, or will that take extra work due to the multiple-file nature?

**Comment by philborman** [comment]
The calibre issue is that if we rename a book that's also in a calibre database, calibre won't be able to find it. If we rename the book and then tell calibre to update it's database, calibre will change the name back to it's preferred format and then we can't find it.  I can work around it if I don't let lazylibrarian rename books that are in a calibre style directory. 

It would be fairly easy to add to the "Mark selected as [Rename] Go dropdown" now that it's working in libraryscan so we can have both manual and automatic options, maybe if you tick the box to rename a book we ignore the calibre check? However we don't display the filename anywhere. How do you know which books you need to tick? 

I had a quick look at writing new metadata out - not easy. None of the libraries we currently use for epub/mobi/pdf/id3 can write metadata, they are all read only. I think it's probably best to keep it that way, as if we should mismatch the book or corrupt the original file writing metadata to it there is no going back. 

Audiobooks are not much more complex than ebooks, as long as we can pick up the various parts in the right order, so either the metadata needs to be 100% or the filenames need to be clear enough.

**Comment by nitrag** [comment]
id3 can rewrite id3v1-2 tags. But I'm assuming you mean metadata in the sense the ffmpeg/ffprobe uses?

In my recent organization I've seen many different formats for the ID3 "Track" `Chapter 01`, `Chapter 9`, `6`, `Track 7/22`, etc).

There would also probably need to be an additional check: "Ok there are 50 files, and I've identified the Track `count` (1-50) exist.

To make sure we are on the same page, I think 
1) LL is able to identify the Book using it's existing methods, which are great!
2) LL identifies that the folder structure is incorrect, and does a simple `cp+rm` (can't `mv` if author folder already exists) to:
```
\Root\AuthorFirst AuthorLast\Book Title\[Files]
```
3) [Question]: If you can identify the book in LL already, can't you standardize the ID3 tags? Keeping in mind the "Track" dilemma mentioned above? If so, it should be done here.
4) LL identifies the files are in some whacky format (`01 - Book - Chapter 22.mp3`, `Book-Part03.mp3`, etc.), then uses ID3 tags to build the appropriate file name, whichever that might be.

I agree it's pretty complex. I'm doing it manually right now and it's a pain, and I'm not 100% sure it's easily automated. I agree the metadata needs to be spot on. I'm kinda learning new roadblocks along the way.

**Comment by philborman** [comment]
The id3 library we use on lazylibrarian is id3reader.py (which is read only) but it could be upgraded to a read/write one. We currently create a folder structure using the "AudioBook Foldername Pattern" setting in config for audiobooks that we download, but not for ones already on your system or downloaded outside lazylibrarian. We don't rename any of the files for the reasons you outline in (4) above. We could create an entry in config for audiobooks like the "eBook Filename Pattern" that would allow you to use variables like $author $title $track to build your filename ?

**Comment by philborman** [comment]
It's quite tricky to pick the chapter/part numbers automatically, here are a few examples from my library.
Some have more than one number in the name, some have part x of y, the number next to the .mp3 is not always the one  you want...

RRAM01-22 Robert Rankin - Armageddon The Musical.mp3
Mussolini, His Part In My Downfall Pt 1.mp3
06 - Goodbye Soldier/Goodbye Soldier 01 of 12.mp3
02 - Rommel Gunner Who/Rommel - Gunner Who 1.mp3
The Good, the Bad and the Smug (Unabridged) - 001.mp3
The Hobbit - Chapter 1 - An Unexpected Party - 01 of 219.mp3
01 Primary Phase - Episode 01.mp3
dirkgently01.mp3

**Comment by philborman** [comment]
Just playing with a new version that has audiobook renaming. Are you up for some testing? I only have a small number of audiobooks to try.

The test version doesn't actually rename anything, just reports what it would do if enabled.

**Comment by nitrag** [comment]
Yea sure. You got it pushed up to a branch?

**Comment by philborman** [comment]
It's in my repo...
https://github.com/philborman/LazyLibrarian.git
There are two options in config->processing to check. There is a filename pattern, and a toggle Rename existing books - text just says ebooks currently but it does both.
If you run with debug log on, lines in the log containing audioRename are the interesting ones.
It will report if it can't rename (inconsistent info, missing parts)
and will report what it would rename from and to

**Comment by nitrag** [comment]
```
Oct-2017 22:28:25 - INFO :: AUDIO_SCAN : gr.py:find_book:888 : Articles on Novels by Robert Ludlum, Including by Hephaestus Books added to the books database
02-Oct-2017 22:28:26 - ERROR :: AUDIO_SCAN : librarysync.py:LibraryScan:917 : Unhandled exception in libraryScan: Traceback (most recent call last):
  File "/tmp/LazyLibrarian/lazylibrarian/librarysync.py", line 764, in LibraryScan
    book_filename = audioRename(bookid)
  File "/tmp/LazyLibrarian/lazylibrarian/bookwork.py", line 69, in audioRename
    if '/' in track:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by philborman** [comment]
Good catch, audiofile with no track counter in it's id3
Should be trapped now.

**Comment by nitrag** [comment]
How do I run manually? It's not doing anything.

**Comment by philborman** [comment]
Upgrade to latest on my git and run libraryscan again.

**Comment by philborman** [comment]
Seems to be working ok, closing this for now
