### ISSUE TITLE
Set Audiobooks as primary

### ISSUE THREAD

**Issue by germaguire** [DobyTang/LazyLibrarian#1045]
Hi, I was wondering if there is an easy way to set the library to be focused on audiobook instead of ebooks ? I assume that setting the file ext and search category to mp3 and 3030 in the ebooks field will allow the app to do the same thing but is there a different way ?

Main reason is that its very hard to search and add books from a series for example as it default adds book as an ebook and audiobooks have to be individualy added explicitly.

Great work on LazyLibriarian and thanks for all the hard work !

Ger.

**Comment by philborman** [comment]
Are you using the bookstrap interface? It has a built in audiobook mode.
The reason ebooks are the main focus is that the providers we use (goodreads/googlebooks) work that way. The Series page has a "mark selected as" dropdown which is currently ebook only. Could be upgraded to have an audiobook option. I will have a look.

**Comment by philborman** [comment]
Latest version allows you to set status for audiobooks in the series page
