### ISSUE TITLE
Issue: GoodReads Sync

### ISSUE THREAD

**Issue by mccorkled** [DobyTang/LazyLibrarian#1047]
I would like to first say thank you for implementing this. I ran the OAuth today and it went super smoothly. The issue I am having is that the Sync doesn't appear to be working. When I click Goodreads Sync I get the message that...

"Goodreads Sync is already running"

There is nothing in the log about Sync. The log only shows the manual search I did as well as the snatching and post processing. 

Thanks.

**Comment by philborman** [comment]
When a sync task starts, it gives itself a name so we can identify it. When you start a new task it check if another task with the same name  already exists and prints that message if it finds one.

I would try restarting lazylibrarian, turn debug logging on (with refresh in one window, then run the sync task from another window and watch the log.

**Comment by philborman** [comment]
There are changes in the new version to the way the threading/name_checking code works, an upgrade to latest version should help. Problem may have been the scheduled task and the on-demand button both trying to run at the same time.

**Comment by mccorkled** [comment]
The update fixed the issue. You're too dang good. ;D
