### ISSUE TITLE
LL not updating "Untitled" books when title is added in GoodReads

### ISSUE THREAD

**Issue by wizzy99** [DobyTang/LazyLibrarian#1049]
To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Often a new book is added to GoodReads with a title of "Untitled".  When the real title is added, LL doesn't update the title.  The log shows:

02-Oct-2017 10:08:32 - DEBUG   :: REFRESHAUTHOR : gr.py:get_author_books:442 : Book URL: http://www.goodreads.com/book/show?id=NUMBER&key=XXXXXX
02-Oct-2017 10:08:33 - DEBUG   :: REFRESHAUTHOR : cache.py:get_cached_request:166 : CacheHandler: Storing XML for http://www.goodreads.com/book/show?id=NUMBER&key=XXXXXX
02-Oct-2017 10:08:33 - DEBUG   :: REFRESHAUTHOR : gr.py:get_author_books:490 : GR language: eng
02-Oct-2017 10:08:33 - DEBUG   :: REFRESHAUTHOR : gr.py:get_author_books:592 : Rejecting bookid NUMBER for [Author][Correct Title] already got bookid for [Author][Untitled]

**Comment by philborman** [comment]
Interesting, didn't know they did that.

Sometimes goodreads has the same bookid but slightly different spellings for book titles
or has the same bookid/title  with different authors/pen names
and we need the bookid to be unique, which is why we check.
Is it always "Untitled", if so it's easy enough to treat that as a special case.

**Comment by wizzy99** [comment]
Untitled seems to be the standard convention.

https://www.goodreads.com/search?q=untitled

**Comment by philborman** [comment]
Ok, just added some code to do that. Hopefully will sort it, but it's untested at the moment (I don't have any untitled books)

**Comment by wizzy99** [comment]
I've only tried one example, but looks good.  Thanks for the quick turnaround.

02-Oct-2017 14:19:16 - DEBUG   :: REFRESHAUTHOR : gr.py:get_author_books:592 : Renaming bookid NUMBER for [Author][Untitled] to [RealTitle]
