### ISSUE TITLE
Upcoming GoodReads Error...???

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1051]
To better protect user privacy and security, we will be enabling HTTP to HTTPS redirection for all requests to goodreads.com on December 4th.

To prevent your applications from breaking, please do one of the following before December 4th:

Make sure your applications support HTTPS redirects
Update your applications to make only HTTPS requests
If you have any questions, please post in the developer forum.

Best,
Goodreads

**Comment by philborman** [comment]
Already done, but may cause problems with some older nas devices that don't have working https. Should be included in the next release.
