### ISSUE TITLE
Problem with MAM & Jackett

### ISSUE THREAD

**Issue by osinfield** [DobyTang/LazyLibrarian#1056]
Trying to use Jackett to download from MyAnonaMouse but getting the following error in the logs

```
[NewzNabPlus] URL = http://HIDDEN:8086/api/v2.0/indexers/myanonamouse/results/torznab/api?author=Ta-Nehisi+Coates&apikey=HIDDEN&t=book&cat=8000%2C8010&title=We+Were+Eight+Years+in+Power
Error reading data from http://HIDDEN:8086/api/v2.0/indexers/myanonamouse/results/torznab/: Exception reason Bad Request
```
Category is set to load values from provider, should I be setting anything manually?

**Comment by philborman** [comment]
What do you have as your jackett/torznab entry in lazylibrarian config as your log entry looks very different to mine. I don't have a working MAM account to test at the moment (lapsed) but jackett runs by default on port 9117 and the lazylibrarian config entry would look like http://192.168.0.1:9117/torznab/myanonamouse (link supplied by "copy torznab feed" button in jackett)
My log entry then shows [NewzNabPlus] URL = http://192.168.0.1:9117/torznab/myanonamouse/api?author=Mega+Recipes&apikey=<apikey>&t=book&cat=8000%2C8010&title=Beer+Home+Brewing

**Comment by osinfield** [comment]
I have Jackett v0.8.246.0 running on port 8086 and it works fine with other sites/apps. Here's the entry in the config (I copied the Torznab feed link from Jackett and pasted into LL config - are you using an older version and therefore not getting a "v2.0" link to Jackett's API?)

`http://HIDDEN:8086/api/v2.0/indexers/myanonamouse/results/torznab`

**Comment by philborman** [comment]
Yes, I'm on Jackett Version 0.7.1146.0
I will try upgrading and see if I can reproduce the problem. If there are api changes that could be it.

**Comment by philborman** [comment]
Upgraded to Jackett Version 0.8.249.0 and seems to be behaving the same here, getting the v2 api link but still working as expected. What happens if you try the http link in a browser? Should return some xml. I can't find any documentation on the jackett v2 api so I'm a bit in the dark. If it's a bad request, why? What's bad about it.  If the first link fails
http://HIDDEN:8086/api/v2.0/indexers/myanonamouse/results/torznab/api?author=Ta-Nehisi+Coates&apikey=HIDDEN&t=book&cat=8000%2C8010&title=We+Were+Eight+Years+in+Power try 
http://HIDDEN:8086/api/v2.0/indexers/myanonamouse/results/torznab/api?q=Ta-Nehisi+Coates+We+Were+Eight+Years+in+Power&apikey=HIDDEN&t=book&cat=8000%2C8010
which bypasses the "book" search and uses a "general" one.

**Comment by osinfield** [comment]
@philborman both links return -
```
<Error>
<Message>myanonamouse does not support the requested query.</Message>
</Error>
```
However if I manually take out "&t=book" from the URL I get a response with search results. Interestingly, the 1st link doesn't give me the right book in search results but the 2nd one does!

**Comment by philborman** [comment]
Ok, if you go into lazylibrarian config, categories, find myanonamous and clear the "Book Search" field it should get myanonamous working. Tick the box to prevent reloading config, and save config.

I've not had any luck yet finding documentation on the jackett v2 api

**Comment by osinfield** [comment]
@philborman that did the trick, thanks!!

**Comment by philborman** [comment]
Looks like mam doesn't do book search? I'm fairly sure it used to when I had an account?
Next version should disable this automatically by checking for the "bad request" message.
The other providers that don't do book search all return different messages, 'no such function', 'unknown parameter', 'unknown function', 'incorrect parameter'. Don't you just love standards ;-)

**Comment by seanvree** [comment]
just FYI, I'm having the same issue with API v2 as well.

**Comment by philborman** [comment]
Not sure if it's a bug in the v2 api, or Mam doesn't support t=book  I'm fairly sure it used to support it. The solution at least for now is to disable book search for MAM in lazylibrarian config which will force lazylibrarian to use a general search.

**Comment by samkatakouzinos** [comment]
https://github.com/DobyTang/LazyLibrarian/issues/1056#issuecomment-334273558; Thank you! Clearing the 'Book Search' field has resolved my LazyLibrarian receiving 400 Bad Request from its local Jackett server and its indexers.
