### ISSUE TITLE
Error in magazine search...

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1058]
Unhandled exception in search_magazines: Traceback (most recent call last): File "Z:\Applications\lazylibrarian\lazylibrarian\searchmag.py", line 431, in search_magazines comp_date = datecompare(newdatish, control_date) File "Z:\Applications\lazylibrarian\lazylibrarian\formatter.py", line 189, in datecompare date2 = datetime.date(y2, m2, d2) ValueError: day is out of range for month
--

**Comment by philborman** [comment]
Ok thanks, fixed now. New version out in a few hours, just working on some other bits.
