### ISSUE TITLE
LL will not PP books in sub DIR of download dirctory

### ISSUE THREAD

**Issue by seanvree** [DobyTang/LazyLibrarian#1059]
LL ver:  Current Version: aecfb700d43edaa2638ff0804bf63ec26605399b 
OS:  Windows 10E x67 1703
Interface: Bookstrap
API: both
Install:  GIT

ISSUE:

When post-processing, LL will not "drill down" beyond the root download DIR.  So if the download client puts files in a sub directory, LL doesn't find files. 

Example:

Deluge;

LL Download DIr:  c:\media\plexdownloads\books\

Torrent is downloaded and placed in c:\media\plexdownloads\books\torrentname\book

However, but because the download client puts the files in a torrent sub dir within the download DIR, LL doesn't find the files. 

From the example below, deluge downloaded the files to "c:\PlexDownloads\books\Stephen R. Covey\The 7 Habits Of Highly Effective People (98)"  So I had to take the files from that sub dir and place in "c:\PlexDownloads\books\Stephen R. Covey\" and only did it then find the files. 

So essentially, we need LL to look for files in the sub dir AND all child sub dirs below the download dir. 

logs:

```
Oct 06 04:20:43 LazyLibrarian lazylibrarian.log:  06-Oct-2017 04:20:42 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:242 : Stephen R. Covey was sent to DELUGERPC
Oct 06 04:20:43 LazyLibrarian lazylibrarian.log:  06-Oct-2017 04:20:43 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:291 : Looking for eBook Stephen R. Covey in C:\Media\PlexDownloads\Books\
Oct 06 04:20:43 LazyLibrarian lazylibrarian.log:  06-Oct-2017 04:20:43 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:363 : Found folder (100%) [C:\Media\PlexDownloads\Books\Stephen R. Covey] for eBook Stephen R. Covey
Oct 06 04:20:43 LazyLibrarian lazylibrarian.log:  06-Oct-2017 04:20:43 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:366 : Skipping C:\Media\PlexDownloads\Books\Stephen R. Covey, no ebook found
Oct 06 04:20:43 LazyLibrarian lazylibrarian.log:  06-Oct-2017 04:20:43 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:453 : Snatched torznab Stephen R. Covey is not in download directory
```

**Comment by philborman** [comment]
Sort of intentional in case the download contains multiple books. I've had occasions where an entire authors back catalog was in the download, each book in separate subdirectories, and you might actually want more than one of the authors books. If lazylibrarian processed the download it would grab one book and then delete the rest. Rewriting the postprocessor to get around that is non trivial, so I took the easy way out and decided to leave it for manual processing. Postprocessor could definitely be much smarter than it is.

**Comment by seanvree** [comment]
@philborman .   Ahh gotcha.  Humm....trying to figure out a way around this!

Anyway, thanks for the hard work and explanation!
