### ISSUE TITLE
Won't load KAT match to uTorrent...

### ISSUE THREAD

**Issue by richbutler1** [DobyTang/LazyLibrarian#106]
Trying torrent method.  I have same setup info in Headphones, works perfectly for uTorrent.  I check log and see a KAT match.  "Found Torrent:..."  then nothing happens.  I've tried black hole method as well just putting the drop folder for torrent files, nothing there either.  Any advice or is this verified issue?

**Comment by daktak** [comment]
Blackhole fixed in #118

**Comment by daktak** [comment]
Should be fixed in #118, please try again
