### ISSUE TITLE
Feature Request: Remote Path Mappings

### ISSUE THREAD

**Issue by osinfield** [DobyTang/LazyLibrarian#1060]
I use a remote Seedbox and the download client paths confuse LL as they're not local paths, so I have to rely upon the naming of the file when importing (I run a process which copies the remote files over to a local directory for processing), which is fine for NZBGet as the naming includes the book ID but torrents don't and so often don't get imported.

Sonarr has implemented a way to specify remote > local path mappings, so that they can be used in place of what the download client is providing as a download path, in combination with mounting a remote Seedbox location on the local machine. For example -

Remote
/home/user/files/deluge/complete/tv/

Local
D:\files\deluge\complete\tv\

This way, when LL talks to Deluge and asks what the download path is, the response will be manipulated to point to the mounted D drive location on the local machine instead of looking in /home/user/files/deluge/complete/tv/

Think we could do something similar? And there would need to be the ability to have multiple mappings, so I can specify one path for NZBGet and another for Deluge.

**Comment by philborman** [comment]
We don't currently work that way. Although log says "Deluge: Get torrent folder name", LL only uses the filename, not the path. We expect all files to be in the same download directory specified in lazylibrarian config. Can you not just map your deluge download directory to the location lazylibrarian expects?

**Comment by philborman** [comment]
Actually, thinking about this, you probably only need the postprocessor to be able to look in more than one directory for results? You could then have one (locally mapped) directory for deluge and another for nzbget. That's quite easy to implement, would that work?

**Comment by osinfield** [comment]
@philborman If you could specify for each directory path whether to link/move/copy, then that work great!

**Comment by philborman** [comment]
Latest version allows a list of directories for the postprocessor to look at.
Lazylibrarian will move files unless "keep original files" is set in config, or for torrents if "keep seeding" is set. We don't use links as they are not available on all platforms or between file systems.
