### ISSUE TITLE
Feature Request: Forced Magazine Search For Specific Magazine...Not All Magazines

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1062]
Feature Request: Forced Magazine Search For Specific Magazine...Not All Magazines

I don't always want to force search for all magazines...just one.

**Comment by philborman** [comment]
The "force search" button on each magazines issue page now only searches for that magazine.
The "force search" button on the main magazine page searches for all active magazines.

**Comment by MrMxyzptlk** [comment]
Thank you!
