### ISSUE TITLE
Feature Request: Book reject list 

### ISSUE THREAD

**Issue by surfshack66** [DobyTang/LazyLibrarian#1064]
Currently, the way to reject books is by using a comma separated list of words and the search results with any of these words in the title will be ignored.

However, the site I use does not put ".mp3" or "audiobook" in the title of the book. Therefore, audiobooks are downloaded despite being in the reject books list.

Is it possible to add "type" to reject book list, so we could specify file types to be ignored/rejected?

**Comment by philborman** [comment]
Unfortunately we usually don't know the "type(s)" until we have downloaded the torrent/nzb. The details we get in the search results from the providers are title and sometimes size. You could try filtering on size as audiobooks are huge compared to ebooks. Maybe set an ebook maximum size slightly larger than your largest ebook, audiobooks should be larger than that.

**Comment by surfshack66** [comment]
That solution should work. Thanks!
