### ISSUE TITLE
Update box not visible with Bookstrap theme (all), only with default

### ISSUE THREAD

**Issue by CasperH2O** [DobyTang/LazyLibrarian#1065]
To help with identifying and fixing issues, please include as much information as possible, including:
### Not needed?

Doing a first time LazyLibrarian install/configuration today. I noticed it was complaining that I had to do an update so it knew wich version I had downloaded. However the box in the bottom right on the settings page is not visible unless you choose the Default interface. Needless to say, it took me a while to find that one when using the Bookstrap theme. It does not seem to be part of the regular settings UI?

**Comment by philborman** [comment]
I think it should be automatic, lazylibrarian detects an install from a zip or tar file and forces an upgrade without user intervention? A bit draconian, but I couldn't find another way to tell if the version in a zip/tar is current. Not sure why you get an extra box on the bottom right, can you supply a screenshot?  Also not sure how how you got to the bookstrap interface _before_ lazylibrarian noticed it was an unknown zip installation?

**Comment by CasperH2O** [comment]
Your welcome Phil, glad I could contribute with my small observation. :)

To be clear, with a fresh install the theme is indeed the Default, it was merely the first thing I changed.

**Comment by CasperH2O** [comment]
Seems to be fixed in the latest release with commit 594a395ea85d8ccf147725e2037b1840e0d94cbd. The pop up is shown in Bookstrap for about 15 seconds.

Tested with:  097a5d5. See image.

![afbeelding](https://user-images.githubusercontent.com/14330834/31459818-a073542c-aec4-11e7-8d6e-efe1f4d13c9c.png)

Interesting to note, after hitting update in the dialog box, the actual functionality is not triggered properly. But this is already reported in: #1067.

Closing ticket, thanks Phil!

**Comment by CasperH2O** [comment]
Hey @philborman, not sure what happened but I just downloaded and unzipped the latest rev (due to some other issue with Deluge) and this issue seems to be back again. It's a fresh unzipped unchanged version.

Output during boot:```

Lazylibrarian is starting up...
19-okt-2017 20:57:24 - INFO :: MAIN : __init__.py:initialize:530 : Log level set to [1]- Log Directory is [C:\Users\<username removed>\Desktop\LazyLibrarian-master\Logs] - Config level is [1]
19-okt-2017 20:57:24 - INFO :: MAIN : __init__.py:initialize:536 : Screen Log set to INFO/WARN/ERROR
19-okt-2017 20:57:25 - INFO :: MAIN : __init__.py:config_read:786 : Config file loaded
19-okt-2017 20:57:25 - INFO :: MAIN : __init__.py:initialize:539 : SYS_ENCODING is UTF-8
19-okt-2017 20:57:25 - INFO :: MAIN : __init__.py:initialize:572 : Database is version 0, integrity check: ok
19-okt-2017 20:57:25 - WARNING :: MAIN : __init__.py:initialize:591 : pyOpenSSL: module missing
19-okt-2017 20:57:25 - WARNING :: MAIN : __init__.py:initialize:591 : cryptography: module missing
19-okt-2017 20:58:08 - INFO :: MAIN : versioncheck.py:logmsg:37 : [VersionCheck] -  Comparing currently installed version with latest github version
19-okt-2017 20:58:08 - WARNING :: MAIN : versioncheck.py:logmsg:41 : (getCommitDifferenceFromGit) KeyError -  could not get difference status from GitHub
19-okt-2017 20:58:08 - INFO :: MAIN : versioncheck.py:logmsg:37 : [VersionCheck] -  You are running an unknown version of lazylibrarian. Run the updater to identify your version
19-okt-2017 20:58:08 - INFO :: MAIN : LazyLibrarian.py:main:189 : Starting LazyLibrarian on port: 5299, webroot ""
19-okt-2017 20:58:08 - INFO :: MAIN : webStart.py:initialize:57 : Starting LazyLibrarian web server on http://0.0.0.0:5299/
19-okt-2017 20:58:10 - INFO :: DB_UPGRADE : dbupgrade.py:dbupgrade:127 : Creating new database, version 23
19-okt-2017 20:58:10 - INFO :: DB_UPGRADE : dbupgrade.py:dbupgrade:349 : Database upgraded to version 23
19-okt-2017 20:58:22 - INFO :: CONFIG_WRITE : __init__.py:config_write:937 : Config file [C:\Users\<username removed>\Desktop\LazyLibrarian-master\config.ini] has been updated
```

I went through the last 5 commits, it does not seem you touched that previous file with the missing bracket.

Tested with:  55cf15e

**Comment by CasperH2O** [comment]
Mmmh you are right. I just downloaded a fresh copy (same version) to another PC and ran it. No problems. Perhaps I tested with an older version as I had been switching back and forth a bit for testing purposes.
