### ISSUE TITLE
Most recent commit 'Unable to get latest version from GITHub'

### ISSUE THREAD

**Issue by SteadFast13** [DobyTang/LazyLibrarian#1067]
Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 097a5d5bc62548d29dc31a5446f738e88b2fe819 : Latest Version: Not_Available_From_GitHUB

Windows 10
Bookstrap
Both API
source git

Since recent update seems to have trouble with git as well as when using bookstrap, bookwatch theme field is blank with no options from the dropdown. 

I tried to clone from git completely fresh and I have the same result.

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1376363/debug.zip)

**Comment by philborman** [comment]
Unfortunately your debug log is not showing any errors. There were major changes in the way we talk to websites in this version, (using a new library) and it seems something is broken. Not clear what yet, as it's working on all my systems here.

Would like to get it fixed a.s.a.p. Can you try starting lazylibrarian with debug logging on. The first point where we use the new library is getting bookstrap themes, somewhere around line 420 in the log just after checking the sqlite3 version. I'm guessing you will have an error noted in the log at that point, would be useful to know what it says.  Also if you are able to run lazylibrarian from a terminal as that can sometimes show errors from background tasks. Thanks in advance.

**Comment by SteadFast13** [comment]
Sorry about that. Here is an updated log.

```
11-Oct-2017 12:55:52 - INFO    :: MAIN : __init__.py:config_read:784 : Config file loaded
11-Oct-2017 12:55:52 - INFO    :: MAIN : __init__.py:initialize:539 : SYS_ENCODING is UTF-8
11-Oct-2017 12:55:52 - INFO    :: MAIN : __init__.py:initialize:572 : Database is version 23, integrity check: ok
11-Oct-2017 12:55:52 - DEBUG   :: MAIN : __init__.py:initialize:578 : sqlite3 is v3.6.21
11-Oct-2017 12:55:54 - DEBUG   :: MAIN : __init__.py:build_bookstrap_themes:1089 : Error getting bookstrap themes : Exception SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)
11-Oct-2017 12:55:54 - DEBUG   :: MAIN : versioncheck.py:logmsg:42 : Set Install Type, Current & Latest Version and Commit status
11-Oct-2017 12:55:55 - DEBUG   :: MAIN : versioncheck.py:logmsg:42 : (RunGit)Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in C:\Program Files (Git.Source)\LazyLibrarian
11-Oct-2017 12:55:55 - DEBUG   :: MAIN : versioncheck.py:logmsg:42 : (RunGit)Git output: [master]
11-Oct-2017 12:55:55 - DEBUG   :: MAIN : versioncheck.py:logmsg:42 : (getCurrentGitBranch) Current local branch of repo is [master] 
11-Oct-2017 12:55:55 - DEBUG   :: MAIN : versioncheck.py:logmsg:42 : (getInstallType) [git] install detected. Setting Branch to [master]
11-Oct-2017 12:55:55 - DEBUG   :: MAIN : versioncheck.py:logmsg:42 : (RunGit)Trying to execute: "git rev-parse HEAD" with shell in C:\Program Files (Git.Source)\LazyLibrarian
11-Oct-2017 12:55:56 - DEBUG   :: MAIN : versioncheck.py:logmsg:42 : (RunGit)Git output: [097a5d5bc62548d29dc31a5446f738e88b2fe819]
11-Oct-2017 12:55:56 - DEBUG   :: MAIN : versioncheck.py:logmsg:42 : (updateVersionFile) Updating [C:\Program Files (Git.Source)\LazyLibrarian\version.txt] with value [097a5d5bc62548d29dc31a5446f738e88b2fe819]
11-Oct-2017 12:55:56 - DEBUG   :: MAIN : versioncheck.py:logmsg:42 : (getCurrentVersion) - Install type [git] Local Version is unchanged [097a5d5bc62548d29dc31a5446f738e88b2fe819] 
11-Oct-2017 12:55:56 - DEBUG   :: MAIN : versioncheck.py:logmsg:42 : (getLatestVersion_FromGit) Retrieving latest version information from github command=[https://api.github.com/repos/dobytang/lazylibrarian/commits/master]
11-Oct-2017 12:55:57 - WARNING :: MAIN : versioncheck.py:logmsg:44 : (getLatestVersion_FromGit) Could not get the latest commit from github
11-Oct-2017 12:55:57 - DEBUG   :: MAIN : versioncheck.py:logmsg:42 : git TypeError for https://api.github.com/repos/dobytang/lazylibrarian/commits/master: 'dict' object is not callable
11-Oct-2017 12:55:57 - INFO    :: MAIN : versioncheck.py:logmsg:40 : Unable to get latest version from GitHub
11-Oct-2017 12:55:57 - DEBUG   :: MAIN : versioncheck.py:logmsg:42 : (getCommitDifferenceFromGit) - exiting with commit value of [lue of [0]
11-Oct-2017 12:55:57 - DEBUG   :: MAIN : versioncheck.py:logmsg:42 : Update check complete
11-Oct-2017 12:55:57 - DEBUG   :: MAIN : lazylibrarian.py:main:162 : Current Version [097a5d5bc62548d29dc31a5446f738e88b2fe819] - Latest remote version [Not_Available_From_GitHUB] - Install type [git]
11-Oct-2017 12:55:57 - INFO    :: MAIN : lazylibrarian.py:main:189 : Starting LazyLibrarian on port: 5299, webroot ""
11-Oct-2017 12:55:57 - INFO    :: MAIN : webStart.py:initialize:57 : Starting LazyLibrarian web server on http://0.0.0.0:5299/
11-Oct-2017 12:56:02 - DEBUG   :: MAIN : common.py:scheduleJob:287 : Start processDir job in 10 minutes
11-Oct-2017 12:56:05 - DEBUG   :: MAIN : common.py:scheduleJob:311 : Start checkForUpdates job in 24 hours
11-Oct-2017 12:56:05 - DEBUG   :: MAIN : common.py:scheduleJob:335 : Start authorUpdate job in 60 minutes
11-Oct-2017 12:56:33 - DEBUG   :: SAVELOG : common.py:saveLog:582 : Processing logfile [C:\Program Files (Git.Source)\LazyLibrarian\Logs\lazylibrarian.log]

```

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1376697/debug.zip)

**Comment by CasperH2O** [comment]
Seeing something similar with a fresh "download" install. After hitting the update I can see the following in the console/terminal:
`11-okt-2017 20:39:36 - INFO :: MAIN : __init__.py:logmsg:1285 : LazyLibrarian is updating...
INFO:lazylibrarian:MAIN : __init__.py:logmsg:1285 : LazyLibrarian is updating...
11-okt-2017 20:39:36 - INFO :: MAIN : versioncheck.py:logmsg:40 : (update) Downloading update from: https://github.com/dobytang/lazylibrarian/tarball/master
INFO:lazylibrarian:MAIN : versioncheck.py:logmsg:40 : (update) Downloading update from: https://github.com/dobytang/lazylibrarian/tarball/master
11-okt-2017 20:39:36 - ERROR :: MAIN : versioncheck.py:logmsg:38 : (update) Unable to retrieve new version from https://github.com/dobytang/lazylibrarian/tarball/master, can't update: global name 'proxylist' is not defined
ERROR:lazylibrarian:MAIN : versioncheck.py:logmsg:38 : (update) Unable to retrieve new version from https://github.com/dobytang/lazylibrarian/tarball/master, can't update: global name 'proxylist' is not defined
11-okt-2017 20:39:36 - INFO :: MAIN : __init__.py:logmsg:1285 : LazyLibrarian is restarting ...
INFO:lazylibrarian:MAIN : __init__.py:logmsg:1285 : LazyLibrarian is restarting ...`

Proxylist is not defined?

**Comment by philborman** [comment]
proxylist is a silly typo, should be capital L, proxyList
The other issue is missing SSL support in @SteadFast13 windows version of requests library, I think.
There is a testing version in my git https://github.com/philborman/LazyLibrarian.git
which forces use of a lazylibrarians own copy of requests, if you could give it a try?

**Comment by philborman** [comment]
Ok, the proxylist typo is fixed now so tar/zip upgrades should work again. Found the ssl problem here 
https://stackoverflow.com/questions/35405092/sslerror-sslv3-alert-handshake-failure
You need to upgrade your python versions of a few packages to get ssl support working. Sadly this is needed for goodreads starting from December, so it's not really optional. Core requirement. I will have a look if there is any way we can ship a copy with lazylibrarian, or at least detect it's missing and warn users.
You need to upgrade or install... (use pip to install the packages if you have it)
pyOpenSSL
ndg-httpsclient 
pyasn1

**Comment by SteadFast13** [comment]
Sorry about the late reply.

Ran pip install
pyOpenSSL
ndg-httpsclient
pyasn1

All were successful.

Then cloned https://github.com/DobyTang/LazyLibrarian/

[debugDT.zip](https://github.com/DobyTang/LazyLibrarian/files/1377783/debugDT.zip)

Same issue as before, 'Unable to get latest version from GITHub' as well as no options for bookwatch theme.

Cloned https://github.com/philborman/LazyLibrarian

[PBdebug.zip](https://github.com/DobyTang/LazyLibrarian/files/1377805/PBdebug.zip)

Both issues seem to be resolved. It does state '20 commits behind' but attempts to update are unsuccessful.

**Comment by philborman** [comment]
Ok, many thanks for your help. I will push my version to DobyTang in a few hours. Once you have pip installed/upgraded the python packages, the only difference between DobyTang and mine is I force lazylibrarian to use a local copy of the "requests" library instead of the system one. Could be the system version installed on windows is not compatible? If you are curious, try in a terminal 
python -c "import requests; print requests.__version__"  to see what the system version is. The one shipped with lazylibrarian is 2.12.4


The version number difference (20 commits behind) is expected as we are mixing versions. Git is comparing the DobyTang version number with the code you are running from my git.

**Comment by SteadFast13** [comment]
All fixed! Pulling from git just fine and bookstrap themes are working again too.

I attempted to run
```
python -c "import requests; print requests.version"

Traceback (most recent call last):
File "<string>", line 1, in <module>
AttributeError: module object has no attribute 'version'
```

Not a concern for me, as I am just a learn as I go hobbyist monkey. I assume that is something I am doing wrong, ie wrong directory. 

I appreciate all the hard work! Thank you for the help!

**Comment by philborman** [comment]
No problem. Thanks for your help testing it so quickly. Good to get a rapid fix out as it could break quite a few systems.

As for the attribute error,  the markup formatter on github has stripped out the underscores.
Should have two underscores in front and behind version...
`python -c "import requests; print requests.__version__" `
Not too crucial, but I could potentially test for versions that don't work and recommend an upgrade, or at least issue a warning.

**Comment by SteadFast13** [comment]
Well in that case

0.14.2

I guess I am little out of date?
