### ISSUE TITLE
Error after latest pull

### ISSUE THREAD

**Issue by DK2Maverick** [DobyTang/LazyLibrarian#1070]
To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

just pulled the new commit and on start up I get:
  File "LazyLibrarian.py", line 14, in <module>
    import lazylibrarian
  File "/opt/LazyLibrarian/lazylibrarian/__init__.py", line 32, in <module>
    from lazylibrarian import logger, postprocess, searchbook, searchrss, librarysync, versioncheck, database, \
  File "/opt/LazyLibrarian/lazylibrarian/postprocess.py", line 26, in <module>
    from lazylibrarian import database, logger, utorrent, transmission, qbittorrent, \
  File "/opt/LazyLibrarian/lazylibrarian/utorrent.py", line 25, in <module>
    from lazylibrarian.common import USER_AGENT
  File "/opt/LazyLibrarian/lazylibrarian/common.py", line 29, in <module>
    import requests
ImportError: No module named requests

Was working before the pull

Thanks

**Comment by philborman** [comment]
Line 29 should say import lib.requests
Seems your ubuntu does not include the requests library. sudo apt install python-requests will get you up and running, or there will be a fix out later today.  Thanks for the bug report.

**Comment by VarunChugh** [comment]
sorry for a noob question, how do I upgrade from the command line? Since I dont have the UI? thanks

**Comment by philborman** [comment]
Depends how you installed lazylibrarian.
If you installed it from git, log into your freenas jail, cd into the lazylibrarian directory (in your case "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/") and do "git pull"
If you installed from a zip file, you can just download and install the new zip

The above suggestions will work for pretty much any installation problem.
Another option (but only for this particular problem) is to log into your freenas jail and do "pip install requests" which will get around the issue, as long as your jail has pip included. Lazylibrarian will then start, and you can use the internal upgrade to get to current version.

**Comment by VarunChugh** [comment]
I get the below error if I do a git pull

root@lazylibrarian_2:/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian # git pull
fatal: Not a git repository (or any of the parent directories): .git

I also tried pip install requests, the command ran but the LL UI is not coming back up. I tried starting but get the below error:

root@lazylibrarian_2:/ # service lazylibrarian start
Starting lazylibrarian.
Traceback (most recent call last):
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/LazyLibrarian.py", line 14, in <module>
    import lazylibrarian
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/__init__.py", line 32, in <module>
    from lazylibrarian import logger, postprocess, searchbook, searchrss, librarysync, versioncheck, database, \
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 26, in <module>
    from lazylibrarian import database, logger, utorrent, transmission, qbittorrent, \
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/utorrent.py", line 25, in <module>
    from lazylibrarian.common import USER_AGENT
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/common.py", line 29, in <module>
    import requests
ImportError: No module named requests
/usr/local/etc/rc.d/lazylibrarian: WARNING: failed to start lazylibrarian

**Comment by philborman** [comment]
So it looks like the docker image did not use git to install lazylibrarian, and the requests library is still not found.

Another option is to patch File 
"/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/common.py", line 29
change... 
`import requests`
to...
`import lib.requests as requests`
which is what the new version says. This will stop lazylibrarian updating from git (it will complain there are local changes) but should not stop non-git upgrades, which yours seems to be.

**Comment by VarunChugh** [comment]
that worked. Thanks!
