### ISSUE TITLE
Magazine reject list filters not retained after LL restart.

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1073]
Magazine reject list filters not retained after LL restart.

It is retained while moving between LL tabs, just missing what I have previously entered, before a LL restart or update.

**Comment by philborman** [comment]
Can't reproduce it here, seems to be working ok. A few places it could be failing, are you pressing "save" after making changes, does the log show the config was saved (could be failing to write), does the config file have your new entries in (could be failing to read back).

**Comment by MrMxyzptlk** [comment]
OK, I added the word 'Runner', as a reject word to a magazine. I looked in the log file and it said that it wrote it out to the config file. I restarted LL and the reject word is still there, but I can't find it in the config file?

**Comment by philborman** [comment]
oops, my bad. We used to store that in the config file but not any more, it's in the database now.  
You still need to save the config so lazylibrarian knows there are changes to write to the database.

**Comment by MrMxyzptlk** [comment]
So it's actually writing to the DB, but says it's writing to the config.ini?

I will see if my filters stick for a few days, this time.

**Comment by philborman** [comment]
Yes it's writing some info to both. Confusing message (confused me too)  I will change it.
