### ISSUE TITLE
Download directory with spaces not handled properly

### ISSUE THREAD

**Issue by CasperH2O** [DobyTang/LazyLibrarian#1074]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
Current Version: ec9a96f583b6096e16eb9e6ebe787059d94d4428 : Latest Version: ec9a96f583b6096e16eb9e6ebe787059d94d4428
### Operating system used (windows, mac, linux, NAS type)
Windows 10
### Interface in use (default, bookstrap)
Bookstrap
### Which api (Goodreads, GoogleBooks, both)
GoogleBooks, is both possible?
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
Zip file
### Relevant debug log with api keys and any passwords redacted
Not sure if needed?

Observed this one in the terminal output after LazyLibrarian had been running for a while:
```
15-okt-2017 12:13:45 - WARNING :: POSTPROCESS : __init__.py:DIRECTORY:1019 : Download dir [N:\Work] not found, using C:\Users\<my user name>\Software\Applicaties\LazyLibrarian
15-okt-2017 12:13:45 - WARNING :: POSTPROCESS : __init__.py:DIRECTORY:1019 : Download dir [N:\Work] not found, using C:\Users\<my user name>\Software\Applicaties\LazyLibrarian
15-okt-2017 12:13:45 - INFO :: POSTPROCESS : postprocess.py:processDir:636 : 0 books/mags processed.
15-okt-2017 12:13:45 - INFO :: POSTPROCESS : postprocess.py:processDir:673 : Nothing marked as snatched. Stopping postprocessor.
```

Doing some investigation I found the settings page: Settings -> Downloaders bottom right. I had the following entered: N:\Work In Progress
Apparently that does not work. I adjusted it with double quotes to "N:\Work In Progress" but upon saving it disappears. 

I have a feeling this is just to handle different OS types, but a warning in the text below would be nice. :-)

**Comment by philborman** [comment]
Ah, that's a bug. Recent change to allow multiple directories has broken it, expect a fix shortly.

Which api (Goodreads, GoogleBooks, both)
GoogleBooks, is both possible?

Yes, but not at the same time. For example if googlebooks has an author that goodreads does not have, or if you have a book in your library that is only listed on one of the sites. Used to be quite common, but less so now as both sites have better lists.

**Comment by CasperH2O** [comment]
Thanks for checking it out Phil.

I just hit the update button but it seems something went wrong. I was three commits behind on the master. See update log:

```
15-okt-2017 20:00:22 - INFO :: UPDATES : versioncheck.py:logmsg:37 : [VersionCheck] -  New version is available. You are 3 commits behind
15-okt-2017 20:00:59 - INFO :: MAIN : __init__.py:logmsg:1285 : LazyLibrarian is updating...
INFO:lazylibrarian:MAIN : __init__.py:logmsg:1285 : LazyLibrarian is updating...
15-okt-2017 20:00:59 - INFO :: MAIN : versioncheck.py:logmsg:37 : (update) Downloading update from: https://github.com/dobytang/lazylibrarian/tarball/master
INFO:lazylibrarian:MAIN : versioncheck.py:logmsg:37 : (update) Downloading update from: https://github.com/dobytang/lazylibrarian/tarball/master
15-okt-2017 20:01:01 - INFO :: MAIN : versioncheck.py:logmsg:37 : (update) Extracting fileC:\Users\<username>\Software\Applicaties\LazyLibrarian\master
INFO:lazylibrarian:MAIN : versioncheck.py:logmsg:37 : (update) Extracting fileC:\Users\<username>\Software\Applicaties\LazyLibrarian\master
15-okt-2017 20:01:01 - WARNING :: MAIN : __init__.py:logmsg:1283 : LazyLibrarian failed to update: error Error -3 while decompressing: invalid literal/lengths set. Restarting.
WARNING:lazylibrarian:MAIN : __init__.py:logmsg:1283 : LazyLibrarian failed to update: error Error -3 while decompressing: invalid literal/lengths set. Restarting.
15-okt-2017 20:01:01 - INFO :: MAIN : __init__.py:logmsg:1285 : LazyLibrarian is restarting ...
INFO:lazylibrarian:MAIN : __init__.py:logmsg:1285 : LazyLibrarian is restarting ...
DEBUG:lazylibrarian:MAIN : __init__.py:logmsg:1281 : Restarting LazyLibrarian with ['C:\\Python27\\python.exe', 'C:\\Users\\<username>\\Software\\Applicaties\\LazyLibrarian\\LazyLibrarian.py', '--nolaunch']
15-okt-2017 20:01:01 - INFO :: MAIN : __init__.py:logmsg:1285 : LazyLibrarian is exiting
INFO:lazylibrarian:MAIN : __init__.py:logmsg:1285 : LazyLibrarian is exiting
Lazylibrarian is starting up...
15-okt-2017 20:01:06 - INFO :: MAIN : __init__.py:initialize:530 : Log level set to [1]- Log Directory is [C:\Users\<username>\Software\Applicaties\LazyLibrarian\Logs] - Config level is [1]
15-okt-2017 20:01:06 - INFO :: MAIN : __init__.py:initialize:536 : Screen Log set to INFO/WARN/ERROR
15-okt-2017 20:01:07 - INFO :: MAIN : __init__.py:config_read:784 : Config file loaded
15-okt-2017 20:01:07 - INFO :: MAIN : __init__.py:initialize:539 : SYS_ENCODING is UTF-8
15-okt-2017 20:01:07 - INFO :: MAIN : __init__.py:initialize:572 : Database is version 23, integrity check: ok
15-okt-2017 20:01:08 - INFO :: MAIN : versioncheck.py:logmsg:37 : [VersionCheck] -  Comparing currently installed version with latest github version
15-okt-2017 20:01:09 - INFO :: MAIN : versioncheck.py:logmsg:37 : [VersionCheck] -  New version is available. You are 3 commits behind
```

Do you require any other debug log? I have remove my user name from the paths FYI.

**Comment by philborman** [comment]
Looks like you got a corrupt or incomplete tarfile
I would suggest download the zip and reinstall from that.

**Comment by CasperH2O** [comment]
I have not seen the message of not being able to find the download directory for a while. Closing ticket.
