### ISSUE TITLE
File Type Select

### ISSUE THREAD

**Issue by wabit** [DobyTang/LazyLibrarian#108]
LL does not seem to look at what file type it is downlaoding, too often it downloads Audio books.

and as my collection is dedicated to .mobi files when it downloads .pdf and .epud it can be quite annoying.

If we could blacklist certain words from search terms it would be very usefull to getting files you want

**Comment by daktak** [comment]
So the ebook type setting in file formats is used in the search term, depending on your provider you could put !audio maybe.
searchterm = author + ' ' + book # + ' ' + lazylibrarian.EBOOK_TYPE
