### ISSUE TITLE
Two warnings in log, everything seems OK

### ISSUE THREAD

**Issue by CasperH2O** [DobyTang/LazyLibrarian#1083]
### LazyLibrarian version number (at the bottom of config page)
Current Version: 00853d052dbc697356e5d319812892364c12f472 : Latest Version: 00853d052dbc697356e5d319812892364c12f472
### Operating system used (windows, mac, linux, NAS type)
Windows 10
### Interface in use (default, bookstrap)
Bookstrap
### Which api (Goodreads, GoogleBooks, both)
GoogleBooks
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
Zip

Doing some test downloads and checking if everything is running smoothly. So far the first book went OK. However in the log I see two warnings that I can't really explain. Attached two images (book name and usernames redacted).

![afbeelding](https://user-images.githubusercontent.com/14330834/31825275-f106f9fe-b5b1-11e7-9af2-000ad17b98dd.png)

The book is found, downloaded and nicely copied to the Calibre auto add folder, where Calibre picked it up. What I don't understand:
- Why is the fact that Deluge is seeding a warning level event? Checking the command line nothing went wrong there.
- I get the message to check the EBOOK_DEST_FOLDER setting, but I can't seem to find that one, which setting is that? I have the Calibre Auto Add Directory and eBook Library Folder filled in in the settings. The alternate directory is empty.

**Comment by philborman** [comment]
Deluge warning may be because you have "keep seeding after processing" set, but "keep original files" is not set so it's warning you it has to keep the original files so it can keep seeding.

Check ebook dest folder warning is because the setting for eBook/AudioBook Foldername Pattern contains a '/'   (default is $Author/$Title)  and windows uses '\' as a separator, you probably want to change that.

**Comment by CasperH2O** [comment]
> Deluge warning may be because you have "keep seeding after processing" set, but "keep original files" is not set so it's warning you it has to keep the original files so it can keep seeding.

Nice catch, that was the case. 

> Check ebook dest folder warning is because the setting for eBook/AudioBook Foldername Pattern contains a forwardslash (default is $Author/$Title) and windows uses backslash as a separator, you probably want to change that.

Actually the default is "$Author\$Title" for eBook/AudioBook Foldername Pattern and "_Magazines/$Title/$IssueDate" for magazines. Should I try with a forward slash instead?

**Comment by philborman** [comment]
For windows, use backslash.
`"$Author\$Title" and "_Magazines\$Title\$IssueDate" `
