### ISSUE TITLE
Email notification password visible as plain text

### ISSUE THREAD

**Issue by CasperH2O** [DobyTang/LazyLibrarian#1084]
### LazyLibrarian version number (at the bottom of config page)
Current Version: 00853d052dbc697356e5d319812892364c12f472 : Latest Version: 00853d052dbc697356e5d319812892364c12f472
### Operating system used (windows, mac, linux, NAS type)
Windows 10
### Interface in use (default, bookstrap)
Bookstrap
### Which api (Goodreads, GoogleBooks, both)
Googlebooks
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
Zip

Setting up the email notification after downloads are completed, noticed that the email password field shows my actual password (does not make it into circles or whatever). On that note, how does LazyLibrarian store it's passwords? Are the hashed/salted what not? Not my area of expertise to be honest.

Additionally of interest, last week I could not get email notification with SSL to work. But since I pip installed the missing modules for https GoodReads in the near future I can. This seems to be an additional prerequisite that needs to be tried/failed gracefully?

**Comment by philborman** [comment]
The user account passwords stored in the database are hashed. Email password is stored in config file in plain text as is the webuser name and password, and your api keys for providers / downloaders and lazylibrarians api key. The api keys are sent in plain text anyway, the email and webuser passwords are not currently encrypted, and we would need a method for unencrypting them before use. If you allow others to use your lazylibrarian, enable user accounts and don't give them admin access. This blocks access to lazylibrarian config page which is the only place they are shown.

The email notifiler (and all the other notifiers) have a "test" button to check connection. I would expect if you try sending an email with ssl and no ssl module is loaded you will get an error message popup?  Probably we can detect the message and replace it with one telling you to install the missing modules. I will have a look.

**Comment by CasperH2O** [comment]
Tested with ver. 6e29d4d0fb9eb4cdcb487c205fec4f54446fdf66 text field is obfuscated. Thank you @philborman. Closing ticket.
