### ISSUE TITLE
History Tab Error

### ISSUE THREAD

**Issue by osuhickeys** [DobyTang/LazyLibrarian#1087]
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1403095/debug.zip)
### LazyLibrarian version number (at the bottom of config page)
"00853d052dbc697356e5d319812892364c12f472"
### Operating system used (windows, mac, linux, NAS type)
Windows 10
### Interface in use (default, bookstrap)
Default
### Which api (Goodreads, GoogleBooks, both)
Both
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
zip
### Relevant debug log with api keys and any passwords redacted

500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.
Traceback (most recent call last):
  File "C:\Users\mark\Documents\GitHub\LazyLibrarian\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\Users\mark\Documents\GitHub\LazyLibrarian\cherrypy\lib\encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\mark\Documents\GitHub\LazyLibrarian\cherrypy\_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Users\mark\Documents\GitHub\LazyLibrarian\lazylibrarian\webServe.py", line 2705, in history
    title = title.replace('.', ' ')
AttributeError: 'NoneType' object has no attribute 'replace'
Powered by CherryPy 3.6.0

**Comment by philborman** [comment]
Seems you have an item in your history (wanted table) with no title. Shouldn't really happen. I will add some code to trap it, thanks for the bug report.

**Comment by philborman** [comment]
Also your log shows that the version of pyopenssl is too old, you may hit problems talking to goodreads when their upgrade rolls out in December.

pyOpenSSL: module missing required functionality. Try upgrading to v0.14 or newer. 
You have pyOpenSSL: 0.13

**Comment by osuhickeys** [comment]
I removed all books in my wanted list and updated to the latest version.  There were three new updates today it appears.  Restarted LL and still getting the same results.  It does not appear there is a Windows version of pyOpenSSL-0.14 yet.  I will update once it becomes available.  Thanks for the heads up.

**Comment by philborman** [comment]
The bad entry in the "wanted" list is not a book that's still marked as wanted, it's a faulty entry in the table with no title. You can't clean that inside lazylibrarian as it shouldn't really exist. I could add some code to the startup routine to check the database entries each time, might not be a bad idea, but would be better if we didn't store the bad entry to start with. Problem with these sorts of issues is finding how they occur in the first place.

If you are up to a little database editing, you can clear the bad entry with one sqlite command:
"delete from wanted where title is null"

The pyopenssl version you are running was released February 2014, so is just a _little_ out of date. Current version is 17.3.0
I think you can upgrade from pyopenssl.org

**Comment by osuhickeys** [comment]
Running "delete from wanted where NZBtitle is null;" brought back the history tab.  Appreciate the help!

Seems like pyOpenSSL on Windows is not a straight forward process.  There does not seem to have been any new release of it in an MSI format since pyOpenSSL: 0.13.  Lots of people struggling over the years on OpenStack.com trying to figure out how to get it to work with a newer version.  After uninstall 0.13 and running "pip install pyopenssl" LL will not start.  Exits with "AttributeError: 'module' object has no attribute 'SSL_ST_INIT'".  I'll work on this some more over the weekend and see if I can get it to work with a newer version.

**Comment by philborman** [comment]
Looks like you also need to upgrade/install cryptography,  see...
https://cryptography.io/en/latest/installation/

**Comment by osuhickeys** [comment]
When I tried to do pip install cryptography I get requirement already satisfied.  I uninstalled it and reinstalled it and LL still will not start.  Below is the full console message when it fails to start.

Traceback (most recent call last):
  File "LazyLibrarian.py", line 14, in <module>
    import lazylibrarian
  File "C:\Users\username\Documents\GitHub\LazyLibrarian\lazylibrarian\__init__.py", line 32, in <module>
    from lazylibrarian import logger, postprocess, searchbook, searchrss, librarysync, versioncheck, database, \
  File "C:\Users\username\Documents\GitHub\LazyLibrarian\lazylibrarian\postprocess.py", line 26, in <module>
    from lazylibrarian import database, logger, utorrent, transmission, qbittorrent, \
  File "C:\Users\username\Documents\GitHub\LazyLibrarian\lazylibrarian\utorrent.py", line 25, in <module>
    from lazylibrarian.common import USER_AGENT
  File "C:\Users\username\Documents\GitHub\LazyLibrarian\lazylibrarian\common.py", line 30, in <module>
    import lib.requests as requests
  File "C:\Users\username\Documents\GitHub\LazyLibrarian\lib\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\Users\username\Documents\GitHub\LazyLibrarian\lib\requests\packages\urllib3\contrib\pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "build\bdist.win32\egg\OpenSSL\__init__.py", line 8, in <module>
  File "build\bdist.win32\egg\OpenSSL\SSL.py", line 105, in <module>
    )
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by philborman** [comment]
I did a quick google for SSL_ST_INIT and it seems to crop up quite a lot. OpenSSL and pyOpenSSL need to communicate and it looks like they need to be a matched pair. Maybe remove OpenSSL and pip install a new one?

**Comment by osuhickeys** [comment]
That seems to have done it.  I did a pip install pyopenssl to make sure it was there and it said requirements satisfied.  I uninstalled and reinstalled and it works now.  Thanks for your help.

**Comment by philborman** [comment]
Excellent news. I will have to write up what needed to be done for the wiki as this could cause issues for quite a few users. Thanks for your help.
