### ISSUE TITLE
LazyLibrarian Docker - Magazines

### ISSUE THREAD

**Issue by jrdnlc** [DobyTang/LazyLibrarian#1088]
Anyone here running this in a docker? I'm having trouble setting this up for magazines and getting it to just work correctly. So far each magazine I download go into their own folder but some are not in there respective folders like this magpi issues here

![screen shot 2017-10-21 at 12 37 20 am](https://user-images.githubusercontent.com/15741144/31849499-0db44782-b5f8-11e7-8c18-2aff495f6ef0.png)

Any idea how can I fix this? Is there a proper folder structure? How about cover images? How are those detected/downloaded? 

Any help will be greatly appreciated. Thank you in advance!

**Comment by philborman** [comment]
Magazine folder and filename structure is set in lazylibrarian config in the processing tab.
Default is a subdirectory in your book library, _Magazines/$Title/$IssueDate
Cover images are generated from the first page of each magazine pdf file using ghostscript, which may be included in your docker image, or you may need to configure an external ghostscript (or imagemagick or other converter) in lazylibrarian config "cover creation program"

**Comment by jrdnlc** [comment]
I believe ghostcript is included in the docker images because some magazines do have a cover image. Is there a way to double check? @philborman

**Comment by philborman** [comment]
Which docker? If you are on the ones linked to from lazylibrarian git page then yes, should be included.
The presence of covers doesn't necessarily mean you have gs installed, there might have been a cover included in the download. Not sure where ghostscript is installed in the dockers, are you familiar with logging into the docker? If so, try "which gs". If you want to check from inside lazylibrarian, easiest way is to turn debug log on and add a new magazine or libraryscan existing magazines. You could also use the api command createMagCovers
In the debug log you will see lines saying where it tried to find ghostscript, and if it found ghostscript it will tell you the version number
