### ISSUE TITLE
New Updates

### ISSUE THREAD

**Issue by Viper911** [DobyTang/LazyLibrarian#1089]
Seeing something really weird.  Every time there is an update I get the popup at the bottom right but it will say something like 200 not committed, then the next time 250, then 300..  I think I am up to like 350.  I have applied the updates and it will say I'm up to date when a new one comes out, rather than saying there are like 5 new ones, it just adds to the prior total and would be like 355.

Thoughts?

**Comment by philborman** [comment]
Couple of options spring to mind...
1. Is your version.txt file read only, so we can't update it? Not sure if we check for that, we probably should.
2. Have you switched between lazylibrarian githubs, eg between the dobytang one and mine or itsmegb? The version file might contain a checksum from a different github. 

You can reset the version.txt file to make the problem go away, just create a new one containing the proper checksum shown on the github you are using. The current checksum is the "latest commit" shown on the page, for dobytang it's currently 6e29d4d0fb9eb4cdcb487c205fec4f54446fdf66.

**Comment by Viper911** [comment]
1) I checked the file and its read and write on it
2) As far as I know I've only used DobyTang

I looked in my file and it reads "e219456912c78277ca36c2d4d99be6be2442c282", your saying I just need to replace this with the one you gave me?

**Comment by Viper911** [comment]
BTW - this is what it reads in the setting section.

Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: e219456912c78277ca36c2d4d99be6be2442c282 : Latest Version: e219456912c78277ca36c2d4d99be6be2442c282

**Comment by Viper911** [comment]
Not sure why the post is being concatenated, but its the checksum is what I put in my other post.  I'll try again here
Current Version: "e219456912c78277ca36c2d4d99be6be2442c282"
Latest Version: "e219456912c78277ca36c2d4d99be6be2442c282"

**Comment by philborman** [comment]
Strange. Current version and latest are the same, but that version code is an old one from July. Seems you are not updating even though you think you are, but I'm not sure why the "latest version" is so far out of date.   If you wouldn't mind, can you turn debugging on, go to the config page and hit "check version", and post the debug log showing what the updater tries to do. Don't update from the popup that appears as it will stop the log showing the info we need.

The useful section starts with 
Set Install Type, Current & Latest Version and Commit status
and ends at 
Update check complete

**Comment by Viper911** [comment]
Sorry for the delay, here it is:

28-Oct-2017 16:16:07 - DEBUG   :: MAIN : Set Install Type, Current & Latest Version and Commit status
28-Oct-2017 16:16:07 - DEBUG   :: MAIN : (RunGit)Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /opt/LazyLibrarian
28-Oct-2017 16:16:07 - DEBUG   :: MAIN : (RunGit)Git output: [master]
28-Oct-2017 16:16:07 - DEBUG   :: MAIN : (getCurrentGitBranch) Current local branch of repo is [master]
28-Oct-2017 16:16:07 - DEBUG   :: MAIN : (getInstallType) [git] install detected. Setting Branch to [master]
28-Oct-2017 16:16:07 - DEBUG   :: MAIN : (RunGit)Trying to execute: "git rev-parse HEAD" with shell in /opt/LazyLibrarian
28-Oct-2017 16:16:07 - DEBUG   :: MAIN : (RunGit)Git output: [e219456912c78277ca36c2d4d99be6be2442c282]
28-Oct-2017 16:16:07 - DEBUG   :: MAIN : (updateVersionFile) Updating [/opt/LazyLibrarian/version.txt] with value [e219456912c78277ca36c2d4d99be6be2442c282]
28-Oct-2017 16:16:07 - DEBUG   :: MAIN : (getCurrentVersion) - Install type [git] Local Version is unchanged [e219456912c78277ca36c2d4d99be6be2442c282]
28-Oct-2017 16:16:07 - DEBUG   :: MAIN : (getLatestVersion_FromGit) Retrieving latest version information from github command=[https://api.github.com/repos/dobytang/lazylibrarian/commits/master]
28-Oct-2017 16:16:07 - DEBUG   :: MAIN : (getLatestVersion_FromGit) Checking if modified since Sat, 28 Oct 2017 21:16:04 GMT
28-Oct-2017 16:16:07 - DEBUG   :: MAIN : (getLatestVersion_FromGit) Not modified, currently on Latest Version
28-Oct-2017 16:16:07 - DEBUG   :: MAIN : Update check complete

________________________________

**Comment by philborman** [comment]
ok, I see what's happening here.
Not sure what your system is, but as you are on a git install if you open a terminal in your lazylibrarian installation directory and do  `git pull`  there will be a load of updates. Restart lazylibrarian and the problem should go away.
The lazylibrarian installation directory is the one containing LazyLibrarian.py

**Comment by Viper911** [comment]
Well, I did the pull and restarted, now the Auther screen is empty (no Authors listed)..  If I go to the setting screen I get the below errors.  In any case, something got messed up.  Perhaps the DB needs updating or something now?

Error !
KeyError: 'SORT_DEFINITE'
<input type="checkbox" id="mag_tab" name="mag_tab" value=1 ${checked} /> <label> Show Magazines</label> <br> <% if lazylibrarian.CONFIG['SORT_DEFINITE'] == True: checked = 'checked="checked"' else: checked = '' %>
/opt/LazyLibrarian/data/interfaces/default/config.html, line 182:
<%
/opt/LazyLibrarian/data/interfaces/default/base.html, line 157:
${next.body()}
/opt/LazyLibrarian/mako/runtime.py, line 890:
callable_(context, *args, **kwargs)
/opt/LazyLibrarian/mako/runtime.py, line 864:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/opt/LazyLibrarian/mako/runtime.py, line 829:
**_kwargs_for_callable(callable_, data))
/opt/LazyLibrarian/mako/template.py, line 445:
return runtime._render(self, self.callable_, args, data)
/opt/LazyLibrarian/lazylibrarian/webServe.py, line 69:
title="Database Upgrade", timer=5)


________________________________

**Comment by Viper911** [comment]
Also when going to the log screen I get a popup:  DataTables warning (table id = 'log_table'): Requested unknown parameter '3' from the data source for row 0

I can get to books screen without error it seems, but have no faith that its really working..

Thoughts?



________________________________
From: Mark Heaps <markheaps@hotmail.com>
Sent: Sunday, October 29, 2017 6:10:55 AM
To: DobyTang/LazyLibrarian
Subject: RE: [DobyTang/LazyLibrarian] New Updates (#1089)

Well, I did the pull and restarted, now the Auther screen is empty (no Authors listed)..  If I go to the setting screen I get the below errors.  In any case, something got messed up.  Perhaps the DB needs updating or something now?

Error !
KeyError: 'SORT_DEFINITE'
<input type="checkbox" id="mag_tab" name="mag_tab" value=1 ${checked} /> <label> Show Magazines</label> <br> <% if lazylibrarian.CONFIG['SORT_DEFINITE'] == True: checked = 'checked="checked"' else: checked = '' %>
/opt/LazyLibrarian/data/interfaces/default/config.html, line 182:
<%
/opt/LazyLibrarian/data/interfaces/default/base.html, line 157:
${next.body()}
/opt/LazyLibrarian/mako/runtime.py, line 890:
callable_(context, *args, **kwargs)
/opt/LazyLibrarian/mako/runtime.py, line 864:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/opt/LazyLibrarian/mako/runtime.py, line 829:
**_kwargs_for_callable(callable_, data))
/opt/LazyLibrarian/mako/template.py, line 445:
return runtime._render(self, self.callable_, args, data)
/opt/LazyLibrarian/lazylibrarian/webServe.py, line 69:
title="Database Upgrade", timer=5)


________________________________

**Comment by Viper911** [comment]
Never mind, although I stop and restarted that didn’t seem to work, but I rebooted the Ubuntu box and its come up again.  Still testing, but not seeing the errors I noted anymore.

________________________________
From: Mark Heaps <markheaps@hotmail.com>
Sent: Sunday, October 29, 2017 6:17:42 AM
To: DobyTang/LazyLibrarian
Subject: RE: [DobyTang/LazyLibrarian] New Updates (#1089)

Also when going to the log screen I get a popup:  DataTables warning (table id = 'log_table'): Requested unknown parameter '3' from the data source for row 0

I can get to books screen without error it seems, but have no faith that its really working..

Thoughts?



________________________________
From: Mark Heaps <markheaps@hotmail.com>
Sent: Sunday, October 29, 2017 6:10:55 AM
To: DobyTang/LazyLibrarian
Subject: RE: [DobyTang/LazyLibrarian] New Updates (#1089)

Well, I did the pull and restarted, now the Auther screen is empty (no Authors listed)..  If I go to the setting screen I get the below errors.  In any case, something got messed up.  Perhaps the DB needs updating or something now?

Error !
KeyError: 'SORT_DEFINITE'
<input type="checkbox" id="mag_tab" name="mag_tab" value=1 ${checked} /> <label> Show Magazines</label> <br> <% if lazylibrarian.CONFIG['SORT_DEFINITE'] == True: checked = 'checked="checked"' else: checked = '' %>
/opt/LazyLibrarian/data/interfaces/default/config.html, line 182:
<%
/opt/LazyLibrarian/data/interfaces/default/base.html, line 157:
${next.body()}
/opt/LazyLibrarian/mako/runtime.py, line 890:
callable_(context, *args, **kwargs)
/opt/LazyLibrarian/mako/runtime.py, line 864:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/opt/LazyLibrarian/mako/runtime.py, line 829:
**_kwargs_for_callable(callable_, data))
/opt/LazyLibrarian/mako/template.py, line 445:
return runtime._render(self, self.callable_, args, data)
/opt/LazyLibrarian/lazylibrarian/webServe.py, line 69:
title="Database Upgrade", timer=5)


________________________________

**Comment by Viper911** [comment]
Seems everything is ok now.  The only thing I see in the logs that looks out of place is:

2017-10-29 06:45:43

WARNING

cryptography: module missing

2017-10-29 06:45:43

WARNING

OpenSSL missing module/attribute: No module named OpenSSL.SSL

2017-10-29 06:45:43

WARNING

pyOpenSSL: module missing


Anything to be concerned about?

________________________________
From: Mark Heaps <markheaps@hotmail.com>
Sent: Sunday, October 29, 2017 6:28:09 AM
To: DobyTang/LazyLibrarian
Subject: RE: [DobyTang/LazyLibrarian] New Updates (#1089)

Never mind, although I stop and restarted that didn’t seem to work, but I rebooted the Ubuntu box and its come up again.  Still testing, but not seeing the errors I noted anymore.

________________________________
From: Mark Heaps <markheaps@hotmail.com>
Sent: Sunday, October 29, 2017 6:17:42 AM
To: DobyTang/LazyLibrarian
Subject: RE: [DobyTang/LazyLibrarian] New Updates (#1089)

Also when going to the log screen I get a popup:  DataTables warning (table id = 'log_table'): Requested unknown parameter '3' from the data source for row 0

I can get to books screen without error it seems, but have no faith that its really working..

Thoughts?



________________________________
From: Mark Heaps <markheaps@hotmail.com>
Sent: Sunday, October 29, 2017 6:10:55 AM
To: DobyTang/LazyLibrarian
Subject: RE: [DobyTang/LazyLibrarian] New Updates (#1089)

Well, I did the pull and restarted, now the Auther screen is empty (no Authors listed)..  If I go to the setting screen I get the below errors.  In any case, something got messed up.  Perhaps the DB needs updating or something now?

Error !
KeyError: 'SORT_DEFINITE'
<input type="checkbox" id="mag_tab" name="mag_tab" value=1 ${checked} /> <label> Show Magazines</label> <br> <% if lazylibrarian.CONFIG['SORT_DEFINITE'] == True: checked = 'checked="checked"' else: checked = '' %>
/opt/LazyLibrarian/data/interfaces/default/config.html, line 182:
<%
/opt/LazyLibrarian/data/interfaces/default/base.html, line 157:
${next.body()}
/opt/LazyLibrarian/mako/runtime.py, line 890:
callable_(context, *args, **kwargs)
/opt/LazyLibrarian/mako/runtime.py, line 864:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/opt/LazyLibrarian/mako/runtime.py, line 829:
**_kwargs_for_callable(callable_, data))
/opt/LazyLibrarian/mako/template.py, line 445:
return runtime._render(self, self.callable_, args, data)
/opt/LazyLibrarian/lazylibrarian/webServe.py, line 69:
title="Database Upgrade", timer=5)


________________________________

**Comment by philborman** [comment]
Not at the moment, but it could become a problem when GoodReads switch their system to https in December. What system are you running lazylibrarian on? there might be an easy fix

**Comment by Viper911** [comment]
Ubuntu 16.04

________________________________

**Comment by philborman** [comment]
You should be able to just
`apt install openssl python-openssl python-cryptography `
or use pip to install direct from python
