### ISSUE TITLE
Option to disable update check

### ISSUE THREAD

**Issue by chriscraig-nb** [DobyTang/LazyLibrarian#1091]
I'm using the Linuxserver/lazylibrarian docker container, and so I perform updates by pulling updated versions of that image every week or so.  

Every time I log into LazyLibrarian, I get a notification that there are updates available.  Now, this is good news!  It shows how active this project is, and I love that.  But, it would be great if I could turn off the update check and just get my updates by pulling a new image from Docker.

Am I just missing something in the config?

**Comment by philborman** [comment]
Not in config,  but you can disable update checks for 24hrs in the bookstrap interface. The popup has an ignore option.

Also in "version.py" if you change the install type to "Package" it disables updates as deb/rpm should be updated by their package managers.
