### ISSUE TITLE
Enhancement: Allow global reject list for Magazines, just like books and audiobooks

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1093]
My particular issue.
LL keeps sending .MP4 files to SAB and Deluge, as it thinks they are a match.

I would set a maximum size for magazines, but some of my magazines are several hundred MB, and the videos are smaller than that.

I would put reject filters in the individual magazines, but I have hundreds of them. That would take quite a while.

If we could have a global reject list for magazines (just like books, and audio-books have), that is used in parallel with the individual magazine filters...that would be the perfect solution. 

Thank you in advance.

**Comment by philborman** [comment]
ok, added that, will be in next release.

**Comment by MrMxyzptlk** [comment]
Excellent! Thank you.
