### ISSUE TITLE
[Feature Request] Add book via API

### ISSUE THREAD

**Issue by bishpuppy** [DobyTang/LazyLibrarian#1095]
I can add Author via name or id, same with Magazines, but i can't add a book.  I tried doing the queueBook but everything is NULL except the bookid and it doesn't appear on the web version.  Via web, I can add a book.

**Comment by philborman** [comment]
Not sure what you are trying to do.
If you want to ask lazylibrarian to download a book, queueBook or searchBook.
`queueBook&id=` just marks the book as wanted so the search tasks look for it next time.
`searchBook&id=` will search for it now (just search for one book, not all wanted books)

If you want to add a book you already have downloaded, `importAlternate&dir=`

**Comment by bishpuppy** [comment]
I can search for a book via `findBook` but I can't add it to the wanted list.  Via the web, I can search for a title of a book (`findBook` via API) but on the web, I have the option to add just the book to LL, via API that option seems to be missing.  I thought I could use the `queueBook` to get LL to add it to the wanted, but that only works partially.  I want to be able to add a book to LL's library as wanted, and have LL pull all the book details, and show it in the  Books section, all via an API command -- which LL already does if you do it from the web.  Right now my only option via API is to add the author, unless if the expected method to add a book via API is to add the author and then queue the book but that is not what the web does since the web does not add the Author to authors page.

**Comment by philborman** [comment]
Ah I see what you mean, not sure how to implement it though... 
Addbook from web search results let's you pick the one you want to download
findBook&name via api gives you a list of results, do you just queue the first one as that's the "best" match?
I could put a new addBook&id= command if you want to choose the right one?

**Comment by bishpuppy** [comment]
thats perfect.  Yeah, on my app, it will display the results and the user can choose the book they want.

**Comment by bishpuppy** [comment]
Just tested this and THANK YOU SO MUCH.
