### ISSUE TITLE
Seeing a lot of errors re: calibredb Error 1

### ISSUE THREAD

**Issue by Viper911** [DobyTang/LazyLibrarian#1098]
Postprocessing for ..... has failed: calibredb return 1 from /opt/calibre/

Where .... looks like its the book or author names

What is error 1? and how might I fix it..

**Comment by philborman** [comment]
Would need to see a debug log. Calibre doesn't seem to document it's exit codes, but may send us an error message along with the code, and we print the command we sent to calibredb in the debug log.

**Comment by philborman** [comment]
Latest version should dump everything that calibre returns to debug log, might help track it down...

**Comment by philborman** [comment]
There is another issue raised with calibredb returning error 1, in that issue its because calibredb is not found. Could it be the same problem you have?
Latest lazylibrarian version has a test button in config to check calibredb

**Comment by Viper911** [comment]
When hit the button it gives error permission denied but not sure anything changed when it was working.  Below is the permission on the file.  Htpc is the user and group name.  I’m logged in as htpc and can run it manually though.  Does LL use a different account?

-rwxrwxrwx  1 htpc htpc 6280 Oct 19 22:52 calibre

________________________________

**Comment by philborman** [comment]
calibredb return 1 from /opt/calibre/

I think it should be /opt/calibre/calibredb

**Comment by Viper911** [comment]
That worked, it used to not need the calibredb part.

BTW, now that I have a bunch of stuff that errored out when it tried calibre, is there a way to force it to scan the download directory again and do the processing?

________________________________

**Comment by philborman** [comment]
As long as lazylibrarian still has them as "wanted" just rename any directories ending in .fail and force postprocess
