### ISSUE TITLE
Global magazine filter not working

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1099]
I only have one thing in the global magazine filter to reject: mp4; however LL is still grabbing 'books' that have .mp4 at the end of the title?

**Comment by philborman** [comment]
Seems to be working here. If you put debug level to 3 you will get details of the postprocessing filters, including title, what's in the reject list, and what expression was passed in order to request the download. Just for fun I put pdf in my global reject list and _nothing_ got through ;-)

**Comment by MrMxyzptlk** [comment]
The only thing i have in the global magazine reject filter is 'mpg'.
I didn't search for anything, it's when LL runs it's daily search for wanted, I usually find a few videos being downloaded, and they all have mp4 in their titles.

I will enable debug level to 3, and see what happens tomorrow.

**Comment by philborman** [comment]
With debug level 3 you should get _loads_ of info about the search results, something like this for each result it found...
29-Oct-2017 15:52:04 - DEBUG   :: SEARCHMAG : searchmag.py:search_magazines:238 : Magazine matched: 100% Android Magazine for Android Welt 2017 06 GERMAN RETAiL MAGAZiNE eBOOk sUppLeX
29-Oct-2017 15:52:04 - DEBUG   :: SEARCHMAG : searchmag.py:search_magazines:257 : Reject: ['pdf']
29-Oct-2017 15:52:04 - DEBUG   :: SEARCHMAG : searchmag.py:search_magazines:258 : Title: android welt 2017 06 german retail magazine ebook supplex
29-Oct-2017 15:52:04 - DEBUG   :: SEARCHMAG : searchmag.py:search_magazines:259 : Bookid: android magazine
29-Oct-2017 15:52:04 - DEBUG   :: SEARCHMAG : searchmag.py:search_magazines:398 : regex 3 [Android Welt 2017 06 GERMAN RETAiL MAGAZiNE eBOOk sUppLeX] 2017-06-01
29-Oct-2017 15:52:04 - DEBUG   :: SEARCHMAG : searchmag.py:search_magazines:440 : Magazine Android Welt 2017 06 GERMAN RETAiL MAGAZiNE eBOOk sUppLeX failed: Expecting issue number
29-Oct-2017 15:52:04 - DEBUG   :: SEARCHMAG : searchmag.py:search_magazines:499 : Added Android.Welt.2017.06.GERMAN.RETAiL.MAGAZiNE.eBOOk-sUppLeX to pastissues marked Skipped

**Comment by MrMxyzptlk** [comment]
OK, I see in the log LL is rejecting a slew of magazines with mp4 in their titles. But some are still getting through?

Here is an example, I copied and pasted the name of the file from Deluge.

[UrbanTbc] To Love Ru Darkness OVA 10 (2017) [480P].mp4

**Comment by philborman** [comment]
Looks like that should fail magazine check on several counts... It contains mp4, it doesn't have a valid date, and the name doesn't look like a magazine title to me.

Can you post the debug log at level 3 as I mentioned earlier. Should contain 3 lines starting
Reject:
Title:
Bookid:
and then a few lines later there might be a line starting with regex and a number, which will show why we asked for the download instead of giving a reason for rejecting it.

**Comment by MrMxyzptlk** [comment]
I just emailed you the debug log file. Like I was saying you will see LL is rejecting lots of files with mp4 in the title and extension, but for some reason, doesn't do this with a few files?

**Comment by philborman** [comment]
Fixed in latest version

**Comment by MrMxyzptlk** [comment]
Thank you!

I have updated to the latest version.
