### ISSUE TITLE
Same magazine being downloaded every check

### ISSUE THREAD

**Issue by osuhickeys** [DobyTang/LazyLibrarian#1100]
Some but not all of the same magazines are being downloaded every time the check is ran for new magazines.  Post processing for them is not working correctly which I think is the root of the issue.  The magazines stay in the root of the download folder and do not get processed and renamed and moved into the _Magazines folder. SABnzbd shows error for the ones failing as "SABPostProcess - ERROR - No valid category detected"  When I check the ones failing as they are downloading SABnzbd shows their category correctly as Books which is what I have specified in SABnzbd to categorize requests coming from LL.  It is not all of the same magazine.  Some of a particular title work and others do not.  It is always the same titles that fail.

To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
"f748efc8ec7b3723db0f2aa026716fc7cbddf0bd"
### Operating system used (windows, mac, linux, NAS type)
Windows 10
### Interface in use (default, bookstrap)
Default
### Which api (Goodreads, GoogleBooks, both)
Both
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
Zip

**Comment by osuhickeys** [comment]
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1425221/debug.zip)

Here is the log file.

**Comment by philborman** [comment]
The SAB category could be because lazylibrarian is requesting a category that sab doesn't understand. Try the "test sab"  button and that should show an error of my guess is right. SAB needs the category to exist, and spelling is case sensitive.

The log you posted shows the requests sent to SAB, and SAB reports ok and gives us an ID.  Can you post a debug log of the postprocessor, with debug level 3

**Comment by osuhickeys** [comment]
Test SABnzbd produce a popup saying "SABnzbd connection successful".  The category in SABnzbd is "books"  It is also "books" in LL.

I shutdown LL, set the log level in the LL config.ini file to 3, and restarted.  Debug log file still shows it set to 2 if I am reading things correctly.  Is that the right way to change it to 2?

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1425329/debug.zip)

**Comment by osuhickeys** [comment]
I was not being precise when I first replied as I did not know it was case sensitive at the time.  It is a lower case "b" on both sides.Looks like log level was set to 3 this time.

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1425413/debug.zip)

**Comment by philborman** [comment]
Had a quick look at the debug log, thanks for that.
Seems lazylibrarian looks for 18 magazine issues in C:\Users\username\Downloads\complete\books
but there are only 3 folders found. Presumably the rest have not been downloaded by SAB or have been put in a different folder?

The three entries are...
_Magazines
Fname.Lname.USA.TruePDF-November.December.2017
Fname.Lname.USA.TruePDF-September.October.2017

The two Fname.Lname issues get rejected because...
 Nothing in database matching "Fname Lname"

**Comment by osuhickeys** [comment]
I removed all magazines from the web interface and confirmed the magazines table was empty.  I looked at the wanted table and I had magazines in there that were no longer in the web interface.  So, I deleted all files in the root download folder that were not being post processed and made sure the _Magazines folder was empty.  It deleted the files when they were removed from the web Interface.  I deleted all of the orphaned magazine related entries in the wanted table.

I now added just one magazine back and forced a search and post process.  I confirmed the name in the web interface matched the name in the magazines and wanted tables.  It successfully downloaded the magazines and processed them this time.  So it appears there were corrupt/orphaned entries in the wanted table that matched the names which was causing the problem.

**Comment by philborman** [comment]
Looks like I need to add some code to check the wanted table for orphaned entries. Could check the wanted table every time in the postprocessor, or maybe in the search tasks, so we don't try to search for magazines/books that are no longer in the database, or could delete from wanted table when deleting a magazine. Maybe we do that last one already, would need to check.

**Comment by philborman** [comment]
Added some code to delete orphaned entries now. Closing this, re-open if this doesn't fix it,
