### ISSUE TITLE
LL redirects to 127.0.0.1:5299 using reverse proxy

### ISSUE THREAD

**Issue by chriscraig-nb** [DobyTang/LazyLibrarian#1105]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
f748efc8ec7b3723db0f2aa026716fc7cbddf0bd
### Operating system used (windows, mac, linux, NAS type)
Linux 
### Interface in use (default, bookstrap)
bookstrap
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
linuxserver/lazylibrarian docker container

I have user accounts enabled and I have LL behind an NGINX (docker container) reverse proxy:

location /books {
    proxy_pass http://192.168.0.102:5299/books;
}

When I visit the site (http://mydomain.tld/books), I see the log in page just fine.  When I attempt to log in, I'm redirected to http://127.0.0.1:5299/books/home.  

If I then correct the url to http://mydomain.tld/books/home, I'm logged in and the app works.  I get the same problem when I log out.

Am I just setting up the proxy incorrectly?

**Comment by philborman** [comment]
Had a similar report a while ago. I think you need to untick http_proxy in lazylibrarian config.
Nginx doesn't need it, and if that box is ticked cherrypy looks for a header that Nginx doesn't set. It was added for apache, but I don't think we can tell which proxy is in use. 
After unticking the box and saving config you need to restart lazylibrarian or the cherrypy server won't pick up the new setting.

**Comment by chriscraig-nb** [comment]
That's exactly what the problem was.  Thanks!

**Comment by philborman** [comment]
Thought so. We really need to get that documented somewhere ;-)
