### ISSUE TITLE
GoogleBooks vs GoodReads

### ISSUE THREAD

**Issue by Viper911** [DobyTang/LazyLibrarian#1108]
More of a suggestion/enhacement

In the Importing section you can pick Goodreads or GoogleBooks from the drop down.  What is the advantage of using one over the other?  If this is for finding/matching books wouldn't I want it to use both? (ie. search goodreads first, if not found search GoogleBooks)

**Comment by philborman** [comment]
I had a look at this a while ago, and the main problem seems to be duplicate detection.
Some books/authors appear in googlebooks but not goodreads or vice-versa, some are in both.
Some have different author names (James Lovelock  vs  James E. Lovelock) for the same author
Some books with multiple or different authors appear under different names, eg the Jason Bourne series, first few were written by Robert Ludlum, the rest by Eric Van Lustbader, but google/goodreads disagree on who to file them under.
Some books are on google with a different isbn and a slightly different title to goodreads etc...
Would be a useful enhancement, but hard to manage

**Comment by Viper911** [comment]
So what I was thinking was just make that drop down the “Preferred” source.  Then the code pulls from that.  If found, done, if not found, then look at the other.  The idea isn’t so much figure out which is better or merge or anything, but rather have a book not fail matching if its only in one of the two and happens to not be what is in the drop down.  I notice in my logs when its processing errors like “not match found”, and just wondering if some of those would be found in the other source.

________________________________

**Comment by philborman** [comment]
The current method grabs a list of all the authors books from the preferred source. If you add a book by the author that isn't listed by that source we try the same source again in case it was rejected. There are several reasons why we might have rejected it first time round, things like doesn't match language preferences,  author name seems wrong, or wrong "role", book attributed to a different author, future publication date. If after all that it still isn't found maybe we could try the other source. I will have a look.

**Comment by philborman** [comment]
The book name matching code was a bit too strict on rescan, so I have rewritten the goodreads section so it matches better. Also I tried an option to use both goodreads and googlebooks at the same time, but that still throws up a lot of duplicates where the name is slightly different. Seems to cause more trouble than it is worth.  New version probably out tomorrow as long as the current round of testing looks ok.
