### ISSUE TITLE
Auto update fails

### ISSUE THREAD

**Issue by Meridiian** [DobyTang/LazyLibrarian#1113]
I have this running on my QNAP NAS but it keeps coming up with "unable to get latest version from github" when trying to update.

This is currently what is shown at the bottom of the config window:

Repo: https://github.com/dobytang/lazylibrarian : Branch: /bin/sh: /Apps/bin/git: No such file or directory
Current Version: GIT invalid hash return : Latest Version: Not_Available_From_GitHUB

How can I get LL to auto update via Github.

**Comment by philborman** [comment]
Looks as though lazylibrarian can't find the git program. Did you install from git? If so it must be on your NAS somewhere. If you can log into it over ssh, try `which git` to find where it is installed, then put that value into lazylibrarian config, or alternatively delete the `.git` subdirectory in the lazylibrarian folder. This will make lazylibrarian treat it as a "source" install and update using a zip file

**Comment by philborman** [comment]
Debug log should show errors trying to talk to git, this would probably help track it down.

**Comment by Meridiian** [comment]
I reinstalled git from OPKG and changed the config file to point to the new folder and all seems to be working fine now. Thanks
