### ISSUE TITLE
File Naming with Series Name / Info

### ISSUE THREAD

**Issue by claym** [DobyTang/LazyLibrarian#1114]
I've been digging around and trying to find out if it's possible? 

I'd like to be able to embed the series info into the epub / mobi or add it to the file name.

For example if I could name a file like "Game of Thrones (A Song of Fire and Ice #1) ?

**Comment by philborman** [comment]
There are a few options depending on why you want to do this...

You cannot use lazylibrarian to embed info, as we do not modify the original files. It could be added, but at the moment the libraries we use to get the metadata are read-only.

The filename pattern currently only allows $TITLE and $AUTHOR variables for the filename, but we store series information in the lazylibrarian database (as we do not modify the original files). You can edit the database info from the "Manual" page for each book. 

There are a couple of problems with storing the series info in the filename...
1. Some books are part of more than one series, which one do we use
2. If you share your library with calibre it will force-rename the files for you and remove everything except author/title anyway. 

It might be possible to work around the problems, but if you just want to be able to store and retrieve the series info yourself, the database already contains it, you could read it from there. If you want to save the info outside the database, each book has an accompanying .opf file, the series info could fairly easily be added to that file as it's plain text.

**Comment by claym** [comment]
Yeah, I'm trying to provide this all via Ubooquity.

How do I generate that .opf file? Can LL do this?

Thanks!

**Comment by philborman** [comment]
LL will create an .opf file for books during postprocessing, but only if config allows it to. 
There is a tick box in LL config, "Only import ebook, not opf or jpg"  If this is not ticked we will create an opf file. I had a quick look at the code and we _do_ put series info into the opf file. 

At the moment there is no way to create an opf file except during postprocessing, but this could easily be added as a new api command

**Comment by philborman** [comment]
Next version has two new api commands for writing out opf files  
writeOPF &id= [&refresh]
writeAllOPF [&refresh]
where refresh will overwrite an existing opf file

Also you can add a $Series variable to the filename format string. 
As long as you are not sharing the files with calibre it should be ok. If you are, or if we think you are, we won't rename the files.

Should be out tomorrow as long as testing overnight shows no problems.

**Comment by claym** [comment]
The writeOPF worked great, thank you!

Probably a dumb question, but what happens if you use $Series and there's no series information?

**Comment by philborman** [comment]
If there's no series information at all we just ignore it
If there's series name but no number (or a number we can't decipher) we just use the series name, eg 
(Song of Ice and Fire Book Two)
