### ISSUE TITLE
ImportError: No module named _sqlite3

### ISSUE THREAD

**Issue by mattyams** [DobyTang/LazyLibrarian#1116]
### Source of your LazyLibrarian installation (git, zip file, 3rd party package) git

Installed python and did a git clone.  When attempting to run I get this error. I am assuming it is something quite simple that I am overlooking.

`root@lazylibrarian_1:/LazyLibrarian # python LazyLibrarian.py -d
Traceback (most recent call last):
  File "LazyLibrarian.py", line 14, in <module>
    import lazylibrarian
  File "/LazyLibrarian/lazylibrarian/__init__.py", line 30, in <module>
    import sqlite3
  File "/usr/local/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3
`

**Comment by philborman** [comment]
Looks like your nas does not have a working  sqlite3 installation.
If you ssh into your nas you could type `sqlite3 --version` to check it.

**Comment by mattyams** [comment]
`[root@homenas] ~# sqlite3 --version
3.14.1 2016-08-11 18:53:32 a12d8059770df4bca59e321c266410344242bf7b
`
And from the jail:
`root@lazylibrarian_1:/ # sqlite3 --version
3.21.0 2017-10-24 18:55:49 1a584e499906b5c87ec7d43d4abce641fdf017c42125b083109bc77c4de48827
`

**Comment by philborman** [comment]
Looks like the python version in the jail is the problem.

**Comment by mattyams** [comment]
Think you can assist me on how to correct it?  I am assuming remove the sqlite3 version and install the older one?  I can understand how to remove it, but the second part...no idea.

**Comment by mattyams** [comment]
Ah, I figured it out. 

Needed to use `databases/py-sqlite3`
