### ISSUE TITLE
AudioBook Naming format not working

### ISSUE THREAD

**Issue by seanvree** [DobyTang/LazyLibrarian#1118]
LL Current Version: e24616d1e4bcb86090bf6ba06c39470f7faf8429 : 
OS: Windows 10E x64 1709
Interface: Bookstrap
API: both
Install: GIT

Current: Uaidobook filename pattern:

```
$Title - $Author - Part $Part of $Total
```

Issue:

Started recently, but the when the post-processor runs for audio books, it takes out all the spaces:

TheWisdomofPsychopathsWhatSaintsSpiesandSerialKillersCanTeachUsAboutSuccess.mp3

Ebooks are named fine:
The Wisdom of Psychopaths - Kevin Dutton.epub

Logs:

```
POSTPROCESS : postprocess.py:processDir:406 : Found match (100%): C:\Media\PlexDownloads\Books\Kevin Dutton - The Wisdom of Psychopaths for AudioBook Kevin Dutton - The Wisdom of Psychopaths
POSTPROCESS : postprocess.py:processDir:412 : Processing AudioBook vrPIaNGZY3UC
POSTPROCESS : postprocess.py:processDestination:1125 : BookType: audiobook, calibredb: []
POSTPROCESS : postprocess.py:processDestination:1155 : Copying 71A2+AZ8f8L._SL1500_.jpg to directory e:\books\The Wisdom of Psychopaths
POSTPROCESS : postprocess.py:processDestination:1177 : Ignoring unwanted file: info.txt
POSTPROCESS : postprocess.py:processDestination:1155 : Copying TheWisdomofPsychopathsWhatSaintsSpiesandSerialKillersCanTeachUsAboutSuccess.mp3 to directory e:\books\The Wisdom of Psychopaths
POSTPROCESS : postprocess.py:processDir:479 : Processed torznab: The Wisdom of Psychopaths - Kevin Dutton, http://192.168.1.20:9117/jackett/dl/iptorrents/?jackett_apikey=yta2gs8jaetdm4atln6nxabhcqt9uemd&path=Zkp1VWsyTkM3TWRMeklTSTN3aFpBMStpaElWNWVVeG5aNU50MnB1UlB1OUh3eUU0RkRzd0ovSElldXQ2bVBTZHJleVJYTURGTFowNUQyb1BxWFE5VDhieW45Y0ZBMDNwbFIvdVhoQVJkMG1CREt1V3dQUlRHeW8xTTdmbWNZanpnNC9LZXo2WWFXZ25LK2xlY0t6MUc3cS9oMWFEWmYwQVJMWUNUNTlWWkVhU2VVelF2TmdkNy9sMjZqWUlINFptOGg1MFRyM3lIRTJZanZCTEx6Z0IwRS9MVlFZN3VyZ2lXY1hsTFhWQmp4Qm9TMDBTV1h1ZFVxSXhxeUNNQ3JUTDNQQ3NRSnc1WFR4V3F4Qm5zcXJvZnE5TVBxYWVPOHEzZXc5ZVBZS1JqN0c4OEpLblJ3eXlqVXVJMU12TWoyK3lPaWJ1d0lPSzRzVC83T05ldngzcUMxV3ZDei9Sam13RDhzSTdHeGFBYjZ5djJiUGJKanZVcVJVZ0hCSnVad3lYOWVDZWVTbzdXeExxSVl0YmR2M3lhdWNyalBQeisxZFdMZUpSQlY4b3g2bzFRSWhtSVpvZnRHUlB4SGR6eklMUA2&file=Kevin+Dutton+-+The+Wisdom+of+Psychopaths
POSTPROCESS : bookwork.py:audioRename:69 : The Wisdom of Psychopaths found 1 audiofiles
POSTPROCESS : bookwork.py:audioRename:72 : The Wisdom of Psychopaths: Incorrect number of parts (found 0 from 1)
POSTPROCESS : postprocess.py:processDir:523 : DELUGERPC is seeding torznab Kevin Dutton - The Wisdom of Psychopaths
POSTPROCESS : postprocess.py:processDir:555 : Successfully processed: The Wisdom of Psychopaths - Kevin Dutton
```

**Comment by philborman** [comment]
The name with no spaces was found in the directory downloaded by deluge, this is prior to the lazylibrarian rename. Sadly it seems quite often that torrents have obfuscated or incorrect filenames. The jpg file also has a weird name. 
Lazylibrarian has not renamed it as it's a single file and we're expecting audiobooks to normally have lots of parts, we llink to part 1.
Are there any id3 tags in the mp3 file, if so is the name correct in the tag?
I will add some code to handle single file audiobooks, would be useful to know if it has anything in the tags with a part number (usually track number) and how many parts there should be (sometimes track number is n/nn eg 1/12)

**Comment by seanvree** [comment]
Understood. 

Nope. no tags with the original file. 

![image](https://user-images.githubusercontent.com/8906637/32790588-b017b51c-c913-11e7-9868-709684d5f04f.png)

**Comment by philborman** [comment]
Ok thanks. I will add some code for single file audiobooks with no tags
