### ISSUE TITLE
qbitorrent snatch always marked failed

### ISSUE THREAD

**Issue by wavesoup** [DobyTang/LazyLibrarian#1123]
Hi,

Snatching via qBittorrent seems to be broken. Log states qBit returns OK, but LL always considers it failed.
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1485249/debug.zip)

Version number: 35dbb17b923f2caeaad946637b98b6791a4229df
Docker (linuxserverio)

**Comment by philborman** [comment]
Yes, looks like it's been broken a while, or maybe it's down to different versions of qbittorrent?
We expect to get a json result, but your version is returning plain text. Easy enough to code around, will push a fix later today.
