### ISSUE TITLE
Log Page Issues

### ISSUE THREAD

**Issue by osinfield** [DobyTang/LazyLibrarian#1125]
Couple of issues -

1. Log page in Chrome refreshes as soon as it loads, making the page unusable.
2. Refreshing problem doesn't happen in Firefox but pagination doesn't work.

**Comment by philborman** [comment]
Both browsers working normally here.
Pagination is a datatables feature, would have thought that would behave the same whatever the browser was. Page refresh might well be browser dependent, but minimum refresh time is 5 seconds, so something else amiss I think.
 Anything unusual in the debug log?
