### ISSUE TITLE
Feature Request: Specify Default Missing Book action for books on a per author basis.

### ISSUE THREAD

**Issue by Hughlander** [DobyTang/LazyLibrarian#1126]
I have a few dozen authors I follow that have written books with a few dozen more authors.  Given how LL has set up the library structure my author list is about 70/30 ratio of those I don't care about vs do.  So I've set the default Missing Book to be Skipped.  But for that 30% I'd really like it to be Fetch.  Is there any possibility of being able to specify on a per author basis if it's skipped vs fetched?

**Comment by philborman** [comment]
You can do this using the bookstrap interface, but it can get complicated. 
On each author page, top left above the author picture is a button that says one of
` Active Wanted Paused Ignored`
Active = monitor for new books and take default action
Wanted = monitor for new books and mark them as wanted
Paused = don't monitor for new books
Ignored = don't monitor and don't show this author in lists

If set to Active, and the book is part of one or more series, default action depends on the status the various series are set to (wanted, ignored, skipped). If no series is marked wanted or ignored,
or if not in a series the config setting for new books is used.
