### ISSUE TITLE
&library=eBook Parameter missing when changing status of books

### ISSUE THREAD

**Issue by thehaven** [DobyTang/LazyLibrarian#1128]
I'm using commit: c617161fd3335b73ec1f26d87c989a83cecb8aa5

When browsing to <my url>/books and marking books as skipped/wanted etc then I get the following error:

```
404 Not Found
Missing parameters: library

Traceback (most recent call last):
  File "/opt/LazyLibrarian/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/LazyLibrarian/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/LazyLibrarian/cherrypy/_cpdispatch.py", line 67, in __call__
    raise sys.exc_info()[1]
HTTPError: (404, 'Missing parameters: library')
Powered by CherryPy 3.6.0
```

The URL loaded is:
```
<my url>/markBooks?booklang=None&redirect=books&action=Skipped&book_table_length=100&6516300=on
```

Looks like it should be suffixing the library parameter on the end and its not i.e.:
```
&library=eBook
```

If you need any more info then please let me know.

**Comment by philborman** [comment]
Odd bug introduced a couple of days ago, not sure how or why, makes no sense.
Fixed now, will push an update shortly. Thanks for the bug report.

**Comment by thehaven** [comment]
Thanks for the quick response that seems to have resolved my issue. I'll close this off.
