### ISSUE TITLE
So how do i post process and update LL from SAB

### ISSUE THREAD

**Issue by mgaulton** [DobyTang/LazyLibrarian#113]
After realizing i have been updating LL but didn't have downloaders turned on for some reason, i turned it on and noticed tones of stuff showing up in SAB with LL (###) tabs on the nzbs. This being reminicent of CouchPotato's tt(###) tagging. How do I get SAB to run a script and update LL with the download result etc. I looked and didn't see anything that jumped out at me.

    	Greg Bear - Queen of Angels (Queen of Angels, #1) LL.​(410766)

**Comment by mgaulton** [comment]
I've realized from watching the logs for a while, it is scanning the designated post-processing folder but I'm still interested in on demand if possible. (this might also make it workabel for nzbToMedia)

**Comment by daktak** [comment]
Your script could call http://localhost/lazylibrarian/forceProcess?source=books

**Comment by clinton-hall** [comment]
Just looking at this. I can certainly add this to nzbToMedia to force a process of the post-processing folder.

Just curious if it would be possible to add an option to pass a different directory in via forceProcess call?
