### ISSUE TITLE
LL wont start now

### ISSUE THREAD

**Issue by gilly65** [DobyTang/LazyLibrarian#1131]
QNAP decided to update their Python, from 2.7.12 to 2.7.12.1 and now when I try to start LL, I get this error;
Failed to start LazyLibrarian, /usr/bin/python2.7 was not found. Please re-install the Pythton qpkg.

It wont start, neither will CouchPotato, yet QCouchPotato will. Also, post processing with SickRage stopped too, on the QNAP page for their new Python, it says;

-If you use Python 2.7.12.1 need souce PATH /etc/profile.d/python2.bash

there is a path entry in /etc/profile.d/python2.bash;

_PYTHON2_QPKG_BIN="/usr/local/python2/bin"
echo "${PATH}" | grep -q  ${_PYTHON2_QPKG_BIN} || export PATH=${_PYTHON2_QPKG_BIN}:${PATH}

and I am lost at how to make this work again, any advice would be appreciated.

Thanks

**Comment by gilly65** [comment]
Also, when I try to start it from SSH, I get this;

Traceback (most recent call last):
  File "LazyLibrarian.py", line 14, in <module>
    import lazylibrarian
  File "/share/CACHEDEV1_DATA/.qpkg/LazyLibrarian/LazyLibrarian/lazylibrarian/__init__.py", line 33, in <module>
    from lazylibrarian import logger, postprocess, searchbook, searchrss, librarysync, versioncheck, database, \
  File "/share/CACHEDEV1_DATA/.qpkg/LazyLibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 26, in <module>
    from lazylibrarian import database, logger, utorrent, transmission, qbittorrent, \
  File "/share/CACHEDEV1_DATA/.qpkg/LazyLibrarian/LazyLibrarian/lazylibrarian/rtorrent.py", line 18, in <module>
    import xmlrpclib
ImportError: No module named xmlrpclib

**Comment by philborman** [comment]
Looks like from ssh you are finding python ok, but the new python is missing xmlrpclib
How are you starting it from ssh, are you using "python LazyLibrarian.py"? 
If so, what does "which python" say, and  "python - - version" as it might default to python3

**Comment by gilly65** [comment]
Yes, using python LazyLibrarian.py from the LL directory

those commands return this;

[~] # which python
/usr/local/bin/python
[~] # python - - version
Python 2.7.5 (default, Nov 17 2017, 02:44:57)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by philborman** [comment]
ok, so you are running the new python, (Nov 17 build date), but it doesn't have xmlrpclib

Maybe `pip install xmlrpclib` will get you further, but there might be more modules missing.

**Comment by gilly65** [comment]
-sh: pip: command not found

I will have to try to figure out how to get pip installed and working.

**Comment by philborman** [comment]
xmlrpclib and pip are both normally part of the default python installation.

You can download xmlrpclib from here `http://effbot.org/downloads/#xmlrpclib`, unpack it,  
and then in the unpacked xmlrpclib directory run:
python setup.py build
python setup.py install

**Comment by gilly65** [comment]
-sh: pip: command not found

I will have to try to figure out how to get pip installed and working.

**Comment by gilly65** [comment]
pip install xmlrpclib
Collecting xmlrpclib
  Could not find a version that satisfies the requirement xmlrpclib (from versions: )
No matching distribution found for xmlrpclib

I guess I do have pip, but it failed to install xmlrpclib.

**Comment by philborman** [comment]
Seems the xmlrpclib directory that pip looks at is empty. Try to use pip to install from source... you might need to be logged in as an administrator or use sudo...

pip install http://effbot.org/media/downloads/xmlrpclib-1.0.1.zip

**Comment by gilly65** [comment]
That gives me this:

Collecting http://effbot.org/media/downloads/xmlrpclib-1.0.1.zip
  Downloading http://effbot.org/media/downloads/xmlrpclib-1.0.1.zip
    Complete output from command python setup.py egg_info:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: invalid command 'egg_info'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /share/CACHEDEV1_DATA/.qpkg/Entware-ng/tmp/pip-tSLfof-build/


and still no reply from Qnap...

**Comment by philborman** [comment]
egg_info is part of setuptools, so it looks like your installation doesn't include that either.
pip install setuptools
or maybe your setuptools is outdated/broken
pip install --upgrade setuptools

**Comment by gilly65** [comment]
Cool, now it starts, I still get the message;
Failed to start LazyLibrarian, /usr/bin/python2.7 was not found. Please re-install the Pythton qpkg.
but it does run, however it seems that it has also reset, all my settings are gone and all authors and books are not showing up now.

It was 37 commits behind and it did update, the directory structure has changed but the config.ini and lazylibrarian.db are still in the config folder.

It appears it was Nov 9 when I upgraded Python and it quit, not sure if there was a major update since then or not that may have caused this.

**Comment by philborman** [comment]
It seems it's the new incomplet python installation that's the issue. Quite a few lazylibrarian changes since Nov 9th but nothing affecting config or database.  

If you are starting lazylibrarian yourself  using "python LazyLibrarian.py"  then add the --datadir parameter to the end pointing to your config folder ( the folder containing config.ini and lazylibrarian.db), something like...
python LazyLibrarian.py --datadir=/home/phil/.lazylibrarian/

**Comment by gilly65** [comment]
It wont start from the app center, but when I sue SSH it will, using this line
python /share/CACHEDEV1_DATA/.qpkg/LazyLibrarian/LazyLibrarian/LazyLibrarian.py --daemon --datadir=/share/CACHEDEV1_DATA/.qpkg/LazyLibrarian/config/

That gives way to this, but it is working better now, I can add that line to crontab if I have to.

Lazylibrarian is starting up...
[~] # 27-Nov-2017 14:32:23 - INFO :: MAIN : __init__.py:initialize:542 : Log level set to [1]- Log Directory is [/share/CACHEDEV1_DATA/.qpkg/LazyLibrarian/config/Logs] - Config level is [1]
27-Nov-2017 14:32:23 - INFO :: MAIN : __init__.py:initialize:548 : Screen Log set to INFO/WARN/ERROR
27-Nov-2017 14:32:23 - INFO :: MAIN : __init__.py:config_read:804 : Config file loaded
27-Nov-2017 14:32:23 - INFO :: MAIN : __init__.py:initialize:583 : Database is version 23, integrity check: ok
27-Nov-2017 14:32:23 - WARNING :: MAIN : __init__.py:initialize:602 : pyOpenSSL: module missing
27-Nov-2017 14:32:23 - WARNING :: MAIN : __init__.py:initialize:602 : OpenSSL missing module/attribute: No module named OpenSSL.SSL
27-Nov-2017 14:32:23 - WARNING :: MAIN : __init__.py:initialize:602 : cryptography: module missing
27-Nov-2017 14:32:24 - INFO :: MAIN : LazyLibrarian.py:main:196 : Starting LazyLibrarian on port: 5299, webroot ""
27-Nov-2017 14:32:24 - INFO :: MAIN : webStart.py:initialize:58 : Starting LazyLibrarian web server on http://0.0.0.0:5299/


All my authors and books are there now, thanks for that, I can live with a little quirkiness.

**Comment by philborman** [comment]
Couple of things...
1. It would be a good idea to move your datadir out of the main lazylibrarian folder, makes it easier if you have to reinstall for any reason. Do you have a home or user folder you can move it into?

2. GoodReads are going to be https only from some point in December, so the warnings about missing pyOpenSSL and cryptography might become an issue. You should be able to pip install them.

**Comment by gilly65** [comment]
FYI, if anyone else has this issue, don't upgrade Python, stay at 2.7.12
It is still located here;
https://download.qnap.com/QPKG/Python_2.7.12_x86_64.zip
