### ISSUE TITLE
Pushbullet notifications in LazyLibrarian

### ISSUE THREAD

**Issue by circa1665** [DobyTang/LazyLibrarian#1132]
I’m trying to setup pushbullet notifications, I have an access token but no deviceID. I’ve never had to use a deviceID with pushbullet before. Sorry if this is the wrong place to ask this.

**Comment by philborman** [comment]
Pushbullet deviceID is optional, you can use it to just send the notifications to one device. If the id field is empty, notifications get sent to all your pushbullet devices. The "test pushbullet" button will list your devices and their IDs.
