### ISSUE TITLE
LL not creating audio book covers...only 'question mark' images

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1133]
LL not creating audio book covers...only 'question mark' images.

It's obviously trying to create these from an mp3...which is not going to have an image.

**Comment by philborman** [comment]
LL doesn't try to create audiobook covers, it should use the ebook cover for the same title. Should first try for an image embedded in the ebook or cover.jpg in the ebook folder (if you have the ebook), if not it tries goodreads/librarything/googleimages and if none found it then displays questionmark. You can override it or add a cover using the api command getBookCover&id=   or by using the "manual" option on the audiobook page (under the book title). You should see some cover images to choose from at the bottom of the page.

**Comment by MrMxyzptlk** [comment]
None of my audio books have covers created so I will manually add them all.

Thank you.
