### ISSUE TITLE
Download directory enhancements

### ISSUE THREAD

**Issue by chriscraig-nb** [DobyTang/LazyLibrarian#1135]
I had a hiccup in my setup where books downloaded with NZBGet weren't getting processed and the issue turned out to be that I had assumed LL would interact with NZBGet to determine the download location based on the category directory set there. 

I had assumed that because the field to specify the download directory is under the Torrent side of the Downloaders config page.  This confused me, and I'm guessing I'm not the only one.

Can I suggest that either the download directories field is moved so that it's more obviously a global setting or better still, implement code to check with the downloader directly to determine the status of the download and it's directory.

Cheers & thanks for the hard work!

**Comment by philborman** [comment]
I see what you mean, I will change the text prompt. The position of the download directory field depends on the device you're viewing it on, it's on the end of the page on single column devices (tablets/phones) but end of the last column on wider screens.
 
It's not easy to check the directory with the downloader, as not all the downloaders offer that as an option. NZBget/sabnzb are ok, but the torrent downloaders are all different. Some rename the file when the torrent is complete, some move it to a completed directory, some do neither. Most offer a label option so you can put "books" into a different directory to "movies" so if we can get them all to put their completed book downloads into the same folder, lazylibrarian postprocessor can just check the one location.  Could be improved to query each download, but is it worth it...
