### ISSUE TITLE
Mark book as read?

### ISSUE THREAD

**Issue by jrc27** [DobyTang/LazyLibrarian#1139]
Would it be possible to add a column with a check box or something on the Authors page for marking a book as read?

**Comment by philborman** [comment]
Maybe a different "Status" for the book, "Read"  instead of "Open" for a book you have read?
or did you want to include books in the database you have read but are not in your library?

Would also need to account for different users, so needs to be user specific. Do-able, just need to think about the best way...

**Comment by Code-Slave** [comment]
this would work if this is how you manage everything. If you use calibre though and theres no way to sync  then not real useful

**Comment by philborman** [comment]
New version will display a bookmark on the status button for books you mark as "Read" or an empty bookmark for books you mark "To Read". Only works with bookstrap interface and user accounts enabled as the bookmarks are per user, not per library. You can mark books from the author/ebook/manage pages, and there's an "Unread" option to remove the bookmarks. Looks like this, top book is marked read, next one is marked to-read. No sync options yet. Feedback/thoughts would be appreciated.
![screenshot at 2017-12-13 10-58-26](https://user-images.githubusercontent.com/12158777/33932952-a75dc7de-dff4-11e7-9eb4-7e30a73e5e02.png)

**Comment by jrc27** [comment]
Looks good, but that leaves me with other issues...I don't have any user accts., just admin.  When i try to add a new user account i get the following error: 
New user NOT added
Failed to send email to blahblahblah@blahblah.com

Side not, I didn't know i could mark books as read in Calibre either.  I just looked and i can't seem to figure it out if it is possible.

**Comment by philborman** [comment]
Calibre - looks like you can do it in calibre by creating a custom column, but it's not a standard feature. I'm not going to worry too much about sync at this stage.

User accounts - if it's only you using your library, just use the admin account. You can set a flag in config to bypass login if there's only one user.

To add new users lazylibrarian tries to send the user an email giving them their password and access details. Not too crucial if lazylibrarian library is just for you.

**Comment by jrc27** [comment]
Oh, ok...i thought you said you had to have users enabled so the marked read/unread flag would show up.

**Comment by philborman** [comment]
Yes, you need user accounts enabled, but you can have only one user. With user accounts enabled LazyLibrarian keeps track of who is logged in so when you mark a book as read it's only marked for you.  


![screenshot at 2017-12-15 11-02-01](https://user-images.githubusercontent.com/12158777/34037004-6ab38a46-e187-11e7-8d1c-aee85434051e.png)

**Comment by jrc27** [comment]
I still must be doing something wrong...I'm up to date, have both boxes checked under access control and still don't have the option to mark as read.....ARGGGG! lol

**Comment by philborman** [comment]
Just added some debug code to help track it down, on my repository at github.com/philborman/lazylibrarian or will push it in a couple more days if you want to wait for it.

**Comment by philborman** [comment]
Just pushed a new version with more debugging. If you set loglevel to 4 you should see
getbooks userid nn read xx,yy  
where xx and yy are the total number of books you (nn) have marked as toread (xx), read (yy)
and later on you should see
getbooks page returning aa to bb, flagged xx,yy 
where xx and yy are the number of books flagged on the current page

**Comment by Code-Slave** [comment]
sorry I should have been more clear. Yes you need custom columns, most people who want to track that in calibre have read and toread columns. Also the majority of apps that talk to calibre on mobile will update this status if its defined.

**Comment by philborman** [comment]
I will have to look into that. Maybe the calibredb program can access calibre custom columns? I guess the user(s) would have to be able to specify the custom column names, perhaps you have multiple "read" and "toread" columns if the calibredb is used by multiple users (eg I have read the book, but my wife wants it "toread")

**Comment by philborman** [comment]
Had a bit of a play with this, seems creating custom columns is easy enough, and adding/removing books to/from each column is working ok. Have tied this to each user at the moment so you can each have your own read/toread columns synced with calibre. Might look at tying it into per-user goodreads sync too, but that is a bit more complicated. Also calibre gets a bit messy if there are too many custom columns.

**Comment by philborman** [comment]
Well, hit a bit of a brick wall with this one. Can't seem to find a way to get calibre to tell us the contents of a custom column, or the setting of a custom column for a particular book, which means we can write data to the columns but cannot read it back.

This means every time we sync we have to set the "read" and "toread" columns for every book as we have no way of knowing the current state. Also if you change state within calibre we will be unaware of the change and overwrite it. Not too satisfactory.

Also as each command for each book needs a separate call to calibredb its __very__ slow. No way of sending calibre a list (set column to True for this list of books)
Think I might skip calibre sync for now.

**Comment by philborman** [comment]
Managed to sort out how to read the calibre sync columns, but still have to send calibre each book status one at a time. Takes about 6 seconds per call on my pi3, tedious first time. After that it we only send changes, so it's getting almost usable.  Need to sort out how to set the per-user calibre columns in a way that gives some security, ie one user can't set the columns of another user.
