### ISSUE TITLE
Add ability to put magazines in autoadd dir

### ISSUE THREAD

**Issue by Code-Slave** [DobyTang/LazyLibrarian#1140]
Can you add the same options for mags as books? To copy to autoadd? Ideally a seperate dir (optional). With mags doing opf I can manage them in calibre pretty easy its just all by hand now

**Comment by philborman** [comment]
Never tried this, if you manually drop a magazine/opf/jpg into the autoadd directory does calibre import it ok? if so it's easy to add.  Also can calibre do more than one autoadd directory (one for books, one for mags)

**Comment by Code-Slave** [comment]
yes i hand copied stuff. Let me look into the autoadd as seperate dirs. I dont think calibre can do that.

**Comment by Code-Slave** [comment]
one think im looking at is a separate calibre docker just for mags. id really like them in a separate library to be honest so thinking along those lines an option to autoadd mags in an optional separate dir would work well there

**Comment by philborman** [comment]
If you run two separate calibre dockers, I think you should be able to have the "Magazine" one use the lazylibrarian autoadd directory, and the "book" one use calibredb to import books?

**Comment by Code-Slave** [comment]
Thats what i was thinking. I think this is probably the best way to go for me. i have 3 calibre dbs right now to help segment some of my books. I read ALOT (over 1900 "read" books in calibre).  if we have seperate dirs for mags and books autoadd in LL then i could use either way to add to calibre?

**Comment by philborman** [comment]
ok I will put a second autoadd directory in the next version. I guess we should autoadd pdf, opf, jpg or do you need the option to have pdf-only ? Its useful for books as we might have different authornames but probably not so useful for magazines.

**Comment by Code-Slave** [comment]
since we are creating the opf with mag title etc for uniformity then id say have option. its actually useful to have the opf. i had to kill and reinstall my docker as db was corrupted (on me not ll) se getting everything back to running again after holidays
