### ISSUE TITLE
Additional Parameters for eBook/AudioBook foldername Pattern

### ISSUE THREAD

**Issue by galacticat** [DobyTang/LazyLibrarian#1146]
Enhancement Request
It would be nice to have options for this setting for Series, and Series Number.

**Comment by philborman** [comment]
You can already add $Series to ebooks filename pattern,  it's a fixed format which includes the number if known, and produces something like "The Return Of The King (Lord of the Rings #3)"
It could be extended to be more flexible and maybe foldername too not just filenames. Its quite hard to get it to work with audiobook filenames though, because of the wide range of naming formats

**Comment by galacticat** [comment]
The organizational format I use to work with Booksonic is Author/SeriesName/Book - SeriesNumber - Title

I had tried $Author/$Series/$Title previously (thinking that $Series would produce the SeriesName value) , but it was producing a folder called "sSeries" at the time. I turned that off to prevent messing up my library. I'll have to do some more experimenting to see if that was something I setup wrong, or a bug.

It would be nice to split SeriesName and SeriesNumber into two separate variables

**Comment by philborman** [comment]
I left them together as a single variable as it's easier to strip them out for cases where there is no series info, or imcomplete info, so your example above doesn't create "Author/SeriesName/Book -  - Title", or "Author//Book -  - Title" if series info is incomplete or missing. The way we currently do it gives no series info if no seriesname. or (seriesname #seriesnum) or (seriesname)  depending on what we info we have. Maybe we need two folder/filename patterns depending if series info is there or not?

I have added $Series to audiobooks (wasn't as hard as I thought) and may add to foldernames tomorrow. Would need extra variables to separate seriesnum and seriesname so we don't break existing users settings. Just need to think about how to handle the missing data case.

**Comment by philborman** [comment]
Just pushed a new version with more configurable series variables. 
To do Author/SeriesName/Book - SeriesNumber - Title as per your example above, put SerName variable as just $SerName, and put SerNum variable as "Book - $SerNum -$$"  (without the quotes). If a book doesn't have any series details this will just generate Author/Title as the "Book - " and "-$$" get stripped if there is no value for $SerNum.  $$ generates a space on the end before Title, so you don't get left with a space if there is no $SerNum

**Comment by philborman** [comment]
Is this working as expected? If so I will close the issue

**Comment by galacticat** [comment]
It is
