### ISSUE TITLE
Redownload covers after move to new pc

### ISSUE THREAD

**Issue by Viper911** [DobyTang/LazyLibrarian#1147]
I moved the ini and db files over and it come sup on the new machine, however its missing all the covers.  Is there a way for it to either rescan the library (is on a nas) or force it to redownload all the covers?

**Comment by philborman** [comment]
They are all stored in the cache folder, you could copy that over as well, that would be fastest as very little needs to be downloaded. Alternatively for books you can use the api command getBookCovers

For magazines again the cache contains the covers, or just run libraryscan and that will extract them from the pdf files.
