### ISSUE TITLE
Support CORS in API

### ISSUE THREAD

**Issue by agc93** [DobyTang/LazyLibrarian#1153]
|Info|Value|
|:--|:---|
|LL Version|d0bdcc76f8c3b14a953a48779215ca3b01d84441|
|OS|Docker on Ubuntu 16.04|
|Interface|N/A|
|API|N/A|
|Installation Source|ls.io Docker image|

The HTTP API does not support CORS, making requests from any browser-based applications essentially impossible. 

Since it does not return any `Access-Control-*` headers, CORS requests (i.e. anything from a browser) fail with CORS errors. Can CORS support be added so that apps using browser-based JS can use the API without an additional reverse proxy?

**Comment by philborman** [comment]
The api code is derived from headphones, I guess that doesn't support CORS either.
Any idea what exactly needs to be added, or some example I can follow?

**Comment by agc93** [comment]
@philborman Yeah I can test it out. Without changes to the config screens, it will have to have some pretty insecure defaults, but I don't think that's the end of the world

**Comment by philborman** [comment]
I agree. You need to know the api key so that shouldn't be too much of a security issue.
I have some draft code here that adds basic cors support. Only on api calls, and all it does is  set Access-Control-Allow-Origin to the Origin sent in the request header, should be enough?  I will run a few more tests (there are other unrelated changes too) and post a new version later today on my git fork https://github.com/philborman/LazyLibrarian/

**Comment by philborman** [comment]
Pushed this to main branch now.  Returns the header if called using curl, but would be useful to know if it solves the issue.

**Comment by agc93** [comment]
@philborman Even using `curl` I don't seem to be getting any of the CORS headers returned from requests using your fork.

What options were you using to see the headers?

**Comment by philborman** [comment]
curl -i -H "Origin: http://www.dummysite.org" "http://127.0.0.1:5299/lazylibrarian/api"
HTTP/1.1 200 OK
Content-Length: 15
Vary: Origin
Server: CherryPy/3.6.0
Date: Fri, 12 Jan 2018 08:19:24 GMT
Access-Control-Allow-Origin: http://www.dummysite.org
Content-Type: text/html;charset=utf-8

Missing api key

**Comment by philborman** [comment]
Just noticed the cors header is only being sent if http_pass is enabled (it's in the wrong section)
Will fix this in the next release.
