### ISSUE TITLE
Library scan fails with non-alphanumeric characters 

### ISSUE THREAD

**Issue by nigelhooper** [DobyTang/LazyLibrarian#1155]
To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Log extract:
Now scanning subdirectory Kevin Mitnick/Ghost in the Wires

Unhandled exception in libraryScan: Traceback (most recent call last): File "/opt/lazylibrarian/lazylibrarian/librarysync.py", line 455, in LibraryScan book_filename = os.path.join(r, files) File "/usr/lib/python2.7/posixpath.py", line 80, in join path += '/' + b UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 63: ordinal not in range(128)

Book title: 
Kevin Mitnick - Ghost in the Wires- My Adventures as the World’s Most Wanted Hacker (epub).epub

It is falling over with several other books all the same librarysync.py", line 455

I believe it also doesn't like colons i.e.    :

**Comment by philborman** [comment]
It's a bit more complicated than that, unfortunately.
The problem with Ghost in the Wires is the apostrophe in "World's" which is not a regular ascii apostrophe. The apostrophe doesn't decode to utf-8 which is what we use as default for unicode in lazylibrarian. It __does__ decode correctly using latin-1 though, so I guess the file came from a windows filesystem at some point in it's history ;-)  
I've added some code to work around this, we had a similar problem with some scandinavian characters a while ago that would only decode in latin-1, which gave me the clue. Expect a new version shortly, just running some tests first.

The colon issue may be related, or may be something entirely different, not enough info to go on.
Colons are handled specially in a few places in lazylibrarian, eg goodreads often uses colon to separate the book title and subtitle, what exactly are you seeing?

**Comment by nigelhooper** [comment]
For clarity, whilst LL is running on linux the file store is windows (I know) and the copy and paste of the filename was done on windows.  Thanks in advance for the fix.  I have several books that are causing problems, I believe all the others are colon related, I will reproduce and then post details below.

**Comment by nigelhooper** [comment]
I have moved the books back into my library folder and it is not reproducing the bug.  It also saying that it is adding the same books to the library every time I run the scan. I had to restart and it is now generating the error again:

2018-01-03 21:31:28	ERROR	Unhandled exception in libraryScan: Traceback (most recent call last): File "/opt/lazylibrarian/lazylibrarian/librarysync.py", line 455, in LibraryScan book_filename = os.path.join(r, files) File "/usr/lib/python2.7/posixpath.py", line 80, in join path += '/' + b UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 63: ordinal not in range(128)

2018-01-03 21:31:27	WARNING	Updating book location for Jeremy Clarkson The World According to Clarkson from /mnt/eBooks/ByAuthor/Jeremy Clarkson/For Crying Out Loud_ The World According to Clarkson/Jeremy Clarkson - For Crying Out Loud_ The World According to Clarkson.epub to /mnt/eBooks/ByAuthor/Jeremy Clarkson/The World According to Clarkson/Jeremy Clarkson - The World According to Clarkson.epub

The filename is Jeremy Clarkson - For Crying Out Loud_ The World According to Clarkson.epub

The good reads details for the book is:
For Crying Out Loud! (The World According to Clarkson #3) by Jeremy Clarkson

**Comment by nigelhooper** [comment]
I am struggling to work out which books are causing errors as the error message doesn't list the book and it isn't always the bog in the previous log entry.  Any tips for tracking down which books are causing problems?

**Comment by philborman** [comment]
Hopefully fix will be out in a few hours, just running a complete library scan on my database to see if it throws any errors. 

The error character you are getting (0xe2) is a prefix for lots of extended characters, including the apostrophe you hit before, also a colon, and the minus sign you have in "Clarkson - For"
Not sure why this hasn't shown up before, looks like it should be a common enough problem.

Not easy to get a quick workaround, the error line is 455 in librarysync.py
so add a line just above saying 
logger.debug(files)
with the "l" of "logger" directly above the "b" of "book_filename"
will show the problem, but not fix the error.

**Comment by nigelhooper** [comment]
Thanks no need to rush the fix.  I am not sure on the Clarkson one, it may have been picking up the original Kevin Mitnick book, however a lot of clarksons books have none alphanumerics in.  I shall wait for the fix and try again.

Would it be possible to add "logger.debug(files)" to the debug logs e.g. "processing ....."

**Comment by philborman** [comment]
Pushed the new version tonight, hopefully fixed. 
> Would it be possible to add "logger.debug(files)" to the debug logs e.g. "processing ....."
I haven't added any extra logging, there is a line in the logs just before you hit the error saying "Now scanning subdirectory xxxx" which shows where the rogue filename is, though not the exact file. Should be enough, I think.
