### ISSUE TITLE
lost most magazine after update

### ISSUE THREAD

**Issue by dazedyep** [DobyTang/LazyLibrarian#1159]
To help with identifying and fixing issues, please include as much information as possible, including:
### installed via synocommunity package

after update of LL today; all but one magazine has disappeared from Magazines page. running a LibraryScan I can see in the log that magazinescan.py is running and finding all the magazines ok, but they are just not showing up on the page.

**Comment by Code-Slave** [comment]
I just updated that code, I'm looking into it now

**Comment by philborman** [comment]
Magazines are still there, just a display issue. Reverted yesterdays changes for now, should get you up and running again ;-)

**Comment by Code-Slave** [comment]
Phill. I fixed the main issue. now im unsure how to do pr as changes reverted.

**Comment by dazedyep** [comment]
that was quick - just updated and all is displayed again. Thanks!

**Comment by philborman** [comment]
git pull --rebase . upstream/master
that will pop off your local commits, pull the dobytang changes down to your fork, then push your commits back on. Your fork can then do a pr.
