### ISSUE TITLE
Magazines

### ISSUE THREAD

**Issue by mccorkled** [DobyTang/LazyLibrarian#1165]
Is there a way to force USA issues? Nat Geo is grabbing every country and every other magazine they have such as Nat Geo Kid and I have to go through and manually pick each one. Additionally, do you know of a program that can be used to read magazines similar to Calibre?

Thank you.

**Comment by philborman** [comment]
National Geographic is a bit of a problem as there are so many variants. With other mags like "Maxim USA" or "Maxim South Africa" "Maxim UK" etc there are not too many so you can put the ones you don't want as excluded words in the config->reject words, eg South,UK  for the above example. Might need to be a long list for Nat Geo though, and it doesn't handle ones that don't say which one they are in the title eg "Maxim January 2018". Can't think of a better way at the moment...

Magazines are usually pdf files, so I just read them in chrome with a pdf viewer extension. I have it set to open automatically on download so when I click on a magazine in lazylibrarian it opens straight up.

**Comment by mccorkled** [comment]
I am trying to avoid using a browser since we are running this off a NAS and streaming all of our content. I'll add the rejected words though, thanks.

**Comment by philborman** [comment]
The "required words" list is the title, so National Geographic USA requires all 3 words although you might need to adjust the "search match ratio" as National Geographic USA is 90% the same as National Geographic and the default is 90%, I think. It's so close a match because USA is a short word.

Past issues per-magazine list should be easy enough to add

auto update off can be done by setting the Version Check Interval to zero

**Comment by mccorkled** [comment]
I cannot seem to locate Version Check Interval. 
Thanks

**Comment by philborman** [comment]
It's in config -> processing in the Intervals section. Top of page or left column depending on your screen layout. Takes effect after a restart.

Past issues per-magazine list is done, should be new version out tomorrow

**Comment by mccorkled** [comment]
Ok wonderful. As always, thanks!!! I will close this now and work on getting the magazines working better for me.
