### ISSUE TITLE
Jackett

### ISSUE THREAD

**Issue by LordJay23** [DobyTang/LazyLibrarian#1166]
Has anything changed lately with the way that Torznab providers are called?  I've recently started getting 400 errors from Jackett for all searches.  Trying to figure out if something has changed in LL or something has changed in Jackett.

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report.

**Comment by philborman** [comment]
I would initially suspect Jackett, I don't use it myself, my torznab server is cardigann and that's still working.
I did some testing with Jackett a few months ago so could get a server up and running to try maybe tomorrow. What version Jackett are you on, and what error are you getting? 400 is Bad Request which would seem to mean we are talking to it, but not correctly.  There were some changes to Jackett api quite a few months ago. The format of the api call changed but we should handle the old style and the /api/v2.0/ style calls. A debug log of a book/mag search would help.

**Comment by philborman** [comment]
Just tried with Jackett Version 0.8.566.0 and seems to be working ok. Would need more info, debug log, versions etc.

**Comment by LordJay23** [comment]
`6-Jan-2018 22:19:00 - DEBUG   :: SEARCHBOOK : providers.py:IterateOverNewzNabSites:252 : [IterateOverTorzNabSites] - https://redacted.host/user/jackett/torznab/myanonamouse
06-Jan-2018 22:19:00 - DEBUG   :: SEARCHBOOK : providers.py:NewzNabPlus:574 : [NewzNabPlus] searchType [book] with Host [https://redacted.host/user/jackett/torznab/myanonamouse] mode [torznab] using api [pf0yfo1hcoad8cwh0lat4bm6vq
7tkrvu] for item [{'bookSub': u'The Unexpected Triumph of Old Media In the Digital Age', 'bookid': u'23493736', 'bookName': u'Television Is the New Television', 'library': 'eBook', 'authorName': u'Michael Wolff', 'searchterm': u'Michael W
olff Television Is the New Television: The Unexpected Triumph of Old Media In the Digital Age'}]
06-Jan-2018 22:19:00 - DEBUG   :: SEARCHBOOK : providers.py:ReturnSearchTypeStructure:750 : [NewzNabPlus] - torznab Search parameters set to {'author': u'Michael Wolff', 'apikey': u'APIKEY', 't': u'book', 'cat': 
u'8000,8010', 'title': u'Television Is the New Television'}
06-Jan-2018 22:19:00 - DEBUG   :: SEARCHBOOK : providers.py:NewzNabPlus:592 : [NewzNabPlus] URL = https://redacted.host/user/jackett/torznab/myanonamouse/api?author=Michael+Wolff&apikey=APIKEY&t=book&cat=
8000%2C8010&title=Television+Is+the+New+Television
06-Jan-2018 22:19:01 - ERROR   :: SEARCHBOOK : providers.py:NewzNabPlus:603 : Error reading data from https://redacted.host/user/jackett/torznab/myanonamouse: Response status 400: bad_request
06-Jan-2018 22:19:01 - INFO    :: SEARCHBOOK : providers.py:BlockProvider:215 : Blocking provider https://redacted.host/user/jackett/torznab/myanonamouse for 60 minutes because Response status 400: bad_request
06-Jan-2018 22:19:01 - DEBUG   :: SEARCHBOOK : providers.py:BlockProvider:222 : Provider Blocklist contains 1 entries
06-Jan-2018 22:19:01 - DEBUG   :: SEARCHBOOK : providers.py:NewzNabPlus:680 : No data returned from https://redacted.host/user/jackett/torznab/myanonamouse for Michael Wolff Television Is the New Television: The Unexpected Triumph
 of Old Media In the Digital Age
06-Jan-2018 22:19:01 - DEBUG   :: SEARCHBOOK : providers.py:get_capabilities:78 : Using stored capabilities for https://redacted.host/user/jackett/torznab/torrentleech
06-Jan-2018 22:19:01 - DEBUG   :: SEARCHBOOK : providers.py:IterateOverNewzNabSites:252 : [IterateOverTorzNabSites] - https://redacted.host/user/jackett/torznab/torrentleech
06-Jan-2018 22:19:01 - DEBUG   :: SEARCHBOOK : providers.py:NewzNabPlus:574 : [NewzNabPlus] searchType [book] with Host [https://redacted.host/user/jackett/torznab/torrentleech] mode [torznab] using api [pf0yfo1hcoad8cwh0lat4bm6vq
7tkrvu] for item [{'bookSub': u'The Unexpected Triumph of Old Media In the Digital Age', 'bookid': u'23493736', 'bookName': u'Television Is the New Television', 'library': 'eBook', 'authorName': u'Michael Wolff', 'searchterm': u'Michael W
olff Television Is the New Television: The Unexpected Triumph of Old Media In the Digital Age'}]
06-Jan-2018 22:19:01 - DEBUG   :: SEARCHBOOK : providers.py:ReturnSearchTypeStructure:750 : [NewzNabPlus] - torznab Search parameters set to {'author': u'Michael Wolff', 'apikey': u'APIKEY', 't': u'book', 'cat': 
u'8000,8010', 'title': u'Television Is the New Television'}
06-Jan-2018 22:19:01 - DEBUG   :: SEARCHBOOK : providers.py:NewzNabPlus:592 : [NewzNabPlus] URL = https://redacted.host/user/jackett/torznab/torrentleech/api?author=Michael+Wolff&apikey=APIKEY&t=book&cat=
8000%2C8010&title=Television+Is+the+New+Television
06-Jan-2018 22:19:02 - ERROR   :: SEARCHBOOK : providers.py:NewzNabPlus:603 : Error reading data from https://redacted.host/user/jackett/torznab/torrentleech: Response status 400: bad_request
06-Jan-2018 22:19:02 - INFO    :: SEARCHBOOK : providers.py:BlockProvider:215 : Blocking provider https://redacted.host/user/jackett/torznab/torrentleech for 60 minutes because Response status 400: bad_request
06-Jan-2018 22:19:02 - DEBUG   :: SEARCHBOOK : providers.py:BlockProvider:222 : Provider Blocklist contains 2 entries
06-Jan-2018 22:19:02 - DEBUG   :: SEARCHBOOK : providers.py:NewzNabPlus:680 : No data returned from https://redacted.host/user/jackett/torznab/torrentleech for Michael Wolff Television Is the New Television: The Unexpected Triumph of Old Media In the Digital Age
06-Jan-2018 22:19:02 - DEBUG   :: SEARCHBOOK : providers.py:IterateOverNewzNabSites:248 : [IterateOverNewzNabSites] - https://redacted.host/user/jackett/torznab/myanonamouse is BLOCKED
06-Jan-2018 22:19:02 - DEBUG   :: SEARCHBOOK : providers.py:IterateOverNewzNabSites:248 : [IterateOverNewzNabSites] - https://redacted.host/user/jackett/torznab/torrentleech is BLOCKED
06-Jan-2018 22:19:02 - INFO    :: SEARCHBOOK : searchbook.py:search_book:265 : NZB Searches for eBook Michael Wolff Television Is the New Television: The Unexpected Triumph of Old Media In the Digital Age returned no results.`

**Comment by LordJay23** [comment]
This appears to be the same issue as #1056 -- I followed the recommendation there, and it worked.  However, I know this WAS working before.  Weird.  Also, do you know if the searches honor the categories if you use the general search?

**Comment by philborman** [comment]
Yes they still use the categories in general search.

This problem is something to do with the way jackett works with the "capabilities" request, I think
Maybe jackett tells us the upstream provider supports "book" when it doesn't, or maybe jackett tells us thet jackett supports book, rather than what the upstream provider says. Can't be sure who generates the 400 error. Difficult to track down as I can't reproduce it, I don't have an account with MAM any more, had a trial one a while ago for testing that was closed due to inactivity.
