### ISSUE TITLE
Request: Automatic Updating!

### ISSUE THREAD

**Issue by ethanopp** [DobyTang/LazyLibrarian#1167]
Love the app and all the progress that you've been making - every time I check back in on it there's a new update!

Would be great if LL could self update itself automatically - this inst already an option is it?

**Comment by philborman** [comment]
Not easy to do as you need to restart lazylibrarian after each update. Can't really automate that in case you are in the middle of doing something at the time. At the moment we just show a pop-up saying there is an update available. The bookstrap interface pop-up has buttons to start the upgrade or stop nagging for 24 hrs so you can choose to upgrade when you are ready.
