### ISSUE TITLE
Fixing an error with config file?

### ISSUE THREAD

**Issue by dma9** [DobyTang/LazyLibrarian#1169]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)

b0f8c37401c1c88fc21c0e657c8a095346e7764c 

### Operating system used (windows, mac, linux, NAS type)

Ubuntu 17.10 in an LXC container

### Interface in use (default, bookstrap)

bookstrap

### Which api (Goodreads, GoogleBooks, both)

Goodreads

### Source of your LazyLibrarian installation (git, zip file, 3rd party package)

git

### Relevant debug log with api keys and any passwords redacted

WARNING | Unable to create new config file: /var/lib/lazylib IOError [Errno 13] Permission denied: '/var/lib/lazylib.new'

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

I think the one line will be sufficient for this particular issue. First, I will apologize, the root cause of the difficulty I'm encountering arose because of an error on my part. Unfortunately, I can't quite seem to figure out how to resolve it and am hoping some kind soul can point me in the right direction.

The specific issue that I noticed is that none of the configuration settings were saved upon a restart of LazyLibrarian. In examining the logs, I noticed that LL was trying to write a config file where it wasn't supposed to be writing it. I then figured out that this was because I had made an error when first setting it up. More specifically, in `/opt/LazyLibrarian/init/lazylibrarian.default`, I had mistakenly set `CONFIG=/var/lib/lazylib` (as I thought I needed to set the folder, not the full path and file name - unfortunately I did not notice the comments right above that line in the file when configuring). I then followed the rest of the instructions in `INSTALL.txt`. Of course, because of how I set `CONFIG=` up, LL could not write the config file (as shown in the log entry above.

When I realized my error, I stopped the service, revised `/opt/LazyLibrarian/init/lazylibrarian.default` to reflect `CONFIG=/var/lib/lazylib/config.ini` and followed the rest of the installation steps. I also disabled and enabled the lazylibrarian service, and all executed `systemctl daemon-reload`. I also tried restarting the container. I also checked the various files in `/etc/default`, `etc/init.d` and so on and they all seemed to be in order (i.e. wherever where was CONFIG specified, it was set to `/var/lib/lazylib/config.ini`

However, despite making the above changes, and several attempts at restarting the service and the container, I still keep getting the error in the LL log - i.e. LL still tries to create `/var/lib/lazylib.new` rather than `/var/lib/lazylib/config.ini`. Unfortunately I'm at a loss on what else to change to make LL point to the correct file. Any thoughts or suggestions would be most appreciated.

**Comment by philborman** [comment]
Hmm, looks like it should be trying to create /var/lib/lazylib/config.new  
The idea is we create a config.new, rename the old config.ini to config.bak, then finally rename config.new to config.ini

Not sure how your container is set up, ie how you actually start the lazylibrarian process. 
Could be your startup script passes --config on the commandline which would overrule the setting in the lazylibrarian.default file, or maybe your startup script uses info it read from the .default file before you changed it, or uses it's own copy of the .default file before you changed it?

If you use the lazylibrarian inbuilt debug log generator it will show the startup command used, which would narrow down where to look.

**Comment by dma9** [comment]
Thanks very much for the note. In terms of the set up, I followed the instructions in /opt/LazyLibrarian/init/INSTALL.txt, more or less to the letter. I was about to provide the specific details and contents in my file and log output but then noticed something in the logs, where it seemed to now be properly writing to the correct config file. In going through the logs the only thing that seems to have changed is that it pulled a new release late last night. I'm not sure if that's the reason it is now working, but in any event it is working now. In any event, thank you for pointing me in the right direction.
