### ISSUE TITLE
Calibre and Lazy Librarian in separate dockers

### ISSUE THREAD

**Issue by PeteJB** [DobyTang/LazyLibrarian#1171]
Hi,

I have lazy librarian installed in a docker and calibre installed in a separate docker. They both have access to the same library of books as they both reside on the same physical machine.

I've been trying to get lazy librarian to update the calibre database.

After reading this thread: https://github.com/DobyTang/LazyLibrarian/issues/1152 and the calibre reference guide: https://manual.calibre-ebook.com/generated/en/calibredb.html I think I know what the problem is.

I have the calibre content server started with username and password authentication and a username/password created and also have coded the IP address and port of the server (as well as user name and password) in the lazy librarian configuration. I have ticked the line to say use calibre content server. The calibredb location is blank as calibre is not installed in the docker.

When lazy librarian downloads the book it copies it into the library correctly, but never updates calibre. The only line that seems to be of interest in the debug log is this:
08-Jan-2018 01:30:44 - DEBUG :: POSTPROCESS : postprocess.py:processDestination:1165 : BookType: ebook, calibredb: []

I've come to the conclusion that lazy librarian cannot update calibre because it has no access to the calibredb program which is used to:
1. update the calibre database directly OR:
2. send commands to the calibre content server (in my case) to update the calibre database

If I'm correct then running lazy librarian on a separate machine to the main calibre library requires an install of calibre on the machine with lazy librarian?

Hopefully that's clear.

Looking forward to your response and thanks for a great program.

**Comment by philborman** [comment]
Yes that's exactly it. If calibredb is in the calibre docker then lazylibrarian can't see it. Only a problem if both are in separate dockers.

The easy solution is to use a lazylibrarian docker that includes its own copy of calibredb, there is a link to one on the lazylibrarian home page. All you need do then is tell lazylibrarian the url  of the content server, and where calibredb is located. In the Thraxis docker I think it's /opt/calibre/calibredb but the "test calibre" button will let you know if I've remembered that wrong.

**Comment by PeteJB** [comment]
Thanks very much for the reply. I moved from the docker I was using to the Thraxis docker which includes calibre and it solved my problem.
