### ISSUE TITLE
Author folders creating with 700 permissions

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#1173]
Heya again :)  I'm still seeing some permissions issues, both with new magazine downloads and new Author folders.  The individual book directories are creating with 0755, as expected, but the author folder is creating with 0700.  The base folder is 0755, so it's not inheriting permissions.

I'm running FreeBSD, and it appears the permission changes are happening in some locations.  

I can occasionally just reset those folders, but I'd like to eliminate that step.

Thanks

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report.

**Comment by philborman** [comment]
Couple of things to check...
1. in your config_ini (or in debug log) can you check value of dir_perm
2. if you turn on loglevel 3 you will get lines in the log saying Failed to set permission %s for %s: %s %s"
which will show if there were problems. If there are no lines in the log it might be we aren't trying to set permission, or it might be we don't know it failed.

**Comment by DarkSir23** [comment]
Missed this, I'm setting that now and will let you know.

**Comment by philborman** [comment]
Think this may be fixed in current version, changes to umask, so closing this for now. Please reopen if its still an issue
