### ISSUE TITLE
Logging strangeness

### ISSUE THREAD

**Issue by LordJay23** [DobyTang/LazyLibrarian#1177]
This seems new:  I run lazylibrarian as a service with one of the command line options as -q

Starting today, it seems that -q sets the loglevel to 0, instead of 2, which is what it's always been.  This prevents any logging to file.  If I set the loglevel back to 2 in config, it also turns console logging on.

Did something change?

**Comment by philborman** [comment]
Yes, I noticed a while ago that it had been broken __forever__, the -q is meant to be "quiet" so errors and warnings only. Normal is 1, includes info messages, -d is debug, level 2 or more

**Comment by LordJay23** [comment]
I thought the -q was only to turn off console logging.  At least, that seems to be how it used to work.

**Comment by philborman** [comment]
Yes true, but the logfiles used to still contain everything, ignoring loglevel. 
-q will turn off console logging at startup and also sets loglevel to zero
If you later change loglevel inside lazylibrarian, console logging will remain off, the -q is only read at startup.
