### ISSUE TITLE
Unable to access nzbhydra

### ISSUE THREAD

**Issue by phairplay** [DobyTang/LazyLibrarian#1180]
Hi,
I’m running LazyLib version b6a1158ade421e99189b386994fa373749106a83
On windows 10
Bootstrap interface.

I’ve added my nzbhydra setting same as sonarr and radarr yet I see this error message in the logs

Error reading data from http://127.0.0.1/nzbhydra: Exception SSLError: hostname '127.0.0.1' doesn't match either of 'mydomain.com', 'www.mydomain.com'

Could you please tell me what I’m doing wrong?

Many thanks

**Comment by Code-Slave** [comment]
Turn on debug logging and add try again then send the logs here. That will make it fairly easy to figure out.

**Comment by philborman** [comment]
Could be you don't have ssl modules in your python setup? Debug log would show this.
Sonarr and Radarr are .NET/mono programs so will use their own ssl, not the python interface.

**Comment by phairplay** [comment]
Hi 
I'm at work at the moment if that's the case how would I resolve this?
My domain has ssl

**Comment by phairplay** [comment]
hi 
here is the debug log after doing a search. i've removed my api key and domain

```
09-Jan-2018 16:36:35 - DEBUG   :: WEBSERVER : webServe.py:clearblocked:3023 : Cleared 1 blocked provider
09-Jan-2018 16:36:38 - INFO    :: CONFIG_WRITE : __init__.py:config_write:991 : Config file [C:\LazyLibrarian\config.ini] has been updated
09-Jan-2018 16:36:47 - DEBUG   :: SEARCHMAG : searchmag.py:search_magazines:70 : Removing old magazine search results
09-Jan-2018 16:36:47 - INFO    :: SEARCHMAG : searchmag.py:search_magazines:73 : Searching for 1 magazine
09-Jan-2018 16:36:47 - DEBUG   :: WEBSERVER : webServe.py:startMagazineSearch:2648 : Searching for magazine with title: PlayStation uk
09-Jan-2018 16:36:47 - DEBUG   :: SEARCHMAG : providers.py:get_capabilities:78 : Using stored capabilities for http://127.0.0.1/nzbhydra
09-Jan-2018 16:36:47 - DEBUG   :: SEARCHMAG : providers.py:IterateOverNewzNabSites:234 : [IterateOverNewzNabSites] - http://127.0.0.1/nzbhydra
09-Jan-2018 16:36:47 - DEBUG   :: SEARCHMAG : providers.py:NewzNabPlus:607 : [NewzNabPlus] searchType [mag] with Host [http://127.0.0.1/nzbhydra] mode [nzb] using api [myapi] for item [{'searchterm': 'PlayStation uk', 'bookid': u'PlayStation uk'}]
09-Jan-2018 16:36:47 - DEBUG   :: SEARCHMAG : providers.py:ReturnSearchTypeStructure:755 : [NewzNabPlus] - nzb Search parameters set to {'q': u'PlayStation uk', 'apikey': u'myapi', 't': u'search', 'extended': u'1', 'cat': u'7010'}
09-Jan-2018 16:36:47 - DEBUG   :: SEARCHMAG : providers.py:NewzNabPlus:625 : [NewzNabPlus] URL = http://127.0.0.1/nzbhydra/api?q=PlayStation+uk&apikey=myapi&t=search&extended=1&cat=7010
09-Jan-2018 16:36:47 - ERROR   :: SEARCHMAG : providers.py:NewzNabPlus:636 : Error reading data from http://127.0.0.1/nzbhydra: Exception SSLError: hostname '127.0.0.1' doesn't match either of 'mydomain.com', 'www.mydomain.com'
09-Jan-2018 16:36:47 - INFO    :: SEARCHMAG : providers.py:BlockProvider:207 : Blocking provider http://127.0.0.1/nzbhydra for 60 minutes because Exception SSLError: hostname '127.0.0.1'...
09-Jan-2018 16:36:47 - DEBUG   :: SEARCHMAG : providers.py:BlockProvider:214 : Provider Blocklist contains 1 entries
09-Jan-2018 16:36:47 - DEBUG   :: SEARCHMAG : providers.py:NewzNabPlus:685 : No data returned from http://127.0.0.1/nzbhydra for PlayStation uk
09-Jan-2018 16:36:47 - DEBUG   :: SEARCHMAG : searchmag.py:search_magazines:174 : No results for magazine PlayStation uk
09-Jan-2018 16:36:47 - INFO    :: SEARCHMAG : searchmag.py:search_magazines:547 : Search for magazines complete
```

**Comment by philborman** [comment]
If you use the "save debug log" button on lazylibrarian log page it will add info on the software versions in use, and report any missing ones. It also strips the api keys/passwords to save you some work. 
I suspect one or more of the python ssl components is missing.

You can get the same info from the lazylibrarian api (if it's enabled) using the getDebug command

**Comment by phairplay** [comment]
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1616299/debug.zip)
sorry i missed this options

**Comment by philborman** [comment]
It looks like you are talking to nzbhydra on hostname '127.0.0.1'  and getting an ssl error as the ssl connection is expecting a name, not a number.  It seems you have openssl installed, which may be enough, maybe changing lazylibrarian config to use hostname would be enough to fix it, eg https://www.yourhostname.com ? 

The debug log shows...
pyOpenSSL: module missing
OpenSSL missing module/attribute: No module named OpenSSL.SSL
cryptography: module missing

On a linux system you would just use "pip install" to add them in. Installing pyOpenSSL makes the first two warnings go away. The third one (cryptography) might go away too if it's already included in the windows version of ssl, not sure.

A quick google threw up a possible solution here... 
https://www.experts-exchange.com/questions/28530165/Issues-Installing-pyOpenSSL-for-Python-2-7-in-Windows.html
and cryptography is here...
https://cryptography.io/en/latest/

**Comment by phairplay** [comment]
Thank you
I thought I had tried this, but it's working now.
