### ISSUE TITLE
Invalid schema

### ISSUE THREAD

**Issue by PeteJB** [DobyTang/LazyLibrarian#1194]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
Current Version: 905ba68510f4b4f75f6ef5923192b00538c1b3d8 : Latest Version: 329cf3a03468a9a852c4d1222dfc85ef4b47bc4d

### Operating system used (windows, mac, linux, NAS type)
Linux Alpine 3.7 - Docker running under unraid

### Interface in use (default, bookstrap)
bookstrap

### Which api (Goodreads, GoogleBooks, both)
Goodreads

### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
linuxserver docker

### Relevant debug log with api keys and any passwords redacted
Relevant message from log (**edited to remove apikey**)
Error reading data from https//api.nzb.su: Exception MissingSchema: Invalid URL 'https//api.nzb.su/api?author=Dean+Koontz&apikey=<apikey_removed_here>&t=book&cat=7000%2C7020&title=Wilderness': No schema supplied. Perhaps you meant http://https//api.nzb.su/api?author=Dean+Koontz&apikey=<apikey_removed_here>&t=book&cat=7000%2C7020&title=Wilderness?

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report.

**Comment by philborman** [comment]
Over edited ;-)
We're missing a colon by the look of it, but can't tell from the section you posted which file/line numner generated the error. Could be a config file problem, maybe you missed the colon yourself in the config, or maybe you didn't include the http(s) section at all in which case we're adding it and getting it wrong. Either way we should be able to trap it and either fix it or give a better error msg, would be good to know where to look :-)

**Comment by PeteJB** [comment]
No probs Phil. Thanks for the reply. Will create a proper debug and post it.

**Comment by PeteJB** [comment]
My apologies and thanks for the pointer. Missing ":" in the config.

**Comment by PeteJB** [comment]
Tested and all good. Sorry for the false alarm.
