### ISSUE TITLE
Feature Request: Set status of audiobook to "have" and be able to manually point to folder in audibook library

### ISSUE THREAD

**Issue by PeteJB** [DobyTang/LazyLibrarian#1200]
I've had some trouble getting an audio book obtained outside of LL, recognised by LL even though I've put it in the correct library. 

I have updated the status to "Have", and thought that it would be handy to be able to click on the have button to update the database with the location.

**Comment by philborman** [comment]
Might be useful, will have a look.
For now the easy way is to put the audiobook into a folder that lazylibrarian expects ( something like audiobooklibraryfolder/author/title )  and then from the audiobook page run libraryscan (scans whole audiobook library),  or from the author page run audiobookscan (scans one author in audiobook library)

**Comment by philborman** [comment]
Don't seem to be able to use a file selector to choose a file, we only get the filename, not the path. Could use a text input box but it's a bit clunky and would need a lot of input validation for security. Might just leave it as-is for now.

**Comment by PeteJB** [comment]
Thanks. The pointer for mp3tags helped heaps. I can find the books now.
