### ISSUE TITLE
Exception in search_book

### ISSUE THREAD

**Issue by ezar** [DobyTang/LazyLibrarian#1202]
Unhandled exception in search_book: Traceback (most recent call last): File "/opt/lazylibrarian/lazylibrarian/searchbook.py", line 161, in search_book resultlist, nprov = IterateOverTorrentSites(book, searchtype) File "/opt/lazylibrarian/lazylibrarian/providers.py", line 320, in IterateOverTorrentSites results, error = KAT(book) File "/opt/lazylibrarian/lazylibrarian/torrentparser.py", line 212, in KAT soup = BeautifulSoup(result, 'html5lib') File "/opt/lazylibrarian/lib/bs4/__init__.py", line 165, in __init__ % ",".join(features)) FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

**Comment by philborman** [comment]
Oops, looks like I have missed a link somewhere. Not at home at the moment but if you
 pip install html5lib
That should get you going. I will look into what's wrong and fix it for the next update. Sorry about that!

**Comment by ezar** [comment]
Current Version: de772610795ba611d6a6268d75df5e901da8aab4

**Comment by philborman** [comment]
Latest version should be ba12f50
Can you try upgrading and see if that solves it.
Thanks.

**Comment by Code-Slave** [comment]
im on ba12f50

Unhandled exception in search_magazines: Traceback (most recent call last): File "/app/lazylibrarian/lazylibrarian/searchmag.py", line 131, in search_magazines tor_resultlist, nproviders = IterateOverTorrentSites(book, 'mag') File "/app/lazylibrarian/lazylibrarian/providers.py", line 322, in IterateOverTorrentSites results, error = TPB(book) File "/app/lazylibrarian/lazylibrarian/torrentparser.py", line 92, in TPB soup = BeautifulSoup(result, 'html5lib') File "/app/lazylibrarian/lib/bs4/__init__.py", line 165, in __init__ % ",".join(features)) FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

**Comment by philborman** [comment]
Found the problem, but unfortunately it's taking a while to fix.  The quick and simple fix for now is to 

pip install six
pip install webencodings

These are two libraries that are used by html5lib and are not installed on all python systems. We need to ship these with lazylibrarian and tell our copy of html5lib to use them if no system version is found.
Adding the system versions won't cause any conflicts later.
The earlier version of BeautifulSoup didn't use html5lib, but isn't compatible with python3 and we're getting close to having a working python3 version of lazylibrarian.  Maybe a day or two.

**Comment by Code-Slave** [comment]
ok. if you want me testing any python3 let me know

**Comment by philborman** [comment]
I pushed a fix yesterday for the missing libraries, should be working now.
There is a python3 version of lazylibrarian at https://github.com/philborman/LazyLibrarian3.git
it should all work if you want to have a play.

The current code for lazylibrarian3 has been auto-converted from the python2 version. The aim is eventually to get a single source that runs on both python2 and python3, the new "six" library should help with this.
