### ISSUE TITLE
Post Processing Multiple Directories

### ISSUE THREAD

**Issue by mccorkled** [DobyTang/LazyLibrarian#1203]
I have the download directory setup to be `/completed,/complete` but when post processing happens, it's not grabbing the book. 

[lazylibrarian.log](https://github.com/DobyTang/LazyLibrarian/files/1666390/lazylibrarian.log)

**Comment by philborman** [comment]
From the logs it looks like transmission is not putting the book in /completed or /complete
or is putting the book under a different name?

If you turn debug level up to 3 and run postprocessor you will get more info in the log, might show what's happening

**Comment by mccorkled** [comment]
Very interesting. Movies, TV, and music all are properly moving to /complete when done, but none of my books are. Any chance you can add a way to post process a user set set directory upon clicking? This way, books can be placed into a directory, processed with Calibre, and placed into a directory. 

Thanks

**Comment by philborman** [comment]
You can use the "alternate import" directory for this, but would be better to sort out why transmission isn't putting them in the right place

**Comment by mccorkled** [comment]
I have done more testing and even switched to qBittorrent, and the books are still not being moved to /completed. I tested both torrent clients with movies and tv shows and they are moving fine, but both clients are not moving ebooks. I believe this is due to the way LL is snatching the torrents.

**Comment by philborman** [comment]
Might be worth checking the torrent clients logs?
qBittorrent moves completed files according to the "label" applied, the label is configured in lazylibrarian.
transmission only uses one directory for downloads, doesn't use labels.

**Comment by barbequesauce** [comment]
It’s true that transmission doesn’t use labels, but you can simulate the behavior by having each manager application specify a download path. To illustrate, I have Mylar configured to send torrents to transmission using a download_dir of /transmission/completed/comics and LL using a download_dir of /transmission/completed/books...

**Comment by mccorkled** [comment]
I have qBittorrent set to have files in /incomplete and move to /complete upon finishing. In LazyLibrarian I have Download Directories set to /completed,/complete

**Comment by philborman** [comment]
What does the qbittorrent log say, does it think it moved the file to /complete or was there an error (permissions maybe?)

**Comment by philborman** [comment]
@barbequesauce Not sure how mylar does this, there doesn't seem to be an option in the transmission api to specify a download directory - api is here: https://trac.transmissionbt.com/browser/trunk/extras/rpc-spec.txt  which is presumably why headphones,  sickbeard etc don't offer the option.
Maybe mylar moves the files itself on completion?

**Comment by barbequesauce** [comment]
I'm guessing that spec is out of date, and the behavior I'm talking about might be unintentional. That said, I know Mylar, Headphones, and SickGear do it - and, in fact, you're doing it too by passing download_dir [here](https://github.com/DobyTang/LazyLibrarian/blob/4f7cfa792fc47519453fb73b1120f86e2bb0e0dc/lazylibrarian/transmission.py#L38). Note you have download_dir on a different config page... check the screens below to see how others implemented it.

Mylar is passing it [here](https://github.com/evilhero/mylar/blob/f091ac5fa2137d57b91c7026e5d5897aee8a07bd/mylar/torrent/clients/transmission.py#L75)

Headphones does it too - it is passing it [here](https://github.com/rembo10/headphones/blob/da9287d7cf6049a68266cf365c5b30e44d2d54a9/headphones/transmission.py#L43).

And SickGear does it [here](https://github.com/SickGear/SickGear/blob/783ddda80689b4628a330df627137b535598811e/sickbeard/clients/transmission.py#L71).

Not sure about Sickbeard as I don't use it.

GUI screenshot from Headphones:

<img width="474" alt="screen shot 2018-02-23 at 11 14 48 am" src="https://user-images.githubusercontent.com/25070944/36604739-94fc4612-188c-11e8-8153-7fa363a60d55.png">


GUI screenshot from Mylar:

<img width="435" alt="screen shot 2018-02-23 at 11 15 00 am" src="https://user-images.githubusercontent.com/25070944/36604723-8bc10e7a-188c-11e8-98bb-fd4a8e1d8a45.png">


GUI screenshot from SickGear:

<img width="800" alt="screen shot 2018-02-23 at 11 15 08 am" src="https://user-images.githubusercontent.com/25070944/36604706-7d4d5588-188c-11e8-8557-f384a9a3198b.png">

**Comment by mccorkled** [comment]
Here is the log. Check out book "Diet for a Small Planet"
https://pastebin.com/17sygXdG

It does indeed say permission issue, but what would be causing ONLY eBooks to have permission issues?

**Comment by philborman** [comment]
Think I've found it.
There is a problem if you have more than one download directory configured, and you pass that to a torrent downloader. Only affects transmission, and qbittorrent/deluge, I think.
Expect a fix shortly...

**Comment by mccorkled** [comment]
You are seriously wonderful.

**Comment by philborman** [comment]
Not so fast, I havent fixed it yet

**Comment by philborman** [comment]
Ok, need a little more help. Problem isn't where I thought it was. Can you try a download with qbittorrent again, with lazylibrarian debug log on, and look for the line that says "addTorrent args (xxxx xxxx xxxx)"
Only works with qbittorrent. Transmission doesn't include that log line (yet)

**Comment by mccorkled** [comment]
I can't find that line but here is my last log.
[lazylibrarian.log](https://github.com/DobyTang/LazyLibrarian/files/1752709/lazylibrarian.log)

**Comment by philborman** [comment]
Ok , thanks. please look out for the next book lazylibrarian sends to qbittorrent to download and send a redacted log of the section talking to qbittorrent. Should hopefully show us what's going on.  

Am I right in thinking you are running lazylibrarian in a docker, transmission in a different docker, qbittorrent in another docker?

At the moment I think given the permission issue in the pastebin log it might be that the qbittorrent docker /completed folder is not the same location as the lazylibrarian docker /completed folder

or maybe is not set to the same user

or maybe we are picking up the wrong folder (/completed instead of /complete)

I think lazylibrarian should tell the downloaders to use the __first__ folder in  /completed,/complete but maybe we are not? The debug line  "addTorrent args (xxxx xxxx xxxx)"  in the log will tell us.

**Comment by mccorkled** [comment]
Yes I am using all Dockers. I have mapped `qbittorrent/downloads/complete` to `/complete` in LL and `qbittorrent/downloads` to `/downloads` in qBittorrent. I am using this same structure for Radarr/Sonarr, and SABnzbd and it is working fine. SAB moves completed files to /complete and then Radarr/Sonarr read /complete, renames, and moves.

**Comment by philborman** [comment]
Bingo!
I think this is the problem...

In your latest post
>> I have mapped qbittorrent/downloads/complete to **/complete** in LL

In your first post, top of page
>> I have the download directory setup to be /completed,/complete

LazyLibrarian will tell the qbittorrent to put the files in the __first__ folder in it's download list (in your case **/completed**)  but you have mapped qbittorrent to **/complete** 

I would try setting lazylibrarian download directory to just **/complete**  or swapping the order to /complete, /completed

I don't think multiple download directories is much use in dockers, as you can map them around to the same space anyway. It's useful in situations outside dockers if you are downloading to different network drives, for example.

**Comment by mccorkled** [comment]
Each program needs it's own download location, hence /complete and /completed. Using this method is needed because within a program such as LL, if both download locations we called, /complete, you wouldn't be able to map them as two separate folders.

**Comment by philborman** [comment]
You should be able to set it up so that /complete in lazylibrarian maps to /media/Downloads/complete
and /complete in qbittorrent also maps to /media/Downloads/complete
and /complete in transmission also maps to /media/Downloads/complete 

If that isn't working it's probably permissions/ownership issues between the dockers. 

All your downloaders should be able to share the one folder (or folder tree), I have mine set as
/media/Downloads/complete/books
/media/Downloads/complete/Movies
/media/Downloads/complete/Audio
/media/Downloads/complete/TV
and the downloaders all share the same folder structure, using labels to place in the right subfolder.

**Comment by mccorkled** [comment]
I have mine set to:
Docker/Sabnzbd/Download/Completed
Docker/Sabnzbd/Download/Incomplete
Docker/qBittorrent/Download/Complete
Docker/qBittorrent/Download/Incomplete

Then in each Docker, I map
Docker/Sabnzbd/Download/Completed to /completed
and
Docker/qBittorrent/Download/Complete to /complete

**Comment by philborman** [comment]
ok, this is getting confusing.

Headphones seems to use two download directories, one for nzb, and another for torrents. We could fairly easily do the same on the assumption you only use one nzb client and one torrent client at a time (seems a reasonable assumption)

Sickbeard defaults to using one directory for everything, but has override options for each torrent provider (but not for nzb). Seems they might hit the same problem if sab/nzbget are in dockers and so is the torrent provider. If any one of torrent/nzb/lazylibrarian is NOT a docker, no problem.

Sonarr/Radarr don't use any directories, they query the downloaders for the location, which is quite a neat solution, but more work. They monitor the downloaders, we don't.

Maybe we go for the two folder option that headphones uses.

**Comment by mccorkled** [comment]
That sounds fine. I don't imagine anyone needing multiple usenet, and torrent clients.

**Comment by philborman** [comment]
In the end I went for separate directory entries in the config for the torrent downloaders that use them. You can leave it blank if the downloader default is ok.

**Comment by mccorkled** [comment]
So now do I need to add /complete to the qBittorrent settings or do I leave "/completed,/complete" under Download Directories?

**Comment by philborman** [comment]
Leave "/completed,/complete" under Download Directories (this tells lazylibrarian postprocessor where to look)

The separate transmission/qbittorrent directories can be left blank to use their own settings, or you can put a foldername here to override them. More flexible that way.

eg If transmission config file says downloads go in /complete  lazylibrarian will find them. Or lazylibrarian could tell transmission to use /complete/books  (as long as you also put /complete/books in lazylibrarian Download Directories)
