### ISSUE TITLE
GoodReads Sync Error

### ISSUE THREAD

**Issue by halethrain** [DobyTang/LazyLibrarian#1205]
Most recent git pull on Linux:

GoodReads sync either manually or via timer returns the following error. Books in "To Read" list are not imported. Configuration for GoodReads tests without issue. Syncing GR previously worked.

`Unhandled exception in grsync: Traceback (most recent call last): File "/opt/LazyLibrarian/lazylibrarian/grsync.py", line 501, in grsync gr_shelf = GA.get_gr_shelf_contents(shelf=shelf) File "/opt/LazyLibrarian/lazylibrarian/grsync.py", line 287, in get_gr_shelf_contents content = self.getShelfBooks(current_page, shelf) File "/opt/LazyLibrarian/lazylibrarian/grsync.py", line 360, in getShelfBooks raise Exception('Failure status: %s for page ' % response['status'] + page) TypeError: cannot concatenate 'str' and 'int' objects`

**Comment by philborman** [comment]
Problem is

**Comment by tkosig** [comment]
GR sync is broken, log shows this error message "Failure status: 403 for page 1" when sync is attempted. Configuration for GR tests without issue. GR sync worked before upgrading to 753687edfce21d95d6c68bc9d69e72d3bc15f118. First GR sync after upgrade actually removed books from "Wanted" list.

**Comment by tkosig** [comment]
Hey, thanks for quick & detailed reply. I've attached a [debug.log](https://github.com/DobyTang/LazyLibrarian/files/2114723/debug.log) of a GR sync with loglevel 1024. It seems that the 403 error appears when the page for the GR shelf is to be pulled.

I've also added more books to my GR shelf but they don't get synced either so I don't think it's an issue with consolidation/merging of authors on the GR side.

**Comment by philborman** [comment]
Hmm, seems there is not enough info in the log to tell us what's going on apart from the error code. 
It's a bit weird as we can get a list of your shelves, so we must be authorised, but then we can't get a list of the books on the shelf.

I have attached a new grsync.py with more debugging code (level 1024) which will print the url of the page we couldn't get just to check the parameters we are sending look ok. Keep a copy of your existing grsync.py (maybe rename to grsync.old) so you can replace it later, or lazylibrarian will complain when you try to upgrade. Drop in the new file, restart lazylibrarian, and try a sync again. Hopefully we will get more info on why it's failing, as it's working for me here.


```
2018-06-19 11:20:39 | INFO | 438 | 64 changes to lazylibrarian_wanted shelf, 0 changes to Wanted from GoodReads, 95 changes to lazylibrarian_have shelf, 0 changes to Owned from GoodReads
2018-06-19 11:20:39 | INFO | 589 | 0 new in goodreads lazylibrarian_have
2018-06-19 11:18:51 | INFO | 537 | 5 missing from lazylibrarian lazylibrarian_have
2018-06-19 11:18:51 | INFO | 508 | There are 1719 Open/Have books, 1633 books on goodreads lazylibrarian_have shelf
2018-06-19 11:17:15 | INFO | 476 | Syncing Open to lazylibrarian_have shelf
2018-06-19 11:17:15 | INFO | 589 | 2 new in goodreads lazylibrarian_wanted
2018-06-19 11:16:57 | INFO | 574 | 17 new in lazylibrarian lazylibrarian_wanted
2018-06-19 11:16:57 | INFO | 552 | 0 missing from goodreads lazylibrarian_wanted
2018-06-19 11:16:18 | INFO | 537 | 47 missing from lazylibrarian lazylibrarian_wanted
2018-06-19 11:16:18 | INFO | 508 | There are 30 Wanted books, 62 books on goodreads lazylibrarian_wanted shelf
2018-06-19 11:16:09 | INFO | 476 | Syncing Wanted to lazylibrarian_wanted shelf
```
[grsync.zip](https://github.com/DobyTang/LazyLibrarian/files/2114883/grsync.zip)

**Comment by tkosig** [comment]
Here is the log output with the URL:

```
19-Jun-2018 13:27:50 - INFO    :: GRSync : grsync.py:grsync:480 : Syncing Wanted to to-get shelf
19-Jun-2018 13:27:51 - DEBUG   :: GRSync : common.py:gr_api_sleep:144 : GoodReads sleep 0.473, total 1.704
19-Jun-2018 13:27:51 - DEBUG   :: GRSync : grsync.py:get_shelf_list:187 : Shelf read : 118: Exclusive true
19-Jun-2018 13:27:51 - DEBUG   :: GRSync : grsync.py:get_shelf_list:187 : Shelf currently-reading : 3: Exclusive true
19-Jun-2018 13:27:51 - DEBUG   :: GRSync : grsync.py:get_shelf_list:187 : Shelf to-read : 47: Exclusive true
19-Jun-2018 13:27:51 - DEBUG   :: GRSync : grsync.py:get_shelf_list:187 : Shelf fantasy : 1: Exclusive false
19-Jun-2018 13:27:51 - DEBUG   :: GRSync : grsync.py:get_shelf_list:187 : Shelf sci-fi : 6: Exclusive false
19-Jun-2018 13:27:51 - DEBUG   :: GRSync : grsync.py:get_shelf_list:187 : Shelf test : 0: Exclusive false
19-Jun-2018 13:27:51 - DEBUG   :: GRSync : grsync.py:get_shelf_list:187 : Shelf to-get : 5: Exclusive false
19-Jun-2018 13:27:51 - DEBUG   :: GRSync : grsync.py:get_shelf_list:190 : Found 7 shelves on page 1
19-Jun-2018 13:27:51 - DEBUG   :: GRSync : common.py:gr_api_sleep:144 : GoodReads sleep 0.215, total 1.919
19-Jun-2018 13:27:52 - DEBUG   :: GRSync : grsync.py:get_shelf_list:190 : Found 0 shelves on page 2
19-Jun-2018 13:27:52 - DEBUG   :: GRSync : grsync.py:get_shelf_list:192 : Found 7 shelves on 1 page
19-Jun-2018 13:27:52 - DEBUG   :: GRSync : common.py:gr_api_sleep:144 : GoodReads sleep 0.568, total 2.487
19-Jun-2018 13:27:53 - DEBUG   :: GRSync : grsync.py:get_gr_shelf_contents:288 : User id is: 12398753
19-Jun-2018 13:27:53 - ERROR   :: GRSync : grsync.py:getShelfBooks:365 : Failure status: 403 for to-get page 1
19-Jun-2018 13:27:53 - DEBUG   :: GRSync : grsync.py:getShelfBooks:367 : https://www.goodreads.com/review/list?format=xml&v=2&id=12398753&sort=author&order=a&key=<redacted>&page=1&per_page=100&shelf=to-get
19-Jun-2018 13:27:53 - DEBUG   :: GRSync : grsync.py:get_gr_shelf_contents:315 : Found 0 books on page 1 (total = 0)
19-Jun-2018 13:27:53 - DEBUG   :: GRSync : grsync.py:get_gr_shelf_contents:319 : Found 0
19-Jun-2018 13:27:53 - INFO    :: GRSync : grsync.py:grsync:512 : There are 0 Wanted books, 0 books on goodreads to-get shelf
19-Jun-2018 13:27:53 - INFO    :: GRSync : grsync.py:grsync:541 : 0 missing from lazylibrarian to-get
19-Jun-2018 13:27:53 - INFO    :: GRSync : grsync.py:grsync:556 : 0 missing from goodreads to-get
19-Jun-2018 13:27:53 - INFO    :: GRSync : grsync.py:grsync:578 : 0 new in lazylibrarian to-get
19-Jun-2018 13:27:53 - INFO    :: GRSync : grsync.py:grsync:593 : 0 new in goodreads to-get
19-Jun-2018 13:27:53 - DEBUG   :: GRSync : grsync.py:grsync:649 : Sync Wanted to to-get shelf complete
19-Jun-2018 13:27:53 - INFO    :: GRSync : grsync.py:sync_to_gr:442 : 0 changes to to-get shelf, 0 changes to Wanted from GoodReads, Sync Owned books is disabled
```

**Comment by tkosig** [comment]
Possibly stupid question but is the review.list call using OAuth? My GR profile is not public and the API states that OAuth is required to view profiles that are visible to friends only.

**Comment by philborman** [comment]
Yes we are using oauth, I think it may be a shelf name issue. The shelf name is to-get  and I think maybe the minus sign is the problem. Can you try changing the shelf name to to_get instead, just to confirm if that's it?   Goodreads is a bit funny about characters in shelf names, see https://www.goodreads.com/topic/show/868899-changes-to-characters-allowed-in-shelf-names
or it could be an encoding issue, maybe we need to send the minus as %2d

**Comment by tkosig** [comment]
I've created a new shelf to_get (also tried no underscore) and added books to it. Unfortunately I still get the 403 and no books are synced. Not a shelf name issue I guess. :disappointed:

**Comment by philborman** [comment]
Wouldn't be that easy I guess. Just looking at what's different between your setup and mine, since it's working here.  I will have a play later and see if I can reproduce it and get back to you.

**Comment by philborman** [comment]
Ok, I can get a 403 forbidden error if I set my profile to friends only. Not sure if we can get around this as we are already using oauth (you can't add or remove books from a list without oauth).

**Comment by tkosig** [comment]
Well then GR's API is broken. This is what https://www.goodreads.com/api/ states for the review.list call:

> Get the books on a members shelf. Customize the feed with the below variables. Viewing members with profiles who have set them as visible to members only or just their friends requires using OAuth.

**Comment by tkosig** [comment]
Last comment in that thread points to an [issue](https://code.google.com/archive/p/oauth-signpost/issues/47) in the sign-post library. Seems to be an issue with the code querying the GR API. Has the OAuth library in this codebase been recently updated, maybe an issue was introduced there?

**Comment by philborman** [comment]
No we don't use the same library, that's a google library, but the symptoms are exactly the same. Our oauth library hasn't been updated at all, but maybe needs to be? I'm guessing it has never worked with private profiles?

That part is easy to check, there are earlier releases of lazylibrarian on the git page under "releases" 

I might get around to looking at that option in a day or two, still hunting for more examples or any other known issues.

**Comment by tkosig** [comment]
Well it's worked just fine with my profile which has been set private for a long time (longer than I've had LL syncing to GR). Thanks for your time and effort looking into this anyway!

**Comment by philborman** [comment]
In that case maybe you could try an earlier version of lazylibrarian from the git page. If we can find the last version that worked we can see what changed.

**Comment by philborman** [comment]
ok, found the problem. Back in December the oauth library was changed from a python2 only one to a version compatible with both python2 and python3. They are both from the same source and supposedly the same version (VERSION = '1.0' # Hi Blaine!) but don't behave the same.

The py2 version works fine with goodreads public and private profiles but won't run at all on py3
The py3 version works fine with public profiles on py2 and py3, but not private profiles on either.
I think we need a new oauth library.

**Comment by tkosig** [comment]
Great, well done for figuring that out! Either a different library or the existing library needs fixing. Not sure what exactly the issue in the library is though.

**Comment by philborman** [comment]
No idea either, but the py2 version seems to run fine. It's probably easiest just to use 2to3 to produce a py3 version from it and ship two different libraries as we do with some of the other libraries we use.  Maybe later today...
