### ISSUE TITLE
LazyLibrarian snatching ebooks when I have set all new books to be marked as skipped

### ISSUE THREAD

**Issue by mcaron1234** [DobyTang/LazyLibrarian#1208]
### Relevant debug log with api keys and any passwords redacted
Here is a portion of the debug log when a book was snatched:
[https://pastebin.com/Q836hyqG
](https://pastebin.com/Q836hyqG)
Here is the debug.zip with the config settings is attached.

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1675466/debug.zip)

I only want to use LazyLibrarian with audiobooks.  I have a good system already for managing my ebooks with Calibre and I don't want to introduce any complications with that.  With that in mind I installed and configured LL last night with the library location of my audiobooks.  I did not set an ebook library location, and in setting -> processing I set missing book status, new book status, and new authors book status authors book status to skipped, and I did not scan my existing ebook library into LL. I did scan my audiobook library. Sometime during the night LL snatched about 13 ebooks and added them the the library (per my pushover notifications).  I'm not sure where it added them, as I haven't configured a library location for ebooks, only audiobooks.

How can I configure LL to not search for, catalog, or attempt to snatch ebooks?

**Comment by philborman** [comment]
Sounds like you are set up correctly, could be a bug. Lazylibrarian will only snatch books marked as "wanted" so either they are being incorrectly marked wanted, or we are picking up ebooks when it's the audiobook that's marked wanted.

Not all downloads tell you what's in them until you download them, could be that?

**Comment by philborman** [comment]
If that is what's going on, try adding epub, mobi touch your reject words list for audiobook

**Comment by philborman** [comment]
Unfortunately your pastebin link comes up "not found" so guessing really ;-)

**Comment by mcaron1234** [comment]
The pastebin link was an error in the post formatting.  I've fixed it now and the link works.  

Thank you for the advice and I will try your suggestion, but I would think having the setting new book status, etc to skipped would be enough.

**Comment by philborman** [comment]
Found the bug that was causing this, will be fixed in next release, probably today or tomorrow.
