### ISSUE TITLE
Favorite author checkbox

### ISSUE THREAD

**Issue by Code-Slave** [DobyTang/LazyLibrarian#1210]
Would like to explore thoughts on having a "favorites" check on authors thats displayed on front page so It is sortable at the minimum or slectable so it only shows favorites. You could add a button at top of author page where the pause etc button is. Im at 145 authors and is getting to be challenging to get to specifics or groups.

extra spicy bonus would be to do search and fetch for just starred authors

**Comment by philborman** [comment]
You can sort-of do it using the author status, you can filter so only the "wanted" authors are visible, assuming you want all new books by your favourite authors. Wouldn't be too much work to put another status in, but might work well enough as it is for what you want?

Search and fetch for only "wanted" authors would be easy enough to add.

**Comment by Code-Slave** [comment]
Im kinda an extreme case :) I read a book a week minimum. And have been known to read 2-3 on a rainy saturday, so I have a large pool of authors. I havent used the author status in that way. Ill play around a bit

**Comment by philborman** [comment]
Active means monitor author periodically for new books
Wanted means try to download all new books from this author  (ignores default new book status)
