### ISSUE TITLE
Unable to add Newznab & Torznab

### ISSUE THREAD

**Issue by mrsrockguru** [DobyTang/LazyLibrarian#1212]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number
 Repo: https://github.com/dobytang/lazylibrarian : Branch: master : Updated: Sun Feb 4 20:04:17 2018
Current Version: ad2145999866d53c570bd73d5c5d4ef18454a61c : Latest Version: ad2145999866d53c570bd73d5c5d4ef18454a61c

### Relevant debug log with api keys and any passwords redacted

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1695204/debug.zip)

I get the same error when trying to add either.  line 75 Unknown provider.

Chrs

**Comment by philborman** [comment]
Replied to you on reddit (assuming it's you, the username is different but the query is the same)
SAVE config before testing, might get fixed so you don't need to in a later version.
