### ISSUE TITLE
calibredb retry exception: OSError [Errno 8] Exec format error

### ISSUE THREAD

**Issue by silentArtifact** [DobyTang/LazyLibrarian#1219]
I'm attempting to connect LL to my calibre library, which is in the /books directory, same as the books themselves. LL is able to index the books in that directory, but it doesn't seem to want to allow me to connect to the library stored there, for whatever reason. 

I was able to access LL in the container through telnet, and vi into the metadata.db file, so it seems like permissions _should_ be ok.

Any thoughts?

### LazyLibrarian version number (at the bottom of config page)
ae14d00a13e376edf4ee8cfd4320b3d585b99079

### Operating system used (windows, mac, linux, NAS type)
Synology DS718+

### Interface in use (default, bookstrap)
Bootstrap

### Which api (Goodreads, GoogleBooks, both)
Both

### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
Docker (linuxserver)

### Relevant debug log with api keys and any passwords redacted
12-Feb-2018 19:16:47 - INFO    :: CP Server Thread-6 : webServe.py:clearLog:2875 : Log cleared, level set to [1]- Log Directory is [/config/log]
12-Feb-2018 19:16:49 - INFO    :: WEBSERVER : webServe.py:toggleLog:2908 : Debug log ON, loglevel is 2
12-Feb-2018 19:16:58 - DEBUG   :: WEBSERVER : calibre.py:calibredb:417 : [u'/books', '--version']
12-Feb-2018 19:16:58 - DEBUG   :: WEBSERVER : calibre.py:calibredb:431 : calibredb exception: OSError [Errno 13] Permission denied
12-Feb-2018 19:17:03 - INFO    :: WEBSERVER : webServe.py:toggleLog:2906 : Debug log OFF, loglevel is 1

**Comment by SilentArtifact** [comment]
I've found that I need to specify the metadata.db file in the path, but now when doing so, I run into a new error, 

`calibredb communication failed: calibredb exception: OSError [Errno 8] Exec format error`

I'm attaching the proper log, as I should have done earlier...
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1718400/debug.zip)

**Comment by philborman** [comment]
Your docker might not include calibredb, not all do. In the thraxis docker linked to from the lazylibrarian page the calibredb program is at /opt/calibre/calibredb. There is a test button in lazylibrarian config page to check communication with calibredb

**Comment by SilentArtifact** [comment]
Yeah, I think you're right. I found the `thraxis` version, and it seems happy now. How exactly does LL link up with Calibre? Is it able to import books it snatches into the library? I've had some luck with finding things, but I seem to be missing how to bridge the two components.

**Comment by philborman** [comment]
There is some basic documentation in the lazylibrarian wiki in the configuration page. Lack of documentation is still a problem with lazylibrarian, needs quite a bit more work.

Two main lazylibrarian/calibre areas of integration
1. You can get lazylibrarian to download books, tell calibre it's downloaded them, and calibre will add the books into the calibre library. Useful if you use one library folder for the two programs.

2. You can sync lazylibrarian wanted/read status to custom columns in the calibre interface. Not sure if this is actually documented yet, it's a fairly new addition. Works on a per-user basis, so needs user accounts enabled, as each user can have their own calibre columns showing which books they have read or want to read.
