### ISSUE TITLE
unicode error reading .mobi file(s)

### ISSUE THREAD

**Issue by nakermann1973** [DobyTang/LazyLibrarian#1221]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
master/ae14d00a13e376edf4ee8cfd4320b3d585b99079 

### Operating system used (windows, mac, linux, NAS type)
linux (docker) - thraxis/lazylibrarian-calibre

### Interface in use (default, bookstrap)
bookstrap

### Which api (Goodreads, GoogleBooks, both)
both

### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
linux (docker) - thraxis/lazylibrarian-calibre

### Relevant debug log with api keys and any passwords redacted
15-Feb-2018 08:29:38 - DEBUG   :: IMPORTALT : postprocess.py:processAlternate:78 : Processing alternate directory /downloads/Manual/Books
15-Feb-2018 08:29:38 - DEBUG   :: IMPORTALT : postprocess.py:processAlternate:78 : Processing alternate directory /downloads/Manual/Books/Pawn of Prophecy
15-Feb-2018 08:29:38 - DEBUG   :: IMPORTALT : postprocess.py:processAlternate:105 : No metadata file found for /downloads/Manual/Books/Pawn of Prophecy/David Eddings - Pawn of Prophecy.mobi
15-Feb-2018 08:29:38 - DEBUG   :: IMPORTALT : librarysync.py:get_book_info:63 : Unable to parse mobi in /downloads/Manual/Books/Pawn of Prophecy/David Eddings - Pawn of Prophecy.mobi, AttributeError 'unicode' object has no attribute 'read'
15-Feb-2018 08:29:38 - WARNING :: IMPORTALT : postprocess.py:processAlternate:150 : Book /downloads/Manual/Books/Pawn of Prophecy/David Eddings - Pawn of Prophecy.mobi has no metadata, unable to import
15-Feb-2018 08:29:38 - DEBUG   :: IMPORTALT : postprocess.py:processAlternate:78 : Processing alternate directory /downloads/Manual/Books/Queen of Sorcery
15-Feb-2018 08:29:38 - DEBUG   :: IMPORTALT : postprocess.py:processAlternate:105 : No metadata file found for /downloads/Manual/Books/Queen of Sorcery/Book 2 - Queen of Sorcery.mobi
15-Feb-2018 08:29:38 - DEBUG   :: IMPORTALT : librarysync.py:get_book_info:63 : Unable to parse mobi in /downloads/Manual/Books/Queen of Sorcery/Book 2 - Queen of Sorcery.mobi, AttributeError 'unicode' object has no attribute 'read'
15-Feb-2018 08:29:38 - WARNING :: IMPORTALT : postprocess.py:processAlternate:150 : Book /downloads/Manual/Books/Queen of Sorcery/Book 2 - Queen of Sorcery.mobi has no metadata, unable to import

As you can see from the log, I am trying to manually import some books, and am getting a unicode error.  Please let me know if you want the actual mobi file for testing.

**Comment by philborman** [comment]
Yes would be useful thanks. Can't reproduce the problem with any of my mobis here. Could be there is genuinely no metadata in the file (unusual) or could be the mobi library we're using can't handle the data. You can email the file to me at phil.borman@gmail.com or send me  link to a dropbox/googledrive
Thanks.

**Comment by nakermann1973** [comment]
Thank you - I can confirm this is now working
