### ISSUE TITLE
Ignore BTS flagfiles?

### ISSUE THREAD

**Issue by barbequesauce** [DobyTang/LazyLibrarian#1224]
Found a few issues talking about skipping post processing if there are BT sync files present (*.bts). Is there a switch to disable this preference?

For some reason I have a bunch of downloads with this file in the torrent, even though I don’t use BT sync...

**Comment by philborman** [comment]
As far as I understand it the .bts file shouldn't be in a completed download, it's a file that isn't complete yet. 
"""
A .bts basically represents file download in progress and is generated for the purposes of file allocation, to reserve the space for the file. When the download/sync is finished, the extension is changed back to the original.
"""
so it looks like whoever uploaded the book you are downloading didn't wait until they had a complete copy and is seeding an incomplete version. Of course it might mean the ebook file is complete and it's some other component that isn't all there that we don't care about, or the epub is complete but the mobi isn't, we can't tell, so it's safer to ignore and leave for manual processing.

that said, I can easily make it configurable by moving the extension list into the config file, as long as you are aware there could be bits missing.

**Comment by barbequesauce** [comment]
Understood. I’m planning on mentioning it in the MaM forums this morning as well... best I can tell the files are intact...

**Comment by philborman** [comment]
What's in the .bts file, is it empty or does it look like data, jpg, text ?

**Comment by barbequesauce** [comment]
Not sure - I deleted all of mine already... I'll update the thread next time I see one.

That said, a little research led me to this thread that indicated orphan .bts files can be the result of misconfiguration, [apparently](https://forum.resilio.com/topic/38415-bts-bittorrent-sync-file-orphan-file/)...

**Comment by philborman** [comment]
ok, I have moved the list of skipped extensions into config.ini , appears next time you save the config file.
Will push the new version in a few hours. You can remove bts from the list and see what happens :-)

**Comment by DarkSir23** [comment]
I'm checking one of the torrents he experienced this with, to see what's happening, too.

**Comment by barbequesauce** [comment]
Thanks!

**Comment by barbequesauce** [comment]
just updated... thanks again!
