### ISSUE TITLE
Duplicate opf files

### ISSUE THREAD

**Issue by mccorkled** [DobyTang/LazyLibrarian#1226]
I am haveing a strange issue where I am getting a file called "Book Name.opf" as well as a "Metadata.opf" after importing via Calibre. Do you know why this is, or what I can do to change it?

Thanks

**Comment by philborman** [comment]
Metadata.opf is the calibre file, book_name.opf is either from the download, or generated by lazylibrarian, contents might tell you which.  Calibre needs it's metadata.opf file, and will generate one if not found. 

Some uploaders include an opf file with the book, can be either name format.

The lazylibrarian one might be sent to calibre in one piece, or we might only send details from it (author, title) depending on how you import it. Debug log should let you see what's going on.

**Comment by mccorkled** [comment]
[log.zip](https://github.com/DobyTang/LazyLibrarian/files/1749228/log.zip)

**Comment by philborman** [comment]
Nothing about opf files in those logs, but if you see the problem in another download, check the log files for "opf" and send any relevant ones
