### ISSUE TITLE
Feature Request:  processDir flexibility

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#1227]
Could you please add a dir kwarg to forceProcess in the API and pass that directory to processDir, which would be an override for the usual post-process directory in config?

Syntax example:  api?cmd=forceProcess&dir=/mnt/directdownload/Some+Book+Name

Hope this makes sense :)

**Comment by DarkSir23** [comment]
This will allow Harpoon to work and bypass the need for using btsync.

**Comment by philborman** [comment]
ok, looks easy enough to add.

**Comment by DarkSir23** [comment]
Thank you so much, that'll simplify a lot of things for me :)  And hey ,anything to make the API more robust, right? ;)

**Comment by philborman** [comment]
ok, just added that - let me know if it works as expected, fairly trivial change so not tested here :-)
btw - what's harpoon?

**Comment by DarkSir23** [comment]
It's a script made by the mylar guy that helps move files that are downloaded/seeded outside the local environment.

**Comment by philborman** [comment]
Actually, although I have added that, I don't think it's what you actually want?  I might leave it as an option still for postprocessing one folder if you normally have several set in config. 

I think the importAlternate api command is the one you want, and includes a dir= option, and also handles books not in the database or books not marked as snatched.

The postprocessor only processes snatched books, or books with a LL.(number) in the foldername.

**Comment by DarkSir23** [comment]
It IS processing snatched books, it's just moving them to a folder that's not normally monitored beforehand.  So, hopefully it will work.  We'll find out :)

**Comment by DarkSir23** [comment]
The process is:  LL snatches a book, client starts downloading.  The script fires, watching the remote client for the process to be done.  When it's finished, it pulls the completed file(s) back to the local machine, and says to LL "Ok, ready to process.  Here."
By putting it in a non-monitored folder, it keeps LL from accidentally processing it before it's finished transferring.

**Comment by philborman** [comment]
Ah, OK. Either api call will work then.
How does the script get fired though, are you linking into the lazylibrarian custom notifier, or watching  the client for new torrents?

**Comment by DarkSir23** [comment]
The goal is a custom notification. I need to look at what that can pass, tho

**Comment by DarkSir23** [comment]
So, if I'm following correctly, the custom notification sends the book entry as parameters to the script, is that correct?

Would it be possible to also send the name of the torrent or nzbfile, if it's being called on-snatch?c

**Comment by philborman** [comment]
Yes we currently send the whole "book" or "magazine" table entry to the notifier, we can also send the whole "wanted" table entry which would include the name of the torrent or nzb, which downloader it was sent to, when, downloaders unique id etc. Will add that later today.

If you try the example_custom_notify.py script you will see what you get sent. The "test notifier" button will create a file in lazylibrarian root dir called "notification.out"

**Comment by DarkSir23** [comment]
Perfect, thanks!
