### ISSUE TITLE
Bulk Mag import

### ISSUE THREAD

**Issue by Code-Slave** [DobyTang/LazyLibrarian#1229]
I think all the importing is book based (alt dir). Is there a way Im not seeing to bulk load mags? I can get the mags in the right naming format (date - title) but having to make a subdir for each is a pain (im snagging full year collections).. Any Ideas?

Adding to that. Is there a reason mags are in a 1 issue per dir? I know its similiar to books layout, Im just trying to understand if its needed really?

**Comment by philborman** [comment]
One issue per dir is not essential, hangover from the author / book layout. 
Personally I use one dir per magazine, all issues of one mag in the same folder. 
Magazine foldername: /media/Magazines/$Title
Magazine filename: $IssueDate - $Title
I keep title in both file and foldername for easy identification if I download an issue. 

For bulk loading, if you already have the mags just rename to match your magazine foldername / filename settings and then run libraryscan on that magazine (or the whole library)  LL will import them and create cover/opf as required. If you don't already have the issues then selecting from past issues should grab and process correctly.

**Comment by Code-Slave** [comment]
Thanks. Past issues doesnt always help. Some of the issues are 10 years old. One other issue im having is volume xx vs date format. Thats on me to work out though i think.

**Comment by philborman** [comment]
In searchmag we look for a number that's not a year, <1900 or > (this year + 2) and optionally has the word  ["issue", "no", "nr", "vol", "volume"] in front of it (case independent, with or without a dot eg vol. 12)
We don't allow magazines to have mixed issue numbers and dates, it's one or the other for each mag.
The database and filename use 4 digit numbers for ease of matching and sorting, so issue 3 becomes 0003.  Hope this helps.

**Comment by Code-Slave** [comment]
the problem is i see some directories do have mixed issues and dates in the dir names.

**Comment by philborman** [comment]
Would need to be managed manually then.
There is no way we can tell if issue 123  is before or after the july issue, for example. 
It might even be the same issue.

**Comment by Code-Slave** [comment]
Yea its dependant on the release group. Its not a huge problem as there are only 3-4 mags that have that. I just switched everything to single dir. Quick request, when inside a mag and hit scan library, can you change to scan just that library? it does a full scan even if inside the mag

**Comment by philborman** [comment]
Should be fairly easy, and useful addition, will have a look.

**Comment by Code-Slave** [comment]
thanks. would help testing naming stuff a lot :)

**Comment by Code-Slave** [comment]
Ok heres a problem. 

Mag is shopnotes.

filename 
ShopNotes - Issue 01  - Shop Built Router Table

i have about 100 mags in that dir. on library scan it took each issue as a seperate mag.


Issue 01  - Shop Built Router Table | 1 | 2018-02-02 | ShopNotes | Active
-- | -- | -- | -- | --

back woods home magazine. same problem
backwoods home magazine - Volume-37.pdf

Volume-37 | 1 | 2017-09-17 | backwoods home magazine
-- | -- | -- | --

**Comment by Code-Slave** [comment]
ok/ it must be vol/iss/date magname exactly as in magtitle .pdf

might want to make that case insensitive if it is

**Comment by philborman** [comment]
The importer expects to find filenames that exactly match the configured magazine filename pattern
eg  $IssueDate - $Title  will match 2016-10-01 - BBC Focus.pdf  but not match BBC Focus Oct 2016.pdf
or any other combination. The routine that matches torrent/nzb results to the wanted magazines handles all sorts of combinations, but renames them to the configured pattern. The libraryscan routine just scans for the configured pattern.  I don't think it's easy to get access to more complex the name matching routine via api, but I will have a look.

**Comment by philborman** [comment]
Just added a new api call to lazylibrarian getIssueName&name=
If you pass it a filename it will give you a formatted issue number, ie "Jan 2017 - BBC Focus.pdf" returns "2017-01-01"
If you pass it a full path it returns the new pathname formatted as per magazine filename formatting, picking the magazine name up from the parent directory. 
ie "/Media-Magazines/BBC Focus/Jan 2017 bbc focus.pdf"  returns "/Media-Magazines/BBC Focus/2017-01-01 - BBC Focus.pdf"

Should help with renaming. 
Doesn't actually rename anything itself, just tells you what the name should be.
Returns empty string if can't parse a data/issue number.
 
You could script this from outside lazylibrarian to help your issue, something like
for each pdf in directory
  api call the filename
  if result:
    rename file to result

**Comment by philborman** [comment]
Sample script below...
```
#!/bin/bash
# Quick demo of how to use getIssueName api call from bash
# Pass a directory containing magazines as parameter 1, eg
# bash script.sh "/media/library/Magazines/Radio Times"
# param to curl needs to be urlencoded, this example uses sed to
# encode space and ampersand
HOST="http://127.0.0.1:5299/lazylibrarian"
APIKEY="12345678901234567890"
ls "$1/"*.pdf | while read name
do encoded=`echo $name | sed -e 's/&/%26/g;s/ /%20/g'`
  cmd="$HOST/api?apikey=$APIKEY&cmd=getIssueName&name="$encoded
  newname=`curl -s "$cmd"`
  echo "$name  $newname"
done
```

If the results look ok, change the last "echo" line to a "mv" 
Run libraryscan after changes to update the links and generate jpg and opf

**Comment by Code-Slave** [comment]
thats actually very helpful. Thanks a lot.
