### ISSUE TITLE
Custom script notification

### ISSUE THREAD

**Issue by Ganfoud** [DobyTang/LazyLibrarian#1230]
Hi,
I'm starting to use LL and it will make my life easier, thanks for this!

I created a custom script to be executed on download, however, it does not seem to work
This script accepts the "-l" and "-q" as options (logging and quiet).
When I try to put "/home/pi/script/ebook_add.sh -l" in the "Custom script to run" field (with and without quotation marks), I have the following error message:
`Error sending command: [Errno 2] No such file`
(I translated to english the error description)
It works fine if I don't use the -l or -q option

any idea of the issue?
thanks!

**Comment by philborman** [comment]
The interface to custom script does not allow parameters and it does not have access to lazylibrarian logging. It is fairly limited. What are you trying to do as it might be possible to expand the script options

**Comment by Ganfoud** [comment]
I like to have a verbose/logging mode in my scripts depending on when I start it manually or in background, hence the parameters...
I could probably manage without the parameters though, by adapting my script though

**Comment by philborman** [comment]
You could adapt your script to use the lazylibrarian API for logging? This is a new addition.
Using  curl you would do something like...
curl  "http://localhost:5299/lazylibrarian/api?apikey=b4b10c7c3fbc4117542346c98d84b659&cmd=logMessage&level=info&text=test%20message"

Note that spaces in the message need encoding to %20 or +
and some other non-ascii characters will need encoding too

**Comment by Ganfoud** [comment]
That's a good idea! At least all the logs would be available in the same place...
Didn't think about it since this function was not documented (or at least I didn't see it!), But I'll definitely have a look when I have time!

**Comment by Ganfoud** [comment]
done, and it seems to be working fine!
thanks for your help
