### ISSUE TITLE
Manual Post Processing question (LL.(#####))

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#1233]
Does the forced post processing using LL.() work for magazines?  If so, what do you use, the title field?

**Comment by Code-Slave** [comment]
can you give a little more detail? im in the middle of doing some of this too

**Comment by DarkSir23** [comment]
Well, you can add LL.(<BookID>) to the end of a folder to help LL know what book is inside.  However, magazines don't have a BookID, so I'm wondering what, if anything, you'd use inside LL.()

**Comment by philborman** [comment]
No, the LL.() only works for ebooks and audiobooks. It's needed for goodreads wishlists and csv files and you're using it as a side-effect. Not easy to extend it to magazines unfortunately.

**Comment by DarkSir23** [comment]
No worries, just a curiosity, more than anything. :)
