### ISSUE TITLE
Keep original files, and other processing options

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#1234]
I want to make sure I've got everything configured properly.  When I process a book, it doesn't always remove t he folder, though I don't have Keep original files checked.  Is there another place that I can tell it to remove the processed folder on a successful processing?

**Comment by philborman** [comment]
It should remove unless
1. Keep original files is checked
2. Download was a torrent/magnet and "keep seeding " is checked
3. There was an error postprocessing the download
4. Download is in the root of download dir
5. There is a bug :-)

The first 4 should leave a message in the debug log

**Comment by DarkSir23** [comment]
Will turning off "keep seeding" actually send a command to the downloader to STOP seeding?

**Comment by philborman** [comment]
Not exactly. If the postprocessor decides we want to delete the original file because we don't want to keep seeding, we ask the downloader to delete the torrent. We delete the files ourselves if the other tests say it's ok to do so.

**Comment by DarkSir23** [comment]
Any way to accomodate for a situation where the files being processed aren't the files the downloader is seeding?  Like, if they're being copied to another machine before they're processed.

**Comment by DarkSir23** [comment]
Or if API triggered postprocessing with a dir argument could ignore the keep seeding variable, and just delete the folder if the other criteria are met. :)

**Comment by philborman** [comment]
API triggered is quite easy to do. Do you __always__ want to ignore "keep seeding" if triggered by api, or do you need a switch in the api call?

**Comment by DarkSir23** [comment]
Totally up to you.  Whatever makes the most sense :)

**Comment by philborman** [comment]
ok, added  &ignorekeepseeding to forceProcess api call

**Comment by DarkSir23** [comment]
Awesome, thanks!

**Comment by DarkSir23** [comment]
Hmm, even with ignorekeepseeding, it appears to be telling the client to stop.  I may have mis-made my request.

Could I have a switch for forceProcess that deletes the folder if keep original files is unchecked but does nothing with the client, regardless of the keep seeding setting?

**Comment by philborman** [comment]
ok, done. ignorekeepseeding renamed to ignoreclient to make it clearer

**Comment by DarkSir23** [comment]
Awesome, thank you :)
