### ISSUE TITLE
GoodReads Sync

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#1239]
Trying to take advantage of GoodReads Sync and trying to find a way to keep the goodreads info private.

The best way to have a private bookshelf on Goodreads is to use the bookshelf of a secret group.  Can LL sync with a group's bookshelf, if it has access?  If not, is there anything I can do to help make that a possibility? :)

Thanks

**Comment by DarkSir23** [comment]
Nevermind, I don't think the goodreads api will let you do anything with a group shelf.

**Comment by philborman** [comment]
I think you are right, user shelves only. Can other users see your shelves then? 
There are 3 flags we can set on a shelf, exclusive, sortable, featured
All default to "False". Nothing else we can change as far as I know.
