### ISSUE TITLE
Unable to extract TAR file

### ISSUE THREAD

**Issue by stlouisn** [DobyTang/LazyLibrarian#1241]
Unhandled exception in processDir: Traceback (most recent call last): File "/app/lazylibrarian/lazylibrarian/postprocess.py", line 489, in processDir res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle) File "/app/lazylibrarian/lazylibrarian/postprocess.py", line 240, in unpack_archive z = tarfile.TarFile(pp_path) File "/usr/lib/python2.7/tarfile.py", line 1587, in __init__ self.firstmember = self.next() File "/usr/lib/python2.7/tarfile.py", line 2370, in next raise ReadError(str(e)) ReadError: invalid header 

after manually extracting the TAR file, post processing ran correctly.

**Comment by philborman** [comment]
Ok thanks, I will take a look. It's a fairly new section of code so not well tested. Probably something simple I've overlooked.

**Comment by stlouisn** [comment]
also to note, i am using linuxserver/lazylibrarian docker container, so its possibly the fault is a missing component in the docker container. i posted the issue there aswell

**Comment by philborman** [comment]
Looks like there is nothing missing, just unable to read the tar file. Do you still have the unextracted file by any chance?  Maybe the file is compressed in an unsupported way (unsupported by the builtin tar extractor). Was it a tar.bz or tar.gz or plain tar.

**Comment by stlouisn** [comment]
PC Gamer USA - August 2013.tgz

not even sure what the file came from or why it grabbed something five years old

**Comment by stlouisn** [comment]
$ tar x PC\ Gamer\ USA\ -\ August\ 2013.tgz
tar: Refusing to read archive contents from terminal (missing -f option?)
tar: Error is not recoverable: exiting now

)$ tar xfv PC\ Gamer\ USA\ -\ August\ 2013.tgz
~Get Your Files Here/
~Get Your Files Here/Get More Ebooks Here.url
~Get Your Files Here/Important ! Readme.txt
~Get Your Files Here/PC Gamer USA - August 2013.pdf
^ Just one Click to Get More Ebooks Mags.url
~Download More Stuff Here !.url
~Read More Ebooks and Tutorials Online.url

**Comment by philborman** [comment]
ok thanks, I will have a look at that. Will add an error message if we cant read the file, but might be able to find out why it wouldnt read. The builtin tarfile routine recognised it as a tarfile, then failed to extract. Maybe we can at least get it to say why.

**Comment by philborman** [comment]
Had a quick look at this, the doc says...
reads and writes gzip and bz2 compressed archives if the respective modules are available.

so maybe the modules aren't available in your docker, and it silently fails?
Easy to check, you just need to log into your docker using ssh and try to import the modules from within python, eg...

docker exec -it <containerIdOrName> bash
python
>> import gzip
>> import bz2
>> quit()
