### ISSUE TITLE
Newznab categories 7000,7020 used in API searches

### ISSUE THREAD

**Issue by theotherp** [DobyTang/LazyLibrarian#1242]
Hi,

I'm the developer of NZBHydra. I've had some reports about issues which were caused because LL uses the newznab categories 7000 and 7020 for searches. That's a scenario which I never expected to happen. I've already worked around it but I'm wondering what the reason would be to provide a main category and one of its subcategories. The [spec](http://newznab.readthedocs.io/en/latest/misc/api/#predefined-categories) is a bit vague on the issue (and many indexers don't follow the spec to the letter) but as I understand it a search for the category 7000 should return any results in the categories 7010, 7020, 7030, etc. I haven't encountered any indexer that does not behave that way.
Thanks.

**Comment by philborman** [comment]
No problem, I will change that.
I misunderstood and thought 7000 returned additional results that were not in 7020 (or maybe I tested on a provider that didn't follow the spec either)
New version due out later today, should be included.

**Comment by philborman** [comment]
ok, that's included. Will take a while to filter through for existing users, as we cache the capabilities response and only update capabilities for existing providers every few days.

btw, thanks for NZBHydra, great program, I use it all the time!

**Comment by theotherp** [comment]
Thanks and you're welcome 😉

Am 27.02.2018 8:05 nachm. schrieb "philborman" <notifications@github.com>:

**Comment by claym** [comment]
Can verify this is fixed. Thanks all!
