### ISSUE TITLE
Audiobook not showing in Manage

### ISSUE THREAD

**Issue by blizzardcldasl** [DobyTang/LazyLibrarian#1250]
Audiobooks in a wanted or any status are not showing on the manage tab.

Interface: bookstrap
git_repo: lazylibrarian
git_user: dobytang
git_branch: master
version: 1e09a53a0a043dc30a61500d1700228c1d56a457
Python version: ['2.7.12 (default, Dec  4 2017, 14:50:18) ', '[GCC 5.4.0 20160609]']
Distribution: ('Ubuntu', '16.04', 'xenial')
System: Linux
Machine: x86_64
Platform: Linux-4.13.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
version: #40~16.04.1-Ubuntu SMP

**Comment by philborman** [comment]
The "Manage" page is for ebooks and most functions on that page (syncing, importing lists) have no equivalent functionality for audiobooks. Not sure how useful it would be to add this, or whether just listing/changing status is all thats needed?
