### ISSUE TITLE
Unable to install RPM package

### ISSUE THREAD

**Issue by gtranche** [DobyTang/LazyLibrarian#1252]
Hi,

when i try to install the rpm package i got those errors:
`yum localinstall lazylibrarian-1.5.0-2.noarch.rpm
Loaded plugins: fastestmirror
Examining lazylibrarian-1.5.0-2.noarch.rpm: lazylibrarian-1.5.0-2.noarch
Marking lazylibrarian-1.5.0-2.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package lazylibrarian.noarch 0:1.5.0-2 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package          Arch      Version      Repository                        Size
================================================================================
Installing:
 lazylibrarian    noarch    1.5.0-2      /lazylibrarian-1.5.0-2.noarch     17 M

Transaction Summary
================================================================================
Install  1 Package

Total size: 17 M
Installed size: 17 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test

Transaction check error:
  file / from install of lazylibrarian-1.5.0-2.noarch conflicts with file from package filesystem-3.2-21.el7.x86_64
  file /lib from install of lazylibrarian-1.5.0-2.noarch conflicts with file from package filesystem-3.2-21.el7.x86_64
  file /opt from install of lazylibrarian-1.5.0-2.noarch conflicts with file from package filesystem-3.2-21.el7.x86_64
  file /usr/bin from install of lazylibrarian-1.5.0-2.noarch conflicts with file from package filesystem-3.2-21.el7.x86_64
  file /etc/init.d from install of lazylibrarian-1.5.0-2.noarch conflicts with file from package chkconfig-1.7.4-1.el7.x86_64

Error Summary
-------------`
I'm on Centos 7.4 x86_64.
Do you need more informations ?

Thank you

**Comment by philborman** [comment]
Looks like the rpm package is broken, or does not work on Centos. Please try installing from zip file or docker.

**Comment by philborman** [comment]
We create the rpm from a debian package using "alien". The next version in a few days will have the rpm created by a different method, might solve the problem but I have no way of testing it apart from the rpm test tools, which said the "old" one was ok.
