### ISSUE TITLE
[Feature Request] - Transmission torrent labels

### ISSUE THREAD

**Issue by timelf123** [DobyTang/LazyLibrarian#1253]
This is supported in Sonarr and Radarr, any chance we can add them here? All the other torrent clients support labels except transmission

`Branch: master
Current Version: 1e09a53a0a043dc30a61500d1700228c1d56a457 : Latest Version: 1e09a53a0a043dc30a61500d1700228c1d56a457`

**Comment by philborman** [comment]
I don't think transmission itself supports labels, at least I can't find anything in the documentation about it.

**Comment by timelf123** [comment]
I stand correct, thanks! Looks like they never made it live https://trac.transmissionbt.com/ticket/5385

**Comment by philborman** [comment]
Depending what you want to do you can use the lazylibrarian  transmission download directory to segregate the books into a separate folder, or use a lazylibrarian custom notifier script to process the successful download, might be enough?

**Comment by timelf123** [comment]
Yep, going to use the download directory for now, thanks!
