### ISSUE TITLE
Import failure, not loading the book folder?

### ISSUE THREAD

**Issue by Dulanic** [DobyTang/LazyLibrarian#1256]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
1e09a53a0a043dc30a61500d1700228c1d56a457 
### Operating system used (windows, mac, linux, NAS type)
Linux Docker
### Interface in use (default, bookstrap)
default
### Which api (Goodreads, GoogleBooks, both)
Goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
https://github.com/linuxserver/docker-lazylibrarian
### Relevant debug log with api keys and any passwords redacted
```
09-Mar-2018 14:47:43 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:365 : Carol Stock Kranowitz - The Out-of-Sync Child LL.(25339) was sent to DIRECT
09-Mar-2018 14:47:43 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:415 : Looking for eBook Carol Stock Kranowitz - The Out-of-Sync Child LL.(25339) in /downloads/complete/books
09-Mar-2018 14:47:43 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:494 : Found folder (100%) [/downloads/complete/books/Carol Stock Kranowitz - The Out-of-Sync Child LL.(25339)] for eBook Carol Stock Kranowitz - The Out-of-Sync Child
09-Mar-2018 14:47:43 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:543 : Found match (100%): /downloads/complete/books/Carol Stock Kranowitz - The Out-of-Sync Child LL.(25339) for eBook Carol Stock Kranowitz - The Out-of-Sync Child LL.(25339)
09-Mar-2018 14:47:43 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:549 : Processing eBook 25339
09-Mar-2018 14:47:43 - WARNING :: POSTPROCESS : __init__.py:DIRECTORY:1108 : eBook dir [/books] not usable, using /run/s6/services/lazylibrarian: [Errno 13] Permission denied: u'/books/ll_temp'
09-Mar-2018 14:47:43 - DEBUG   :: POSTPROCESS : postprocess.py:processDestination:1230 : BookType: ebook, calibredb: []
09-Mar-2018 14:47:43 - DEBUG   :: POSTPROCESS : postprocess.py:processDestination:1232 : /run/s6/services/lazylibrarian/Carol Stock Kranowitz/The Out-of-Sync Child does not exist, so it's safe to create it
09-Mar-2018 14:47:43 - ERROR   :: POSTPROCESS : postprocess.py:processDir:727 : Postprocessing for The Out-of-Sync Child - Carol Stock Kranowitz has failed: Unable to create directory /run/s6/services/lazylibrarian/Carol Stock Kranowitz/The Out-of-Sync Child: [Errno 13] Permission denied: '/run/s6/services/lazylibrarian/Carol Stock Kranowitz'
09-Mar-2018 14:47:43 - WARNING :: POSTPROCESS : postprocess.py:processDir:748 : Residual files remain in /downloads/complete/books/Carol Stock Kranowitz - The Out-of-Sync Child LL.(25339).fail
```

If I run bash inside the docker container and did echo to create and it creates fine so it def has permissions?

`root@852557fd2630:/books$ echo "" > test`

The file creates on the host no problem.

`-rw-r--r-- 1 dulanic dulanic 1 Mar  9 14:49 test`

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report.

**Comment by philborman** [comment]
Not usable means we failed to create a test file in the folder, or we failed to delete the test file after creation.
The file would be /books/ll_temp and as that failed we try to use "current working directory" instead, and that also failed. Current working directory is usually a fairly safe fallback, but not on dockers because of strict permissions. The folder /books needs to be rwx for the user that lazylibrarian runs as. Just because you can ssh into it and create a file it doesnt mean lazylibrarian can, you are logged in as root.

**Comment by Dulanic** [comment]
I use the same user for the docker container as my SSH.

**Comment by Dulanic** [comment]
Now that Im home, I can screen shot what I did. This is running direct within the container, so it has the rights.
![image](https://user-images.githubusercontent.com/2948206/37234358-e3f10fc4-23bc-11e8-80c2-024835e3ff10.png)

**Comment by philborman** [comment]
The code that's throwing the error is
with open(os.path.join(usedir, 'll_temp'), 'w') as f:
                f.write('test')
and we get "[Errno 13] Permission denied: u'/books/ll_temp'" 
so the lazylibrarian process does not have write access to  the /books directory for some reason.
This message is either from the docker os or passed to it from the underlying host os
When you log in over ssh it looks like you are running in the docker as root, 
root@852557fd2630:/books$ rm test
so you may have higher privileges than the lazylibrarian process, which may be a normal user?
When you are in the docker, what are the permissons of the /books folder ?  Also maybe in the host os try setting /local-media/Media/Books to rwx for all users as it looks like only dulanic has write access, others are read/execute only ?

**Comment by Dulanic** [comment]
Well it shows root because that is within the docker. But it's ran /w - e
uid / gid 1000. Root for the container is equivalent to dulanic. If I check
the /books permission from within the container it shows the exact same as
on host. It's so weird since LL is run as root in the container and I can
run the command manually in the container no problem.

**Comment by philborman** [comment]
Its certainly weird. Not sure what needs to be done. Are you up to a bit of editing?  If not I can add some debugging code to the next release.

If you ssh into the container and edit` lazylibrarian/__init__.py `(there is usually nano editor in the docker containers) in the DIRECTORY function around line 1110 you will see the "not usable" message in a "logger.warn()". Directly under that if you add
 
```
            logger.debug("Folder: %s Mode: %s UID: %s GID: %s W_OK: %s X_OK: %s" % (usedir,
                         oct(os.stat(usedir).st_mode), os.stat(usedir).st_uid, os.stat(usedir).st_gid,
                         os.access(usedir, os.W_OK), os.access(usedir, os.X_OK)))

```

it will show us the permissions lazylibrarian finds when it tries and fails to write.
Python is fussy about whitespace, the "logger.debug" line needs to be indented with spaces (not tabs) so it lines up vertically with the line above.

Also keep a copy of the original` __init__.py` file so you can put it back afterwards, or the docker will complain about being unable to upgrade because of local changes.

**Comment by Dulanic** [comment]
Does this help?

10-Mar-2018 07:46:26 - DEBUG   :: POSTPROCESS : __init__.py:DIRECTORY:1111 : Folder: /books Mode: 040755 UID: 1000 GID: 1000 W_OK: True X_OK: True

**Comment by philborman** [comment]
Sadly no. That line says we have write access (W_OK True)  and execute access (X_OK True) and /books directory is mode  755  so it's a real puzzle why we can't write to it. I will see if I can find anything on google.

**Comment by Dulanic** [comment]
Yeah, it's very strange. I can write, that shows I can, but yet LL wont do it :(

![image](https://user-images.githubusercontent.com/2948206/37243094-d86a552a-2439-11e8-956a-154077f59acd.png)

**Comment by Dulanic** [comment]
OK, I got it. It was a problem /w MergerFS. The location itself was a mount also and that at some point created as root not the user. Sorry for the confusion. Very odd situation. Trying to figure out why mergerFS even created it as root since it's set for the user also, but separate problem/concern unrelated to this.
