### ISSUE TITLE
Just updated and now LL won't load

### ISSUE THREAD

**Issue by jcouch93** [DobyTang/LazyLibrarian#1259]
Linux Mint 18.2 on an unRAID VM.

Just updated and now I get this when I try and load LL:

10-Mar-2018 10:42:10 - INFO :: MAIN : webStart.py:initialize:56 : Starting LazyLibrarian web server on http://0.0.0.0http://192.168.1.13:5299/config#searchprocessing:5299/
Exception in thread HTTPServer Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/unraidvm/LazyLibrarian/cherrypy/process/servers.py", line 205, in _start_http_thread
    self.httpserver.start()
  File "/home/unraidvm/LazyLibrarian/cherrypy/wsgiserver/wsgiserver2.py", line 1955, in start
    raise socket.error(msg)
error: No socket could be created -- ((u'0.0.0.0http://192.168.1.13:5299/config#searchprocessing', 5299, 0, 0): [Errno -2] Name or service not known)

Failed to start on port: 5299. Is something else running?

I've checked and as far as I can see there's nothing else running on that port.  Any ideas?  Thanks!

**Comment by jcouch93** [comment]
Ok, I figured it out.  I do'nt know if the update corrupted the config or something else but the line above "((u'0.0.0.0http://192.168.1.13:5299/config#searchprocessing', 5299, 0, 0): [Errno -2] Name or service not known)" was the culprit.  I removed the http: stuff from the config (only leaving the 0.0.0.0) and saved the config and restarted LL.  It now works.

**Comment by philborman** [comment]
Update shouldn't corrupt config as it only touches python files. Maybe running the old and the new simultaneously could cause problems?  I will check the restart code in case there is anything obvious. Closing this for now. Please reopen if it happens again. Another update just released now.
