### ISSUE TITLE
 073a8cf3a2fb8374ab23d4813ef3b02d6d56139a breaks post-processing - destination folders are not created

### ISSUE THREAD

**Issue by splog123** [DobyTang/LazyLibrarian#1261]
Commit 073a8cf3a2fb8374ab23d4813ef3b02d6d56139a (found with git-bisect) now causes post-processing to fail with this log message (book and author names obfuscated to $VAR):

ERROR Postprocessing  for $AUTHOR - $BOOK has failed: Unable to move file  /var/download/complete/books/$AUTHOR - $BOOK  LL.(4657)/$AUTHOR - $BOOKFILE to  /mnt/media/eBooks/lazylibrarian/$AUTHOR/$BOOK/$AUTHOR - $BOOKFILE: IOError [Errno 2] No such file or  directory: u'/mnt/media/eBooks/lazylibrarian/$AUTHOR/$BOOK/$AUTHOR - $BOOKFILE'

WARNING Residual files remain in /var/download/complete/books/$AUTHOR - $BOK LL.(4657).fail

Basically, the destination directories in the library folder are not being created. If you imagine the code were to run say "mkdir /path/to/new/folder" when it needs to be "mkdir -p ..." then you get the idea of how it will fail.

System: git checkout on Gentoo Linux. Library folder is an NFS mount. Setup has worked correctly and flawlessly for 4 years+

Config:
eBook Library Folder: /mnt/media/eBooks/lazylibrarian/
eBook/AudioBook Foldername Pattern: $Author/$Title/
eBook Filename Pattern: $Author - $Title

Bug is repeatable and consistent:
- Checkout latest, post-processing fails. 
- Checkout 63edcbd77a3922408107f3e422dcd369d6dd30c0 (commit just before broken one), post-processing consistently succeeds.

The problem is not folder setup, I haven't changed this for 4 years. NFS share has not changed or been updated in months.

**Comment by philborman** [comment]
There were some changes to making directories to try to track down and get around a problem with Google drive. We currently try to do the equivalent of makedir -p ourselves to get info on each stage of the folder creation. This seems to be failing on your setup, not sure why. I will probably revert the change later today as the Google drive issue seems to be something we can't work around anyway. Sorry for the disruption,

**Comment by splog123** [comment]
No problem. Sometimes you have to write the code and only then find all the $DUMB_ISSUES with $VENDOR :-)

**Comment by philborman** [comment]
Just pushed the reverted code, hopefully ok now.

**Comment by splog123** [comment]
I checked out the latest push, all seems grest from here - previous behaviour restored.

Thanks for the swift reaction!

**Comment by philborman** [comment]
No problem, I was halfway through it anyway ;-)
Google Drive Stream was/is the reason for the change, issue 1244, it doesn't seem to report permissions properly but I can't find a way around it within lazylibrarian
