### ISSUE TITLE
Expected a Session ID from Transmission, got 400

### ISSUE THREAD

**Issue by cinghialino** [DobyTang/LazyLibrarian#1263]
can't configure Transmission, using the same working parameters as Sonarr.
I have transmission on a remote host on port 443, 
and I also noticed that I can't set up the URL base

Please help

To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
d641ceb95291cd3bc54dde54e22d7b5faeb89b94
### Operating system used (windows, mac, linux, NAS type)
Synology with Linuxserver.io Docker container
### Interface in use (default, bookstrap)
bookstrap
### Which api (Goodreads, GoogleBooks, both)
Goodreads
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

**Comment by philborman** [comment]
I have mine set to just localhost and port number
and in transmission config I have
rpc-bind-address  0.0.0.0 
rpc-port  same as lazylibrarian entry 
rpc-username and rpc-password same as lazylibrarian entries
Looks like you are using https (port 443) have you tried plain http?

**Comment by cinghialino** [comment]
I figured it out. Thanks for your help

I needed to add my trailing folder to the hostname so from 
`hostname.domain.com` to `hostname.domain.com/user/`
