### ISSUE TITLE
Connection problems with NZBGet

### ISSUE THREAD

**Issue by inject00r** [DobyTang/LazyLibrarian#1264]
Hi,

I have problems like an issue happened before. Nzbget is connected to all other services. But except to the other services - the connection fails here. I use a docker container and set the ip of the docker network http://10.0.3.1:6789.

For authentication I did setup form authentication.

"NZBget connection FAILED
Check debug log"

NZBget url set to [http://user:password@10.0.3.1:6789/xmlrpc]
Please check your NZBget host and port (if it is running). NZBget is not responding to this combination: [Errno -2] Name does not resolve

Thanks for your help.

**Comment by philborman** [comment]
In lazylibrarian config page just put 
nzbget host  10.0.3.1  (or http://10.0.3.1)
port 6789
username (usually nzbget)
pass (usually tegbzn6789)

No need to put user:password@  or /xmlrpc
We build the full url from the config entries, and we add http:// if it is not already there.

**Comment by inject00r** [comment]
I know, I am using a custom user+strong password.

I am just taking this information from the log which is built from the application.

Therefore I am really wondering why the connection is not working.

The docker gateway is 10.0.3.1, docker subnet ip is 10.0.3.9, nzbget is reachable from: 192.168.178.2:6789 with my user+ password over form auth.

Now I open http://nas:6789/xmlrpc and i get some xml back:
<methodResponse>
<fault>
<value>
<struct>
<member>
<name>faultCode</name>
<value>
<i4>1</i4>
</value>
</member>
<member>
<name>faultString</name>
<value>
<string>Invalid procedure</string>
</value>
</member>
</struct>
</value>
</fault>
</methodResponse>

**Comment by inject00r** [comment]
I mean I also connect Hydra as a provider with the same ip range and it works. And all other docker containers are also working with nzbget.

Therefore I am really wondering why the socket connection is not successfully here.

**Comment by inject00r** [comment]
Ok, I changed the password. Maybe it was to long or it included too many special chars. :-)
