### ISSUE TITLE
Cannot change audiobook status from ignored/skipped

### ISSUE THREAD

**Issue by algarythem** [DobyTang/LazyLibrarian#1266]
Cannot change audiobook status from an ignored/skipped status. On a possible related note, changing the status of an eBook, also changes the status on the associated audiobook.

LazyLibrarian version number: d641ceb95291cd3bc54dde54e22d7b5faeb89b94
Operating system: Windows Server 2012
Interface: default
api: Goodreads
Source of LazyLibrarian installation: git
Attached the debug log crated from the built-in creator
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1823051/debug.zip)

**Comment by philborman** [comment]
I think it's cosmetic. The database values are ok, we are just displaying the wrong button on the AudioBook page (showing ebook status instead of audiobook status). Should get a fix out probably tomorrow.
