### ISSUE TITLE
Command line datadir vs library location?

### ISSUE THREAD

**Issue by barbequesauce** [DobyTang/LazyLibrarian#1268]
I've recently realized I may have conflated the concept of the datadir command line flag and the location of the library. If they are distinct, I'd like to separate them back out.

Can you confirm they are distinct concepts? If so, which files/directories should be considered part of datadir? I'd assume the db, logs, cache folder, ini file... what else?

Thanks in advance for your great support!

**Comment by barbequesauce** [comment]
And - is there anything special I should do prior to moving them?

**Comment by philborman** [comment]
datadir holds the logs, cache, database, config.ini
librarydir just holds the books, metadata, covers
You can safely move them, best into a user directory, and not in the lazylibrarian program directory so you can reinstall without losing books or existing config etc.

**Comment by barbequesauce** [comment]
Thanks!
