### ISSUE TITLE
magazines failing process 

### ISSUE THREAD

**Issue by phairplay** [DobyTang/LazyLibrarian#1269]
hi for some reason my magazines are all failing when hitting processing. i'm running the latest version and i've not changed anything my end. (that i know of)

all folders change to say fail at the end

here is a debug and log
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1826803/debug.zip)
any help would be appreciated

**Comment by philborman** [comment]
Lots of lines in the log like this...
2018-03-17 has failed: Unable to create directory C:\Users\User\OneDrive\Magazines\: [Error 183] Cannot create a file when that file already exists: 'C:\\Users\\User\\OneDrive\\Magazines\\'
so it looks like there is a permissions problem or maybe there is something odd about onedrive?
There were some changes made to try and get "google drive file stream" working, but they have all been replaced now, I think.

Can you try adding a magazine with lazylibrarian debug level 3, we should see lines in the lazylibrarian log about checking for directory existence and trying to create directories. Thanks.

**Comment by philborman** [comment]
Actually scrap that, there is a silly bug. Missing a line. Fix should be out shortly.

**Comment by phairplay** [comment]
All fixed 
Many thanks for the quick response
