### ISSUE TITLE
110 commits behind, won't update

### ISSUE THREAD

**Issue by jrc27** [DobyTang/LazyLibrarian#1273]
LazyLibrarian version number - b53cbb15f05265e21c022a4d9c20310b8a6949b7
Operating system used - Windows
Interface in use - Bookstrap
Which api - Goodreads
Source of your LazyLibrarian installation - Zip file

**Comment by philborman** [comment]
We get this occasionally with git, seems to  get out of step with it's version number calculation. Having said that there have been a few changes to the version detection in the last few weeks, so current version may have solved it. Might be worth doing a manual upgrade (just download a fresh zip from the main git page and reinstall). As long as your data directory and book directory are not inside the lazylibrarian program folder it should all be ok. Otherwise if you post a debug log showing the failed upgrade I can check the messages and see if it's fixed or maybe suggest a workaround.

**Comment by jrc27** [comment]
I tried to do a debug log, but i think it gets wiped on the restart after the failed update.....I have the command prompt type window open....maybe i can run the update again and take a screen grab.

**Comment by jrc27** [comment]
I was able to copy this from the command window...


22-Mar-2018 17:56:56 - INFO :: MAIN : __init__.py:logmsg:1382 : LazyLibrarian is updating...
INFO:lazylibrarian:MAIN : __init__.py:logmsg:1382 : LazyLibrarian is updating...
Traceback (most recent call last):
  File "J:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "J:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file logger.py, line 101
22-Mar-2018 17:56:56 - INFO :: MAIN : versioncheck.py:logmsg:40 : Downloading update from: https://github.com/dobytang/lazylibrarian/tarball/master
INFO:lazylibrarian:MAIN : versioncheck.py:logmsg:40 : Downloading update from: https://github.com/dobytang/lazylibrarian/tarball/master
Traceback (most recent call last):
  File "J:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "J:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file logger.py, line 101
22-Mar-2018 17:56:57 - INFO :: MAIN : versioncheck.py:logmsg:40 : Extracting file J:\LazyLibrarian\master
INFO:lazylibrarian:MAIN : versioncheck.py:logmsg:40 : Extracting file J:\LazyLibrarian\master
Traceback (most recent call last):
  File "J:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "J:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file logger.py, line 101
22-Mar-2018 17:57:04 - INFO :: MAIN : versioncheck.py:logmsg:40 : Deleting file J:\LazyLibrarian\master
INFO:lazylibrarian:MAIN : versioncheck.py:logmsg:40 : Deleting file J:\LazyLibrarian\master
Traceback (most recent call last):
  File "J:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "J:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file logger.py, line 105
22-Mar-2018 17:57:04 - ERROR :: MAIN : versioncheck.py:logmsg:38 : Invalid update data, update failed: ['DobyTang-LazyLibrarian-2f89a49', 'DobyTang-LazyLibrarian-4033963', 'DobyTang-LazyLibrarian-490abf7', 'DobyTang-LazyLibrarian-4f7cfa7', 'DobyTang-LazyLibrarian-8097354', 'DobyTang-LazyLibrarian-ae14d00', 'DobyTang-LazyLibrarian-cca628f', 'DobyTang-LazyLibrarian-d641ceb', 'DobyTang-LazyLibrarian-debbe6b']
ERROR:lazylibrarian:MAIN : versioncheck.py:logmsg:38 : Invalid update data, update failed: ['DobyTang-LazyLibrarian-2f89a49', 'DobyTang-LazyLibrarian-4033963', 'DobyTang-LazyLibrarian-490abf7', 'DobyTang-LazyLibrarian-4f7cfa7', 'DobyTang-LazyLibrarian-8097354', 'DobyTang-LazyLibrarian-ae14d00', 'DobyTang-LazyLibrarian-cca628f', 'DobyTang-LazyLibrarian-d641ceb', 'DobyTang-LazyLibrarian-debbe6b']
Traceback (most recent call last):
  File "J:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "J:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file logger.py, line 101
22-Mar-2018 17:57:04 - INFO :: MAIN : __init__.py:logmsg:1382 : LazyLibrarian is restarting ...
INFO:lazylibrarian:MAIN : __init__.py:logmsg:1382 : LazyLibrarian is restarting ...
Traceback (most recent call last):
  File "J:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "J:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file logger.py, line 101
22-Mar-2018 17:57:04 - INFO :: MAIN : __init__.py:logmsg:1382 : LazyLibrarian is exiting
INFO:lazylibrarian:MAIN : __init__.py:logmsg:1382 : LazyLibrarian is exiting
Lazylibrarian is starting up...
Traceback (most recent call last):
  File "J:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "J:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file logger.py, line 101
22-Mar-2018 17:57:22 - INFO :: MAIN : __init__.py:initialize:561 : Log level set to [1]- Log Directory is [J:\LazyLibrarian\Logs] - Config level is [1]
Traceback (most recent call last):
  File "J:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "J:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file logger.py, line 101
22-Mar-2018 17:57:22 - INFO :: MAIN : __init__.py:initialize:567 : Screen Log set to INFO
Traceback (most recent call last):
  File "J:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "J:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file logger.py, line 101
22-Mar-2018 17:57:22 - INFO :: MAIN : __init__.py:config_read:842 : Config file loaded
Traceback (most recent call last):
  File "J:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "J:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file logger.py, line 101
22-Mar-2018 17:57:22 - INFO :: MAIN : __init__.py:initialize:604 : Database is version 28, integrity check: ok
Traceback (most recent call last):
  File "J:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "J:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file logger.py, line 103
22-Mar-2018 17:57:23 - WARNING :: MAIN : __init__.py:initialize:623 : pyOpenSSL: module missing
Traceback (most recent call last):
  File "J:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "J:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file logger.py, line 103
22-Mar-2018 17:57:23 - WARNING :: MAIN : __init__.py:initialize:623 : OpenSSL missing module/attribute: No module named OpenSSL.SSL
Traceback (most recent call last):
  File "J:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "J:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file logger.py, line 101
22-Mar-2018 17:57:24 - INFO :: MAIN : __init__.py:build_bookstrap_themes:1195 : Bookstrap found 16 themes
Traceback (most recent call last):
  File "J:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "J:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file logger.py, line 101
22-Mar-2018 17:57:25 - INFO :: MAIN : versioncheck.py:logmsg:40 : New version is available. You are 110 commits behind
Traceback (most recent call last):
  File "J:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "J:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file logger.py, line 101
22-Mar-2018 17:57:25 - INFO :: MAIN : LazyLibrarian.py:main:201 : Starting LazyLibrarian on port: 5300, webroot "/lazylibrarian"
Traceback (most recent call last):
  File "J:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "J:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file logger.py, line 101
22-Mar-2018 17:57:25 - INFO :: MAIN : webStart.py:initialize:56 : Starting LazyLibrarian web server on http://127.0.0.1:5300/
Traceback (most recent call last):
  File "J:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "J:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file logger.py, line 101
22-Mar-2018 17:57:25 - INFO :: MAIN : webStart.py:initialize:106 : Web server authentication is enabled, username is

**Comment by philborman** [comment]
ok, thanks for that. Looks like I need to study that a bit. Might be the new version is trying to run before the old one has closed down. There is a "sleep" instruction when the new one start up to allow the old one to close files down, might need to extend the sleep time.

I think easiest solution for you would be to make sure books, database, config and cache are not in the lazylibrarian folder, then download a new zip and reinstall.

**Comment by jrc27** [comment]
I just cloned to a new folder and then copied the files to my existing and let it re-write what was already there and I think it's working ok....I check for an update and it says i am up to date.
