### ISSUE TITLE
Latest master version of LL gives an error while doing an initial scan of my books.

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1274]
Latest master version of LL gives an error while doing an initial scan of my books.

2018-03-21 17:08:24 | ERROR | EBOOK_SCAN | librarysync.py | LibraryScan | 959 | Unhandled exception in libraryScan: Traceback (most recent call last): File "X:\Applications\lazylibrarian\lazylibrarian\librarysync.py", line 773, in LibraryScan book_filename = bookRename(bookid) File "X:\Applications\lazylibrarian\lazylibrarian\bookwork.py", line 347, in bookRename for fname in os.listdir(makeBytestr(r)): WindowsError: [Error 3] The system cannot find the path specified: 'X:\\Anthony\\Book\\Books\\M\xc3\xa1rio Alves\\The Master Collection/*.*'
-- | -- | -- | -- | -- | -- | --
2018-03-21 17:08:24 | DEBUG | EBOOK_SCAN | librarysync.py | LibraryScan | 766 | Librarysync link to preferred type pdf: X:\Anthony\Book\Books\Mário Alves\The Master Collection\Mark Twain - The Master Collection.pdf

**Comment by philborman** [comment]
Hmm, problem doing accented character translation on a windows filename.
The code is trying to make sure the book matches the naming style you have configured for lazylibrarian eg author/title (series #num)  Simple fix is to turn off "Rename existing books on libraryscan" in config so we don't try, but it's not really the right answer. Need to look into accented characters in windows filenames. I guess it's a unicode issue with lazylibrarian default being utf-8 and windows being latin-1.
Might take some time to fix properly as I don't have a windows system to try it on at the moment.

**Comment by MrMxyzptlk** [comment]
I will temporarily change the accented character.
Please let me know how I can help, I can test updates on my Windows system if you like?

**Comment by MrMxyzptlk** [comment]
So I moved the few books I had that were causing to the parser to fail. The library scan completed, but indicated 250 of my books were of unknown language. Is there an easy way to delete those books through LL?

I would still like you to look into the accent characters issue...thanks!

**Comment by philborman** [comment]
Couple of options. There is an api command listNoLang which will display them, or use the language filter on the ebooks page. Or leave them for now. The next major release of lazylibrarian has a new source for isbn lookups (if we don't know the language from goodreads we try looking it up using the isbn, but often when goodreads has no language it has no isbn as well). The numbers of books with no language should go down significantly with the new version.

Accented characters might take me a couple of days as need to get a windows vm up and running first.

**Comment by MrMxyzptlk** [comment]
Thanks, let me know if you need help testing...

**Comment by philborman** [comment]
Do you have python3 on your windows box?   I think the problem is fixed under python3

**Comment by MrMxyzptlk** [comment]
I'm running 2.7 as most of my apps require this. I'm thinking I can install both 3 and 2.7 at the same time I will try this...and let you know the outcome.

**Comment by philborman** [comment]
No reason why you can't have both pythons installed. 
2.x is due to be deprecated in a year or so...
Could make lazylibrarian work with windows accented filenames, but might be a fair bit of work.

**Comment by MrMxyzptlk** [comment]
V3 fixed it!

Thanks for the tip, now you don't have to waste your time fixing that bug.
