### ISSUE TITLE
Feature Request: Group editor for authors.

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1276]
Say if I want to delete 30 authors, rather than delete them one at a time, it would be nice to delete all 30 at once.

Also have the option to delete all of their books at the same time.

Thanks!

**Comment by philborman** [comment]
A bit risky, I think, would be too easy to delete all your authors and also their books. Safer to do one author at a time with a prompt to remind you.

**Comment by MrMxyzptlk** [comment]
No more risky than going to the ebooks tab and selecting all, and deleting?
Like you said just put a notification box that shows, "Are you sure you want to delete XX authors?, this CANNOT be undone!".

That message should be enough, right?

**Comment by philborman** [comment]
Added that to next version. Can't display a count of the authors though, message just says "Are you sure you want to permanently delete the selected authors and their books?"
Two options, Remove and Delete. Remove just removes database entries, delete also deletes the book files and the directories they are in (includes jpg, opf, other formats)

**Comment by MrMxyzptlk** [comment]
Ha! Thanks, that will make things even better. When are you releasing the new version? Need a beta tester? Wink, Wink, Nudge, Nudge?

**Comment by philborman** [comment]
The next version needs a fairly major database upgrade. Not the author deletion stuff, that's fairly minor. We used to get series information from LibraryThing but they have disabled one of their api interfaces so now we have to look elsewhere for the info. We can get similar info from goodreads, but it needs a database rebuild which is quite time consuming. My own library (12000 books, 260 authors) took 6hrs to upgrade. Would like to speed it up if possible, but there are limits on how quickly we can call goodreads. Googlebooks is very poor at series info, at least via their api, and I don't want to have to scrape html pages as they keep changing.  No timescale for the new version yet, it's working fine but could do with some optimising. If you want to try the new version there is a copy at https://github.com/philborman/LazyLibrarian.git

**Comment by MrMxyzptlk** [comment]
I installed the 'new' version in parallel with the current version, and it's working very well! Thank you.

I noticed a couple of 'bugs' which you may or may not be aware of.

1. If you click on the "Image" link on the first tab of LL, it hide the checkbox column instead of the image column. I'm guessing your code is still 'flipping' the 1st column which used to the authors image.

2. Some of the authors converted in the paused state which is fine, but that left their image blank.

Keep up the great work...

**Comment by philborman** [comment]
Thanks for the bug report. Fixed the toggle issue, not sure what the problem is with paused author images yet.  Will look into it.

**Comment by MrMxyzptlk** [comment]
It took over night for my DB upgrade, but it finished just fine.

The update took care of the author image toggle, and it's looking good.

**Comment by MrMxyzptlk** [comment]
I just noticed the new version db 29 won't start using Python 3 only 2, weird?
So now I'm back to the author name issues from before?

**Comment by MrMxyzptlk** [comment]
Here is the error when running with Python 3:

X:\Applications\LazyLibrarian>C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\python.exe lazylibrarian.py
Traceback (most recent call last):
  File "lazylibrarian.py", line 13, in <module>
    import lazylibrarian
  File "X:\Applications\LazyLibrarian\lazylibrarian\__init__.py", line 29, in <module>
    from lazylibrarian import logger, postprocess, searchbook, searchrss, librarysync, versioncheck, database, \
  File "X:\Applications\LazyLibrarian\lazylibrarian\postprocess.py", line 39, in <module>
    from lazylibrarian.calibre import calibredb
  File "X:\Applications\LazyLibrarian\lazylibrarian\calibre.py", line 20, in <module>
    from lazylibrarian.importer import addAuthorNameToDB, search_for, import_book
  File "X:\Applications\LazyLibrarian\lazylibrarian\importer.py", line 22, in <module>
    from lazylibrarian.grsync import grfollow
  File "X:\Applications\LazyLibrarian\lazylibrarian\grsync.py", line 25, in <module>
    from lazylibrarian.gr import GoodReads
  File "X:\Applications\LazyLibrarian\lazylibrarian\gr.py", line 30, in <module>
    from lib.isbnlib import isbn_from_words
  File "X:\Applications\LazyLibrarian\lib\isbnlib\__init__.py", line 22, in <module>
    from ._ext import (cover, desc, mask, meta, info, editions, isbn_from_words,
  File "X:\Applications\LazyLibrarian\lib\isbnlib\_ext.py", line 12, in <module>
    from ._metadata import query
  File "X:\Applications\LazyLibrarian\lib\isbnlib\_metadata.py", line 6, in <module>
    from .registry import services
  File "X:\Applications\LazyLibrarian\lib\isbnlib\registry.py", line 4, in <module>
    from pkg_resources import iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by philborman** [comment]
Missing a library. Thought it was standard but apparently not. You have it installed on your system for python2 but not python3
`pip3 install pkg_resources `  will get it for you.  Only a temporary problem anyway, the library that uses it in lazylibrarian is isbnlib, and we only use that for one function (isbn_from_words) which can be done directly without using the lib. isbnlib had some other useful looking functions but they are too slow so are not being used. I will probably remove isbnlib later today.

**Comment by MrMxyzptlk** [comment]
I will install that and test momentarily.

I noticed that during the DB upgrade it keep showing in the log 'WorkNow' disabled? No error, but just curious what that meant?

**Comment by philborman** [comment]
WhatWork

It was an api provided by librarything, but it's been disabled because of overuse (hopefully not by us!)

If you called WhatWork with an ISBN it would return book details including title,author,cover image, what series the book is in, other authors/contributors/illustrators/editors/translators, alternative ISBN for the same book. Very useful.

We used to cache the results so we didn't call librarything too often, and the code is still in lazylibrarian just disabled with a switch. If they enable the api again we can flip the switch back. Existing cached results will be kept (cache won't expire) but no new results will be looked for or cached.

**Comment by MrMxyzptlk** [comment]
Got it.

I'm having issues installing pkg_resource for Python 3:

C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32>python.exe -m pip install pkg_resource
Collecting pkg_resource
  Could not find a version that satisfies the requirement pkg_resource (from versions: )
No matching distribution found for pkg_resource

**Comment by philborman** [comment]
ok, don't worry, it's gone from lazylibrarian now. We have our own equivalent. It used to just call google with a query string and we had most of the code to do that already.

**Comment by philborman** [comment]
I notice you are trying pip,  on linux pip is for python2,  you need pip3  for python3 packages

**Comment by MrMxyzptlk** [comment]
I will just wait until you update the 'new' philborman version of LL.

**Comment by philborman** [comment]
Just done.
