### ISSUE TITLE
Allow to override Slack notification URL

### ISSUE THREAD

**Issue by MrTimscampi** [DobyTang/LazyLibrarian#1278]
Discord has Slack-compatible webhook URLs and I use those on other services I run (Sonarr, Lidarr, Radarr, etc) to notify my users of new downloads.

I noticed in slack.py that the URL for Slack Notifications is hardcoded, and it'd be great to be able to override it through the UI, much like Sonarr/Radarr/Lidarr, to be able to send notifications to Slack-compatible services without having to roll out a custom script for it.

**Comment by philborman** [comment]
Should be easy enough to add, you just need the "https://hooks.slack.com/services/" to be configurable?
Is it always https, or is http valid (in case the user doesn't supply either in config)

**Comment by MrTimscampi** [comment]
That's pretty much all that's needed, yes :)
Discord auto-generates the webhook URL on a per-channel basis. It's always HTTPS (It auto-redirects to HTTPS as well).

**Comment by philborman** [comment]
No problem, I have added that in. Just wasn't sure what to do if the user supplied a webhook without specifying HTTP or HTTPS  Most of the other places in lazylibrarian where that happens (downloaders, providers) we tag HTTP on the front.
