### ISSUE TITLE
Feature Request: send different category to down loaders

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1279]
Feature Request: send different category to down loaders.

For example send the 'books' category for book downloads, and 'magazine' for magazines downloads.

**Comment by philborman** [comment]
Would get quite messy, 3 labels or categories per downloader that understands them (not all do).One each for  eBooks, Magazines, AudioBooks. Can't really use the same labels for all downloaders as your nzb downloader might need a different label to your torrent downloader. Minimum of 6 required. Is it really worth it?  Lazylibrarin itself doesn't need them, it queries the downloaders for location on completion.

**Comment by MrMxyzptlk** [comment]
I can't speak for everyone else but it would definitely clean up things on my end.
I only use Deluge (new beta 2.0 is awesome), and SABnzbd.

The main issue I have that this would solve for me, is that 90% of the 'books' that LL sends to either down loaders are still videos. I had tried to fix this with you in the past but size limits / filters / exclusions didn't take care of the issue. 

All of these videos are coming from LL automatic magazine searching not books. So if I could send magazines to the down loaders as a different category, I could process these videos on the down loader side of things.

**Comment by philborman** [comment]
Would be better to figure out why we are getting videos instead of Magazines.
The searches for newznab/torznab have categories attached so the providers should only return the right categories. Not so with torrents. Also some torrent providers don't give us sizes so we can't filter on that. Not sure how we manage to match a magazine title and a valid looking date against a video though.

**Comment by MrMxyzptlk** [comment]
Yeah they are all torrents.

Here is an example that was sent from LL. I'm assuming this is from a search for one of my magazines "Kandy".

This is in Deluge...

AssTraffic - Kandy Kors NEW 20 January 2018

There are so many variations of videos sent I can't begin to use the filter for this.

**Comment by philborman** [comment]
That's difficult.
Are they all from the same torrent source (piratebay, limetorrents etc.) If so maybe you could drop that source? Alternatively it might be possible to query deluge after the download has started to see what the file sizes are going to be, and abort the download if it doesn't match the filters. Most of the code is probably there in lazylibrarian, just need to implement it in the postprocessor.
BTW how does deluge work with lazylibrarian, haven't tried deluge2 myself, still using transmission as I'm on a low powered Raspberry Pi. Are you using deluge daemon or webui?

**Comment by MrMxyzptlk** [comment]
I used Transmission forever but found Deluge to be much more robust; however the web gui was very sluggish and buggy.

Then it all changed...I found out they had Deluge 2.x beta out with an updated web gui. I installed last week and it has none of the issue of the previous web gui, rock solid, lots of torrents with no lost connections! I highly recommend it.

OK...I like that idea. I have some pretty large books and mags, but I think we could eliminate a lot of the video issues. Let me know...

**Comment by philborman** [comment]
We can check the size of each file in deluge once the download has started, and also check the filenames. Haven't looked at the other downloaders yet.

What do you think is best, reject the whole torrent if it contains a file with a banned extension (avi, mp4, iso whatever)  or reject the whole torrent if one file is more than a certain size?

**Comment by MrMxyzptlk** [comment]
The first option; banned extension.

Too many books and mags are larger than some of my videos.

**Comment by philborman** [comment]
ok, that's just being tested.

**Comment by MrMxyzptlk** [comment]
I may have fixed most of MY issue. 
I assumed when LL queried my providers it was populating all of the correct cats...but I assumed incorrectly.
I have researched all of my providers and put in the 'proper' cats for books, mags, audiobooks, and am running a full search. I will let you know the outcome.

**Comment by MrMxyzptlk** [comment]
Lo and behold no videos.

But if I look in the past issues there are tons, so I'm hoping the banned extension resolution, will clear these out?

The search added about 10,000 mags to the past issues. Hopefully what you are testing will clear out 3/4 of these.
