### ISSUE TITLE
Post processing broken

### ISSUE THREAD

**Issue by nncrypted** [DobyTang/LazyLibrarian#128]
I've noticed if I rename the folders in my download dir to the corresponding file names in the LL history then it post processes as it used to.

**Comment by daktak** [comment]
Using SAB?

**Comment by nncrypted** [comment]
Using sab and trying torrent. So noticed torrent just drops the file in the root and sab puts it in a folder was under the impression the file had to be in a folder in order to post process it. Also needed the LL ### sequence in order to process it which seems to have disappeared

**Comment by nncrypted** [comment]
Ok I just turned torrent search off and it works fine using sab folders are properly named and processed fine so it seems to just be torrents that fail

**Comment by daktak** [comment]
It seems the tor_title contains the LL.( and is saved when using TOR_BLACKHOLE in searchtorrents. However this is not currently passed to utorrent or transmission.

**Comment by danhosler** [comment]
Just checked to see if switching from utorrent to blackhole would fix this, but it does not. post processing still won't pick up my torrent downloads. I'm using utserver.
