### ISSUE TITLE
Feature Request: 'save' buttons at top, instead of bottom of screen

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1280]
Feature Request: 'save' buttons at top, instead of bottom of screen.

For example I have several hundred magazines, and on the filter tab of the configuration, I have to scroll wayyyyy down to click save on every edit.

It may work great to somehow lock the 'top' menus on each of the tabs for the same reason; if possible?

**Comment by philborman** [comment]
Added save button at top now, can't see how to lock the menus though.

**Comment by MrMxyzptlk** [comment]
Awesome! Thank you...

**Comment by MrMxyzptlk** [comment]
Ha! I just remembered I'm using your 'new' version from the PhilBorman fork...I guess I won't see this change until you merge these 2?

**Comment by philborman** [comment]
Yes, quite hard to merge one part on its own.
For the save buttons you could just copy bookstrap/config.ini across from my fork, that's the only file changed

**Comment by MrMxyzptlk** [comment]
OK, I may try that.

The funny part is that Headphones somehow 'froze' the upper menu?

**Comment by philborman** [comment]
Yeah, it's not that it can't be done, it just can't be done BY ME
No idea how to...
