### ISSUE TITLE
Transmission ReadTimeout

### ISSUE THREAD

**Issue by ethanopp** [DobyTang/LazyLibrarian#1281]
Transmission seems to be timing out when sending torrents from LL, but the connection works fine when I test from the Downloaders config page 'Test Transmission' = 'Transmission login successful'

### LazyLibrarian version number (at the bottom of config page)
4033963e370b5d42523731b9d7ea8d9fb3ffd30b
### Operating system used (windows, mac, linux, NAS type)
QNAP Linux Docker
### Interface in use (default, bookstrap)
default
### Which api (Goodreads, GoogleBooks, both)
Goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
linuxserver.io docker
### Relevant debug log with api keys and any passwords redacted
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1853067/debug.zip)

**Comment by philborman** [comment]
Odd, can't reproduce it. I use transmission all the time for torrents. Is it a recent change that's caused the problem? There were some changes to transmission.py about 10 days ago, but nothing that leaps out as a possible cause for the issue. What's puzzling me is that the code to get authorisation is working, but adding the torrent isn't, yet they use the same function to talk to transmission...  Might need some extra debugging messages to see what's going on. Are you able to log into your docker and issue a few commands?

**Comment by ethanopp** [comment]
Yeah I've been using for a while with no issues... Which commands?

**Comment by MrMxyzptlk** [comment]
Oddly enough I'm getting the same thing with Deluge just now.


2018-03-27 19:39:14 | INFO | SEARCHBOOK | searchbook.py | search_book | 288 | Search for Wanted items complete, found 0 books
-- | -- | -- | -- | -- | -- | --
2018-03-27 19:39:14 | ERROR | SEARCHBOOK | downloadmethods.py | TORDownloadMethod | 344 | DelugeRPC failed CallTimeoutException
2018-03-27 19:38:54 | DEBUG | SEARCHBOOK | client.py | call | 90 | Calling reqid 2 method 'daemon.login' with args:(u'mrmxyzptlk', u'WNV95$nsnJb6CPe') kwargs:{}
2018-03-27 19:38:54 | DEBUG | SEARCHBOOK | client.py | connect | 70 | Connected to Deluge, logging in
2018-03-27 19:38:54 | INFO | SEARCHBOOK | client.py | connect | 59 | Connecting to localhost:58846
2018-03-27 19:38:53 | DEBUG | SEARCHBOOK | downloadmethods.py | TORDownloadMethod | 313 | Sending Sue Klebold - A Mothers Reckoning LL.(25937671) to Deluge

**Comment by MrMxyzptlk** [comment]
I'm wondering if my issue comes from a new Deluge 2.x SSL requirement?

https://github.com/JohnDoee/deluge-client/issues/6

**Comment by philborman** [comment]
@MrMxyzptlk  Quite likely, looks like we need to upgrade our deluge rpc client for deluge v2. I think it's a drop-in replacement so should be easy to try, they upgraded the library a week ago.

**Comment by philborman** [comment]
@ethanopp There were some changes about 10 days ago to do with keeping session_id and host_url between calls, supposed to speed communication up as we don't need to keep repeating stuff. I'm guessing that's not working, though not sure why at the moment.
Can you edit lazylibrarian/transmission.py and add some debugging lines, if not I will post you a version with the debugging added. 

In the torrentAction function towards the end of the file, we seem to be getting auth ok, and then failing on the real request. There is a comment `# Prepare next request` around line 235.  Just below that put
```
logger.debug(host_url)
logger.debug(headers)
```
That will check if we are getting the host built correctly from it's parts, and also if we have authorisation

**Comment by MrMxyzptlk** [comment]
OK, I added the code, and then searched for the same book...same error message.
I have 5 second refresh on the LL log, and it pauses for 15 seconds or so after the line with call daemon login.


2018-03-28 07:42:14 | INFO | SEARCHBOOK | searchbook.py | search_book | 288 | Search for Wanted items complete, found 0 books
-- | -- | -- | -- | -- | -- | --
2018-03-28 07:42:14 | ERROR | SEARCHBOOK | downloadmethods.py | TORDownloadMethod | 344 | DelugeRPC failed CallTimeoutException
2018-03-28 07:41:54 | DEBUG | SEARCHBOOK | client.py | call | 90 | Calling reqid 2 method 'daemon.login' with args:(u'mrmxyzptlk', u'***********') kwargs:{}
2018-03-28 07:41:54 | DEBUG | SEARCHBOOK | client.py | connect | 70 | Connected to Deluge, logging in
2018-03-28 07:41:54 | INFO | SEARCHBOOK | client.py | connect | 59 | Connecting to localhost:58846
2018-03-28 07:41:53 | DEBUG | SEARCHBOOK | downloadmethods.py | TORDownloadMethod | 313 | Sending Sue Klebold - A Mothers Reckoning LL.(25937671) to Deluge

**Comment by philborman** [comment]
ok, I might have to try and set up a deluge2 instance here. Might take me a few days though. 
You are failing to login and timing out waiting for the response.  I tried the new deluge library with version 1 deluge and that's working ok.

**Comment by MrMxyzptlk** [comment]
So I just remembered I use the web gui, and it doesn't use a username but a password only.
So I looked at the Deluge down loader in LL, and discovered their was a username box that wasn't there before.

I removed the username, saved, and tested. Here is the new error.


2018-03-28 08:07:29 | DEBUG | WEBSERVER | deluge.py | _get_auth | 253 | Deluge: Connection failed, let's try HTTPS just in case
-- | -- | -- | -- | -- | -- | --
2018-03-28 08:07:28 | DEBUG | WEBSERVER | deluge.py | _get_auth | 234 | Deluge: FYI no SSL certificate configured
2018-03-28 08:07:28 | DEBUG | WEBSERVER | deluge.py | _get_auth | 215 | Deluge: Authenticating...
2018-03-28 08:07:28 | DEBUG | WEBSERVER | deluge.py | checkLink | 525 | Deluge: Checking connection

**Comment by philborman** [comment]
Settings problem, I think. Check the settings for user/pass/host/port
  
Daemon port is usually 58846, needs user and pass and no HTTP or HTTPS in the hostname

WebUI port is usually 8112, just needs pass  -  which might be a different pass to daemon, no user, needs ssl setting to match (if deluge webui says ssl enabled you need lazylibrarian host to use HTTPS)

**Comment by MrMxyzptlk** [comment]
OK, I've got it working. 

I always connect to the web ui in Radarr, Sonarr, LazyLibrarian, etc...
and somehow the new unreleased version of LL defaulted to connecting to the Deluge daemon.

Once I changed it back to connecting to the web ui, it started connecting no problem.

**Comment by philborman** [comment]
@MrMxyzptlk excellent, we can regard that as fixed!

**Comment by philborman** [comment]
@ethanopp  Managed to reproduce what you're seeing when my internet connection went down.  Can authorize with transmission (as on local net) but can't send a torrent to it, timeout as unable to connect to trackers. Could it be something similar you are seeing?  Maybe a proxy server issue or a route problem?

**Comment by ethanopp** [comment]
@philborman Could be - noticing a different error message now:
```
2018-03-28 18:06:55 | ERROR | SEARCHBOOK | transmission.py | torrentAction | 245 | Transmission ValueError: No JSON object could be decoded
```
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1857963/debug.zip)

Logs attached... Also added those two lines of code but not sure if they are showing up?

**Comment by philborman** [comment]
Yes they are showing up, lines 238 and 239, looks ok,  we have communication now,  but  not getting a valid json response. Could be a transmission version difference, what version are you on? Could be a json decoding issue as we are using "requests" to decode, not the external json library used in previous versions - any idea what version of requests you are using?

**Comment by ethanopp** [comment]
using the linuxserver.io container

```
pip show requests
Name: requests
Version: 2.18.4
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /usr/lib/python2.7/site-packages
Requires: chardet, certifi, urllib3, idna

```

**Comment by philborman** [comment]
Well, it looks like we are getting our message across to transmission, and getting a response, just not in the format we are expecting. Your requests version is slightly ahead of mine, but that should be ok, some quite old versions of requests didn't have a built-in json decoder. Your transmission version is exactly the same as mine.

One other thing we can try. Since we are getting a response (just can't decode it), can you try adding another debug line . You currently have the error message
`transmission.py | torrentAction | 245 | Transmission ValueError: No JSON object could be decoded`
Just above that line can you put
`logger.debug(response.text)`
`logger.debug(response.status_code)`  
which will show us what we got back so we can see why it didn't decode.

**Comment by ethanopp** [comment]
Attached
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1860628/debug.zip)

**Comment by philborman** [comment]
Debug log is showing timeout again rather than the decode issue.

**Comment by ethanopp** [comment]
Ran it again... Seems hit or miss which error I am getting, this time got the json error one though...
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1860889/debug.zip)

**Comment by philborman** [comment]
Frustrating, the debug log is not showing the extra lines we need adding just above the json error
logger.debug(response.text)
logger.debug(response.status_code)

**Comment by ethanopp** [comment]
Whoops my bad - had put the loggers outside of the except so they were executing after the response='' line.

...Attached again
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1861026/debug.zip)

**Comment by philborman** [comment]
Hmm, ok.  Here is a complete new section to retry as per the message. Remove everything from the Try: line to the except Exception line and insert this new block in it's place...

```
    try:
        response = requests.post(host_url, json=data, headers=headers, proxies=proxies,
                                 auth=auth, timeout=timeout)
        if response.status_code == 409:
            session_id = response.headers['x-transmission-session-id']
            logger.debug("Retrying with new session_id %s" % session_id)        
            headers = {'x-transmission-session-id': session_id}
            response = requests.post(host_url, json=data, headers=headers, proxies=proxies,
                                     auth=auth, timeout=timeout)
        if not response.status_code.startswith('2'):
            logger.error("Expected a response from Transmission, got %s" % response.status_code)
            return
        return response.json()

    except Exception as e:
```

**Comment by ethanopp** [comment]
...Just getting the timeout errors again now

*Apologies - clicked closed by accident

**Comment by philborman** [comment]
ok, is that timeout after the first try, or the second (do yo u get the new "retrying with..." message before or after the timeout)

**Comment by philborman** [comment]
Is that before or after the "Retrying with new session_id %s" message, ie in the log do you get timeout first, then the retrying message, which means it's the first attempt failing, or does the retry fail as well. If the retry is failing you will see "Retrying with new session_id %s"  and then the timeout message

**Comment by ethanopp** [comment]
Doesn't look like there is anything in the logs with "*Retrying*"

**Comment by ethanopp** [comment]
Alright think I'm getting closer...

Verified that the issue is coming from transmission... Tried manually going to the host_url in my browser (http://10.0.3.1/transmission/rpc) and got the 409

Then went into to config from LL to see if the connection to transmission was still successful and it is not:

```
2018-03-29 15:49:33 | ERROR | WEBSERVER | transmission.py | torrentAction | 260 | Error sending torrent to Transmission
2018-03-29 15:49:33 | ERROR | WEBSERVER | transmission.py | torrentAction | 256 | Transmission AttributeError: 'int' object has no attribute 'startswith'
```

I changed the following line in the code you provided to convert to string and the connection to transmission works now:
`if not str(response.status_code).startswith('2'):`

...The bad news is that I am still getting the timeout error lol

**Comment by ethanopp** [comment]
Still timed out

**Comment by ethanopp** [comment]
What's even more odd is that if I then test the config connection to transmission again, it works, and in the logs still has the same session ID... So it must be something other than the session ID causing it to timeout.

**Comment by philborman** [comment]
Headers are case independent, or supposed to be, good to see transmission is following the standard ;-)
I suspect the problem is transmissions internet connectivity rather than lazylibrarian, as the only way I can reproduce it is when my internet connection is playing up. Routing issue maybe, proxy server, vpn ?

**Comment by ethanopp** [comment]
Dont think it's internet... Sonarr/Radarr have downloads going to it fine :/

...Also if there was internet connection, wouldn't when we "test connection" from LL fail?

**Comment by philborman** [comment]
No, LL "test connection" just checks we can talk to transmission and our user/password are accepted. Doesn't check transmission can talk to the outside world.
I get __exactly__ the same symptoms as you if my internet is down (rural Spain, flaky microwave mesh system).  I can talk to transmission over wifi via my router, so login is fine, but transmission can't talk to trackers and times out when I try to add a torrent to it. That's why I wondered if your issue was similar, but since Sonarr/Radarr are working with transmission it can't be that.

The other difference between "test connection" and "add torrent" is that "test" uses a GET command and "add" uses s POST command.  POST is a bit more fussy about parameters. Maybe something is wrong there.  Has transmission ever worked for you with lazylibrarian, as there were some changes a few weeks ago. If it was working for you a while back it might be worth retro-fitting some old code to test.

**Comment by ethanopp** [comment]
Well regardless of Sonarr/Radarr, LL is still able to get that actual request from my indexes to post to transmission so this is why I do not thinK it’s internet...If I copy and paste the actual ‘post’ to my web browser it downloads the .torrent.

LL has worked with my setup for several hundred books already, this is just started happening recently - and I auto update the container ever Friday... think you’re right about the post because that is where it times out... how can I test the old code?

**Comment by philborman** [comment]
Ah, well if it used to work before, it's almost certainly us!
Any idea when it stopped working, to narrow down the search a bit?
I can post you several older versions of the transmission.py file to try :-)

I suspect the most likely candidate is the json encoding part. If so, that's easy enough to try...
I transmission.py the POST command looks like...
```
        response = requests.post(host_url, json=data, headers=headers, proxies=proxies,
                                 auth=auth, timeout=timeout)
```
Change it to 
```
        response = requests.post(host, data=json.dumps(data), headers=headers, proxies=proxies, 
                                 auth=auth, timeout=timeout)
```
and at the top of the file, in among the other imports, put
`import json`

**Comment by ethanopp** [comment]
Should host_url be chainging to host?

**Comment by ethanopp** [comment]
So the following?
```
response = requests.post(host_url, data=json.dumps(data), headers=headers, proxies=proxies, 
                                 auth=auth, timeout=timeout)
```

**Comment by philborman** [comment]
Yes, looks fine.  The only change is instead of using requests library to convert the data to json, we are doing it ourselves with a separate json library

**Comment by ethanopp** [comment]
Same issue...

**Comment by philborman** [comment]
ok, here is the transmission file from end of February. Just drop-in and rename it to transmission.py
[transmission.zip](https://github.com/DobyTang/LazyLibrarian/files/1864029/transmission.zip)
If that works I will revert back to the old version.

**Comment by ethanopp** [comment]
Still erroring out
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1864214/debug.zip)

**Comment by philborman** [comment]
Maybe the problem has been there longer than you think?
Here is the version of transmission.py from Jan 1st.
Prior to that it hadn't changed for 5 months.
[transmission.zip](https://github.com/DobyTang/LazyLibrarian/files/1864292/transmission.zip)

**Comment by philborman** [comment]
Not sure if this will help, but if you go back to a fairly current version and add these 6 lines near the top of transmission.py just before the "This is a simple script" comment, it enables verbose debugging for the requests library so we see the communication in more detail

import logging
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True

**Comment by ethanopp** [comment]
Added those lines, logs still look the same though
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1864468/debug.zip)

**Comment by philborman** [comment]
Don't know where to go from here then - doesn't seem to be related to anything changed in lazylibrarian?

**Comment by philborman** [comment]
Another thought...
You could try downloading a zip file of the lazylibrarian image from a month or two ago and installing a whole clean copy of lazylibrarian to try with transmission. This one is 6 weeks ago https://github.com/DobyTang/LazyLibrarian/archive/1.5.0.zip
and this is end of December 
https://github.com/DobyTang/LazyLibrarian/archive/1.4.3.zip

If the problem is still there, and it was clearly working before, then something else has changed.

**Comment by ethanopp** [comment]
Funny you said that... I had somewhat given up on getting my current version to work and am in the process of setting it up from scratch... As soon as i booted it up I realized how outdated my config was...

The whole program looks WAY better, I was still on the old white style...

Hopefully once I get set up again it'll work, will let you know

**Comment by ethanopp** [comment]
Taking a little while for it to sync up with all my books so I cant ask it to try to download again....

Unrelated question here, I see some new settings in here though.

I use both Calibre and LL in separate dockers on the same host... If I want to use the calibre content server to sync with LL, do I also need to user calibredb?

**Comment by ethanopp** [comment]
Fresh install did the trick... not sure exactly what the issue was - I am convinced it was just a function of having the old config files saved for over a year and them not being caught up to speed with all of the updates that have been made since...

Thanks for the help!

**Comment by ethanopp** [comment]
Re-opening this as I believe there is still an issue... After some additional testing, I've come to realize that the issue is not with transmission, it is with TORZNAB... I am using a jackett container to route my indexers into LL.

Using the Torrent Providers (kickass, zooqle, etc.) work fine with sending to transmission

**Comment by philborman** [comment]
Your previous debug logs show transmission timeout sending torrents from zooqle and TPB ?

Are you still seeing timeouts, or are you getting different errors now?

**Comment by ethanopp** [comment]
Not sure I follow - The timeouts before were from the torznab requests...

I now disabled all of the torznab and just enabled the torrent providers and its sending to transmission successfully

**Comment by philborman** [comment]
Sorry, that's me mis-reading the log. I will enable Jackett or Cardigann here and have a play...

**Comment by ethanopp** [comment]
Oh should they only have 'eBook'? Right now I have both categories in the configs

**Comment by ethanopp** [comment]
I matched the eBook category for alpharation to what is showing in Jackett.. still same issue. Logs attached.
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1866347/debug.zip)

**Comment by philborman** [comment]
104‰ looks wrong but isn't. 100% match for what you asked for, plus a few bonus points because the download title includes formats you want.

The left hand side is blank because that provider does not have a dedicated book search, which is normal for torznab

I think the problem is that jackett sometimes redirects the url to a new one internally, and feeds you a new one. If it feeds you a magnet link the requests library can't handle it. I think I have a work around, will post details later today

**Comment by philborman** [comment]
ok, in the file downloadmethods.py there is a transmission section around line 300. You should see
` downloadID = transmission.addTorrent(tor_url)  # returns id or False`
If you can change that to
```
        if torrent.startswith('magnet'):
            downloadID = transmission.addTorrent(torrent)  # returns id or False
        else:
            downloadID = transmission.addTorrent(tor_url)  # returns id or False
```
this will send the magnet link to transmission, not the jackett url that redirect to the magnet link. The redirect certainly confuses requests library, and maybe transmission too.

**Comment by ethanopp** [comment]
Still getting the error...

Added a debug line in there to see what downloadID is returning and its 'False' even with the code above.

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1868537/debug.zip)

**Comment by philborman** [comment]
ok, thanks for trying. Can we try and see what's in "torrent" before we send anything to transmission...
In downloadmethods.py, line 206 is a logger.debug(sending file to transmission)
just after that add
`logger.debug("TORRENT %s [%s] [%s]" % (len(torrent), torrent[:20], torrent[-20:]))`

**Comment by ethanopp** [comment]
`TORRENT 2725 [d8:announce75:http:/] [\xcd\x9b\xed\x1eh\xab7:privatei1eee]`

**Comment by philborman** [comment]
Excellent, we should be able to send that to transmission, just need to encode it first...
[transmission.zip](https://github.com/DobyTang/LazyLibrarian/files/1868754/transmission.zip)

**Comment by ethanopp** [comment]
Working!!! Thanks for struggling through that one with me 😄

**Comment by philborman** [comment]
Ok great news, thanks. I will add this into the next release.  The next version has a __big__ database upgrade too, so takes a while. I'm not able to issue this as a separate version unfortunately, too many intertwining changes in other files.  I might have a look if we can do something similar with the other torrent downloaders first, deluge, qbittorrent etc, ie send the encoded torrent instead of the link. Should stop any issues with jackett redirects.

**Comment by ethanopp** [comment]
Okay good to know - I'll keep that zip handy just in case I forget and upgrade by accident prior to this being implemented.

**Comment by philborman** [comment]
Lazylibrarian internal upgrade will refuse to work as there are local changes, so it won't overwrite them.
Will only be an issue if you update the whole docker.

New version might be out in a week or so

**Comment by ethanopp** [comment]
Oh okay perfect! Will remove LL from my auto-docker-refresh script for now then.

Thanks again!
