### ISSUE TITLE
[Feature Request] Calibre

### ISSUE THREAD

**Issue by mccorkled** [DobyTang/LazyLibrarian#1282]
I have been using the Thraxis version of your program since it has Calibre built in. Thraxis NEVER responds to issues and I was curious if you could implement it into your build so that we can all benefit from it and then you could help answer questions pertaining to it since you would see the code. 

LL has been importing multiple versions of books that are downloaded and I thought I could just delete them from the folders, but that has only caused broken links. 

Thanks.

**Comment by philborman** [comment]
Thraxis bundles lazylibrarian into a docker and adds calibre to it. There are no changes made to lazylibrarian in the process, so there is no responsibility for lazylibrarian issues, which is probably why you don't get a response.  I think the build process is automated so maybe your issues are not even read?

I presume by multiple versions you mean lazylibrarian downloads multiple formats, epub/mobi/pdf or whatever. There is often nothing from the provider to tell us what formats are included in the download, we only get a title (we prefer titles that do tell us the format) and some downloads include multiple formats in the one download. If you delete the format we are linked to in the database (ie you delete the .mobi and there is an .epub in the same directory) then a libraryscan of the author (or the whole db) will fix the broken link by linking to the format that's still there. We link to the "preferred" format if there is more than one in the download, "preferred" being the format on the left of the formats list, so if your preferred list is "epub,mobi,pdf" and there is only a mobi we link to that. If there are mobi and epub we link to the epub. Hope that makes sense!

**Comment by mccorkled** [comment]
The problem is that once Calibre imports the book, there's no way to remove the wrong one.

**Comment by philborman** [comment]
Maybe you can use the "Only import one format of an ebook if multiple formats downloaded"  switch in lazylibrarian config.  That will import the first format it finds and ignore the rest.

**Comment by mccorkled** [comment]
The problem is that Calibre has already imported the books and now multiple formats exist. Another problem I am having is that Calibra is missing some covers. Since this is built into LL, I cannot add covers or even scan and download missing covers.

**Comment by philborman** [comment]
You should be able to remove the unwanted formats in calibre, and use the calibre metadata editor to grab missing covers. LazyLibrarian has a switch in config/processing to say whether to tell calibre about  our cover and opf.  If you remove a format in calibre that lazylibrarian has linked to, a lazylibrarian libraryscan of the author will correct the link by linking to one of the remaining formats

**Comment by mccorkled** [comment]
So I should install Calibre?

**Comment by philborman** [comment]
Sorry, I dont understand. If you dont have calibre installed then why are you using calibredb to import the books?

**Comment by mccorkled** [comment]
I am using calibre-web which reads a calibre database and has a very nice user interface I can access on all my devices.
![1](https://user-images.githubusercontent.com/13697804/38163936-4afc94b8-34ca-11e8-8a9b-0a540e76ac0f.png)

You can see here that there is a text version of this book but I deleted it from the actual library. Calibre didn't update it though.

![2](https://user-images.githubusercontent.com/13697804/38163945-62fc5f94-34ca-11e8-8e5c-52d2cb6a5791.png)

**Comment by philborman** [comment]
calibre-web says it has ...
Support for editing eBook metadata and deleting eBooks from Calibre library
Never used it though, so don't know how. Hopefully the metadata editing includes adding covers?

**Comment by mccorkled** [comment]
Thank you. I will contact the devs at calibre-web
