### ISSUE TITLE
Force post processing magazines

### ISSUE THREAD

**Issue by dazedyep** [DobyTang/LazyLibrarian#1283]
To help with identifying and fixing issues, please include as much information as possible, including:
Current Version: 4033963e370b5d42523731b9d7ea8d9fb3ffd30b
Operating system used :Synology
Interface in use: bookstrap
Source of your LazyLibrarian installation: git

Hi
I have downloaded magazines but they where not imported into LL (probably due to configuration error in LL on my side). When I try to "force post processing" it still won't import the magazines - as seen in the debug log below. LL finds the files but since they are not snatched LL ignores them as far as I can see. 
How can I mark the files as snatched or get LL to import them?

From Debug log:
2018-03-28 16:04:22 | INFO | POSTPROCESS | postprocess.py | processDir | 837 | Nothing marked as snatched. Stopping postprocessor.
2018-03-28 16:04:22 | DEBUG | POSTPROCESS | postprocess.py | processDir | 356 | Found 18 files in /volume1/downloads/magz/
2018-03-28 16:04:21 | DEBUG | POSTPROCESS | postprocess.py | processDir | 355 | Found 0 files marked "Snatched"

**Comment by philborman** [comment]
Magazines aren't force processed unless snatched. We can do that with eBooks as they have a unique ID which we can look for, magazines don't.

Best solution is to manually move the magazines into the right magazine folders so lazylibrarian can find them and then run libraryscan on the magazines.

**Comment by dazedyep** [comment]
ok, thanks for the reply.
