### ISSUE TITLE
Feature Request: Incorporate ISSUU search and downloads

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1285]
Feature Request: Incorporate ISSUU search and downloads.

This may be fun and tricky to implement. Issuu has their own API to search the magazines / publications.
https://developer.issuu.com/

There are also a ton of clever people that turn any ISSUU url which is a magazine / publication, into a downloadable PDF file. Here is one example site that does this.
https://issuudownload.net/

**Comment by philborman** [comment]
Interesting, maybe once the workload slows down a bit...

**Comment by MrMxyzptlk** [comment]
Yes, not a high priority.

**Comment by alagave** [comment]
This sounds very interesting. There are folks out there still digitizing magazines from library collections and posting digital copies of magazine collections. Some of these are decades old.

**Comment by philborman** [comment]
Development has moved to [GitLab](https://lazylibrarian.gitlab.io/)
All open issues have been moved over to [LazyLibrarian Issues](https://gitlab.com/LazyLibrarian/LazyLibrarian/issues)
Please open any new issues or comments on the new repo as the old one is no longer maintained, thanks
