### ISSUE TITLE
"Change Selected Books" action in Manage resets books/audiobooks filter

### ISSUE THREAD

**Issue by ChrisWeiss** [DobyTang/LazyLibrarian#1287]
In the Manage view, if I select Audiobook as the media type (upper right corner). Doing a "Change Selected Books" action (drop-down at the bottom of the page) resets the media filter back to eBook. Other page refresh activities seem to maintain the media filter state.

Interface: Bookstrap/Slate
Platform: Docker container linuxserver/lazylibrarian
Version: Repo: https://github.com/dobytang/lazylibrarian : Branch: master : Updated: Thu Mar 22 23:10:40 2018
Current Version: 4033963e370b5d42523731b9d7ea8d9fb3ffd30b : Latest Version: 4033963e370b5d42523731b9d7ea8d9fb3ffd30b

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report.

**Comment by philborman** [comment]
Seems we are not saving enough info to restore the setting. Audiobook is a new addition to the manage tab. I will fix this in the next release. Thanks for the bug report.
