### ISSUE TITLE
Feature: Edit format of Date string in Magazine Filename Pattern

### ISSUE THREAD

**Issue by ChrisWeiss** [DobyTang/LazyLibrarian#1289]
It'd be handy if it were possible to edit the date format available in the Magazine Filename Pattern. Or at least put the year first to help in sorting.

**Comment by philborman** [comment]
We already do that, I think. $IssueDate is yyyy-mm-dd. Issue numbers have leading zeros added so should sort correctly too.

**Comment by ChrisWeiss** [comment]
I'm not seeing that in my build.
Example folder/file:
\Magazine.Title.TruePDF-April.2018\
      \Magazine.Title.TruePDF-April.2017.pdf
      \Magazine.Title.TruePDF-April.2017.nzb


My Magazine settings are:
Magazine Foldername Pattern: /books/Calibre_Periodicals/$Title/
Magazine Filename Pattern: $Title - $IssueDate
Magazines Inside Book Folder: [unchecked]
Quick Open Single Issue of Magazines: [checked]

Interface: Bookstrap/Slate
Platform: Docker container linuxserver/lazylibrarian
Version: Repo: https://github.com/dobytang/lazylibrarian : Branch: master : Updated: Thu Mar 22 23:10:40 2018
Current Version: 4033963 : Latest Version: 4033963

**Comment by philborman** [comment]
Looks like your IssueDate is not being picked up correctly for that magazine, should have been converted from April.2017  to  2017-04-01. Also normally the TruePDF part would be stripped out. The $Title part would normally just be title (what you searched for when you added it) and I doubt you specified you wanted TruePDF, though it's possible. Looks like the whole rename code is failing here. Is it all magazine titles, or just some?

A few questions...
1. Was the magazine imported by lazylibrarian, or was it downloaded separately (we don't rename existing magazines, though we do for books, so it could be added)
2. How long ago was the magazine downloaded (in case it's not a problem with current code)
3. If the magazine is downloaded by lazylibrarian, the postprocessor in debug mode will show which "regex" it date-matched against. 'Issue %s (regex %s) for %s ' or zero if it failed to parse a date.
4. When you go to the magazine page for each title, the "Issue" column should contain dates in yyyy-mm-dd format, does yours?   For magazines with issue numbers and no date it should be a 4 digit number with leading zeros, eg 0063
