### ISSUE TITLE
NZBGet working?

### ISSUE THREAD

**Issue by blindpet** [DobyTang/LazyLibrarian#129]
I have NZBGet checked and put in all the credentials and port, nzbs are found but not sent to NZBGet
Is it just not supported yet?

2015-05-19 21:06:42	INFO	No download method is set, use SABnzbd or blackhole

When I switch to blackhole I still get errors and the nzb isn't in the blackhole folder

2015-05-19 21:06:42	INFO	There is nothing to search for. Mark some magazines as active.
2015-05-19 21:06:42	INFO	No download method is set, use SABnzbd or blackhole
2015-05-19 21:06:42	INFO	Found NZB: Shannyn Schroeder - [Hot & Nerdy 02] - Her Perfect Game (epub)
2015-05-19 21:06:41	INFO	Search for Wanted items complete

**Comment by daktak** [comment]
#130
that INFO line "No download method is set, use SABnzbd or blackhole" was triggered erroneously.
Is there any more info after the Search for Wanted items complete?

**Comment by daktak** [comment]
Was tested against version 10. not having luck with version 14 at the moment ;-(

**Comment by blindpet** [comment]
Thanks, maybe Mylar can help out, I believe it is working with nzbget 14 when I tested it
https://github.com/evilhero/mylar

**Comment by sukhysall** [comment]
Guys. 

I've got a Synology NAS running nzbget v16.4. In the nzbget "categories" I have a category called "books" and the download folder for this category is defaulted to whatever i set it to in the paths config.

Now on LL I have the following configured for nzbget (screenshot)

![21](https://cloud.githubusercontent.com/assets/5501195/12496602/aec37ca8-c08e-11e5-9472-b949085ad99d.jpg)

As you can see the dowload directory is set to match the same line in the nzbget "paths" config section. 

Until recently I used the blackhole folder myself. Like an idiot, I forgot to add the nzbget port to the end of the nzb ip address in LL config.

I hope this helps. Please let me know if it does.

Thanks

**Comment by danfozzy** [comment]
@sukhysall apologies for the off topic but how did you get this fork installed on your synology?

**Comment by sukhysall** [comment]
nzbget? - Got that through the Synocommunity package repository
link: http://packages.synocommunity.com/

Just add that to your Synology Package Center and let it refresh and you'll have version 16 ready for download.

**Comment by sukhysall** [comment]
Unless you mean LL in which case I used the LL package from the MArtin Devries repository
link: http://packages.mdevries.org/

Again, add that and let it refresh. You're 3rd party packages will show you 2 sets of LL. You want the DobyTang version of course :)

**Comment by danfozzy** [comment]
Sorry I meant LL many thanks got it working :)

**Comment by sukhysall** [comment]
@danfozzy is this still an issue for you?
