### ISSUE TITLE
LibrarySync error:  Unable to create directory %s: %s' % (dest_path, why)) UnicodeEncodeError: 'ascii' codec can't encode character u'\u014d' in position 81: ordinal not in range(128)

### ISSUE THREAD

**Issue by Gamethrall** [DobyTang/LazyLibrarian#1296]
LazyLibrarian version number: fef464b8d67c09575d01c0d9b5704a7310b5a099 
Operating system used: Windows 10
Interface in use: default
Which API: Goodreads
Source of your LazyLibrarian installation: zip
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1884506/debug.zip)

**Comment by philborman** [comment]
Interesting one this...
The original filename had Marie Kondo without the accent on the 'o'
LazyLibrarian is trying to rename it to Marie Kondō  as we got the accented name from goodreads or the book metadata, could have been either. Normally we try to stick to goodreads preferred name so we don't end up with an authors books spread over several different spellings of their name.
If I remember right there is a problem with the accented ō in windows filenames as the character is valid utf-8 but not valid windows cp1252
Not sure what's best to do. We could strip all accents from filenames, but it's a bit draconian and we're not in the 1980s. Lots of authors with "latin" accents in their names are fine, and most Scandinavian accents too, eg Jo Nesbø, Henri Charrière, Zoë Ferraris

Are you up for a bit of editing to see what might work?

**Comment by Gamethrall** [comment]
I'm willing to edit and try things if it will help the project.

What needs editing and where?

**Comment by philborman** [comment]
That's great, thanks.
The line throwing the error is in bookwork.py, line 316
`shutil.move(r, dest_path)`
Just above that can you add 
`logger.debug(" %s, %s" % (type(r), type(dest_path)))`

Python is fussy about whitespace, the lines need to line up vertically with the 'l' of logger directly above the 's' of shutil with spaces used to pad them, not tabs. That should show us what types we're trying to move, and I can try a solution depending on the result. Keep a copy of the unmodified file so you can replace it after testing or lazylibrarian will not upgrade properly because of local changes.

**Comment by Gamethrall** [comment]
Here you go. I hope this helps.
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1887520/debug.zip)

**Comment by philborman** [comment]
Yes that's a big help thanks. Both directory names are unicode so the issue does seem to be the file system. I will have to remove the accent to get it working unless I can think of a better way.

**Comment by philborman** [comment]
I had a scout around on stackoverflow and the consensus seems to be "try it and handle the error", so I have added some code to try and catch the error, remove the accents and retry without them. It's not ideal but should hopefully fix the problem. New version should be out in a few hours, would be grateful if you could try it with Marie Kondō and report back.

**Comment by Gamethrall** [comment]
I've pulled the newest version.  Now, when I update the library, it only rescans my existing files and does not add anything from the Download Directory or the Alternate Import/Export Folder I have specified. Is there another way to force it to look at/grab files from either/both of those directories?
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1900682/debug.zip)

**Comment by philborman** [comment]
They are separate processes run for different reasons
Libraryscan just scans the main library folder, useful when you first set up, if sharing a folder with calibre or other book software, or for rebuilding your database

The postprocessor is used to grab files from your Download Directory. Runs manually or on a schedule, moves downloaded books into your main library folder (only looks for files it is expecting though, ie files lazylibrarian downloaded)

You can import books from the Alternate Import directory using buttons on the "Manage" page. Useful for manually adding books to your library that were not downloaded by lazylibrarian. Two options, Import or Include. Import moves the books into main library folder like the postprocessor does, Include just creates links to the files without moving them

**Comment by Gamethrall** [comment]
Thanks.

It's not finding metadata for the Marie Kondo book. I'll look for an opf file.
