### ISSUE TITLE
Traceback in dbupgrade.log / upgrade database every restart

### ISSUE THREAD

**Issue by barbequesauce** [DobyTang/LazyLibrarian#1301]
Updated last night and left the db upgrade running since it said it needed 66 minutes. This afternoon I had to restart the machine and LL was doing the db upgrade again.

Dbupgrade.log ended with this traceback....

```
Sat Apr  7 20:33:55 2018 v0: Updating database to version 30, current version is 28
Sat Apr  7 20:33:55 2018 v29: Adding WorkID to member and books tables
Sat Apr  7 20:33:58 2018 v29: Upgrading 50 authors, 2570 books
Sun Apr  8 03:31:34 2018: Unhandled exception in database upgrade: Traceback (most recent call last):
  File "/opt/LazyLibrarian/lazylibrarian/dbupgrade.py", line 340, in dbupgrade
    upgrade_function(myDB, upgradelog)
  File "/opt/LazyLibrarian/lazylibrarian/dbupgrade.py", line 1021, in db_v29
    entries_done += int(expected_books)  # may have extra books now, don't overcount
TypeError: int() argument must be a string or a number, not 'NoneType'
```

Current commit, raspbian Jessie, bootstrap, goodreads, git install...

**Comment by philborman** [comment]
Silly bug in the database upgrade code, fixed now, sorry about that.
You can bypass the upgrade repeat if you want to, but next time shouldn't take as long as most of the data is Cached.

**Comment by wizzy99** [comment]
I'm running LL via the linuxserver docker.  My upgrade has been running for 48+ hours, and based on the above, I did a git pull and restarted; I now have a 42 hour estimate to completion.  dbupgrade.log is 0 bytes, and my LL log continues to have a bunch of "09-Apr-2018 08:02:58 - WARNING :: DB_UPGRADE : gr.py:get_author_books:424 : No isbn found for #######" warnings (same behavior as before the recent pull).

**Comment by philborman** [comment]
42 hours is an extraordinarily long time. The op quoted 66 minutes, mine takes 2 hours, or 4 with an empty cache. "No isbn found" is not fatal, just a warning, but wouldn't expect too many of them. The goodreads pages seem to have about 10% without an isbn, but we use a couple of other sources too, so should fill in most of them.  Can you post a log excerpt with debug on showing the problem, might be something odd going on.

**Comment by wizzy99** [comment]
I'll need to set the log level manually as LL only displays the upgrade-in-progress page.  What level should I set in config.ini?
Current settings:
logdir = /config/Logs
loglevel = 0
loglimit = 500
logfiles = 10

**Comment by philborman** [comment]
loglevel = 2

let it run for at least one complete author, then abort. The start of the log will contain passwords, so you will need to hand edit them out, or just post the section showing the upgrade (after the config is read) as that part won't have passwords in.  Either zip and post it here, or email to me at phil.borman@gmail.com

Debug level 2 is useful as it will show any communication errors talking to the information sources.

**Comment by wizzy99** [comment]
[hold.zip](https://github.com/DobyTang/LazyLibrarian/files/1890792/hold.zip)
Here you go.

**Comment by philborman** [comment]
Ok, thanks for that.  Nothing leaping out at me, sadly.
Tom Clancy started at 12:19:12 and ended at 12:20:46, 94 seconds for 266 results. Not too slow.
Includes time of 50 isbn fetched in 34 seconds, these are ones that goodreads didn't have. Seems quite a lot missing on goodreads, but might be right.

Audrey Faye, 12:20:47 to 12:21:18, 31 seconds for 23 results, quite a lot slower but not many rejects. 
23 isbn in 16 seconds

Sherrilyn Kenyon, 12:21:19 to 12:22:53, 94 seconds for 175 results, 49 isbn in 34 seconds

so 3 authors completed in 219 seconds, 70 seconds per author. If lazylibrarian is estimating 42 hours that would mean over 2100 authors?  Seems unlikely?  Maybe the estimate is wrong?

Also your log shows lots of cache expiring messages, maybe increase your cache expiry time so we don't need to fetch info so often

**Comment by wizzy99** [comment]
I do have a bunch of authors, some are valid and some were added by "accident" over time via various means.  I guess I'll just let it run to completion at this point, thanks for checking.  I'll investigate the cache setting. it's set to 7 now.
cache_age = 7

**Comment by philborman** [comment]
The idea behind the cache_age setting is we try to refresh all author details and pick up any new books they have written within that time frame, so unless your authors are very prolific writers you can safely bump that up to 30 for checking each author around once a month, or even longer.

**Comment by PC001** [comment]
Hi,
I'm running the latest commit of LL and still getting the traceback error...
```
10-Apr-2018 23:44:58 - ERROR   :: DB_UPGRADE : dbupgrade.py:dbupgrade:373 : Unhandled exception in database upgrade: Traceback (most recent call last):
  File "/opt/LazyLibrarian/lazylibrarian/dbupgrade.py", line 340, in dbupgrade
    upgrade_function(myDB, upgradelog)
  File "/opt/LazyLibrarian/lazylibrarian/dbupgrade.py", line 1021, in db_v29
    entries_done += int(expected_books)  # may have extra books now, don't overcount
TypeError: int() argument must be a string or a number, not 'NoneType'
```
Is there something I need to do to get it to work?
It fails at a different point in the upgrade every time, so should I just keep on restarting LL?

Thanks.

**Comment by philborman** [comment]
Looks like you have an author in the database with no books and we're not handling it properly. We seem to be getting "None", which makes sense, but we're expecting the number zero. Easy enough to fix, will push an update in the next few minutes.

**Comment by PC001** [comment]
Thanks. Updated and checking now.

**Comment by PC001** [comment]
Completed successfully. Thanks again.

**Comment by wizzy99** [comment]
Upgrade finished after a few days, but with an error.  (don't ask me why I have so many authors, I need to look into that)

Mon Apr  9 12:57:37 2018 v0: Updating database to version 30, current version is
 28
Mon Apr  9 12:57:37 2018 v29: Upgrading 3922 authors, 96200 books
Thu Apr 12 15:19:18 2018: Unhandled exception in database upgrade: Traceback (mo
st recent call last):
  File "/app/lazylibrarian/lazylibrarian/dbupgrade.py", line 340, in dbupgrade
    upgrade_function(myDB, upgradelog)
  File "/app/lazylibrarian/lazylibrarian/dbupgrade.py", line 1021, in db_v29
    entries_done += int(expected_books)  # may have extra books now, don't overc
ount
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by philborman** [comment]
That bug was fixed a few days ago, it's only cosmetic, affecting a log message, but you might need to manually alter the database version number so lazylibrarian doesnt try the upgrade again.
From a terminal in your database directory
sqlite3 lazylibrarian.db
pragma user_version=30
