### ISSUE TITLE
Suggestion: Move lastest version check to *after* app has fully started?

### ISSUE THREAD

**Issue by claym** [DobyTang/LazyLibrarian#1304]
So I came across a weird thing - 

I had an issue where Lazy Librarian was unable to start due to not fully exiting, and my docker (i'm assuming this is the mechanism, I don't have a standalone install to compare it to) keeps restarting it.

Ok, that's fine.

However, there's a hit against api.github.com during the startup process, but before it gets to the "oh no, we failed" part. And if the app gets restarted every 20 seconds or whatever, the app pings github every 20 seconds.

Github limits unauthenticated hits to it's api to 60 / hour. So you eat through that really quick if there's an issue on startup.

I know it's a weird edge case, but hey, thought I'd bring it up. Also happens on Headphones, and maybe Mylar as well? Haven't confirmed that one.

**Comment by philborman** [comment]
Good idea. Was done the current way so that you don't start the webserver and then immediately shut it down to update, but easy enough to swap it around.

**Comment by philborman** [comment]
Ok, added that to next version, out later today

**Comment by philborman** [comment]
Hmm, seems moving the webserver has caused issues with daemonize and/or systemd so have to revert that change for now while I figure out why.
