### ISSUE TITLE
404 for Library Genesis treated as successful download

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1307]
Repo: https://github.com/dobytang/lazylibrarian : Branch: master : Updated: Tue Apr 10 11:15:03 2018
Current Version: d3ce543c6b781d5c11f814511dd3e15ab859b0c3 : Latest Version: d3ce543c6b781d5c11f814511dd3e15ab859b0c3

MacOS 10.13.4

I now have log level set to 2 but it was at 1 when this ran:

grep -i "Men in Black" ~/src/LazyLibrarian-master/Logs/lazylibrarian.log*
/Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log:11-Apr-2018 10:17:55 - INFO    :: POSTPROCESS : postprocess.py:processAutoAdd:1513 : Auto Add completed for [/Users/kids/Calibre/Steve Perry/Men In Black]
/Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log:11-Apr-2018 10:17:56 - INFO    :: POSTPROCESS : postprocess.py:import_book:1133 : Successfully processed: Men In Black - Steve Perry

I re-ran the search but it didn't match this time.   grep results attached (500 lines).

This is the file that was downloaded:

ls -ald Steve\ Perry\ Men\ in\ Black.epub 
-rw-r--r--  1 kids  staff  220 Apr 11 00:50 Steve Perry Men in Black.epub

cat Steve\ Perry\ Men\ in\ Black.epub 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /foreignfiction/ads.php was not found on this server.</p>
</body></html>

Same was true for another book:

ls -ald Hunting\ Kat\ -\ Kelley\ Armstrong.epub 
-rw-r--r--  1 kids  staff  220 Apr 11 04:15 Hunting Kat - Kelley Armstrong.epub
macmedia:~ kids$ cat Hunting\ Kat\ -\ Kelley\ Armstrong.epub 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /foreignfiction/ads.php was not found on this server.</p>
</body></html>

[mib.txt](https://github.com/DobyTang/LazyLibrarian/files/1899866/mib.txt)

**Comment by philborman** [comment]
Interesting, your log shows Found 0 results from libgen.io for Steve Perry Men In Black
so shouldn't try to download anything?
LibGen do keep changing their html pages though, so the parser quite probably needs tweaking again. I will take a look. There is some code in the parser to trap 404 errors, but we don't seem to be hitting it (there should be a message in the log)
