### ISSUE TITLE
Cant sync with calibre-web

### ISSUE THREAD

**Issue by slimshizn** [DobyTang/LazyLibrarian#1309]
To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Using Calibre-Web from technosoft2000/calibre-web:latest. I add /opt/calibre/calibredb to the calibredb import program and testing it works but cant find my database (failed or database is empty). Adding https://192.168.0.50:8083, username and pw it is not syncing with calibre web. I had it working before but after an update now there have been issues that I can't figure out. Logs aren't showing any errors related to this so I assume its a directory error. 

LazyLib
Host/volume | Path in container
-- | --
/share/CACHEDEV1_DATA/appdata/LazyLib | /config
/share/CACHEDEV1_DATA/Books/Audiobooks | /audiobooks
/share/CACHEDEV1_DATA/Download/LAZYLIB DL | /downloads
/share/CACHEDEV1_DATA/Books | /books
/share/CACHEDEV1_DATA/Books/_Magazines | /magazines

Calibre-web
Host/volume | Path in container
-- | --
/share/CACHEDEV1_DATA/Books | /books
/share/CACHEDEV1_DATA/appdata/Calibre Web | /config

Anything else just let me know.

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report.

**Comment by philborman** [comment]
What do you get if you try the "test calibredb" button in the lazylibrarian config page. Try with debug log on, you should see what commands are being sent and the responses.

**Comment by slimshizn** [comment]
2018-04-11 14:50:00 | DEBUG | WEBSERVER | calibre.py | calibredb | 424 | [u'/opt/calibre/calibredb', '--version', '--username', u'admin', '--password', u'password']

2018-04-11 14:50:14 | DEBUG | WEBSERVER | calibre.py | calibredb | 439 | calibredb returned 0: res[calibredb (calibre 3.21) ] err[]

2018-04-11 14:50:14 | DEBUG | WEBSERVER | calibre.py | calibredb | 424 | [u'/opt/calibre/calibredb', 'list_categories', '--username', u'admin', '--password', u'password', '-i', '--with-library', u'http://192.168.0.50:8083']

**Comment by philborman** [comment]
Ok so we talked to calibredb, got it's version number
Then we asked it for a list of categories and got no reply. 
Seems calibredb is not talking to the server, or the server is not running 
Check your calibre server settings including its startup options, see the calibre section in the lazylibrarian wiki config page

**Comment by philborman** [comment]
I think that's it.
You have local write enabled, but you are talking to it from lazylibrarian using  '--with-library', 'http://192.168.0.50:8083'   which is not a local address, should be 127.0.0.1:8083
