### ISSUE TITLE
Suggest using systemd instead in init.d 

### ISSUE THREAD

**Issue by MatthewYax** [DobyTang/LazyLibrarian#1311]
My systemd script that is working now... although when updating, app will not restart. 

[Unit]
Description=Lazy Librian
After=network.target

[Service]
ExecStart=/usr/bin/python /opt/lazylibrarian/LazyLibrarian.py
Type=simple
User=lazyl
Group=users
Restart=on-failure

[Install]

**Comment by philborman** [comment]
# lazylibrarian.service to run as $USER with config in $HOME/.lazylibrarian
[Unit]
SourcePath=/etc/init.d/lazylibrarian
Description=LSB: starts instance of LazyLibrarian
After=all.target

[Service]
Type=forking
Restart=no
TimeoutSec=5min
IgnoreSIGPIPE=no
KillMode=process
GuessMainPID=no
RemainAfterExit=yes
ExecStart=/etc/init.d/lazylibrarian start
ExecStop=/etc/init.d/lazylibrarian stop

[Install]
WantedBy=multi-user.target

**Comment by philborman** [comment]
The above file lets you use the init.d scripts from systemd. Not sure where this script came from originally, but it seems a good compromise

**Comment by wizzy99** [comment]
I'm running a docker instance now, but I'm pretty sure this worked when I was running it on the native host.

[Unit]
Description=LazyLibrarian application instance
After=network.target

[Service]
ExecStart=/usr/bin/python /home/<user>/LazyLibrarian/LazyLibrarian.py -d
GuessMainPID=no
Type=forking
User=<user>
Group=<group>

[Install]
WantedBy=multi-user.target

**Comment by philborman** [comment]
If you are using systemd to run lazylibrarian, don't include - d in the ExecStart line
Also @MatthewYax would be best to specify a home dir in ExecStart to keep your config and database outside of the program folder for easier reinstallation

**Comment by philborman** [comment]
The -d error is fixed now, but still prefer to keep data files outside of the program directory
