### ISSUE TITLE
Logs rotating too fast

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1312]
Repo: https://github.com/dobytang/lazylibrarian : Branch: master : Updated: Wed Apr 11 11:15:26 2018
Current Version: 0a51cb90f788fba0364f31b3f88d850ef7e6b123 : Latest Version: 0a51cb90f788fba0364f31b3f88d850ef7e6b123

MacOS 10.13.4

I've got log level set to 2 and it's spitting out information.   I had another 404 page downloaded from search:

cat John\ W\ \ Campbell\ Jr\ \ -\ The\ Space\ Opera\ Megapack\ \(R\)\ LL.\(22220011\)/*
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /foreignfiction/ads.php was not found on this server.</p>
</body></html>

but that happened last night at 6:41 when LazyLibrarian automatically downloaded it.   

ls -al John\ W\ \ Campbell\ Jr\ \ -\ The\ Space\ Opera\ Megapack\ \(R\)\ LL.\(22220011\)/
total 16
drwxr-xr-x   3 kids  staff  102 Apr 11 18:41 .
drwxr-xr-x  10 kids  staff  340 Apr 12 10:50 ..
-rw-r--r--   1 kids  staff  220 Apr 11 18:41 Campbell John WLake Jay The Space Opera Megapack.epub

-rw-r--r--  1 kids  staff   53314 Apr 12 10:51 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log
-rw-r--r--  1 kids  staff  204714 Apr 12 10:50 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.1
-rw-r--r--  1 kids  staff  204680 Apr 12 10:41 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.10
-rw-r--r--  1 kids  staff  204796 Apr 12 10:47 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.2
-rw-r--r--  1 kids  staff  204686 Apr 12 10:43 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.3
-rw-r--r--  1 kids  staff  204657 Apr 12 10:41 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.4
-rw-r--r--  1 kids  staff  204663 Apr 12 10:41 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.5
-rw-r--r--  1 kids  staff  204688 Apr 12 10:41 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.6
-rw-r--r--  1 kids  staff  204776 Apr 12 10:41 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.7
-rw-r--r--  1 kids  staff  204662 Apr 12 10:41 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.8

tail -10 ~/src/LazyLibrarian-master/Logs/lazylibrarian.log*10
12-Apr-2018 10:41:24 - DEBUG   :: SEARCHALLRSS : resultlist.py:findBestResult:100 : RSS author/book Match: 24/39 Abelssoft WashAndGo Build Pre Cracked at https://worldwidetorrents.me/
12-Apr-2018 10:41:24 - DEBUG   :: SEARCHALLRSS : resultlist.py:findBestResult:100 : RSS author/book Match: 18/36 WinZip Registry Optimizer Crack at https://worldwidetorrents.me/
12-Apr-2018 10:41:24 - DEBUG   :: SEARCHALLRSS : resultlist.py:findBestResult:100 : RSS author/book Match: 26/31 Young And Tight DiSC XXX DVDRip x WOPNC at https://worldwidetorrents.me/
12-Apr-2018 10:41:24 - DEBUG   :: SEARCHALLRSS : resultlist.py:findBestResult:132 : Rejecting Young And Tight DiSC XXX DVDRip x WOPNC, too large
12-Apr-2018 10:41:24 - DEBUG   :: SEARCHALLRSS : resultlist.py:findBestResult:100 : RSS author/book Match: 26/31 Young And Tight DiSC XXX DVDRip x WOPNC at https://worldwidetorrents.me/
12-Apr-2018 10:41:24 - DEBUG   :: SEARCHALLRSS : resultlist.py:findBestResult:132 : Rejecting Young And Tight DiSC XXX DVDRip x WOPNC, too large
12-Apr-2018 10:41:24 - DEBUG   :: SEARCHALLRSS : resultlist.py:findBestResult:100 : RSS author/book Match: 12/27 WinRAR Beta bit and bit at https://worldwidetorrents.me/
12-Apr-2018 10:41:24 - DEBUG   :: SEARCHALLRSS : resultlist.py:findBestResult:100 : RSS author/book Match: 18/31 Big Beach Builds SE Blown Out Beach House HDTV x CRiMSONNC at https://worldwidetorrents.me/
12-Apr-2018 10:41:24 - DEBUG   :: SEARCHALLRSS : resultlist.py:findBestResult:132 : Rejecting Big Beach Builds SE Blown Out Beach House HDTV x CRiMSONNC, too large
12-Apr-2018 10:41:24 - DEBUG   :: SEARCHALLRSS : resultlist.py:findBestResult:100 : RSS author/book Match: 18/33 Big Beach Builds SE Blown Out Beach House p HDTV x CRiMSONNC at https://worldwidetorrents.me/

I don't have a great suggestion on what to do.   Obviously you're concerned about the log files getting too big and that's valid.     Maybe some sort of setting to keep files for 24 hours, even if they're large?

**Comment by philborman** [comment]
You can increase the number of log files and the max size of the files in lazylibrarian config. Hopefully that way we can get a capture of what's going on. It's kept fairly small by default for systems like raspberry pi logging to sd cards

**Comment by dkids** [comment]
Thanks very much for the response.   I don't see a way to increase the number of log files.   On Config, Interface I changed the value from 500 to 50000.   It didn't seem to make a difference, so I restarted.   Still doesn't seem to make a difference.

Log Limit: 
[ 50000 ]
Size of on-screen log, smaller is faster and uses less memory 

Because it's 500, I assumed it was lines per file but that doesn't seem to be quite right.   It would be nice to know the unit of measurement.   I do get that huge files could be a problem but I'm using grep on the command line.

There is Config, Logs.   Would it make sense to gather log-related stuff (like size and number of log files) there?   


l  ~/src/LazyLibrarian-master/Logs/lazylibrarian.log*
-rw-r--r--  1 kids  staff   96382 Apr 12 12:37 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log
-rw-r--r--  1 kids  staff  204550 Apr 12 12:20 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.1
-rw-r--r--  1 kids  staff  204706 Apr 12 11:40 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.10
-rw-r--r--  1 kids  staff  204428 Apr 12 12:19 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.2
-rw-r--r--  1 kids  staff  204732 Apr 12 12:06 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.3
-rw-r--r--  1 kids  staff  204739 Apr 12 11:50 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.4
-rw-r--r--  1 kids  staff  204727 Apr 12 11:46 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.5
-rw-r--r--  1 kids  staff  204793 Apr 12 11:40 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.6
-rw-r--r--  1 kids  staff  204630 Apr 12 11:40 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.7
-rw-r--r--  1 kids  staff  204775 Apr 12 11:40 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.8
-rw-r--r--  1 kids  staff  204766 Apr 12 11:40 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.9

$ wc ~/src/LazyLibrarian-master/Logs/lazylibrarian.log*
     384    9038   96382 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log
     651   15677  204550 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.1
    1234   26563  204706 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.10
    1099   19837  204428 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.2
     674   15408  204732 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.3
    1034   21330  204739 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.4
    1160   24661  204727 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.5
    1237   26514  204793 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.6
    1236   26487  204630 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.7
    1240   26521  204775 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.8
    1236   26525  204766 /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.9
   11185  238561 2143228 total

Thanks again.

**Comment by philborman** [comment]
Ah, in the config page the only changeable settings are the log level and the number of lines for the on-screen log. The logfile settings are only available in the config file itself. Not sure why they are not all alterable in config except that it's not something you often need to do. Could easily be moved though.  For now you can edit the lines in config.ini (while lazylibrarian is not running)
logfiles= how many files
logsize is max size per file

**Comment by philborman** [comment]
logfiles and logsize will be configurable in the next version
