### ISSUE TITLE
LazyLibrarian won't shutdown/restart

### ISSUE THREAD

**Issue by bjfisher** [DobyTang/LazyLibrarian#1315]
Running Ubuntu 16.04, using the latest Git version 738034adca7e591aca0a20e2e9c078ec0135fdcd, bookstrap interface.

So I'm a long way from an expert on how systemd or ubuntu in general work, but I'm having trouble getting LL to shutdown. 

Using the Shutdown button in the config menu takes me to the shutdown page and initiates a countdown, but at the end of that the page refreshes and LL is running as normal.

Taking cue from https://github.com/DobyTang/LazyLibrarian/blob/master/init/INSTALL.txt, running `sudo systemctl stop lazylibrarian` does nothing. I had to kill the process in order to actually stop it. Which lead to the further problem of being unable to start it again. A reboot of the server got it running again.

So I thought this might just be a configuration issue, but the fact that the shutdown button doesn't work either might mean its more than that.

**Comment by philborman** [comment]
There is a conflict between systemd and the lazylibrarian -d option which stops the shutdown/restart buttons working and also stops you listing/restarting lazylibrarian background tasks. Havent been able to find out why yet. I think it used to work, but certainly doesn't now.

For systemd run lazylibrarian without -d  until it's fixed.
If you are using the supplied scripts, /etc/init.d/lazylibrarian 
line 72 DAEMON_OPTS="LazyLibrarian.py -d --nolaunch"
remove the -d
