### ISSUE TITLE
eBook Scan stopped working with Calibre

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1318]
Repo: https://github.com/dobytang/lazylibrarian : Branch: master : Updated: Sat Apr 14 14:26:09 2018
Current Version: 1b172413b6b0b02a68822167d878f2b4de794d82 : Latest Version: 1b172413b6b0b02a68822167d878f2b4de794d82

MacOS 11.3.4

I manually downloaded a bunch of Ed McBain books and put them into Calibre's AutoAdd directory.  Calibre has added them but LL still shows them as wanted after multiple attempts to eBook Scan.   This has been working fine with other authors.

Apparently LL is not searching for the authors marked as wanted.    

I have log files set to 2MB and 100 log files.   That's just a bit over 24 hours of logs, so I'm going to increase the size to 10MB.

Attached is cat ~/src/LazyLibrarian-master/Logs/lazylibrarian.log.*  | grep McBain | grep Ice |sort 
[ed.txt](https://github.com/DobyTang/LazyLibrarian/files/1913114/ed.txt)

**Comment by dkids** [comment]
Also, I have stopped and re-started both LL and Calibre in an effort to get them to communicate.

It would be nice to have a "test Calibre Content Server" the way that there is for the calibredb program.

**Comment by philborman** [comment]
The calibre test button tests both calibredb and the content server.
It reports calibredb version, then the database read/write tests are from the content server. calibredb talks to the content server and passes us the replies.

Ed McBain books:
If calibre has already imported them via it's auto-add directory it will have moved them into the calibre library folders. Something like Calibre Library/Ed McBain/Book Title (number)/
If you are sharing that same folder structure with lazylibrarian it won't know calibre has added anything unless you run LibraryScan (either full ebook library, or per author) to create/update entries in the lazylibrarian database for the books.  The logfiles you posted don't show a libraryscan, they show searching for the books using torznab, but not finding any.

**Comment by dkids** [comment]
Yeah, the problem is that LL is not searching for "Ice Ed McBain" although it (I think) should.   I included the logs even though they didn't show results.

The behavior I thought I was seeing on previous versions:

   direct download books via web browser
   move books to Calibre's auto-add directory
   after import, run eBook Scan on the author(s) to catch new additions

Parts 1 and 2 are working fine but #3 is not.   

I don't have eBook Library Folder set because LL was writing directly to it.

calibredb was generating error messages.   Huh.   Just tested it to verify but it is not generating error messages now.   I was getting an error message that the library couldn't be read or written to.   I attempted to pass the username and password in as variables but then it didn't work, either.   I didn't report it because I though I was supposed to just use the Calibre Content Server.

The logs show that LL knows about 42 books but Calibre has 65.    

Should I change the eBook Library Folder?   

PS: my ultimate goal is to get out of doing direct downloads.

**Comment by philborman** [comment]
You need the ebook library folder set so that lazylibrarian knows where the books are. If the folder is shared between lazylibrarian and calibre, do not use calibre auto-add, use calibredb with/without the content server.  There are too many options with calibre, it gets quite confusing.  How you do it depends on whether you want separate libraries (folders), whether lazylibrarian and calibre are on the same machine, what major version of calibre you use (2.xx or 3.xx). 

> The behavior I thought I was seeing on previous versions:
> 
> direct download books via web browser
> move books to Calibre's auto-add directory
> after import, run eBook Scan on the author(s) to catch new additions
> 
That will work fine if you have lazylibrarian ebook library folder set to the calibre library folder.
Calibre will auto add them, lazylibrarian isn't involved in that part. eBook Scan will scan the  lazylibrarian ebook library folder and pick up the new books
