### ISSUE TITLE
504 treated as successful download

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1321]
Repo: https://github.com/dobytang/lazylibrarian : Branch: master : Updated: Sun Apr 15 11:31:58 2018
Current Version: cbaa32ba89c8629d84488521eda95553df4f6e8b : Latest Version: cbaa32ba89c8629d84488521eda95553df4f6e8b

Not sure why the error code is not being caught.   It seems like the size (less than 1000 bytes) would be another thing to test for.

cat Ed\ McBain\ -\ Like\ Love\ LL.\(442787\)/Ed\ McBain\ Like\ Love.epub 
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
macmedia:Books kids$ l Ed\ McBain\ -\ Like\ Love\ LL.\(442787\)/
total 16
drwxr-xr-x   3 kids  staff  102 Apr 15 19:55 .
drwxr-xr-x  21 kids  staff  714 Apr 15 19:57 ..
-rw-r--r--   1 kids  staff  176 Apr 15 19:55 Ed McBain Like Love.epub

15-Apr-2018 19:55:07 - INFO    :: SEARCHBOOK : searchbook.py:search_book:289 : TOR Searches for eBook Ed McBain Like Love returned no results.
15-Apr-2018 19:55:13 - DEBUG   :: SEARCHBOOK : directparser.py:GEN:257 : Found Ed McBain Like Love.rar, Size 645120
15-Apr-2018 19:55:14 - DEBUG   :: SEARCHBOOK : directparser.py:GEN:257 : Found Ed McBain Like Love.epub, Size 241664
15-Apr-2018 19:55:14 - DEBUG   :: SEARCHBOOK : directparser.py:GEN:257 : Found Ed McBain Like Love.pdf, Size 30408704
15-Apr-2018 19:55:15 - DEBUG   :: SEARCHBOOK : directparser.py:GEN:269 : Found 3 results from libgen.io for Ed McBain Like Love
15-Apr-2018 19:55:15 - DEBUG   :: SEARCHBOOK : resultlist.py:findBestResult:100 : DIRECT author/book Match: 100/100 Ed McBain Like Love rar at libgen.io/foreignfiction/index.php
15-Apr-2018 19:55:15 - DEBUG   :: SEARCHBOOK : resultlist.py:findBestResult:100 : DIRECT author/book Match: 100/100 Ed McBain Like Love epub at libgen.io/foreignfiction/index.php
15-Apr-2018 19:55:15 - DEBUG   :: SEARCHBOOK : resultlist.py:findBestResult:100 : DIRECT author/book Match: 100/100 Ed McBain Like Love pdf at libgen.io/foreignfiction/index.php
15-Apr-2018 19:55:15 - INFO    :: SEARCHBOOK : resultlist.py:findBestResult:202 : Best match (105%): Ed McBain Like Love epub using book search, libgen.io/foreignfiction/index.php priority 1
15-Apr-2018 19:55:15 - INFO    :: SEARCHBOOK : searchbook.py:search_book:298 : Requesting eBook download: 105% libgen.io/foreignfiction/index.php: Ed McBain Like Love epub
15-Apr-2018 19:55:15 - DEBUG   :: SEARCHBOOK : downloadmethods.py:DirectDownloadMethod:111 : Starting Direct Download for [Ed McBain Like Love epub]
15-Apr-2018 19:55:31 - DEBUG   :: SEARCHBOOK : downloadmethods.py:DirectDownloadMethod:127 : File download got 176 bytes for Ed McBain - Like Love LL.(442787)/Ed McBain Like Love.epub
15-Apr-2018 19:55:31 - DEBUG   :: SEARCHBOOK : downloadmethods.py:DirectDownloadMethod:146 : File Ed McBain - Like Love LL.(442787) has been downloaded from http://libgen.io/foreignfiction/get.php?md5=be2e0c524e712a9b876a2b430663eb51&key=YB2HYRRK0B1KWEIU
15-Apr-2018 19:55:31 - INFO    :: SEARCHBOOK : resultlist.py:downloadResult:261 : Downloading eBook Ed McBain - Like Love LL.(442787) from libgen.io/foreignfiction/index.php

**Comment by philborman** [comment]
We ask for the download and libgen sends us a file, there is no indication from libgen that it's an error page rather than the file we asked for, there doesn't seem to be an error code returned, just the file. I will add some code to check the size as you suggest.
