### ISSUE TITLE
Cannot add audiobooks when eBook already exists

### ISSUE THREAD

**Issue by algarythem** [DobyTang/LazyLibrarian#1322]
I have several audiobooks that I am looking for that for some unknown reason never added, though they are listed under the eBooks section. Within the eBook section, the status can not be removed or deleted. When searching the main page for these books, they cannot be added, as they are already listed in the eBooks. Could a separate button be added for just adding as an audiobook? It is inconvenient that a wanted audiobook has to be added by adding both the eBook and audiobook.

Debug log was created for the actions of trying to change 2 ignored eBooks to a deleted and removed status, of which neither worked properly. Both of these books are still listed as ignored.

LazyLibrarian version number: 1b172413b6b0b02a68822167d878f2b4de794d82
Operating system: Windows Server 2012
Interface: default
api: Goodreads
Source of LazyLibrarian installation: git
Attached the debug log crated from the built-in creator

**Comment by philborman** [comment]
>  Within the eBook section, the status can not be removed or deleted. 

This is working as expected, "removed" sets status to ignored, "deleted" sets status and also deletes the book files. We don't remove the database entry completely, just ignore it. If we remove it completely then the next time you refresh the author it will get put back as we will think it is a new book.

> When searching the main page for these books, they cannot be added, as they are already listed in the eBooks. Could a separate button be added for just adding as an audiobook? It is inconvenient that a wanted audiobook has to be added by adding both the eBook and audiobook.

You can choose the "library" from the author page, there is a dropdown on the top right for audiobook or ebook. When we add a book to the library it is just an author and title, the assumption is that all titles can be an ebook or an audiobook so every title shows up under both "libraries" on this page.

> Debug log was created for the actions of trying to change 2 ignored eBooks to a deleted and removed status, of which neither worked properly. Both of these books are still listed as ignored.

No debug log attached?  I think this is working ok though, as explained above.

**Comment by algarythem** [comment]
This works perfectly, and as intended. Thank you for the quick response, and I apologize for missing the audiobook selection feature on the author's page.
