### ISSUE TITLE
AttributeError: 'module' object has no attribute 'INSTALL_TYPE'

### ISSUE THREAD

**Issue by Gamethrall** [DobyTang/LazyLibrarian#1324]
LazyLibrarian version number:  970158524cf7f0028e075b7374dd86b30c94d23b
Operating system used: Windows 10
Interface in use: bookstrap
Which API: Goodreads
Source of your LazyLibrarian installation: git

I tried to switch the interface from bootstrap to default, and now all pages give the error:
Error !
AttributeError: 'module' object has no attribute 'INSTALL_TYPE'
<body> <div id="container"> <div id="ajaxMsg"></div> % if lazylibrarian.INSTALL_TYPE != 'win': % if not lazylibrarian.CURRENT_VERSION: <div id="updatebar"> You're running an unknown version of lazylibrarian. <a href="update">Update</a> or <a href="#" onclick="$('#updatebar').slideUp('slow');">Close</a> </div>
C:/LazyLibrarian/data/interfaces/default/base.html, line 96:
% if lazylibrarian.INSTALL_TYPE != 'win':
C:\LazyLibrarian\mako\runtime.py, line 890:
callable_(context, *args, **kwargs)
C:\LazyLibrarian\mako\runtime.py, line 864:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
C:\LazyLibrarian\mako\runtime.py, line 829:
**_kwargs_for_callable(callable_, data))
C:\LazyLibrarian\mako\template.py, line 445:
return runtime._render(self, self.callable_, args, data)
C:\LazyLibrarian\lazylibrarian\webServe.py, line 77:
return template.render(perm=lazylibrarian.perm_admin, **kwargs)

I cannot get back to config to try changing it back.

**Comment by philborman** [comment]
I think you must have an old installation, or parts of it, lying around. The old default interface was renamed to "legacy" a while ago, and some of the features used were renamed. 

You can get up and running again by editing the config.ini file http_look entry and change it back to bookstrap, or delete the folder lazylibrarian/data/interfaces/default.
If we can't find the folder we will drop back to "legacy".  If legacy is missing we give up.

**Comment by Gamethrall** [comment]
Ah. I tried editing that ini file, but for some reason I thought it was called "bootstrap." No wonder it didn't work.

I have edited the ini file and for good measure, I've deleted lazylibrarian/data/interfaces/default. If I have any more issues like that, I'll delete all of the files in the LL directory and re-download.

Thanks!
