### ISSUE TITLE
"Unable to rename" error on book name with colon (":") in it

### ISSUE THREAD

**Issue by Gamethrall** [DobyTang/LazyLibrarian#1328]
LazyLibrarian version number: 96ad435ad4e3d2798c39fa95a02d071c40c563f2 
Operating system used: Windows 10
Interface in use: bookstrap
Which API: Goodreads
Source of your LazyLibrarian installation: git

Unable to rename [D:\Books\Audio Books\Pepper Winters\Pennies Dollar Volume 1 (Unabridged)\Chapter 9.mp3] to [D:\Books\Audio Books\Pepper Winters\Pennies Dollar Volume 1 (Unabridged)\Pepper Winters - Pennies: Dollar, Volume 1 (Unabridged): Part 09 of 36.mp3] IOError [Errno 22] invalid mode ('wb') or filename: u'D:\\Books\\Audio Books\\Pepper Winters\\Pennies Dollar Volume 1 (Unabridged)\\Pepper Winters - Pennies: Dollar, Volume 1 (Unabridged): Part 09 of 36.mp3'

**Comment by philborman** [comment]
Windows doesn't like colons in device names, but other systems are fine with them. There are two colons in the filename, the first is included in the title, and the second (between title and Part 09) is added by us from the audiobook format string. We can remove that one easily enough. The first one is more tricky, I will have to leave the colon in (for systems that _can_ handle it), try to catch the error, and rename if there is a problem.
