### ISSUE TITLE
not an issue, a suggestion.

### ISSUE THREAD

**Issue by gilly65** [DobyTang/LazyLibrarian#133]
in \data\images, the lazylibrarian.png file is 345KB and looks like crap on the main menu, I found a better one. Rather than just trying to drop it in mine all the time, I figured you could put it in here and it would help everybody. It's tiny in comparison and looks just fine.

![lazylibrarian](https://cloud.githubusercontent.com/assets/3980067/7735392/5caef3e4-ff13-11e4-9415-b853797a2aa5.png)

and thanks for starting development again, I had all but given up.

**Comment by nncrypted** [comment]
Fixed
