### ISSUE TITLE
Pagination retains spot even if new author selected doesnt have as many books

### ISSUE THREAD

**Issue by Code-Slave** [DobyTang/LazyLibrarian#1330]
Running latest master.

When you go into an author from main page and go to page say 10 browsing books, when you go back to main page and select a new author with less titles who doesnt have 10 pages of books, it displays a blank page. you have to hit first page on the nav then it all works, seems a var needs to be reset

**Comment by philborman** [comment]
This is datatables "statesave". It remembers table position, sort columns, filters etc. on a per-table basis.
Mostly you want this, when you change author you don't. I haven't figured out a way to do this yet, and always-on seems more useful than always-off. the datatables documentation says the statesave info is lost when the page url changes, but this seems not to be the case as changing author changes the url.

**Comment by Code-Slave** [comment]
Yes its odd . Its says url or tableid change should reset. maybe a reset button? though thats kinda messy

**Comment by philborman** [comment]
I think I probably have to track the authorid in python and pass statesave = true/false as appropriate to the javascript table display code.

**Comment by philborman** [comment]
I have added some code to do this, but I'm not sure I like it. 
It resets new authors to the first page of their results, but it also resets the filter, the sort column, and the column toggles which you might not want. I will have to look into how to refine it so we only reset the one item, not the whole saved state.

**Comment by philborman** [comment]
ok, sorted it now, new version out later today. It was suspiciously easy to do. Don't need to mess with savestate at all, just table.page('first').draw() if it's a different author to the last time we drew the page.
