### ISSUE TITLE
Feature Request: 'Top of Page' widget, at bottom of pages...

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1333]
Feature Request: 'Top of Page' widget, at bottom of pages...

Just like in Radarr and Sonarr.
Some of the tabs such as magazines, filters, ebooks, are so long it takes a while to scroll back to the top.

**Comment by philborman** [comment]
That was surprisingly easy to add. Expect it in the next release :-)

**Comment by MrMxyzptlk** [comment]
Danke!
