### ISSUE TITLE
Feature Request: Load 'column options' before tab loads...

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1334]
Feature Request: Load 'column options' before tab loads...on all tabs.

For instance, if I un-toggle the magazine covers, every time I go to that tab it loads the tab, shows the covers, and THEN hides the covers.

Is there a way to make all of 'toggles' load in advance? They also hide / unhide during a magazine scan, etc...I don't want them showing at all...NSFW.

**Comment by philborman** [comment]
Would need to dig into how datatables works. The toggles and the table drawing are all done by that library. Maybe there is a switch to set somewhere to delay drawing the table?

**Comment by philborman** [comment]
Interesting, looks to me like the only page with the toggle/redraw issue is the magazines page. I don't see the same issue on author or book pages - can you confirm?

**Comment by MrMxyzptlk** [comment]
Yes, I would concur. It also does this during a magazine scan as well.
