### ISSUE TITLE
Failed to clear log: The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by Gamethrall** [DobyTang/LazyLibrarian#1336]
LazyLibrarian version number: 6dd0951e0f3e2adae9ff42718be4cb730e4c0668
Operating system used: Windows 10
Interface in use: bookstrap
Which API: Goodreads
Source of your LazyLibrarian installation: git

Whenever I try to clear the log from the Logs page, I receive the message "Failed to clear log: The process cannot access the file because it is being used by another process"

I have LazyLibrarian.py installed as a Windows service. I stopped the service and just ran it from the command line, same result.

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1925043/debug.zip)

**Comment by philborman** [comment]
Not sure why, works fine under linux. Maybe someone with some windows knowledge can shed some light on it.  Do you use any other similar programs on windows, headphones or sickrage for example, and do they have the same issue?

**Comment by Gamethrall** [comment]
I have both Sickrage and Headphones, and I can clear the logs in both applications.

It's not a big deal. It doesn't prevent me from using LL; I just wanted to report it.

**Comment by philborman** [comment]
Sure, it's just if it works in headphones and sickrage we can see what they do differently, copy their code :-)

**Comment by philborman** [comment]
Well it was easy to find. Headphones only clears the on-screen log, not the files. We try to do both.
I might make it switchable, or maybe trap and ignore the error and just do the on-screen if the files can't be wiped.

**Comment by Gamethrall** [comment]
On-screen would be fine with me. I use it to see just the unmatched items or errors since the last scan.

**Comment by bjfisher** [comment]
You could try some of the options on [this page](https://stackoverflow.com/questions/3565218/how-to-know-what-process-is-using-a-given-file) just in case something else is using the files.

**Comment by blkhwk0833** [comment]
That fixed it for me thanks .

**Comment by Gamethrall** [comment]
Same here. Thanks!

**Comment by blkhwk0833** [comment]
Don't know when it happened ,but it seems that my issue came back. With the exception that it now clears the on-screen log but gives me a different error message stating that it couldn't (

Failed to clear logfiles: The process cannot access the file because it is being used by another process
--


)

**Comment by blkhwk0833** [comment]
But in truth it did clear it .
Strange just wanted to submit it for tracking

**Comment by blkhwk0833** [comment]
@philborman I figured out the issue when I reinstalled after an issue I copied over the version file too . So I was actually a few commits back . After taking an update it all fine .
