### ISSUE TITLE
Feature Request: Add different date formats for magazines.

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1339]
Feature Request: Add different date formats for magazines.

I.E. I would prefer to read 1-10-2017 or 01-10-2017 versus 2017-10-01

It makes my North American head spin ; )

**Comment by philborman** [comment]
Yeah, it's done that way for sorting purposes. Might be feasible to have display different to stored value, will have a think about it.

**Comment by MrMxyzptlk** [comment]
sooooo, this is in the latest version?

**Comment by philborman** [comment]
Yes, in config -> importing. Two date variables, one for "Added" date  columns, and one for issue date
