### ISSUE TITLE
Goodreads sync authentication fails after saving working credentials

### ISSUE THREAD

**Issue by silentArtifact** [DobyTang/LazyLibrarian#1340]
I've been seeing an issue where I'll successfully authenticate LL against goodreads, save the settings, and then on next test it'll fail. Any ideas?

To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
f1768e0728105ad662a5b0c395f66de76b75330a
### Operating system used (windows, mac, linux, NAS type)
Synology DS718+
### Interface in use (default, bookstrap)
Default
### Which api (Goodreads, GoogleBooks, both)
Goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
[Docker](https://hub.docker.com/r/thraxis/lazylibrarian-calibre/)
### Relevant debug log with api keys and any passwords redacted

2018-04-20 15:49:05 | WARNING | WEBSERVER | grsync.py | get_user_id | 121 | Goodreads user id error: Please authorise first
-- | -- | -- | -- | -- | -- | --
2018-04-20 15:48:41 | INFO | CONFIG_WRITE | __init__.py | config_write | 1039 | Config file [/config/config.ini]  has been updated

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report. 
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1932793/debug.zip)

**Comment by philborman** [comment]
Ok, seems we didn't save gr_oauth_secret.

Ah - found it. 
We don't refresh the page after oauth2 so the boxes are left blank.
If you save the config at that point you save the empty values. 
Need to add some code to refresh the page
