### ISSUE TITLE
ajax error clicking on ebooks link

### ISSUE THREAD

**Issue by gyre** [DobyTang/LazyLibrarian#1344]
![8a590567-cd0e-4bdd-8b31-41ef79f713f5](https://user-images.githubusercontent.com/434906/39088551-099a3ffa-45ac-11e8-83b5-cb52219e1369.png)
I've just switched from legacy to bookstrap.  I'm finding that each time I click on the ebooks link, I get the following error:

DataTables warning: table id=book_table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

and nothing is displayed on the page.

I've tried generating a debug log, but nothing extra gets written into it by selecting this link.

I'm happy to debug this further, if somebody lets me know the best way to do this.

-- gyre --

LazyLibrarian version: ce900db2dc08835ced31c6931cc4803aedfc75f5
OS: Debian Jessie
Interface: bookstrap
API: both
Source: linuxserver.io docker container

**Comment by philborman** [comment]
I think this was fixed a few hours ago, can you upgrade to latest and see if you still have problems. Thanks

**Comment by gyre** [comment]
however, it is now failing after updating my active authors.  The authors it hasn't yet updated yet list fine.

![257cd975-ea9b-4537-b6c9-80557a26db61](https://user-images.githubusercontent.com/434906/39088956-cc56ccf0-45b3-11e8-853f-a74ac65501ff.png)

**Comment by gyre** [comment]
Yup, can certainly do that.  Where would be a good place to start?  I'm not familiar with ajax.

**Comment by philborman** [comment]
Me neither, but fortunately it's the python code we need to edit :-)
It's all in webServe.py, keep a copy of the unmodified file so you can put it back afterwards.

In the getBooks() function, around line 1583 is this section...
```
            if sortcolumn in [12, 13, 15]:  # series, date
                self.natural_sort(filtered, key=lambda y: y[sortcolumn] if y[sortcolumn] is not None else '',
                                  reverse=sSortDir_0 == "desc")
            elif sortcolumn in [2]:  # title
                filtered.sort(key=lambda y: y[sortcolumn].lower(), reverse=sSortDir_0 == "desc")
            else:
                filtered.sort(key=lambda y: y[sortcolumn], reverse=sSortDir_0 == "desc")
```
if you comment that section our or remove it completely that will stop us trying to sort the column, which is where the problem is.  If you can add   `logger.info("Sort column %s" % sortcolumn)`  that will also tell us which column was the problem.

**Comment by gyre** [comment]
It might be versionitis between the docker container version and the latest git version, but what's causing the author book list to fail is row[13] is None at around line 1648 near the end of getBooks, and then dateFormat is throwing an exception.

**Comment by philborman** [comment]
Ok, thanks for that.
Can you check your formatter.py file, the dateFormat function should start with 
```
    if not datestr:
        return ""
    if datestr.isdigit():
        return datestr

```
which shouldn't throw an exception on None, should return empty string?

**Comment by gyre** [comment]
the version of the code in the docker container is different to that and doesn't check to see if datestr is None before using it.  i suspect it's an earlier version.  i've got a feeling that me attempting to update lazylibrarian within the container is what is causing problems.

**Comment by philborman** [comment]
ok, if you add those lines into the top of dateFormat the problem will be fixed, and when the docker next updates it will include the new code.  Some dockers auto-build on a timer, eg the Thraxis one updates on Fridays, not sure about the linuxserver one but they are usually fairly quick.

**Comment by gyre** [comment]
thanks.  will do that. :)

**Comment by CHBMB** [comment]
@philborman We update on Fridays at 23:00 UK time

**Comment by philborman** [comment]
That's great thanks, I will try extra hard  not to break anything on a Friday evening :-)
