### ISSUE TITLE
Feature Request: Select daily, weekly, bi-weekly, monthly, annual, etc for individual mags.

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1349]
Feature Request: Select daily, weekly, bi-weekly, monthly, annual, etc for individual mags; kind of like Sonarr does for TV shows, you can select 'daily' or 'standard'.

So have the ability to select bi-monthly would adjust how the mags issue date is shown and allowed.
For example: Maxim USA January - February  bi monthly issue would only allow 1 copy; not 1 for January and the same one for February. It would also show the date a January - February.

**Comment by philborman** [comment]
Quite tricky to do as there is no central repository that tells you how often a magazine comes out, and no naming standard in use to tell which issue is which, ie this is Maxim March with one nzb search...
 Maxim.USA.TruePDF-March.April.2018
 Maxim.USA.TruePDF-March.2018
Are those the same issue, or different?  
We should, I think, pick the first up as the April issue and the second as March issue.
(we work backwards from the year to find month, then backwards from that there is no daynumber)
Might be fairly easy to recognise the two month names as a special case and do it automatically, I will have a look. Bi-weekly usually works ok, as the issues have a different daynumber, so 01-Apr-2018 and 15-Apr-2018 are clearly different issues.

**Comment by MrMxyzptlk** [comment]
No, I'm suggesting letting us users be able to change the 'dropdown'. Not automatically.

...just like in Sonarr.

It defaults to 'standard' TV show, but the user can choose 'daily' if they like.

**Comment by philborman** [comment]
I see what you mean, but apart from bi-monthly we already handle all the date formats automatically.
Daily, weekly, bi-weekly, monthly, seasonal, annual. A dropdown for only bi-monthly seems less useful than finding a way around it...

Would be fairly easy to detect bi-monthly and use the first month as the issue date, so
Jan-Feb 2018 would appear as Jan 2018 and you would end up with Jan 2018, March 2018, May 2018 etc.  The Feb April June months would get dropped as long as there wasn't an issue with only the second month name in it. Seems the uploaders who only put one month in the title always use the first month. Might be a reasonable way forward?

**Comment by philborman** [comment]
give it a try, should be in tomorrows release : -)

**Comment by MrMxyzptlk** [comment]
Excellente!
