### ISSUE TITLE
Audiobook snatched but marked as skipped

### ISSUE THREAD

**Issue by robflate** [DobyTang/LazyLibrarian#1361]
- LazyLibrarian version number: `48dcc7b971de144d9744997925cfa61f03d1d6e1`
- Operating system used: Docker container running on MacOS 10.13.4
- Interface in use: bookstrap
- Which api: Goodreads
- Source of your LazyLibrarian installation: https://hub.docker.com/r/linuxserver/lazylibrarian/
- Relevant debug log with api keys and any passwords redacted: [debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1949206/debug.zip)

I search for an Audiobook which is successfully found and sent to Deluge. The download finishes and Deluge moves it to my completed torrents folder. LazyLibrarian does not mark it as snatched in the History table. It is instead marked as Skipped. This means it is never processed and never moved to my AudioBook Library Folder.

![lazylibrarian - history 2018-04-26 01-02-13](https://user-images.githubusercontent.com/4172375/39278880-7efdb6fc-48ed-11e8-9695-c4d6826c3a0e.png)

**Comment by philborman** [comment]
We seem to be stopping part-way through setting the label?  The last entry in your log is deluge.py:setTorrentLabel:441 : Deluge: Books label doesn't exist in Deluge, let's add it
and nothing saying "Label added"  or  "Setting label failed"
Will have to look into why.  What version of deluge are you running, in case it's version dependent

**Comment by robflate** [comment]
Deluge 1.3.15 run from this Docker image using the :latest tag;

https://hub.docker.com/r/linuxserver/deluge/

**Comment by robflate** [comment]
I manually added the book label in Deluge and LL now correctly marks Audiobooks as snatched when downloading via Deluge. I now seem to have another issue which I've made a separate post for as I don't think it's connected to this.
