### ISSUE TITLE
Failed query: [SELECT count(*)) as counter FROM books WHERE Status = 'Wanted']

### ISSUE THREAD

**Issue by splog123** [DobyTang/LazyLibrarian#1365]
After git pull latest commit 29/4/2018, I get in the logs:

29-Apr-2018 18:52:01 - ERROR :: WEBSERVER : database.py:action:62 : Database error: near ")": syntax error
29-Apr-2018 18:52:01 - ERROR :: WEBSERVER : database.py:action:63 : Failed query: [SELECT count(*)) as counter FROM books WHERE Status = 'Wanted']

It's this snippet from 798de00e83360cd991600a8205402bb94738ea23

@@ -570,8 +570,8 @@ def checkRunningJobs():
     # but check anyway for completeness...

     myDB = database.DBConnection()
-    snatched = myDB.match("SELECT count('Status') as counter from wanted WHERE Status = 'Snatched'")
-    wanted = myDB.match("SELECT count('Status') as counter FROM books WHERE Status = 'Wanted'")
+    snatched = myDB.match("SELECT count(*) as counter from wanted WHERE Status = 'Snatched'")
+    wanted = myDB.match("SELECT count(*)) as counter FROM books WHERE Status = 'Wanted'")
     if snatched:
         ensureRunning('processDir')
     if wanted:

A simple uncaught double-keypress, methinks

**Comment by philborman** [comment]
Yes that's exactly it, will push a fix in a couple of hours. Slipped through the code checker too!

**Comment by splog123** [comment]
Thanks, a fix will be nice indeed :-)
