### ISSUE TITLE
Author Sort

### ISSUE THREAD

**Issue by Hydro-guy** [DobyTang/LazyLibrarian#1368]
When you select authors home the authors are not sorted alphabetically unless you click on the latest book column.  This behaviour changed approx 2 months ago. The example below is copied from the interface.
  | Kate Atkinson |  
  | David Weber | 
  | Ram Charan | 
  | Paula Hawkins |
  | Ruth Rendell | 
  | Rebecca Shaw | 
  | Amy Andrews | 

John
Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: bcf442decf8238156f1882e599cecf54960eecb1 : Latest Version: bcf442decf8238156f1882e599cecf54960eecb1

win10 default goodreads git

**Comment by philborman** [comment]
There was an extra column added to bookstrap interface which default doesn't know about. Fixed now. Would probably be best to move to bookstrap interface as all new features are only available there. The old interface is not receiving any updates as some of the libraries it uses are too old.
