### ISSUE TITLE
Can't move .m4a file, Not a recognised archive

### ISSUE THREAD

**Issue by robflate** [DobyTang/LazyLibrarian#1373]
LazyLibrarian version number: `a7d2615c95ada10c6fb7db9678c84646c3e861de`
Operating system used: Docker container running on MacOS 10.13.4
Interface in use: bookstrap
Which api: Goodreads
Source of your LazyLibrarian installation: https://hub.docker.com/r/linuxserver/lazylibrarian/
Relevant debug log with api keys and any passwords redacted: [debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1970502/debug.zip)

When processing an audiobook downloaded via Deluge, LL marks it as `Snatched` but can't move the completed download. I get errors like;

- Deluge files: Could not get torrent folder KeyError: u'total_done'
- Skipping unhandled file
- is not a file or a directory?
- Not a recognised archive

The file extension is .m4a which is not in any excluded lists in Settings.

**Comment by philborman** [comment]
The  Could not get torrent folder KeyError: u'total_done'  means we are not talking to deluge properly, or deluge isn't running, which might not be fatal. The extensions recognised are an "include" list rather than an "exclude" one, so you need m4a adding to config->importing Audiobook File Formats. Default is just mp3

**Comment by robflate** [comment]
Thanks, I've added m4a now.

Regarding the communication with Deluge not working properly, I'm seeing other errors that seem to suggest this. E.g. I saw an error when LL added a magnet link that said something like, 'is deluge running?'. From what I can see, Deluge is running; 

- The Deluge webui works
- The Deluge daemon shows as connected in the connection manager
- I can connect successfully with the Test Deluge button in LL
- I can manually add a torrent to Deluge
- Other apps like Lidarr/Sonarr seem to communicate with Deluge fine
- LL has successfully downloaded ebooks via Deluge

Is there any way I can diagnose this using the logs or anything?

**Comment by philborman** [comment]
Can't diagnose with the current logs, not enough info. Seems to be working fine here and also mostly working on your system, test button works, files get sent, so I need to expand the "is deluge running" message to give more info on what we get back from deluge. Will push a new version tomorrow with extra debugging on level 3.
