### ISSUE TITLE
UTF error on editing author

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1374]
http://localhost:5299/editAuthor?authorid=24567  (does this for all authors, not just this one)

Make change or don't make change, hit submit and get a 400 error

400 Bad Request
Unexpected body parameters: utf8

Traceback (most recent call last):
  File "/Users/kids/src/LazyLibrarian-master/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/Users/kids/src/LazyLibrarian-master/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Users/kids/src/LazyLibrarian-master/cherrypy/_cpdispatch.py", line 67, in __call__
    raise sys.exc_info()[1]
HTTPError: (400, 'Unexpected body parameters: utf8')

Powered by CherryPy 3.6.0 

Repo: https://github.com/dobytang/lazylibrarian : Branch: master : Updated: Tue May 1 16:02:25 2018
Current Version: cbd1c48a81e5021d8b64eee86e5a89b1c19c7710 : Latest Version: cbd1c48a81e5021d8b64eee86e5a89b1c19c7710

MacOS 10.13.4

Looked at logs (set to level 2, debug) and they're not helpful.   There's nothing in them about AuthorUpdate.

This does not happen on editbook: http://localhost:5299/editBook?bookid=26198855

I'm no expert so take this with a grain of salt but it seems like CherryPy is caching result.  I get the 400 error as soon as I press Edit next to the author's name. 

If I press the back arrow, I get sent to http://localhost:5299/authorUpdate (notice author is stripped)

**Comment by philborman** [comment]
Ok, the line containing utf8 in editauthor.html  is exactly the same as the line in editbook.html
It was placed to force Internet Explorer to properly respect the form’s character encoding.
Can't see why this is only causing errors on editauthor and not editbook...   Needs investigation.

**Comment by dkids** [comment]
Seems to be fixed.

**Comment by dkids** [comment]
Forgot to say thanks!

**Comment by philborman** [comment]
No probs, silly error, not picked up by the smart code checking software I was using either.
