### ISSUE TITLE
Fork source changed

### ISSUE THREAD

**Issue by Code-Slave** [DobyTang/LazyLibrarian#1376]
for about 4 days now i get errors that it cant check git. Looking around it looks like the source of the for changed from itsmegb to lexis. Not sure if related or not.

**Comment by philborman** [comment]
Yes I noticed the change of fork. No idea what it means or how it came about.
Shouldn't affect checking git as that's still checking DobyTang.

What errors are you getting, debug level 2 is quite verbose in git communication.

**Comment by philborman** [comment]
I think the reason the fork has changed is that itsmegb fork has been deleted so presumably that in turn was forked from lexis?

**Comment by Code-Slave** [comment]
Yes thats what it looks like. As of this morning its working again (git check). Have no idea shrug.

i think lexis froked from itsmeg but never change so maybe github is trying to be smart
