### ISSUE TITLE
LL stalls on 'Deluge: Removing torrent xxxxx'

### ISSUE THREAD

**Issue by robflate** [DobyTang/LazyLibrarian#1382]
LazyLibrarian version number: `654505062cc9c4035067fe4d043e0bb8c31a1266`
Operating system used: Docker container running on MacOS 10.13.4
Interface in use: bookstrap
Which api: Goodreads
Source of your LazyLibrarian installation: https://hub.docker.com/r/linuxserver/lazylibrarian/
Relevant debug log with api keys and any passwords redacted: [debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1984071/debug.zip)

LL snatched some ebooks and sent them to Deluge. Deluge downloaded them and LL processed the first one and successfully renamed/moved it to my Books folder. It then stalled with `Deluge: Removing torrent 075a1096f6ce99ddac1873864526ebd0af914b90`. That remained at the top of the log for several hours and LL did not move onto process the next ebook. I restarted LL and did a manual Post Process and LL then processed the next ebook successfully. LL stalled again removing the torrent. The only way to move onto the the next ebook is to restart LL for each book.

The only thing I can think of is that I have Deluge set to remove the torrent immediately after a download finishes. Should I be letting LL remove the torrent? If so, what settings should I have in LL and Deluge so books can be processed by LL whilst still seeding? Also, could there be something added to the logs that says the torrent has been removed from Deluge allowing LL to gracefully move on?

Thanks.

**Comment by philborman** [comment]
There are a couple of possibilities. The postprocessor could be stalled waiting for deluge to respond, or it could have aborted. I have tidied up the deluge code to ensure there is a timeout added to all calls, and also some extra debug messages om loglevel 3, if you could give it a try and report back?  Should be available to download in a couple of hours.

**Comment by philborman** [comment]
Any update to this?  Did adding a timeout help, or anything useful in the new debug log?
