### ISSUE TITLE
Import failed but not sure why

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1384]
I've replaced the username and password.   Import does seem to work almost all of the time.  If this is just a temporary problem it would be nice if it re-tried X times.  
[hunted.txt](https://github.com/DobyTang/LazyLibrarian/files/1984496/hunted.txt)

[moth.txt](https://github.com/DobyTang/LazyLibrarian/files/1984470/moth.txt)

Both books are in Calibre.

**Comment by philborman** [comment]
New version of lazylibrarian has more logging in the calibre communication section, hopefully will show what's going on...

**Comment by dkids** [comment]
I'm assuming the error message is related to the import of the one book.  The book is listed as "snatched" rather than "open", as were 3 other books by this author that were successfully sent to Transmission and imported.

08-May-2018 13:52:53 - DEBUG   :: POSTPROCESS : librarysync.py:LibraryScan:443 : [/Users/kid
s/Calibre/Elise Kova/] Now scanning subdirectory Water's Wrath (Air Awakens #4) (7833)
08-May-2018 13:52:53 - DEBUG   :: POSTPROCESS : librarysync.py:LibraryScan:477 : book meta [
] [en] [Elise Kova] [Water's Wrath (Air Awakens Series Book 4)] [epub]
08-May-2018 13:52:53 - DEBUG   :: POSTPROCESS : librarysync.py:find_book_in_db:170 : Searchi
ng database for [Waters Wrath (Air Awakens Series Book 4)] by [Elise Kova]
08-May-2018 13:52:53 - DEBUG   :: POSTPROCESS : librarysync.py:find_book_in_db:206 : Searchi
ng 19 books by [Elise Kova] in database for [Waters Wrath (Air Awakens Series Book 4)]
08-May-2018 13:52:53 - DEBUG   :: POSTPROCESS : librarysync.py:find_book_in_db:253 : Fuzz ma
tch partial [95] [Waters Wrath (Air Awakens Series Book 4)] [Air Awakens]
08-May-2018 13:52:53 - DEBUG   :: POSTPROCESS : librarysync.py:LibraryScan:794 : Librarysync
 link to preferred type epub: /Users/kids/Calibre/Elise Kova/Water's Wrath (Air Awakens #4) 
(7833)/Water's Wrath (Air Awakens #4) - Elise Kova.epub
08-May-2018 13:52:53 - WARNING :: POSTPROCESS : librarysync.py:LibraryScan:808 : Updating bo
ok location for Elise Kova Waters Wrath (Air Awakens Series Book 4) from /Users/kids/Calibre
/Elise Kova/Air Awakens (7831)/Air Awakens - Elise Kova.epub to /Users/kids/Calibre/Elise Ko
va/Water's Wrath (Air Awakens #4) (7833)/Water's Wrath (Air Awakens #4) - Elise Kova.epub
08-May-2018 13:52:53 - DEBUG   :: POSTPROCESS : librarysync.py:LibraryScan:811 : Elise Kova 
Waters Wrath (Air Awakens Series Book 4) matched Open BookID 23127048, [Elise Kova][Air Awak
ens]
08-May-2018 13:52:53 - INFO    :: POSTPROCESS : librarysync.py:LibraryScan:883 : 1/1 new/mod
ified eBooks found and added to the database
08-May-2018 13:52:53 - INFO    :: POSTPROCESS : librarysync.py:LibraryScan:884 : 14 files pr
ocessed
08-May-2018 13:52:53 - DEBUG   :: POSTPROCESS : librarysync.py:LibraryScan:979 : Updating bookcounts for 1 author
08-May-2018 13:52:53 - INFO    :: POSTPROCESS : librarysync.py:LibraryScan:983 : Library scan complete
08-May-2018 13:52:53 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:698 : Processed torznab: Water's Wrath (Air Awakens #4) - Elise Kova, magnet:?xt=urn:btih:137d13808d7f2b298f2f374b3d892f272fdd6495&dn=Water's+Wrath+(Air+Awakens+Seri+-+Elise+Kova.epub.torrent
08-May-2018 13:52:53 - ERROR   :: POSTPROCESS : postprocess.py:processExtras:1252 : processExtras: No dest_file supplied
08-May-2018 13:52:53 - WARNING :: POSTPROCESS : postprocess.py:processDir:746 : TRANSMISSION is seeding torznab Water's Wrath (Air Awakens Seri - Elise Kova.epub
08-May-2018 13:52:53 - INFO    :: POSTPROCESS : postprocess.py:processDir:786 : Successfully processed: Water's Wrath (Air Awakens #4) - Elise Kova

**Comment by philborman** [comment]
Calibre failed to import Ann Brashares The Sisterhood of the Traveling Pants, no added bookids
 calibre reported `The following books were not added as they already exist in the database`
so it thinks the book is already there? Calibre uses the embedded book metadata, so maybe that's the problem?

 Elise Kova Waters Wrath
You seem to have two copies in the calibre database, bookid (7831) and (7833)
Probably best to delete one of them, but check formats in case one has more than the other.

**Comment by dkids** [comment]
The books seem to have been imported properly.   Here's the titles under the author:

ls Elise\ Kova/
Air Awakens (7831)		The Alchemists of Loom (7618)
Crystal Crowned (7832)		Water's Wrath (7833)
Earth's End (7830)

Here's the contents of the directories:

ls Elise\ Kova/*
Elise Kova/Air Awakens (7831):
Air Awakens - Elise Kova.epub	metadata.opf
cover.jpg

Elise Kova/Crystal Crowned (7832):
Crystal Crowned - Elise Kova.epub	metadata.opf
cover.jpg

Elise Kova/Earth's End (7830):
Earth's End - Elise Kova.epub	metadata.opf
cover.jpg

Elise Kova/The Alchemists of Loom (7618):
The Alchemists of Loom - Elise Kova.mobi
cover.jpg
metadata.opf

Elise Kova/Water's Wrath (7833):
Water's Wrath - Elise Kova.epub	metadata.opf
cover.jpg

Not sure what I'm looking for so I've attached  "grep -i kova /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log".  I'd be happy to do other searches.

[kova.txt](https://github.com/DobyTang/LazyLibrarian/files/1985743/kova.txt)

The name of the series is "Air Awakens" and also the title of the first book (which seems like about 50% of the time the first book is the title for the series).   

I did see the Error 1252 message on other books that were successfully imported.

08-May-2018 13:52:42 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:698 : Processed to
rznab: Earth's End - Elise Kova, magnet:?xt=urn:btih:d91c0c0b08a4ab920747c8dda0c13a02b353f96
b&dn=Earth's+End+(Air+Awakens+Series+-+Kova%2C+Elise.epub.torrent
08-May-2018 13:52:42 - ERROR   :: POSTPROCESS : postprocess.py:processExtras:1252 : processExtras: No dest_file supplied
08-May-2018 13:52:42 - WARNING :: POSTPROCESS : postprocess.py:processDir:746 : TRANSMISSION is seeding torznab Earth's End (Air Awakens Series - Kova, Elise.epub
08-May-2018 13:52:42 - INFO    :: POSTPROCESS : postprocess.py:processDir:786 : Successfully processed: Earth's End - Elise Kova

08-May-2018 13:52:42 - DEBUG   :: POSTPROCESS : postprocess.py:move_into_subdir:201 : copy_into_subdir Earth's End (Air Awakens Series - Kova, Elise.epub
08-May-2018 13:52:42 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:560 : Found folder (96%) [/Users/kids/Downloads/Books/Earth's End (Air Awakens Series - Kova, Elise.unpack] for eBook Elise Kova - Air Awakens (Air Awakens #1).epub

**Comment by philborman** [comment]
Ok, I think I see what's going on here. Earth's and Water's containing apostrophes are being compared to the words without the apostrophe Earths Waters  and that's pulling down the fuzzy match percentage .

fuzz.token_sort_ratio("Waters Wrath", "Water's Wrath") = 88  which is below the threshold. 

We need to strip the apostrophes before comparison so we get the right match.  Can you run the same import with debug level set to 3, lazylibrarian will print each book it compares against and the percentage match. Should confirm if that's the problem. If it is, should be fairly simple to fix.

**Comment by dkids** [comment]
Book has been downloaded succesfully but LL is not trying to import it.

> ls -ald  Ann\ Patchett\ State\ of\ Wonder\ 2011\ Retail\ EPUB\ eBook-BitBook/
drwxr-xr-x@ 5 kids  staff  170 May 10 13:11 Ann Patchett State of Wonder 2011 Retail EPUB eBook-BitBook/
>  ls -al  Ann\ Patchett\ State\ of\ Wonder\ 2011\ Retail\ EPUB\ eBook-BitBook/
total 7280
drwxr-xr-x@  5 kids  staff      170 May 10 13:11 .
drwxr-xr-x  22 kids  staff      748 May 10 14:49 ..
-rw-r--r--   1 kids  staff  3697839 May 10 13:11 bb-State_of_Wonder.epub
-rw-r--r--   1 kids  staff    10865 May 10 13:11 bitbook.nfo
-rw-r--r--   1 kids  staff      640 May 10 13:11 file_id.diz

The log files are huge.  I am at level 3, as you asked, and I ran through 100 log files in about 8 hours last night.  And the log files are 10MB each.  I had RSS feeds set to 20 minutes which I changed to 0 minutes last night.  That - to me - seems like it should be RSS off.   

I'm not complaining, just having trouble giving you just the relevant info without a lot of other stuff thrown in.    I've tried running "Run PostProcessor" but I get a "Skipping (not LL)" error:

10-May-2018 15:09:38 - DEBUG   :: POSTPROCESS : postprocess.py:check_residual:922 : Skipping (not LL) Joe R Lansdale - Mucho Mojo
10-May-2018 15:09:38 - DEBUG   :: POSTPROCESS : postprocess.py:check_residual:922 : Skipping (not LL) Ann Leckie - [Imperial Radch 03] - Ancillary Mercy (retail).epub
10-May-2018 15:09:38 - DEBUG   :: POSTPROCESS : postprocess.py:check_residual:922 : Skipping (not LL) Ann Patchett State of Wonder 2011 Retail EPUB eBook-BitBook

Here are all the files in the directory:

Adrian Tchaikovsky - Children of Time 2015 (Sci-Fi) ePUB+MOBI
Alexandra Christo - To Kill a Kingdom LL.(34499221).fail
Ann Leckie - [Imperial Radch 03] - Ancillary Mercy (retail).epub
Ann Patchett State of Wonder 2011 Retail EPUB eBook-BitBook
Collins, Suzanne - [Distritos 02] Catching fire [5944] (r1.2 JerGeoKos).epub
Collins, Suzanne - [Distritos 02] Catching fire [5944] (r1.2 JerGeoKos).unpack
Crouch, Blake - [Wayward Pines 01] Pines [23489] (r1.0) [EN].epub
Crouch, Blake - [Wayward Pines 01] Pines [23489] (r1.0) [EN].unpack
Death Doesn't Bargain by Sherrilyn Kenyon EPUB
Deaths End The Three-Body Problem - Cixin Liu
Fangirl - Rainbow Rowell.epub
Fangirl - Rainbow Rowell.unpack
Joe R Lansdale - Mucho Mojo
Laini Taylor - Night of Cake & Puppets (Daughter of Smoke and Bone #2.5) epub & mobi.fail
Palacio R J - Wonder - Italian Edition-Bymonello78.pdf
Rowell, Rainbow - Fangirl [20912] (r1.0 Cwpper).epub
The Goldfinch-Donna Tartt BY ATHESSI13.zip
The Traitor's Game by Jennifer A. Nielsen EPUB
Torment


I'm not sure if the problem is that LL is trying to match on the file name, which is less relevant than the directory name (which has title and author both).

Anyway, I did this command in an effort to filter out duplicate searches, etc.   
grep -i "Patchett" ~/src/LazyLibrarian-master/Logs/lazylibrarian.log* | cut -f10- -d: |sort -u > ~/patchett.txt

**Comment by philborman** [comment]
> The log files are huge. I am at level 3, as you asked, and I ran through 100 log files in about 8 hours last night. And the log files are 10MB each. I had RSS feeds set to 20 minutes which I changed to 0 minutes last night. That - to me - seems like it should be RSS off.

Yes, could easily add that. At the moment you turn rss off by unticking the rss provider boxes.

> I'm not complaining, just having trouble giving you just the relevant info without a lot of other stuff thrown in. I've tried running "Run PostProcessor" but I get a "Skipping (not LL)" error:

No problem, it's improving the program!
`Run Postprocessor ` checks for snatched books and then processes any that weren't snatched but match a LL naming pattern, this is to pick up wishlist books or books from csv lists. You can ignore that message, it's just for info, something was found in our download directory that we think isn't ours so we ignored it.

I might look into fine tuning the loglevels > 2 so we can set different levels to only give in-depth reports on small sections
