### ISSUE TITLE
Direct search errors

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1387]
My guess is that the site is timing out on these.

09-May-2018 08:24:39 - DEBUG   :: SEARCHALLBOOKS : directparser.py:GEN:124 : Parsing results
 from <a href="http://gen.lib.rus.ec/foreignfiction/index.php?s=Eleanor+Herman+The+Royal+Art
+of+Poison&f_lang=All&f_ext=All&f_columns=0">libgen.io</a>
09-May-2018 08:24:39 - ERROR   :: SEARCHALLBOOKS : directparser.py:GEN:261 : An error occurred in the libgen.io parser: 'NoneType' object has no attribute 'get'
09-May-2018 08:24:39 - DEBUG   :: SEARCHALLBOOKS : directparser.py:GEN:262 : libgen.io: Traceback (most recent call last):
  File "/Users/kids/src/LazyLibrarian-master/lazylibrarian/directparser.py", line 153, in GEN
    link = data.get('href')
AttributeError: 'NoneType' object has no attribute 'get'

09-May-2018 08:24:39 - DEBUG   :: SEARCHALLBOOKS : directparser.py:GEN:269 : Found 0 results from libgen.io for Eleanor Herman The Royal Art of Poison
09-May-2018 08:24:39 - DEBUG   :: SEARCHALLBOOKS : providers.py:IterateOverDirectSites:458 : [IterateOverDirectSites] - http://libgen.io/ foreignfiction/index.php
09-May-2018 08:24:40 - DEBUG   :: SEARCHALLBOOKS : directparser.py:GEN:124 : Parsing results from <a href="http://libgen.io//foreignfiction/index.php?s=Eleanor+Herman+The+Royal+Art+of+Poison&f_lang=All&f_ext=All&f_columns=0">libgen.io</a>
09-May-2018 08:24:40 - DEBUG   :: SEARCHALLBOOKS : directparser.py:GEN:269 : Found 0 results from libgen.io for Eleanor Herman The Royal Art of Poison
09-May-2018 08:24:40 - INFO    :: SEARCHALLBOOKS : searchbook.py:search_book:289 : DIRECT Searches for eBook Eleanor Herman The Royal Art of Poison returned no results.
09-May-2018 08:24:40 - DEBUG   :: SEARCHALLBOOKS : providers.py:IterateOverDirectSites:458 : [IterateOverDirectSites] - http://gen.lib.rus.ec foreignfiction/index.php
09-May-2018 08:24:41 - DEBUG   :: SEARCHALLBOOKS : directparser.py:GEN:124 : Parsing results from <a href="http://gen.lib.rus.ec/foreignfiction/index.php?s=Eleanor+Herman+Dawn+of+Legends&f_lang=All&f_ext=All&f_columns=0">libgen.io</a>
09-May-2018 08:24:41 - ERROR   :: SEARCHALLBOOKS : directparser.py:GEN:261 : An error occurred in the libgen.io parser: 'NoneType' object has no attribute 'get'
09-May-2018 08:24:41 - DEBUG   :: SEARCHALLBOOKS : directparser.py:GEN:262 : libgen.io: Traceback (most recent call last):
  File "/Users/kids/src/LazyLibrarian-master/lazylibrarian/directparser.py", line 153, in GEN
    link = data.get('href')
AttributeError: 'NoneType' object has no attribute 'get'

09-May-2018 08:24:41 - DEBUG   :: SEARCHALLBOOKS : directparser.py:GEN:269 : Found 0 results from libgen.io for Eleanor Herman Dawn of Legends
09-May-2018 08:24:41 - DEBUG   :: SEARCHALLBOOKS : providers.py:IterateOverDirectSites:458 : [IterateOverDirectSites] - http://libgen.io/ foreignfiction/index.php
09-May-2018 08:24:42 - DEBUG   :: SEARCHALLBOOKS : directparser.py:GEN:124 : Parsing results from <a href="http://libgen.io//foreignfiction/index.php?s=Eleanor+Herman+Dawn+of+Legends&f_lang=All&f_ext=All&f_columns=0">libgen.io</a>
09-May-2018 08:24:42 - DEBUG   :: SEARCHALLBOOKS : directparser.py:GEN:269 : Found 0 results from libgen.io for Eleanor Herman Dawn of Legends
09-May-2018 08:24:42 - INFO    :: SEARCHALLBOOKS : searchbook.py:search_book:289 : DIRECT Searches for eBook Eleanor Herman Dawn of Legends returned no results.

**Comment by philborman** [comment]
Subtle change to the way libgen returns an empty table (no matching results found) that was breaking our parser. Should be fixed now. You can safely ignore the error, Found 0 results is correct.
