### ISSUE TITLE
Postprocess error?

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1388]
Found this while looking for warnings.  I am trying to eliminate duplicate books but something like this isn't flagged by Calibre's dupe-checker plugin.   Most often the duplicates sneak in when several books are downloaded in one bundle.   

/Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.9:08-May-2018 14:51:55 - WARNING :: POSTPROCESS : librarysync.py:LibraryScan:808 : Updating book location for Sarah J. Maas Heir of Fire from /Users/kids/Calibre/Sarah J. Maas/Throne Of Glass 03_ Heir Of Fire (7741)/Throne Of Glass 03_ Heir Of Fire - Sarah J. Maas.mobi to /Users/kids/Calibre/Sarah J. Maas/Heir of Fire (7755)/Heir of Fire - Sarah J. Maas.epub
/Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.9:08-May-2018 14:51:56 - WARNING :: POSTPROCESS : librarysync.py:LibraryScan:808 : Updating book location for Sarah J. Maas Throne Of Glass 03: Heir Of Fire from /Users/kids/Calibre/Sarah J. Maas/Heir of Fire (7755)/Heir of Fire - Sarah J. Maas.epub to /Users/kids/Calibre/Sarah J. Maas/Throne Of Glass 03_ Heir Of Fire (7741)/Throne Of Glass 03_ Heir Of Fire - Sarah J. Maas.mobi
/Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.9:08-May-2018 14:52:01 - WARNING :: POSTPROCESS : librarysync.py:LibraryScan:808 : Updating book location for Sarah J. Maas Heir of Fire from /Users/kids/Calibre/Sarah J. Maas/Throne Of Glass 03_ Heir Of Fire (7741)/Throne Of Glass 03_ Heir Of Fire - Sarah J. Maas.mobi to /Users/kids/Calibre/Sarah J. Maas/Heir of Fire (7755)/Heir of Fire - Sarah J. Maas.epub
/Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.9:08-May-2018 14:52:03 - WARNING :: POSTPROCESS : librarysync.py:LibraryScan:808 : Updating book location for Sarah J. Maas Throne Of Glass 03: Heir Of Fire from /Users/kids/Calibre/Sarah J. Maas/Heir of Fire (7755)/Heir of Fire - Sarah J. Maas.epub to /Users/kids/Calibre/Sarah J. Maas/Throne Of Glass 03_ Heir Of Fire (7741)/Throne Of Glass 03_ Heir Of Fire - Sarah J. Maas.mobi
/Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.9:08-May-2018 14:52:09 - WARNING :: POSTPROCESS : librarysync.py:LibraryScan:808 : Updating book location for Sarah J. Maas Heir of Fire from /Users/kids/Calibre/Sarah J. Maas/Throne Of Glass 03_ Heir Of Fire (7741)/Throne Of Glass 03_ Heir Of Fire - Sarah J. Maas.mobi to /Users/kids/Calibre/Sarah J. Maas/Heir of Fire (7755)/Heir of Fire - Sarah J. Maas.epub
/Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.9:08-May-2018 14:52:11 - WARNING :: POSTPROCESS : librarysync.py:LibraryScan:808 : Updating book location for Sarah J. Maas Throne Of Glass 03: Heir Of Fire from /Users/kids/Calibre/Sarah J. Maas/Heir of Fire (7755)/Heir of Fire - Sarah J. Maas.epub to /Users/kids/Calibre/Sarah J. Maas/Throne Of Glass 03_ Heir Of Fire (7741)/Throne Of Glass 03_ Heir Of Fire - Sarah J. Maas.mobi
/Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.9:08-May-2018 14:52:18 - WARNING :: POSTPROCESS : librarysync.py:LibraryScan:808 : Updating book location for Sarah J. Maas Heir of Fire from /Users/kids/Calibre/Sarah J. Maas/Throne Of Glass 03_ Heir Of Fire (7741)/Throne Of Glass 03_ Heir Of Fire - Sarah J. Maas.mobi to /Users/kids/Calibre/Sarah J. Maas/Heir of Fire (7755)/Heir of Fire - Sarah J. Maas.epub
/Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.9:08-May-2018 14:52:19 - WARNING :: POSTPROCESS : librarysync.py:LibraryScan:808 : Updating book location for Sarah J. Maas Throne Of Glass 03: Heir Of Fire from /Users/kids/Calibre/Sarah J. Maas/Heir of Fire (7755)/Heir of Fire - Sarah J. Maas.epub to /Users/kids/Calibre/Sarah J. Maas/Throne Of Glass 03_ Heir Of Fire (7741)/Throne Of Glass 03_ Heir Of Fire - Sarah J. Maas.mobi

**Comment by dkids** [comment]
> ls Sarah J. Maas
A Court of Mist and Fury (A Court of Thorns and Roses, #2) (8453)
A Court of Thorns and Roses (7838)
A Court of Wings and Ruin (8454)
Crown of Midnight (7742)
Empire of Storms (7839)
Heir of Fire (7755)
Queen of Shadows (7805)
The Assassin and the Desert (7744)
The Assassin and the Pirate Lord (7745)
The Assassin and the Underworld (7800)
The Assassin's Blade (7746)
Throne Of Glass 03_ Heir Of Fire (7741)
Throne of Glass (7837)
Tower of Dawn (7840)

**Comment by philborman** [comment]
Yes it's just a warning that you have two (or more) copies. As we scan the filesystem we link the [Open] button to the preferred filetype. Later on we hit another copy of the same book and warn you that the button will now open a different file. If you remove the duplicates the warnings will go away.
