### ISSUE TITLE
Directory name too long?

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1391]
There's not a zipfile in the directory.   That's a truly horrendous title for the directory and it has a "!" embedded in it.

> grep ERROR /Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log 
09-May-2018 12:13:04 - ERROR   :: EBOOK_SCAN : librarysync.py:get_book_info:98 : Unable to parse epub file /Users/kids/Calibre/Philip Pullman/Two Crafty Criminals!_ And How They Were Captured by the Daring Detectives of the New Cut Gang (1056)/Two Crafty Criminals!_ And How They Were C - Philip Pullman.epub, BadZipfile File is not a zip file

> ls -d ~/Calibre/Philip\ Pullman/Tw*
/Users/kids/Calibre/Philip Pullman/Two Crafty Criminals!_ And How They Were Captured by the Daring Detectives of the New Cut Gang (1056)

> ls ~/Calibre/Philip\ Pullman/Tw*
Two Crafty Criminals!_ And How They Were C - Philip Pullman.epub
cover.jpg
metadata.opf

**Comment by philborman** [comment]
epub files are zip archives, we try to read 'META-INF/container.xml' from the archive. Looks like that's a corrupt epub file. Don't think the filename should be a problem. If we can't read the info we just ignore it and go with what's in metadata.opf

**Comment by dkids** [comment]
Calibre couldn't view it so I deleted the entry.   Should have tried viewing it first.

Thanks.
