### ISSUE TITLE
Calibre sync returns "No userid found"

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1392]
Calibre Sync Result

No userid found

(I'm running LL on a headless Mac Mini and for some reason screenshots stopped working with the last security update.   I get a file that's greyed out.   So I had to use the built-in screenshot tool with FireFox, which doesn't include the URL.)

![screenshot-2018-5-9 lazylibrarian - manage ebooks](https://user-images.githubusercontent.com/30055574/39835680-c2cc6ac0-5385-11e8-9519-4c512ebfae62.png)

I use Library Scan to update what LL knows about what's on disk but it takes time and I was hoping Calibre Sync would be faster.

**Comment by philborman** [comment]
Calibre Sync syncs your "wanted" and "read" books with custom calibre columns, probably not what you're after.  The initial lazylibrarian libraryscan is slow, but we cache as much data as possible so subsequent scans are much faster.

**Comment by dkids** [comment]
OK, thanks.
