### ISSUE TITLE
Don't import txt file

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1395]
Notice that the txt file is under 10k, which seems reasonable as the floor for size.   Anything under 10k is probably not usable.

total 4432
drwxr-xr-x@  5 kids  staff      170 May 10 11:53 .
drwxr-xr-x  13 kids  staff      442 May 10 12:08 ..
-rw-r--r--   1 kids  staff   979666 May 10 11:53 Death's End - Liu Cixin.epub
-rw-r--r--   1 kids  staff  1271592 May 10 11:53 Death's End - Liu Cixin.mobi
-rw-r--r--   1 kids  staff       56 May 10 11:53 Death's End - Liu Cixin.txt

book meta [9781784971625] [en] [Cixin Liu] [Death's End (The Three-Body Problem)] [epub]
 book meta [9781784971625] [en] [Cixin Liu] [Death's End (The Three-Body Problem)] [mobi]
 calibredb res 379[Title               : Death's End Title sort          : Death's End (The Three-Body Problem) Author(s)           : Liu Cixin [Liu, Cixin] Publisher           : Head of Zeus Languages           : eng Timestamp           : 2018-05-10T18:53:55.220157+00:00 Published           : 2016-09-19T14:00:00+00:00 Identifiers         : goodreads:25451264 Formats             : EPUB,MOBI,TXT ]
 calibredb res 401[Title               : Death's End Title sort          : Death's End (The Three-Body Problem) Author(s)           : Liu Cixin [Liu, Cixin] Publisher           : Head of Zeus Languages           : eng Timestamp           : 2018-05-10T18:53:55.220157+00:00 Published           : 2016-09-19T14:00:00+00:00 Identifiers         : mobi-asin:B016AWGJBK, isbn:9781784971625 Formats             : EPUB,MOBI,TXT ]
 calibredb res 426[Title               : Death's End (The Three-Body Problem) Title sort          : Death's End (The Three-Body Problem) Author(s)           : Liu Cixin [Liu, Cixin] Publisher           : Head of Zeus Languages           : eng Timestamp           : 2018-05-10T18:53:55.220157+00:00 Published           : 2016-09-19T14:00:00+00:00 Identifiers         : mobi-asin:B016AWGJBK, isbn:9781784971625 Formats             : EPUB,MOBI,TXT ]

**Comment by philborman** [comment]
Good idea.
Next version will only send across files matching lazylibrarian wanted booktypes, so if you only want mobi and the download contains mobi,epub,txt we will only send mobi to calibre.

**Comment by philborman** [comment]
Ah ok, we weren't deleting the original txt file, just ignoring the rename code. Calibre needs all parts to have the same basename (book_name.epub, book_name.mobi, book_name.opf) or at least it used to. It would ignore anything not matching the basename, which would have been the non-renamed txt file.
Added some code to delete it now so we're sure. Looks like newer versions of calibre are more tolerant.
