### ISSUE TITLE
Importing Multiple Files into Database

### ISSUE THREAD

**Issue by mccorkled** [DobyTang/LazyLibrarian#1396]
I thought I had everything running smoothly earlier but apparently not. My database keeps adding multiple copies of the same book to the database. I deleted them and used the LL.xxxx method to add the books so that they were the same ones as Goodreads added to my database but I am still getting multiple copies.

Am I doing something wrong? I don't really have a log right now because a million processes have ran since I noticed this was happening just now. 

![1](https://user-images.githubusercontent.com/13697804/39900014-153e18b4-548d-11e8-9e27-435bcb3d3ebb.png)

![untitled](https://user-images.githubusercontent.com/13697804/39900252-7dc13f64-548e-11e8-959a-e4e2d6da8232.png)

![1](https://user-images.githubusercontent.com/13697804/39900253-7dd39a4c-548e-11e8-8862-10a4809b1652.png)

**Comment by dkids** [comment]
You need to set the status to "skipped" or "ignored" if you don't want them.   Lazy Librarian will try to grab anything labeled as "wanted".

**Comment by philborman** [comment]
Also I think there are multiple copies at goodreads, and we include them all as goodreads says they are different books. eg you have Mark Twain Adventures of Huckleberry Finn an also Mark Twain **THE** Adventures of Huckleberry Finn .  We know they are the same book, but goodreads doesn't.

**Comment by mccorkled** [comment]
Even though I only have one of then added to "to-read" at Goodreads?

**Comment by philborman** [comment]
Depends on your settings. You might have lazylibrarian set to grab all books by an author?

**Comment by mccorkled** [comment]
Where would that setting be located? After I did some more digging today it seems as though LL is adding books to my Goodreads database that I do not want. Would this be something that could happen? Goodreads was showing all of those Plato books were added to its database yesterday.

**Comment by philborman** [comment]
If you have goodreads sync enabled lazylibrarian will sync your "wanted" books and your "I have read" books with goodreads. It uses the goodreads bookid, so should only sync one copy of each book. You define the goodreads bookshelf names in config -> importing tab.
The setting for new author books is in config -> processing tab. New authors book status, and Include other books by new authors. Only used in goodreads sync if you sync an author that isn't already in lazylibrarian database
