### ISSUE TITLE
Top of the page button is missing in latest version

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1399]
Top of the page button is missing in latest version

This feature was there when you first implemented it; now it's 'gone'.

**Comment by philborman** [comment]
Should still be there, working here.
The button only appears if you scroll off the top, and is only in bookstrap interface, not legacy.

**Comment by MrMxyzptlk** [comment]
Weird it's working in Safari...must be a caching issue on my end.

**Comment by philborman** [comment]
Which browser was it failing on. Could be the code needs tweaking

**Comment by MrMxyzptlk** [comment]
Chrome latest version did not show the button.
Safari latest version showed the button.

**Comment by MrMxyzptlk** [comment]
It's definitely Chrome on one of my computers. My other computers are working fine with Chrome.

**Comment by philborman** [comment]
Could be Internet connectivity, were any other icons missing? We download the up-arrow (and all the other icons) from fontawesome. The top-of-page icon is the only thing on the box, so if there is no icon the box is almost invisible.

There is a new version of fontawesome which I can include in the next release that means we don't need to download it each time

**Comment by MrMxyzptlk** [comment]
No other anomalies.
