### ISSUE TITLE
History page blank

### ISSUE THREAD

**Issue by wizzy99** [DobyTang/LazyLibrarian#1400]
version 309e30c5014890afdd5342ec2231f305352af469
I'm not seeing anything listed on the history page.  This query does return results:
SELECT * from wanted WHERE Status != 'Skipped' and Status != 'Ignored'

**Comment by wizzy99** [comment]
If I changed the dropdown from "all" to a number things started to display, perhaps a caching issue.

**Comment by philborman** [comment]
Is it reproducible, not seeing it here.
If it's reproducible should be easy enough to track it down and fix it...

**Comment by wizzy99** [comment]
not seeing it after that initial set of attempts.  closing.
