### ISSUE TITLE
Request: Mark Banned Releases

### ISSUE THREAD

**Issue by LeeThompson** [DobyTang/LazyLibrarian#1401]
There needs to be a way to mark a particular download as bad.   Most other search tools have this feature.  (If LL already has it, it's very well hidden.)

**Comment by philborman** [comment]
We use the history table for this. 
Anything marked as Failed in the history is blacklisted and won't be tried again.

**Comment by philborman** [comment]
I agree, but how do you know what to ban? 
In situations like that you can manually select the right one to download from the eBook or AudioBook pages (click Manual under the book title and use the Searches dropdown)

**Comment by LeeThompson** [comment]
Hmm that might work, I'll check that out.

**Comment by philborman** [comment]
Would be fairly easy to use the successful entries in the history table items as a blacklist too, so if you mark the same book as "wanted" again we will retry for a different copy, but you could end up having several downloads you don't want until you finally get the one you want. I think I prefer the manual option.
