### ISSUE TITLE
ImportCSV problems

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1402]
Before the option to delete the CSV file, I had several "Best of Young Adult 2017" lists.   They didn't seem to be imported, so I cat'd them together in one list to make it easier for me to track.

You added the option to delete the CSV file but somehow it never got to the end.   So I split the big (several hundred lines) back into individual files of 100 lines to see if that would help.

I do see that CSV says it is already importing.

If I push "Import CSV" it alternates between "IMPORTCSV already running" and 
"Importing books (background task) from /Users/kids/file"

The log where it seems to get stuck:

12-May-2018 14:34:47 - DEBUG   :: IMPORTCSV : librarysync.py:find_book_in_db:170 : Searching database for [Flicker and Mist] by [Mary G. Thompson]
12-May-2018 14:34:47 - DEBUG   :: IMPORTCSV : librarysync.py:find_book_in_db:176 : Exact match [Flicker and Mist]
12-May-2018 14:34:47 - INFO    :: IMPORTCSV : csvfile.py:import_CSV:338 : Found book Flicker and Mist by Mary G. Thompson, already marked as "Wanted"
12-May-2018 14:34:47 - DEBUG   :: IMPORTCSV : csvfile.py:import_CSV:319 : CSV: Author Crystal King found in database
12-May-2018 14:34:47 - DEBUG   :: IMPORTCSV : librarysync.py:find_book_in_db:170 : Searching database for [Feast of Sorrow] by [Crystal King]
12-May-2018 14:34:47 - DEBUG   :: IMPORTCSV : librarysync.py:find_book_in_db:176 : Exact match [Feast of Sorrow]
12-May-2018 14:34:47 - INFO    :: IMPORTCSV : csvfile.py:import_CSV:338 : Found book Feast of Sorrow by Crystal King, already marked as "Wanted"
12-May-2018 14:34:47 - INFO    :: IMPORTCSV : csvfile.py:import_CSV:372 : Added 0 new authors, marked 0 books as 'Wanted', 1 book not found

An extract from the CSV file:

"Fangirl","Rainbow Rowell"
"Far from the Tree","Robin Benway"
"Fawkes","Nadine Brandes"
"Feast of Sorrow","Crystal King"
"Feed","Mira Grant"
"Feversong","Karen Marie Moning"

I'm not sure why "Flicker" is coming before "Feast".   I would expect LL to read the file sequentially and I had sorted this alphabetically.

[csv.txt](https://github.com/DobyTang/LazyLibrarian/files/1997990/csv.txt)

I did think that the process was hung but it seems to have restarted after an hour.

**Comment by dkids** [comment]
By the way, both authors (Crystal King where it seems to hang and the next author Mira Grant) are in LL's database.  I would expect the process to be really quick - this one is here, next one, this one is here, etc.

**Comment by philborman** [comment]
Yes it's normally really quick unless it needs to import an author.
It looks as though the import csv routine is aborting after Feast of Sorrow, either a crash, or it thinks it's reached the end of the list?   Can you check your csv file is ok, particularly around the Feast of Sorrow line. Also the log seems to show trying to import an author called "Author" which is a column header.

**Comment by dkids** [comment]
CSV file looks good to me.   The only "issue" I can see is that the first line is title,author rather than "title","author".   I've attached it.

[xac.csv.txt](https://github.com/DobyTang/LazyLibrarian/files/1998636/xac.csv.txt)

GitHub wouldn't take xac.csv so I had to rename it to xac.csv.txt.

I ran it through csvlint.io and it said this:
https://csvlint.io/validation/5af85ed75b514f0004000011


Structural problem: Assumed header

As there is no machine readable way to tell if your CSV has a header row, we have assumed that your CSV has one.

Structural problem: Non-standard Line Breaks on row 1

Your CSV appears to use LF line-breaks. While this will be fine in most cases, RFC 4180 specifies that CSV files should use CR-LF (a carriage-return and line-feed pair, e.g. \r\n). This may be labelled as "Windows line endings" on some systems.

The one thing that jumped out on http://www.convertcsv.com/csv-viewer-editor.htm was that there was "Freedom" with a trademark sign after for a title.   If you're just looking for ASCII?

**Comment by dkids** [comment]
Tried removing that line and it didn't make a difference.   Renamed xac.csv to xx.csv and import started on xad.csv but seems to have hung.

13-May-2018 09:06:16 - INFO    :: IMPORTCSV : csvfile.py:import_CSV:338 : Found book Keeper/Finder by Greg Rucka, already marked as "Wanted"
13-May-2018 09:06:16 - DEBUG   :: IMPORTCSV : csvfile.py:import_CSV:319 : CSV: Author Samira Ahmed found in database
13-May-2018 09:06:16 - DEBUG   :: IMPORTCSV : librarysync.py:find_book_in_db:170 : Searching database for [Love, Hate & Other Filters] by [Samira Ahmed]
13-May-2018 09:06:16 - DEBUG   :: IMPORTCSV : librarysync.py:find_book_in_db:176 : Exact match [Love, Hate & Other Filters]
13-May-2018 09:06:16 - INFO    :: IMPORTCSV : csvfile.py:import_CSV:338 : Found book Love, Hate & Other Filters by Samira Ahmed, already marked as "Open"
13-May-2018 09:06:16 - DEBUG   :: IMPORTCSV : csvfile.py:import_CSV:319 : CSV: Author Pierce Brown found in database
13-May-2018 09:06:16 - DEBUG   :: IMPORTCSV : librarysync.py:find_book_in_db:170 : Searching database for [Morning Star] by [Pierce Brown]
13-May-2018 09:06:16 - DEBUG   :: IMPORTCSV : librarysync.py:find_book_in_db:176 : Exact match [Morning Star]
13-May-2018 09:06:16 - INFO    :: IMPORTCSV : csvfile.py:import_CSV:338 : Found book Morning Star by Pierce Brown, already marked as "Open"
13-May-2018 09:06:16 - INFO    :: IMPORTCSV : csvfile.py:import_CSV:372 : Added 0 new authors, marked 0 books as 'Wanted', 1 book not found
[xad.csv.txt](https://github.com/DobyTang/LazyLibrarian/files/1998652/xad.csv.txt)

**Comment by philborman** [comment]
Hmm, just tried importing your csv file xac.csv and it all seemed to work ok. Final book was Feast of Sorrow.

13-May-2018 21:09:47 - INFO :: IMPORTCSV : csvfile.py:import_CSV:358 : Found (100% 95%) Crystal King: Feast of Sorrow: A Novel of Ancient Rome
13-May-2018 21:09:47 - INFO :: IMPORTCSV : csvfile.py:import_CSV:377 : Added 94 new authors, marked 98 books as 'Wanted', 2 books not found

No idea why it processes them in the order it does, we use a standard python library routine to import the csv file and the order books are processed in does not match the order in the csv file, but they all got processed.  Also the thread that prints the "Added 94 new authors" line above may complete earlier than the final author import, so it may not be at the very end of the log. From what I can see I'm not sure it's actually failing or hanging, the out-of-order importing and out-of -order loglines are maybe confusing things. The csv file isn't deleted at the end if there are any books not found. This behaviour could be changed. Can you check your logfiles for lines showing the 'marked as "Wanted"' or 'marking as "Wanted"' lines, probably all is ok...

**Comment by dkids** [comment]
Attached are 3 files.   One (csv_with_dates.txt) is from pressing Import CSV and then grepping for IMPORTCSV in the log.   Interestingly it says "99 books" but when I do 
wc ~/Dropbox/lldata/xad.csv 
     101     381    3440 /Users/kids/Dropbox/lldata/xad.csv
I did a sort and inspected it but there do seem to be 101 lines.

grep IMPORTCSV * | cut -f 10 -d: | sort -u > ~/csv_no_dates.txt.  Not sure it helps to see all messges but maybe something in there is unusual.

There's got to be a better way to search the files in order but I used "for i in lazylibrarian.log lazylibrarian.log.? lazylibrarian.log.1? lazylibrarian.log.2? lazylibrarian.log.3? lazylibrarian.log.4? lazylibrarian.log.5? lazylibrarian.log.6? lazylibrarian.log.7? lazylibrarian.log.8? lazylibrarian.log.9?         ; do grep IMPORTCSV $i > ~/csv_real_bigtxt; echo $i; done" to get the log files 
[csv_no_dates.txt](https://github.com/DobyTang/LazyLibrarian/files/1999128/csv_no_dates.txt)
[csv_real_big.txt](https://github.com/DobyTang/LazyLibrarian/files/1999129/csv_real_big.txt)
[csv_with_dates.txt](https://github.com/DobyTang/LazyLibrarian/files/1999130/csv_with_dates.txt)

I

**Comment by philborman** [comment]
Ok I will take a look.
For reference, I would use the lazylibrarian logfile creator to make it easier to trace. Open one tab on the lazylibrarian Manage page, and a second tab in your browser on the lazylibrarian logs page, make sure the button at the top of the log page says [Start Debug Log]  If it says [Stop Debug Log] then click it so it's ready to start a new log. Once all set to go, click [Start Debug Log], if you need a loglevel > 2 go to config and set the new level, then switch to the manage page and click [Import CSV]

Once the import has completed (you can watch the log page with refresh on for this) click [Save Debug Log]

This will create a debug.zip with all the lines generated since you last pressed [Start Debug Log] and all the passwords etc will be stripped out. Also includes basic info on your system (software versions etc) the same info displayed when you click [System Info] in config.

**Comment by philborman** [comment]
Ok, found the numbering issue, needs some work... 
csv file is 101 lines long, correct, but contains a header line plus 100 books
We only get 99 as "Inferno" is in the list twice, and gets treated as a duplicate when it shouldn't 
(same title, but different author).  The csv reader code is way too complicated and can be simplified quite a lot, as long as I don't break anything in the process!   Will report back later.

**Comment by dkids** [comment]
There seems to be an issue if a book is not found.  When that happens, the CSV file is not deleted.   That might be the right behavior but it would be nice if the error was made more visible.   

The list I was converting from html to csv used "title by author" and I substituted " by ".  The problem was, a couple of the titles had " by " in the title.

Title,Author
"The Shadows We Know","Heart by Jennifer Park"

Attached log file for this book: 
[heart.txt](https://github.com/DobyTang/LazyLibrarian/files/2002749/heart.txt)

Same deal:
"Title","Author"
"Freed","Flame and Storm by Becky Allen"

log file: 
[flame.txt](https://github.com/DobyTang/LazyLibrarian/files/2002751/flame.txt)

This author wasn't found at all:
Title,Author
"In Pursuit of Spenser","Otto Penzler"

[penzler.txt](https://github.com/DobyTang/LazyLibrarian/files/2002753/penzler.txt)

**Comment by philborman** [comment]
> There seems to be an issue if a book is not found. When that happens, the CSV file is not deleted. That might be the right behavior but it would be nice if the error was made more visible.

Yes that's intentional, but could be changed. I think if there is an error we should leave the file giving you a chance to correct it and retry?  I have added an extra warning message now.

The ones with "by" issues I don't think there is much we can do about, the csv file needs to be corrected.

The Otto Penzler book...
14-May-2018 14:39:14 - WARNING :: IMPORTCSV : csvfile.py:import_CSV:361 : Skipping book In Pursuit of Spenser by Otto Penzler, No match found
14-May-2018 14:39:14 - WARNING :: IMPORTCSV : csvfile.py:import_CSV:364 : Closest match (100% 87%) Otto Penzler: In Pursuit of Spenser: Mystery Writers on Robert B. Parker and the Creation of an American Hero

100% match on author but only 87% on title because of all the extra words. If you edit the books database entry so the [Mystery Writers on Robert B. Parker and the Creation of an American Hero
]  part is subtitle it will match properly, or if you drop your match threshold in config to 87% that will do it too. It's the config->processing tab [Download Match Ratio].   

There is some code in lazylibrarian that should split the title: subtitle when we first import Otto Penzler. Maybe that section of code gets bypassed on importing from csv, will have to check.

**Comment by dkids** [comment]
There seems to be an issue if a book is not found.  When that happens, the CSV file is not deleted.   That might be the right behavior but it would be nice if the error was made more visible.   

The list I was converting from html to csv used "title by author" and I substituted " by ".  The problem was, a couple of the titles had " by " in the title.

Title,Author
"The Shadows We Know","Heart by Jennifer Park"

Attached log file for this book: 
[heart.txt](https://github.com/DobyTang/LazyLibrarian/files/2002749/heart.txt)

Same deal:
"Title","Author"
"Freed","Flame and Storm by Becky Allen"

log file: 
[flame.txt](https://github.com/DobyTang/LazyLibrarian/files/2002751/flame.txt)

This author wasn't found at all:
Title,Author
"In Pursuit of Spenser","Otto Penzler"

[Uploading penzler.txt…]()

**Comment by philborman** [comment]
I think the Otto Penzler issue is fixed now, just need to run a few more tests overnight before releasing it.
Can't do anything about the incorrect entries in the csv file, I think you might need to hand edit that.

**Comment by philborman** [comment]
FYI, send is very good at the sort of substitution you are trying to do. To replace the last occurrence of " by " in a string...
cat file.csv | sed - e 's/\(.*\) by /\1 /'
