### ISSUE TITLE
Can't unmatch book

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1403]
Repo: https://github.com/dobytang/lazylibrarian : Branch: master : Updated: Thu May 10 02:28:31 2018
Current Version: 309e30c5014890afdd5342ec2231f305352af469 : Latest Version: 309e30c5014890afdd5342ec2231f305352af469

MacOS 10.13.4
![screenshot-2018-5-12 lazylibrarian - laini taylor](https://user-images.githubusercontent.com/30055574/39962871-af565f04-5610-11e8-99f9-10978c4288f0.png)

I've tried marking the book with 14 chapters as "skipped", "ignored" and "removed", then running "ebook match".   Each time the book with 14 chapters is matched and the book I want selected stays stuck on "Wanted".   I have looked at the book to make sure it's the full version.

I have the same problem with another book, 1491.   The Goodreads title is "Before Columbus: The Americas of 1491".   I did the same things, marking the Before Columbus book as "skipped", "ignored", and "removed".   I also edited the title to "Before Columbus" and removed the subtitle to give LL less to match on, then repeated marking it.   Still, it locks onto the wrong title.

![screenshot-2018-5-12 lazylibrarian - charles c mann](https://user-images.githubusercontent.com/30055574/39962908-f6a10b6a-5611-11e8-983d-27a16596cd8e.png)

tail -f lazylibrarian.log | grep Before
12-May-2018 18:25:19 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:445 : [/Users/kids/Calibre/Charles C. Mann] Now scanning subdirectory /1491_ New Revelations of the Americas Before Columbus (3865)
12-May-2018 18:25:19 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:479 : book meta [9781400040063] [en] [Charles C. Mann] [1491: New Revelations of the Americas Before Columbus] [mobi]
12-May-2018 18:25:19 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:511 : file meta [9781400040063] [eng] [Charles C. Mann] [1491: New Revelations of the Americas Before Columbus] []
12-May-2018 18:25:19 - DEBUG   :: AUTHOR_SCAN : librarysync.py:find_book_in_db:170 : Searching database for [1491: New Revelations of the Americas Before Columbus] by [Charles C. Mann]
12-May-2018 18:25:19 - DEBUG   :: AUTHOR_SCAN : librarysync.py:find_book_in_db:204 : Searching 8 books by [Charles C. Mann] in database for [1491: New Revelations of the Americas Before Columbus]
12-May-2018 18:25:19 - DEBUG   :: AUTHOR_SCAN : librarysync.py:find_book_in_db:255 : Fuzz match partial [94] [1491: New Revelations of the Americas Before Columbus] [Before Columbus]
12-May-2018 18:25:19 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:796 : Librarysync link to preferred type mobi: /Users/kids/Calibre/Charles C. Mann/1491_ New Revelations of the Americas Before Columbus (3865)/1491_ New Revelations of the Americas Befo - Charles C. Mann.mobi

grep Daughter lazylibrarian.log 
12-May-2018 18:27:23 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:445 : [/Users/kids/Calibre/Laini Taylor] Now scanning subdirectory /Daughter of Smoke and Bone (7139)
12-May-2018 18:27:23 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:479 : book meta [] [en] [Laini Taylor] [Daughter of Smoke and Bone] [epub]
12-May-2018 18:27:23 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:511 : file meta [] [eng] [Laini Taylor] [Daughter of Smoke and Bone] []
12-May-2018 18:27:23 - DEBUG   :: AUTHOR_SCAN : librarysync.py:find_book_in_db:170 : Searching database for [Daughter of Smoke and Bone] by [Laini Taylor]
12-May-2018 18:27:24 - DEBUG   :: AUTHOR_SCAN : librarysync.py:find_book_in_db:176 : Exact match [Daughter of Smoke and Bone]
12-May-2018 18:27:24 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:796 : Librarysync link to preferred type mobi: /Users/kids/Calibre/Laini Taylor/Daughter of Smoke and Bone (7139)/Daughter of Smoke and Bone - Laini Taylor.mobi
12-May-2018 18:27:24 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:445 : [/Users/kids/Calibre/Laini Taylor] Now scanning subdirectory /Daughter of Smoke and Bone (7139)
12-May-2018 18:27:24 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:479 : book meta [] [en] [Laini Taylor] [Daughter of Smoke and Bone] [mobi]
12-May-2018 18:27:24 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:511 : file meta [] [eng] [Laini Taylor] [Daughter of Smoke and Bone] []
12-May-2018 18:27:24 - DEBUG   :: AUTHOR_SCAN : librarysync.py:find_book_in_db:170 : Searching database for [Daughter of Smoke and Bone] by [Laini Taylor]
12-May-2018 18:27:24 - DEBUG   :: AUTHOR_SCAN : librarysync.py:find_book_in_db:176 : Exact match [Daughter of Smoke and Bone]
12-May-2018 18:27:24 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:796 : Librarysync link to preferred type mobi: /Users/kids/Calibre/Laini Taylor/Daughter of Smoke and Bone (7139)/Daughter of Smoke and Bone - Laini Taylor.mobi
12-May-2018 18:27:46 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:445 : [/Users/kids/Calibre/Laini Taylor] Now scanning subdirectory /Daughter of Smoke and Bone (7139)
12-May-2018 18:27:46 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:479 : book meta [] [en] [Laini Taylor] [Daughter of Smoke and Bone] [epub]
12-May-2018 18:27:46 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:511 : file meta [] [eng] [Laini Taylor] [Daughter of Smoke and Bone] []
12-May-2018 18:27:46 - DEBUG   :: AUTHOR_SCAN : librarysync.py:find_book_in_db:170 : Searching database for [Daughter of Smoke and Bone] by [Laini Taylor]
12-May-2018 18:27:46 - DEBUG   :: AUTHOR_SCAN : librarysync.py:find_book_in_db:176 : Exact match [Daughter of Smoke and Bone]
12-May-2018 18:27:46 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:796 : Librarysync link to preferred type mobi: /Users/kids/Calibre/Laini Taylor/Daughter of Smoke and Bone (7139)/Daughter of Smoke and Bone - Laini Taylor.mobi
12-May-2018 18:27:46 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:445 : [/Users/kids/Calibre/Laini Taylor] Now scanning subdirectory /Daughter of Smoke and Bone (7139)
12-May-2018 18:27:46 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:479 : book meta [] [en] [Laini Taylor] [Daughter of Smoke and Bone] [mobi]
12-May-2018 18:27:46 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:511 : file meta [] [eng] [Laini Taylor] [Daughter of Smoke and Bone] []
12-May-2018 18:27:46 - DEBUG   :: AUTHOR_SCAN : librarysync.py:find_book_in_db:170 : Searching database for [Daughter of Smoke and Bone] by [Laini Taylor]
12-May-2018 18:27:46 - DEBUG   :: AUTHOR_SCAN : librarysync.py:find_book_in_db:176 : Exact match [Daughter of Smoke and Bone]
12-May-2018 18:27:46 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:796 : Librarysync link to preferred type mobi: /Users/kids/Calibre/Laini Taylor/Daughter of Smoke and Bone (7139)/Daughter of Smoke and Bone - Laini Taylor.mobi

**Comment by philborman** [comment]
The first book, Before Columbus  looks like the fuzzy logic is letting us down. There isn't an exact match for 1491: New Revelations of the Americas Before Columbus, and "Before Columbus" is a better partial match than "1491" as more words match. 
The second one, Daughter of Smoke and Bone  you have two equally good matches in the database (exact match on title) so we don't know which to pick.

I think not matching to "Ignored" books is maybe the solution here, but need to allow for the cases where the book _only_ matches an ignored one, eg where the only goodreads entry says it's unknown language but we have the book, so we want to include it. We need to un-ignore it then.

**Comment by philborman** [comment]
Ok, this should be in the next release, probably tomorrow. A few more bits to test first - not this change, it was fairly trivial, but there are quite a few other additions in the next release.

**Comment by dkids** [comment]
That sounds reasonable.   Looking forward to seeing the next version.

**Comment by dkids** [comment]
Works great!   Was able to ignore the books I didn't want matched and eBook scan matched the ones that I did.
