### ISSUE TITLE
Way to add book?

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1404]
grep -i "failed to match" *log.2?
lazylibrarian.log.21:12-May-2018 08:05:12 - WARNING :: AUTHOR_SCAN : librarysync.py:LibraryScan:875 : Failed to match book [Kings Curse] by [Warren Murphy] in database

Calibre matches it.

There's an entry on Goodreads for it. The entry seems fine, showing many, many books from this author.

I did "refresh author" and while it pulled in a couple more books, it didn't pull in this one.

It'd be nice if the book were found.    Failing that, it would be nice to have an "Add Book" button on the author's page that would let people add an ISBN number or Goodreads URL or something similar.

https://www.goodreads.com/book/show/2761593-king-s-curse?ac=1&from_search=true
![screenshot-2018-5-12 king s curse the destroyer 24](https://user-images.githubusercontent.com/30055574/39963409-44b93b1c-561f-11e8-91b7-1934a13886f6.png)

**Comment by philborman** [comment]
Couple of options...
Is Kings Curse in your lazylibrarian database under Warren Murphy page?
If not then we need to look into why we didn't import it in` import author
`
If it's there, we need to look into why we didn't match it in `librarysync`

**Comment by dkids** [comment]
It's there now.   The log says it's continuing to complain about there not being a publication date.   I do have this in config:

[ ] Ignore books with future publication date
[x] Ignore books with unknown publication date
[x] Ignore books with no isbn 

https://www.goodreads.com/book/show/2761593-king-s-curse?from_search=true says it was:
Published December 23rd 2002 by e-reads.com (first published January 1st 1976) 

Not sure why it was added.   I've attached the chronological results of grepping through the log files.

[kings_curse.txt](https://github.com/DobyTang/LazyLibrarian/files/1999168/kings_curse.txt)


grep King * | grep Curse | cut -f10 -d: | sort -u
 Book found
 CacheHandler
 Failed to match book [Kings Curse] by [Warren Murphy] in database
 Fuzz failed [Warren Murphy - Kings Curse] ratio [60,Kill or Cure], partial [64,Survival Course], partname [0,]
 Fuzz match partial [97] [Kings Curse] [King's Curse (The Destroyer, #24)]
 GoodReads doesn't know about Kings Curse
 Librarysync link to preferred type mobi
 Rejecting King's Curse (The Destroyer, #24), no publication date
 Rejecting bookid 39895723 for [Gena Showalter][Heart Of The Dragon/Jewel Of Atlantis/The Nymph King/The Vampire's Bride/The Amazon's Curse] already got this book in database
 Searching 172 books by [Warren Murphy] in database for [Kings Curse]
 Searching 188 books by [Warren Murphy] in database for [Kings Curse]
 Searching database for [Kings Curse] by [Warren Murphy]
 Updated cover for Heart Of The Dragon/Jewel Of Atlantis/The Nymph King/The Vampire's Bride/The Amazon's Curse using cache
 Updated cover for King's Curse (The Destroyer, #24) using cache
 Warren Murphy Kings Curse matched Ignored BookID 2761593, [Warren Murphy][King's Curse (The Destroyer, #24)]
 [/Users/kids/Calibre/Warren Murphy] Now scanning subdirectory /King's Curse (9054)
 [/Users/kids/Calibre] Now scanning subdirectory /Warren Murphy/King's Curse (9054)
 [Gena Showalter] Updated book
 [None] Updated book
 [Stephen King] Updated book
 [Warren Murphy] Updated book
 book meta [] [en] [Richard Sapir] [King's Curse] [mobi]
 file meta [] [eng] [Warren Murphy] [King's Curse] []

**Comment by dkids** [comment]
Oh, I was doing "grep -i King | grep -i Curse" and that's why the noise crept in there.   I remember the "'" as causing some grief and was trying to avoid it since LL might swallow it.

**Comment by philborman** [comment]
It looks like the 
Fuzz match partial [97] [Kings Curse] [King's Curse (The Destroyer, #24)]
GoodReads doesn't know about Kings Curse
comes from the series matching code, but the latest release probably fixes the issue as a side-effect of the way we now handle ignored books.
