### ISSUE TITLE
LL grabbing wrong cover

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1407]
The book is 
Golden Country (Pegasus, #3), The by Robin McKinley

![screenshot-2018-5-15 lazylibrarian - robin mckinley](https://user-images.githubusercontent.com/30055574/40073645-45dc9994-582c-11e8-8979-300612452749.png)

![screenshot-2018-5-15 the golden country pegasus 3](https://user-images.githubusercontent.com/30055574/40073383-88359346-582b-11e8-8dfe-f50816e7e35f.png)

The cover is of The Subtle Knife by Philip Pullman.

The publication date is not visible.   I searched for "0000" and didn't find it.   I assume that LL is using that when it can't find a publication date.

Goodreads refers to https://s.gr-assets.com/assets/nophoto/book/blank-133x176-8b769f39ba6687a82d2eef30bdf46977.jpg  

Another example where the author is the same but the title is different is Ember Days by Alexandra Duncan.
![screenshot-2018-5-15 lazylibrarian - alexandra duncan](https://user-images.githubusercontent.com/30055574/40073415-9c6abf08-582b-11e8-8bde-9a88fc1a599b.png)

This is pretty common for books with future publication dates to have an image of the cover of another book.  It's a minor issue but seems like it would be better to have blank than a wrong cover.

**Comment by dkids** [comment]
By the way, I don't know why LL grabbed a different author but I assume it has something to do with the various lists that GoodReads puts on the page.   Guessing that it's looking for the first image that matches certain parameters.   Same for different book by same author.

**Comment by philborman** [comment]
Yes we use 0000 as a numeric placeholder for unknown dates. 

Have a look at the "manual" page for the books with the wrong cover. At the bottom of the page is a set of available covers, one of which is the wrong one we grabbed. My guess is it's a googleimage cover. 
We try several sources for a book cover, the very last one if all else fails is a googleimage search. google always gives you some results even if it can't find the cover you want. You can disable googleimage in lazylibrarian config->importing.  It will still be available as an option, just not an automatic choice.

**Comment by dkids** [comment]
I've turned off googleimage search because I'd prefer no data to wrong data.   That might not be the right choice for everybody.

Calibre searches Amazon, Google Books, Google, Open Library, and Overdrive and has plugins for Barnes & Noble and GoodReads.  I'm having good luck (95%) with it matching on "download metadata and covers" but sometimes I need to reject what it finds (it finds the wrong book in a series, etc.) and try for it individually.

**Comment by philborman** [comment]
We try  1. Local file cached from goodreads/googlebooks when book was imported
            2. cover.jpg if we have the book
            3. LibraryThing cover image (if you have a dev key)
            4. LibraryThing whatwork (if available)
            5. Goodreads search (if book was imported from goodreads)
            6. Google Books isbn search (if google has a link to book for sale)
            7. Google images search (if lazylibrarian config allows)

May be interesting to add Amazon, Open Library, Overdrive, Barnes & Noble at some point, but not a priority.
