### ISSUE TITLE
Feature idea : Select torrent manually

### ISSUE THREAD

**Issue by cdancette** [DobyTang/LazyLibrarian#1412]
In sonarr, it's possible to do a manual search, and to choose the torrent we want in all results. It would be nice to have this here too (sometimes the automatic search doesn't choose the best download).

**Comment by philborman** [comment]
On the ebooks page under each book title are some buttons

Click on Manual and you get  page where you can edit some details, change cover, etc. At the top of the page is a searchbox for selecting a manual download for that book

**Comment by cdancette** [comment]
thanks, I didn't notice it ! very nice.
