### ISSUE TITLE
"Add book" has problems

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1413]
From the home page, I normally search for an author.   The screen refreshes and there's "null" where the author's name should be.   I click on that (null) to open in a new tab.   When the author information is done, then I can set the books I want to "wanted".

This morning I tried "Add book" instead.   If I click on "Have Author", the URL is 

http://localhost:5299/authorPage?AuthorID=16551933
generates a 500 error

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/Users/kids/src/LazyLibrarian-master/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/Users/kids/src/LazyLibrarian-master/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Users/kids/src/LazyLibrarian-master/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Users/kids/src/LazyLibrarian-master/lazylibrarian/webServe.py", line 1222, in authorPage
    authorname = authorname.encode(lazylibrarian.SYS_ENCODING)
AttributeError: 'NoneType' object has no attribute 'encode'

If I click on "Wanted", the URL is http://localhost:5299/searchForBook?bookid=34836529 but it takes me to http://localhost:5299/authorPage?AuthorID=15802333

The same happens with 

Have Author: http://localhost:5299/authorPage?AuthorID=168148
Wanted: http://localhost:5299/searchForBook?bookid=19186358 but end up on
http://localhost:5299/authorPage?AuthorID=5446656

Obviously the AuthorID is different.

Logs: 
> grep Anderson
16-May-2018 09:10:18 - DEBUG   :: GR-BOOK : gr.py:find_author_id:245 : Searching for author with name: Tim Anderson
16-May-2018 09:10:18 - DEBUG   :: GR-BOOK : cache.py:get_cached_request:193 : CacheHandler: Storing XML bff3184da22187c7fc2c32cf03219070 for https://www.goodreads.com/api/author_url/Tim%20Anderson?key=6oGI3b4XYCntXDtsh0aNA
16-May-2018 09:10:20 - DEBUG   :: GR-BOOK : gr.py:get_author_info:300 : [Tim  Anderson] Processing info for authorID: 5446656
16-May-2018 09:10:20 - DEBUG   :: GR-BOOK : gr.py:get_author_books:398 : GoodReads author name [Tim Anderson]
16-May-2018 09:10:23 - DEBUG   :: GR-BOOK : images.py:getBookCover:285 : Caching goodreads cover for Tim Anderson Sweet Tooth: A Memoir
16-May-2018 09:10:29 - INFO    :: GR-BOOK : gr.py:find_book:1000 : Nanban by Tim Anderson added to the books database
16-May-2018 09:10:31 - DEBUG   :: GR-BOOK : images.py:getBookCover:285 : Caching goodreads cover for Tim Anderson Nanban
16-May-2018 09:10:51 - DEBUG   :: ADDAUTHOR : gr.py:get_author_info:300 : [Tim Anderson] Processing info for authorID: 168148

> grep Japanese
16-May-2018 09:10:14 - WARNING :: GR-BOOK : gr.py:find_book:890 : Book The Ultimate Japanese Cookbook: Japanese Food for the Soul from the Best Japanese Restaurants goodreads language does not match preference, Unknown
16-May-2018 09:10:14 - WARNING :: GR-BOOK : gr.py:find_book:899 : Book The Ultimate Japanese Cookbook: Japanese Food for the Soul from the Best Japanese Restaurants Publication date does not match preference, 0000
16-May-2018 09:10:18 - WARNING :: GR-BOOK : gr.py:find_book:890 : Book Nanban: Japanese Soul Food goodreads language does not match preference, Unknown
16-May-2018 09:10:44 - DEBUG   :: GR-BOOK : bookwork.py:isbn_from_words:802 : No ISBN found for The Ultimate Japanese Cookbook Daniel Humphreys
16-May-2018 09:10:44 - INFO    :: GR-BOOK : gr.py:find_book:1000 : The Ultimate Japanese Cookbook by Daniel Humphreys added to the books database
16-May-2018 09:10:45 - DEBUG   :: GR-BOOK : images.py:getBookCover:285 : Caching goodreads cover for Daniel Humphreys The Ultimate Japanese Cookbook
16-May-2018 09:10:45 - DEBUG   :: GR-BOOK : gr.py:find_book:1006 : Updated cover for The Ultimate Japanese Cookbook using goodreads

> grep Humphreys
16-May-2018 09:10:14 - DEBUG   :: GR-BOOK : gr.py:find_author_id:245 : Searching for author with name: Daniel Humphreys
16-May-2018 09:10:15 - DEBUG   :: GR-BOOK : cache.py:get_cached_request:193 : CacheHandler: Storing XML 3c53edd396035b4eb97b9fc78e550626 for https://www.goodreads.com/api/author_url/Daniel%20Humphreys?key=6oGI3b4XYCntXDtsh0aNA
16-May-2018 09:10:17 - DEBUG   :: GR-BOOK : gr.py:get_author_info:300 : [Daniel  Humphreys] Processing info for authorID: 15802333
16-May-2018 09:10:18 - DEBUG   :: GR-BOOK : gr.py:get_author_books:398 : GoodReads author name [Daniel Humphreys]
16-May-2018 09:10:28 - DEBUG   :: GR-BOOK : images.py:getBookCover:285 : Caching goodreads cover for Daniel Humphreys A Place Called Hope (Z-Day, #2)
16-May-2018 09:10:36 - DEBUG   :: GR-BOOK : images.py:getBookCover:285 : Caching goodreads cover for Daniel Humphreys MAGA 2020 & Beyond
16-May-2018 09:10:44 - DEBUG   :: GR-BOOK : bookwork.py:isbn_from_words:802 : No ISBN found for The Ultimate Japanese Cookbook Daniel Humphreys
16-May-2018 09:10:44 - INFO    :: GR-BOOK : gr.py:find_book:1000 : The Ultimate Japanese Cookbook by Daniel Humphreys added to the books database
16-May-2018 09:10:45 - DEBUG   :: GR-BOOK : images.py:getBookCover:285 : Caching goodreads cover for Daniel Humphreys The Ultimate Japanese Cookbook
16-May-2018 09:10:49 - DEBUG   :: ADDAUTHOR : gr.py:get_author_info:300 : [Daniel Humphreys] Processing info for authorID: 16551933

**Comment by dkids** [comment]
Looks like when I do "Add Book" rather than "Add Author" it keeps the "null" entries in the database.   See screenshot.

![screenshot-2018-5-16 lazylibrarian - authors](https://user-images.githubusercontent.com/30055574/40146337-02302a5a-591a-11e8-8f28-68bfcd00eb23.png)

**Comment by philborman** [comment]
Should stay like that until author is loaded, then update the details. We just need to stop redirecting to that page until it's complete. Haven't had a chance to look at it today though.

**Comment by dkids** [comment]
OK, thanks for the explanation.   I didn't realize that was expected behavior.

**Comment by philborman** [comment]
The null name dates and picture are expected, but could be changed so it updates sooner I think. And I think we should disable the (add book) button while the author is loading. Might get a chance to look at this tomorrow

**Comment by philborman** [comment]
Think this should be sorted now, you should not be able to see any [add book] buttons while the author is loading, and the null authorname and cover should update faster, you maybe won't even have time to see them :-)
