### ISSUE TITLE
Feature Request: Growl Notifications

### ISSUE THREAD

**Issue by LeeThompson** [DobyTang/LazyLibrarian#1420]
I use Growl on my LAN for notifications since it doesn't require the use of a third party service, it would be great if Lazy Librarian supported it.

(I know it's an older protocol and isn't as popular as it once was.)

**Comment by LeeThompson** [comment]
Not working but it MAY be the docker container missing stuff.

**Comment by philborman** [comment]
Probably is the docker. It's certainly working here
![screenshot from 2018-05-19 08-53-55](https://user-images.githubusercontent.com/12158777/40265957-588e9790-5b42-11e8-9eb6-dfe89639b4f8.png)
The docker will need access to the port you talk to growl on. Default is 23053. Might be as simple as adding another -p option to the docker parameters, or can you try without docker?

**Comment by LeeThompson** [comment]
It's working now.  Oddly if I specify the port (192.168.0.17:23053 it fails, if I just put in the address, it works.)

**Comment by philborman** [comment]
That is odd. Will look into it.
