### ISSUE TITLE
Question about Upload books

### ISSUE THREAD

**Issue by davydov-vyacheslav** [DobyTang/LazyLibrarian#1421]
Hi,

Documentation says (as far as I understood) that the only easy way to add book - it to configure torrent system.

According to this I have 2 questions:
- is there a way to set custom .torrent file for book (e.g. I did manually found the torrent file for book and I'd like to upload it) ?
- is there a way to upload custom book?

Thanks,
Slava

**Comment by dkids** [comment]
If you have a library of existing books, you can set this under Config, Processing.  It's the eBook Library Folder setting.

LazyLibrarian seems to work off GoodReads or GoogleBooks.   At this point, there doesn't seem to be a way to add your own books.

**Comment by davydov-vyacheslav** [comment]
thank you for your reply.
Is there plans to add such feature?

(anyway, you can close the issue, if it isn't consistent to current architecture)

**Comment by dkids** [comment]
I don't know if there are such plans.   I'm not one of the programmers.

I do think that it would be good to have such capacity for books that aren't on GoodReads for whatever reason: printed before ISBN numbers, foreign language, unofficial (I have an epub file that is 36 short stories collected together but it was never published that way), etc.

Plex serves TV and Movies but also can serve home movies.   I see something like that as being one possibility for LL but I don't know how many people will want it.

**Comment by philborman** [comment]
Possible to add a special category for books not found on goodreads/googlebooks.
Would need the user to manually enter author/title/cover/maybe other details or supply an .opf file and cover image. Not sure how useful it would be.
