### ISSUE TITLE
Be able to delete author's picture from author's page

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1427]
I don't have a better picture and I don't really care but it bothers me that there's a man's picture for a female author.   So I'd like to just delete it and have a blank or maybe the author's name in the box.
![screenshot-2018-5-19 lazylibrarian - edit author](https://user-images.githubusercontent.com/30055574/40273615-0c72ee3e-5b78-11e8-86cf-fecf8ba74f7b.png)

**Comment by philborman** [comment]
You could put the /full/path/to/lazylibrarian/data/images/nophoto.png
I could add a shortcut button for this maybe, or authors name as you suggest.

**Comment by philborman** [comment]
In the next release of lazylibrarian you can out the word "none" for the new author image file to use the inbuilt default "no photo" image.

**Comment by dkids** [comment]
Seems to be working well.   Thanks!
