### ISSUE TITLE
Feature Request: have LL add cover photo to magazine automatically, after deleting first issue.

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1429]
Feature Request: have LL add cover photo to magazine automatically, after deleting first issue.

If I delete the first issue for a magazine LL shows a question mark for the magazine, rather than showing the cover for the 'new' first issue.

I have to manually remove, and then scan library for the magazine cover to show correctly.

**Comment by philborman** [comment]
Good idea, that's in the next release.
