### ISSUE TITLE
SearchNZBBooks - Error 403 openning url mismatched tag: line 6, column 2

### ISSUE THREAD

**Issue by N00bTaco** [DobyTang/LazyLibrarian#143]
**Expected Results** When using NZB search the supplied URL provided by the search provider should return a valid URL to pass off to the NZB downloader.

**Actual Results**: The returned URL is not correct and the system gives an exception.

**Log Snip**

    27-May-2015 07:36:45 - DEBUG   :: SEARCHNZBBOOKS : [IterateOverNewzNabSites] - USenetCrawler
    27-May-2015 07:36:45 - DEBUG   :: CP Server Thread-6 : Searching for book with id: 23137382
    27-May-2015 07:36:45 - INFO    :: SEARCHNZBBOOKS : [NewzNabPlus] searchType [book] with Host [usenet-crawler.com/] using api [xxxxxxxxxxxxxxxxxxxxxxxxxxx] for item [{'searchterm': "Jim Butcher Jim Butcher's Dresden Files War Cry", 'bookName': u"Jim Butcher's Dresden Files: War Cry", 'authorName': u'Jim Butcher', 'bookid': u'23137382'}]
    27-May-2015 07:36:45 - DEBUG   :: SEARCHNZBBOOKS : NewzNabPlus] - Search parameters set to {'author': 'Jim Butcher', 'apikey': u'xxxxxxxxxxxxxxxxxxxxxxxxxxxx', 't': 'book', 'cat': 7020, 'title': 'Jim Butchers Dresden Files War Cry'}
    27-May-2015 07:36:45 - ERROR   :: SEARCHNZBBOOKS : Error 403 openning url mismatched tag: line 6, column 2
    27-May-2015 07:36:45 - INFO    :: SEARCHNZBBOOKS : Searching for type book failed to find any books...moving to general search
    27-May-2015 07:36:45 - DEBUG   :: SEARCHNZBBOOKS : [IterateOverNewzNabSites] - USenetCrawler
    27-May-2015 07:36:45 - INFO    :: SEARCHNZBBOOKS : [NewzNabPlus] searchType [general] with Host [usenet-crawler.com/] using api [xxxxxxxxxxxxxxxxxxxxxxxxxxxxx] for item [{'searchterm': "Jim Butcher Jim Butcher's Dresden Files War Cry", 'bookName': u"Jim Butcher's Dresden Files: War Cry", 'authorName': u'Jim Butcher', 'bookid': u'23137382'}]
    27-May-2015 07:36:46 - DEBUG   :: SEARCHNZBBOOKS : NewzNabPlus] - Search parameters set to {'q': "Jim Butcher Jim Butcher's Dresden Files War Cry", 'apikey': u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 't': 'search', 'extended': 1}
    27-May-2015 07:36:46 - ERROR   :: SEARCHNZBBOOKS : Error 403 openning url mismatched tag: line 6, column 2
    27-May-2015 07:36:46 - DEBUG   :: SEARCHNZBBOOKS : Adding book Jim Butcher Jim Butcher's Dresden Files War Cry to queue.
    27-May-2015 07:36:46 - INFO    :: SEARCHNZBBOOKS : Search for Wanted items complete

**System**
OS: Windows Server 2012 R2
Python: 2.7.9

**Settings**
Sabnzbd+ only.

**Comment by daktak** [comment]
Usenetcrawler issue. Newznab works.

    28-May-2015 10:36:05 - DEBUG :: SEARCHNZBBOOKS : Found 5 nzb for: Jim Butcher Jim Butcher's Dresden Files War Cry
    28-May-2015 10:36:05 - DEBUG :: SEARCHNZBBOOKS : searchterm Jim Butcher Jim Butcher's Dresden Files War Cry
    28-May-2015 10:36:05 - DEBUG :: SEARCHNZBBOOKS : nzbName jim butchers dresden files war cry digital kempire
    28-May-2015 10:36:05 - DEBUG :: SEARCHNZBBOOKS : NZB Title Match %: 72

**Comment by N00bTaco** [comment]
Nope. Turned off the usenet as provider. Still getting this 403.

What OS are you using @daktak?

    27-May-2015 20:03:19 - DEBUG   :: SEARCHNZBBOOKS : [IterateOverNewzNabSites] - NewzNab1
    27-May-2015 20:03:19 - INFO    :: SEARCHNZBBOOKS : [NewzNabPlus] searchType [book] with Host [http://xxxxxxxxxx/] using api [] for item [{'searchterm': "Jim Butcher Jim Butcher's Dresden Files War Cry", 'bookName': u"Jim Butcher's Dresden Files: War Cry", 'authorName': u'Jim Butcher', 'bookid': u'23137382'}]
    27-May-2015 20:03:19 - DEBUG   :: SEARCHNZBBOOKS : NewzNabPlus] - Search parameters set to {'author': 'Jim Butcher', 'apikey': u'', 't': 'book', 'cat': 7020, 'title': 'Jim Butchers Dresden Files War Cry'}
    27-May-2015 20:03:19 - ERROR   :: SEARCHNZBBOOKS : Error 403 openning url no element found: line 1, column 0
    27-May-2015 20:03:19 - INFO    :: SEARCHNZBBOOKS : Searching for type book failed to find any books...moving to general search

**Comment by daktak** [comment]
Linux, sorry I don't have a Windows box to check with. Python 2.7.9

**Comment by philborman** [comment]
Usenet crawler uses https so you need to put https://usenet-crawler.com as the address. Lazylibrarian assumes http unless told otherwise

**Comment by theguardian** [comment]
This will be fixed with an imminent release.
