### ISSUE TITLE
Remove series from title or sub-title

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1431]
This won't work 100% of the time because sometimes the series name in "Series" differs from what is in the title or sub-title.   But my guess is that removing the series name will increase the percentage matched.

if series 1 has something in it, eject because having two (or more!) series is too complicated to figure out 

If title contains "(Series_name, #X)" 
       remove "(Series_name, #X)" from title
  elif title contains "(Series_name X)" 
       remove "(Series_name X)" 
    elif title contains "- Series #X" 
       remove "- Series #X" 
    elif title contains "- Series X"
       remove "- Series X"

repeat for sub-title

![screenshot-2018-5-20 lazylibrarian - edit book](https://user-images.githubusercontent.com/30055574/40291891-b7772296-5c7c-11e8-8bc7-ed1b5ffeb6b0.png)
![screenshot-2018-5-20 lazylibrarian - edit book 1](https://user-images.githubusercontent.com/30055574/40291892-b79e632e-5c7c-11e8-8197-63936c04af82.png)
![screenshot-2018-5-20 lazylibrarian - edit book 2](https://user-images.githubusercontent.com/30055574/40291893-b7dc94fa-5c7c-11e8-9959-7b653c4db1f6.png)
![screenshot-2018-5-20 lazylibrarian - edit book 3](https://user-images.githubusercontent.com/30055574/40291894-b800d324-5c7c-11e8-9d3b-89a1b9818106.png)
![screenshot-2018-5-20 lazylibrarian - edit book 4](https://user-images.githubusercontent.com/30055574/40291895-b83d1546-5c7c-11e8-8dd6-c8aa8bc164e5.png)
![screenshot-2018-5-20 lazylibrarian - edit book 5](https://user-images.githubusercontent.com/30055574/40291896-b8809500-5c7c-11e8-82df-4012443c5d77.png)

**Comment by philborman** [comment]
We do this for searches, but we keep the whole name in the database as supplied by goodreads/googlebooks. This is so when we refresh the author we don't think it's a different book. Also with googlebooks the (part in braces) is the only source of series info. In goodreads we can query their interface for series info separately which is why the book above says (The League, #10)  but the series info says The League Nemesis Rising #10

For a search we try the whole name (including series, #num) and if we don't get a good enough match we try again without anything in brackets on the end (which isn't always series) eg The Lord of the Rings (Illustrated Edition).

**Comment by dkids** [comment]
OK, that makes sense and I'll stop editing the entries by hand to remove that info.   

Most of the books left to search for are 2018 or 0000, meaning that they've probably not been published yet.   For the rest, they don't seem to be available based on the spot-checking I was doing.

My process is cleaning up using Calibre's "Download metadata and covers" to standardize the names and make sure they can be found.   I'm using "grep Failed ~/src/LazyLibrarian-master/Logs/lazylibrarian.log    | grep WARNING > ~/cleanup" to find books that LL can't match and gradually removing or renaming those.   Those are the issues where it seemed like eBook Scan was working better than Library Scan but that's because I was making sure the count for the author in LL was the same as in Calibre.   Harder to do that when adding lots of things (either downloaded manually, typically torrents, or existing library) to LL.
