### ISSUE TITLE
Number of books not correct after Library Scan

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1433]
Library Scan running in another tab found a book and there are now 7 books total.   The count on this tab stays at 6, even after refreshing the page.

![screenshot-2018-5-21 lazylibrarian - cecil castellucci](https://user-images.githubusercontent.com/30055574/40314866-a88e4a64-5cce-11e8-9594-1b5ed66da6cd.png)

**Comment by philborman** [comment]
The totals are updated at the end of a libraryscan, not as each book is found (too time consuming if adding several books by the same author). Maybe libraryscan was still running when you refreshed the author page? You should find the total gets corrected later.

Can you check your log for 'Updating bookcounts for n authors' and
'Updated totals for [Cecil Castellucci]'

**Comment by dkids** [comment]
It does now show 7.   Sorry for the false alarm.

grep Updat  ~/src/LazyLibrarian-master/Logs/lazylibrarian.log    | grep Castell
21-May-2018 08:15:13 - DEBUG   :: EBOOK_SCAN : importer.py:update_totals:365 : Updated totals for [Cecil Castellucci]
macmedia-2:Bad Suki (11672) kids$ grep Updat  ~/src/LazyLibrarian-master/Logs/lazylibrarian.log    | grep bookcounts
21-May-2018 08:15:06 - DEBUG   :: EBOOK_SCAN : librarysync.py:LibraryScan:1000 : Updating bookcounts for 1036 authors
21-May-2018 08:54:42 - DEBUG   :: POSTPROCESS : librarysync.py:LibraryScan:1000 : Updating bookcounts for 1 author
21-May-2018 08:54:56 - DEBUG   :: POSTPROCESS : librarysync.py:LibraryScan:1000 : Updating bookcounts for 1 author
21-May-2018 09:04:40 - DEBUG   :: POSTPROCESS : librarysync.py:LibraryScan:1000 : Updating bookcounts for 1 author
21-May-2018 09:04:43 - DEBUG   :: POSTPROCESS : librarysync.py:LibraryScan:1000 : Updating bookcounts for 1 author
21-May-2018 09:14:37 - DEBUG   :: POSTPROCESS : librarysync.py:LibraryScan:1000 : Updating bookcounts for 1 author
21-May-2018 09:14:46 - DEBUG   :: POSTPROCESS : librarysync.py:LibraryScan:1000 : Updating bookcounts for 1 author
21-May-2018 09:21:39 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:1000 : Updating bookcounts for 1 author
21-May-2018 09:23:06 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:1000 : Updating bookcounts for 1 author
21-May-2018 09:23:06 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:1000 : Updating bookcounts for 1 author
21-May-2018 09:33:34 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:1000 : Updating bookcounts for 1 author
21-May-2018 09:34:25 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:1000 : Updating bookcounts for 1 author
21-May-2018 09:35:39 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:1000 : Updating bookcounts for 1 author
21-May-2018 09:36:27 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:1000 : Updating bookcounts for 1 author
21-May-2018 10:30:06 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:1000 : Updating bookcounts for 1 author
21-May-2018 10:31:08 - DEBUG   :: AUTHOR_SCAN : librarysync.py:LibraryScan:1000 : Updating bookcounts for 1 author

**Comment by philborman** [comment]
No problem. I've just rewritten that section of libraryscan to update each authors total when we change author, not all at the end.
