### ISSUE TITLE
LL unable to import mags after update to latest build

### ISSUE THREAD

**Issue by danfozzy** [DobyTang/LazyLibrarian#1437]
Current Version: 8c6b66e6e5709614ccb4ea19fa022486c99c1e66
running on synology NAS using linuxserver docker image

im getting issues importing magazines after updating to the latest version:

ERROR | Unhandled exception in processDir: Traceback (most recent call last): File "/app/lazylibrarian/lazylibrarian/postprocess.py", line 677, in processDir with open(ignorefile, 'a'): IOError: [Errno 2] No such file or directory: u'/books/magazines/Autocar uk/2018-05-16/.ll_ignore'
-- | --

it has no issues in find the mag and sending it to nzbget, but this comes up everytime postprocessing

**Comment by danfozzy** [comment]
will provide a full log asap

**Comment by robflate** [comment]
Did you find a solution to this? I've got the same problem.

**Comment by philborman** [comment]
Not fixed yet, sorry not at home at the moment. Should get it done tomorrow
night

**Comment by danfozzy** [comment]
thank you for this fix

little confused, not had to look on github for this project in a while, little confused about the different forks! the fork im using is DobyTang (using the docker image from linuxserver) noticed the fix is on your fork

will this fix make it to DobyTang's version or will i need to ask (pester!) the linuxserver team to adopt your fork as the master?

**Comment by philborman** [comment]
Should make it onto DobyTang, that's the main fork, and linuxserver update theirs from DobyTang every Friday (I think). Mine is just for testing/dev so it breaks regularly. You should be able to use the lazylibrarian internal update mechanism inside the linuxserver docker. Will push my updates to DobyTand in a few hours if the last few tests are ok...

**Comment by danfozzy** [comment]
Thanks fix is good for me
