### ISSUE TITLE
This dead again :(

### ISSUE THREAD

**Issue by ruinit** [DobyTang/LazyLibrarian#144]

**Comment by nncrypted** [comment]
Had someone working on it then they just up and disappeared. I can't even find the user on Git anymore, it's kinda weird.

**Comment by ruinit** [comment]
shame no one will keep this going

**Comment by nncrypted** [comment]
I'm not a coder but I can push the commits if anyone wants to do the work. Not sure where Doby went to. Hope all is well.

**Comment by ruinit** [comment]
wonder if someone could use mylar to and make it download all ebooks not just comics? Mylar works fairly well.

**Comment by nncrypted** [comment]
Anything is possible
