### ISSUE TITLE
Permission Issue

### ISSUE THREAD

**Issue by CrypticOne** [DobyTang/LazyLibrarian#1449]
Scanning an existing Calibre library. I get an error message stating LL cannot create a folder. The log seems to state it is running as nobody/users which is not correct.  It is running as it's own user that should have full permissions to the folders. 

It added 55 items but then no longer finds any other books.

To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
Current Version: c7de4d744427cd1640fb9c64cd8f160c00209195
### Operating system used (windows, mac, linux, NAS type)
Synology 6.17
### Interface in use (default, bookstrap)
bookstrap
### Which api (Goodreads, GoogleBooks, both)
Goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
SynoCommunity package
### Relevant debug log with api keys and any passwords redacted

18:34:46 | DEBUG | EBOOK_SCAN | librarysync.py | LibraryScan | 466 | Skipping /volume1/@appstore/lazylibrarian/var/LazyLibrarian/.git
-- | -- | -- | -- | -- | -- | --
2018-06-03 18:34:46 | INFO | EBOOK_SCAN | librarysync.py | LibraryScan | 379 | Scanning eBook directory: /volume1/@appstore/lazylibrarian/var/
2018-06-03 18:34:46 | DEBUG | EBOOK_SCAN | __init__.py | DIRECTORY | 1181 | Folder: /volume1/Media/K/ Mode: 040770 UID: 99 GID: 100 W_OK: False X_OK: False
2018-06-03 18:34:46 | WARNING | EBOOK_SCAN | __init__.py | DIRECTORY | 1178 | eBook dir [/volume1/Media/K/] not writeable, using /volume1/@appstore/lazylibrarian/var/: [Errno 13] Permission denied: u'/volume1/Media/K/ll_temp'
2018-06-03 18:19:29 | DEBUG | POSTPROCESS | common.py | scheduleJob | 422 | Stop processDir job

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report. 
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/2066572/debug.zip)

**Comment by philborman** [comment]
Definitely something up with permissions...
> Folder: /volume1/Media/K/ Mode: 040770 UID: 99 GID: 100 W_OK: False X_OK: False

Synology is telling us the folder is not writeable or executable by us
> eBook dir [/volume1/Media/K/] not writeable, using /volume1//var/: [Errno 13] Permission denied: u'/volume1/Media/K/ll_temp'

we try to create a file called ll_temp  in that folder and get permission denied

**Comment by CrypticOne** [comment]
Is there any other place that shows what user/group LL is running under? The .pid files are made by a different user.

**Comment by philborman** [comment]
ps command?
ps aux | grep Lazy

**Comment by CrypticOne** [comment]
Somehow the permissions were wrong on the files. Thanks for the help!
