### ISSUE TITLE
Error: no such group

### ISSUE THREAD

**Issue by splog123** [DobyTang/LazyLibrarian#145]
Anyone know what this error means? I'm re-scanning the on-disk Library that was previously scanned in, but the process was aborted and left incomplete.

11-Aug-2015 13:16:38 - INFO    :: CP Server Thread-4 : Scanning ebook directory: /mnt/media/eBooks/books
11-Aug-2015 13:16:38 - INFO    :: CP Server Thread-4 : Missing books will be marked as Wanted
11-Aug-2015 13:16:40 - INFO    :: CP Server Thread-4 : [/mnt/media/eBooks/books] Now scanning subdirectory /David Bowick/How To Disappear Completely
11-Aug-2015 13:16:40 - ERROR   :: CP Server Thread-4 : Unable to complete the scan: no such group

If I remove that book and try again, I get the same error with the next one. And so on and so on (tried up to 10 and gave up). The error prints to the console almost immediately, andI can't see from the code what it's complaining about.

Unix groups? They are correct.
Some book grouping concept inside LL or in Goodreads? Can't find such a thing.

My code base here is sync to master branch

**Comment by splog123** [comment]
Found the issue, but I don't like what the code is doing.

Config var ebook_dest_file MUST contain $Author and $Title otherwise the regexes in lazylibrarian/librarysync.py (around line 89) fail horribly.

**Comment by nncrypted** [comment]
If you can repair it and would like to share I can merge it into the master branch as long as it doesn't break anything else as I'm not the guy to fix anything I just merge LOL

**Comment by splog123** [comment]
:-)

I'll have a closer look in the morning when I can see straight, but it doesn't look easy to fix. The code has to take a fully qualified path/filename like

$DESTINATION_DIR/$Author/$Title/$Author - $Title

and magically figure out the author and title. It's a horrible problem to solve so I can see why devs in the past stuck with "the names work one way, and no other way". I'll compare to headphones and mylar, see how those apps do import from disk.

Or maybe we should just clearly say on the Search & Processing page this is what the format must be.

**Comment by philborman** [comment]
That looks like the file naming format Calibre prefers - are you importing/synching to a calibre library?
If so, another (simpler) way is to read the author/title from the calibre database, or from the metadata.opf file in the current directory

**Comment by splog123** [comment]
I use calibre extensively, but it doesn't feature here. I was trying to name the book collection file like this:

Shakespeare/Hamlet/Hamlet.epub

Having $Author and $Title variables implied they were optional and available to use (this is how the vast majority of software deals with such things). What LL does during disk scan and reading the library store is to look for both values; if one or both is missing, a regex error occurs. Before we all jump up and down saying the code is shocking, we must keep in mind that the LL code is really still pre-alpha and there's huge scope for improvement still, like in this area. I plan to get stuck into it sometime soon when I've freed up some spare time.

Reading the calibre database or the .opf is not really practical; calibre may or may not be installed, it's db may or may not be available and readable, and the .opfs may or may not be there. Also LL fetches books and writes them to disk, from there they get to calibre by some means; making LL and goodreads/googlebooks the source of data and calibre the recipient. Not wise to try and flip those roles around mid-stream

**Comment by philborman** [comment]
Yes,  i agree the current code is horrible but how else can you do it? You
can guess based on filenames  or directory structures but this is just a
guess and needs a degree of sanitising for characters that aren't allowed
in filenames across different file systems and length restrictions.
IF there is a calibre style metadata file present,  at least you don't need
to guess. At present LL goodreads and googlebooks all handle names
differently,  its a nightmare.

Btw; your example filename will probably work as Shakespeare/Hamlet/Hamlet
- Shakespeare.epub

**Comment by splog123** [comment]
OK, I see where you're coming from. When scanning an existing library, use a .opf if present, assuming that the user has already gone to the effort of naming things properly. It's a safe assumption; even if the .opfs are wrong, the code should still assume the user wants it that way and can deal with the result.

I'm starting to think LL should write out an .opf when it saves a book to the destination folder, much like couchpotato and sickrage do with .nfo files.

**Comment by philborman** [comment]
Yes,  i think thats the way forward.  No point in repeating the
search/match process if its already been done.

Goodreads seems to be a fairly poor system to match to,  as it mangles
names horribly,  eg it replaces accented characters with underscores so
"John le Carré"  becomes "John le Carr_"
At the moment I'm using libfuzzy to get around it,  but it's not ideal.

Calibre gets its metadata from
isbndb.com, Google Books, Amazon and Library Thing - not goodreads

May have a look at calibres code ;-)

**Comment by splog123** [comment]
Agreed on GR's horrible metadata; why the need to make stuff 7-bit ASCII-safe? 1995 called, they want their last 20 years back...

I looked at the various data sources a while ago and GR seemed the easiest to use with least restrictive rules, probably why the original coder went with it. I didn't look into isbndb though, will have to read up on that one. What's your thoughts - should GR be made a secondary provider way down the list and at least one of calibre's four become primary?

**Comment by philborman** [comment]
Personally I prefer GoogleBooks. I have a calibre library of 1120 books. 
LL master branch scanning with GoodReads only identifies 536. Scanning 
with GoogleBooks identifies 785. Doing a "fuzzy" scan with GoogleBooks 
pushes this up to 995. I'm still working on the remainder. Some 
genuinely are not in GB or GR so won't ever get detected correctly, 
others just have inconsistent naming.

As the ebooks possibly contain (some) metadata already, and there are 
libraries to extract metadata from inside epub, pdf, mobi I'm wondering 
about this process...

if calibre metadata file found, use it
else if ebook contains embedded metadata, use that
else try to work out author/title from folder/filenames


What do you think?

**Comment by splog123** [comment]
I have similar problems - 7400 books in calibre and GR only finds 2827 of them. I don't have lang set to Unknown (tried that once = chaos ensued) and I find GR's coverage can be patchy depending on what users have entered. Some popular authors' recent books are just not there (Raymond E. Feist). Full library scan takes 3 days (GR can get very slooooow). So I like the idea of adding more metadata providers.

I also agree with your process. I can think of a few edge cases where the ebook will be correct and the .opf is wrong, but I think that's a ToughLuck(tm) scenario - the README should state outright that the .opf is always assumed to be correct and the data is the way it is because the user wants it that way.

Most of my stuff is epub with maybe 20% mobi and so far I find the in-book metadata to be pretty good overall. Those 2 plus whatever Amazon uses cover most users' needs I believe leaving pdf, txt, doc, lit and other old formats where we have to use file/dirnames. I'm happy to let those sit in the 20 part of the 80/20 rule

**Comment by philborman** [comment]
There are a couple of quick-and-easy optimisations you can do in 
librarysync.py to cut your 3 days down to 1 ( my speed-up was nearly x3  
ymmv )

If you only have one book title per directory, the latest_subdirectory 
array (which isn't used currently) was presumably put in to skip 
re-processing directories you have already looked at. No need to run the 
loop for one_book.epub and again for same_book.mobi and same_book.pdf 
and any other random files in the same directory
Just needs an "if not subdirectory in latest_subdirectory " near the 
start if the "for files in f:" loop

The matchstring/replace/pattern section is run for every file in f. Why?
Move this section before the "for r,d,f in oswalk(dir)" loop so it only 
runs once

Phil.
