### ISSUE TITLE
DataTables warning: table id=author_table - Ajax error

### ISSUE THREAD

**Issue by 1liminal1** [DobyTang/LazyLibrarian#1454]
To help with identifying and fixing issues, please include as much information as possible, including:
### Source of your LazyLibrarian installation zip file,

So strangely, this doesn't appear in the logs. Any time I click on the button for the home screen I get this error at the top in a dialogue box

```
DataTables warning: table id=author_table - Ajax error. For more information about this error, please see http://datatables.net/tn/7
```

**Comment by philborman** [comment]
Ajax error means we didn't send the right amount of data from the python code to the table display code. Unfortunately you don't get any more info than that. Would be helpful if the error message was more informative.

Might be worth trying the bookstrap interface in case its a problem with the old legacy interface. 
Also might get more info from lazylibrarian loglevel 256

**Comment by philborman** [comment]
I have added some code to trap any ajax errors, should print a traceback in the log and show an empty table. The traceback should give us enough info to know what the underlying problem is. Will be in the next release, probably tomorrow.

**Comment by 1liminal1** [comment]
Awesome!

Ill try it tomorrow night :)

Thanks

**Comment by 1liminal1** [comment]
New update seems to have fixed the issue!

Thanks for that.

Is there any instructions for this software. Specifically manual searches?

Thanks again

**Comment by philborman** [comment]
The wiki is quite out of date, I really must spend some time tidying it up and adding in the new stuff.

For authors or books you don't have in the database, just put the author name and/or title in the search box top right of the lazylibrarian homepage (authors list). Lazylibrarian wil search and show a page of results. The wiki on this part is fairly correct still, I think.

To automatically search for books that are in the database, mark them as wanted and let lazylibrarian go looking. For a manual search where you pick the one you want to download there is a "manual" button under the book title on the individual author pages. Click that and a metadator editor page opens up. At the top of the editor page is a dropdown where you can select what type of search (usually best to start with both author and title, get less specific if you don't find the one you want). Click on the result you want to download and lazylibrarian grabs that one.
