### ISSUE TITLE
Issues connecting to Deluge

### ISSUE THREAD

**Issue by kevinpawsey** [DobyTang/LazyLibrarian#1459]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
Current Version: 754697fa5e7b20b55106fee76aabfee7eb4b05bf : Latest Version: 754697fa5e7b20b55106fee76aabfee7eb4b05bf

### Operating system used (windows, mac, linux, NAS type)
Linux - Ubuntu 17.10 up to date

### Interface in use (default, bookstrap)
Bookstrap

### Which api (Goodreads, GoogleBooks, both)
Both

### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
git

### Relevant debug log with api keys and any passwords redacted
`13-Jun-2018 08:43:34 - INFO    :: WEBSERVER : client.py:_connect:73 : Connecting to 127.0.0.1:58846
13-Jun-2018 08:51:42 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:363 : Found 239 files marked "Snatched"
13-Jun-2018 08:51:42 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:962 : J K  Rowling - THE DEATHLY HALLOWS LL.(dJ87tAEACAAJ) was sent to SABNZBD
13-Jun-2018 08:51:42 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:962 : J K  Rowling - The Prisoner of Azkaban LL.(p-W7qWMJUasC) was sent to SABNZBD
13-Jun-2018 08:51:42 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:962 : Rick Riordan - The Mark of Athena (Heroes of Olympus Book 3) LL.(4NuJZT8XLgQC) was sent to SABNZBD
13-Jun-2018 08:51:42 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:962 : Rick Riordan - Der Hammer des Thor LL.(EoFZswEACAAJ) was sent to SABNZBD
13-Jun-2018 08:51:42 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:962 : Rick Riordan - From Percy Jackson  Camp Half-Blood Confidential LL.(_DyvDQAAQBAJ) was sent to SABNZBD
13-Jun-2018 08:51:42 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:962 : Nicholas Sparks - The Best of Me LL.(t1DHCAAAQBAJ) was sent to SABNZBD
13-Jun-2018 08:51:42 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:962 : Nicholas Sparks - The Lucky One LL.(NE7hZDy_8hgC) was sent to SABNZBD
13-Jun-2018 08:51:42 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:962 : Nicholas Sparks - The Wedding LL.(M9tARpafXOIC) was sent to SABNZBD
13-Jun-2018 08:51:42 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:962 : Nicholas Sparks - Dear John LL.(LWuNAB3HtVgC) was sent to SABNZBD
13-Jun-2018 08:51:42 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:962 : Nicholas Sparks - The Longest Ride LL.(oNmcESgbOg0C) was sent to SABNZBD
13-Jun-2018 08:51:42 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:962 : J R R  Tolkien - The Return of the King  The Lord of the Rings LL.(dQkFLM8_5ZEC) was sent to SABNZBD
13-Jun-2018 08:51:42 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:962 : LOTR_BBC_Radio was sent to DELUGERPC
13-Jun-2018 08:51:42 - INFO    :: POSTPROCESS : client.py:_connect:73 : Connecting to 127.0.0.1:58846
13-Jun-2018 08:51:42 - ERROR   :: POSTPROCESS : postprocess.py:getDownloadName:986 : DelugeRPC failed NameError global name 'lazylibrarian' is not defined
13-Jun-2018 08:51:42 - INFO    :: POSTPROCESS : client.py:_connect:73 : Connecting to 127.0.0.1:58846
13-Jun-2018 08:51:42 - ERROR   :: POSTPROCESS : postprocess.py:getDownloadFiles:1019 : DelugeRPC failed NameError global name 'lazylibrarian' is not defined
13-Jun-2018 08:51:42 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:404 : No files returned by DELUGERPC for LOTR_BBC_Radio
`

Not sure when this started happening, but if I go to the "Downloaders" config page, click to test Deluge connection, this is saying the same thing...
`Deluge: Daemon connection FAILED
NameError global name 'lazylibrarian' is not defined`

I know that there are no access issues with this machine getting to Deluge, as this is running on the same machine, and the API is working, as I have a script that pauses all the Deluge downloads when I start watching a movie/TV... and this is from the same machine.

I know that the error isn't particularly helpful, and my apologies for not knowing when this started.  I have checked in the archived (.1-.10) log files and I can't see anything in them, as they have already rotated for today.  I will increase log file size/retention to see if that will help me pick up any changes.

Let me know if you need any other information.

**Comment by philborman** [comment]
It's a bug.
Recently changed the debug loglevels to work in a different way, but the deluge daemon doesn't know about them. Deluge webui works, looks like I didn't check the daemon :-)

Fix should be in the next release, probably an hour or two as it's a trivial change and the rest of the updates in this release seem ok.

**Comment by kevinpawsey** [comment]
and this... ladies and gentleman... is why lazylibrarian is awesome 💃 

Thanks for coming back so quick... will let you know when I get the update and will close and comment 👍

**Comment by philborman** [comment]
Yes, I'm getting quite good at fixing bugs I introduced myself, i know _exactly_ where to look :-)

**Comment by kevinpawsey** [comment]
haha... well, I am pleased to say that you can chalk this up to another one of those... it appears that this is fixed now :)

Thanks for your help... and what you do for the project... we all owe you one!
