### ISSUE TITLE
Author titles and booknames not matching

### ISSUE THREAD

**Issue by philborman** [DobyTang/LazyLibrarian#146]
Calibre library and GoodReads have different ways of handling accented characters.
I have patched librarysync.py to include fuzzy matching, how do I submit the patch?
(git push fails with error 403)

**Comment by nncrypted** [comment]
I can't remember how to do that but once you get it as a pull request I will merge it for you. Only advice I have

**Comment by philborman** [comment]
Thanks, I have a pull request ready, don't know how to get it to you.
On the github page I can not see how to send you a pull request, so I 
have attached a diff file.
Please let me know if there is a better way.
Thanks.

**Comment by nncrypted** [comment]
I think it's because you don't have a fork from here on github. Just a thought was hoping someone with more experience would jump in here and give advice

**Comment by philborman** [comment]
Ah ok.
I didnt want to fork,  just contribute a patch to the existing repository.
Probably have to wait until dobytang sees these messages.

Thanks anyway

**Comment by nncrypted** [comment]
I'm don't think Doby is around anymore I haven't seen him here in almost a year

**Comment by philborman** [comment]
so I guess nobody is maintaining it any more?
Has anyone forked it that we can submit patches to?
