### ISSUE TITLE
Runtime error after changing theme to Default

### ISSUE THREAD

**Issue by McArg** [DobyTang/LazyLibrarian#1462]
1: I no longer appear to have any Magazines
2: When clicking on the 'config' button I get this error:

and my version number is: 143d500742aeb84ff94d2a02cfc558b8d9266d0a

Error !
KeyError: 'WWT'
<input type="checkbox" id="kat" name="kat" value=1 ${checked} style="margin-bottom:4px;" /> kickass <input type="text" placeholder="Enter URL Here" id="kat_host" name="kat_host" value="${lazylibrarian.CONFIG['KAT_HOST']}" size="26"> <br> <% if lazylibrarian.CONFIG['WWT'] == True: checked = 'checked="checked"' else: checked = '' %>
E:/Program Files/LazyLibrarian/data/interfaces/default/config.html, line 784:
<%
E:/Program Files/LazyLibrarian/data/interfaces/default/base.html, line 157:
${next.body()}
E:\Program Files\LazyLibrarian\mako\runtime.py, line 890:
callable_(context, *args, **kwargs)
E:\Program Files\LazyLibrarian\mako\runtime.py, line 864:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
E:\Program Files\LazyLibrarian\mako\runtime.py, line 829:
**_kwargs_for_callable(callable_, data))
E:\Program Files\LazyLibrarian\mako\template.py, line 445:
return runtime._render(self, self.callable_, args, data)
E:\Program Files\LazyLibrarian\lazylibrarian\webServe.py, line 91:
return template.render(perm=lazylibrarian.perm_admin, **kwargs)

**Comment by philborman** [comment]
Yes, "wwt" was removed quite a while ago as it's no longer alive, and the "default" interface is no longer supported. There is a version of it called "legacy"  which should work.  It seems somewhere in one of the upgrades your default interface didn't get renamed to legacy?  If you delete the data/interfaces/default folder it should all go back to normal as if we can't find a named interface we fall back to legacy. Magazines should be ok in the legacy interface too, but not audiobooks as all of the new developments are in the newer bookstrap interface.

**Comment by barbequesauce** [comment]
WWT is still around... they changed TLD to .me...

**Comment by philborman** [comment]
Confusing.
https://alternativeto.net/software/worldwidetorrents/   
says WorldwideTorrents is discontinued. Find alternatives in the list below or click here for more info
and then gives the new domain as an update.  I will check it out and add it back in again if it seems ok.

**Comment by McArg** [comment]
Thanks,
after deleting the 

data/interfaces/default folder

configuration was available again (as legacy)

and I could switch back to bookstrap.

I did indeed have an old default folder with a timestamp of: 23/11/2017

**Comment by philborman** [comment]
Ok, so put wwt back in again, but they have added cloudflare bot/ddos protection.
If we hit that we get a 503 error code and no results. Needs more work to get around it.
