### ISSUE TITLE
"title.epub" -> "titleepub", "title.mobi" -> "titlemobi" on Direct matches

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1463]
version: 143d500742aeb84ff94d2a02cfc558b8d9266d0a

ls -al Richard\ Yates\ Revolutionary\ Road/
-rw-r--r--   1 kids  staff  416617 Jun 13 11:24 Richard Yates Revolutionary Roadmobi
ls -al Sylvia\ Plath\ The\ Bell\ Jar/
-rw-r--r--   1 kids  staff  731923 Jun 13 11:25 Sylvia Plath The Bell Jarmobi
ls -al Mike\ Mullin\ Ashfall/
-rw-r--r--   1 kids  staff  402050 Jun 13 11:33 Mike Mullin Ashfallepub

lazylibrarian.log:13-Jun-2018 11:37:42 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:985 : Mike Mullin Ashfall epub was sent to DIRECT

This wasn't a problem until the past few days.

**Comment by philborman** [comment]
Should be fixed in next version.

**Comment by dkids** [comment]
Definitely fixed.   Thanks.
