### ISSUE TITLE
Request: Change Downloaded count to exclude Ignored books/series

### ISSUE THREAD

**Issue by derekoharrow** [DobyTang/LazyLibrarian#1468]
Using LL web, on the Authors page it shows the authors and a count of how many books you have downloaded out of the total for that author.
Can this be changed so that the total excludes any books that are marked as Ignored?
For example I have on author where I've downloaded 5 of their 20 books. The other 15 I'm not interested in and have them marked as ignored, but this screen still says I've got 5/20, rather than 5/5.

**Comment by philborman** [comment]
It should already do that, I think.
Can you let me know what version of lazylibrarian are you using, python version, interface so I can look into it

**Comment by derekoharrow** [comment]
You're right - updated to latest version and it does. Thanks
