### ISSUE TITLE
Don't bundle the libraries

### ISSUE THREAD

**Issue by MrTimscampi** [DobyTang/LazyLibrarian#1472]
Bundling libraries is a really bad practice.

They are often left as-is, without checking for updates regularly and can thus present a security issue, or prevent the use of new features/improvements that would be beneficial to the software.

Bundling libraries goes against the packaging guidelines of most distributions and wastes space on the user's machine, for what is (in Python at least) a very marginal improvement to ease of use.

Python has a package manager that can handle dependencies and should be used instead of bundling them.  
Package maintainers can then rely on the python package definition to determine dependencies and package them if needed.

Procedure should be as follows:

- [ ] Remove lib and lib3 directories
- [ ] Replaces references to `import lib.foobar` with `import foobar`
- [ ] Add version checks if needed (if a library name varies if Python 2 or 3)
- [ ] Make changes if libraries implemented breaking changes since last update
- [ ] Write setup.py and package as a regular Python Package (See packaging.python.org)
- [ ] Eventually publish to PyPi for ease of installation

This would obviously require updates to packages and Dockerfiles, but it is very much worth it.

**Comment by philborman** [comment]
I very much agree with the sentiment and the argument, but unfortunately it's not that simple.  Most of these sorts of servers ( lazylibrarian, headphones, sickbeard, mylar, calibre ) bundle their libraries for good reason. Well, several good reasons.

These servers often run 24/7 and people like to run them on small low power always-on devices like NAS units. Many of these are running crippled versions of o/s with missing or old libraries that users don't have permission to upgrade, or if they do upgrade it breaks the NAS. Older synology units are particularly bad in this respect. I know the "proper" solution is to fix the o/s, but that's not going to happen anytime soon. SSL libraries and some apps like ghostscript have been issues in the past, upgrade and you cripple the NAS requiring a system reinstall. Doesn't lead to happy users :-)

Some other systems (including some versions of windows) run incompatible versions of libraries that we can't upgrade for the same reason, ie there are different libraries called "magic" and "csv" and the syntax differs or some functions in the libraries are named differently. If we install the ones we want system-wide we would break other apps relying on the other library version.

LazyLibrarian runs on an older version of cherrypy which is not simple to upgrade, and if the user upgrades their system cherrypy for a newer version it would break our app.

If there is a bug, it's much easier to track if we know what versions of libraries are in use for tracking the issue down. Not all libraries tell you their version (they probably should, but not all do, eg unrar, magic)

It would be a lot less work for me if there was a way of reliably using system versions of libraries, at the moment for each new library we add I have to manually add relative links to the ones we bundle. Would be great not to have to.

**Comment by MrTimscampi** [comment]
I get what you are saying, but honestly those are all packaging-related issues.

Nothing prevents the person/script packaging for Synology or Windows or whatever to bundle their own set of libraries, for example in a virtual environment or similar.

> LazyLibrarian runs on an older version of cherrypy which is not simple to upgrade

This is specifically due to the issue we are talking about here.  
If it was not bundled in the first place, it could have been dealt with as new stable versions were coming out and it'd be less of a hassle.

> ie there are different libraries called "magic" and "csv" and the syntax differs or some functions in the libraries are named differently

Python is built to handle multi-platform software. You can simply use a try...catch block to try loading one version of the library, then fallback on another one.  
Same for functions with different names. This can all be handled in code. It'd probably make the source code a tiny bit longer, but in my opinion it's much better than bundling old, potentially unsafe, libraries.

**Comment by philborman** [comment]
Development has moved to [GitLab](https://lazylibrarian.gitlab.io/)
All open issues have been moved over to [LazyLibrarian Issues](https://gitlab.com/LazyLibrarian/LazyLibrarian/issues)
Please open any new issues or comments on the new repo as the old one is no longer maintained, thanks
