### ISSUE TITLE
[Enhancement]: method of 'grouping' like-named books together

### ISSUE THREAD

**Issue by kevinpawsey** [DobyTang/LazyLibrarian#1477]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
Current Version: ed55f7e6304bd746db35d478ba9d813111bbdac1 : Latest Version: ed55f7e6304bd746db35d478ba9d813111bbdac1
### Operating system used (windows, mac, linux, NAS type)
Linux Ubuntu 17.10 fully up to date
### Interface in use (default, bookstrap)
Bookstrap
### Which api (Goodreads, GoogleBooks, both)
both
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
git

Was just wondering if there is any way of grouping like-named books together, so that when one book of a certain name is downloaded you don't then end up with multiple copies of it.  It is most annoying with AudioBooks... especially considering my source I need to accumulate seed time to download... only to then find that I snatch a duplicate copy of something! lol

At the moment I am literally going through manually and looking at what has a status of "open" in the ebook list, searching for some words in the title, and then removing any others that are the same.

I know it is a bit of a reach, but I was wondering if I was missing something to stop duplicate names, or how other people deal with it really.

Thanks for your help.

Kevin

**Comment by philborman** [comment]
Not sure how easy this would be to do, particularly with series where the names are very similar to start with. One option would be to set a default of 'Skipped' for all audiobooks and then manually select one of each title to download, rather than stopping the ones you don't want?

**Comment by kevinpawsey** [comment]
I am going to try your method to see how that is going to work out.
Understandably it is going to be difficult to 'group' these releases, unless you use a comparison system like you currently use with the downloads/snatches.
I always get mixed up with Delete/Ignore/Skip.... I think I have my head around it now, and I think that Skip may be my option.
Thanks again for your help.
Kevin
