### ISSUE TITLE
LL + Calibre setup question

### ISSUE THREAD

**Issue by saitoh183** [DobyTang/LazyLibrarian#1478]
I use Calibre Web to serve my books and audiobook to my users. Now i know Calibre doesnt really support Audiobooks except when it is a single mp3 file, i was able to do it with multi-file audiobooks by zipping the audiobook first before adding it to calibre. This works great. Now wanting to add LL into the mix to get some automation going, im trying to figure out how best to approach my situation. Im currently using LL docker from LS and Calibre-RDP docker from aptalca. Im also aware of the docker container that has both calibre and LL in it but i dont know if i need to switch to that in order to achieve what i explain below.

First off the format i use in Calibre for Audiobooks is
- Title [Audiobook]
- Author: First name , Last name
- Add a extra Tag called Audiobook or Ebook
- Add a checkmark to either custom columns (Audiobook or Ebook)

I was doing this manually for each media i added. Since my media is all in google drive, i use unionFS/plexdrive + rclone(for upload) to manage the RW of the metadata.db/opf files and adding new books.

I already have an idea of how to get stuff zipped after download via script and have them placed in the watch directory of LL but i would like to have the format mention above done automatically when the book is added to calibre. 

- Can this be done via caliredb? 
- Can LL do it and calibre add the book as LL named it? 
- Could i use custom notification to launch a script after download that would rename the new media to the title format ***Title format: Title [Audoibook]*** ...are there env variable in LL that i could use in my script? Since Audibooks and Ebooks have there own library location, i was thinking i could use the library folder name as a way of knowing if im treating a audiobook or ebook.

Thanks

**Comment by philborman** [comment]
The thraxis docker with lazylibrarian and calibredb makes it much easier if you are using two dockers as the calibredb in the thraxis docker talks to the calibre content server in the other docker.

You could use a custom notifier to zip the files up, or you could use the same method as the lazylibrarian rss feed, which zips up audiobooks if you download using their rss link. A custom notifier gives you more control over the filename though. Alternatively you could feed the audiobooks to your users via the rss link and save using calibre at all?

I think Calibre will rename the audiobook folder according to it's own naming pattern, it needs to add it's own (id_number) on the end of the foldername, but I don't think it will rename the zipfile. 

In the custom notifier you will be given all sorts of info about the download, including whether it's ebook or audiobook in the AuxInfo field. See the supplied example_custom_notification.py
If you put this example program into lazylibrarian config and use "test custom notifier" button it will pretend the first book in the database has just been downloaded and show the details that were passed to it in the log.

**Comment by saitoh183** [comment]
> I think Calibre will rename the audiobook folder according to it's own naming pattern, it needs to add it's own (id_number) on the end of the foldername, but I don't think it will rename the zipfile.

It can do both
![image](https://user-images.githubusercontent.com/1534197/41737086-3a868d96-755c-11e8-91a8-a13a60e8ebee.png)

> Alternatively you could feed the audiobooks to your users via the rss link and save using calibre at all?

My users are setup to use Calibre web already and they like the layout and such. 

> You could use a custom notifier to zip the files up, or you could use the same method as the lazylibrarian rss feed, which zips up audiobooks if you download using their rss link. A custom notifier gives you more control over the filename though. 

I was thinking of using Sabnzbd/Deluge to run a script to zip up the file using the the same name as the download and putting it in the download folder LL would be monitoring but i dont know if LL would recognized the zip and move it to the audiobook library location. Then i was thinking once it was moved by LL the custom notifier "on download" could launch the calibredb with the proper flag to modify the values i need to achieve the formatting i need.

> The thraxis docker with lazylibrarian and calibredb makes it much easier if you are using two dockers as the calibredb in the thraxis docker talks to the calibre content server in the other docker.

If you dont mind me asking, how does it work? it would be able to communicate with my Calibre-RDP docker? i would have to turn on the content server?

**Comment by philborman** [comment]
LL queries the downloaders for the name of the file, so that part should be ok. When we send a torrent/nzb to deluge/sab they return us an id, which we use to check progress and get the filename. LL will then try to unzip the file though, as we're expecting to put epub/mobi/mp3 or whatever into the library, not zip.   Would be better if lazylibrarian or custom notifier did the zipping.

You would need content server enabling in calibre for the thraxis docker to work, or use calibre watch directory instead. Problem with watch directory is that lazylibrarian doesn't get to talk to calibre to find out where calibre put the files.

**Comment by saitoh183** [comment]
> You would need content server enabling in calibre for the thraxis docker to work, or use calibre watch directory instead. Problem with watch directory is that lazylibrarian doesn't get to talk to calibre to find out where calibre put the files.

I dont mind enabling content server if it means it would work better. 

>  as we're expecting to put epub/mobi/mp3 or whatever into the library, not zip. Would be better if lazylibrarian or custom notifier did the zipping.

If i were to add the zip extension to the File Format section, it wouldnt work? If i let LL or custom notifier do the zipping, how would the process look?

So i installed the Thraxis docker container, added the path to calibredb, anything else i got to do?

**Comment by saitoh183** [comment]
Also since im going to use calibre with Audiobooks, i must point the Audiobook library to /books as well?

**Comment by philborman** [comment]
> If i were to add the zip extension to the File Format section, it wouldnt work? 

No, lazylibrarian will try to look inside zip/tar/rar archives as some torrents arrive zipped up

> If i let LL or custom notifier do the zipping, how would the process look?

The custom notifier will be given the full path and filename of part one of the audiobook. You can use that to find the directory that the audiobook is in, and then you just have to zip up all the files in that directory.
In python you would do something like this...

```
               # audiofile is part one of the audiobook
                if os.path.isfile(audiofile):
                    parentdir = os.path.dirname(audiofile)
                    with tempfile.NamedTemporaryFile() as tmp:
                        with zipfile.ZipFile(tmp, 'w', zipfile.ZIP_DEFLATED) as myzip:
                            for root, dirs, files in os.walk(parentdir):
                                for fname in files:
                                    myzip.write(os.path.join(root, fname), fname)
                            # at this point copy the zipfile to a calibre folder
```

**Comment by saitoh183** [comment]
So i used the example custom script and saw all the info it returned, but how can i use that info in my own custom script? I would only want certain sections..like
- BookLang
- AudioLibrary
- BookName
- BookLibrary

**Comment by philborman** [comment]
If you are using python, the example script produces a dictionary of results, just use the parts you want

**Comment by saitoh183** [comment]
So custom script would 
- look in audiobook library folder
- Zip up the folder (would take the entire folder not just the files)
- Zip would be sent to /books/Author/Title/
- calibredb would called? (via LL or i would have to script it?)

**Comment by saitoh183** [comment]
> If you are using python, the example script produces a dictionary of results, just use the parts you want

Yeah thought so

**Comment by philborman** [comment]
Actually that might be a problem, I think calibre will be called before the notifier runs so the notifier gets the result of the download. You would need to run calibredb again inside the custom notifier, which is getting a bit messy.

**Comment by saitoh183** [comment]
Isnt calibre only called for ebooks? since Audiobooks are in there own directory, they shouldnt be affected by calibredb?

**Comment by saitoh183** [comment]
Ok

**Comment by saitoh183** [comment]
@philborman 

When starting the content server from within the container 
`/opt/calibre/calibre-server --daemonize --pidfile=/app/calibre-server.pid --port=9000 --listen-on=:: --log=/app/calibre-server.log --enable-local-write /books`

and i test calibredb i get this

![image](https://user-images.githubusercontent.com/1534197/41789384-1a64f572-761d-11e8-8efa-07d00578899f.png)

**Comment by philborman** [comment]
ok, so you are talking to calibredb, and calibredb is talking to the content server, which is talking to the database. Nearly there. Write failed is usually a permissions (database is redable but not writeable by calibredb) or authorization problem (you can read if not authorized, but can't write). See the lazylibrarian wiki page https://github.com/DobyTang/LazyLibrarian/wiki/Config_Processing

**Comment by saitoh183** [comment]
The write works when i disable the content server. At first i thought it was because i was using the content server of my Calibre-RDP container but i get the same problem using the content server of this container

**Comment by saitoh183** [comment]
Hi @philborman 

My script is almost finish but i still need to run LL library update via the script but cant find any reference to doing that.

>calibredb set_metadata --field author:authorname bookid

I tried this with --field tags:test and it returns Forbidden and if i just try --list-fields i get

Title                Field name 

Forbidden

**Comment by philborman** [comment]
You can run lazylibrarian library update from the lazylibrarian api, something like
http://192.168.1.2/lazylibrarian/api?apikey=whatever&cmd=forceAudioBookScan&wait&dir=sub_folder

For calibredb set_metadata you might need to include the library eg
calibredb set_metadata --field author:authorname --with-library library_or_server  bookid

**Comment by saitoh183** [comment]
@philborman 

> calibredb set_metadata --field author:authorname --with-library library_or_server bookid

yeah i did that and it still gives that result...it is not a big deal, i will just have to add the tag manually once the book is added to calibre/calibreweb

>You can run lazylibrarian library update from the lazylibrarian api, something like
http://192.168.1.2/lazylibrarian/api?apikey=whatever&cmd=forceAudioBookScan&wait&dir=sub_folder

Thanks i will give that a try
