### ISSUE TITLE
LL matching and unmatching

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1480]
Updating book location for Amanda Hocking Letters to Elise: A My Blood Approves Novella from /Users/kids/Calibre/Amanda Hocking/My Blood Approves (2819)/My Blood Approves - Amanda Hocking.mobi to /Users/kids/Calibre/Amanda Hocking/Letters to Elise_ A My Blood Approves Novella (2832)/Letters to Elise_ A My Blood Approves Nove - Amanda Hocking.mobi

 Updating book location for Amanda Hocking My Blood Approves from /Users/kids/Calibre/Amanda Hocking/Letters to Elise_ A My Blood Approves Novella (2832)/Letters to Elise_ A My Blood Approves Nove - Amanda Hocking.mobi to /Users/kids/Calibre/Amanda Hocking/My Blood Approves (2819)/My Blood Approves - Amanda Hocking.mobi

Updating book location for Brandon Sanderson The Hero of Ages from /Users/kids/Calibre/Brandon Sanderson/The Hero of Ages (8640)/The Hero of Ages - Brandon Sanderson.mobi to /Users/kids/Calibre/Brandon Sanderson/The Hero of Ages (14304)/The Hero of Ages - Brandon Sanderson.mobi

 Updating book location for Brandon Sanderson The Hero of Ages from /Users/kids/Calibre/Brandon Sanderson/The Hero of Ages (14304)/The Hero of Ages - Brandon Sanderson.mobi to /Users/kids/Calibre/Brandon Sanderson/The Hero of Ages (8640)/The Hero of Ages - Brandon Sanderson.mobi

There is a mobi and an epub file in the Sanderson directory and it's possible that I've merged the directories in Calibre.

There is only one "The Hero of Ages" directory.   The one ending in 14304 does not exist now.   Seems like that should be removed.

ls ~/Calibre/Brandon\ Sanderson/The\ Hero\ of\ Ages\ \(8640\)/
The Hero of Ages - Brandon Sanderson.epub	cover.jpg
The Hero of Ages - Brandon Sanderson.mobi	metadata.opf

 Updating book location for V.C. Andrews Heaven from /Users/kids/Calibre/V.C. Andrews/Heavenstone Secrets (10386)/Heavenstone Secrets - V.C. Andrews.epub to /Users/kids/Calibre/V.C. Andrews/Heaven (10358)/Heaven - V.C. Andrews.epub
 
Updating book location for V.C. Andrews Heavenstone Secrets from /Users/kids/Calibre/V.C. Andrews/Heaven (10358)/Heaven - V.C. Andrews.epub to /Users/kids/Calibre/V.C. Andrews/Heavenstone Secrets (10386)/Heavenstone Secrets - V.C. Andrews.epub

These are two different books in two different series.

 Updating book location for Joseph Wambaugh Hollywood Crows from /Users/kids/Calibre/Joseph Wambaugh/Hollywood Station (13291)/Hollywood Station - Joseph Wambaugh.mobi to /Users/kids/Calibre/Joseph Wambaugh/Hollywood Crows (13314)/Hollywood Crows - Joseph Wambaugh.mobi

 Updating book location for Joseph Wambaugh Hollywood Station from /Users/kids/Calibre/Joseph Wambaugh/Hollywood Crows (13314)/Hollywood Crows - Joseph Wambaugh.mobi to /Users/kids/Calibre/Joseph Wambaugh/Hollywood Station (13291)/Hollywood Station - Joseph Wambaugh.mobi

I'm looking for things like this:

 Updating book location for John Brunner Stand on Zanziba from /Users/kids/Calibre/John Brunner/Stand on Zanzibar (3875)/Stand on Zanzibar - John Brunner.mobi to /Users/kids/Calibre/John Brunner/Stand on Zanziba (9842)/Stand on Zanziba - John Brunner.epub

 Updating book location for John Brunner Stand on Zanzibar from /Users/kids/Calibre/John Brunner/Stand on Zanziba (9842)/Stand on Zanziba - John Brunner.epub to /Users/kids/Calibre/John Brunner/Stand on Zanzibar (3875)/Stand on Zanzibar - John Brunner.mobi

The book title should be "Stand on Zanzibar", not "Stand on Zanziba".

This grep looks like it will work well for finding many issues.

grep -i "failed to match" ~/src/LazyLibrarian-master/Logs/lazylibrarian.log | cut -f9- -d:  
[...]
 Failed to match book [Ye Who Would Sing] by [Alan Dean Foster] in database
 Failed to match book [Beautys Release] by [Anne Rice] in database
 Failed to match book [Violin] by [Anne Rice] in database
 Failed to match book [99 Novels] by [Anthony Burgess] in database
 Failed to match book [Blood of My Blood] by [Barry Lyga] in database
 Failed to match book [A Short History of the Internet] by [Bruce Sterling] in database
 Failed to match book [Buckymania] by [Bruce Sterling] in database
 Failed to match book [Shark Ship] by [C.M. Kornbluth] in database
 Failed to match book [Hornblower and the Widow McCool] by [C.S. Forester] in database
[...]

That grep did not find the "Zanziba" mismatch.

$ grep -i "failed" ~/src/LazyLibrarian-master/Logs/lazylibrarian.log* | grep Zanziba  | cut -f9- -d: 
$ 

It doesn't seem that there's really any harm done by this.  I would eventually like to have what's on the disks, in Calibre, and in LL matched up exactly.

**Comment by philborman** [comment]
For Stand on Zanzibar you have two copies in the calibre directory structure (the calibre directories have a number in brackets on the end). When we scan we don't know which we should use so end up flipping between the two. Best to merge the two in calibre so there is only one copy in the calibre directory structure. Stand on Zanziba (9842) Stand on Zanzibar (3875)

My Blood Approves (2819) Letters to Elise_ A My Blood Approves Novella (2832)
we think these are the same book so have the same problem and flip between them. Not sure if they are the same book, or if the 2832 title isn't in the librarian database under a similar enough name, eg just "Letters to Elise". The fuzzy matching can end up with the "my blood approves" part being a better match to  "Letters to Elise_ A My Blood Approves Novella" than "letters to elise"  ( 3 words matching out of 8 in each case, maybe a little worse as Elise is not the same as Elise_ )

For Hero of Ages
>There is only one "The Hero of Ages" directory. The one ending in 14304 does not exist now. Seems like that should be removed.

The folder was still there at the time you ran the last libraryscan. If you libraryscan again it should correct itself to the remaining 8640 folder.

Not sure what's going on with Heavenstone Secrets (10386) Heaven (10358) or 
Hollywood Crows (13314) Hollywood Station (13291)
would expect these to not be the same. Fuzzy matching library might be confusing them. Can we run libraryscan just on the troublesome authors with debug level 128 which turns on extra debugging in the fuzzy match process. You will generate a lot of log lines but we should be able to see why we're getting the wrong match. Might need to tweak the match percentage a little?

**Comment by dkids** [comment]
OK, I did library scan and grepped for the data (attached) but re-reading your message I'll update with just eBook scans for those authors.   I've got an RSS process running but I'll restart LL.

OK, first file has the results from eBook Scan for each author.  

[ebookscan.txt](https://github.com/DobyTang/LazyLibrarian/files/2129175/ebookscan.txt)

[hollywood.txt](https://github.com/DobyTang/LazyLibrarian/files/2129142/hollywood.txt)

[heavenstone.txt](https://github.com/DobyTang/LazyLibrarian/files/2129159/heavenstone.txt)



22-Jun-2018 10:31:15 - DEBUG   :: EBOOK_SCAN : librarysync.py:LibraryScan:504 : [/Users/kids/Calibre] Now scanning subdirectory /V.C. Andrews/Heaven (10358)
22-Jun-2018 10:31:15 - DEBUG   :: EBOOK_SCAN : librarysync.py:LibraryScan:539 : book meta [] [en] [V. C. Andrews] [Casteel 01 Heaven] [epub]
22-Jun-2018 10:31:15 - DEBUG   :: EBOOK_SCAN : librarysync.py:LibraryScan:571 : file meta [9781451636994] [eng] [V.C. Andrews] [Heaven] [787660]
22-Jun-2018 10:31:15 - DEBUG   :: EBOOK_SCAN : librarysync.py:LibraryScan:666 : Found Language [eng] ISBN [9781451636994]
22-Jun-2018 10:31:15 - DEBUG   :: EBOOK_SCAN : librarysync.py:LibraryScan:678 : Already cached Lang [eng] ISBN [145]
22-Jun-2018 10:31:15 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:172 : Searching database for [Heaven] by [V.C. Andrews]
22-Jun-2018 10:31:15 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:198 : Exact match [Heaven]
22-Jun-2018 10:31:15 - DEBUG   :: EBOOK_SCAN : librarysync.py:LibraryScan:876 : Librarysync link to preferred type epub: /Users/kids/Calibre/V.C. Andrews/Heaven (10358)/Heaven - V.C. Andrews.epub
22-Jun-2018 10:31:16 - WARNING :: EBOOK_SCAN : librarysync.py:LibraryScan:890 : Updating book location for V.C. Andrews Heaven from /Users/kids/Calibre/V.C. Andrews/Heavenstone Secrets (10386)/Heavenstone Secrets - V.C. Andrews.epub to /Users/kids/Calibre/V.C. Andrews/Heaven (10358)/Heaven - V.C. Andrews.epub
22-Jun-2018 10:31:16 - DEBUG   :: EBOOK_SCAN : librarysync.py:LibraryScan:893 : V.C. Andrews Heaven matched Open BookID 787660, [V.C. Andrews][Heaven]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:LibraryScan:504 : [/Users/kids/Calibre] Now scanning subdirectory /V.C. Andrews/Heavenstone Secrets (10386)
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:LibraryScan:539 : book meta [] [EN] [V.C. ANDREWS] [THE HEAVENSTONE SECRETS] [epub]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:LibraryScan:571 : file meta [9781439154953] [eng] [V.C. Andrews] [Heavenstone Secrets] [6329443]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:LibraryScan:666 : Found Language [eng] ISBN [9781439154953]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:LibraryScan:678 : Already cached Lang [eng] ISBN [143]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:172 : Searching database for [Heavenstone Secrets] by [V.C. Andrews]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:232 : Searching 133 books by [V.C. Andrews] in database for [Heavenstone Secrets]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 10 [heavenstone secrets][flowers in the attic]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 37 [heavenstone secrets][flowers in the attic]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 16 [heavenstone secrets][petals on the wind]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 27 [heavenstone secrets][petals on the wind]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 27 [heavenstone secrets][if there be thorns]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 43 [heavenstone secrets][if there be thorns]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 27 [heavenstone secrets][seeds of yesterday]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 32 [heavenstone secrets][seeds of yesterday]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 39 [heavenstone secrets][garden of shadows]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 41 [heavenstone secrets][garden of shadows]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 40 [heavenstone secrets][my sweet audrina]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 40 [heavenstone secrets][my sweet audrina]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 48 [heavenstone secrets][heaven]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 100 [heavenstone secrets][heaven]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 21 [heavenstone secrets][dark angel]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 30 [heavenstone secrets][dark angel]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 17 [heavenstone secrets][dawn]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 50 [heavenstone secrets][dawn]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 38 [heavenstone secrets][fallen hearts]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 46 [heavenstone secrets][fallen hearts]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 9 [heavenstone secrets][ruby]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 25 [heavenstone secrets][ruby]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 19 [heavenstone secrets][web of dreams]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 42 [heavenstone secrets][web of dreams]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 22 [heavenstone secrets][gates of paradise]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 35 [heavenstone secrets][gates of paradise]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 11 [heavenstone secrets][pearl in the mist]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 47 [heavenstone secrets][pearl in the mist]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 49 [heavenstone secrets][secrets of the morning]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 37 [heavenstone secrets][secrets of the morning]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 17 [heavenstone secrets][all that glitters]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 24 [heavenstone secrets][all that glitters]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 24 [heavenstone secrets][twilights child]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 22 [heavenstone secrets][twilights child]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 16 [heavenstone secrets][melody]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 17 [heavenstone secrets][melody]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 32 [heavenstone secrets][darkest hour]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 42 [heavenstone secrets][darkest hour]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 17 [heavenstone secrets][midnight whispers]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 42 [heavenstone secrets][midnight whispers]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 25 [heavenstone secrets][april shadows]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 23 [heavenstone secrets][april shadows]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 32 [heavenstone secrets][hidden jewel]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 33 [heavenstone secrets][hidden jewel]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 12 [heavenstone secrets][tarnished gold]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 21 [heavenstone secrets][tarnished gold]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 11 [heavenstone secrets][unfinished symphony]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 32 [heavenstone secrets][unfinished symphony]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 41 [heavenstone secrets][heart song]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 60 [heavenstone secrets][heart song]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 16 [heavenstone secrets][bittersweet dreams]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 40 [heavenstone secrets][bittersweet dreams]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 11 [heavenstone secrets][music in the night]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 28 [heavenstone secrets][music in the night]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 8 [heavenstone secrets][olivia]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 17 [heavenstone secrets][olivia]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 14 [heavenstone secrets][black cat]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 24 [heavenstone secrets][black cat]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 17 [heavenstone secrets][rain]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 25 [heavenstone secrets][rain]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 15 [heavenstone secrets][runaways]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 33 [heavenstone secrets][runaways]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 14 [heavenstone secrets][butterfly]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 22 [heavenstone secrets][butterfly]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 31 [heavenstone secrets][broken flower]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 38 [heavenstone secrets][broken flower]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 33 [heavenstone secrets][raven]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 80 [heavenstone secrets][raven]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 22 [heavenstone secrets][crystal (orphans, #2)]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 36 [heavenstone secrets][crystal (orphans, #2)]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 19 [heavenstone secrets][broken wings]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 33 [heavenstone secrets][broken wings]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 18 [heavenstone secrets][dollanganger boxed set: flowers in the attic / if there be thorns / petals on the wind / seeds of yesterday / garden of shadows(dollanganger, prequel-4]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 32 [heavenstone secrets][dollanganger boxed set: flowers in the attic / if there be thorns / petals on the wind / seeds of yesterday / garden of shadows(dollanganger, prequel-4]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 8 [heavenstone secrets][brooke]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 36 [heavenstone secrets][brooke]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 8 [heavenstone secrets][willow]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 17 [heavenstone secrets][willow]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 33 [heavenstone secrets][lightning strikes]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 41 [heavenstone secrets][lightning strikes]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 34 [heavenstone secrets][eye of the storm]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 44 [heavenstone secrets][eye of the storm]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 17 [heavenstone secrets][flowers in the attic/petals on the wind]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 42 [heavenstone secrets][flowers in the attic/petals on the wind]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 28 [heavenstone secrets][child of darkness]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 29 [heavenstone secrets][child of darkness]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 51 [heavenstone secrets][secrets in the attic]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 37 [heavenstone secrets][secrets in the attic]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 12 [heavenstone secrets][into the garden]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 48 [heavenstone secrets][into the garden]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 15 [heavenstone secrets][the end of the rainbow]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 42 [heavenstone secrets][the end of the rainbow]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 22 [heavenstone secrets][cinnamon]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 38 [heavenstone secrets][cinnamon]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 17 [heavenstone secrets][misty]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 40 [heavenstone secrets][misty]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 38 [heavenstone secrets][celeste]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 57 [heavenstone secrets][celeste]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 18 [heavenstone secrets][cat]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 33 [heavenstone secrets][cat]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 14 [heavenstone secrets][cloudburst]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 30 [heavenstone secrets][cloudburst]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 9 [heavenstone secrets][jade]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 50 [heavenstone secrets][jade]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 26 [heavenstone secrets][star]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 50 [heavenstone secrets][star]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 25 [heavenstone secrets][wicked forest]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 40 [heavenstone secrets][wicked forest]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 36 [heavenstone secrets][dark seed]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 44 [heavenstone secrets][dark seed]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 24 [heavenstone secrets][the wildflowers]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 40 [heavenstone secrets][the wildflowers]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 19 [heavenstone secrets][twisted roots]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 54 [heavenstone secrets][twisted roots]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:247 : Ratio 31 [heavenstone secrets][falling stars]
22-Jun-2018 10:31:17 - DEBUG   :: EBOOK_SCAN : librarysync.py:find_book_in_db:251 : PartialRatio 42 [heavenstone secrets][falling stars]

(not complete - decided it was better to upload the files)

**Comment by philborman** [comment]
Ok, that was useful, thanks.
Heavenstone:
We have two 100% matches
PartialRatio 100 [heavenstone secrets][heaven]
PartialRatio 100 [heavenstone secrets][the heavenstone secrets]
and one 90%
Ratio 90 [heavenstone secrets][the heavenstone secrets]

We prefer a high "ratio" match (over 90%), so it __just__ fails and we accept a high "partial" match (over 95%)

Ratio needs the words to be there, but allows the words to be in a different order, ie "Lord Of The Rings, The"  matches  "The Lord Of The Rings"  100%  

Partial allows "Lord Of The Rings"  to match  "The Lord Of The Rings" but because we are discarding info we need a higher threshold to be met, so we need 95%  instead of 90% for ratio match.

We can either tweak the ratio level so we use "greater than or equal to 90" or tweak the partial ratio so we prefer the "right" 100% match, so where we have two equal scoring matches we get the "best" one.
Need to think about how to do it...

It's a similar story with hollywood crows/hollywood station . There are two 100% matches for both, but that's complicated a bit more because the series name is hollywood station and we would need to make sure when choosing which of the 100% matches we don't confuse the series name with the book title.

**Comment by dkids** [comment]
It's not clear what the "right" thing to do is.  With older books that have multiple printings or multiple publishers there are title variations.    Modern books, like ones that are published through Amazon, can have lots of variations in the series name.

It would be great if there was one authoritative list where the variations could be handled.   But there doesn't seem to be anything out there.   

It may be something that just ends up being ignored.   Thanks for looking into it!

**Comment by philborman** [comment]
Some recent changes to the fuzzy matching code might have improved/fixed this, with the matches where the fuzz ratio is the same we choose the one with the most matching words. Should solve the "heavenstone" and "hollywood" examples above.
