### ISSUE TITLE
Option to pick Abridged vs Unabridged Audiobook with the reject list

### ISSUE THREAD

**Issue by ftpotential** [DobyTang/LazyLibrarian#1481]
For audiobooks from what I understand there is no way to get LL to ignore words in the reject list like "abridged" or "unabridged" if it is not in the title during the search/snatch. Would it possible to automatically add torrents in a paused state, check the name of the torrent file, parent folder, and grandparent folder(if it exists) for the words in the reject list if found run search again and mark the torrent as rejected and snatch the audiobook without the rejected word in title,filename and folders. like how the extension reject list works for transmission/deluge/qbittorrent.

In the post-process stage add (abridged) or (unabridged) to the folder so you only have to check the torrent listing(tracker) manually for the audiobooks without the (). Currently, I'm checking which file I download to know which version I have and manually changing. 

Very often (abridged) or (unabridged) is added in the folder or filename of audiobooks but always it is in the discription, label or tag fields on the torrent site, by using the torrent client + adding in a paused state it is not downloading yet so it isn't counted on the tracker as leeching so it could be done multiple time without HnR.

Sorry I don't know how to put the enhancement label

**Comment by philborman** [comment]
Checking the contents is fairly easy to add for torrents, can't do that for nzb though as there doesn't seem to be a way of getting a file list.

Not sure what you mean about "in the postprocess stage" paragraph, the checking would be done as soon as the file is requested, not during postprocessing (when the download is complete)

Reading the description/label/tag fields on the torrent site is a different issue, as the torrent sites all have different layouts. Some we use html page scraping, and some we use a search api. The search api doesn't give you that information.

**Comment by ftpotential** [comment]
Thats perfect, I hoping that was the case. I noticed there was no control in LL for audiobook version whether Abridged or unabridged but I seen the Extension reject list gets info from the torrent client so I was hoping the same could be done for Audiobook Reject list.



I meant to Add in Config_Processing an $Audiobookversion option to Foldername/Filename Pattern by looking in the download directory for (Abridged) or (Unabridged) in the filename or foldername.
Example:
eBook/AudioBook Foldername Pattern: $Author/$Title ($AudiobookVer)
Options: $Author, $Title, $Series, $SerName, $SerNum, $AudiobookVer, $$, any string.

AudioBook Filename Pattern: $Author - $Title ($AudiobookVer) $: Part $Part of $Total
Options: $Author, $Title, $Series, $SerName, $SerNum, $Part, $Total, $AudiobookVer, $$, any string.
Download source:
/downloads/completed/Benjamin Graham - The Intelligent Investor (Abridged)/Benjamin Graham - The Intelligent Investor - 101.mp3
Ebook directory:
/media/audiobooks/Benjamin Graham/The Intelligent Investor (Abridged)/Benjamin Graham - The Intelligent Investor (Abridged) : Part 01 of 17.mp3

So If the Audiobookversion is in the source file it will always have ($AudiobookVer) in the foldername if set in Config_Processing unless LL didn't find the ($AudiobookVer) info in the folder/file name from the downloads directory. so you only have to manually check your torrent tracker site for the ones left without ($AudiobookVer) in the title. 



I use MAM with jackett and Deluge, I read another comment about jackett that LL can only see titles so I was trying to say by doing the first part with the torrent add in a paused state + checking filename and foldernames for rejected words like (Abridged) or (Unabridged) + LL Postprocessing the adding ($AudiobookVer) in the filename or foldername if chosen then 70%-80% of the time LL can findout automatically as long it is setup with a supported torrent client is used (transmission/deluge/qbittorrent), put the unwanted Audiobook version in the Audiobook Reject list and setup Config-Processing to add $Audiobookver to folder or Filename.

 


I didn't explain enough in the first post and sorry if I wrote too much for this one, I'm excited since you said content search could be done easily from the torrent client. I like the ability to read along while listening to the audiobook or be able to pick up where I left off on both audio and ebook. So I currently have to check which one LL downloaded and if wrong I manually download, delete the unwanted and do a library scan(also means seeding two of the same audiobook).

**Comment by philborman** [comment]
Ok, had a quick look at this.
Using the reject list to select abridged/unabridged downloads can be easily added, but renaming to include the (Unabridged) in the title is more tricky. We use the embedded id3 tags to get author, title, narrator etc. Do you know (or can you check) if the abridged/unabridged is in a tag anywhere so we can look it up? If not we would need to work around it somehow.

The problem with using the filenames is the rename procedure, once we rename the files the info is lost, and the library we use to read id3 tags is read-only so we can't add our own tag. Could always change the library I suppose, but maybe the info is in a tag already, or maybe we can store the info elsewhere.

**Comment by ftpotential** [comment]
I just checked a few files, it looks like if the original source was audible they will have (Abridged) or (Unabridged) in the id3 title if the media kind is Audiobook or in the id3 album if media kind is music. Also, it looks like it only has (Abridged) or (Unabridged) in the title for audible sources if there are multiple versions, if the only audiobook made is unabridged there is nothing next to the title/album id3tag but uploaders might have (unabridged) in the filename or foldername. I used iTunes to look at the id3 tags. Regarding the library, maybe changing it (tinytag) to eyed3 could kill 2 birds with one stone. I looked into id3 tag scripts to convert LL file structure after PostP to id3 tag so I could use plex audible metadata scrapper, I didn't set it up but I have seen multiple batch scripts with eyed3 that could do it. So I think it could work well if eyed3 is used to read id3 and filename/foldername in the rename procedure and if (audiobookversion) is found edit id3 title and foldername with (audiobookversion). Being able to write id3 tags in LL could allow LL to do more PostP like edit incorrect id3 tags like if id3 title and LL Goodreads title match change author tad to LL author from Goodreads and if both author and narrator are in author tag like "First Last/First Last" (very common) LL moves the non author name to composer id3 tag field.  A checkbox added in Config_Processing "Rename ID3 tags on Library scan" could allow batch id3 editing in the library.

I didn't use the script but the above changes would take care of what I wanted. Also, it looks like with the unofficial Plex audiobook support and Embook plugin that's being developed for emby if id3 tags are automated in LL on download it would work seamlessly with Emby or plex metadata scrapers (idk if embook will use audible). 

eyed3 batch script 
https://superuser.com/questions/841967/how-can-i-batch-change-the-metadata-of-mp3-files

if id3 tagger that could edit id3 tags is used for future possibilities this would be cool 
https://community.mp3tag.de/t/ws-audible-albums-and-series/41227

**Comment by philborman** [comment]
Don't really want to add id3 editing to LL, there are plenty of editors out there anyway. The most I would do is add another tag to hold the "Abridged" status, but I think it's probably not necessary.

If the title tag already contains (Abridged) or (Unabridged) we will keep it as we don't alter the tags.
If it's in the filename and we are renaming the files we can choose to keep it or not. Just added some code to try that. New $Abridged option in config folder/filename patterns. I only have one audiobook with (Unabridged) so it's not had much testing, if you could try it and report back?   New version should be out in a couple of hours.
