### ISSUE TITLE
Skipping Magazines without issue numbers 

### ISSUE THREAD

**Issue by Bigmonty69** [DobyTang/LazyLibrarian#1489]
Before I post any logs etc I’ll just ask my question as it might be something easy I’m missing. 

I’m trying to download some magazines from my provider. I have added the magazine in LazyLibrarian then initiated the search. However LazyLibrarian only seems to be allowing ones that have an Issue no. in the title to download, it is skipping ones with just a name and a month in the title. I can manually go in after and look at the Skipped section and the magazine issues are there. 

Is there an option I am missing that is making it do this?

**Comment by philborman** [comment]
Lazylibrarian assumes magazines are ordered either by issue number, or by date. This is so we can decide if we've already got the issue, can't compare a number with a date. As there isn't a central registry of magazines to look at we go by the first issue we find, if that has a date we assume date based ordering, if not we reject dates and just go for issue numbers. It's rare to find magazines with both dates and issue numbers, or at least rare to find them all named that way by the uploaders.

You can override the default behaviour in lazylibrarian config->filters section, there is some information about it in the wiki "config filters" page, eg you can specify that the magazine title must contain a month and a year (MY) or must contain an issue number (I) as appropriate.
Probably best to remove all the existing issues of that magazine, set the filter, then start the search again as we store the most recent issue date/number to compare against, so if the last issue was a number and you say you only want dates nothing will appear to be "more recent"

**Comment by Bigmonty69** [comment]
Thanks you for the quick response.

I have tried what you suggested and deleted then re-added my Magazine with the filter (MY) in 'Magazines Reject Lists' / 'Date'.  Per your suggestion I was hoping this would ignore all Issue no.s in titles and just pull them based on the month and year of the title.  However this did not work.

As an example I am getting the following error in the log:

"This issue of Xbox The Official Magazine UK TruePDF August 2018 not in a wanted date format."

Every single month of the magazine gives the same error and nothing downloads.  If I was to remove the filter the only magazines that would get downloaded are ones from 2017 that have Issue no's in the title, it would miss everything from 2018 and they have been named without issues no.s, as per above.

Any help appreciated.

**Comment by philborman** [comment]
Latest release should fix it, the problem was we were hitting "regex 15" too early, this is "the title only includes a year" when clearly there was a month in there too.  The "old" reject reason is because if there is only a year we assume 1st Jan for date comparison.
