### ISSUE TITLE
Audiobooks not scanning

### ISSUE THREAD

**Issue by PeteB1983** [DobyTang/LazyLibrarian#1497]
To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

the audiobook search doesnt seem to be working, I was having some issues so went for a fresh install, but having set the audiobook location i have been attempting to scan the library and i am getting the following

2018-07-09 17:46:51 | WARNING | Cannot find destination directory: . Not scanning

i have checked the permissions on the folder (read and write to everyone), logged into terminal to check the map of the folder is working, and can see no difference between this and the calibre library location.
so i am now hoping its a bug.... which may be wishful thinking...
any help would be appreciated!

**Comment by philborman** [comment]
You are right, it's a bug.
New release is just about to go out, I will add the fix to it. Thanks for the bug report.

**Comment by PeteB1983** [comment]
amazing thanks....
my first assumption is normally I broke it ;-)

**Comment by philborman** [comment]
No, it was me. Not quite sure when, but it was definitely me.
Fixed now.
