### ISSUE TITLE
post processing not working for audiobooks through nzbget 

### ISSUE THREAD

**Issue by PeteB1983** [DobyTang/LazyLibrarian#1499]
To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

I think the issue may be related to the double folder issue.. However I am getting the error below which I assume relates to the syntax of the request.

and also I cant find a LL book serial number in the folder structure of the download so i guess that may be stopping post processing...

2018-07-09 21:28:19 | ERROR | Failed to get download progress from NZBGET for 6878: TypeError list indices must be integers, not str

**Comment by PeteB1983** [comment]
I turned on debug and got these..

2018-07-09 21:45:51 | ERROR | WEBSERVER | postprocess.py | getDownloadProgress | 1210 | Failed to get download progress from NZBGET for 6887: TypeError list indices must be integers, not str
2018-07-09 21:45:51 | DEBUG | WEBSERVER | nzbget.py | sendNZB | 90 | Successfully connected to NZBget
2018-07-09 21:45:51 | ERROR | WEBSERVER | postprocess.py | getDownloadProgress | 1210 | Failed to get download progress from NZBGET for 6888: TypeError list indices must be integers, not str
2018-07-09 21:45:51 | DEBUG | WEBSERVER | nzbget.py | sendNZB | 90 | Successfully connected to NZBget
2018-07-09 21:45:51 | ERROR | WEBSERVER | postprocess.py | getDownloadProgress | 1210 | Failed to get download progress from NZBGET for 6889: TypeError list indices must be integers, not str

**Comment by philborman** [comment]
LL doesn't use the serial number any more, and the "failed to get progress" message is not enough to stop postprocessing, we just don't know the progress to show in the history page. Postprocessor looks for the files, not the progress, so there is something else going on. Not sure what you mean by the "double folder issue". Maybe try debug level 64 which gives verbose postprocessor logging.

**Comment by PeteB1983** [comment]
Ahh ok, and sorry assumed it was important as it was kicking all the errors.
I meant issue #1484 as they have all come down in a folder within a folder... 
just trying to persuade it to snatch an audiobook now to get a debug log..

**Comment by PeteB1983** [comment]
confusingly it has worked... but I cant work out whats different... here is a log anyway... though i doubt they will help with an issue that didnt happen here...
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/2180563/debug.zip)

**Comment by philborman** [comment]
Most likely if it was nested further down? We only process the top level directory. There was a recent change where we now report in the log if we find multiple books in an archive. Not sure what's best to do with collections of books in an archive. We could try to find and extract the one book we wanted and discard the rest, we could import all of the books, or (easy way out) report it in the log and move on.

If it is an archive with multiple books _and_ you want them all, drop the archive into the "alternate import" directory and import it from there so the postprocessor doesn't get involved.

**Comment by PeteB1983** [comment]
Yeah I can see the complexity... the previous ones in nested folders were just one folder in another... not a bulk download.

if you were looking for my 2 cents, I would suggest trying to match every book against wanted and import everything in the wanted and bin the rest... as I tend to download a lot of one author or one series - so might get a Discworld or Terry Pratchett bulk download and actually want lots of them... 

I tried the alternate import with the selection of audiobooks I had sitting in the download folder and LL said they had no books in... so I put them in the right folder and scanned the library which got them.

interestingly I'm not sure if its the same issue but it just tried to post process a set of books and it looks like LL is denying knowledge of downloads it is waiting for... jim butcher dead beat had an epub in .. and i have now added azw as an ebook and included it in my calibre script.

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/2181266/debug.zip)

**Comment by philborman** [comment]
Gets complicated if you trigger say 6 downloads for 6 different books, and one of the downloads has the whole set in it. The other downloads won't be needed and will sit in the download directory unprocessed.
I think using lazylibrarian to search for individual books is fine but if you want to grab a collection it should be done manually.  

The alternateimport solution currently only works with ebooks, sorry about that, been meaning to get around to adding audiobooks to it. 

Looks like the Dead Beat searches were for an audiobook, which is why the epub, mobi, lit etc. all got rejected. There is a successful audiobook processed near the end of the debug.zip

**Comment by PeteB1983** [comment]
oddly just found that the calibre library has a mobi version... though LL thought i didnt have anything... and the LL Library is shared and just a scan of the calibre DB... 

the only thing I have accessing the calibre db other than LL is COPS and the attached script (please forgive the frankestein scripting... it was my first go - had to change name for it to upload)
[automated - Copy.log](https://github.com/DobyTang/LazyLibrarian/files/2181365/automated.-.Copy.log)

**Comment by PeteB1983** [comment]
How outrageous, software you offer for free and it doesn't do everything for me as soon as I think of it??? ;-)

they would have been for both... yeah the audio book came down but the ebook was wanted as well... I thought it had snatched them as there is a filter on epubs and files under 25mb for audio books

**Comment by philborman** [comment]
If you rescan the author from lazylibrarian with debug level 4096 (loglevels > 2 are a binary bitmask)
it will show why the book was ignored. Could be embedded metadata is wrong or file not in a wanted format, or under a different author, various reasons for rejecting or moving somewhere else.

I think downloading ebook and audiobook at the same time _should_ work, as long as they are in different downloads, we can't yet import an ebook and an audiobook from the same download. I will have a go and see what happens.

**Comment by PeteB1983** [comment]
they were 2 separate downloads and in 2 processes... the only think i can think is the ebook was bounced by calibredb which made it fail... and a rescan of the author added the .mobi
do you get a response from calibre if it already has the book? would it be worth retrying to add the file to the book ID? I had some issues a while ago with LL creating books in calibre without files and then calibre wont add as they exist already?

I think we have probably got to the point where my issue has gone and Im now just thinking out loud... feel free to close this once it bores you!

**Comment by philborman** [comment]
Calibre tells you the book already exists, but nothing more. No idea if the format you are trying to add is already there, or if calibre has a mobi and you have the epub. Not that helpful really, so we just report the calibre message and move on.
