### ISSUE TITLE
Deluge: Adding torrent file failed

### ISSUE THREAD

**Issue by robflate** [DobyTang/LazyLibrarian#1500]
LazyLibrarian version number: `6917a0c455f331c3ea3f985337a282152de1a3f2`
Operating system used: Docker container running on MacOS 10.13.4
Interface in use: bookstrap
Which api: Goodreads
Source of your LazyLibrarian installation: https://hub.docker.com/r/linuxserver/lazylibrarian/
Relevant debug log with api keys and any passwords redacted: [debug.zip](https://github.com/DobyTang/LazyLibrarian/files/2185015/debug.zip)

I keep getting failures when LL uses Jackett to send a torrent to Deluge. LL says `Deluge: Adding torrent file failed`. Here's some info that might be useful;

- LL returns `RuTracker test PASSED` when testing the tracker
- LL returns `Deluge: Connection successful Label is ok` when testing Deluge
- Jackett finds the torrent with a manual search and I can download it
- I can manually add the torrent to Deluge and it downloads
- Deluge Daemon 1.3.15 is connected
- LL succesfully passes nzbs to NZBGet using NZBHydra

Thanks

**Comment by philborman** [comment]
At first glance it looks like jackett is giving us an invalid torrent file?
Sending Deluge torrent with name  kbps and content [ZDg6YW5ub3VuY2UyMzpodHRwOi8vYnQ0LnQtcnUu...]

but I think it might have given us a b64encoded version, jackett does some odd things...

I will add a test to try decoding the jackett result in the next version, if you could try it and report back?

**Comment by robflate** [comment]
Thanks. I'll keep a look out for the next version and test.

**Comment by philborman** [comment]
I tried b64decoding the data and that looks like a valid torrent file, we're just not expecting it to be encoded. I have added a check to the code so if it doesn't look like a bare torrent we try decoding it and see if that looks like a torrent.

**Comment by robflate** [comment]
Here's the latest debug log showing a `Deluge UnicodeDecodeError`: [debug.zip](https://github.com/DobyTang/LazyLibrarian/files/2195275/debug.zip)

As before, the torrent is valid and can be downloaded from the URL at `LL > History > Failed`

**Comment by philborman** [comment]
Well, different error. Got past the first bit and hit another problem later on. Not enough info in the debug log to track it down though. Could you try again with debug level 16, should give us more info. Thanks.

**Comment by robflate** [comment]
Here you go: [debug.zip](https://github.com/DobyTang/LazyLibrarian/files/2195564/debug.zip)

**Comment by philborman** [comment]
You are not on latest version, latest is  c09de92    (first few digits are enough to identify it)
Your version is 9 days old.

>Also, how do I know I'm on the latest version? Is it just by going to the Config page and comparing Current to Latest. I assume Current is the version I'm on and Latest is the latest version on GitHub? 

That's correct as long as we can talk to github

>Do those number correlate with releases on GitHub...is there a page on GitHib where I can see those numbers? 

If you go to https://github.com/DobyTang/LazyLibrarian   latest is the most recent commit near top right of page. The "check version" button on lazylibrarian config page will tell you if you are up to date, show what's changed, and may let you upgrade depending on installation method. Some dockers may disable internal upgrade. "Releases" are different to "versions", and have a different numbering system. Releases are done much less frequently and usually indicate major changes. The releases page on lazylibrarian github doesn't get updated very often.

**Comment by robflate** [comment]
Thanks for the info.

I've updated to the latest version and this is now fixed. Thanks very much.
