### ISSUE TITLE
Failed to add nzbget download

### ISSUE THREAD

**Issue by tzortst** [DobyTang/LazyLibrarian#1504]
Downloads added to NZBGET Failed
Tried with different providers, all with same error

### LazyLibrarian version number (at the bottom of config page)
Branch: master : Updated: Thu Jul 12 09:59:53 2018
Current Version: d5728f1c49c1151c7aacda65416d2460be528088 : Latest Version: d5728f1c49c1151c7aacda65416d2460be528088

### Operating system used (windows, mac, linux, NAS type)
Windows Server 2016

### Interface in use (default, bookstrap)
Bookstrap

### Which api (Goodreads, GoogleBooks, both)
Goodreads

### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
git

### Relevant debug log with api keys and any passwords redacted
Unhandled exception in downloadResult: Traceback (most recent call last): File "C:\Software\LazyLibrarian\lazylibrarian\resultlist.py", line 279, in downloadResult controlValueDict["NZBurl"], newValueDict["AuxInfo"]) File "C:\Software\LazyLibrarian\lazylibrarian\downloadmethods.py", line 69, in NZBDownloadMethod downloadID, res = nzbget.sendNZB(nzb) File "C:\Software\LazyLibrarian\lazylibrarian\nzbget.py", line 132, in sendNZB nzbcontent64 = standard_b64encode(data) File "C:\Python3\lib\base64.py", line 95, in standard_b64encode return b64encode(s) File "C:\Python3\lib\base64.py", line 58, in b64encode encoded = binascii.b2a_base64(s, newline=False) TypeError: a bytes-like object is required, not 'str'

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/2195310/debug.zip)

**Comment by philborman** [comment]
Could you try running lazylibrarian under python2 instead of python3?
There are still some unresolved issues with python3 on windows, lazylibrarian/python3 works fine on linux  and on some users windows systems, but has problems on others. Not sure why.

**Comment by philborman** [comment]
Think I may have found the problem, an upgrade to latest version may fix it, if not try python2
