### ISSUE TITLE
No filenames returned by direct

### ISSUE THREAD

**Issue by paulmorabito** [DobyTang/LazyLibrarian#1507]
Whenever I add a book, Lazy Librarian downloads it and I can see it is in a folder in my lazy librarian install directory. However the post processor always returns a "no filenames returned by DIRECT".

The file repeatedly get snatched but never processed.

### LazyLibrarian version number (at the bottom of config page)
2377ecc9a2850b60a4c43aaccfd6e377e5568a37

### Operating system used (windows, mac, linux, NAS type)

Ubuntu 18.04

### Interface in use (default, bookstrap)

Bootstrap

### Which api (Goodreads, GoogleBooks, both)

Goodreads

### Source of your LazyLibrarian installation (git, zip file, 3rd party package)

Git

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report. 

17-Jul-2018 11:38:16 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:350 : Found 3 files marked "Snatched"
17-Jul-2018 11:38:16 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:988 : Blaine Harden - King of Spies LL.(39383536) was sent to DIRECT
17-Jul-2018 11:38:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:849 : No filenames returned by DIRECT for Blaine Harden - King of Spies LL.(39383536)
17-Jul-2018 11:38:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:907 : Blaine Harden - King of Spies LL.(39383536) accepted
17-Jul-2018 11:38:16 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:988 : Blaine Harden - The Great Leader and the Fighter Pilot LL.(25853013) was sent to DIRECT
17-Jul-2018 11:38:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:849 : No filenames returned by DIRECT for Blaine Harden - The Great Leader and the Fighter Pilot LL.(25853013)
17-Jul-2018 11:38:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:907 : Blaine Harden - The Great Leader and the Fighter Pilot LL.(25853013) accepted
17-Jul-2018 11:38:16 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:988 : Daniel Ellsberg - The Doomsday Machine LL.(25663779) was sent to DIRECT
17-Jul-2018 11:38:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:849 : No filenames returned by DIRECT for Daniel Ellsberg - The Doomsday Machine LL.(25663779)
17-Jul-2018 11:38:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:907 : Daniel Ellsberg - The Doomsday Machine LL.(25663779) accepted
17-Jul-2018 11:38:16 - INFO    :: POSTPROCESS : postprocess.py:processDir:735 : 0 books/mags processed.
17-Jul-2018 11:38:16 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:792 : Blaine Harden - King of Spies LL.(39383536) was sent to direct 88 minutes ago
17-Jul-2018 11:38:16 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:792 : Blaine Harden - The Great Leader and the Fighter Pilot LL.(25853013) was sent to direct 88 minutes ago
17-Jul-2018 11:38:16 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:792 : Daniel Ellsberg - The Doomsday Machine LL.(25663779) was sent to direct 86 minutes ago
17-Jul-2018 11:48:16 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:350 : Found 3 files marked "Snatched"
17-Jul-2018 11:48:16 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:988 : Blaine Harden - King of Spies LL.(39383536) was sent to DIRECT
17-Jul-2018 11:48:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:849 : No filenames returned by DIRECT for Blaine Harden - King of Spies LL.(39383536)
17-Jul-2018 11:48:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:907 : Blaine Harden - King of Spies LL.(39383536) accepted
17-Jul-2018 11:48:16 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:988 : Blaine Harden - The Great Leader and the Fighter Pilot LL.(25853013) was sent to DIRECT
17-Jul-2018 11:48:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:849 : No filenames returned by DIRECT for Blaine Harden - The Great Leader and the Fighter Pilot LL.(25853013)
17-Jul-2018 11:48:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:907 : Blaine Harden - The Great Leader and the Fighter Pilot LL.(25853013) accepted
17-Jul-2018 11:48:16 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:988 : Daniel Ellsberg - The Doomsday Machine LL.(25663779) was sent to DIRECT
17-Jul-2018 11:48:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:849 : No filenames returned by DIRECT for Daniel Ellsberg - The Doomsday Machine LL.(25663779)
17-Jul-2018 11:48:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:907 : Daniel Ellsberg - The Doomsday Machine LL.(25663779) accepted
17-Jul-2018 11:48:16 - INFO    :: POSTPROCESS : postprocess.py:processDir:735 : 0 books/mags processed.
17-Jul-2018 11:48:16 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:792 : Blaine Harden - King of Spies LL.(39383536) was sent to direct 98 minutes ago
17-Jul-2018 11:48:16 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:792 : Blaine Harden - The Great Leader and the Fighter Pilot LL.(25853013) was sent to direct 98 minutes ago
17-Jul-2018 11:48:16 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:792 : Daniel Ellsberg - The Doomsday Machine LL.(25663779) was sent to direct 96 minutes ago
17-Jul-2018 11:58:16 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:350 : Found 3 files marked "Snatched"
17-Jul-2018 11:58:16 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:988 : Blaine Harden - King of Spies LL.(39383536) was sent to DIRECT
17-Jul-2018 11:58:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:849 : No filenames returned by DIRECT for Blaine Harden - King of Spies LL.(39383536)
17-Jul-2018 11:58:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:907 : Blaine Harden - King of Spies LL.(39383536) accepted
17-Jul-2018 11:58:16 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:988 : Blaine Harden - The Great Leader and the Fighter Pilot LL.(25853013) was sent to DIRECT
17-Jul-2018 11:58:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:849 : No filenames returned by DIRECT for Blaine Harden - The Great Leader and the Fighter Pilot LL.(25853013)
17-Jul-2018 11:58:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:907 : Blaine Harden - The Great Leader and the Fighter Pilot LL.(25853013) accepted
17-Jul-2018 11:58:16 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:988 : Daniel Ellsberg - The Doomsday Machine LL.(25663779) was sent to DIRECT
17-Jul-2018 11:58:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:849 : No filenames returned by DIRECT for Daniel Ellsberg - The Doomsday Machine LL.(25663779)
17-Jul-2018 11:58:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:907 : Daniel Ellsberg - The Doomsday Machine LL.(25663779) accepted
17-Jul-2018 11:58:16 - INFO    :: POSTPROCESS : postprocess.py:processDir:735 : 0 books/mags processed.
17-Jul-2018 11:58:16 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:792 : Blaine Harden - King of Spies LL.(39383536) was sent to direct 108 minutes ago
17-Jul-2018 11:58:16 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:792 : Blaine Harden - The Great Leader and the Fighter Pilot LL.(25853013) was sent to direct 108 minutes ago
17-Jul-2018 11:58:16 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:792 : Daniel Ellsberg - The Doomsday Machine LL.(25663779) was sent to direct 106 minutes ago
17-Jul-2018 12:08:16 - DEBUG   :: POSTPROCESS : postprocess.py:processDir:350 : Found 3 files marked "Snatched"
17-Jul-2018 12:08:16 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:988 : Blaine Harden - King of Spies LL.(39383536) was sent to DIRECT
17-Jul-2018 12:08:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:849 : No filenames returned by DIRECT for Blaine Harden - King of Spies LL.(39383536)
17-Jul-2018 12:08:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:907 : Blaine Harden - King of Spies LL.(39383536) accepted
17-Jul-2018 12:08:16 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:988 : Blaine Harden - The Great Leader and the Fighter Pilot LL.(25853013) was sent to DIRECT
17-Jul-2018 12:08:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:849 : No filenames returned by DIRECT for Blaine Harden - The Great Leader and the Fighter Pilot LL.(25853013)
17-Jul-2018 12:08:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:907 : Blaine Harden - The Great Leader and the Fighter Pilot LL.(25853013) accepted
17-Jul-2018 12:08:16 - DEBUG   :: POSTPROCESS : postprocess.py:getDownloadName:988 : Daniel Ellsberg - The Doomsday Machine LL.(25663779) was sent to DIRECT
17-Jul-2018 12:08:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:849 : No filenames returned by DIRECT for Daniel Ellsberg - The Doomsday Machine LL.(25663779)
17-Jul-2018 12:08:16 - DEBUG   :: POSTPROCESS : postprocess.py:check_contents:907 : Daniel Ellsberg - The Doomsday Machine LL.(25663779) accepted
17-Jul-2018 12:08:16 - INFO    :: POSTPROCESS : postprocess.py:processDir:735 : 0 books/mags processed.

**Comment by philborman** [comment]
Yeah, it's just cosmetic. We have a new routine that queries the downloaders for the contents of the download so we can reject downloads that don't match names or size filters. The direct downloaders (libgen) can't tell us. I really should suppress the message if it's a direct download.

**Comment by paulmorabito** [comment]
Hi,

If it is just cosmetic then why does the file not post process? i.e. it is
not moved to the configured destination directory.

**Comment by philborman** [comment]
Good question, it's not the "no filenames" part though, the next line confirms the download was accepted
check_contents:849 : `No filenames returned` by DIRECT for Daniel Ellsberg - The Doomsday Machine LL.(25663779)
check_contents:907 : Daniel Ellsberg - The Doomsday Machine LL.(25663779) `accepted`

The direct downloader has presumably marked the book "Snatched" so not sure why we are re-snatching it, log doesn't show the download so can't be sure.
Also you get the line `Found 3 files marked "Snatched"`, then confirm each download is accepted, but there is no attempt to scan the download directory/directories for any results. Would expect to see something like Found 3 files in /home/me/Downloads/  or wherever you have configured lazylibrarian->config->processing->Download Directories. Can you check your config and make sure the setting for download directory looks ok, that's where the postprocessor looks for downloaded books.

**Comment by paulmorabito** [comment]
Hi,

You are current I had nothing entered into the Download directories so it
wasn't scanning there.

Thanks.
