### ISSUE TITLE
Adding Date to series folder

### ISSUE THREAD

**Issue by leaderdog** [DobyTang/LazyLibrarian#1510]
Hi Phil,

Sorry to bother you.  But I decided I want the start date of a series to precede the series name. so:

`David Anthony Durham\2007 - Acacia\Acacia - 01 - The War with the Mein.epub`
`David Anthony Durham\2007 - Acacia\Acacia - 02 - The Other Lands.epub`

is what I'm looking for

So I head over to Post-Processing in config and scratch my head a few times. and Logically (to me) it seems I should add to ebook/AudioBook Foldername Pattern:
`$Author\$PubYear$$ - $$$SerName`

Again, seems logical.
Save and added the David Anthony Durham for testing.

I select the two Acacia books to download and it sets to work downloading the second book in the series but not the first.

Folder shows up and, again I'm left scratching my head as my logical mind has failed me once again:
`H:\_ebooks\David Anthony Durham\2009 -\- 02 - The Other Lands.epub`

The other problem here is because it downloaded the second book the year for the folder became the wrong year for the series start.  The First book came out in 2007 so that should be the date on the folder.

Obviously, I did something wrong because, well, of course I did. :)  

Could you please tell me where/what I did wrong? I'm off to remove the stuff I put in.

Thanks and again sorry for my lack of understanding the post-processing.  My brain doesn't work in the format that it's listed in the config, so I just have a heck of a time figuring this out.

**Comment by philborman** [comment]
Can't do that, PubYear is the publication year of each book, not the start of the series. 
We don't know the start of the series, could possibly add another variable for the PubYear of the first book in the series, but at the moment no way of doing it.

**Comment by leaderdog** [comment]
Hi Phil,

aw shoot.  Ok ;)  

The reason for the series start date is to keep the books in order (just like the book in the folder is in place with the numbering).  

Some books like Mark Lawrence's will refer back to things in a previous series, so I figured if I had the start date for the series, then it helps to keep the reading order intact.

Understandably, a person could just check lazylibrarian for that info.

**Comment by philborman** [comment]
Should be working ok, seems to be here.
Try the api call I showed you before for testing. If you play with that until it gives the right info and then rescan it should all be ok.

**Comment by leaderdog** [comment]
hmm, so such is my luck that the one author I try and get it to work with doesn't have a series name listing just to confuse me. :)
`http://172.16.1.89:5299/api?apikey=2396df9c5ba4ceec7fa5c3e054b763e6&cmd=nameVars&id=6077427`
`{"PubYear": "2009", "Abridged": "", "FmtName": "", "SerNum": "2", "BookFile": "- 02 - The Other Lands", "Author": "David Anthony Durham", "FolderName": "David Anthony Durham\\", "SerYear": "2007", "SerName": "", "FmtNum": "- 02 -", "PadNum": "02", "Title": "The Other Lands", "AudioFile": "David Anthony Durham - The Other Lands: Part $Part of $Total", "FmtFull": "- 02 -"}`

But that doesn't make any sense, in the Author Page it lists Acacia 1 and Acacia 2 under Series name.  Or is that just listed wrong there?

Otherwise it does work.
I changed eBook/Audiobook Foldername Pattern to:
`$Author\$SerYear$$ - $$$SerName`

and ebook Filename Pattern to:
`$Series$$$Title$$ ($PubYear)$$`

and got my desired outcome:
`H:\_ebooks\J.V. Jones\2005 - Sword of Shadows\Sword of Shadows - 01 - A Cavern of Black Ice (2005).epub`

So, I'm guessing this issue is because the people that filled in the "api tags" just plain messed up?
2 books from J.V. Jones Sword of Shadows series weren't listed (Book 2 and 3).  I took them off ignore and set them to download and I got the wrong info after post-processing.

`Sword of Shadows - 02 - A Fortress of Grey Ice (Sword of Shadows, #2) ().epub`

when doing the check I get:
`{"PubYear": "", "Abridged": "", "FmtName": "Sword of Shadows", "SerNum": "2", "BookFile": "Sword of Shadows - 02 - A Fortress of Grey Ice (Sword of Shadows, #2) ()", "Author": "J.V. Jones", "FolderName": "J.V. Jones\\2005 - Sword of Shadows", "SerYear": "2005", "SerName": "Sword of Shadows", "FmtNum": "- 02 -", "PadNum": "02", "Title": "A Fortress of Grey Ice (Sword of Shadows, #2)", "AudioFile": "J.V. Jones - A Fortress of Grey Ice (Sword of Shadows, #2): Part $Part of $Total", "FmtFull": "Sword of Shadows - 02 -"}`

When this happens, we're just out of luck,?  I will just need to manually alter the file to make it organized with the other files?

Thanks again for your help Phil !

**Comment by philborman** [comment]
The info on goodreads is user submitted and not necessarily correct. Sometimes other users go in and correct it. In lazylibrarian you can alter the details we use ourselves on each books "manual" edit page. You can change title, author, series details and cover image. BTW latest version out later today shows the nameVars info on the config page so you can edit config and see how the naming will work out. 

Not sure why series info is in the author page but not showing in nameVars, should be reading the same info, need to look into that.

Also in book 2 above, Fortress of Grey Ice, there is no pubyear so you end up with empty braces. You can edit this in the "manual" page too, or put it into the filename without braces to look neater if there isn't a data available.

**Comment by philborman** [comment]
Just another thought, might be worth running "refresh author" on David Anthony Durham. I just loaded him and got this... No pubyear for book 3, but sername and sernum are there for both books.

{"Title": "The Other Lands", "SerYear": "2007", "SerNum": "2", "AudioFile": "David Anthony Durham - The Other Lands: Part $Part of $Total", "Abridged": "", "PadNum": "02", "FmtName": "Series: Acacia", "SerName": "Acacia", "FolderName": "David Anthony Durham/Acacia/02 - The Other Lands/", "FmtNum": "02 -", "Author": "David Anthony Durham", "BookFile": "The Other Lands (Acacia 02)", "FmtFull": "(Acacia 02)", "PubYear": "2009"}

{"Title": "The Sacred Band", "SerYear": "2007", "SerNum": "3", "AudioFile": "David Anthony Durham - The Sacred Band: Part $Part of $Total", "Abridged": "", "PadNum": "03", "FmtName": "Series: Acacia", "SerName": "Acacia", "FolderName": "David Anthony Durham/Acacia/03 - The Sacred Band/", "FmtNum": "03 -", "Author": "David Anthony Durham", "BookFile": "The Sacred Band (Acacia 03)", "FmtFull": "(Acacia 03)", "PubYear": ""}

**Comment by leaderdog** [comment]
hmm, I messed something up, or well I think but it's working differently now which is odd.

1) Using the above settings when there were books that weren't a part of the series they just got placed in the author folder. 
2) I tried moving the $PubDate before the $tittle. - This worked fine for the series it would just show:
`Sword of Shadows - 01 - (2005) - A Cavern of Black Ice.epub`
which is all good. buuut
3) single books now were put in a folder '-' 
4) after several failed attempts to fix this, I scrapped the idea and just copy pasted what I had above to just leave the pub date at the end of the file.
5) I still get a folder that is a '-' where it didn't behave like that before.  I did a clear cache and saved just in case, but that didn't fix it.

I realize, I'm calling for that dash in the folder name, but like I said, it used to only add it for the series.  Here's my settings at this point:

![settings](https://user-images.githubusercontent.com/39628596/43046151-e086ba3e-8db4-11e8-9564-8b965514f853.jpg)


I fiddled trying to get the pubyear to show up for the single files, but none of the single books have a pubyear listed, even though under release it has the year, and on good reads they say "Published April 1st 1999"

I'm so confused.

Not to be rude, I know you've been more than helpful with me on this, but couldn't you do something like Mylar does so that dashes. slashes and brackets are just recognized without any special string info to create your desired folder/series/single book information:
for example:
![mylar](https://user-images.githubusercontent.com/39628596/43046218-78ae7ebe-8db5-11e8-8c30-779fb08ce453.jpg)

Just have another one for individual books and audiobooks, It's just cleaner to figure out what needs to be done without the extra `$$ - $$` etc, I've literally spent the past hour and half trying to get it to do what I want and I'm more confused than when I started.

If each Format was it's own fill in box like Mylar it wouldn't take long to fill each out or leave them blank if not using (like I don't bother with audiobooks)
eg:
Folder Format: `H:\_ebooks\$Author`
Series Format: `$SerYear - $SerName\$SerName - $FmtNum - ($PubYear) - $Title`
Individual Book Format: `$PubYear - $Title\$PubYear - $Title`
same for audiofiles

(I guess I'm assuming it can put folder and name in the same line.  If not then of course you'd need a series folder and an individual book folder.  But again worse case scenario, you have two boxes to fill out for each series/individual book/audiobook.

That's the layout I have/want for the books and it's pretty simple to understand (I think).  The problem is, I don't have a technical mind like you do, the $stuff is second nature to you and other programmers, but us non programmers just look at the screen with mouth hung open and one eye squinted/twitching trying to figure out what is required in there.

instead of $FmtNum, I'd change it to $Numpad1 and $Numpad01  so you wouldn't need the extra line for the format since it's already done just needs the call to the numpad.

I realize there are some more variables with LL than with Mylar, but all the extra text and having numpad, series, and what not on separate lines is just not intuitive for most.  I haven't had this kind of trouble figuring out naming with any of the other auto downloaders.

again, not trying to be rude, or difficult, I just think the current layout is too hard for us simpler folk to understand. ;)

**Comment by leaderdog** [comment]
Hi Phil,

You're right, some issues would still persist due to lack of info from goodreads, out of curiosity, do the other book list sites have api's? where you could default/call to another if goodreads is missing some information to fill in the blanks?

And yeah, there are lots of crazy variables when it comes to books, but the existing layout requires a programmer to fill in.  I would have given up and just walked away if you hadn't stepped in to help me figure out the renaming (I did give up once before, but this time I decided to ask questions).  And I don't imagine you want that as your average experience when confronting the configuration.

I know I did that with Mylar when I first tried it. I got so confused and frustrated that I didn't use it for a couple years.  Then looked at it again and still found it challenging to install.  I ended up finding a walkthrough on how to install it on the web or I probably wouldn't have bothered at that point as well.

In my example of having separate boxes to fill in for each file format, it at least simplifies how the user enters the fields.  If some things aren't filled in, the user can add the date or series manually in their system.  As long as the majority of it is filled in that's better than nothing.  Missing information is out of your control as the developer.

But for series and for individual books, they can't really be handled the same and they can't really be handled to the users choice the way the layout currently is, at least not intuitively.

I tried logging in goodreads to change some of the api data, but I don't have access to it.  I can only change the pointless noob questions they give. haha

other API (but not sure if they're just swiping it from goodreads)
https://www.librarything.com/
https://www.libib.com/
https://openlibrary.org/dev/docs/api/books

I guess google books and amazon have api as well?

or even if these sites could be used to scrape a date/series name or whatever to offset the inconsistencies with goodreads.

**Comment by philborman** [comment]
Maybe better documentation is the answer here rather than anything too radical unless we can copy a much better solution from somewhere else.

We used to use librarything for all the series info, but unfortunately they disabled their api because of overuse (I hope it wasn't us ;-)  We used to get much more complete series info than goodreads using the librarything "whatwork" interface. You could give it a book and it would tell you all the series the book was part of, and all the other members of the series, and all the authors contributing to the series. Shame it got disabled really.

Googlebooks is shocking at series info, and the info that it does have isn't searchable unless you know the exact series name they have stored it under. 

Amazon requires each user of a program (ie each lazylibrarian user) to sign up and get their own amazon developer key, no key sharing allowed.

Don't know about libib or openlibrary.org, but I will take a look, and the other difficulty with mixing providers is they are not consistent. ie librarything sometimes called a book 3.5 in a series where goodreads had it as book 4 so all the others were out by one. 

The latest lazylibrarian (as of a few minutes ago) has a few more details in config including examples generated from your format strings, which might help a little. In the meantime I will look into what else can be done.

**Comment by leaderdog** [comment]
aw too bad about librarything. haha

I would still strongly encourage you to talk to Evilhero from Mylar,  He is incredibly helpful.  He helped me with a completely unrelated computer problem (parking an old website i used to run).  

When I found a different site for him to get way better information from for weekly releases, he used that and had to come up with a way to get the information without having each Mylar user to touch that site.  He set something up so that we went through that site with the gathered information instead of hitting the website he was gathering it from.  Thus preventing over use etc for the main information site.

But to the renaming issue here.  This definitely helps to understand what's going on better, but I'm still running into the same problem, The current layout is all based on series information.  So when individual books pop up, I end up getting them put into a folder that is a dash.

I know this is the problem: `$Author\$SerYear$$ - $$$SerName`

but I don't know how to make it all disappear or allow for the individual books to be put in their own folder based on `$pubyear - $Title`
It's like an either or situation not both?

Or is there a way to do that?
![new setting](https://user-images.githubusercontent.com/39628596/43049200-26e2152c-8de3-11e8-9da9-30f6b80d3cf1.jpg)

Thanks again, Phil,

**Comment by philborman** [comment]
If you don't include the dash it will work,  $Author\$SerYear$$ - $$$Sername if there is no series will return $Author\
Alternatively since you are not using the $FmtName variable anywhere in your file/folder patterns, you could use that. You have $FmtName as series_year - series_name,  if these are both empty then FmtName is also empty, no dash

BTW - libib doesn't look useful, but openlibrary could be a useful source of publication date and book covers

**Comment by philborman** [comment]
Actually, scrap the fmtname option,  it's broken. Still returns dash when it shouldn't.
Will fix it tomorrow

**Comment by leaderdog** [comment]
Hopefully that site will help, Would be handy to have all the pertinent information ;)

**Comment by leaderdog** [comment]
Hi Phil, 

I think you fixed the $FmtName``  It seems to work, The series folder and naming works the way I like, and the one off books just sit in the main Author folder.  That's fine.

It shows up as: `() - The Barbed Coil.epub`
but I figured, I can just add the date. It has it in Released in lazy librarian, but it doesn't have it listed in the pubdate.  So I just added 1999 in the folder.

I ran ebook scan just to see if it still recognized the file and it took the 1999 out of the brackets. :)

haha

Here are the settings I went with:
![settings2](https://user-images.githubusercontent.com/39628596/43239272-1b4846a0-9081-11e8-9222-66c927fc29fc.jpg)

I guess that's as good as I can expect for the format I want.  Any luck with libib?  Will it work to help fill in some missing information?

**Comment by philborman** [comment]
Nothing useful from libib unfortunately, doesn't seem to have an api we can use, unless it's only in the pro version?  Series dates are being worked on, the current release (earlier today) now grabs original publication dates for books in a series, doesn't do non-series books yet as there are limits to how many times we can call the goodreads api, and how quickly.

For the filenames like () - The Barbed Coil.epub  you can edit the pubdate in the book "manual" edit page, and then tick the "lock" button so we don't overwrite the info on a rescan. 

If you want to lose the  () -   part, the punctuation needs to be part of one of the series variables, so if there is no series name the whole lot returns empty, so maybe change series pattern to  `$SerName$$$FmtNum$$($PubDate) -`  and ebook filename pattern to `$Series$$$Title`  so if there is no series your book filename is just Title

**Comment by leaderdog** [comment]
Hi Phil,

Crappy about libib.

is is `$PubDate` or `$PubYear`?

The series is working the way I like.  It's the individual book (or this particular book) that is struggling with the date.  I clicked the edit like you suggested and this is what I see in there:
![pubdate](https://user-images.githubusercontent.com/39628596/43349625-a99d4d36-91f0-11e8-90c5-8a49ca1fb4ff.jpg)


It shows up as published 1999 but it doesn't send that value to the post-processing?

**Comment by philborman** [comment]
Yeah, PubYear not date, it was date for a while as sometimes you can get month and day too.
If it's in the manual edit page it should really show in the nameVars api call too, as they read the info from the same place?  Will need to look into it.

**Comment by philborman** [comment]
ok, it was a bug. Fixed now, will push a new version later today.

**Comment by leaderdog** [comment]
/raises hit foot high and slams it down!!

Another bug squashed! :)

Awesome! I look forward to messing with it later today.

Thanks Phil
