### ISSUE TITLE
Missing Library For SSL/HTTPS

### ISSUE THREAD

**Issue by Luminaii** [DobyTang/LazyLibrarian#1513]
Hello,

When trying to enable SSL in the settings of LazyLibrarian it says I'm missing the pyOpenSSL library.
I'm currently on commit 6f0bef42da1b9add4c582af2690e52db8e9273e0.

**Comment by philborman** [comment]
Not all python installations include all the necessary libraries, see the wiki
https://github.com/DobyTang/LazyLibrarian/wiki/SSL-Errors

Depending on your operating system and installation you may be able to install the libraries using your system package manager, or from a terminal using pip
