### ISSUE TITLE
Form Authtentication

### ISSUE THREAD

**Issue by Luminaii** [DobyTang/LazyLibrarian#1514]
Hello,

Not really an issue but more a question/idea.
Is there any support for form authentication planned instead of the basic authentication which is currently used?

**Comment by philborman** [comment]
There is form based authentication if you enable user accounts in config (and remove webserver user and password). There is only one user account set up by default, admin with password admin. You should be prompted to change this password, or create a new admin account under another name and delete the old account.

**Comment by Luminaii** [comment]
I see.
I enabled it and tried to add my own account but I couldn't add it because I can't send any mail. I then added an smtp account to email notifications. I can't however get a successful test. I'm not sure what is going wrong. Is there anyway I can debug the email sending?

**Comment by philborman** [comment]
Maybe the debug log will show what's going wrong?

**Comment by Luminaii** [comment]
I'm not getting anything in the console or in the lazylibrarian.log

**Comment by philborman** [comment]
If debug is turned on you should at least get messages saying 
Email notification:
Email from:
Email to:
Email text:

and then if it fails
Error sending Email: and a reason

Maybe try enabling the notifier, and also "notify on download" in case we're exiting too early on a test

**Comment by Luminaii** [comment]
Well, when I check notify on download it's immediately successful. I don't however, want to receive an email. I've already setup telegram and don't want duplicate notifications

**Comment by philborman** [comment]
Yes it's really just to check the email process is working, the only email you would get is the login info, so you _should_ be able to create new user accounts now that's working. I'm assuming the settings were wrong when you tried before?

If you go to config, the UserAdmin button near the top, add new user, fill in the details and hit save the new users account should get an email. You don't need the notifier to be active at this point, the new user admin just shares the same smtp server. I don't think we even care if the users email is valid, as long as it looks like a valid email address.

**Comment by Luminaii** [comment]
No the settings were the same. I just checked the send notification on download and it starts working. I couldn't add users before I checked it, but afterwards I could. I now unchecked it and checked if I could still make users and it still works. It seems it needed an initialisation run.

**Comment by philborman** [comment]
Weird, it should just work, no initialisation needed?
I will need to look into why you need "notify on download" checking, the test case shouldn't need it.
