### ISSUE TITLE
Force Library Scan Errors with "ERROR	Unable to complete the scan: global name 'etree' is not defined"

### ISSUE THREAD

**Issue by philborman** [DobyTang/LazyLibrarian#152]
Issue 150 marked as closed, but the fix doesn't actually fix the issue, will hit errors scanning mobi and epub files.
 
unidecode references now all need changing from unidecode.unidecode() to unidecode() now library is in lib.unidecode, easy to fix.

lxml.etree returns different data to xml.etree.ElementTree so new books aren't found now, just appears to work. Harder to fix. For now we need an external lxml library, unless someone with more python/xml experience can get the etree section to work with ElementTree

**Comment by theguardian** [comment]
lxml is notoriously difficult to build for linux newbs, and impossible to build on NAS appliances that don't support installation of required dependencies such as python-dev (e.g. QNAP, Synology, etc.)

So it sounds like the options are to somehow build lxml and include it as a lib within the repo, or to rewrite some of the xml parsing that xml.etree can handle?

**Comment by philborman** [comment]
I tried building lxml and including it as a lib, but it seems lxml is architecture dependant. I run on Ubuntu linux and Raspberry Pi arm.  Amazon example code uses lxml and I wanted to add amazon books as an additional source.

Do you have any experience with lxml? I have none at all. Totally new to xml/etree and fairly new to python (as you can probably tell!)

What we need is a way to read author,title,language,isbn from an .opf file
I found an example using lxml and used that. Can't seem to find an example using ElementTree and don't have the experience to write one from scratch.

**Comment by theguardian** [comment]
Cool. I'm going to do some end-end testing this evening to clean up the existing code in debug mode. I'll take a look at .opf files and see if xml.etree can be used

**Comment by theguardian** [comment]
LL should function normally now.

Re: .opf files:
It looks like LL is able to write .opf files in postprocess.py, so it makes sense that they should also be able to be extracted with the current python packages. There's some documentation here: https://docs.python.org/2/library/xml.etree.elementtree.html

I'm not terribly familiar with lxml, but yup - it's architecture dependent, which is why most python-based web apps avoid it. Assume the user doesn't have the chops to make builds.

... and welcome to python programming! It looks like your learning path is much like mine. I learned python by forking python web apps and adding a feature here and there. I'm by no means an expert by any stretch of the imagination. I've just been around long enough to know that apps like Sabnzbd+, SickBeard/SickRage, Headphones, CouchPotato, etc are all based on the same general framework and they all follow similar patterns.

**Comment by theguardian** [comment]
librarysync.py still fails due to the lxml/xml.etree errors if the user clicks "Library Scan" from the Authors page. I'm going to rename this issue to reflect the remaining error.

**Comment by philborman** [comment]
Thanks for the pointer to ElementTree documentation, I have rewritten 
the librarysync routine to use this instead of lxml.
Deleted lazylibrarian.db and re-scanned my library and it works as expected.
Do you want me to put in a pull request from my fork of the repo, or 
what's best as my fork doesn't match DobyTang now with the changes.
How do I tell git to merge your changes into my fork?

Thanks,
Phil.

**Comment by theguardian** [comment]
I think the best/fastest way would be to save your new updated version of librarysync.py somewhere safe, then do the following:

git checkout <branch> //switches to desired local branch
git remote update // captures information of origin & upstream
git reset --hard upstream/master // gets snapshot of newest master
git push origin +<branch> // updates your fork/branch to match latest upstream/master

At this point, a branch in your fork will be a perfect reflection of LL master.

Then simply copy the contents of your new librarysync.py over the old librarysync.py, commit, push and issue a pull request.

There are other ways, but that's the safest/cleanest in my experience.

**Comment by philborman** [comment]
Thanks, should get this done tonight.
I have also added back in the stats table that was removed from gb.py 
and gr.py, it's useful for checking the libraryscan runs properly. The 
comment says the table isn't in __init__.py, which is correct. I delete 
any old stats table and create it on the fly in librarysync.py
