### ISSUE TITLE
LL pings github every 5 seconds

### ISSUE THREAD

**Issue by wizzy99** [DobyTang/LazyLibrarian#1526]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
4dceecd9a9ecb06d6d4863cf8b6d84bad7b89e6e
### Operating system used (windows, mac, linux, NAS type)
linux (fc28)
### Interface in use (default, bookstrap)
bookstrap
### Which api (Goodreads, GoogleBooks, both)
github
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
docker;  image: thraxis/lazylibrarian-calibre:latest
### Relevant debug log with api keys and any passwords redacted

I noticed a 403 (forbidden) error in one of my logs and found that I'd maxed the daily github calls.  I'm seeing that LL is hitting github every 5 seconds. I don't know if it's always doing it, but it seems to be the default behavior if it can't get the version.  My config is to check for a new version every 24 hours. versioncheck_interval = 24

lazylibrarian.log.9:31-Jul-2018 06:36:17 - WARNING :: MAIN : versioncheck.py:log
msg:45 : Could not get the latest commit from github
lazylibrarian.log.9:31-Jul-2018 06:36:22 - WARNING :: MAIN : versioncheck.py:log
msg:45 : Could not get the latest commit from github
lazylibrarian.log.9:31-Jul-2018 06:36:26 - WARNING :: MAIN : versioncheck.py:log
msg:45 : Could not get the latest commit from github
lazylibrarian.log.9:31-Jul-2018 06:36:31 - WARNING :: MAIN : versioncheck.py:log
msg:45 : Could not get the latest commit from github
lazylibrarian.log.9:31-Jul-2018 06:36:36 - WARNING :: MAIN : versioncheck.py:log
msg:45 : Could not get the latest commit from github

**Comment by philborman** [comment]
Interesting, seems to be stuck in a loop, can't immediately see why... 
I tried disabling my internet so lazylibrarian can't contact github, but unfortunately that works as expected, so I think somehow we are contacting github but not getting the right reply?
If it's still doing it, can you turn debug on (without stopping it) as there are two places that generate that message and it would narrow it down if we knew which one it was.

**Comment by wizzy99** [comment]
Unfortunately I'd already restarted it and it seems to have settled down.  I'll turn on debug if it resurfaces.
