### ISSUE TITLE
Exception in thread DBIMPORT:

### ISSUE THREAD

**Issue by Bacchusm** [DobyTang/LazyLibrarian#153]
20-Oct-2015 21:00:34 - INFO :: DBIMPORT :: Now updating author: Danielle Steel
20-Oct-2015 21:00:34 - DEBUG :: DBIMPORT : Searching for author with name: Danielle Steel
20-Oct-2015 21:00:34 - ERROR :: DBIMPORT : Error fetching authorid: undefined entity: line 47, column 90http://www.goodreads.com/api/author_url/Danielle%20Steel?key=+g1vzTiRr6MOJg3LCl29slA
Exception in thread DBIMPORT:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/lazylibrarian/lazylibrarian/importer.py", line 31, in addAuthorToDB
    author = GR.find_author_id()
  File "/opt/lazylibrarian/lazylibrarian/gr.py", line 163, in find_author_id
    rootxml = sourcexml.getroot()
UnboundLocalError: local variable 'sourcexml' referenced before assignment

I am getting this error each time I try to add an author.  I am running on a Raspberry PI.  I tried removing and reinstall the programs, delete the database.  

Any help would be appreciated. 

Thank You

**Comment by philborman** [comment]
There have been some conflicting changes to xml handling that may be responsible for this, a new commit was made a few hours ago. Try re-downloading from the git repository. In addition to deleting the database, delete the caches .lazylibrarian/.AuthorCache  and .lazylibrarian/.ProviderCache

**Comment by Bacchusm** [comment]
Now it is working.  Thank You!
