### ISSUE TITLE
ebook is tagged as an audibook

### ISSUE THREAD

**Issue by adispi** [DobyTang/LazyLibrarian#1531]
To help with identifying and fixing issues, please include as much information as possible, including:
### synocommunity, however, updated via git

ebook are tagged as audiobook, and failed on post processing.
there should be a check for a size, as most audibooks are not less then a MB... (usually more then 100MB).

Adi

**Comment by philborman** [comment]
There are settings in config->filters where you can control sizes and extensions to accept/reject for each type, but not all providers give us enough info. Some torrent or magnet links don't give sizes, and most nzb don't give us a file list, so for those we have to download and then look at what we got sent, and then reject. Should automatically retry for a different copy though.
