### ISSUE TITLE
X next to filter on Manage screen not working

### ISSUE THREAD

**Issue by wizzy99** [DobyTang/LazyLibrarian#1533]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
9bdc7a4c844ab7eaaeb3f17fb3faa788254334da
### Operating system used (windows, mac, linux, NAS type)
fedora
### Interface in use (default, bookstrap)
bookstrap

Clicking the X next to the filter box to remove the current contents of the filter doesn't seem to work.  It blanks the box, refreshes the screen, and the word remains in the box with the filter applied.

This same function works just fine on the other screens.

**Comment by philborman** [comment]
Odd, hadn't noticed that here, but had a play and it seems to be intermittent. Often works as expected, then occasionally fails but clicking it again works. Needs looking into.

**Comment by philborman** [comment]
Hmm, actually it's not working properly on the other screens either, for example if you go to series page, select only Complete series, then hit the 'X' on the filter it resets the page to show all series.

Can't see where I lifted that code from, and can't find another example anywhere. Might remove the 'X' completely, what do you think?

**Comment by wizzy99** [comment]
I do find the X handy when it works.

**Comment by philborman** [comment]
Found the problem, should be fixed in next release.
