### ISSUE TITLE
Magazine fetch error

### ISSUE THREAD

**Issue by Code-Slave** [DobyTang/LazyLibrarian#1538]
Using the latest

  | Error  fetching url  https://thepiratebay.rocks//https://thepiratebay.rocks/torrent/19044193/American_Survival_Guide_-_January_2018,  Response status 404: not_found
-- | --

double urls

**Comment by philborman** [comment]
Not enough info to go on, we just use the url the tor provider gave us. Could be jackett mangling things (if you use it), or redirecting us to a different address, or maybe thepiratebay.rocks is giving us wrong info, or a different format?  I use piratebays.co  with no problems.
Would be useful to see a debug log of a search for one book/mag with all other providers switched off to reduce noise.

**Comment by Code-Slave** [comment]
thanks
