### ISSUE TITLE
DelugeVPN Docker Issues; Best torrent client?

### ISSUE THREAD

**Issue by bmilcs** [DobyTang/LazyLibrarian#1552]
Hello,

Very simple question -- what is the best performing Torrent Client for use with LazyLibrarian?

**Comment by philborman** [comment]
Personally I use transmission. It's lightweight, small memory and cpu footprint so it runs headless on my relatively low powered raspberry pi. "best performing" depends a lot on your use case.
Having said that, deluge also has a headless daemon mode and qbittorrent and utorrent have nicer interfaces than transmission, depends what you want. If you have a free choice I would avoid rtorrent as it's not got such a good api for us to talk to to get progress info and filenames.
