### ISSUE TITLE
rtorrent error: Could not find info-hash

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#1554]
Has anything changed for rtorrent in LL lately?  It appears nothing has sent to rtorrent for me in 13 weeks.  I'm getting the following error: 

`29-Aug-2018 14:50:02 - DEBUG   :: SEARCHBOOK : rtorrent.py:getServer:45 : rTorrent client version = 0.9.6
29-Aug-2018 14:50:09 - ERROR   :: SEARCHBOOK : rtorrent.py:addTorrent:102 : rTorrent Error: Fault: <Fault -501: 'Could not find info-hash.'>
`
Caveat:  I'm using jackett, and I've tried two different jackett installations.  downloadmethods.py is getting the file from jackett, and I've verified it by copying the url and downloading it manually.  I've also been able to upload the downloaded file to the rutorrent interface, and it succeeds.

I'm just not sure where to debug further.  Any suggestions?

To help with identifying and fixing issues, please include as much information as possible, including:

**Comment by DarkSir23** [comment]
It is a URL, and I'm happy to try :)

**Comment by philborman** [comment]
ok great thanks,
first thing is to find out exactly what we are sending to rtorrent, so in downloadmethods.py line 365
downloadID, res = rtorrent.addTorrent(tor_url, hashid)
just after that we need to add 
logger.info("URL: %s" % tor_url[:40])
logger.info("HASH: %s" % hashid)
logger.info("DATA: %s" % torrent[:40])

this is just to make sure the values look sensible, and to check torrent isn't empty and whether it is already encoded. We don't currently use torrent data in rtorrent, just the url and hash but we could maybe use data instead, that works with jackett/deluge

**Comment by DarkSir23** [comment]
False alarm, sorta.  It seems that since my Jackett instance was on the local network, but the rtorrent wasn't, it couldn't see the URL.  It might be good to send the data rather than the torrent for that reason, but it's not an encoding thing, it seems.

**Comment by DarkSir23** [comment]
`30-Aug-2018 10:29:06 - DEBUG   :: SEARCHBOOK : rtorrent.py:getServer:46 : rTorrent client version = 0.9.6
30-Aug-2018 10:29:06 - DEBUG   :: SEARCHBOOK : rtorrent.py:addTorrent:78 : Sending rTorrent content [d8:announce79:http://t.obfuscated.net/...]
30-Aug-2018 10:29:06 - ERROR   :: SEARCHBOOK : rtorrent.py:addTorrent:105 : rTorrent Error: Fault: <Fault -503: 'Call XML not a proper XML-RPC call.  Call is not valid XML.  XML parsing failed'>
30-Aug-2018 10:29:06 - ERROR   :: SEARCHBOOK : downloadmethods.py:TORDownloadMethod:511 : Failed to send torrent to RTORRENT
`

**Comment by philborman** [comment]
ok so it looks like we do need it encoded...
Two options, 50/50  Try this one first...
[rtorrent.zip](https://github.com/DobyTang/LazyLibrarian/files/2336667/rtorrent.zip)

**Comment by DarkSir23** [comment]
`30-Aug-2018 11:04:01 - DEBUG   :: SEARCHBOOK : rtorrent.py:getServer:46 : rTorrent client version = 0.9.6
30-Aug-2018 11:04:01 - DEBUG   :: SEARCHBOOK : rtorrent.py:addTorrent:78 : Sending rTorrent content [d8:announce79:http://t.obfuscated.net/...]
30-Aug-2018 11:04:08 - ERROR   :: SEARCHBOOK : rtorrent.py:addTorrent:105 : rTorrent Error: Fault: <Fault -501: 'Could not find info-hash.'>
30-Aug-2018 11:04:08 - ERROR   :: SEARCHBOOK : downloadmethods.py:TORDownloadMethod:511 : Failed to send torrent to RTORRENT
`

**Comment by philborman** [comment]
It's fun trying to debug without a working rtorrent to try and no documentation ;-)
Here is another attempt to get the data sent to rtorrent, and an attempt to send the index for getDownloadFiles
[rtorrent.zip](https://github.com/DobyTang/LazyLibrarian/files/2336845/rtorrent.zip)

**Comment by philborman** [comment]
Think it's fixed now. rtorrent does need the data encoding, just not in the same way as any of the other torrent downloaders :-)
[rtorrent.zip](https://github.com/DobyTang/LazyLibrarian/files/2340006/rtorrent.zip)
I think the progress bar and postprocessor should be ok now too, but the extra debug lines are still in there to check...
