### ISSUE TITLE
LL matching single books to entire Goodreads Series

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#1555]
This seems relatively new, but it's importing whole series as individual titles from GoodReads, and then when it tries to download them, it's matching a single book, and processing it as the entire series.  

A: Is there a way to stop LL from importing GoodReads whole series entries?
B: Is there a way to remove the ones that are already there?
C: I also have several books that added before I refined the language filter.  Is there a way to remove those?

**Comment by DarkSir23** [comment]
I think I found the answer to A

**Comment by philborman** [comment]
Sorry, not sure what you mean with A and B
For C you can use the language filter on the ebooks page to select each language you don't want, and either delete or mark the books as ignored

**Comment by DarkSir23** [comment]
It appears to be the ones that had no language.  And there are thousands of them.  Regarding A, I'm guessing it's the "ignore sets" option in config.  I was just hoping there was a way to mass remove the ones that had already been added to authors.

**Comment by philborman** [comment]
You can do it from sqlite, but not inside lazylibrarian, but there is an api call to list them...
listNoLang
If you run the list and it looks ok, in sqlite3
delete from books where lang='' or lang=NULL;
