### ISSUE TITLE
Does LL tell Calibre if it renames a file as noted at librarysync.py:LibraryScan:929

### ISSUE THREAD

**Issue by blysik** [DobyTang/LazyLibrarian#1556]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
14c6ac51ae93865421e45b461101c724abf31b5b

### Operating system used (windows, mac, linux, NAS type)
Synology NAS via Docker (thraxis LL+calibredb)

### Interface in use (default, bookstrap)
bookstrap
### Which api (Goodreads, GoogleBooks, both)
Goodreads (default setting)
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
Thraxis docker

Question: during the initial import of my existing Calibre library, I noticed some lines where LL was renaming some files.

Does LL tell Calibre that it's renamed things, so that it plays nicely?   I have Calibre Content server setup, if it matters.  

From my testing, it appears that Calibre could still find those files, but I just wanted to be sure.

Thanks!

**Comment by philborman** [comment]
LazyLibrarian isn't renaming the book at that point, it thinks the book has moved so it's updating it's link so the "open" button works.

It usually means you have two copies of the book in different locations during the scan, or  a false match against a very similar title. Look at the "from" and "to" lines in the log to see if it's really two copies or correcting an incorrect match. If there are two copies probably best to delete one?

**Comment by blysik** [comment]
Okay, thanks.  It's most likely dupes.
