### ISSUE TITLE
Remove from torrent client upon seeding completion?

### ISSUE THREAD

**Issue by ethanopp** [DobyTang/LazyLibrarian#1559]
Is there a way to have LL remove torrent from client (transmission in my case) upon seeding completion?

I'm thinking similar approach to how Sonarr/Radarr have their 'complete download handling' settings...

Also would be nice if it could also delete all the extra crap that sometimes gets downloaded along with the book file.

**Comment by philborman** [comment]
Should already do that, as long as "keep seeding" is not set in lazylibrarian config.
Transmission tells us if the torrent is "finished", which means downloaded and seeded, so if you have seeding limits/ratios set in transmission we won't delete unless they are completed. We ask transmission to delete everything unless "keep originals" is set.

**Comment by ethanopp** [comment]
Hmm odd... I do not have keep seeding nor keep original files set...

**Comment by philborman** [comment]
If the seeding threshold has not been hit by the time we postprocess the download, we won't ask transmission to delete it. There is currently no additional checking later, we only check once. 
I don't have seeding limits myself and everything gets tidied up ok. Maybe increase your postprocessing delay so we don't postprocess so soon, or can you set transmission to delete after seeding is complete, I know deluge can do that.  We could maybe scan the history table every so often to check transmission until seeding is complete, but at the moment we don't store enough info to do it.

**Comment by ethanopp** [comment]
Ah yep that's definitely what is happening... seed ratio is 1.25 and deff not being hit before post processing (i think every 15?)

Unfortunately cant set transmission to delete because that then screws up the Sonarr/Radarr post processing that is being done

Scanning history every so often to check is an interesting idea though... Leaves the burden on LL as opposed to transmission

**Comment by ethanopp** [comment]
The only setting in transmission I am aware of is the following:
`TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=false` 

However if I set this to true, it messes with the complete download handler of Sonarr/Radarr since those applications handle everything from their side, and given that those files tend to be much larger than the book ones I'm giving them priority to make sure they seed correctly...

A while ago when I used couchpotato there was a way to set the seed ratio per indexer, do we have a setting in LL where we can set the seed ratio so it would overwrite the default transmission has?

If so I could just lower the seed ratio for the LL files and increase the post processing time so ideally they would just complete in time.

**Comment by ethanopp** [comment]
How can we change to check for just completion of download as opposed to completion of seeding?

**Comment by ethanopp** [comment]
When you say delete on completion, is that when its completed downloaded or completed seeding?

**Comment by philborman** [comment]
Delete after processing, so download is complete and we don't care if still seeding. The second tickbox stops you deleting if it's still seeding, but we don't check again, leave it up to the torrent downloader. Only transmission and qbittorrent tell us anyway, so the second tickbox has no effect on the other downloaders.

**Comment by ethanopp** [comment]
Okay I see the 2 options now - will give them a go!
