### ISSUE TITLE
Cover Page # for Individual Magazine Issues

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1562]
Love how LL is working, thank you!

The option to choose which page to use for a magazines cover page is excellent; however I have quite a few magazines where the correct cover is page 1 but some issues on page 2 for the same mag.

Could we have an option to choose the cover page for each issue?

Thank you again...

**Comment by MrMxyzptlk** [comment]
OK, thanks for the guidance.

**Comment by MrMxyzptlk** [comment]
I just came up with an idea that may be easy for you to implement? That would keep me from spending so much time maintaining which page an issue uses. You have added the 'New Cover' option as a drop down; how about after selecting some issues, and then clicking 'New Cover', have a popup that asks for a page #? That would keep me from having to delete the issues with the wrong covers, go to filters and temporarily change page number for covers. re-scan mag, and then, change cover page number back.

**Comment by philborman** [comment]
The magazines I use here all seem to be either page 1 or page 2 for cover image, no other numbers used. If there are only two options it would be easier to add both to the current dropdown?

**Comment by MrMxyzptlk** [comment]
Yes, that is what I have found as well. Let er rip...thanks!
