### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by mccorkled** [DobyTang/LazyLibrarian#1565]
Do you have the original PSD of the logo? I need to make it bigger to attach to the tutorials I wrote. I am finally ready to get them up. 

Thanks.

**Comment by philborman** [comment]
The original .ico file is here if that's any use...
https://github.com/philborman/lazylibrarian.bookstrap/blob/master/images/ll.ico

**Comment by mccorkled** [comment]
I was looking for this logo

https://hub.docker.com/r/linuxserver/lazylibrarian/

**Comment by philborman** [comment]
That's the old icon, the only copy we have is at
      LazyLibrarian/data/images/favicon.ico

**Comment by mccorkled** [comment]
Damn. Well, I just won't add a logo to the posts for now I guess. I don't have time to recreate logos.

http://sasquatters.com/lazylibrarian-docker/
http://sasquatters.com/lazylibrarian-configuration/

**Comment by philborman** [comment]
Nice work!
Can I add those links to the lazylibrarian Readme page? 
Is that a permanent location for the pages?
Thanks, Phil

**Comment by mccorkled** [comment]
Yeah, no problem at all. Yes they are permanent.
