### ISSUE TITLE
Ubuntu 18.04.1 reports Cannot Stat, dpkg error

### ISSUE THREAD

**Issue by delize** [DobyTang/LazyLibrarian#1566]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page) 
https://github.com/DobyTang/LazyLibrarian/releases/tag/v1.6.1
### Operating system used (windows, mac, linux, NAS type) Ubuntu 
18.04.1 LTS
### Interface in use (default, bookstrap) 
default
### Which api (Goodreads, GoogleBooks, both) 
N/A
### Source of your LazyLibrarian installation (git, zip file, 3rd party package) 
N/A
### Relevant debug log with api keys and any passwords redacted 
N/A

I am going to keep the below in, but only for further debugging purposes as this issue doesn't exist within the client, but before because of the way the package appears to be built.

```
~$ sudo dpkg --configure -a
Setting up lazylibrarian (1.6.1-1) ...
cp: cannot stat '/opt/lazylibrarian/lazylibrarian.desktop': No such file or directory
cp: cannot stat '/opt/lazylibrarian/lazylibrarian.sh': No such file or directory
cp: cannot stat '/opt/lazylibrarian/lazylibrarian.default': No such file or directory
cp: cannot stat '/opt/lazylibrarian/lazylibrarian.init': No such file or directory
cp: cannot stat '/opt/lazylibrarian/lazylibrarian.service': No such file or directory
dpkg: error processing package lazylibrarian (--configure):
 installed lazylibrarian package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 lazylibrarian
```

However, I can still run `python lazylibrarian.py -d ` and everything works fine\ (afaict)

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report.

**Comment by philborman** [comment]
There is an error in the post-installation script, all those files are in  /opt/lazylibrarian/init/  not in /opt/lazylibrarian/  Only affects the auto-start setup and the menu entry, you can copy the files manually if you want to use those features. The rest of lazylibrarian should not be affected.

Not sure how that crept in, I will fix it in the next release, thanks for the bug report.
