### ISSUE TITLE
Can't delete magazine or export filters with this magazine name added 'kpck собака'

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1573]
To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report.

**Comment by philborman** [comment]
Cyrillic characters not matching the stored value in the database. Should be fixed later today but you may have to remove the magazine and then librarysync to correct it, there are "long" and "short" ways of storing the Cyrillic characters and we need to just use the short form so we can compare and match  correctly.

**Comment by MrMxyzptlk** [comment]
Thanks!
