### ISSUE TITLE
Custom Notifications

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#1579]
Have the parameters that get sent out to custom notification scripts changed recently?  I have a script that used to watch for DownloadID, but it's no longer picking that up from LazyLibrarian.

**Comment by philborman** [comment]
Yes there was a bug introduced a few days ago as part of getting the scripts to run under windows. Fixed a few hours ago, I think, an upgrade to latest should solve it. If not, let me know...

**Comment by DarkSir23** [comment]
Unfortunately not.  I am updated to the newest philborman release, and I'm getting an "unterminated quoted string" error from the script.

I added some logging to custom_notify.py, and see that ' '.join(params) is creating a string of params that looks like this (this is taken from the middle):

`BookPub Hazelden Publishing & Educational Services BookDesc Cynicism and black humor underscore`

**Comment by DarkSir23** [comment]
NZBDate, BookPub, NZBDate, BookDesc, and NZBtitle can all have spaces in them and appear to break the parameters list.

**Comment by philborman** [comment]
Ok I will revert the changes until we can fix it properly. The original problem is windows not recognizing the scripts as executable so we currently run the scripts via the shell, which doesn't like spaces in parameters. Fun.

**Comment by DarkSir23** [comment]
Just a thought...  Windows based Sonarr and Radarr set environment variables before they call custom scripts.  That might be a way around the problem.

**Comment by philborman** [comment]
Should be fixed now, but I had to add a special case for python scripts on windows. You can write the external scripts in any language you like for linux, but windows doesn't natively recognise python scripts as executable. I will have a look at Sonarr to see what they do, but it's not written in python so might not help.
