### ISSUE TITLE
Unhandled exception in downloadResult

### ISSUE THREAD

**Issue by CaloC-NZ** [DobyTang/LazyLibrarian#1582]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
82427c71cb4fd3ee30eba5a99854cb1b44cae75e

### Operating system used (windows, mac, linux, NAS type)
thraxis/lazylibrarian-calibre linux docker / qbit is also a docker container

### Interface in use (default, bookstrap)
bookstrap

### Which api (Goodreads, GoogleBooks, both)
n/a

### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
thraxis/lazylibrarian-calibre linux docker

### Relevant debug log with api keys and any passwords redacted
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/2440955/debug.zip)

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report. 

I've just installed the docker container, added qbittorrent and jackett, added an author and searched for a book and have not yet been successful.  Any ideas, am I missing something?

**Comment by CaloC-NZ** [comment]
Thanks for updating. I've applied the update however still running into the same/similar issue.  I've
 attached the debug log.
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/2445291/debug.zip)

**Comment by philborman** [comment]
Doesn't look like you are on latest version?
The debug log shows 783107377a22c18c93f6cb9c798e9e810bbfaa49  when latest version is 4edcc80941f283635f89b35b6e89e352f41fc884
The line numbers look wrong, and your debug shows us still calling addTorrent instead of addFile

**Comment by CaloC-NZ** [comment]
Ok, I'll have a look at that.

**Comment by philborman** [comment]
You are now on 4edcc80 which is latest version on main branch, the last debug log was the wrong version though, so gave the wrong info. Can you run the test again and post a new debug log, thanks.

**Comment by CaloC-NZ** [comment]
Here you go (and thanks for looking into this)
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/2445711/debug.zip)

**Comment by philborman** [comment]
Hmm, still something odd going on. Your latest debug log says it is running
version: 783107377a22c18c93f6cb9c798e9e810bbfaa49
which is not current, and the line numbers still show it's the old code, eg 
04-Oct-2018 22:16:52 - DEBUG   :: SEARCHBOOK : qbittorrent.py:addTorrent:261 : addTorrent(d8:announce68:https://ssl.iptorrents.com
we shouldn't be calling addTorrent in the new code, and that message isn't on line 261 any more, it's now line 265, so the upgrade appears not to have taken place???
