### ISSUE TITLE
Possible bug with post processor / directory. 

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1584]
![screen shot 2018-10-03 at 8 50 29 am](https://user-images.githubusercontent.com/1753001/46411312-7789cf80-c6e9-11e8-8a79-c9fbbb51fad9.png)

It appears that after the scheduled mag search in LL the post processor fails, with the message x:\anthony\downloads\books is not a directory; but when I go to the mags tab in LL and click post process it works fine.

Is this just an erroneous message, or an actual bug?
I'm not entirely sure that the PP is working correctly period...some mags left in SAB and Deluge?

I have attached a screen shot of the the pertinent part of the debug log.

**Comment by philborman** [comment]
Looks like your Download Directory entry in LL config  contains more than one entry, and x:\anthony\downloads\books either doesn't exist, or is not recognised as a directory ?  The second entry x:applications\downloads\books is ok though.

**Comment by MrMxyzptlk** [comment]
Woops, yep missing directory...
