### ISSUE TITLE
Feature Request: option to allow keeping empty mag directory if deleting last issue

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1586]
I have quite a few mags that initially do not find the correct mag, and I would like to delete all of those issues, but keep the mag. This will keep my filters, etc...

Maybe a checkbox somewhere in the configuration tabs?

**Comment by philborman** [comment]
Would be fairly easy to add, I will take a look. For now you can do this by leaving some other file in the directory, we only delete the directory if it's empty. The file can be anything.
