### ISSUE TITLE
Can not download audiobook and ebook for the same book

### ISSUE THREAD

**Issue by Piottreck** [DobyTang/LazyLibrarian#1591]
If I just set it do audiobook or ebook it works perfectly fine but if i select both only one the ebook is downloaded.
The status of the missing audiobook is "wanted".

### git

Since I do not get any error which I could reproduce i think the log does not really help.

**Comment by Piottreck** [comment]
Well the problem is that the audiobook is found and downloaded when i do not select the ebook. 
And the audiobook is "snatched" and not "wanted" as i mistakenly stated before! sorry for that

I created the log with "Start debug log" and then pressed
- search
- run post processor
- library audio scan
on the audiobooks page.
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/2453114/debug.zip)

**Comment by philborman** [comment]
ok, the log shows we are 
Looking for AudioBook J K Rowling Harry Potter The Sorcerers Stone txt in /mnt/nextcloud/Library/books/downloads
but in that folder there are no audiobooks. The problem seems to be we are sending the audiobook request to "direct" which is libgen, and libgen sends us txt, azw, pdf. Libgen often puts the filetypes in the title so if you add txt, azw, pdf  to your AudioBook Reject List in lazylibrarian config we will know the files are not audiobook and not try to download them.

**Comment by Piottreck** [comment]
I only have "epub, mobi" in the audiobook reject list and that would also not explain why it works as soon as I remove the ebook.
The status of the audiobook changed back to "wanted" by the way. I think thats also the reason why I initially stated that the status of the missing audiobook is "wanted"...
[debug.txt](https://github.com/DobyTang/LazyLibrarian/files/2453330/debug.txt)

**Comment by philborman** [comment]
In the latest log, around 2018-10-06 16:27:10  the audiobook "J K Rowling Harry Potter The Sorcerers Stone txt" gets sent to libgen. LazyLibrarian rejected epub and mobi versions as per the audiobook reject list. It's not an audiobook, but we don't know that until the file is downloaded and the "magic" library tells us it's ASCII text. The postprocessor runs at 2018-10-06 16:30:41 but fails to find an audiobook, so after the timeout (previous debug log said 2 hours) the audiobook will be reset to "Wanted"

**Comment by philborman** [comment]
Recent changes to lazylibrarian downloaders let you set libgen to be eBook only, should solve the confusion.

**Comment by Piottreck** [comment]
Well that worked for me!
I do not know if the Size Limits in the filter have been there before but setting a minimum size limit for audiobooks seems very promising as well for such a problem.

**Comment by philborman** [comment]
Size limits have been there a while now, but only some torrent downloaders give us the info. We don't know sizes for libgen or nzb until the download is complete.
