### ISSUE TITLE
Unfortunately empty folders got deleted on scan magazine directory, even though 'Don't delete empty folders when deleting last issues', is unchecked.

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1596]
Unfortunately empty folders got deleted even though 'Don't delete empty folders when deleting last issues', is unchecked.

Please add code to prevent empty folder deletion if no magazines are present...

Thank you!

**Comment by philborman** [comment]
Found it, there were two places in the code that deleted the folder  and the new tickbox was only applied to one of them. Should be fixed in next release probably out tomorrow.

**Comment by MrMxyzptlk** [comment]
Thanks for the quick update!
