### ISSUE TITLE
Minimum Seeders Not Being Applied

### ISSUE THREAD

**Issue by MichealX64** [DobyTang/LazyLibrarian#1600]
Hi guys, today I have been setting up LL and so far so good, I love this application, but I have run into an issue where no matter what value I set the minimum seeders to on the "Downloaders" config page, it seems LL grabs the first result it can find, usually resulting in a torrent with 0 seeders a dead torrent.

**LL Version:** f3e62ca3076c6c5841a4b1c68fdf4d2385493110
**OS:** Windows Server 2016
**Interface:** bookstrap
**API:** Goodreads, multiple torznab sources through Jackett
**LL Source:** Git
Debug Logs Attached

Thank you for you for you help and for a great application.
[LL_torznab_debug.txt](https://github.com/DobyTang/LazyLibrarian/files/2466650/LL_torznab_debug.txt)

**Comment by philborman** [comment]
Looks like we are not picking up the "seeders" value correctly from jackett, will take a look later today.

**Comment by MichealX64** [comment]
Have updated to the most recent version and can confirm this is now working as expected.

Thank you.
