### ISSUE TITLE
common.py debug logging breaking calibredb process.

### ISSUE THREAD

**Issue by jcal22** [DobyTang/LazyLibrarian#1603]
Current master commit has an error in common.py line 1214:

logger.debug(params)  causes errors.

It's fixed by commenting out or casting params as a string.  Not sure how to submit fixes or pull requests or such, but this causes calibredb to fail.  Probably other things using runScript.

**Comment by philborman** [comment]
Many thanks, this will be fixed in the next few minutes. Thanks for the bug report, still learning!
runScript is a recent addition to get around issues with running scripts under windows so not so well tested yet.

**Comment by jcal22** [comment]
You've done an amazing job!  Would love to help out more.

**Comment by philborman** [comment]
Always open for help...
