### ISSUE TITLE
Audiobooks LibraryScan not writing playlist.ll

### ISSUE THREAD

**Issue by justagame** [DobyTang/LazyLibrarian#1609]
Repo: https://github.com/dobytang/lazylibrarian : Branch: master : Updated: Sat Oct 13 11:23:36 2018
Current Version: f35cd2c6c64ccd589c7134911c8329c2ba492005 : Latest Version: f35cd2c6c64ccd589c7134911c8329c2ba492005
Linux 16.04 with Synology NAS
bookstrap interface
Source of installation is git

LibraryScan does not generate playlist.ll files for the older folders....
typical line in debugging log:

  | Unable  to create playlist in /mnt/SynMediaFiles/AudioBooks1/Suzanne  Collins/Mockingjay: [Errno 2] No such file or directory:  u'/mnt/SynMediaFiles/AudioBooks1/Suzanne Collins/Mockingjay/playlist.ll'
-- | --

**Comment by philborman** [comment]
Odd error, could it be permissions?
The "no such file" message is coming from a line where we are trying to create the file. Is the directory path OK?

**Comment by justagame** [comment]
funnily, i was just looking into that.....I'm attaching  the most recent
debug .zip file and log files....

Wendy Atkinson

**Comment by justagame** [comment]
I'm very green and just learned where to find the bookrename.py file and
look at the error line.....
Wendy Atkinson

**Comment by philborman** [comment]
Should be fixed now, there was a problem if you did not have "rename audiofiles" ticked, we were trying to create the playlist in the wrong directory.
