### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by Code-Slave** [DobyTang/LazyLibrarian#1612]
In opds server can links to authors and maybe series be added? If you browse calibre opds server and click on a book to get details it has links to author, series etc. I think it would be useful. (im trying to move away from calibre mostly for day to day).

I still use calibre mostly for conversions and emailing to kindles with epub/mobi. What do you think about adding a export to calibre dropdown when on the authors books page. this would trigger the selected method of export (calibre direct or send to calibre import directory) or is there a decent conversion tool that can be incorporated? Im also wonder how ll would handle having say mobi and epub in same dir?

**Comment by philborman** [comment]
OPDS link to author should be fairly easy now we can do multiple links per book, link to series is a bit more complicated as there could be several series per book. I will have a look.

We could probably do email-to-kindle from inside lazylibrarian with a bit of work, as far as I know you just send an email with the mobi or azw3 as an attachment, but I don't have a kindle to try with. Does the kindle app work the same way, do you know?

For conversion we use the calibre ebook-convert program as it's not worth writing another equivalent one. Kindle also has it's own converter program but that's only convert-to-mobi, not the other way around. The example preprocessor script calls that calibre convert do the conversion on a new download before processing if required.
 
LazyLibrarian is fine with multiple formats of the same book in the same dir, we link to the "left most" format in the ebook types list in config by default. If you click "Open" to download a book and you have user accounts enabled we link to the users preferred format if one is set, If not we show a popup asking which format you want to open.

**Comment by philborman** [comment]
Yes, Thraxis docker includes all the calibre components. We need to add a "kindle email" field to the users table and a "send to kindle" option to the downloader, not too much work.

I prefer converting everything up-front rather than converting when the download is requested, takes too long, browsers often timeout. If you don't want to do it that way maybe don't offer the "send to kindle" option if there isn't already a mobi? Or we could include a script to retro build all the missing epub or mobi versions. Another user created a neat script using calibre ebook-convert.

**Comment by Code-Slave** [comment]
Yes a more generic send to email or device with preferred type. 

Conversion. If we front load it the it should likely be an option to do conversion as prt of the adding process. Or on a scheduled timer?  I know my ll library is a mix as i grab whatever format is available. 

Magazines: i think email is fine here too it just sends the pdf. Most readers i know of have no issue with pdf i think.

**Comment by philborman** [comment]
The example preprocessor script makes sure each ebook download contains epub and mobi and creates the missing ones. If you put it in the "preprocessor" box in lazylibrarian config it will run every time an ebook download completes but before the postprocessor runs to import the book into the library.

**Comment by Code-Slave** [comment]
awesome ill swich dockers and give it a try

**Comment by Code-Slave** [comment]
Is there a good debug setting for mags? i redid docker and lost all my mags and when i library scan it says zero mags. (they are in dirs), just need better debug info for that scan

**Comment by philborman** [comment]
Regular debug should be enough. Just need to check mag directory and whether it's inside ebook dir or not

**Comment by philborman** [comment]
Don't seem to be able to get author links appearing anywhere in aldiko or moon+
Any chance you can post the xml from a page that works so I can see where I am going wrong

**Comment by Code-Slave** [comment]
Yes give me a sec

**Comment by Code-Slave** [comment]
This is the calibre listing for the book. when i hit opds in moon+ and i click on the book gives all this info. I cant replicate the exact functionality in a browser  

<entry>
    <title>Mysterious Things in the Woods; Mysterious Disappearances, Missing People; Sometimes Found...Unexplained Disappearances.: Creepy Mysteries of the Unexplained</title>
    <author>
      <name>Steph Young</name>
    </author>
    <id>urn:uuid:fa01cee5-70e2-47a4-9e3f-f63a53b368a8</id>
    <updated>2018-10-17T12:42:20+00:00</updated>
    <published>2018-10-15T19:21:23.952224+00:00</published>
    <dc:date>2014-05-16T00:00:00+00:00</dc:date>
    <content type="xhtml">
      <div xmlns="http://www.w3.org/1999/xhtml">RATING: ★★★<br/>
TAGS: new<br/>
From Kindle: Yes<br/>
<p>As featured on National Radio Shows; 'Something in the woods is taking People'; Something unknown that we cannot define; Something that others have had the misfortune to encounter. People snatched soundlessly, never to be seen again. Or returned; dead. A strange and highly unusual predator. Highly intelligent. Very successful. And able to overpower someone in an instant.... This is a puzzle. An often deadly one.  </p>
<p>'Mysterious Things in the Woods;' features unusual disappearances, Missing people, Strange encounters, Mysterious deaths, hikers found inexplicably mutilated; hunters found dead in weird circumstances; campers disappearing, their bodies never found...other bodies found as though left out on display...these are just some of the most baffling unexplained mysteries in the woods...and all are true stories...Don't go in the Woods....You might not come back.....  </p>
<p>Stephen (Steph) Young has appeared on national radio shows &amp; podcasts including 'Coast to Coast AM', 'The Unexplained,' 'Where did the road go?', 'Midnight in the Desert,' 'Darkness Radio'  </p>
<p>An independent Researcher addicted to researching all Paranormal, Supernatural, Esoteric &amp; Enigmatic mysteries. Each book Young writes seems to lead to further questions and searches for answers as the mysteries inevitably deepen &amp; develop into ever more complex riddles in the spectrum of the Unknown.   </p>
<p>Steph now has her own podcast "Masquerade" on itunes.  </p>
<p>Creepy Mysteries of the Unexplained.  </p>
<p>**</p></div>
    </content>
    <link href="/get/epub/2389/lib_books" rel="http://opds-spec.org/acquisition" type="application/epub+zip" length="181967" mtime="2018-10-15T19:21:34.078709+00:00"/>
    <link href="/get/mobi/2389/lib_books" rel="http://opds-spec.org/acquisition" type="application/x-mobipocket-ebook" length="340521" mtime="2018-10-15T19:21:26.291642+00:00"/>
    <link href="/get/cover/2389/lib_books" rel="http://opds-spec.org/cover" type="image/jpeg"/>
    <link href="/get/thumb/2389/lib_books" rel="http://opds-spec.org/thumbnail" type="image/jpeg"/>
  </entry>

**Comment by philborman** [comment]
The only links there are epub, mobi, cover, thumb
No link to author as far as I can see. The author name is defined, but that's not a link, purely for display.

**Comment by Code-Slave** [comment]
yea, in the ereader it shows as the main listing. then when i click on a book it shows that info with author and series as a link. I cant replicate exact functionality in the browser. Im looking for an opds browser for osx or linux gui

**Comment by philborman** [comment]
Yes, that's one of the guides I looked at, it doesn't show any extra links. There is a uri for the author rather than a link, and it doesn't produce anything on screen in moon+ or aldiko

**Comment by Code-Slave** [comment]
Just some references. It seems moon+ is a sucky reader as far as odps is concerned and whats supported.

tests of various clients
https://docs.google.com/spreadsheets/d/14lC_joUXnwUAdMQJ-PYOTvz8RWPcgfSg1Rky8RRwV28/edit#gid=0

https://github.com/Feedbooks/opds-test-catalog
https://feedbooks.github.io/opds-test-catalog/

good info here

**Comment by philborman** [comment]
The spreadsheet is quite useful. 
Line 30  "multiple aquisitions" is the one that allows us to choose epub/mobi or whatever to download. It seems moon+ ignores all links except mobi?
Line 11 "full image" is why there were no images in moon+ but they were working in aldiko
Nothing in there about links to author or series though. The test-catalog has a few other options though, will take a look.

**Comment by Code-Slave** [comment]
Yea, ive been reading some opds google groups and aldikido seems to be the best client for opds so far. I may have to make a switch as they have ios app in testing to.

Just FYI. I started docs
https://github.com/Code-Slave/LazylibrarianDocs/

**Comment by Code-Slave** [comment]
re docs. Ill be posting tickets on my repo for now with questions

**Comment by philborman** [comment]
Looks a good start. I take it nothing came of trying to get the lazylibrarian domain at github?

**Comment by Code-Slave** [comment]
No. completely no response after 3 emails. 

Initial is to get readme and wiki implemented, and updated with current graphics. Im just about done with front end, moving to config. if you want to see what its looking like
pip install mkdocs
pip install mkdocs-material
git pull my repo
in repo
mkdocs build -clean
mkdocs serve

itll be on local port 8000

**Comment by Code-Slave** [comment]
Can you inquire with github again? i just checked repo and it said 0 people are associated with it. (lazylibrarian org)

**Comment by philborman** [comment]
Ok, have just emailed github again. See what they say.

I am just upgrading my ubuntu to latest release, will take a few hours, so will install mkdocs and have a look at your repo later.

**Comment by Code-Slave** [comment]
18.10? or .04? Im on .04 and am really liking it

**Comment by philborman** [comment]
18.10 came out yesterday. I was on 18.04 mint edition, then vanilla ubuntu.  This time I'm trying kubuntu with plasma, tried a live usb and it looks very smooth. I think my 18.04 had accumulated too much junk. Every couple of years a fresh install seems to help rather than an upgrade.

**Comment by philborman** [comment]
Ok, up and running again, yay!
Had a look at your repo docs, all looking very professional. I will have a look in more detail in the coming days, and let you know about any omissions or changes in the code that need documenting. The info in the wiki is at least a year out of date, except for the odd update.

btw  in order to get mkdocs to run  I had to python -m mkdocs --clean  and python -m mkdocs serve
just mkdocs on its own didn't recognise the pip installed material theme

Also I had a reply from GitHub Staff re the lazylibrarian domain, was it brianredbeard you tried to contact, as it looks like it's his domain. GitHub have an email address for the owner though, they said...
> I've just sent your message, so (with any luck) we'll hear something back from the owner of that username soon. We can't guarantee a response, of course, but we'll be sure to let you know immediately if we receive any word from them.

**Comment by Code-Slave** [comment]
Good news. And sorry about the shorthand with mkdocs. I decided to go to 18.10 too cause why not. Just got settled back in as well.btw we need a better way to chat. Discord? i am codeslave#2342 there. Im gmt -5 btw

**Comment by philborman** [comment]
I just signed up to discord, pb1961#8978
I'm gmt +2 until Sunday then gmt +1

**Comment by Code-Slave** [comment]
sent a friend request. Lots of doc updates. The unclear or parts I need more are marked with TODO:
