### ISSUE TITLE
Please consider adding torrentz2.eu 

### ISSUE THREAD

**Issue by Matthijz98** [DobyTang/LazyLibrarian#1614]
I think adding torrentz2.eu could be really handy.
There are a lot of books that LazyLibrarian did not find but i did find using torrentz2.eu

Thanks for the great program!!!

**Comment by philborman** [comment]
It's fairly complicated to add that one, it's an aggregator rather than a search engine, so it's links just point you to other sites, some of which aren't working. Not sure if it's worth the effort.
