### ISSUE TITLE
[Feature Request] Convert size to KB,MB,GB for manual search results

### ISSUE THREAD

**Issue by saitoh183** [DobyTang/LazyLibrarian#1635]
![image](https://user-images.githubusercontent.com/1534197/47236137-3829d700-d3a9-11e8-8f2e-354dde96818a.png)

It would be easier to read and to know what the actual size of the file is.

**Comment by philborman** [comment]
Ok, that should be in the next version, probably later today. 
I had a version a while ago that did this but had problems getting it to sort correctly. 
Since then I've learned how to do it using a hidden sort field.
