### ISSUE TITLE
Question: Config of Directories

### ISSUE THREAD

**Issue by yabdali** [DobyTang/LazyLibrarian#1643]
### Relevant debug log with api keys and any passwords redacted
Just need some clarification, in the Config page, whats the difference between:
A) Downloaders> Deluge >Download directory ; and
B) Processing>Folders>Download Directories?

I have both pointed to the folder where Deluge move completed downloads based on my set label 'books'. Is this inline with the logic behind your workflow?

**Comment by philborman** [comment]
A) Downloaders> Deluge >Download directory
this tells deluge where to put the books (as does label, you don't need both)
B) Processing>Folders>Download Directories
this tells lazylibrarian where to look, optionally more than one location in case torrents and usenet downloads are in different places
