### ISSUE TITLE
Unable to access configuration

### ISSUE THREAD

**Issue by fitzy2211** [DobyTang/LazyLibrarian#1649]
I was wondering if someone could help me

I had everything working great and then I decided to change layout from bookstrap to legacy. Now I can't access the config page. 

I'm running windows 10 and I installed using a zip file. My version is 8e18b9d25367d8ff1789b818a5449e6c093e93d5

The error I get is "mako runtime error" with the following displayed

Error !
KeyError: 'GIT:BASE'
<p><input type="submit" value="Save changes" id="add"></p> </div> <p>&nbsp;</p> <p style="text-align:center;color:grey">Repo: https://${lazylibrarian.CONFIG['GIT:BASE']}/${lazylibrarian.CONFIG['GIT_USER']}/${lazylibrarian.CONFIG['GIT_REPO']} : Branch: ${lazylibrarian.CONFIG['GIT_BRANCH']}<br> Current Version: ${lazylibrarian.CONFIG['CURRENT_VERSION']} : Latest Version: ${lazylibrarian.CONFIG['LATEST_VERSION']}</p> </div> </form> </%def> <%def name="javascriptIncludes()">
C:/LazyLibrarian/data/interfaces/legacy/config.html, line 2079:
<p style="text-align:center;color:grey">Repo: https://${lazylibrarian.CONFIG['GIT:BASE']}/${lazylibrarian.CONFIG['GIT_USER']}/${lazylibrarian.CONFIG['GIT_REPO']} : Branch: ${lazylibrarian.CONFIG['GIT_BRANCH']}<br>
C:/LazyLibrarian/data/interfaces/legacy/base.html, line 157:
${next.body()}
C:\LazyLibrarian\mako\runtime.py, line 890:
callable_(context, *args, **kwargs)
C:\LazyLibrarian\mako\runtime.py, line 864:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
C:\LazyLibrarian\mako\runtime.py, line 829:
**_kwargs_for_callable(callable_, data))
C:\LazyLibrarian\mako\template.py, line 445:
return runtime._render(self, self.callable_, args, data)
C:\LazyLibrarian\lazylibrarian\webServe.py, line 84:
return template.render(perm=lazylibrarian.perm_admin, **kwargs)

I just want to change back to bookstrap but I don't know how to?

**Comment by philborman** [comment]
Ah, that's a typo, will push a fix in a few minutes. Sorry about that.
Easy fix for now is to edit your config.ini file, the line you need to change is near the top
http_look = bookstrap

**Comment by fitzy2211** [comment]
Thank you so much for that! It worked :)

I spent like an hour trying to figure it out, thank you again
