### ISSUE TITLE
Log File

### ISSUE THREAD

**Issue by nncrypted** [DobyTang/LazyLibrarian#165]
Is there a way to clear the log file? Easily?

**Comment by philborman** [comment]
its a rolling log, 5 files max, each file up to 51200 bytes long. defined at the start of logger.py
No easy way to clear them except delete them from outside LL. Would be easy enough to add though.
Maybe wipe the logs on program startup? What do you think?

**Comment by nncrypted** [comment]
How about a clear button?

**Comment by nncrypted** [comment]
Just checked my log and its at 18396 lines and takes awhile to load.
