### ISSUE TITLE
Small bug after reboot or update

### ISSUE THREAD

**Issue by maxcore** [DobyTang/LazyLibrarian#166]
Each reboot or update i need to check SABnzbd 

INFO	No download method is set, use SABnzbd or blackhole

thx

**Comment by nncrypted** [comment]
I've seen this also.

**Comment by philborman** [comment]
That message comes from searchtorrents and checks KAT, not sabnzbd. The message from sabnzbd says INFO No download method is set, use SABnzbd/NZBGet or blackhole.
I think the KAT message needs changing, but I think  the change from bool to int in commit #164 should have fixed the failure to preserve settings. Can you check you are running the current version?

**Comment by maxcore** [comment]
Branch: master Current Version: bf049a88bdedc2a820727bca55aea6c8ae979222 : Latest Version: bf049a88bdedc2a820727bca55aea6c8ae979222

i have the last one. If i un check kat the problem solve ? i dont need kat.. the provider dont working here.

**Comment by maxcore** [comment]
ok i have uncheck torrent search and the problem was fixed . KAT provider dont working here .

Branch: master Current Version: d4895242ebda443879df2bdd07f922cad3b9dbfd : Latest Version: d4895242ebda443879df2bdd07f922cad3b9dbfd
