### ISSUE TITLE
Error searching libgen

### ISSUE THREAD

**Issue by jcal22** [DobyTang/LazyLibrarian#1660]
For the past week or so, libgen keeps getting blocked for returning 403 errors.  However, if I copy the URL from LL and paste it into my browser, it returns a results page and 200.  Not sure if it's blocking LL by user-agent or something, but I have not successfully searched that site in some time.  Up to date with the commits.

**Comment by philborman** [comment]
You can change user_agent in config.ini but it's not available in the web interface
user_agent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
will make lazylibrarian look like a browser, but that will affect all calls, or try a libgen proxy site like gen.lib.rus.ec

**Comment by philborman** [comment]
Hopefully the workarounds above have fixed the issue.
Development has moved to [GitLab](https://lazylibrarian.gitlab.io/)
All open issues have been moved over to [LazyLibrarian Issues](https://gitlab.com/LazyLibrarian/LazyLibrarian/issues)
Please open any new issues or comments on the new repo as the old one is no longer maintained, thanks
