### ISSUE TITLE
Feature Request: Separate Download Client Categories Per User

### ISSUE THREAD

**Issue by chetcuti** [DobyTang/LazyLibrarian#1661]
It would be super handy if we could assign separate download client categories for each user, so we could process the downloads differently depending on the LL user. My wife and I deal with our eBooks differently, so we have our own eBook categories setup in NZBGet, and it would be great if we could use these same categories in LL. You can already assign the category, just not per-user.

If this were in place, eBook downloads would be handled completely differently depending on which LL user was logged in, which would be great for any multi-user systems.

**Comment by philborman** [comment]
Not sure what you are trying to achieve with this, the category is used to tell nzbget where to put the books so lazylibrarian can find them. If you have multiple categories that tell nzbget to put the books in different locations you would need to tell lazylibrarian about all the locations or it will think the download failed and try again.

**Comment by chetcuti** [comment]
I'm trying to achieve different users being able to have their downloads processed differently, so if User A and User B each add an eBook, their own eBooks would end up in their own final destination (Library) folders, and they could each do their own post-processing on the eBooks.

Ideally each user would have their own Download and Library folders, but since that's not how the system works I figured I would try to solve the issue using different download categories, but that's not working out too well either.

So I guess the only solution for now is two separate installations. A bit more work, but it'll solve everything.

**Comment by philborman** [comment]
Yes, would be quite a bit of work to separate it out, two instances of lazylibrarian would be simpler especially if there is not too much overlap in the libraries.
