### ISSUE TITLE
Database Integrity Error - foreign key constraint failed

### ISSUE THREAD

**Issue by anotb** [DobyTang/LazyLibrarian#1663]
Multiple database integrity errors on trying to add past issues of magazines to wanted list, as well as any new magazine searches

Version - 59b5b79fe5b069ab8d74677f8cd9799dba611354

**Comment by philborman** [comment]
That's a tricky one. Missed that. The foreign key restraint deletes orphans, but the magazine doesn't have an entry in the same table as books. Sounds like there are a couple of locations with the error, found one on line 3267, in markPastIssues but haven't found the other yet, do you have the location in your browser "internal server error"?

**Comment by airix1** [comment]
I have this error as well

`09-Nov-2018 10:12:18 - ERROR :: SEARCHMAG : searchmag.py:search_magazines:507 : Unhandled exception in search_magazines: Traceback (most recent call last):
  File "/opt/LazyLibrarian/lazylibrarian/searchmag.py", line 458, in search_magazines
    myDB.upsert(insert_table, newValueDict, controlValueDict)
  File "/opt/LazyLibrarian/lazylibrarian/database.py", line 143, in upsert
    self._action(query, list(valueDict.values()) + list(keyDict.values()), suppress="UNIQUE")
  File "/opt/LazyLibrarian/lazylibrarian/database.py", line 58, in _action
    sqlResult = self.connection.execute(query, args)
IntegrityError: FOREIGN KEY constraint failed`

**Comment by philborman** [comment]
Tomorrows upgrade will include a fix for this, the fix seems to work fine in testing, but have to delay the upgrade until tomorrow as we are moving provider. Sorry for the inconvenience.

**Comment by philborman** [comment]
Should be fixed now, 
Development has moved to [GitLab](https://lazylibrarian.gitlab.io/)
All open issues have been moved over to [LazyLibrarian Issues](https://gitlab.com/LazyLibrarian/LazyLibrarian/issues)
Please open any new issues or comments on the new repo as the old one is no longer maintained, thanks
