### ISSUE TITLE
Unhandled exception with uTorrent

### ISSUE THREAD

**Issue by Magnatolia** [DobyTang/LazyLibrarian#1669]
Hi,

I am yet to be able to get a book downloaded with this. I just got the following unhandled exception in the log. Can anyone explain the action I need to take to rectify this? I'm guessing it has something to do with uTorrent. I tested my uTorrent set up and this came back as successful.

Unhandled exception in downloadResult: Traceback (most recent call last): File "D:\My Downloads\LazyLibrarian\LazyLibrarian-master\lazylibrarian\resultlist.py", line 297, in downloadResult controlValueDict["NZBurl"], newValueDict["AuxInfo"]) File "D:\My Downloads\LazyLibrarian\LazyLibrarian-master\lazylibrarian\downloadmethods.py", line 367, in TORDownloadMethod downloadID, res = utorrent.addTorrent(tor_url, hashid) # returns hash or False File "D:\My Downloads\LazyLibrarian\LazyLibrarian-master\lazylibrarian\utorrent.py", line 259, in addTorrent uTorrentClient.add_url(link) File "D:\My Downloads\LazyLibrarian\LazyLibrarian-master\lazylibrarian\utorrent.py", line 101, in add_url return self._action(params) File "D:\My Downloads\LazyLibrarian\LazyLibrarian-master\lazylibrarian\utorrent.py", line 156, in _action url = self.base_url + '/gui/' + '?token=' + self.token + '&' + urlencode(params) TypeError: can only concatenate str (not "bytes") to str

Thanks!

**Comment by philborman** [comment]
Development has moved to gitlab, and the issue may have already been fixed in later versions.  
Please update to the latest version at https://gitlab.com/LazyLibrarian/LazyLibrarian  
If the issue still occurs please open a new ticket on gitlab.
Thanks
