### ISSUE TITLE
X-Forwarded-Proto header is ignored

### ISSUE THREAD

**Issue by alesnav** [DobyTang/LazyLibrarian#1670]
Hello there,

I'm trying to set up a reverse proxy with SSL-offload to publish LazyLibrarian. It does work, but it tries to redirect continously to clear HTTP.

I am forwarding the HTTP header called X-Forwarded-Proto, which contains "https", but it seems that LazyLibrarian don't look at it.

This makes impossible to use LazyLibrarian in an iFrame if the parent frame was loaded using https, because of mixed content. For example, it it not possible to include in Organizr whn protected behind reverse proxy.

Radarr, Sonarr and Lidarr does support this feature.

Thanks!

**Comment by doug-w** [comment]
While it would be good to have it working properly, I have worked around this in nginx with the following config:
```
        location ~ ^/books/ {
                rewrite ^/books(/.*)$ $1 break;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://192.168.86.100:9000;
        }
```

**Comment by alesnav** [comment]
In nginx you can add `proxy_redirect off`, but I use traefik :(

```
location ~ ^/books/ {
                proxy_redirect off;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://192.168.86.100:9000;
        }
```

**Comment by philborman** [comment]
Development has moved to gitlab, and the issue may have already been fixed in later versions.  
Please update to the latest version at https://gitlab.com/LazyLibrarian/LazyLibrarian  
If the issue still occurs please open a new ticket on gitlab.
Thanks
