### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by nncrypted** [DobyTang/LazyLibrarian#168]
Not sure this is even possible but could LL also download audiobooks and put them into a seperate directory? Also how hard would it be to have Magazines in a different folder seperate from the ebooks?

**Comment by philborman** [comment]
Magazines in a separate folder is easy. Just need to add a checkbox to say if magazine_destination_folder is absolute, or relative to base_destination_folder
Default to "relative" so it doesn't break existing users.

Not sure about audiobooks, that might be a bit more complex

**Comment by nncrypted** [comment]
It was just a thought then I just checked my ebook dir and found several audiobooks that came down as ebooks so it's kind of doing it just more random rather than planned.

**Comment by philborman** [comment]
ok,
have put option in to separate out magazine directory, just need to test 
it before uploading it.
Current restriction is that if magazines are inside base directory they 
must start with '_' or '.' so libraryscan ignores the directory

I think you can stop audio book downloads by setting ebook_type in 
config to just the types you want,
default is epub,mobi,pdf    but I haven't tried it...

**Comment by philborman** [comment]
I think the audiobooks must have been pulled in on a "general search", they are a different nzb type to ebooks, type 3030. Not sure how best to filter these out, its quite hard to verify filetype until after the download has completed. 

btw, I think issues #145, #152, #166 can be closed now, and #155 is probably fixed but would like confirmation from theguardian

**Comment by nncrypted** [comment]
Thank you for contributing to this project. Wish I could do more but I'm a hardware guy software and programming are not my thing.

**Comment by philborman** [comment]
Not really mine either, I'm strictly an amateur. I used to do quite a 
bit in C and 68000 assembler 15 years or so ago, but nothing much 
recently, and I'm new to python.
I looked at Lazy Librarian a year or so ago when I was setting up my 
first Raspberry Pi as a media centre, but it wasn't really working for 
me then. Now I'm recently retired I felt like a challenge.

I've been asked about adding Torznab search support which looks 
interesting (see https://github.com/Jackett/Jackett). I might get around 
to this next, but also I think the magazine section needs a rethink.

I think the "Magazines" page should be more like "Authors", where you 
select an author to get a list of books. For magazines you select a 
title to get a list of issues. Also I think the past issues shouldn't be 
cluttering up the "wanted" table in the database, (unless they are 
marked "wanted") but probably move them into their own table, like books 
are. Quite a bit of work though, what do you think? Could break existing 
users databases unless we provide an update function.

**Comment by nncrypted** [comment]
The magazines portion was originally TheGuardian's project so when he see's this hopefully he'll chime in.  I looked at Jackett also and yes it looks interesting just need to read a bit more about it. I'll just keep merging your changes in.
