### ISSUE TITLE
Getting the following locale error after updating LL on Windows

### ISSUE THREAD

**Issue by stumueller** [DobyTang/LazyLibrarian#172]
10-Nov-2015 17:08:08 - INFO :: MAIN : Added month names for locale [en_GB.utf8]
10-Nov-2015 17:08:08 - WARNING :: MAIN : Unable to load requested locale [en_US.
utf8]
Traceback (most recent call last):
  File "C:\LazyLibrarian\LazyLibrarian.py", line 170, in <module>
    main()
  File "C:\LazyLibrarian\LazyLibrarian.py", line 117, in main
    lazylibrarian.initialize()
  File "C:\LazyLibrarian\lazylibrarian\__init__.py", line 573, in initialize
    build_monthtable()
  File "C:\LazyLibrarian\lazylibrarian\__init__.py", line 605, in build_monthtab
le
    locale.setlocale(locale.LC_ALL, current_locale) # restore entry state
  File "C:\Python27\lib\locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

I believe its to do with the locale names in Windows but I may be wrong. Does anyone have any advise on what to do?

**Comment by stumueller** [comment]
it seems to be commit 6bfeb41 that's broken it. I'm currently sitting on the 7th Nov changes and its OK...as soon as I update to that commit though it stops working

**Comment by philborman** [comment]
Remove en_US.utf-8 from the line in config.ini, you do not need both en_GB and en_US as the month names are the same. 

I will look into why there is an error generated after the warning. 
Should just warn and move on.  Dont have a windows system to test on though.

**Comment by philborman** [comment]
ok, I've applied a fix and tried this on an emulated windows (virtualbox on linux) 
Seems to be ok, but I'd appreciate it if you could test it on a real windows system and let me know if it works. I've tested it on linux x64 and Raspberry Pi arm, and another user has tested it on mac.
The test version is in a separate repository, https://github.com/philborman/LazyLibrarian.git
If it checks out ok please let me know and I will request its uploaded to DobyTang version.
Please backup your config.ini before using the test version as some settings are modified.
Thanks, Phil

**Comment by stumueller** [comment]
I did a git clone to another folder using your test version you mentioned and it started fine! I'll wait for it to be uploaded to the DobyTang version and then update :-)

Thanks

**Comment by stumueller** [comment]
Ive just updated to the latest version and its working

Thanks :-)
