### ISSUE TITLE
Push nzb's to NZBGet

### ISSUE THREAD

**Issue by hjone72** [DobyTang/LazyLibrarian#174]
Hi,

LazyLibrarian can't push nzb's to NZBGet. NZBGet logs a message saying that LL connected and will be dropping an NZB off soon however LL shows an error.

30-Oct-2015 15:27:46 - ERROR   :: SEARCHNZBBOOKS : Connect Error to NZBget: could not add Nora Roberts - The Liar LL.(-M7WoQEACAAJ).nzb to the queue: <Fault 2: 'Invalid parameter (AddTop)'>
30-Oct-2015 15:27:46 - ERROR   :: SEARCHNZBBOOKS : Failed to download nzb @ <a href="https://api.nzbgeek.info/api?t=get&id=996ad9c0e29870675899706753563617&apikey=[REMOVED]">https://api.nzbgeek.info/</a>

Thanks,

**Comment by philborman** [comment]
Hi,  do you know what version of nzbget you are on,  the debug log should show this,  and also gives an error message from nzbget

**Comment by hjone72** [comment]
Hi,

I am using NZBGet version 16. Here is the snippet from the LL Log.

30-Oct-2015 15:27:48 - DEBUG   :: SEARCHNZBBOOKS : Successfully connected
to NZBget
30-Oct-2015 15:27:48 - INFO    :: SEARCHNZBBOOKS : Sending NZB to NZBget
30-Oct-2015 15:27:48 - DEBUG   :: SEARCHNZBBOOKS : URL:
http://nzbget:N0ch2ng35@192.168.0.200:6789/xmlrpc
30-Oct-2015 15:27:48 - DEBUG   :: SEARCHNZBBOOKS : NZB Version 16
30-Oct-2015 15:27:48 - ERROR   :: SEARCHNZBBOOKS : Connect Error to NZBget:
could not add Nora Roberts - The Liar LL.(-M7WoQEACAAJ).nzb to the queue:
<Fault 2: 'Invalid parameter (AddTop)'>
30-Oct-2015 15:27:48 - ERROR   :: SEARCHNZBBOOKS : Failed to download nzb @
<a href="
https://api.nzbgeek.info/api?t=get&id=996ad9c0e29870675899706753563617&apikey=a6ac4ecb5f96924f79f9e69a576069dc
">https://api.nzbgeek.info/</a>


Thanks,



*Hayden Jones*
IT Technician

*M*   *0414 965 583 <0414965583>*
*E*    *hjone72@gmail.com <hjone72@gmail.com>*
*G*   *Google+ <https://plus.google.com/+HaydenJones93/posts>*

**Comment by philborman** [comment]
Hi, I think this was fixed in yesterdays release.
Can you check if it still happens with current version and report back.

Thanks.

**Comment by hjone72** [comment]
Yeah working perfectly now.

Thanks,

**Comment by philborman** [comment]
Please mark this closed now

**Comment by kysdaddy** [comment]
Hello,
I am a total rookie at this and seem to be having a similar issue but it could be operator malfunction on my part.
I have been able to get LazyLibrarian Docker/Rockon working on a Rockstor NAS using the Transmission Docker/Rockon on the same machine but I have failed to get LazyLibrarian to use the NZBGet Docker/Rockon on the same machine. Any suggestions on where to start trouble shooting? NZBGet works I can drag and drop and properly catagorize the files download and extract to the correct share.

I have no idea where to start.

Thanks for any help you might have

Chas

**Comment by philborman** [comment]
First step would be to try the "Test NZBget" button, see what the log shows.

**Comment by kysdaddy** [comment]
I'm sorry I meant to mention that the test button states "NZBget connection successful" rookie error, sorry.
I really don't mean to waste your time.

Chas

**Comment by philborman** [comment]
Well that's odd as the check for nzbget communication seems to be working. This would mean nzbget is running, your username and password are correct, and we spoke to nzbget and received a valid reply.
Next step in tracking it down would be to post a lazylibrarian debug log like the one above. There is a log creator built in to lazylibrarian which will strip out passwords etc for you. Version numbers can be quite important, especially with nzbget as it's communication protocol has changed several times. The debug log will include this info.

**Comment by kysdaddy** [comment]
Just to be sure that I am following the correct procedures, are you suggesting that I create a new issue such as "LazyLibrarian and NZBGet not downloading", and include the debug log in the post? 
Also would it be recommended to turn off/Uncheck use Transmission, so that the only information in the log applies to NZBGet?

Thanks again.
Chas
