### ISSUE TITLE
Not so much an issue as a thank you

### ISSUE THREAD

**Issue by stumueller** [DobyTang/LazyLibrarian#181]
I've had LazyLibrarian installed for a couple of months now, and it never seemed to pull in all of the books by an author. When I first set it up I added the authors I wanted to monitor and a lot of the books I had or wanted weren't added to my library. so I went through a process of manually adding the books that I had/wanted for those authors and just thought I'd use it to correctly name and organise my book collection, but I had resigned myself to it not necessarily pulling in new book information. Until now!

I've just done a manual refresh on my list of authors and lo and behold its now pulling in all of the book data that it was previously missing.

So I just wanted to say a big thank you, I get the feeling that LazyLibraian is going to be as useful as Headphones and Sonaar for me :-)

**Comment by coolius** [comment]
Me too, so glad that this is back in development! :+1:

**Comment by knobunc** [comment]
Absolutely!
