### ISSUE TITLE
Pulling in wrong books for author

### ISSUE THREAD

**Issue by stumueller** [DobyTang/LazyLibrarian#182]
Hi

After refreshing my authors most of them have pulled in the correct books for the author however a couple of them seem to be pulling in too many books; as an example M.L. Hamilton, also gets books pulled in for Lewis Carroll.

I can provide a copy of any log files you might need or screenshots

Thanks

Stuart

**Comment by philborman** [comment]
Weird authorcache bug here, the lazylibrarian authorcache is returning details for the wrong author.
The cache is far too complex for me to understand, but never seems to get cleared. The provider cache gets cleared on each search so I have added code to clear authorcache too. This seems to fix the problem, but isn't perhaps the ideal solution.

The fixed version is at https://github.com/philborman/LazyLibrarian.git  
Could you give it a try and let me know if it works for you. If it does, I will upload it to master.
Thanks

**Comment by stumueller** [comment]
Hi

I'll try it tonight after I get home from work and let you know

**Comment by stumueller** [comment]
Hi

So I cloned your copy into another folder and added the author M.L. Hamilton

The log file still reports its pulling in books by Lewis Caroll though. On the front screen (list of authors) it show her as having over 400 books, but when you click on the author name no books are listed.

**Comment by philborman** [comment]
Thanks for that, seems the cache was a red-herring.

goodreads is used to look up author details, and its api doesnt like 
initials without periods,
"m l hamilton" fails, or at least returns "m l hamilton" plus some 
seemingly random authors
"m.l.hamilton" and "m.l. hamilton" both work as we want.
sadly the existing code forces all of them to be "m l hamilton" by 
stripping '.' and multiple spaces.

I have just added a fix, just need to make sure it doesnt break anything 
else.
First attempt was simply changing all spaces to '.'
eg "tom holt" gives "tom.holt" which then fails to find any books.

Should have something uploaded tonight with a bit of luck

**Comment by philborman** [comment]
Fixed version has been added to dobytang master branch
Have fun :-)
