### ISSUE TITLE
Ubuntu 15.10 Issues

### ISSUE THREAD

**Issue by Apocrathia** [DobyTang/LazyLibrarian#186]
When trying to run LL on Ubuntu 15.10. I get the following errors.

./LazyLibrarian.py: line 1: import: command not found
from: can't read /var/mail/lib.configobj
./LazyLibrarian.py: line 4: import: command not found
from: can't read /var/mail/lazylibrarian
./LazyLibrarian.py: line 9: opt_out_of_certificate_verification: command not found
./LazyLibrarian.py: line 18: syntax error near unexpected token `('
./LazyLibrarian.py: line 18: `def main():'

**Comment by philborman** [comment]
Hi, 
This is a python program,  so you can run it from the command line with python ./LazyLibrarian.py
but it's more useful running in the background as a system service. 
Have a look at the files in the init folder.  I think you want the lazylibrarian.service file for ubuntu, modify the locations and copy the service file into /lib/systemd/system/
Then you need to tell ubuntu to run it on boot using systemctl
"systemctl enable lazylibrarian" and "systemctl start lazylibrarian"  should do it. 
There isn't an automated way of doing this yet,  or a ready made  .deb file  that i know of. 
Maybe one will get created once the project is more mature.

**Comment by Apocrathia** [comment]
I was the one who uploaded the systemd service file...

**Comment by philborman** [comment]
Ah ok, 
I'm on ubuntu 15.10 too,  but upgraded for years from probably  10.xx
So I'm still using init.d files via a systemctl wrapper. Not sure what my raspberry pi uses,  but it's systemd based on debian jessie. 
We probably just need to  update the systemd service file to exec with python. 
I'm working on the magazine handling at the moment but will have a look at the systemd file when I'm finished

**Comment by philborman** [comment]
Just had a quick look 
Seems the ExecStart line at line 59 needs to specify python,
Ie ExecStart = /usr/bin/python  /home/lazylibrarian/LazyLibrarian.py  ...

**Comment by Apocrathia** [comment]
The ExecStart line is "/home/lazylibrarian/LazyLibrarian.py --daemon --config /home/lazylibrarian/lazylibrarian.ini --datadir /home/lazylibrarian/.lazylibrarian --nolaunch --quiet"
I've copied this into bash and the first message of this thread is the error which it produces. 
Looking at the LazyLibrarian.py file, there is no '#!/usr/bin/env python' line at the top, so bash is trying to execute the script itself. I'll toss a shebang in at the beginning and update the service file when I get home to a computer.

**Comment by Apocrathia** [comment]
Yep, came to the same conclusion. I'll update the service file, and a shebang needs to be added to the LazyLibrarian.py file for safe measure.

**Comment by philborman** [comment]
Doesnt need to be in the lazylibrarian.py file if the launcher knows its python. The init.d scripts specify python so the lazylibrarian.py doesn't have to.  Don't suppose it matters if its specified twice though

**Comment by philborman** [comment]
Hmm, just another thought, do we know if Windows and Mac understand #!/usr/bin/env python
I have no experience of these and no way of testing.

**Comment by Apocrathia** [comment]
Specifying it in both places just idiot-proofs it regardless of where you launch it from.

**Comment by philborman** [comment]
True.

**Comment by Apocrathia** [comment]
Fixed the ExecStart line in the lazylibrarian.service file. We can still add in the shebang to the LazyLibrarian.py, but at least it's future-proofed for systemd now.
