### ISSUE TITLE
Deluge handshake error

### ISSUE THREAD

**Issue by Azno** [DobyTang/LazyLibrarian#188]
Hi there, is anyone else getting this issue when they try to setup deluge for torrents?

Exception in thread SEARCHMAGS:
traceback (most recent call last):
File "F:\Python27\lib\threading.py", line 810, in __bootstrap_inner
self.run()
File "F:\Python27\lib\threading.py" line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "F:\PLazyLibrarian-master\lazylibrarian\searchmag.py", line 279, in search 
_magazines
TORDownloadMethod(items['bookid'], items['nzvprov'], items['nztitle'], items['nzbur'])
File "F:\lazylibrarian-master\lazylibrarian\searchtorrents.py", line 229, in TORDownloadMethod
client.connect()
File "F:\lazylibrarian-master\lib\deluge_client\client.py", line 43, in connect
self._socket.connect((self.host,self.port))
file "F:\python27\lib\ssl.py", line 844, in connect
self._real_connect(addr,False)
file "F:\python\lib\ssl.py", line 835, _real_connect
self.do_handshake()
file "F:\python\lib\ssl.py", line 808, in do_handshake
self.sslobj.do_handshake()
SSLError: ('_ssl.c:574: The handshake operation timed out;,)

(took me forever to type that out as LL doesnt log this king of error.

Donwload settings:

Deluge Host: localhost
Deluge Port: 38081
Deluge Username: 
Deluge Password: *****

Cheers

**Comment by Azno** [comment]
Also Deluge doesnt need a username tab, would be better if that was changed to a label tab instead :)

**Comment by philborman** [comment]
I can confirm its not working here either. Transmission works fine. 

The blackhole option should work though. Have you tried that as a workaround.

**Comment by Azno** [comment]
I have but deluge for some reason doesnt like the .torrent files it black holes (although headphones works fine with blackhole option)

**Comment by philborman** [comment]
ok, fixed version in my git repository if you want to try it,  https://github.com/philborman/LazyLibrarian.git

there were a couple of issues, and also can you check your deluge port number, the default is 58846
the user/pass combination is for future versions of deluge that will need it.
the user/pass is stored in .config/deluge/auth  on a linux system. not sure what the location would be on a windows box, look for a deluge\auth file somewhere. it probably only contains one line, 
localclient:xxxxxxx
add a line after this with user:pass, eg
fred:mypassword

**Comment by Azno** [comment]
My Deluge daemon port is 58846
ah right okies wasnt aware!
there is is a deluge_client folder but inside is only client, recode and int .py files.

When you say add user/password do i just make a random user up?

**Comment by Azno** [comment]
Tried it with the daemon port in the settings tab in the user interface.

Exception in thread SEARCHMAGS:
Traceback (most recent call last):
  File "F:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "F:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "F:\LazyLibrarian-master\lazylibrarian\searchmag.py", line 279, in search
_magazines
    TORDownloadMethod(items['bookid'], items['nzbprov'], items['nzbtitle'], item
s['nzburl'])
  File "F:\LazyLibrarian-master\lazylibrarian\searchtorrents.py", line 229, in T
ORDownloadMethod
    client.connect()
  File "F:\LazyLibrarian-master\lib\deluge_client\client.py", line 45, in connec
t
    result = self.call('daemon.login', self.username, self.password)
  File "F:\LazyLibrarian-master\lib\deluge_client\client.py", line 83, in call
    exception_type, exception_msg, traceback = data
ValueError: need more than 1 value to unpack

Cheers

**Comment by philborman** [comment]
Yes that's what I got.  You get past the ssh timeout but need a
username/password.
I followed this guide, not sure what the file locations will be on windows
though.
http://dev.deluge-torrent.org/wiki/UserGuide/ThinClient
