### ISSUE TITLE
"local variable 'language' referenced before assignment" on Library import

### ISSUE THREAD

**Issue by metalgeekstl** [DobyTang/LazyLibrarian#198]
ERROR	Unable to complete the scan: local variable 'language' referenced before assignment

Latest Version: b727dca0d64462dd9da5bc4cc693b78c068b05d2

**Comment by philborman** [comment]
Fixed, waiting for it to be pulled into master branch. If you need to fix it quickly, in librarysync.py around line 301 just before the comment about metadata.opf there is a blank line, in there put 
language = "Unknown"
 This will get overridden if we can lookup the language later.

**Comment by philborman** [comment]
This is fixed now,  reorganised the metadata scanning
