### ISSUE TITLE
Failed to add nab from dogNZB

### ISSUE THREAD

**Issue by hctancredi** [DobyTang/LazyLibrarian#204]
I'm getting these errors right after finding something on dogNZB. Any clues?

Thanks

2015-12-27 20:48:16	ERROR	Failed to download nzb @ https://api.dognzb.cr
2015-12-27 20:48:16	ERROR	Connect Error to NZBget: could not add

**Comment by daktak** [comment]
Looks like an NZBget issue. What version of NZBget are you using? Can you try nzb blackhole?

**Comment by hctancredi** [comment]
I'm using NZBget 16.4. I will try blackhole and let you know.

**Comment by hctancredi** [comment]
blackhole is working like a charm. If you need anything that would help your problem determination .. please let know.. will be happy to help. BTW awesome work

**Comment by philborman** [comment]
After the message "could not add" it should say the nzb name, then "to the queue:" then an error message from nzbget. What does the error message say?  Might tell us what parameter it didn't like?

**Comment by MiTeePingWin** [comment]
NZBGet 16.3 works fine for me using DOGNzb.
Make sure your Host is set as your correct IP such as: 192.16.1.12:6789

**Comment by hctancredi** [comment]
I will have to reproduce it today, my log wraped.

**Comment by hctancredi** [comment]
I switched from localhost:6789 to my ip:port and it's working again... just making a few more tests
