### ISSUE TITLE
qBittorrent - Invalid torrent

### ISSUE THREAD

**Issue by MiTeePingWin** [DobyTang/LazyLibrarian#206]
qBittorrent picks up everything as invalid through blackhole if it's grabbed through LazyLibrarian. Manually grabbing the torrent works fine.

[Laini_Taylor_-_Daughter_of_Smoke_&_Bone_(Daughter_of_Smoke_&_Bone,_#1)_LL.(8490112).torrent.invalid.txt](https://github.com/DobyTang/LazyLibrarian/files/74101/Laini_Taylor_-_Daughter_of_Smoke_._Bone_.Daughter_of_Smoke_._Bone._.1._LL.8490112.torrent.invalid.txt)

**Comment by philborman** [comment]
Blackhole works with transmission/deluge, not sure why it won't with qBittorrent. Could you post the debug log, and the .torrent file that LazyLibrarian grabs.

**Comment by MiTeePingWin** [comment]
Sure.
Here's the debug log. The torrent file is attached in the post above, rename it from .torrent.invalid.txt back to .torrent.invalid   which is what qbittorrent renamed it to. Github only allows certain file types.

[torr.txt](https://github.com/DobyTang/LazyLibrarian/files/74304/torr.txt)

**Comment by philborman** [comment]
Thanks for that.

Strange, LL working as expected, log looks fine, but the downloaded file 
is not a torrent, it's a html file.

Inside the file is a link to the torrent file,  and a magnet link.
Seems torcache.net adds a level of redirection that's not expected.
Not sure how to handle this.

**Comment by MiTeePingWin** [comment]
I'm guessing torcache.net is part of kat's grab? This means all torrents from KAT wouldn't work then (via blackhole at least).

**Comment by philborman** [comment]
Guess so. I know KAT works with transmission.
I will try blackhole and see what happens here.
I suppose we could add code to parse the html if there's not an easier way.

**Comment by philborman** [comment]
ok, found it. For some reason we send an extra header (Referer) if the torrrent source was KAT. No idea why. If we remove that extra header it all works as expected, KAT sends us a torrent, not html.

Fix should be uploaded soon.

**Comment by MiTeePingWin** [comment]
Hey hey! The fix worked!
Thank you  :)

**Comment by philborman** [comment]
Thanks, can you close the issue
