### ISSUE TITLE
30-12-15: Attempt to add author results in error

### ISSUE THREAD

**Issue by sukhysall** [DobyTang/LazyLibrarian#208]
Hi

Found the below bug and following an update to version "55ce9cf7e3c8ed5039b423c9fe917d189649af59" , the bug is still present:

I just carried out an author search. When I clicked on "Add Author" I got the following error message:

404 Not Found

Missing parameters: AuthorName

Traceback (most recent call last):
  File "/volume1/@appstore/LazyLibrarian/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/volume1/@appstore/LazyLibrarian/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/LazyLibrarian/cherrypy/_cpdispatch.py", line 35, in __call__
    raise sys.exc_info()[1]
HTTPError: (404, 'Missing parameters: AuthorName')

when I added "Add book" there was no issue and the book was added successfully. I only get the above error message for the Author.

I think I understand where the issue lies. I copied the link that for the button i clicked on and I got:

(Failed link) http://192.168.0.15:5299/addAuthor?authorname=Steven%20Pinker

Now if I change the "authorname" to "AuthorName" and pasted the edited link which is now:

(Working link) http://192.168.0.15:5299/addAuthor?AuthorName=Steven%20Pinker

The author is successfully added.

I'm unsure when this occurred but I did add an author approximately 3 days ago with no issue so it's got to be in the last couple of commits

**Comment by philborman** [comment]
Ah, typo in searchresults.html, Lines 50 and 55 if you want to edit them for a quick fix. 
It takes you to the newly added authors page instead of back to the result list, which seems more logical, but the result list uses lowercase authorname and the author page uses AuthorName
