### ISSUE TITLE
Wont update allthough it tells me I'm 19 commits behind

### ISSUE THREAD

**Issue by In0cenT** [DobyTang/LazyLibrarian#232]
Hello

In my logs I see:

2016-01-11 23:23:27	INFO	[VersionCheck] - New version is available. You are 19 commits behind
2016-01-11 23:23:25	INFO	[VersionCheck] - Comparing currently installed version with latest github version

How do I update?

**Comment by philborman** [comment]
Sometimes happens if you have a locally changed file?
In a terminal cd to the installation directory and try "git pull"

**Comment by In0cenT** [comment]
No changes made, "git pull" told me its up to date.

**Comment by philborman** [comment]
Try "git status"     might show something as modified.
if there is, "git checkout" the changed file, then "git pull" again

if there is nothing modified, I don't know.
Maybe delete the whole directory and "git pull" the entire program,
eg "git pull https://github.com/DobyTang/LazyLibrarian.git"
as long as there is no config/library or anything else in the directory.

**Comment by In0cenT** [comment]
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        Anthony Horowitz/
        Christopher Paolini/
        George R.R. Martin/
        J.R.R. Tolkien/

nothing added to commit but untracked files present (use "git add" to track)

No editing has been made, I've allready redownloaded everything -> still the same...

**Comment by philborman** [comment]
Could you remove the directory and start again, or download into a new 
directory, git leaves hidden files in the directory which might be part 
of the problem?

**Comment by philborman** [comment]
Managed to reproduce it here by deleting config.ini
Will work on a fix, but for now if you edit config.ini lines that say 
current_version = 4f260a7c533dd9dac43609376a315640a2d12356
latest_version = 4f260a7c533dd9dac43609376a315640a2d12356

Change both settings to match whatever value you have in current_version

**Comment by pr0fetul** [comment]
Hi @philborman - any update on this? I am still unable to update from the web interface.

**Comment by philborman** [comment]
no sorry, can't see why its not working. My best suggestion is delete the whole lazylibrarian folder and reinstall. Your library and config should be in your user directory so they should be preserved.

**Comment by pr0fetul** [comment]
Ok, I have renamed the old lazylibrarian folder - just in case - and re-downloaded and setup lazylibrarian from your repository- and now it seems ok.The settings were preserved along with the authors already added. 
Thank you for the solution.

**Comment by philborman** [comment]
No problem.

Wish I knew why it happened though, don't like mysteries.
