### ISSUE TITLE
Support plain RSS feeds?

### ISSUE THREAD

**Issue by tymanthius** [DobyTang/LazyLibrarian#233]
I was wondering if rss feeds are supported so that torrent indexers can be included more easily?

Or point me in the direction of where to set them up?

**Comment by philborman** [comment]
Not at present, could  be a useful addition though.
Any examples I could look at?

**Comment by tymanthius** [comment]
Such as an example from my feed from anonymouse? I guess I could do that.  :)

Although I'd think you could rob code from any of the projects out there that grab rss feeds like sonarr & such.

**Comment by philborman** [comment]
yes, it's not the code, just a feed that has books that I can try grabbing results from.
How often do the feeds need checking, daily/hourly? as I guess we would need to run the check separately to the current nzb/torrent scans

**Comment by tymanthius** [comment]
I would make it a configurable settting. I know for my tv show stuff I have it configured at 22 minutes just so that the server isn't slammed every 15 by 1000 users.  ;)

I'll have an example feed in a few.

**Comment by tymanthius** [comment]
Here you go:  http://hastebin.com/opomijedet.xml

**Comment by philborman** [comment]
Thanks for that.
Haven't used rss except for news feeds on the desktop.

Doesn't look too hard, we already have feedparser library in 
lazylibrarian for KAT which parses the xml you sent fine.

Just need to add config entries for some feeds (how many do you think?), 
and set up a job to run every x minutes to parse the feed.rss for wanted 
books/magazines.

The links in the xml you sent go to a login page so I guess we need to 
add authorisation, is that a login/password combo, or do you have an api 
key like nzb providers?

Might only take a few days to rustle up something.

**Comment by tymanthius** [comment]
For me, the links go straight in. I'd say leave out the authentication and just let the user handle it.

Some rss feeds do include api keys in the feed tho.  

Let me pull one from baconbits and see if that is diff.

Yep, here it is:  http://hastebin.com/cuwukepayo.xml

**Comment by philborman** [comment]
Thanks,
The first link looks like this...
http://www.myanonamouse.net/t/283825&amp;hit=1
which goes to a page saying "Not signed in"  so maybe if you are signed 
in first outside of LazyLibrarian it will work based on the request 
coming from your ip address?
If it looks for a cookie from the browser we're out of luck as we are 
not inside the browser
I can't test this. Looks like there is no way of passing the signin 
details in the request for the link?

The second link looks like this...
http://baconbits.org/torrents.php?action=download&authkey=<authkey>&torrent_pass=<password.hashed>&id=185398
which is more hopeful, we need to put authkey and hashed password in the 
request for it to work
so I guess we just need boxes in config for rss_url, authkey, password. 
We have hashlib already.

I will have a think about it and try to rustle up something to test over 
the next few days.

**Comment by philborman** [comment]
Just checking if this is working now, I've used RSS feeds for kat (plain)  and usenet_crawler (auth embedded in the rss feed query) but don't have any sites I can use that need separate pass/user providing. Thx.

**Comment by tymanthius** [comment]
I'll have to update & test. I've not been playing w/ books lately.
