### ISSUE TITLE
[Bug] I can't delite magazines with é in the name

### ISSUE THREAD

**Issue by maxcore** [DobyTang/LazyLibrarian#240]
Magazine Name : Elle Québec

![capture d ecran 2016-01-17 10 14 04](https://cloud.githubusercontent.com/assets/4043787/12378142/4c4aa792-bd03-11e5-828c-be9947d7746d.png)

**Comment by philborman** [comment]
Think it deletes, but fails when it tries to log message. Should be fixed in next release
