### ISSUE TITLE
common missing from searchnzb.py

### ISSUE THREAD

**Issue by warlord0** [DobyTang/LazyLibrarian#241]
```
18-Jan-2016 14:18:57 - DEBUG :: SEARCHNZBBOOKS : Nzbfile has been downloaded from http://bookstrap.whalesanctuary.co.uk/getnzb/1fa4c9c3cf3b21bc0b59723fc6b11d38.nzb&i=1&r=8c728f40fa8cb270b86bed90285a9528
Exception in thread SEARCHNZBBOOKS:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/paulb/LazyLibrarian/lazylibrarian/searchnzb.py", line 88, in search_nzb_book
    found = processResultList(resultlist, book, "shortbook")
  File "/home/paulb/LazyLibrarian/lazylibrarian/searchnzb.py", line 178, in processResultList
    common.schedule_job(action='Start', target='processDir')
NameError: global name 'common' is not defined
```

Added
```
import lazylibrarian.common as common
```
and the error goes away.

**Comment by philborman** [comment]
Thanks for that, 
fixed in todays release ;-)

**Comment by warlord0** [comment]
Not sure how else to contact you. So sorry if this appears rude.

I've been working on a few themes for projects I use. One of them newznab and thought I'd have a go with LazyLibrarian too. Feel free to have a look.

https://github.com/warlord0/lazylibrarian.bookstrap

I'm pretty new to git, so hope you can get what I was hoping for.

**Comment by philborman** [comment]
I'm away from home today so will try to look at this tonight.  The project
has been dormant for quite a while and I  seem to be the only one working
on it at the moment so any help is welcome!

I have added a few new features,  bug fixes and enhancements,  but I'm not
really a programmer,  learning as i go along.

The web interface needs quite a bit of work especially on small screens,
and i have no experience of html css so feel free to have a go if you wish😁

My email is Phil.borman@gmail.com if you want to discuss anything

**Comment by warlord0** [comment]
Thanks Phil,

I've not done anything on the underlying code as python is a bit of a
stretch for me. HTML & CSS I've pretty much replaced the entire default
theme with one that uses bootstrap. So small screens work just fine. I
let bootstrap do all that work for me.

Got a few issues yet to resolve, but so far it works well for me on
books at least.

I've tried to get every page into html compliance but there's one thing
that niggles me. The use of destination2 in searchresults.html

It combines a string and a variable:

destination = "authorPage?AuthorName="+result['authorname']

The authorname invariably contains a space, which is not legit html for
a url and should be escaped. But if I use the url escape in the output as:

${detination2|u}

Then it escapes the whole sequence including the ? and = in the string
so the url breaks :(

Ideally I need to escape it at the result['authorname'] stage like
escape(result['authorname']), but I have no clue with mako and python on
how to do that. Can you offer any insight?

--
Paul

**Comment by philborman** [comment]
Hey, looks good!
The screenshots are great.

Should be easy enough to change the search results passed to the html 
_before_ passing them over. The AuthorName and BookName may both contain 
spaces, and also possibly other "illegal" characters. There are 
functions in LazyLibrarian to do this, I just need to apply them to the 
function in webServe.py that calls the html template.

Shouldn't take long, are you using current branch from DobyTang, as I do 
most of my development work on my branch...
https://github.com/philborman/LazyLibrarian.git
and then move them over to DobyTang when complete.

**Comment by warlord0** [comment]
Hi, yeah I'm using the current branch. Now I fixed the config.html as below.

You may like this... or not :)

http://i.imgur.com/EjLaJGT.png

Also, I like the fact you converted the newznab providers to an array.
Frustratingly I spent ages on the config.html page - then you change it
to make it easier. All done now and I updated github. I'm fairly new to
git versioning. Now I am working two projects with different versioning
tools, both git and subversion.

I'm trying to work out how the updates work. I call the /update url but
then is it supposed to redirect me one the job is successful?

**Comment by philborman** [comment]
Love the icon!

We definitely need a new icon, even DobyTang suggested that himself a 
couple of years back but he isn't around and doesn't seem to even keep 
an eye on the git any more - or at least never any feedback from him.

Current branch is matching mine at the moment apart from the html which 
I was working on a bit yesterday. Nothing worth keeping though.

I moved newznab/rss/torznab into arrays and used variable argument list 
so we can have unlimited numbers of feeds rather than me deciding how 
many to set. Also added code to put a new empty entry on the end if the 
slots are full - well, actually only checks the last slot. I think this 
has made it into the DobyTang branch. Will check. Won't interfere with 
your work anyway.

Sadly you can't auto update your changes into DobyTang master, you need 
write access, and the only one who can give that is DobyTang.

I don't have write access either, I send my updates as a "pull" request 
from my git - I can give you write access to that if you want, or if 
nncrypted is monitoring this thread he can perhaps help as he has write 
access :-)

Kind regards,

Phil

**Comment by warlord0** [comment]
It did make it into DobyTang and it's not an issue. I just rebuilt the
config page to suit.

If I knew what a pull request was that is :) As said I'm kinda new to
this. I only included files in my git that don't class with the DobyTang
ones at all. Most of my html doesn't even use the styles and scripts
other than the ones I included. It makes use of the Max CDN for
bootstrap and fontawesome. So there's no local copies.

If you were to clone my git into your data folder you should find it
just works alongside. Well it certainly does with the DobyTang version.
If you want to just consume it into your project that's fine too. I'm
not prissy about rights and credit.

**Comment by philborman** [comment]
ok, just submitted the changes, waiting for them to be pulled in.
nncrypted is usually quite quick - just noticed he has done it while I'm 
typing this message!

**Comment by warlord0** [comment]
Woop. Nice now my index, author and boos pages are all green for compliance!

Magazines isn't though.

searchForMag?bookid=yada yada

**Comment by philborman** [comment]
ok, magazine search and open now both converted too. Any others just let 
me know. I will have a look and see if I spot any more myself, but your 
compliance tool seems to do the work for us!

Kind regards,
Phil

**Comment by philborman** [comment]
Not quite working on all titles, can't immediately see why. Screenshot 
attached.
Below the selection list (wanted,have,skipped,ignored) and before the 
main book table starts, it has put the title and subtitle for book 2 in 
the table, and in the table line 2 all columns are shifted left

**Comment by warlord0** [comment]
No screenshot?

**Comment by philborman** [comment]
![screenshot from 2016-01-19 19-41-01](https://cloud.githubusercontent.com/assets/12158777/12428892/a236aea4-bee7-11e5-810e-baa63ea4b3e3.png)

**Comment by warlord0** [comment]
Hmm bit quirky. I've added that author and only get 1 book result and it
appears fine.

What does the underlying html look like?

**Comment by philborman** [comment]
Here is the html, and a screenshot of the same author on the default interface


<!doctype html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>LazyLibrarian - Amanda Knox</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <link rel="shortcut icon" type="image/png"  href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/templogo.png">
    
    
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/s/bs-3.3.5/jqc-1.11.3,dt-1.10.10,b-1.1.0/datatables.min.css"/>
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/flatly/bootstrap.min.css" rel="stylesheet">
    
    
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    
    <link href="css/bookstrap.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="https://code.jquery.com/jquery-migrate-1.3.0.min.js"></script>
        
    <script src="js/lazylibrarian-bs.js"></script>
    
    


    
    <script type="text/javascript">
        // Allow the user to reset the search filter
        $(document).ready(function () {
            $.fn.dataTableExt.oApi.clearSearch = function ( oSettings ) {
                var table = this;

                //var clearSearch = $('<img title="Delete" alt="" src="data:image/png;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAD2SURBVHjaxFM7DoMwDH2pOESHHgDPcB223gKpAxK34EAMMIe1FCQOgFQxuflARVBSVepQS5Ht2PHn2RHMjF/ohB8p2gSZpprtyxEHX8dGTeMG0A5UlsD5rCSGvF55F4SpqpSm1GmCzPO3LXJy1LXllwvodoMsCpNVy2hbYBjCLRiaZ8u7Dng+QXlu9b4H7ncvBmKbwoYBWR4kaXv3YmAMyoEpjv2PdWUHcP1j1ECqFpyj777YA6Yss9KyuEeDaW0cCsCUJMDjYUE8kr5TNuOzC+JiMI5uz2rmJvNWvidwcJXXx8IAuwb6uMqrY2iVgzbx99/4EmAAarFu0IJle5oAAAAASUVORK5CYII=" style="vertical-align:text-bottom;cursor:pointer;" />');
                
                var clearSearch = $('<i class="fa fa-remove" style="cursor:pointer;width:16px;text-align:left;" title="Reset Search"></i>');
                $(clearSearch).click( function ()
                        {
                                table.fnFilter('');
                                $('input[type=search]').val('');
                        });
                $(oSettings.nTableWrapper).find('div.dataTables_filter').append(clearSearch);
                $(oSettings.nTableWrapper).find('div.dataTables_filter label').css('margin-right', '-16px');//16px the image width
                $(oSettings.nTableWrapper).find('div.dataTables_filter input').css('padding-right', '16px');
            }

            //auto-execute, no code needs to be added
            $.fn.dataTable.models.oSettings['aoInitComplete'].push( {
                "fn": $.fn.dataTableExt.oApi.clearSearch,
                "sName": 'whatever'
            });
        });
    </script>
    
        
<script type="text/javascript">
    $(document).ready(function()
    {
        $('#book_table').dataTable(
            {
                "order": [],
                "columnDefs": 
                    [{ targets: 'no-sort', orderable: false }] // Don't allow colums of class no-sort to be sorted
                ,
                "oLanguage": {
                    "sLengthMenu":"Show _MENU_ books per page",
                    "sEmptyTable": "No books found",
                    "sInfo":"Showing _START_ to _END_ of _TOTAL_ results",
                    "sInfoEmpty":"Showing 0 to 0 of 0 books",
                    "sInfoFiltered":"(filtered from _MAX_ total books)"},
                "sPaginationType": "full_numbers",
                "bStateSave": true,
                "aLengthMenu": [[5, 10, 15, 25, 50, 100, -1], [5, 10, 15, 25, 50, 100, "All"]],
                "iDisplayLength": 10,
            });
			$('.dataTables_filter input').attr("placeholder", "Seach table here");
    });
</script>

    <script type="text/javascript">
        // Check or uncheck all checkboxes in the same table
        function toggleAll(e) {
            var table = $(e).closest('table');
            $('td input:checkbox', table).prop('checked', e.checked);
        }
    </script>
    <script type="text/javascript" src="https://cdn.datatables.net/s/bs-3.3.5/jqc-1.11.3,dt-1.10.10,b-1.1.0/datatables.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="js/bootbox.min.js"></script>
    <script src="js/bootstrap-notify.min.js"></script>

</head>
<body>
    <div id="container">
                    
        <header>
            <nav class="navbar navbar-default navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#MainNav" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/"><i class="fa fa-home"></i> LazyLibrarian</a>
                    </div>
                    
                    <div class="collapse navbar-collapse" id="MainNav">
                        <ul class="nav navbar-nav">
                            <li><a href="home" class="navbarele">Authors</a></li>
                            <li><a href="books" class="navbarele">Books</a></li>
                            <li><a href="magazines" class="navbarele">Magazines</a></li>
                            <li><a href="manage" class="navbarele">Manage</a></li>
                            <li><a href="history" class="navbarele">History</a></li>
                            <li><a href="logs" class="navbarele">Logs</a></li>
                            <li><a href="config" class="navbarcfg"><i class="fa fa-cog"></i> Config</a></li>
                        </ul>
                        
                        <form class="navbar-form navbar-right" action="search" method="get">
                            <div class="form-group">
                                <div class="input-group">
                                    <input type="text" class="form-control deletable input-sm" value="" onfocus="if(this.value==this.defaultValue) this.value='';" name="name" placeholder="Title / Author / ISBN" id="searchbox">
                                    <span class="input-group-btn">
                                        <button type="submit" class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                                    </span>
                                    
                                </div>
                            </div>
                            
                        </form>                        
                    </div>
                </div>
            </nav>
            
            <div id="subnav" class="navbar-inverse">
                <div id="subhead" class="container">
                    
    <div id="subhead_container">
        <form id="subhead_menu" class="form-inline">            
            <a href="refreshAuthor?AuthorName=Amanda+Knox" class="btn btn-sm btn-primary"><i class="fa fa-refresh"></i> Refresh Author</a>
            <a href="deleteAuthor?AuthorID=6471656" class="btn btn-sm btn-primary"><i class="fa fa-remove"></i> Delete Author</a>
                <a href="pauseAuthor?AuthorID=6471656" class="btn btn-sm btn-primary"><i class="fa fa-pause"></i> Pause Author</a>
            <a href="authorPage?AuthorName=Amanda+Knox&amp;Ignored=True" class="btn btn-sm btn-primary"><i class="fa fa-ban"></i> Ignored Books</a>
                <div class="form-group pull-right">
                    <label for="chooselanguage"><small>Language</small></label>
                    <select class="form-control input-sm" id="chooselanguage" onchange="location = 'authorPage?AuthorName=Amanda+Knox&amp;BookLang=' + this.options[this.selectedIndex].value;">
                        <option value="">All</option>
                        <option value="eng">eng</option>
                    </select>
                </div>            
        </form>
    </div>

                </div>
            </div>
        </header>

        <div id="main" class="main container" style="zpadding-top: 120px;">
            
<div class="row">
    <div id="authorart_container" class="col-md-3">
        <div id="authorart_menu">
            <img src="http://s.gr-assets.com/assets/nophoto/user/f_200x266-3061b784cc8e7f021c6430c9aba94587.png" class="box-shadow img-responsive" alt="Amanda Knox" title="Amanda Knox">
        </div>
    </div>

    <div id="authorhead_container" class="col-md-9">
        <div id="authorhead_menu">
            <h1><a href="http://www.goodreads.com/author/show/6471656.Amanda_Knox" target="_blank">Amanda Knox</a></h1>
            <p><b>Born:</b> 1987/07/09</p>
            <p><b>Totalbooks:</b> 2</p>

            
            <div class="row" title="50.0">
                <div class="col-xs-4"><strong>Progress:</strong></div>
                <div class="col-xs-4">
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="50.0" aria-valuemin="0" aria-valuemax="100" style="width: 50.0%;">
                        <span class="sr-only">50.0% Complete</span>
                    </div>                    
                </div>
                </div>                
                <div class="col-xs-4">
                    <span class="progressbar-front-text">1 / 2</span>
                </div>
            </div>
        </div>
    </div>
</div>

<form action="markBooks" method="get" class="form-inline">            
    <div class="indented">
        
            <input type="hidden" name="AuthorName" value="Amanda Knox">
            <input type="hidden" name="redirect" value="author">
            <div class="form-group">
                <label for="action" class="">Mark selected as</label>
                <select class="markBooks form-control input-sm" id="action" name="action">
                    <option value="Wanted">Wanted</option>
                    <option value="Have">Have</option>
                    <option value="Skipped">Skipped</option>
                    <option value="Ignored">Ignored</option>
                </select>                
            </div>
            <input type="submit" class="markBooks btn btn-sm btn-primary" value="Go">
        
    </div>
    <p>&nbsp;</p>
<div class="table-responsive">
    <table class="display table table-striped table-hover table-bordered" id="book_table">
        <thead>
            <tr>
                <th class="select no-sort">
                    <input type="checkbox" onClick="toggleAll(this)" />
                </th>
                <th class="bookart col-xs-1 text-center no-sort hidden-xs">Cover</th>
                <th class="bookname col-xs-3">Title</th>
                <th class="series col-xs-2">Series</th>
                <th class="seriesOrder col-xs-1 text-center">Num.</th>
                <th class="stars col-xs-1 text-center hidden-xs">Rating</th>
                <th class="date col-xs-1 text-center">Released</th>
                <th class="language col-xs-1 text-center hidden-xs">Language</th>
                <th class="status col-xs-1 text-center">Status</th>
            </tr>
        </thead>

        <tbody>
                
                <tr>
                    <td class="select"><input type="checkbox" name="XndgT2jYfhIC" /></td>
                    <td class="bookart text-center hidden-xs"><a href="http://books.google.es/books/content?id=XndgT2jYfhIC&printsec=frontcover&img=1&zoom=1&source=gbs_api" target="_blank"><img src="http://books.google.es/books/content?id=XndgT2jYfhIC&printsec=frontcover&img=1&zoom=1&source=gbs_api" height="75" width="50" alt="Cover"></a></td>
                        <td class="bookname"><a href="http://books.google.es/books/about/Waiting_to_Be_Heard.html?hl=&id=XndgT2jYfhIC" target="_blank">Waiting to Be Heard</a></td>
                    <td class="series">None</td>
                    <td class="seriesOrder text-center">None</td>
                    <td class="stars text-center hidden-xs"><img src="images/3-stars.png" alt="Rating"></td>
                    <td class="date text-center">2013-05-01</td>
                    <td class="language text-center hidden-xs">eng</td>

                        <td class="status text-center"><a class="btn btn-xs btn-success button green" href="openBook?bookid=XndgT2jYfhIC" target="_self">Open</a></td>
                </tr>
                
                <tr>
                    <td class="select"><input type="checkbox" name="DbSAMAEACAAJ" /></td>
                    <td class="bookart text-center hidden-xs"><a href="http://books.google.es/books/content?id=DbSAMAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api" target="_blank"><img src="http://books.google.es/books/content?id=DbSAMAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api" height="75" width="50" alt="Cover"></a></td>
                        <class id="bookname"><a href="http://books.google.es/books/about/Waiting_to_Be_Heard_LP.html?hl=&id=DbSAMAEACAAJ" target="_blank">Waiting to Be Heard LP</a><br>
                        <i class="smalltext">A Memoir</i></td>
                    <td class="series">None</td>
                    <td class="seriesOrder text-center">None</td>
                    <td class="stars text-center hidden-xs"><img src="images/3-stars.png" alt="Rating"></td>
                    <td class="date text-center">2013-04-30</td>
                    <td class="language text-center hidden-xs">eng</td>

                                    <td class="status text-center"><a class="btn btn-xs btn-default button">Skipped</a></td>
                </tr>
        </tbody>
    </table>
</div>
</form>
<p>&nbsp;</p>

        </div>
    </div>

<script type="text/javascript">    
    msg = '';

$(document).ready(function() {
    if (msg != '') {
        $.notify({
            icon: 'fa fa-check-square-o',
            message: msg
        },{
            type: 'warning'    
        });
    }
});
    
</script>
    
</body>
</html>




![screenshot from 2016-01-19 20-16-03](https://cloud.githubusercontent.com/assets/12158777/12429324/e2958798-bee9-11e5-8ba7-977e4c093716.png)

**Comment by warlord0** [comment]
Ok, well it's repeatable :D

I had to go get a google books api key to do it. Looks like it works
fine from goodreads, but something about the data from google is borking it.

**Comment by warlord0** [comment]
Found it, nailed it will update shortly.

There was a fudged html td tag. was <class= and needed to be <td class=

Only occurs if there's a subtitle

**Comment by philborman** [comment]
Yep, was just writing you an email, I spotted the subtitle difference too.
<td class=   vs   < class id=

**Comment by philborman** [comment]
That's fixed it - quick work!

I'm about done with the python side of LazyLibrarian for now, might look at doing some documentation for it next. Took me a while to get back into programing again, not done any serious coding for 15+ years, and then it was mainly 'C' and Motorola 68000 assembly stuff, but I retired a year ago and wanted a challenge. Learning a bit of python was fun.

**Comment by warlord0** [comment]
I'm no coder. Just have a spread of knowledge over too many things in
IT. Enough logic to poke about with a few languages, but not a master of
any.

At least I'm not the only old fart working on stuff :D Still got more
than a few years before retirement, but no spring chicken.

I have a handle on grabbing everything off usenet other than books, so
thought I'd poke around with newznab and lazylibrarian. I've
bookstrapped newznab too and they may be including it in their release too.
