### ISSUE TITLE
Removing Alternate Folder on Import

### ISSUE THREAD

**Issue by warlord0** [DobyTang/LazyLibrarian#248]
When I use the import book button from the Manage page it successfully imports the book from within the Alternate Import/Export Folder but then removes the folder as well as the book it imported.

eg.

/home/warlord/temp

After the import the temp folder is gone.

**Comment by philborman** [comment]
Yes that's sort of intentional, same as if you snatched a book with sab or a torrent downloader. The downloaded book is put into it's own separate folder, and when you import the book it gets moved into the LazyLibrarian structure.  If you want to copy it, rather than move it, set destination_copy = True
in the config file.
It's meant to work more like 
/home/warlord/temp/book_to_import/book1.epub
home/warlord/temp/another_book_to_import/book2.epub

needs documenting :-)

**Comment by warlord0** [comment]
Documentation would be good :D

I can probably update the interface with some help tips after the
documentation. Once I understand how magazines work which seems a bit
stranger than books to figure out.

I must confess to not using it to actually store and process files. I
just want it to search and then tell sab to snatch them. Once that's
done it's over to me to decide if I want them in calibre or not.

**Comment by philborman** [comment]
Magazines are a bit more complex as there is no central repository to look
them up like goodreads for books

Search is done purely on title.  Titles have to include a date in a format
and language we can identify.  This can be tricky as there is no consistent
way of naming them.  We then grab one copy of each issue we can find,
providing its date is within the last month.  Older issues,  issues with no
date,  or a date we can't determine get listed in the 'past issues'
section  so user can select them for download manually.

The "weekly, fortnightly, monthly"  select box is ignored and can probably
go. It was put in by the original author to aid date matching but that code
is much more thorough now and doesn't need user to specify the frequency.

Magazines that are downloaded are put in separate folders under title,
then issue,  a cover page is generated if imagemagick is available.  On the
magazine page,  if we only have one issue the open  button opens it.  If we
have multiple issues,  it opens a page showing all the available issues
with covers to aid selection.

Now i've thought about it again i should remove that frequency select box
and table column.  Little task for tomorrow i think.

**Comment by warlord0** [comment]
Delete magazines is now broken because of the url encoding on book
title. Works for a magazine with a single name.

For example, the checkbox values are now appearing in the html as
"linux+journal". So when the form is submitted I'm guessing the query is
not finding a matching title because of this escaping.

**Comment by philborman** [comment]
Strange, works on the default interface. See screenshot below.
Guess I need to "unescape" the returned values, though why would it work in default?

I have also removed the "frequency" checkbox and column from magazines as not used, and there are a lot of redundant import statements in the html that have now gone.
You can also delete album.html, extras.html, manageartists.html, managenew.html, upcoming.html
as they are not part of LL :-)

![screenshot from 2016-01-20 16-16-43](https://cloud.githubusercontent.com/assets/12158777/12452956/52071892-bf91-11e5-9439-6ff0b6bd8999.png)

**Comment by warlord0** [comment]
Ignore me. I had some stray |u 's from trying to escape stuff.

**Comment by philborman** [comment]
Can you mark this thread closed now. Thanks  :-)
