### ISSUE TITLE
Here's one that's really naughty

### ISSUE THREAD

**Issue by warlord0** [DobyTang/LazyLibrarian#252]
In the magazine issues it's giving me the full path (unescaped as well) to the file. Which then presumably the "openMag" script is grabbing the file and sending it out.

Bad thing about this is what if I changed the href to /etc/passwd - well I just tried it and although the file comes back pretending to be a rar file it is a text file and is my .etc.passwd file :o: 

```
<td class="issue text-center"><a class="button green btn btn-xs btn-warning" href="openMag?bookid=/home/warlord/base/_Magazines/linux journal/2016-01-01 - linux journal.pdf" target="_self"><i class="fa fa-book"></i> Open</a></td>
```

Needs the openMag to deal with the only the file name being sent, or better yet an id. It also should stop any funny business like changing if to ../../../etc/passwd or the like. Because even if you used a concatenation of [download dir] + [file name] the resulting path /home/warlord/base/../../../etc/passwd would still rape the system.

Most of us aren't going to be using this in a vulnerable environment or open to the elements, but it is a biggie.

**Comment by philborman** [comment]
Nice one! 
There is a comment in the code saying
#I think I need to consolidate bookid in args to unique values...
I wonder if the original author spotted that too but never got round to implementing it.
Should be easy enough to add a unique bookid (the bookid field currently holds title as you noticed), will also need some code to retro-fit a bookid to existing libraries and magazines in them.
Will look at this over the day or two. I submitted code to unescape the args yesterday but that won't be needed now for a bookid.

**Comment by philborman** [comment]
ok, fixed that. In issues.html if you use IssueID instead of IssueFile you pass a sha1 back and forth instead. Only using sha1 as the code is in LL anyway :-) 

Like the new gray theme, but noticed magazine covers are not standard sizes. Depends on the resolution of the original pdf they are generated from. Can you standardise them in the html, or would you like me to do it when I generate the images, if so, what size? On the original interface you just get a small thumbnail which comes up full size if you click on it.

Also spotted small typo in config.html,  Convesion program:

Thanks, Phil

**Comment by warlord0** [comment]
I'll have a look see in issues.html. Only trouble is that anything that
can be decyphered to a meaningful path can be hacked. But if it's a sha1
used as an id in the database as a lookup key then even if you submitted
a sha1 hash of /etc/passwd it wouldn't be found in the database. So I
guess it depends on the implementation.

I pretty much took all the style= attribs out so they can be made tidy
in a separate css. So images will be 100% original sizes right now. I
can add in a size attribute like width and a class of img-responsive so
on a large screen they'd be whatever the width specified and as you
squeeze the screen down they'll resize proportionally.

I'll sort the typo - that I can do easily :D

**Comment by philborman** [comment]
Yes, it's just a lookup key.
sha1 of title + issue eg "Linux Format 2015-12-01" no path or other 
details included
if the sha1 is in the database as an IssueID,  return the associated 
filename eg /media/nfs/Magazines/Linux Format/2015-12-01/Linux Format 
2015-12-01.pdf

Phil.

**Comment by warlord0** [comment]
Oh, and in case you didn't realise I just changed the theme by editing
base and sticking one in from here:

https://www.bootstrapcdn.com/bootswatch/

Basically just change "slate" to one of the others like flatly or
cerulean etc.

Some of them work quite well. Others have some issues with buttons and
input sizing.

**Comment by philborman** [comment]
Ah, interesting.

Does that mean you could name the bootstrap theme you want on the 
configure page and I could add some python code to download/install a 
new one that way?

**Comment by warlord0** [comment]
You certainly could.

If you want to get creative a list of the available themes is available
via api call.

https://bootswatch.com/api/3.json

**Comment by warlord0** [comment]
Oh, and no need to download it. It is using the theme directly from the
cssCdn value over at maxcdn. So you could just store the name and
template it:

<link
href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/${bootswatch}/bootstrap.min.css"
rel="stylesheet">

The commented out

<link
href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
rel="stylesheet">

Is the base bootstrap style without any themes

**Comment by philborman** [comment]
Added bookstrap theme selection. See example in config.html. Uses a hidden checkbox for testing, so bookstrap options only appear if bookstrap is installed and selected, ie no options appear on default theme. I can remove this code once the select box and method is copied into your config.html
The theme select box should only appear if you're using bookstrap.
I suppose I could test for bookstrap during init and only download a list of themes if it's installed. Might add that. Won't affect the config section.

**Comment by warlord0** [comment]
I'm struggling on a bit of mako I think. Trying to get the class
attribute to set to class="hidden" if the current
lazylibrarian.HTTP_LOOK is equal to 'bookstrap'

Here's what I have:

<div class="checkbox" class="hidden"> 
    <label for="bookstrap" class="control-label">
    <input type="checkbox" name="use_bookstrap" id="bookstrap" value="1"
${checked} />
        Use Bookstrap</label>
</div>
<%                                          
    if lazylibrarian.HTTP_LOOK == 'bookstrap':
        class = 'class="hidden"'
    else:
        class = ''
%>
<fieldset id="bookstrap_options"
${class}>                                                                                      

    <div class="form_group">
        <label for="bookstrap_theme" class="control-label">Bookstrap
Theme:</label>
        <select name="bookstrap_theme" id="bookstrap_theme"
class="form-control">
        %for bookstrap_theme in lazylibrarian.BOOKSTRAP_THEMELIST:
            <%
                if bookstrap_theme == lazylibrarian.BOOKSTRAP_THEME:
                    selected = 'selected="selected"'
                else:
                    selected = ''
            %>
            <option value="${bookstrap_theme}"
${selected}>${bookstrap_theme}</option>
        %endfor
        </select>
    </div>
</fieldset>

When I run the page I get:


      SyntaxException: (SyntaxError) invalid syntax (<unknown>, line 2)
      (u"if lazylibrarian.HTTP_LOOK == 'bookstrap':\n cla") in file
      '/home/warlord/LazyLibrarian/data/interfaces/bookstrap/config.html' at
      line: 132 char: 41

Hoping you can spot something I can't.

Later on in the Javascript I can then unhide/hide it if you change the
<select> value.

    $('#http_look').change(function() {
        if ($(this).val() == 'bookstrap') {
            $('#bookstrap_options').removeClass("hidden");
        } else {
            $('#bookstrap_options').addClass("hidden");
        }
    });

I've hidden the "use_bookstrap" as it's not really needed if you can
establish the use from the http_look value.

**Comment by philborman** [comment]
Probably don't need any of it. Since your config.html only runs if user is in bookstrap, just always show the bookstrap theme selector.  I can take the selector out of the default theme config.html as there's no point offering the user a list of themes for a different interface. I hit the same problem with mako so used a hidden checkbox just to get it running.

**Comment by warlord0** [comment]
I guess that makes sense :)

I've changed base.html too, by taking a guess and it works fine:

<link
href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/${lazylibrarian.BOOKSTRAP_THEME}/bootstrap.min.css"
rel="stylesheet">

I'll git submit it shortly.

**Comment by philborman** [comment]
In config.html, could you change all the prompts for "Host" to "URL", ie "Newznab URL #1" 
apparently other similar apps call it URL rather than Host and one user has queried it.
I have just changed the default theme. The underlying global variables don't need changing, just the on-screen prompts. Thanks.

**Comment by warlord0** [comment]
Technically they'd be right.

How about the others like Torznab & RSS? They'd be URL's too.

**Comment by philborman** [comment]
yes, all the "host" changed to "url", and I think you already have api 
instead of password.
I'm leaving the rss user/pass for now as I don't know what we might 
need. I've only tried rss without auth so far

**Comment by philborman** [comment]
Hello again, just me making more work for you :-)
I have removed USE_RSS  USE_TOR  USE_NZB from config. They are now functions in the python code instead of globals, easier to maintain now we have the providers in arrays.
Could you remove the references to them in your config.html, and the associated show/hide functions.
Thanks.

**Comment by warlord0** [comment]
Are the providers limitless arrays? I can then see about each time
someone adds one, a blank one appears to add another. I'm just concious
that the way the interface population is done uses numbers. So I see
newznab_host1, newznab_api1 meaning they'd be submitted like that as
individual values.

If I populate the form as newznab[0...x][host], newznab[0...x][api] then
they'd be sent back as an array for you to process/iterate in python too.

**Comment by philborman** [comment]
Yes, sequential so the creation/scanning stops as soon as theres a 
missing number, ie 1,2,3,4,6,7,8 will stop after 4 cos theres no 5

Would be much better as arrays as that's how the python code uses them, 
but I couldn't figure out how to pass an array back and forth, but if 
you can do it in the html I can see what comes back in the argument list 
and adjust the python accordingly, then retro-fit it to the default 
interface.

I wasn't sure if mako could handle arrays, or only single variables

**Comment by warlord0** [comment]
The array on the html side is submitting ok, but the python needs
strangling or wrangling :)

This is what I see as the forms post parameters if I submit to a dummy page.

newznab[0][enabled] = "1"
newznab[0][host] = "a magic host"
newznab[0][api] = "Some made up api"

and so on through 1,2,3 and 4.

If I don't tick the enable checkbox for an item then newznab[x][enabled]
doesn't get posted at all.

If I post to the actual configUpdate page python throws this:


    500 Internal Server Error

The server encountered an unexpected condition which prevented it from
fulfilling the request.

Traceback (most recent call last):
  File "/home/warlord/LazyLibrarian/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/home/warlord/LazyLibrarian/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/warlord/LazyLibrarian/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/warlord/LazyLibrarian/lazylibrarian/webServe.py", line 257, in configUpdate
    lazylibrarian.config_write()
  File "/home/warlord/LazyLibrarian/lazylibrarian/__init__.py", line 723, in config_write
    add_newz_slot()
  File "/home/warlord/LazyLibrarian/lazylibrarian/__init__.py", line 843, in add_newz_slot
    if count == 0 or len(CFG.get('Newznab%i' % int(count-1), 'HOST')):
TypeError: object of type 'NoneType' has no len()

**Comment by philborman** [comment]
We currently put defaults in, so we can have newznab[0][enabled] = "0"
unless the form post says otherwise. Not all parameters have to be 
passed, so that's not a problem
as long as we know. I can check in the python if a parameter exists or not
eg
if newznab[0][enabled] in argv:
     result = newznab[0][enabled]
else:
     result = default_value

**Comment by warlord0** [comment]
Actually might make sense to send you config.html to see what it does.
I've only modified the newznab variables for now. Not sure how this
deals with attachments, so sent you it to gmail too.

Be warned. Because the form isn't processing the data you will lose your
form settings for newznab until the python bit works.

**Comment by philborman** [comment]
Can you mark this thread closed now please, we can continue any non-thread related stuff in private messages. Thanks.
