### ISSUE TITLE
magazine with multiple issues, every "open" is linked to the latest issue

### ISSUE THREAD

**Issue by sukhysall** [DobyTang/LazyLibrarian#254]
LL Ver: 702f4d60c820b06ce504dbb0c6c028eb84484660

Hello. Just me again. 

So I just want to say (and I should have said this a while ago) much love for all the focus on this amazing application. I couldn't manage without it and I'm glad that there are good people out there dedicated to continuously improving it.

So now we come to the one issue I have found (and it's shameful I didn't regression test this functionality following each commit what with me being a test engineer by trade :( )

I have some magazines with multiple issues (see screenshot). On my screenshot you see 3 seperate issues, but regardless of which issue I open, the only file that opens is the latest issue. I can confirm that the other issues are available. 

To double check I deleted the magazine and the folder off my NAS. I then re-added the magazine, LL went away and found all 3 issues again and I tried to open each issue and was still presented with the latest issue. 

So I went to the NAS folder where the issues are stored and I opened each file individually and can confirm that each file (all named correctly) has the correct magazine when opened. 

![same mag opens](https://cloud.githubusercontent.com/assets/5501195/12496138/aead70aa-c08b-11e5-83ad-b39f09e958df.jpg)

I hope this helps. Thanks again guys.

**Comment by philborman** [comment]
If you hover your cursor over the "Open" buttons, do you get a popup at the bottom of the screen showing you the link? Firefox and Chrome do this, not sure about other browsers.
The link will say openMag?bookid=xxxxxxxx
the xxxxxx part should be different for each magazine issue

**Comment by sukhysall** [comment]
Hi

Please see Issue #255 where I've added the links. I will close this issue and let it get sorted in #255.

That is unless you want me to keep the issue seperate rather than merge them into #255 ?

I'm happy either way. Please advise.

**Comment by sukhysall** [comment]
Closing this issue as it was a side effect of #255
