### ISSUE TITLE
How to add newsnab sources?

### ISSUE THREAD

**Issue by famewolf** [DobyTang/LazyLibrarian#260]
Other apps(headphones, couch potato sonarr and sickrage) ask for Url and API key when adding a custom newsnab source. LL asks for user and host.   How is this supposed to work?  No examples in wiki.  Nothing found on a google search.

**Comment by philborman** [comment]
Host is the URL (where to go, where the files are hosted)
User is the API key (identifies who you are)
I will reword these on the next release to match the other apps

**Comment by famewolf** [comment]
You may just be able to grab their code..it looks like you only allow 1?  Theirs has several presets then allows custom newsnab sources.  I have a handful of sites that only allow me to do anywhere from 5-20 api hits a day and then one or two that allow more.   I'm currently only dabbling in usenet/newsnab but have to admit all your apps works pretty well together (sonarr, htpcmanager, couch potato, lazy librarian and headphones).    I'm running them all from one freenas server but it looks like they are a host of pc's since each jail on the freenas is assigned it's own ip and port.

**Comment by philborman** [comment]
We allow an unlimited number.
As you use a "slot" another empty one appears below it.
We don't have any presets yet, only KAT for torrents.
Not looked at limit on api calls either. We could add a config option to 
hold a limit per provider, and count the calls, but I think if you 
exceed your limit you just don't get any results back.

Have to admit I like the way Sonarr works, but it's way outside my 
expertise to do anything like that ;-)

**Comment by famewolf** [comment]
Yeah..when I exceed my limit they quit working..which is a pain when you are trying to add them to a new app and the app keeps erroring out because you've exceeded your limit for the day.  Thanks for all the info!   I'll close this now.

**Comment by philborman** [comment]
No problem.

Thinking about it, there's not much point in me adding api counters as 
that would just be counting LazyLibrarian  apps calls, not any others 
apps you might have running.

**Comment by famewolf** [comment]
Oh...a simple solution to adding custom torrent sites might just be to allow the user to enter rss feeds.   It seems you already support rss feeds for nzb and pretty much any large torrent site has a rss feed....apparently only some of them contain the filesize but it works for your "sister apps".
