### ISSUE TITLE
"Open" for magazine with multiple issues returns user to magazine section

### ISSUE THREAD

**Issue by sukhysall** [DobyTang/LazyLibrarian#266]
Hi

Just took the latest commit: 27eb58a3259f3404c5272aafdece35d17c7aa3f1 

I can confirm if you have a single magazine and click "Open", the magazine will open as per usual.

However I have a few magazines with multiple issues and if I click on a particular magazine, I'm presented with the next page showing the issues (now with added covers :-) ) BUT if I click "open" on any issue of that magazine, I'm returned to the main magazine page.

So I have Mens Health which has a single issue and this opens OK:
http://192.168.0.15:5299/openMag?bookid=Mens+Health+UK (click this and magazine opens)

And I have Edge magazine which has multiple issues:
http://192.168.0.15:5299/openMag?bookid=Edge (click this and you get the page with the issues & covers)

But when I click on a  particular issue (as per link below):
http://192.168.0.15:5299/openMag?bookid=/volume1/magazines/Edge/2016-02-01/2016-02-01%20-%20Edge.pdf (click this and you're returned to the magazine section.

Sorry, forgot to add, debug log shows a line when I open the men's health mag but no other log entries for the issues that do not open.

**Comment by philborman** [comment]
Somehow got an old version of issues.html in the current release, newer ones use a bookid rather than magazine name, http://192.168.0.15:5299/openMag?bookid=/volume1/magazines/Edge/2016-02-01/2016-02-01%20-%20Edge.pdf

I have just uploaded the newest one again.

**Comment by sukhysall** [comment]
Hi

can confirm fix is working great. closing issue.
