### ISSUE TITLE
[REQ] Add download directory for Transmission

### ISSUE THREAD

**Issue by maxcore** [DobyTang/LazyLibrarian#272]
Lazy snatch a release but he dont put on /volume1/Downloads/EBOOK  (Processing folder) he put on default Transmission folder is /volume1/Downloads/TORRENTS .

My question is : Can you add directory for Torrent download ?

**Comment by philborman** [comment]
I will see, not sure.
Can you use the blackhole directory and get transmission to load torrent files from there?

**Comment by philborman** [comment]
Just found out how to do it,  If I upload a test version to my git can you try it?

**Comment by maxcore** [comment]
@philborman yes i can try it :)

**Comment by philborman** [comment]
ok, it's there now

**Comment by maxcore** [comment]
@philborman working ! thx

**Comment by philborman** [comment]
That's great news thanks 
Can you please close the issue now its working
