### ISSUE TITLE
fresh install ubuntu 15.10

### ISSUE THREAD

**Issue by HansKonings** [DobyTang/LazyLibrarian#274]
Hi 

First time install here on a ubuntu 15.10.
Python 2.7.10

locale -a
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX

Trying to run "python LazyLibrarian.py -d" results in:

`29-Jan-2016 14:15:31 - INFO :: MAIN : Checking database
Traceback (most recent call last):
  File "LazyLibrarian.py", line 179, in <module>
    main()
  File "LazyLibrarian.py", line 125, in main
    lazylibrarian.initialize()
  File "/opt/LazyLibrarian/lazylibrarian/__init__.py", line 630, in initialize
    build_monthtable()
  File "/opt/LazyLibrarian/lazylibrarian/__init__.py", line 928, in build_monthtable
    current_locale = locale.setlocale(locale.LC_ALL, '')  # read current state.
  File "/usr/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting`

**Comment by philborman** [comment]
I've been developing on ubuntu 15.10 here, so it should work :-)
What do you get from 'locale'  (without the -a)
The line it's crashing on in the python code is trying to read the current setting so it can restore it later.
locale.setlocale(locale.LC_ALL, '')
Also what is your setting in config for "Languages for month names"

**Comment by HansKonings** [comment]
Sorry about that and thanks for the hint.

locale (without the -a) gave an error, this fixed it:
locale-gen en_US en_US.UTF-8
dpkg-reconfigure locales
update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

Up and running now, very interested in your progress it's been a few years since my last install of LazyLibrarian!

**Comment by philborman** [comment]
Glad its fixed. I've added some extra error trapping in that section so it won't break now.

It's not really my project, but since no-one else has been working on it I thought I'd have a play. Learning as I go along.

The basic interface is quite dated and doesn't work well on small screens, but take a look at 
https://github.com/warlord0/lazylibrarian.bookstrap.git
 
Can you mark the issue as closed now (I can't as you opened it)
Thanks.
