### ISSUE TITLE
[Bug] Can't process torrent snatched

### ISSUE THREAD

**Issue by maxcore** [DobyTang/LazyLibrarian#276]
lazy can't process my last torrent snatched : 
````
2016-01-29 13:33:56	INFO	No snatched books/mags have been found
2016-01-29 13:33:56	DEBUG	Snatched NZB Maxim USA - December 2015 - January 2016 is not in download directory
2016-01-29 13:33:56	DEBUG	Checking [/volume1/Downloads/EBOOK] for files to post process
2016-01-29 13:33:28	INFO	Search for magazines complete
`````
 DEBUG	Snatched NZB ? its not Snatched Torrent ? 
the file is on the good folder  /volume1/Downloads/EBOOK/Maxim USA - December 2015 - January 2016/Maxim USA - December 2015 - January 2016.pdf

**Comment by philborman** [comment]
HaHa, the code could not tell if it was a torrent or an nzb, it can now. Fixed that.
The "not found" problem is not easy to diagnose.
Could you have a look in postprocess.py, line 95
it says 
if fuzz.token_set_ratio(fname, book['NZBtitle']) >= 98

try changing to 95 and see if that fixes it.
If 95 does not fix it, try 90. Do not go any lower than 90 
If that still does not work I will need to think again.

**Comment by maxcore** [comment]
ahhh we have setting for set ratio ?

**Comment by philborman** [comment]
no, it's fixed in the code. 
It is there because of small changes in unicode, for example there is more than one way of coding the minus sign, and you have two of those in that title Maxim USA - December 2015 - January 2016
It could be that the "fuzzy" value of 98% is too high. There are other ways round the problem if this does not work. For example we can remove all except A-Z and 0-9.

**Comment by maxcore** [comment]
@philborman yeah i try now ;)

**Comment by maxcore** [comment]
95,90 nothing working ..

**Comment by maxcore** [comment]
@philborman working now i have delited last snatched and restart and now the postprocessing work for torrent thx

**Comment by philborman** [comment]
Ok thanks for trying
I might change how that section of code works anyway,  I am not too happy
with it
