### ISSUE TITLE
creating copy for calibre auto import

### ISSUE THREAD

**Issue by danfozzy** [DobyTang/LazyLibrarian#277]
The copy that is created for the auto import folder setting for calibre is being created as read only. Calibre is unable to import it until i change the books properties and untick the read only box for the files.

**Comment by philborman** [comment]
It looks like its supposed to copy the permissions and ownership of the source files,  which might not be what we want for calibre as it needs write access to delete the file fom the import folder.
I have never actually used it myself,  but that's how it looks in the code. 

Do you know if the source file (the book in lazylibrarian library)  is read only?
I'm not sure if it is failing to copy the permissions across or whether we need to add a chmod to set the calibre copy of the book to read/write

**Comment by danfozzy** [comment]
right, i think it may have been an issue with the setup.

I hadnt set the base folder as i want bothered about creating a library from LL, i wanted calibre to do it for me as it auto updated my server at the same time. this was producing the book in the import folder with read only permissions.

ive now set a base folder to a folder in my downloads shared folder. Now the import copy created is rw, and will get imported.

if i leave the base dir empty, were is it saving the LL books?

ive just come across another issue now ive got round this one tho..

if LL downloads a book with several formats, it will copy them to the import folder. Unfortunately calibre auto import only works if only 1 item is placed in there. so for it to work, it needs to only send one book, calibre will auto import and convert it to what ever format is required.

**Comment by philborman** [comment]
It looks like if base folder isn't set, it downloads into the "current directory" which is probably where LazyLibrarian is run from. I think we need to put a warning in if base_dir is empty. It might be ok to run that way as long as you know.  It will create directories in your lazylibrarian folder in each authors name.

The "one book only" is a bit tricky to decide what to do about. If we only move one, which one does Calibre prefer, epub, mobi?  Any thoughts?

**Comment by danfozzy** [comment]
epub is prob the most common available, calibre does a very good job at converting, so its not really an issue for me (i use mobi format)

there away to say if theres an epub, send that, if not send whichever?

**Comment by philborman** [comment]
Yes there is. Seems a shame Calibre has to re-convert epub -> mobi if there's already a mobi in the download though. Is there not a setting in calibre to import all formats? I know you can from the front panel [Add books from directories, including sub-directories (One book per directory, assumes every ebook file is the same book in a different format)]

**Comment by danfozzy** [comment]
i think i maybe talking rubbish, hold on lol

**Comment by philborman** [comment]
Is that several books, or several versions of the same book?
I've just looked at how we put stuff in the auto-add directory, and it's got some messages about the names all the same, but doesn't actually convert them??
ie does it need book_title.epub   book_title.jpg   book_title.opf 
or is it ok with  book_title.epub  cover.jpg  metadata.opf

**Comment by philborman** [comment]
Seems this is working as Calibre intends, at least to current version.
@danfozzy can you mark this closed now. Thanks
