### ISSUE TITLE
Issue with RSS SSL?

### ISSUE THREAD

**Issue by dvdgorila** [DobyTang/LazyLibrarian#279]
I'm trying to configure an RSS feed and Im getting the following in the logs

`Error opening url: <urlopen error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>`

and the result comes back as 0

the rss feed does not appear to support http, only https

Anyone using https RSS feeds?

**Comment by philborman** [comment]
I've used it on http://kat.cr/books/?rss=1  and also  https://kat.cr/books/?rss=1   as kat supports both,
and
https://www.usenet-crawler.com/rss?t=7010&dl=1&i=xxxxxx&r=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
which is only https, not http.  Maybe you need to include credentials in the url like usenet-crawler?
