### ISSUE TITLE
Snatched torrents not found in download_dir

### ISSUE THREAD

**Issue by arogl** [DobyTang/LazyLibrarian#282]
I am using the latest release and qbittorrent as a client:

    03-Feb-2016 18:12:19 - DEBUG :: MAIN : (getCommitDifferenceFromGit) -  GitHub reports as follows Status [identical] - Ahead [0] - Behind [0] - Total Commits [0]
    03-Feb-2016 18:12:20 - DEBUG :: MAIN : Start checkForUpdates job
    03-Feb-2016 18:15:25 - DEBUG :: POSTPROCESS :  Checking [F:\EBook_down] for files to post process
    03-Feb-2016 18:15:25 - DEBUG :: POSTPROCESS : Snatched torrent Shannon West - Bloodlust (Dark Hollow Wolf Pack #9) LL.(18282341) is not in download directory
    03-Feb-2016 18:15:25 - DEBUG :: POSTPROCESS : Snatched torrent Alan Campbell - Art of Hunting (The Gravedigger Chronicles #2) LL.(16081149) is not in download directory
    03-Feb-2016 18:15:25 - DEBUG :: POSTPROCESS : Snatched torrent Alexey Pehov - Chasers of the Wind (The Cycle of Wind and Sparks #1) LL.(18490614) is not in download directory
    03-Feb-2016 18:15:25 - INFO :: POSTPROCESS : No snatched books/mags have been found

History screen

    Title	ID	Provider	Date	Size	Status
    Alan Campbell - Art of Hunting (The Gravedigger Chronicles #2) LL.(16081149) 	16081149 	KAT 	2016-02-03 01:41:11 	0.47 MB 	Snatched
    Alexey Pehov - Chasers of the Wind (The Cycle of Wind and Sparks #1) LL.(18490614) 	18490614 	KAT 	2016-02-03 01:47:18 	4.45 MB 	Snatched
    Shannon West - Bloodlust (Dark Hollow Wolf Pack #9) LL.(18282341) 	18282341 	KAT 	2016-02-02 19:44:14 	0.18 MB 	Snatched

Contents of download_dir:

    Directory of F:\EBook_down
    
    02/02/2016  07:44 PM           192,367 Bloodlust - Shannon West.epub
    03/02/2016  01:42 AM    <DIR>          The Art of Hunting by Alan Campbell (The Gravedigger Chronicles #2) - [praful99]
    03/02/2016  01:57 AM    <DIR>          [The Cycle of Wind and Sparks 01] Chasers of the Wind by  Alexey Pehov {dwg}
    
    Directory of F:\EBook_down\The Art of Hunting by Alan Campbell (The Gravedigger Chronicles #2) - [praful99]
    
    03/02/2016  01:42 AM           495,071 The Art of Hunting by Alan Campbell (The Gravedigger Chronicles #2).epub
    
    Directory of F:\EBook_down\[The Cycle of Wind and Sparks 01] Chasers of the Wind by  Alexey Pehov {dwg}
    
    03/02/2016  01:57 AM         1,172,523 Chasers of the Wind - Alexey Pehov.azw3
    03/02/2016  01:57 AM           947,343 Chasers of the Wind - Alexey Pehov.epub
    03/02/2016  01:57 AM           797,717 Chasers of the Wind - Alexey Pehov.mobi
    03/02/2016  01:57 AM         1,653,503 Chasers of the Wind - Alexey Pehov.pdf
    03/02/2016  01:56 AM            91,912 cover.jpg
    03/02/2016  01:54 AM             1,343 metadata.opf

**Comment by philborman** [comment]
Seems we are not talking to qbittorrent quite right, we expect it to download the files into a directory that we are looking for. ie we expect to find 
F:\EBook_down\Alan Campbell - Art of Hunting (The Gravedigger Chronicles #2) LL.(16081149)
but qbittorrent gives us
F:\EBook_down\The Art of Hunting by Alan Campbell (The Gravedigger Chronicles #2) - [praful99]

We look for the "LL.(bookid)"  in the name, and it isn't there. I will have to think about that...

**Comment by arogl** [comment]
This update still did not allow me to pick up the snatched files:

History screen

    Title   ID  Provider    Date    Size    Status
    Alan Campbell - Art of Hunting (The Gravedigger Chronicles #2) LL.(16081149)    16081149    KAT     2016-02-03 01:41:11     0.47 MB     Snatched
    Alexey Pehov - Chasers of the Wind (The Cycle of Wind and Sparks #1) LL.(18490614)  18490614    KAT     2016-02-03 01:47:18     4.45 MB     Snatched
    Shannon West - Bloodlust (Dark Hollow Wolf Pack #9) LL.(18282341)   18282341    KAT     2016-02-02 19:44:14     0.18 MB     Snatched

Debug log file

    04-Feb-2016 18:21:45 - DEBUG :: POSTPROCESS :  Checking [F:\EBook_down] for files to post process
    04-Feb-2016 18:21:45 - DEBUG :: POSTPROCESS : Snatched torrent Shannon West - Bloodlust (Dark Hollow Wolf Pack #9) LL.(18282341) is not in download directory
    04-Feb-2016 18:21:45 - DEBUG :: POSTPROCESS : Snatched torrent Alan Campbell - Art of Hunting (The Gravedigger Chronicles #2) LL.(16081149) is not in download directory
    04-Feb-2016 18:21:45 - DEBUG :: POSTPROCESS : Snatched torrent Alexey Pehov - Chasers of the Wind (The Cycle of Wind and Sparks #1) LL.(18490614) is not in download directory
    04-Feb-2016 18:21:45 - INFO :: POSTPROCESS : No snatched books/mags have been found
    04-Feb-2016 18:21:45 - DEBUG :: POSTPROCESS : Stop processDir job

Also  line 73 of post process needs the space before the word Checking removed.

**Comment by philborman** [comment]
Ok, I have removed the extra space, that's a nice easy fix :-)
The other bit is more tricky, if you don't mind editing, can you add 
this line at 104 in postprocess.py
(just above the "if match >= 95") and force postprocess with debug on. 
Thanks

logger.debug("%i %s" % (match, matchname))

python is very sensitive about whitespace
the 'l' of 'logger' needs to be ditectly over the 'i' of 'if'

The problem is name-matching your torrent download directories to the 
expected book names, might be as simple as reducing the 95% a bit?

**Comment by arogl** [comment]
OK, Managed to get it to fail on a snatched book but it is a combined author and the name of the dir = torrent name,

    05-Feb-2016 17:50:28 - DEBUG :: DBIMPORT : Imported/Updated 34 books for author
    05-Feb-2016 17:50:28 - INFO :: DBIMPORT : [Laura J. Burns] Book processing complete: Added 33 books to the database
    05-Feb-2016 17:50:28 - DEBUG :: DBIMPORT : [Laura J. Burns] Author update complete
    05-Feb-2016 17:50:37 - INFO :: CP Server Thread-5 : Status set to "Wanted" for "Sanctuary Bay"
    05-Feb-2016 17:50:39 - INFO :: SEARCHTORBOOKS : TOR Searching for one book
    05-Feb-2016 17:50:39 - DEBUG :: SEARCHTORBOOKS : [IterateOverTorrentSites] - KAT
    05-Feb-2016 17:50:40 - DEBUG :: SEARCHTORBOOKS : Parsing results from <a href="https://kat.cr/usearch/Laura%20J%20Burns%20Sanctuary%20Bay/?category=books&field=seeders&rss=1&sorder=desc">KAT</a>
    05-Feb-2016 17:50:40 - DEBUG :: SEARCHTORBOOKS : Found 1 results from KAT for Laura J Burns Sanctuary Bay, checking seeders
    05-Feb-2016 17:50:40 - DEBUG :: SEARCHTORBOOKS : Found Laura J. Burns & Melinda Metz - Sanctuary Bay A Novel. Size: 2332000
    05-Feb-2016 17:50:40 - DEBUG :: SEARCHTORBOOKS : Found 1 results from KAT for Laura J Burns Sanctuary Bay
    05-Feb-2016 17:50:40 - DEBUG :: SEARCHTORBOOKS : TOR author/book Match: 100/100 for Laura J Burns Melinda Metz Sanctuary Bay A Novel
    05-Feb-2016 17:50:40 - DEBUG :: SEARCHTORBOOKS : Found Torrent: Laura J. Burns & Melinda Metz - Sanctuary Bay A Novel using book search
    05-Feb-2016 17:50:41 - DEBUG :: SEARCHTORBOOKS : Sending Laura J  Burns - Sanctuary Bay LL.(25663880) to qbittorrent
    05-Feb-2016 17:50:41 - DEBUG :: SEARCHTORBOOKS : addTorrent(https://torcache.net/torrent/41429422764A8E9ED900AEF6B606D7610A0E8393.torrent)
    05-Feb-2016 17:50:41 - DEBUG :: SEARCHTORBOOKS : login cookie: SID, value: Yl8AAHtlAAC3YAAAnDwAAJQdAABpRAAA
    05-Feb-2016 17:50:41 - DEBUG :: SEARCHTORBOOKS : QBittorrent WebAPI Command: command/download
    05-Feb-2016 17:50:41 - DEBUG :: SEARCHTORBOOKS : Torrent file has been downloaded from https://torcache.net/torrent/41429422764A8E9ED900AEF6B606D7610A0E8393.torrent
    05-Feb-2016 17:50:41 - DEBUG :: SEARCHTORBOOKS : Start processDir job, already scheduled
    05-Feb-2016 17:50:41 - INFO :: SEARCHTORBOOKS : TORSearch for Wanted items complete, found 1 book
    05-Feb-2016 17:52:44 - DEBUG :: POSTPROCESS :  Checking [F:\EBook_down] for files to post process
    05-Feb-2016 17:52:44 - DEBUG :: POSTPROCESS : 82 Laura J. Burns & Melinda Metz - Sanctuary Bay A Novel
    05-Feb-2016 17:52:44 - DEBUG :: POSTPROCESS : Snatched torrent Laura J  Burns - Sanctuary Bay LL.(25663880) is not in download directory
    05-Feb-2016 17:52:44 - INFO :: POSTPROCESS : No snatched books/mags have been found
    05-Feb-2016 17:52:44 - DEBUG :: POSTPROCESS : Stop processDir job

Confusing because a new Author and snatch worked:

    05-Feb-2016 17:57:29 - DEBUG :: GR-SEARCH : Now searching GoodReads API with keyword: Charlie Donlea
    05-Feb-2016 17:57:29 - DEBUG :: GR-SEARCH : Searching for Charlie Donlea at: http://www.goodreads.com/search.xml?q=Charlie+Donlea&key=ckvsiSDsuqh7omh74ZZ6Q
    05-Feb-2016 17:57:30 - DEBUG :: GR-SEARCH : CacheHandler: Caching response for http://www.goodreads.com/search.xml?q=Charlie+Donlea&key=ckvsiSDsuqh7omh74ZZ6Q
    05-Feb-2016 17:57:30 - DEBUG :: GR-SEARCH : Found 1 results with keyword: Charlie Donlea
    05-Feb-2016 17:57:30 - DEBUG :: GR-SEARCH : The GoodReads API was hit 0 times for keyword Charlie Donlea
    05-Feb-2016 17:57:37 - DEBUG :: DBIMPORT : Now adding new author: Charlie Donlea to database
    05-Feb-2016 17:57:37 - DEBUG :: DBIMPORT : Searching for author with name: Charlie Donlea
    05-Feb-2016 17:57:38 - DEBUG :: DBIMPORT : CacheHandler: Caching response for http://www.goodreads.com/api/author_url/Charlie%20Donlea?key=ckvsiSDsuqh7omh74ZZ6Q
    05-Feb-2016 17:57:39 - DEBUG :: DBIMPORT : CacheHandler: Caching response for http://www.goodreads.com/author/show/13922088.xml?key=ckvsiSDsuqh7omh74ZZ6Q
    05-Feb-2016 17:57:39 - DEBUG :: DBIMPORT : [Charlie Donlea] Processing info for authorID: 13922088
    05-Feb-2016 17:57:39 - DEBUG :: DBIMPORT : CacheHandler: Caching response for http://www.goodreads.com/author/list/13922088.xml?key=ckvsiSDsuqh7omh74ZZ6Q
    05-Feb-2016 17:57:39 - DEBUG :: DBIMPORT : [Charlie Donlea] Now processing books with GoodReads API
    05-Feb-2016 17:57:39 - DEBUG :: DBIMPORT : url http://www.goodreads.com/author/list/13922088.xml?key=ckvsiSDsuqh7omh74ZZ6Q
    05-Feb-2016 17:57:39 - DEBUG :: DBIMPORT : author name Charlie Donlea
    05-Feb-2016 17:57:39 - DEBUG :: DBIMPORT : Found cached language [eng] for isbn [149]
    05-Feb-2016 17:57:39 - DEBUG :: DBIMPORT : book found Summit Lake 2016
    05-Feb-2016 17:57:39 - DEBUG :: DBIMPORT : [Charlie Donlea] Added book: Summit Lake
    05-Feb-2016 17:57:40 - DEBUG :: DBIMPORT : CacheHandler: Caching response for http://www.goodreads.com/author/list/13922088.xml?key=ckvsiSDsuqh7omh74ZZ6Q&page=2
    05-Feb-2016 17:57:41 - DEBUG :: DBIMPORT : Found 1 total books for author
    05-Feb-2016 17:57:41 - DEBUG :: DBIMPORT : Removed 0 bad language results for author
    05-Feb-2016 17:57:41 - DEBUG :: DBIMPORT : Removed 0 bad character results for author
    05-Feb-2016 17:57:41 - DEBUG :: DBIMPORT : Ignored 0 books by author marked as Ignored
    05-Feb-2016 17:57:41 - DEBUG :: DBIMPORT : Imported/Updated 1 books for author
    05-Feb-2016 17:57:41 - INFO :: DBIMPORT : [Charlie Donlea] Book processing complete: Added 1 books to the database
    05-Feb-2016 17:57:41 - DEBUG :: DBIMPORT : [Charlie Donlea] Author update complete
    05-Feb-2016 17:57:57 - INFO :: CP Server Thread-4 : Status set to "Wanted" for "Summit Lake"
    05-Feb-2016 17:57:59 - INFO :: SEARCHTORBOOKS : TOR Searching for one book
    05-Feb-2016 17:57:59 - DEBUG :: SEARCHTORBOOKS : [IterateOverTorrentSites] - KAT
    05-Feb-2016 17:58:00 - DEBUG :: SEARCHTORBOOKS : Parsing results from <a href="https://kat.cr/usearch/Charlie%20Donlea%20Summit%20Lake/?category=books&field=seeders&rss=1&sorder=desc">KAT</a>
    05-Feb-2016 17:58:00 - DEBUG :: SEARCHTORBOOKS : Found 1 results from KAT for Charlie Donlea Summit Lake, checking seeders
    05-Feb-2016 17:58:00 - DEBUG :: SEARCHTORBOOKS : Found Charlie Donlea - Summit Lake. Size: 1384197
    05-Feb-2016 17:58:00 - DEBUG :: SEARCHTORBOOKS : Found 1 results from KAT for Charlie Donlea Summit Lake
    05-Feb-2016 17:58:00 - DEBUG :: SEARCHTORBOOKS : TOR author/book Match: 100/100 for Charlie Donlea Summit Lake
    05-Feb-2016 17:58:00 - DEBUG :: SEARCHTORBOOKS : Found Torrent: Charlie Donlea - Summit Lake using book search
    05-Feb-2016 17:58:01 - DEBUG :: SEARCHTORBOOKS : Sending Charlie Donlea - Summit Lake LL.(25489185) to qbittorrent
    05-Feb-2016 17:58:01 - DEBUG :: SEARCHTORBOOKS : addTorrent(https://torcache.net/torrent/DC0D8C0E9069CF0E35EF939B7A38BEA731EEB1DC.torrent)
    05-Feb-2016 17:58:01 - DEBUG :: SEARCHTORBOOKS : login cookie: SID, value: /2QAAE4PAADCUAAAbksAAMBdAAB6IQAA
    05-Feb-2016 17:58:01 - DEBUG :: SEARCHTORBOOKS : QBittorrent WebAPI Command: command/download
    05-Feb-2016 17:58:01 - DEBUG :: SEARCHTORBOOKS : Torrent file has been downloaded from https://torcache.net/torrent/DC0D8C0E9069CF0E35EF939B7A38BEA731EEB1DC.torrent
    05-Feb-2016 17:58:01 - DEBUG :: SEARCHTORBOOKS : Start processDir job, already scheduled
    05-Feb-2016 17:58:01 - INFO :: SEARCHTORBOOKS : TORSearch for Wanted items complete, found 1 book
    05-Feb-2016 17:59:21 - DEBUG :: POSTPROCESS :  Checking [F:\EBook_down] for files to post process
    05-Feb-2016 17:59:21 - DEBUG :: POSTPROCESS : 28 Charlie Donlea - Summit Lake
    05-Feb-2016 17:59:21 - DEBUG :: POSTPROCESS : 82 Laura J. Burns & Melinda Metz - Sanctuary Bay A Novel
    05-Feb-2016 17:59:21 - DEBUG :: POSTPROCESS : Snatched torrent Laura J  Burns - Sanctuary Bay LL.(25663880) is not in download directory
    05-Feb-2016 17:59:21 - DEBUG :: POSTPROCESS : 100 Charlie Donlea - Summit Lake
    05-Feb-2016 17:59:21 - DEBUG :: POSTPROCESS : Found folder F:\EBook_down\Charlie Donlea - Summit Lake for Charlie Donlea - Summit Lake LL.(25489185)
    05-Feb-2016 17:59:21 - DEBUG :: POSTPROCESS : F:\EBook_Library\Charlie Donlea\Summit Lake does not exist, so it's safe to create it
    05-Feb-2016 17:59:21 - DEBUG :: POSTPROCESS : Copying cover.jpg to directory F:\EBook_Library\Charlie Donlea\Summit Lake
    05-Feb-2016 17:59:21 - DEBUG :: POSTPROCESS : Copying metadata.opf to directory F:\EBook_Library\Charlie Donlea\Summit Lake
    05-Feb-2016 17:59:21 - DEBUG :: POSTPROCESS : Copying Summit Lake - Charlie Donlea.epub to directory F:\EBook_Library\Charlie Donlea\Summit Lake
    05-Feb-2016 17:59:21 - DEBUG :: POSTPROCESS : Processing Summit Lake - Charlie Donlea, https://torcache.net/torrent/DC0D8C0E9069CF0E35EF939B7A38BEA731EEB1DC.torrent?title=[kat.cr]charlie.donlea.summit.lake
    05-Feb-2016 17:59:21 - DEBUG :: POSTPROCESS : AutoAdd - Attempt to copy from [F:\EBook_Library\Charlie Donlea\Summit Lake] to [E:\unarc\e-Books\import]
    05-Feb-2016 17:59:21 - DEBUG :: POSTPROCESS : AutoAdd Copying file [Summit Lake - Charlie Donlea.epub] as copy [F:\EBook_Library\Charlie Donlea\Summit Lake\Summit Lake - Charlie Donlea.epub] to [E:\unarc\e-Books\import\Summit Lake - Charlie Donlea.epub]
    05-Feb-2016 17:59:21 - DEBUG :: POSTPROCESS : AutoAdd Copying file [Summit Lake - Charlie Donlea.jpg] as copy [F:\EBook_Library\Charlie Donlea\Summit Lake\Summit Lake - Charlie Donlea.jpg] to [E:\unarc\e-Books\import\Summit Lake - Charlie Donlea.jpg]
    05-Feb-2016 17:59:21 - DEBUG :: POSTPROCESS : AutoAdd Copying file [Summit Lake - Charlie Donlea.opf] as copy [F:\EBook_Library\Charlie Donlea\Summit Lake\Summit Lake - Charlie Donlea.opf] to [E:\unarc\e-Books\import\Summit Lake - Charlie Donlea.opf]
    05-Feb-2016 17:59:21 - INFO :: POSTPROCESS : Auto Add completed for [E:\unarc\e-Books\import\Summit Lake - Charlie Donlea.opf]
    05-Feb-2016 17:59:21 - DEBUG :: POSTPROCESS : Downloading cover from http://d.gr-assets.com/books/1443109083m/25489185.jpg
    05-Feb-2016 17:59:22 - DEBUG :: POSTPROCESS : F:\EBook_Library\Charlie Donlea\Summit Lake\Summit Lake - Charlie Donlea.opf allready exists. Did not create one.
    05-Feb-2016 17:59:22 - INFO :: POSTPROCESS : Successfully processed: Summit Lake - Charlie Donlea
    05-Feb-2016 17:59:22 - INFO :: POSTPROCESS : 1 books/mags have been processed.
    05-Feb-2016 17:59:22 - DEBUG :: POSTPROCESS : Stop processDir job

**Comment by philborman** [comment]
Yes it's the extra author name that's pulling the score down to 82%
If you change the 95 to 82 it will work for now. 
With usenet feeds we know the download directory name.  With torrents the name is fixed and we try to match it using author and title.  If we make the match % too low we can get false matches. 
Needs a rethink...

**Comment by philborman** [comment]
Just looking at your logs again - very useful.
We know exactly what the torrent file will be called, it's in the "Found Torrent" line in the log. Why are we mucking about trying to do name matching, we can just look for the name we sent to qbittorrent. Unless I'm missing something of course. Maybe we should look for that first, and then try to name-match as a second attempt.

Will rustle something up later today and try it out.

**Comment by philborman** [comment]
Hmm, well that didn't work either. Transmission  sometimes uses a directory name that isn't the one we asked for, or the title of the torrent, so we still have to name-match. Will probably have to check the names we expect first, then name match if it fails.  More work needed.
