### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by nncrypted** [DobyTang/LazyLibrarian#284]
Can someone please post a screen shot of what the Folder section should look like I've mucked up my config and now all books are being dumped into the root of the author but not in folders. 
Thank you

**Comment by philborman** [comment]
Default is  $Author/$Title  for ebook destination folder
$Title - $Author  for ebook destination file
Screenshot attached....
For any setting, if you stop lazylibrarian, delete the whole setting from your config.ini, then restart, the default value gets written to config.ini next time.
![screenshot from 2016-02-03 17-18-04](https://cloud.githubusercontent.com/assets/12158777/12788661/ad4417c8-ca9a-11e5-9ef7-7e65945ae92c.png)

**Comment by nncrypted** [comment]
Thank you. Now how do I go about getting that nice looking theme/skin you have there.

**Comment by philborman** [comment]
its work in progress.
Have a look at https://github.com/warlord0/lazylibrarian.bookstrap

Magazines don't quite work yet, cover sizing needs sorting out, and 
config doesn't work at the moment as it needs qbittorrent adding in. 
Author is quite active so probably won't be long getting it finished.

Works much better on small screens than the default theme too.

**Comment by nncrypted** [comment]
That looks sweet. If stupid work wasn't getting in my way I'd play with this a bit more but gotta work to pay the bills.
