### ISSUE TITLE
[Questions] cover

### ISSUE THREAD

**Issue by maxcore** [DobyTang/LazyLibrarian#288]
I dont know why but this name : "PC GAMER USA" the lazy or convert dont create the cover. 

````
2016-02-06 09:29:11	INFO	Successfully processed: 2016-03-01 - PC GAMER USA
2016-02-06 09:29:10	DEBUG	Creating cover for /volume2/EBOOK/_Magazines/PC GAMER USA/2016-03-01/2016-03-01 - PC GAMER USA.pdf using /usr/syno/bin/gsconvert.py
2016-02-06 09:29:10	DEBUG	Issue PC GAMER USA 2016-03-01 Hash: 29828a154ee3169b1d026c49e813ea2664642c65
`````
No cover on the folder

**Comment by philborman** [comment]
Can you try running gsconvert from the command line and see if you get any output.
 /usr/syno/bin/gsconvert.py /volume2/EBOOK/_Magazines/PC GAMER USA/2016-03-01/2016-03-01 - PC GAMER USA.pdf  test.jpg
Might get an error message tellingus why?
I had another user with the same problem (different magazine) but could not reproduce it here.

**Comment by maxcore** [comment]
i think the command is gs ?

````
NAS-MAXCORE> gs /volume2/EBOOK/_Magazines/PC GAMER USA/2016-03-01/2016-03-01 - P
C GAMER USA.pdf test.jpg                        
GPL Ghostscript  9.00 (2010-09-14)
Copyright (C) 2010 Artifex Software, Inc.  All rights reserved.
This software comes with NO WARRANTY: see the file PUBLIC for details.
Error: /undefinedfilename in (/volume2/EBOOK/_Magazines/PC)
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push
Dictionary stack:
   --dict:1148/1684(ro)(G)--   --dict:0/20(G)--   --dict:77/200(L)--
Current allocation mode is local
Last OS error: 2
GPL Ghostscript  9.00: Unrecoverable error, exit code 1
````

**Comment by danfozzy** [comment]
Are you using a synology? What did you put in the settings to create the covers?

**Comment by philborman** [comment]
Hmm, seems gs cannot read that partiicular pdf file. Nothing we can do about it.

Any chance you can email me a copy of the pdf file so I can try it here?

**Comment by maxcore** [comment]
![capture d ecran 2016-02-07 11 32 35](https://cloud.githubusercontent.com/assets/4043787/12873565/95f127fe-cd8e-11e5-9918-297b0391d1c4.png)

**Comment by maxcore** [comment]
the mag here : https://www.dropbox.com/s/flpdfovupvdjqit/2016-03-01%20-%20PC%20GAMER%20USA.pdf?dl=0

**Comment by philborman** [comment]
Thanks for the link to the mag. 
I'm using
GPL Ghostscript 9.16 (2015-03-30)
and it works here, produces a cover. So I guess it's a different ghostscript version?

**Comment by maxcore** [comment]
i just you the .py i think i will install the real script ...

````
#!/usr/bin/python

import sys
import subprocess

GS = "/usr/bin/gs"

if len(sys.argv) != 3:
    print "Usage: gsconvert input.pdf output.jpg"
else:
    try:
        jpeg = sys.argv[2]
        pdf = sys.argv[1]
        if '[' in pdf:
            pdf = pdf.split('[')[0]
            
        params = [GS, "-sDEVICE=jpeg", "-dNOPAUSE", "-dBATCH", "-dSAFER", "-dFirstPage=1", "-dLastPage=1",
                  "-sOutputFile=" + jpeg, pdf ]
        subprocess.check_output(params, stderr=subprocess.STDOUT)
        #print params
        
    except subprocess.CalledProcessError as e:
        print("Failed: %s" % e)

`````

**Comment by maxcore** [comment]
NAS-MAXCORE> gs -version
GPL Ghostscript  9.00 (2010-09-14)
Copyright (C) 2010 Artifex Software, Inc.  All rights reserved.

**Comment by danfozzy** [comment]
I've installed imagemagick from the synocommunity repo, I've pointed the convert program to the imagemagick directory  (/volume1/@appstore/imagemagick/bin/) but can't get it to create covers, any idea?

**Comment by danfozzy** [comment]
I've even installed it via Ipkg but I'm having no luck, what exactly an idea supposed to put in the convert program box?

**Comment by philborman** [comment]
Because we had problems with imagemagick versions on synology i wrote a
script that called ghostscript instead.  If you have a full imagemagick
installation on Linux / mac / windows it's automatic and just works (tm)

Some synology users have reported it works if you put
/user/syno/bin/convert  in the box.

If that fails,  there is a python script in the lazylibrarian folder you
can try called gsconvert.py  so if your lazylibrarian folder is
/opt/LazyLibrarian  you would put /opt/LazyLibrarian/gsconvert.py  in the
box.  This isn't perfect either as it depends on the version of ghostscript
that's installed,  9.1.x is ok,  earlier ones fail on some PDF files but it
mostly works

**Comment by maxcore** [comment]
@philborman yes i am back with the convert 
````
2016-02-09 16:47:35	DEBUG	Unable to create cover for /volume2/EBOOK/_Magazines/MacLife/2016-03-01/2016-03-01 - MacLife.pdf using convert
2016-02-09 16:47:25	DEBUG	Creating cover for /volume2/EBOOK/_Magazines/MacLife/2016-03-01/2016-03-01 - MacLife.pdf using /usr/syno/bin/convert
````

you can add more debug log for find why convert fail  one in three times  ?

**Comment by philborman** [comment]
I think the problem is the version of ghostscript on the synology. I 
think you need version 9.1
What's the latest version you can get?

If you use this as your script it will show the output from ghostscript, 
9.1 reported an error in the magazine file, not following pdf standards, 
and then said it had applied a work-around. Maybe the synology version 
of ghostscript doesn't include the work-around???

**Comment by maxcore** [comment]
I search how update this with the last version on my synology ...

**Comment by maxcore** [comment]
https://www.archlinux.org/packages/extra/i686/imagemagick/

?

**Comment by philborman** [comment]
I think its ghostscript you need to update, but I don't know what 
operating system is on the synology. If it runs on archlinux you could try

https://www.archlinux.org/packages/extra/i686/ghostscript/

Otherwise you could compile ghostscript from source ?
https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs918/ghostscript-9.18.tar.gz

**Comment by maxcore** [comment]
Ok i will try tonight

**Comment by philborman** [comment]
If you have a c compiler on your synology (hopefully)

download the source from here
https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs918/ghostscript-9.18.tar.gz

tar -xvf ghostscript-9.18.tar.gz
cd ghostscript-9.18
./configure
make
./bin/gs --version

**Comment by maxcore** [comment]
Thx for line !

**Comment by maxcore** [comment]
````
> ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... ./configure: line 1714: grep: command not found
gcc -E
./configure: line 1714: grep: command not found
checking for a sed that does not truncate output... /opt/bin/sed
checking for ranlib... ranlib
checking for pkg-config... /opt/bin/pkg-config
checking supported compiler flags... 
   -O2
   -Wall
./configure: line 1677: grep: command not found
   -Wstrict-prototypes
   -Wundef
   -Wmissing-declarations
   -Wmissing-prototypes
   -Wwrite-strings
   -Wno-strict-aliasing
   -Werror=declaration-after-statement
   -fno-builtin
   -fno-common
   -Werror=return-type

   -gdwarf-2
   -g3
   -O0
 ...done.
checking for big endian... little
checking sse2 support... ./configure: line 1794: grep: command not found
no
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for grep that handles long lines and -e... configure: error: no acceptable grep could be found in /opt/bin:/opt/sbin:/bin/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin:/var/packages/JavaManager/target/Java/bin:/var/packages/JavaManager/target/Java/jre/bin:/usr/xpg4/bin
`````
``````
> make
make: *** No targets specified and no makefile found.  Stop.
> 
````
....

**Comment by philborman** [comment]
So you do not have grep installed.
If you have ipkg you can install it from there
ipkg install grep

**Comment by maxcore** [comment]
> make
base/unixlink.mak:107: warning: overriding recipe for target `bin/'
base/unixlink.mak:83: warning: ignoring old recipe for target `bin/'
base/unixlink.mak:130: warning: overriding recipe for target `bin/'
base/unixlink.mak:107: warning: ignoring old recipe for target `bin/'
gcc -O2 -Wall -Wstrict-prototypes -Wundef -Wmissing-declarations -Wmissing-prototypes -Wwrite-strings -Wno-strict-aliasing -Werror=declaration-after-statement -fno-builtin -fno-common -Werror=return-type -DHAVE_STDINT_H=1 -DHAVE_DIRENT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_SYS_TIMES_H=1 -DHAVE_INTTYPES_H=1 -DGX_COLOR_INDEX_TYPE="unsigned long long" -D__USE_UNIX98=1 -DGS_MEMPTR_ALIGNMENT=8     -I./base -o ./obj/aux/genconf ./base/genconf.c  -lm  -lidn -rdynamic -ldl -L/opt/lib -lfontconfig    
/opt/lib/gcc/i686-linux-gnu/4.2.1/../../../../i686-linux-gnu/lib/libdl.so: undefined reference to `_dl_open@GLIBC_PRIVATE'
/opt/lib/gcc/i686-linux-gnu/4.2.1/../../../../i686-linux-gnu/lib/libdl.so: undefined reference to `_dl_close@GLIBC_PRIVATE'
collect2: ld returned 1 exit status
make: *** [obj/aux/genconf] Error 1

**Comment by philborman** [comment]
Your version of libdl is old, or maybe we are picking up an old one and 
there is a newer one elsewhere on the system?

A quick google search shows there are lots of people with problems 
compiling different programs on synology. The default libdl seems to be 
an old version, can you search your synology for  versions of libdl
on linux as root you would do this...

find // -name "libdl*"

//lib32/libdl.so.2
//lib32/libdl-2.21.so
//usr/lib/debug/lib/x86_64-linux-gnu/libdl-2.21.so
//usr/lib/x86_64-linux-gnu/libdl.a
//usr/lib/x86_64-linux-gnu/libdl.so
//usr/lib/libreoffice/program/libdlgprovlo.so
//lib/i386-linux-gnu/libdl.so.2
//lib/i386-linux-gnu/libdl-2.21.so
//lib/x86_64-linux-gnu/libdl.so.2
//lib/x86_64-linux-gnu/libdl-2.21.so

as you see, all mine are 2.21, you might have a mix.

**Comment by maxcore** [comment]
> find // -name "libdl*"
//lib/libdl.so.2
//lib/samba/libdlz_bind9_for_torture.so
//lib64/libdl.so.2

**Comment by philborman** [comment]
No version numbers, that doesn't help us much.

**Comment by philborman** [comment]
There should be others too, your first message found one in
/opt/lib/gcc/i686-linux-gnu/4.2.1/../../../../i686-linux-gnu/lib/libdl.so

**Comment by maxcore** [comment]
i search how update the libdl ... a real pain this box

**Comment by philborman** [comment]
It's part of libc-dev, not sure what version you have installed. Try this...

ipkg upgrade libc-dev

**Comment by maxcore** [comment]
> ipkg upgrade libc-dev
Nothing to be done
Successfully terminated.

**Comment by philborman** [comment]
any luck finding more copies of libdl  on your synology?

**Comment by philborman** [comment]
for i in lib* opt usr ; do find /$i -name 'libdl*'; done

**Comment by maxcore** [comment]
````> find /$i -name 'libdl*';
/lib/libdl.so.2
/lib/samba/libdlz_bind9_for_torture.so
/lib64/libdl.so.2
/volume1/@optware/i686-linux-gnu/lib/libdl-2.3.6.so
/volume1/@optware/i686-linux-gnu/lib/libdl.so
/volume1/@optware/i686-linux-gnu/lib/libdl.so.2
/opt/i686-linux-gnu/lib/libdl-2.3.6.so
/opt/i686-linux-gnu/lib/libdl.so
/opt/i686-linux-gnu/lib/libdl.so.2
````

**Comment by philborman** [comment]
ok, so there appear to be four versions of libdl on your system.
/lib/libdl.so.2
/lib64/libdl.so.2
/volume1/@optware/i686-linux-gnu/lib/libdl-2.3.6.so
/opt/i686-linux-gnu/lib/libdl-2.3.6.so

do any of the have the label it complained was missing, dlopen?

strings /lib/libdl.so.2 | grep open
strings /lib64/libdl.so.2 | grep open

and so on...

**Comment by maxcore** [comment]
`````
> strings /lib/libdl.so.2 | grep open
dlopen
dlmopen

`````

`````
> strings /lib64/libdl.so.2 | grep open
dlopen
dlmopen
```

**Comment by philborman** [comment]
strings /volume1/@optware/i686-linux-gnu/lib/libdl-2.3.6.so | grep open
strings /opt/i686-linux-gnu/lib/libdl-2.3.6.so | grep open

**Comment by maxcore** [comment]
`````
> strings /volume1/@optware/i686-linux-gnu/lib/libdl-2.3.6.so | grep open
_dl_open
dlopen
dlmopen
````
`````
> strings /opt/i686-linux-gnu/lib/libdl-2.3.6.so | grep open
_dl_open
dlopen
dlmopen

````

**Comment by philborman** [comment]
so the first two libraries (/lib/libdl.so.2 and /lib64/libdl.so.2) do 
not have _dl_open
but the next two do have it.

I think you need to make gcc use a different version of the library but 
I am not sure how to force it to do that. I would try this first...

mv /volume1/@optware/i686-linux-gnu/lib/libdl-2.3.6.so  /tmp/lib1
mv /opt/i686-linux-gnu/lib/libdl-2.3.6.so /tmp/lib2

then try ./configure, make as before
hopefully it will then use  /lib/libdl.so.2  or  /lib64/libdl.so.2
that don't have _dl_open in them

If it does not work, put the libraries back
mv /tmp/lib1 /volume1/@optware/i686-linux-gnu/lib/libdl-2.3.6.so
mv /tmp/lib2 /opt/i686-linux-gnu/lib/libdl-2.3.6.so

**Comment by maxcore** [comment]
hum @philborman you can give me your email address i will give you acces to the box am very newbies with linux ... ?

**Comment by philborman** [comment]
phil.borman@gmail.com

**Comment by maxcore** [comment]
@philborman i need to fix the routeur for outgoing connection ..

**Comment by maxcore** [comment]
@philborman check your mail

**Comment by maxcore** [comment]
`````
2016-02-15 12:51:26	INFO	Successfully processed: 2016-02-01 - Home Cinema Choice
2016-02-15 12:51:26	WARNING	/usr/syno/bin/convert reports: convert: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/706.
2016-02-15 12:51:21	DEBUG	Creating cover for /volume2/EBOOK/_Magazines/Home Cinema Choice/2016-02-01/2016-02-01 - Home Cinema Choice.pdf using /usr/syno/bin/convert
````

**Comment by danfozzy** [comment]
Would love to know what you've done to sort this. Think all syno users will be the same

**Comment by philborman** [comment]
We are not quite there yet. The version of ghostscript shipped with some (maybe all) synology doesn't do pdf conversion, the version in ipkg is not current and only does some pdfs, and there are different  versions of libdl on the system which makes compiling your own ghostscript tricky.

Once it's sorted we can publish details on how to get it working.

**Comment by philborman** [comment]
Unless you have replaced the old ghostscript, /usr/syno/bin/convert will 
still use the old version.
It does not know about the new one, which has a different name.

Is it ok if I log in again?

**Comment by maxcore** [comment]
I use the same line ?

**Comment by maxcore** [comment]
@philborman 
i got this error now
````
2016-02-16 14:27:36	WARNING	/usr/syno/bin/gsconvert.py reports: Failed: Command '['/usr/local/bin/gs', '-sDEVICE=jpeg', '-dNOPAUSE', '-dBATCH', '-dSAFER', '-dFirstPage=1', '-dLastPage=1', '-sOutputFile=/volume2/EBOOK/_Magazines/Play/2014-03-01/2014-03-01 - Play.jpg', '/volume2/EBOOK/_Magazines/Play/2014-03-01/2014-03-01 - Play.pdf']' returned non-zero exit status -11
2016-02-16 14:27:33	DEBUG	Creating cover for /volume2/EBOOK/_Magazines/Play/2014-03-01/2014-03-01 - Play.pdf using /usr/syno/bin/gsconvert.py

````

**Comment by philborman** [comment]
I think we are picking up the wrong ghostscript again, ?
I thought it should be /opt/bin/gs

Is it ok if I log in again and have another look

**Comment by maxcore** [comment]
````
2016-02-16 15:21:25	DEBUG	Unable to create cover for /volume2/EBOOK/_Magazines/Play/2013-09-01/2013-09-01 - Play.pdf using convert
2016-02-16 15:21:25	DEBUG	Creating cover for /volume2/EBOOK/_Magazines/Play/2013-09-01/2013-09-01 - Play.pdf using /opt/bin/gs
````

**Comment by philborman** [comment]
I just tried it from the command line

 > gs -sDEVICE=jpeg -dNOPAUSE -dBATCH -dSAFER -dFirstPage=1 -dLastPage=1 
-sOutput
File=test.jpg "/volume2/EBOOK/_Magazines/Play/2013-09-01/2013-09-01 - 
Play.pdf"
GPL Ghostscript 9.18 (2015-10-05)
Copyright (C) 2015 Artifex Software, Inc.  All rights reserved.
This software comes with NO WARRANTY: see the file PUBLIC for details.
Processing pages 1 through 1.
Page 1

and it created a jpeg file test.jpg

Very strange why convert isn't working.
Can you check that your config is using program /opt/syno/bin/gsconvert.py
Can you check if the cover is there, it could be the error is not real?

**Comment by maxcore** [comment]
@philborman 

this /usr/local/bin/gs WORKING NOW!

we need to do a tuto for all synology user

@danfozzy

**Comment by maxcore** [comment]
@philborman 
All work good now with /usr/syno/bin/convert

i scan the library and now all work good !

i just strange fact look the screen : 
![capture d ecran 2016-02-16 21 24 55](https://cloud.githubusercontent.com/assets/4043787/13097958/c8cbe242-d4f3-11e5-946f-3b9ffd897a1f.png)

this cover in black in white . I try to redownload 3 time and same way and the real pdf the front have color .

**Comment by philborman** [comment]
Good news that it is working

Can you try gsconvert.py and see if that works in colour

**Comment by maxcore** [comment]
I dont find anymore  the gsconvert.py ...

**Comment by philborman** [comment]
it should be in the same directory as LazyLibrarian

Here is a copy...

**Comment by maxcore** [comment]
Ok i find the file but the same for this cover (only the pc gamer) ! 

What you do for make a small tuto for synology user , we need upgrade the bootstrap ? The convert work well too with the 9.18 version

The problem was fix at 99%

**Comment by philborman** [comment]
Still something strange with that issue of PC Gamer.
I downloaded this one
PC Gamer USA TruePDF-March 2016 
<https://www.oznzb.com/details/6b89dedec3348067fcfcf1198b3f69ae/PC.Gamer.USA.TruePDF-March.2016>
from oznzb  and it converted fine, colour image
but this one
PC Gamer USA March 2016 
<https://www.oznzb.com/details/6b89dedec3348067fcfcf1198b3f69ae/PC.Gamer.USA.TruePDF-March.2016>
is black-and-white

The tutorial is quite simple, I will put something in the wiki later.

This assumes your LazyLibrarian installation is in /opt/LazyLibrarian/
If not, you will need to adjust the path in step 2

1. ssh into your NAS

2. Switch to your LazyLibrarian installation directory
     cd /opt/LazyLibrarian

3. Download  a new version of GhostScript from here
     wget 
https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs918/ghostscript-9.18-linux-x86_64.tgz

4. Unpack the archive
     tar -xvf ghostscript-9.18-linux-x86_64.tgz

5. Move the new ghostscript into the LazyLibrarian directory and change 
the name to gs
     mv ghostscript-9.18-linux-x86_64/gs-918-linux_x86_64  gs

6. Delete the unwanted files
     rm -rf ghostscript-9.18-linux-x86_64*

7. Put /opt/LazyLibrarian/gsconvert.py in the config setting for 
"Conversion Program"

That way we don't disturb any of the other software on Synology that 
might want a different version of gs, we use our own private copy.

**Comment by maxcore** [comment]
Phill you are machine thx ! 

So the truepdf its better ?

**Comment by danfozzy** [comment]
Thanks!! working a treat! is there any way to make LL to process the mags i already have rather than just the new ones?

**Comment by danfozzy** [comment]
after following the instructions, im getting alot of warnings:

/volume1/@appstore/LazyLibrarian/gsconvert.py reports: Using gs [/volume1/@appstore/LazyLibrarian/gs] version 9.18

**Comment by philborman** [comment]
Yes, just go to the "magazines" page and hit the "Library Scan" button

**Comment by philborman** [comment]
Yes, ignore it, It's just reporting where it found ghostscript and what 
version it's using.
It should be a debug message rather than a warning. I have moved it to 
debug in the next release.
9.18 is the current version so all is well.

**Comment by danfozzy** [comment]
brilliant, thanks!

**Comment by philborman** [comment]
@maxcore As this is now working, can you mark it as closed. Thanks

**Comment by maxcore** [comment]
Thx for this phill!
