### ISSUE TITLE
No grabs - Error on personal nZEDb

### ISSUE THREAD

**Issue by PREngineer** [DobyTang/LazyLibrarian#289]
Hi, I just discovered your repo today and gave it a try since I don't have anything for books.

I however, can't seem to be able to grab books that I know exist in my Indexer, another additional Indexer that I use and torrents.

It even gives an error with nZEDb.  Is it compatible with nZEDb?

Please look at the Log result.

![screen shot 2016-02-07 at 1 33 43 am](https://cloud.githubusercontent.com/assets/6334069/12871209/2dfbc75a-cd3c-11e5-951e-b1ccb99e21e8.png)

**Comment by philborman** [comment]
No idea on nZEDb, never used it. If it's easy to configure I could have a try...
Known working indexers are usenet-crawler.com, nzbplanet.net, oznzb.com, nzbgeek.com
The only torrent feed I have used directly is kat.cr, or I use  torrents via torznab and rss feeds 
If it's failing on multiple indexers it may be a config issue. Any more info if you turn debug logging on?

**Comment by PREngineer** [comment]
That's the weird thing... nZEDb is a fork of NewzNab, so the API is the same.  I'm using nzbgeek and I can't pull anything from there either.  I'll post the debug log in a sec.

**Comment by nncrypted** [comment]
Nzedb should work fine as I'm using my private newznab plus I'm using nzb hydra and all work well.

**Comment by PREngineer** [comment]
It decided to work today with another book and grabbed it from nzbgeek.  :/

However, I find it strange that it doesn't work with nZEDb, being the same API as NewzNab.  Look at the lines that I got with nZEDb in the very beginning [NewzNab 0] when I turned debug log on.

http://pastebin.com/6znvb8Q8

I guess the API doesn't take "books" as a parameter.  I tried to get the capabilities of the API and this is what it shows:

http://pastebin.com/18PDu0Fe

It seems to me that nZEDb uses the number code for the request instead of the word "book".

**Comment by PREngineer** [comment]
https://github.com/nZEDb/nZEDb  <--- nZEDb is free, based on NN+ and with improvements to grab more releases.

**Comment by philborman** [comment]
The number codes are different, that may be the problem.
newznabplus uses t=book, cat=7020 for ebooks, nzedb is using 8010 and 
doesn't seem to mention "t=" as a parameter. Might be able to work 
around it, I'll have a think.

**Comment by PREngineer** [comment]
It does use the "t="

Here's the API Requests page for reference.

http://pastebin.com/CQYnYhXT

**Comment by philborman** [comment]
Someone else had the same problem here...
http://forums.nzedb.com/index.php?topic=1741.0

If you don't mind a bit of light editing, in providers.py
lines 299 and 312 change   "t": "book"   to   "t": "books"

and lines 303 and 316  change "cat": 7020  to  "cat": 8010

and try nzedb again. Bear in mind this will break other newznab sources 
for now, but will test if that's all we need to change for nzedb.  If it 
works I will add extra searches with these parameters. Not sure yet how 
we'll tell which sites need which.  I would try it myself but don't have 
nzedb set up :-)

**Comment by PREngineer** [comment]
No problem!  Give me a min (I'm eating right now) and I will test it.  :)

**Comment by philborman** [comment]
Just found this also...
Torznab is a wordplay on Torrent and Newznab. It uses the same structure and syntax as the Newznab API specification, but exposing torrent-specific attributes and .torrent files. Thus supports a recent rss feed AND backlog searching capabilities. The specification is not maintained and supported by the Newznab organization. (The same api specification is shared with nZEDb)

so if you move the nzedb host and api from the usenet column in config into the torznab column it just might magically start to work.  Torznab uses 8010 but still general search, not books.

**Comment by PREngineer** [comment]
Ok, I applied the changes to providers.py but nothing changed.  I guess because there's another file that is providers.py (compiled) and it stays the same...

**Comment by PREngineer** [comment]
Putting nZEDb in the Torznab was even worse, the link was not even put correctly in the search.

http://pastebin.com/dgsSD5hB

**Comment by philborman** [comment]
looks like your torznab url and api need swapping over in the config??
not sure why altering providers.py hasn't helped. providers.pyc gets rebuilt next time you run the program so should not be an issue. I might have to try setting up a nzedb server here.

**Comment by PREngineer** [comment]
Sorry, I noticed and edited the previous comment instead of putting a new one.  It did find a match but the NZB never got sent to Sab.

If you want I can add you to my Indexer for you to test for a while.  My Database got corrupted, so I'm re-indexing.  It will slowly add more entries.  But there are a few books in there... like 200 pages.

Please let me know so that I can add you and please provide me with an e-mail to send you the information.  I'm not sure if you can PM in GitHub.

**Comment by philborman** [comment]
You can email me at phil.borman@gmail.com I'm away until Wednesday though so won't be updating much. Was it easy to set up a nzedb server, I had a brief look at setting up a  newznab server but the regex provided weren't indexing much so i gave up and stayed with my paid providers.

**Comment by PREngineer** [comment]
I will e-mail you the information so that you can use it.  I will leave the account working for a bit.

nZEDb is actually quite easy to install.  Just follow the Repo's instructions or join the nZEDb forum if you have problems.  The issue is that indexing takes a while and consumes a lot of data.  You can easily go over 4TB of data used in a month if you enable certain features like screenshot creation, and media info.

nZEDb's Regexes are much better than NN+ so you get more results and if you use the PreDB, even more.

**Comment by philborman** [comment]
@PREngineer If this is now working correctly (I think it is) can you mark the issue as closed. Thanks.

**Comment by PREngineer** [comment]
I'm sorry... I have been busy and I didn't get to test it before.

It seems to be working.  The results are a little weird because it gets books that are not even related but it filters through them and grabs it if it finds it.

So I will close this ticket.

Thank you.
