### ISSUE TITLE
Configuration instructions

### ISSUE THREAD

**Issue by Theli93** [DobyTang/LazyLibrarian#294]
We could really use some configuration instructions/explanations in the Wiki. Many of the configuration fields are ambiguous enough to leave one attempting to understand what is going on via trail and error (if they're patient enough to bother); particularly for newbs like myself. If there is some good instruction on the web, then a link would be helpful as a majority of information I find is for installation only and/or horribly outdated due to being for the previous fork. Even the sabnzbd forums are about the previous fork.

**Comment by philborman** [comment]
Yes the program has been dormant for quite a while.  We could do with some good documentation especially for the new additions,  and once the features are stable I will have a go at putting something together.  If anyone else wants to step in and do it they are more than welcome.  Documentation isn't really my field. 

Mind you,  python wasn't a few months ago either :-)

**Comment by philborman** [comment]
I have added basic config instructions to the wiki. Needs more work, but any areas that aren't clear, ask and I'll try to explain it better. Some areas are blank as I don't know how they work myself.

**Comment by maxcore** [comment]
@philborman  Great job for the wiki !

**Comment by philborman** [comment]
Can this be closed now?

**Comment by thejrose1984** [comment]
Not sure how relevant this is, but no matter how I configure LL, my books wind up all other place. Even though I specifically state to organize them in directories.

**Comment by philborman** [comment]
I would guess LL can't find your directory, maybe it's a config issue. 
Can you post your debug log and config.ini

**Comment by thejrose1984** [comment]
config.ini = http://pastebin.com/zAv1Ng7y

debug log enabled a few minutes ago, so I'll need to let it run for a little bit in order to give more information before submitting

**Comment by philborman** [comment]
Only books in epub format is tricky as lots of torrents/nzb don't say.  What we do at the moment is download best name match and blacklist any that don't give us an epub,  then next search retries a different download. 

Calibre integration is ok,  but calibre library folder names have a number assigned to them which calibre generates.  Full integration with that is tricky and not ideal as lazylibrarian gives calibre a second copy of the book.  Can be integrated better,  but it's quite a large amount of work.  Might look into it at some point.

**Comment by coleberhorst** [comment]
Added a pull request to the README to outline a very basic config using uTorrent.

**Comment by coleberhorst** [comment]
I think this issue should be closed. Probably lost the OP and the issue seems resolved by wiki and readme changes.
