### ISSUE TITLE
Create release for packaging?

### ISSUE THREAD

**Issue by fryfrog** [DobyTang/LazyLibrarian#296]
Hi,

I just created an AUR lazylibrarian-git "package" and think it would be really great to create a non-git version that was based on releases. Any chance you could pick a point you consider stable and worthy of a "release" in the past (or future) and create a release?

**Comment by philborman** [comment]
Just looking into how to do this. Seems the package managers for debian and snap need a setup.py and a structure ( bin/ doc/ lib/ ) defined by lsb which we don't have. 

First thing to create would probably be a "snap" package which should work on all linux variants, as the snap carries its own version of python (so we don't need to worry about migrating to python3)
and lazylibrarian carries all the libraries it needs in the git structure.
This might save having to create and maintain several formats,  deb, rpm, aur, tgz, 
 
Did you work round the directory structures for the AUR package, if so, how?

There are package converters (alien, debtap) that can convert between packaging formats which might be another way forward, once we've created the first one.

**Comment by philborman** [comment]
Ok I have working deb and rpm packages now,  can't get snap to work though.  Do you have a script to produce your aur package and would you be willing to share it?  I am trying to get a website up where we can distribute prebuilt packages

**Comment by fryfrog** [comment]
https://aur.archlinux.org/packages/lazylibrarian-git/

But what I'm looking for is really just a release tag, w/ the accompanying .tar.gz and .zip files. That way I could create a version package to go along w/ the git package.

**Comment by fryfrog** [comment]
Thanks for making a release, I've created a new AUR package for lazylibrarian.

https://aur.archlinux.org/packages/lazylibrarian/

**Comment by philborman** [comment]
is it ok if I put a link to that in the lazylibrarian README?

Not sure if it's relevant for AUR packages, if you don't want the internal update mechanism just edit the version.py file. I know rpm package managers don't like you messing with files they think they own, not sure if AUR minds, but set the version.py variable to "package" and the update check will tell you to use your package manager to update. 

Also just a heads-up, I will be pushing a new release in the next couple of days. Quite a few changes.
