### ISSUE TITLE
Any Chance of Fantastic Fiction Book Search

### ISSUE THREAD

**Issue by JaBaine** [DobyTang/LazyLibrarian#299]
I happen to use Fantastic Fiction plugin instead of GoodReads when updating metadata in calibre. They just seem to have less repeats/incorrect/useless title/author data available.

Any chance of adding [http://www.fantasticfiction.co.uk/](url) to the Book search options?

**Comment by philborman** [comment]
Looks like they are using Amazon books as their source. I looked at Amazon as an addition to google/goodreads but it seemed quite complicated to implement and didn't give us all the info we wanted without jumping through hoops. 

Do you know if FantasticFiction have an api we can use, (didn't see it mentioned on their website) or are you grabbing the info manually?

**Comment by JaBaine** [comment]
I use the plugin from within calibre which ends up being automatic. 

you can find the plugin code here though
[http://www.mobileread.com/forums/showthread.php?t=132908](url)

I just thought it might be worth a look. no worries

**Comment by philborman** [comment]
I just had a look at the plugin. It gives us clues to most of what we need, but I can't figure out how to get details on a book from the bookID (yet), only from the book title. We can query the database to get a list of bookIDs for a given author, and much of our code uses the bookID as it's guaranteed unique, whereas the title isn't, but as yet I can't see how to look up a book from it's bookID.

I might try contacting the plugin author for info. Probably can't contact FantasticFiction as they might not appreciate us using their database to avoid buying books from them :-)

One other problem I found, it only has details on 40% of the authors in my library. The rest don't seem to be in their database at all, including some quite common authors.
