### ISSUE TITLE
Download Directory not found?

### ISSUE THREAD

**Issue by partymike** [DobyTang/LazyLibrarian#317]
I can see the following error logged:
WARNING	Download dir not found, books will be downloaded to c:\python27

It was set to a local drive eg H:\LazyLibrarian

I then tried a few other combinations eg //nas/media/lazylibrarian (to a NAS), but still see the same error.

Running on windows and even though items are snatched nothing ever ends up in the specified directory (remains in the torrent download folder)....am I missing something?

**Comment by philborman** [comment]
Next version has extra debugging messages to try and track this down. 
We try to check the entry in the config for download_dir is a valid directory and complain if it doesn't seem to be one.

**Comment by philborman** [comment]
Any update on this, or should I close it?
