### ISSUE TITLE
[NewzNabPlus] - nzb No matching search parameters

### ISSUE THREAD

**Issue by osuhickeys** [DobyTang/LazyLibrarian#318]
Does not appear to work with dognzb.  Using sames setting as I use in Couchpotato, Sonnar, and Headphones which are all working.  Can search via the browser and find the books on dognzb, but LazyLibrarian seems to be unable to find them.

**Comment by philborman** [comment]
Anything useful in the debug log?

**Comment by osuhickeys** [comment]
Nothing that jumped out at me.  I do not have another provider I can test.  Not sure if it is the site or NewzNab providers in general.

2016-03-17 20:24:01	DEBUG	[NewzNabPlus] - nzb No matching search parameters
2016-03-17 20:24:00	DEBUG	[NewzNabPlus] searchType [general] with Host [https://api.dognzb.cr] mode [nzb] using api [apikey] for item [{'searchterm': 'BookAuthor BookTitle', 'bookName': u'BookTitle', 'authorName': u'AuthorName', 'bookid': u'32422'}]
2016-03-17 20:24:00	DEBUG	[IterateOverNewzNabSites] - https://api.dognzb.cr
2016-03-17 20:24:00	DEBUG	Using stored capabilities for https://api.dognzb.cr
2016-03-17 20:24:00	DEBUG	No nzb's found for BookAuthor BookTitle using searchtype book
2016-03-17 20:24:00	DEBUG	[NewzNabPlus] - nzb No matching search parameters
2016-03-17 20:24:00	DEBUG	[NewzNabPlus] searchType [book] with Host [https://api.dognzb.cr] mode [nzb] using api [apikey] for item [{'searchterm': 'BookAuthor BookTitle', 'bookName': u'BookTitle', 'authorName': u''BookAuthor', 'bookid': u'32422'}]
2016-03-17 20:24:00	DEBUG	[IterateOverNewzNabSites] - https://api.dognzb.cr
2016-03-17 20:24:00	DEBUG	Using stored capabilities for https://api.dognzb.cr
2016-03-17 20:24:00	INFO	NZB Searching for one book
2016-03-17 20:24:00	DEBUG	Searching for book with id: 32422

**Comment by cybercorey** [comment]
Hi there, did you resolve this I believe I have a simular issues.
First book I tried worked after that none worked including the first book I retried.

**Comment by philborman** [comment]
The "no matching search parameters found" means we asked dognzb for its capabilities but couldn't find any of the ones that we use.  Either it doesn't report them,  or reports them in a way we don't understand.  You can override the detected parameters in the tab in config. 

Would be interesting to see what (if anything) the autodetect picked up from dognzb. 

You need to detect and fill in at least one of "search"  and "booksearch",  and at least one category number for books and magazines or that message gets printed when you search.

**Comment by osuhickeys** [comment]
Yes, I did have to go in and tick that box and remove those settings to get
rid of error incorrect parameter in the debug log.  The error did not go
away until I blanked every field except category if I remember correctly
which I left as 7000.  That is the correct parameter for dognzb.  I blanked
them out one at a time.  Could not figure out what the other fields should
be set to.  I do not think that tab was in the documentation.
Auto-discovery did fill out 3 more fields. Extended search was set to 1 I
believe.  I do not remember which other 2 were filled out and what they
were set to.

I cannot seem to get the auto-discovery to work by removing the provider,
saving, restarting, and re-adding.  Guessing even though I removed the
provider, it is somehow remembering it was added at one time and
auto-discovery was run.  Auto-discovery must only be able to be run once
for a provider???

Is it me or is the clear log function also not working?  Looks like it is
trying to delete the file to clear it based on the error message and cannot
because it is currently open.

Failed to clear log: The process cannot access the file because it is being
used by another process

On Fri, Mar 18, 2016 at 3:07 AM, philborman <notifications@github.com>
wrote:

> The "no matching search parameters found" means we asked dognzb for its
> capabilities but couldn't find any of the ones that we use. Either it
> doesn't report them, or reports them in a way we don't understand. You can
> override the detected parameters in the tab in config.
>
> Would be interesting to see what (if anything) the autodetect picked up
> from dognzb.
>
> You need to detect and fill in at least one of "search" and "booksearch",
> and at least one category number for books and magazines or that message
> gets printed when you search.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/DobyTang/LazyLibrarian/issues/318#issuecomment-198245453>
>



-- 
*Mark E. Hickey*
*1906 Lunenburg Dr.*
*St. Peters, MO 63376*
*636-344-0706*

**Comment by osuhickeys** [comment]
Clear log works immediately after you restart the services.  Guessing the file has not been opened yet so it is able to delete it?

I added dognzb as a second provider and disabled the original one I added.  Extended search = 1. General search = search.  Book categories =  7000,7020.  Book search = book.  Mag cat = 7010.  When I do a search now I get the 3 errors below several times in a row:

ERROR	https://api.dognzb.cr - Incorrect parameter
ERROR	Unable to connect to SAB with URL: http://192.168.1.103:8080/books/api?nzbname=.....
ERROR	Failed to download nzb @ https://api.dognzb.cr

**Comment by philborman** [comment]
Yeah,  it's not documented yet as it's a new feature and changed a few
times just before I went on holiday.

The settings are stored in the database and only refreshed periodically.  I
don't think we have an easy way to tell if a provider has been removed to
force a rescan.  I will have a think about how to add something.

The search settings should be "search"  in the general search box,
(without the quotes) and "book" in the book search box.  Magazine search
blank. Looks like dognzb uses 7000,7020 for books and 7010 for magazines.
I need to look into why the autodetect didn't get this but I'm away until
mid week.  Manually setting the values should get you going for now.

**Comment by philborman** [comment]
Sorry,  working from memory,  might be "books"  rather than "book" or might be that dognzb doesn't have a specific book search in which case leave the booksearch blank and we don't try to use it.  The category numbers are right for dognzb as it tells us that.  We can't tell about book search though as dognzb doesn't say so we have to guess,  and blank the booksearch field if there isn't one. Leave the categories in though,  we can use them in a general search.

**Comment by philborman** [comment]
Actually my memory isn't working as well as i would like.  The settings are not stored in the database,  they used to be.  They are in the config file now,  so much easier to force a rescan.

Each providers config entry includes the search parameters and a datestamp.  If you wipe the datestamp it will force a rescan next time you search.  I will look at it when i get back.

**Comment by osuhickeys** [comment]
I get "ERROR https://api.dognzb.cr - Incorrect parameter" with either book or books in the book search field.  If I blank it out, I do not get that, but still get "[NewzNabPlus] - nzb No matching search parameters".  I am not able to put search in the general search filed and get it to save.  It disappears once I click save.

I saw the time stamp in the ini file originally and tried wiping it and setitng manual to false thinking it would re-scan, but it did not.

Safe travels and thanks for your help!

**Comment by osuhickeys** [comment]
I also noticed that making changes directly in the ini file are not reflected in the GUI.  I can remove book from the ini file, but it still show in the GUI after a refresh and restart.  That may be why blanking the timestamp from the ini file is not forcing a rescan.  Something being cached perhaps?

**Comment by philborman** [comment]
The program keeps the ini file in memory while running and writes it out
again on save or exit so if you want to hand edit the ini file,  stop the
program first.

**Comment by cybercorey** [comment]
Awesome, Managed to fix it buy resetting to default settings (copied from backed up ini file) then restarting the server!

Cheers all

**Comment by osuhickeys** [comment]
Just realized I accidentally closed it yesterday.

**Comment by osuhickeys** [comment]
Just realized I accidentally closed it yesterday.

**Comment by philborman** [comment]
New version now clears the log file even if in use.
Now also clears the detected parameters if you change provider host name.
(reloads parameters when you next search for a book)
I think the other remaining issues here are due to changing the config file outside the program while its still running. Just a bit more testing here before I upload it.
