### ISSUE TITLE
API

### ISSUE THREAD

**Issue by cybercorey** [DobyTang/LazyLibrarian#319]
Any chance that you'll bring back the application API, I plan to build a HTPCManager module for this, but have no api to play with =(

**Comment by philborman** [comment]
Hmm, would be a useful addition, didn't know there used to be one.
What would you need?

**Comment by cybercorey** [comment]
Just occured to me the API may have been ripped out long before you took over the project! (or was from a really old fork of headphones that didnt have an API)

I was planning to pretty much do everything via API though HTPCManager.

**Comment by philborman** [comment]
ok, added a basic api to this version. Try host:port/api?apikey=xxx&cmd=help
hopefully it's fairly self-explanatory, if not let me know. 
I think you can do most of what you need through the api, no way of altering config values yet, needs a bit more thought. Any missing functions you think could be useful let me know.
I will try to get some documentation in the wiki over the next few days.

**Comment by cybercorey** [comment]
Awesome cheers!
Can I assume this will be very similar to headphones API?
Looks like I'ma build that module for htpcmanager after all !!

**Comment by cybercorey** [comment]
Awesome cheers, just looked through the code looks like everything I need!

Thanks again

**Comment by cybercorey** [comment]
Hey dude,

Is it possible to get an api request for getting all books?

Cheers

**Comment by cybercorey** [comment]
Another Question, using the addAuthor function, seems to be erroring.
I've tried supplying both the name of the author & the id from goodreads.

**Comment by philborman** [comment]
Parameters need to be passed as urllib.quote_plus so...
addAuthor&name=Tom+Holt

Added new api function getAllBooks to list all books in the database
getAuthor&id= will get author details plus all their books in one call.

To add a book, mark it as wanted by calling queueBook&id=
then call forceBookSearch or wait for the next time the search jobs run
Book and author need to be in the database to do this. If the book isn't in the database you can add it by calling findBook to get the author name, then addAuthor to get it into the database

We don't have a forceSingleBookSearch , I will look into adding it.

**Comment by cybercorey** [comment]
Legend! 
I'll keep on working on this and let you know if I need more!

Thanks a tonn

**Comment by philborman** [comment]
Added searchBook&id=   to search for a single book
Also a few extra api functions, and added an optional &wait to functions that take a long time to run.
If you add &wait the api call will wait for completion before returning. 
Default is to return 'OK' immediately and run the function in a separate thread.
