### ISSUE TITLE
Cover logic?

### ISSUE THREAD

**Issue by knobunc** [DobyTang/LazyLibrarian#320]
(Using the GoodReads API)

I added "Agatha Christie" and after the import many of the books have no cover even when GoodReads has the cover.  e.g. "Murder on the Orient Express" (http://www.goodreads.com/book/show/16304.Murder_on_the_Orient_Express)

What's the logic for how the cover is grabbed?  Is it using a different image than the one shown on the main goodreads page?  Is there a way to refresh a cover?

**Comment by philborman** [comment]
We ask goodreads api for a list of books by Agatha Christie. 
Goodreads gives us back some xml, several books at a time, containing the book title, publication date, cover image, language, isbn, number of pages, description etc.
Quite often not all the fields are in the xml, and sometimes the cover given is just a link to http://www.goodreads.com/assets/nocover/111x148.png even when goodreads has a proper cover on the book page. There is currently no way to manually change the cover, but it might be worth looking into how we can grab one.

**Comment by philborman** [comment]
Added code in the next release to grab a thumbnail from google advanced image search if we don't get a cover (or get a 1x1 gif) from goodreads. Should get it uploaded to git tonight or tomorrow.
Just hit "refresh active authors" button to grab the covers, or use the api cmd=getBookCovers.

It's not too smart, just accepts the first image google gives us. Might look into allowing user to choose from a selection like calibre does?

**Comment by philborman** [comment]
Added two new cover sources, and also extra source for book series info.
Now tries librarything, then searches goodreads, then searches google images as a last resort.
Just update lazylibrarian and run "refresh active authors"

If this works as expected, can you mark the issue as closed. Thanks.
