### ISSUE TITLE
ERROR	(getCurrentVersion) & WARNING (getCommitDifferenceFromGit)

### ISSUE THREAD

**Issue by osuhickeys** [DobyTang/LazyLibrarian#325]
Getting the following 2 errors in the log.  Web page also says, "Running a local updated version.  Piush changes to Github or rollback to master release.  Tried a fresh install, started the app, and get the messages right away.  When I run the local githiub app and select the repo it shows no local changes.  When I do a sync nothing new seesm to be pulled down.

ERROR	(getCurrentVersion) Couldn't find latest git installed version.

WARNING	(getCommitDifferenceFromGit) - Could not get commits behind from github. Can happen if you have a local commit not pushed to repo

**Comment by philborman** [comment]
The error message is trying to use git to determine what version of lazylibrarian you are running.
The actual command is git rev-parse HEAD
Not sure how that fails. Can you try that from the command line and see what output you get? 
Can you also try running lazylibrarian again with debug on, it will show debug messages from the git commands.
The warning message is generated because we can't tell what the local version is.

If all else fails, save your config file and delete the whole lazylibrarian directory (which contains hidden files) and git clone into a new directory.

**Comment by osuhickeys** [comment]
Running from the command line returns 54a5fcf8211fd270f50906ac8d16a03b80570edb.

Config page shows this in the lower left hand corner:
Branch: None Current Version: GIT Cannot establish version : Latest Version: 54a5fcf8211fd270f50906ac8d16a03b80570edb

Here si the log file with debug on:
2016-03-24 15:01:44	ERROR	(getCurrentVersion) Couldn't find latest git installed version.
2016-03-24 15:01:44	DEBUG	(RunGit)Unable to find git with command git rev-parse HEAD
2016-03-24 15:01:44	DEBUG	(RunGit)Git output: ['git' is not recognized as an internal or external command, operable program or batch file. ]
2016-03-24 15:01:44	DEBUG	(RunGit)Trying to execute: "git rev-parse HEAD" with shell in C:\Users\mark\Documents\GitHub\LazyLibrarian
2016-03-24 15:01:44	DEBUG	(getInstallType) [GIT] install detected. Setting Branch to [None]
2016-03-24 15:01:44	DEBUG	(getCurrentGitBranch) Current local branch of repo is [None]
2016-03-24 15:01:44	DEBUG	(RunGit)Unable to find git with command git rev-parse --abbrev-ref HEAD
2016-03-24 15:01:44	DEBUG	(RunGit)Git output: ['git' is not recognized as an internal or external command, operable program or batch file. ]
2016-03-24 15:01:43	DEBUG	(RunGit)Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in C:\Users\mark\Documents\GitHub\LazyLibrarian
2016-03-24 15:01:31	INFO	Debug log display ON, loglevel is 2
2016-03-24 07:46:58	INFO	Nothing marked as snatched. Stopping postprocessor job.
2016-03-24 07:36:56	INFO	Starting LazyLibrarian on port: 5299
2016-03-24 07:36:56	INFO	[VersionCheck] - You are running an unknown version of lazylibrarian. Run the updater to identify your version
2016-03-24 07:36:56	WARNING	(getCommitDifferenceFromGit) - Could not get commits behind from github. Can happen if you have a local commit not pushed to repo
2016-03-24 07:36:55	INFO	[VersionCheck] - Comparing currently installed version with latest github version
2016-03-24 07:36:54	ERROR	(getCurrentVersion) Couldn't find latest git installed version.

**Comment by osuhickeys** [comment]
I also tried to rename the folder, remove the repor from Githib desktop, re-downloaded using the githib stub from the web page and having Github desktop open it rather than doing the clone form the command line.  Same results.  Gitbuh Desktop called the folder LazyLibrarian whihc is what I called it when I did the initial install from the command line.  Not sure if you were looking for a differnet folder name for the root of LazyLibrarian or not?

**Comment by philborman** [comment]
Looks like lazylibrarian can't find the git program, though running it from the command line works and returns the correct result. No idea why. 
Are you running Linux? What is the output from "which git"

**Comment by philborman** [comment]
Looks like lazylibrarian can't find the git program,  though running it from the command line works and returns the correct result. Not sure how this is supposed to work on windows as i run on linux.

**Comment by osuhickeys** [comment]
I added the directory below to my path and it is working now.  I am gonna guess that path will change with each github desktop app upgrade.  

C:\Users\Bob\AppData\Local\GitHub\PortableGit_cf76fc1621ac41ad4fe86c420ab5ff403f1808b9\cmd

Couple thoughts on options....
1.  Update documentation to state Win users must add Githug desktop folder to their path
2.  Add section in config to tell LazyLibrarian where to find Github.  NewzNab does this for a handful of programs it needs that are external to it if I remember correctly.

Anyway, it is working now.  Thanks for the help.

Also, the error log is still not clearing.  I think you piushed a fix for that already if I remember correctly.  It no longer throws an error saying it cannot clear.  Says its cleared, but it really does not.  My most recent 3 entries after trying to clear it.  Not big deal, but just wanted to let you know.

2016-03-24 16:52:59	INFO	Log cleared, level set to [2]- Log Directory is []
2016-03-24 16:50:14	DEBUG	(getCommitDifferenceFromGit) - exiting with commit value of [0]
2016-03-24 16:50:14	INFO	[VersionCheck] - lazylibrarian is up to date

**Comment by speedyflipper** [comment]
How did you solve this? I'm having the same problem running on Windows 7

**Comment by osuhickeys** [comment]
The githib update issue was initially resolved by adding the path to the github exe to my path statement.  Since then though, the path as I had feared, has changed and updating the path did not resolve it.  Resetting githib for this app did not work either.  The only thing that works is re-downloading it about once a week to get the new updates and reentering your settings.  

Even after I got it successfully downloading, a third of the downloads were not in English and another third were audio books even though I had English selected and audio books deselected.  Not sure if it is an issue with the provider not marking the releases correctly (or at all), the app, or a bit of both, but 33% success rate on downloads is too low for me to stick with the app at this time.  Love the concept.  Hope it continues to evolve.

**Comment by philborman** [comment]
A couple of separate issues here. The github section is based on some old headphones code. The newer headphones version has a config option to allow you to specify the location of git. I've just added this to lazylibrarian, though it won't help if git keeps moving with new versions of github. 
I will push the fix for that tonight, but I don't have a working windows machine to try any of this on, so would appreciate feedback, particuarly debug logs if it still fails.

The problem with non-english and audiobooks is probably the torrents and/or nzb files not being marked correctly. Again debug logs would help. The search routines are fairly complex, and without knowing why it thinks a particular file matches or doesn't match it's hard to work out how to improve the search routines

**Comment by philborman** [comment]
osuhickeys was using the portable version of git, which doesn't put the exe file into the users path. Hopefully the workaround of a config option will fix it. 
If you download the standard version of git for windows from https://git-scm.com/download/win  
then git gets installed to C:\Program Files\Git\cmd\git.exe which is in the path and works out of the box.

**Comment by perezbalen** [comment]
I'm recently getting this one on OS X 
A popup constantly nags: "Running a local updated version. Push changes to GITHub or rollback to Master release"

**Comment by philborman** [comment]
It either thinks a file on your lazylibrarian is newer than the git
version, or can't contact git to get current details. A debug log might
show which.
Config page has latest and current versions on the bottom.

**Comment by perezbalen** [comment]
I get:
9f9fea1e46d94814dfc82678ae9e8d4fcc81f12c : Latest Version: Not_Available_From_GitHUB

But thr interesting thing is that this happens only when I log using an iPad.

**Comment by philborman** [comment]
Yes that is interesting. Shouldn't matter what device the client is, the server should still be able to talk to github. I will add some more debugging messages and see if we can track this down. I don't have an ipad, but it works with android tablets & phones so can't see why it wouldn't with an ipad. The only code that knows what client it's talking to is the web server, so it sends the right html layout.
