### ISSUE TITLE
js errors from nav.js

### ISSUE THREAD

**Issue by knobunc** [DobyTang/LazyLibrarian#326]
nav.js errors because the box variable is not defined. The box variable is not defined because the navbar doesn't have IDs on the items.

This is a cleaner way to do it:

```javascript
$(document).ready(function() {
    // get document url
    var docURL = document.URL;
	
    // reset class of nav links
    $("#navbardiv a").removeClass("navactive");

    // pull our page
    var page = location.pathname.substring( location.pathname.lastIndexOf("/") + 1 );

    // add active class
    $("#navbardiv a:not(.navbarlogo)[href=\""+page+"\"]").addClass("navactive");
});
```
But... since the navbar is made of images, they are hard to style.  Would it make sense to flip the navbar back to use styled text?  And then the active button can be highlighted?

Otherwise, if you don't want to do that, just pull nav.js from the site...

**Comment by philborman** [comment]
Many thanks for that, have replaced nav.js with your code into the next release.
js is way out of my comfort zone. I think this was inherited from Headphones way back.

**Comment by knobunc** [comment]
The problem is still that the sections are images.  It would be easier if they were just styled text.  Would you be opposed to changing that if I provide the css?  Then we can have the sections work correctly with highlights by fiddling with the style.

**Comment by philborman** [comment]
Yes, no problem. Happy for any input :-)

I can't see what you would need to do to use styled text in the html,
The images are referenced in base.html and I tried changing that to text 
but it didn't look good.
Could you also modify the html to use styled text?

Kind regards,
Phil

**Comment by knobunc** [comment]
Yeah, if I get time to mess with it, it will change the css and the html and lose the images.

**Comment by philborman** [comment]
That would be great thanks, html/css is something I've not really played 
with
