### ISSUE TITLE
REQUEST: Can we have a better import process pretty please?

### ISSUE THREAD

**Issue by sukhysall** [DobyTang/LazyLibrarian#329]
So my setup is I got LL running on a Synology NAS. Now for every book LL grabs for my listed authors, it creates a copy of that book file in a "temp_books" folder. Now I have Calibre running on my PC and from time to time I'll load it up and it will grab everything from the U:\ drive which is my mapped "temp_books" folder. 

And when I look in Calibre at the books imported I'm disheartened by the sad fact that the metadata is seriously out of whack sometimes. A book title is the authorname and the author is the book title is one I use as an example. So Calibre becomes the tool I use to correct the meta data for a LOT of the books I grab (I grab via nzb).

So I decided to try something; I decided to delete the books on my NAS and re-import the Calibre metacleaned ebooks back into LL so that LL could get the books via the import method and that way if anyone browsed to LL from their machine, they could download an epub safe in the knowledge that the metadata was correct (if they cared enough)

The question/request from me is: Is it possible to evolve the import process so you don't have to import 1 ebook at a time? I was hoping to have a folder I could stick say a bunch of ebooks into and press "import books" and be like "WOAH!!!!!!" (I assume that's how my cousins across the pond spell it :)

So gentlemen & gentleladies......what do you think?

**Comment by philborman** [comment]
Yeah, that's what libraryscan does. Ideal for a calibre library, that's what I use myself.
In config/search&processing tab, put base destination folder as your calibre library
eg /media/NAS/Calibre Library/
then on the authors page, hit "Library Scan"
LL will scan the whole directory structure and import all the authors and books it finds in one go.
We've got a lot better at metadata scanning now, and will use metadata from calibre in preference to embedded (which is often wrong or incomplete as you have noticed)

A few tweaks you might want...
1. If your books are not staying in the Calibre Library, or if you are importing directly from your "temp_books" folder make sure "Full scan" is not ticked, so LL will not remove database entries for any books that have been moved 
2. If your calibre library has (say) lord_of_the_rings.epub  and lord_of_the_rings.mobi in the same directory, tick the "One book per directory" box and LL will not try to scan both copies. Saves time.

btw, I'm not "across the pond" (unless you are :-) more like "across the channel and head south"

Regards,
Phil

**Comment by sukhysall** [comment]
@philborman forgive me I'm slightly confused here. My Calibre library is on my PC and not my NAS. The way I've been using LL was for LL to have a whole list of authors and naturally pull the books down. A copy of each book was sent to a NAS folder (temp_books) which was mapped to my PC (as "U:\"). Every time I ran Calibre it would look at the "U:\" drive which was my mapped "temp_books" folder and then pull the books down and process each one into a designated books folder on my PC.

I assume from your instructions that your Calibre library is hosted on your NAS? I've never had luck with putting my Calibre library on my NAS and certainly not for lack of trying. If you got it working, please do share :)

I will try the instructions above though and let you know how I progress.

Thanks

**Comment by philborman** [comment]
Mine isn't a true NAS it's a networked raspberry pi with a hard disk but
used as a NAS among other things.

You might find the improved metadata processing means you don't have to use
calibre to change it manually,  but if not,
could you process the books with calibre on the pc to tidy the metadata,
then get LL to process them from the shared pc folder?

**Comment by sukhysall** [comment]
@philborman. Sorted.  Thanks. Works the way I want which is brilliant.
