### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by nncrypted** [DobyTang/LazyLibrarian#330]
I'll be away from April 3 to April 10 with limited to possibly no internet access.

**Comment by philborman** [comment]
ok thanks, just submitted changes up to date. I've nothing else major to work on for now so I'll have a break too :-)

**Comment by philborman** [comment]
Welcome back, hope you had a nice break :-)
I think we can close 
#338 (improved http/https parsing)
#335 (expected behaviour)
#332 (fixed)
#326 (knobunc supplied fix)
#325 (fixed)
#320 (new feature added)
#319 (new feature added)
