### ISSUE TITLE
Cant get mine to update via web interface?

### ISSUE THREAD

**Issue by ruinit** [DobyTang/LazyLibrarian#334]
First of all man thank for starting this up again :)
I cloned the one from from philborman commit 3ab57a9dafff9d4250ef14a7af439062d822cf5e
But when I start is says I am behind 78 commits and when I click update it says updating but bever does?

**Comment by ruinit** [comment]
nvm I cloned this git and it's up to date

**Comment by philborman** [comment]
Yes the philborman one is just for testing really,  and has different version numbers which confuses git.

**Comment by ruinit** [comment]
it is working much better thanks for updating!

**Comment by philborman** [comment]
That's great. Can you mark this issue as closed now please?
