### ISSUE TITLE
Magazines seem to automatically start snatching after you add a magazine?

### ISSUE THREAD

**Issue by ruinit** [DobyTang/LazyLibrarian#335]
Added Popular mechanics to the magazine section and it started snatching stuff all by it's self? I don't know if that is rss or a glitch?

**Comment by philborman** [comment]
Neither, it's intentional.
When you add a new magazine it tries to find and download any new issues for you.

**Comment by ruinit** [comment]
oh ok then we need a filter maybe? I am getting popular mechanics south Africa etc automatically downloaded that I obviously don't want :)

**Comment by philborman** [comment]
Yes, there is a filter. In the config page import options tab, Reject List.
add south or africa in there and those issues will be rejected
