### ISSUE TITLE
NZBGet Errno 11001 getaddrinfo failed

### ISSUE THREAD

**Issue by stoofz** [DobyTang/LazyLibrarian#338]
Having a connection with LL and NZBGet issue. LL works fine with SAB though.

2016-04-11 09:46:39	ERROR	Failed to download nzb @ https://nzbsitehere
2016-04-11 09:46:39	ERROR	Please check your NZBget host and port (if it is running). NZBget is not responding to this combination: [Errno 11001] getaddrinfo failed
2016-04-11 09:46:35	DEBUG	Requesting URL via GET method: https://nzbsite/getnzb/454235423blahblahblah623623623.nzb&i=12blahblahblah342314231&r=api4842384blahblahblah
2016-04-11 09:46:35	DEBUG	Found NZB: Bookname - Authorname using author search

![capture](https://cloud.githubusercontent.com/assets/16441523/14429251/aa691066-ffca-11e5-80c8-b5d2c119a191.PNG)

I've tried putting in a username / password but no luck either. 

Indexers are all working, can push to SAB fine. NZBGet works fine with Headphones / Mylar as well.

**Comment by philborman** [comment]
I've had a quick look at the code and it looks like it does need a username and password.
Also the host doesn't need http://
I've got it working here using 127.0.0.1

**Comment by stoofz** [comment]
Awesome! I took out the http:// used only localhost with a username / pw. It's all good now thanks!

**Comment by philborman** [comment]
I've no experience with nzbget - do you know if it's valid to call it 
without a user/pass
if so I can modify the code to allow that. Currently always tries 
http://user:pass@host:port/xmlrpc

**Comment by stoofz** [comment]
I'm not sure what the call sends when NZBGet is set with a blank user/pass. But the default settings have the credentials as nzbget/tegbzn6789

**Comment by hctancredi** [comment]
I had the same issue,  using "localhost" and taking off "http://" were enough to put me back to business.
thanks!

**Comment by philborman** [comment]
The http bit shouldn't matter now on the latest release,  and localhost or
numeric id is ok.  Still need user/pass as i think nzbget wont work without
them.
