### ISSUE TITLE
Inport Magazines

### ISSUE THREAD

**Issue by BenBeyond** [DobyTang/LazyLibrarian#341]
I have been trying to get LazyLibrarian setup as a magazine download system, but I have been having some difficulties and have some questions:
There is a manual import button for books, but not for magazines.  I have tried combinations of forcing magazine library scans and forcing post-processing, but LL does not seem to catch on or like what I am doing.  
An Example: If I use the command line (ubuntu) to copy the PDFs into the correctly named folders and rename them to the correct file name, and force a library scan, LL will correctly acknowledge that there are issues there, but will not update the issue buttons to allow me to open the issues. (see image)
![image](https://cloud.githubusercontent.com/assets/5505883/14641741/bc021c68-0615-11e6-9490-308a7d4c1bff.png)

Also, when forcing post-processing, it will not recognize correctly named issues for magazines in the download folder, but seems to only look for issues that it has previously snatched.  

Lastly, I was wondering if LL can handle magazines that release more often than monthly?  Such as Entertainment Weekly or other magazines that release twice a month or weekly.

Thanks for any help you can provide.

**Comment by philborman** [comment]
I think there may be a naming issue stopping the library scan working as expected. Can you try running with debug logging on to see what's going on?
The default tree structure for magazines should look like this...

/home/phil/Test_Library/_Magazines/The Magpi/
├── 2015-11-01
│   ├── 2015-11-01 - The Magpi.jpg
│   └── 2015-11-01 - The Magpi.pdf
├── 2015-12-01
│   ├── 2015-12-01 - The Magpi.jpg
│   └── 2015-12-01 - The Magpi.pdf
├── 2016-01-01
│   ├── 2016-01-01 - The Magpi.jpg
│   └── 2016-01-01 - The Magpi.pdf
└── 2016-02-01
    ├── 2016-02-01 - The Magpi.jpg
    └── 2016-02-01 - The Magpi.pdf

The "library scan" button on the magazine page will then correctly scan and import these for you. 
Post-processing does only import magazines it snatched, this is expected behaviour.
LL will (hopefully) correctly handle weekly mags providing the magazine includes a full date in the title. 
To add a new magazine, just put the title in the search box on the magazine page, not the top right black box, the white one below it, and hit the "+magazine" button. LL will then add the magazine to the database and try to download the last few issues

**Comment by philborman** [comment]
Just tried Entertainment Weekly, correctly grabbed and processed the last 4 issues, so working ok :-)

/media/Popcorn/Magazines/Entertainment Weekly/
├── 2016-03-25
│   ├── 2016-03-25 - Entertainment Weekly.jpg
│   └── 2016-03-25 - Entertainment Weekly.pdf
├── 2016-04-08
│   ├── 2016-04-08 - Entertainment Weekly.jpg
│   └── 2016-04-08 - Entertainment Weekly.pdf
├── 2016-04-15
│   ├── 2016-04-15 - Entertainment Weekly.jpg
│   └── 2016-04-15 - Entertainment Weekly.pdf
└── 2016-04-22
    ├── 2016-04-22 - Entertainment Weekly.jpg
    └── 2016-04-22 - Entertainment Weekly.pdf

4 directories, 8 files

**Comment by BenBeyond** [comment]
Still having problems with snatched issues.  The below image shows 3 issues that were snatched by LL but now will not post process.

![image](https://cloud.githubusercontent.com/assets/5505883/14657707/548c0006-065d-11e6-8e1d-b723c3e8e23f.png)

**Comment by philborman** [comment]
Anything in the debug log that might help?

**Comment by BenBeyond** [comment]
Here is a copy of the log after hitting the Force Post Processing button on the magazine page:

> Timestamp	Level	Message
2016-04-22 13:11:39	DEBUG	Restart processDir job
2016-04-22 13:11:39	DEBUG	Stop processDir job
2016-04-22 13:11:39	INFO	No snatched books/mags have been found
2016-04-22 13:11:39	DEBUG	Snatched torrent Entertainment Weekly – 1-8 April 2016 is not in download directory
2016-04-22 13:11:39	DEBUG	Checking [/home/ben/Downloads/] for files to post process
2016-04-22 13:11:27	INFO	Log cleared, level set to [2]- Log Directory is [/home/ben/LazyLibrarian/Logs]

and the files from the previous screenshot are definitely in the download directory.

**Comment by philborman** [comment]
Ah - problem is LL  is expecting  the downloads are put in a folder, not 
just raw files in the base of the download directory. In your case it is 
looking for the folder...
/home/ben/Downloads/Entertainment Weekly – 1-8 April 2016/
in which it expects to find some_filename.pdf, any filename will do as 
it's the directory that determines the match.
This is the way it always works with nzb files, and also seems to work 
this way with the torrents I've grabbed here using transmission.
Seems your downloader is not working the way LL expects - what 
downloader are you using, and what settings? Haven't come across this 
"non-directory" way of downloading before. Might be the downloader needs 
tweaking, or might be we need to add a "raw files" mode to the 
postprocessor.

**Comment by BenBeyond** [comment]
I am also running Transmission but did not do any special setup, simply installed from default Ubuntu repo...

**Comment by philborman** [comment]
ok, found the same problem elsewhere on the web, someone using flexget...
http://discuss.flexget.com/t/force-transmission-to-download-into-a-subfolder/2114

Seems transmission doesn't use a sub-folder if theres only one file in 
the torrent.
Normally in a torrent you get something like...

Entertainment Weekly – 1-8 April 2016
├── Entertainment Weekly – 1-8 April 2016.pdf
├── Torrent downloaded from Demonoid.ooo.txt
└── Torrent Downloaded From ExtraTorrent.cc.txt

and LL recognises the folder name, grabs the pdf, discards the .txt 
files, deletes the folder after processing.  With single files it seems 
Transmission doesn't create the sub-folder. I will add some code to 
handle this case.
