### ISSUE TITLE
Book covers not found due to wrong separator generator in html

### ISSUE THREAD

**Issue by arogl** [DobyTang/LazyLibrarian#345]
When viewing the author page, no book covers are shown as the link is 

http://localhost:5299/images\cache\23591092.jpg

```
404 Not Found

The path '/images\cache\23591092.jpg' was not found.

Traceback (most recent call last):
  File "F:\Git\LazyLibrarian\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "F:\Git\LazyLibrarian\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "F:\Git\LazyLibrarian\cherrypy\_cperror.py", line 387, in __call__
    raise self
NotFound: (404, u"The path '/images\\cache\\23591092.jpg' was not found.")

Powered by CherryPy 3.2.0 

```

Changing the link to 

http://localhost:5299/images/cache/23591092.jpg

This is running git version 62fee9a32bfd5c008f64dacd5beb11eb890fb0a6 on windows 10 with Python 2.7.11.

This is the same result for the default interface as well as bootstrap.

**Comment by philborman** [comment]
We need images/cache/23591092.jpg  for the html URLs
but the actual filename is \images\cache\23591092.jpg on windows.
Just posted a fix for this, but the settings in the cache will still be wrong, (stored as  images\cache\ )
until you run "cleanCache" from the api, or use the "refresh active authors" button which is slower.
For the api...

http://localhost:port/api?apikey={your_api_key}&cmd=cleanCache

**Comment by philborman** [comment]
If this is fixed now, can you close the issue, or let me know if it's still not working, thanks.

**Comment by arogl** [comment]
Sorry, to be so late in replying.

yes the commit has fixed it.

**Comment by philborman** [comment]
No problem, just tidying up a bit.  I can't close the threads myself.
