### ISSUE TITLE
Deluge support for Labels

### ISSUE THREAD

**Issue by bncorbet** [DobyTang/LazyLibrarian#347]
Deluge has a nice feature to label torrent requests so that when completed they are placed in a particular directory for post-processing. Lazy Librarian supports deluge, but not the label option. Adding this option would be greatly appreciated.

**Comment by philborman** [comment]
Ok,  just added that.  Lazylibrarian doesn't create the label though, it needs to be created in deluge first.

**Comment by bncorbet** [comment]
This does not appear to be working for me.  I have the label "books" created in Deluge, but the new requests sent from LL always go into "No Label".

![image](https://cloud.githubusercontent.com/assets/17185883/17523531/97cf8566-5e20-11e6-93f2-6940a123c55a.png)

**Comment by philborman** [comment]
There are two deluge communication methods in lazylibrarian, are you using the deluge webui, or the daemon? If you use a deluge username and password we talk to the daemon. If you only have a password we talk to the webui.
Would be useful to know which so I can try and see which library needs focussing on. Also a debug log of a torrent being added would help

**Comment by bncorbet** [comment]
I am using the WebUI being the daemon does not seem to work for when I have LL running in a docker on my NAS. 

![image](https://cloud.githubusercontent.com/assets/17185883/17524478/6ea19a9a-5e24-11e6-8b64-102e55299077.png)

**Comment by philborman** [comment]
Yes, it wasn't even trying to set a label. code was there, just not being used. Fixed now.
