### ISSUE TITLE
Deluge WebUI username/password

### ISSUE THREAD

**Issue by bncorbet** [DobyTang/LazyLibrarian#351]
I am trying to get LL to work with my Deluge docker setup on my QNAP. I have the Deluge WebUI operating and other apps like Sonarr and CouchPotato are able to connect via the WebUI port of 8112 but LL does not.

The difference with those other apps is that they do not require a username, just a password. When I login to the Deluge WebUI there is only a prompt for password not username. 

Is LL designed use interact with Deluge via WebUI or the Daemon directly?  If WebUI, can we set LL to not require the username and only a password?

**Comment by bncorbet** [comment]
This is the error I am getting when trying to use Deluge with LL

Deluge: Connect FAILED
('_ssl.c:565: The handshake operation timed out',)

**Comment by philborman** [comment]
LL uses the daemon directly. The default daemon port is 58846, and your user/pass should be in the deluged auth file, see  http://dev.deluge-torrent.org/wiki/UserGuide/ThinClient
We either need to document this in the wiki, or change LL to use the WebUI instead. 
Not sure why LL uses the daemon directly as it's before my time :-)
What are the advantages of using the webui vs daemon, is it worth switching?

**Comment by bncorbet** [comment]
One advantage is that many pre-built docker apps for Deluge with auto PIA VPN connections built-in only allow port 8112 to connect to Deluge.

**Comment by philborman** [comment]
I have a test version in my branch (https://github.com/philborman/LazyLibrarian.git)
that will talk to Deluge using the daemon if you provide a username, and the WebUI if you don't.
Slightly messy as the libraries for each method are different.
Could you give it a try and report back? 

If it works ok we can push it to the master branch.
Thanks, Phil.
