### ISSUE TITLE
Download not happening with nab.su

### ISSUE THREAD

**Issue by sterlinganderson** [DobyTang/LazyLibrarian#352]
I'm not sure if this is a LazyLibrarian issue, or NZBGet. When an NZB is found the log tells me:

`2016-05-04 10:13:09	DEBUG	Requesting URL via GET method: https://api.nzb.su/getnzb/XXXXXXXXXXX.nzb&i=XXXXXXXX&r=XXXXXXXXX`

(real digits replaced with X by me)

Nothing is downloaded though. When a Blackhole is set the download happens, NZBGet gets it and everything is fine.

**Comment by philborman** [comment]
Ah, it's a bug in the way LL talks to nzbget.  Fixed it now, and also improved debug messages to make it easier to spot.

**Comment by philborman** [comment]
If this is now fixed, could you mark the thread closed using the thread tools. 
Thanks
