### ISSUE TITLE
Post processing for "non-snatched" items

### ISSUE THREAD

**Issue by vmcosco** [DobyTang/LazyLibrarian#356]
I have a handful of epub books from other sources because they weren't available on the indexer I have setup in LL.  I added the books as "Wanted" in LL, dropped the epub files in my download directory.  When I manually run the post-processor I get a message in the log stating "Nothing marked as snatched. Stopping postprocessor job".  Is there a way to still process items that are in my Wanted list but are not snatched by LL?

**Comment by philborman** [comment]
The "Wanted" flag is used to tell the search routines what to look for.
The "Snatched" flag shows what the searchers found and asked the downloaders to grab.
The postprocessor uses the "snatched" flag to match downloaded files against books you asked for.

There are three options, you could either move the books manually into your lazylibrarian library structure and then run "library scan", or put each book one at a time into your "alternate import directory" and use the "import book" function on the "manage" page. Both methods will load author details and a list of their books, then mark the ones found as able to be opened. The library scan method is probably quicker if there are a lot of books to import. BUT...

In your case, as the books you have manually downloaded are already listed in the library (and therefore their authors too),  and the books marked as "wanted", if you use the "manage" page to change the books status to "snatched" and then run "force post-process" they should get imported correctly.

**Comment by vmcosco** [comment]
Thanks for recommendation.  It won't process the book.  I changed to "snatched", Made sure the epub was named "Title - Author", I force post-processing and get "No snatched books/mags have been found".  

I suppose I can just try the other methods.  Will using one of those still create the opf file?

**Comment by philborman** [comment]
Can you try it with debug logging on, I think it should show what its
looking for and why it didn't match.

The other methods should still do the images,  opf etc as they all end up
using the same function

**Comment by vmcosco** [comment]
Turned on debugging and this is all I got:  

15-May-2016 09:18:54 - INFO    :: CP Server Thread-4 : Debug log display ON, loglevel is 2
15-May-2016 09:19:05 - DEBUG   :: POSTPROCESS :  Checking [W:\Media Downloads\complete\books] for files to post process
15-May-2016 09:19:05 - INFO    :: POSTPROCESS : No snatched books/mags have been found
15-May-2016 09:19:05 - DEBUG   :: POSTPROCESS : Stop processDir job
15-May-2016 09:19:05 - DEBUG   :: POSTPROCESS : Restart processDir job

I also verified that the .epub file is present in that directory

**Comment by philborman** [comment]
Just had another look through that code,  its a bit more complicated than
it first looks to fool LL into thinking it downloaded something it didn't.
You need to give it more info to be able to match. The manually downloaded
books would need to be put into subdirectories,  and the subdirectory names
need to contain the bookid.  This is normally done by the downloaders.  ie
you might have
W:\Media Downloads\complete\books\some_name_LL. (12345)\Title - author.epub

It can be done,  but it's a bit messy.  Probably better to use alternate
import directory,  or library scan.
