### ISSUE TITLE
Magazine cover creation issue

### ISSUE THREAD

**Issue by sukhysall** [DobyTang/LazyLibrarian#365]
Hi.

Since cover creation was last working, I accidentally uninstalled LL and had to reinstall it. Everything else appears to be working apart from magazine cover creation.

I know that "gsconvert.py" is packaged with LL during the install but can someone confirm what the exact configuration string is to place in the "Convert Program" configuration box?

**Comment by sukhysall** [comment]
UPDATE 26/05/2016

So I found an old snapshot of my config file and I entered the convert program field with "/usr/syno/bin/gsconvert.py" which I believed worked previously.

Except now I get this when i do a library scan of the magazines.

2016-05-26 15:06:22	DEBUG	/usr/syno/bin/gsconvert.py reports: Using gs [/usr/syno/bin/gs] version Usage: gsconvert input.pdf output.jpg Failed: Usage: gsconvert input.pdf output.jpg

2016-05-26 15:06:22	DEBUG	Creating cover for /volume1/magazines/Stuff UK/2016-06-01/2016-06-01 - Stuff UK.pdf using /usr/syno/bin/gsconvert.py

2016-05-26 15:06:22	DEBUG	Issue Stuff UK 2016-06-01 Hash: a2c9c926b1c1f61f00a4c3b2f5afd8bd6fee2e96

2016-05-26 15:06:22	DEBUG	Found Issue 2016-06-01 - Stuff UK.pdf

Help please?

**Comment by philborman** [comment]
Looks like your /usr/syno/bin/gs is not actually gs
Whats the output of gs --version?

**Comment by sukhysall** [comment]
......I may have copied "gsconvert.py" and renamed the copy as "gs". this is because I was trying to get conversion working and with the gs command missing previously I assumed that gsconvert.py was now "gs" so I did the rename thinking I was smart.

So actually. I don't have "gs"

so first things first, where can I download "gs" from please?

although I have no idea how "gs" disappeared in the first place. I haven't touched SSH in ages.

**Comment by sukhysall** [comment]
Issue fixed. I used ipkgui to download ImageMagick. In the "@optware" folder I found the file "gs".

It's possible I didn't need to install ImageMagick to get the file but that's the order I did it in. anyway I copied "gs" back to "/usr/syno/bin" and did a library scan. Covers are now being created again.

sorry for being an idiot.

**Comment by philborman** [comment]
gs is ghostscript
You can ipkg install ghostscript
Not sure if the version supplied with imagemagick is the latest,  but if
it's working...
