### ISSUE TITLE
International magazine naming issue

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#366]
First of all THANK YOU for continuing development on this excellent app!

The magazine section of LL is working well except for a few renaming issues.
I will GQ as an example. If I search for GQ it will find all versions (US, India, Japan, etc...).
The problem is I want all the GQ versions to go into 1 folder named "GQ", but I also need to retain the magazine country in the PDF filename. For example if LL downloads GQ 1-1-2016 and GQ India 1-1-2016, I need both PDF's to go into the "GQ" folder, but they need to be named "GQ - 1-1-2016" and "GQ - India - 1-1-2016". Notice 2 dashes on the international version. If they don't get named this way then LL creates 2 separate entries for my mag library ("GQ" and "GQ India").

1. One folder per magazine even if they have international version.
2. The country name needs to remain in the file name or else I can't have a US and India version from the same month.
3. One entry per magazine in LL instead of showing "GQ" and "GQ India"

**Comment by philborman** [comment]
Hmm,  tricky. 
It was done this way so that you could just download "gq india"  and not download any other international variants. 
Allowing partial name matches also makes it tricky to download for example "maxim"   without also getting "maximum pc". 
I will have to think about it... Unless anyone else wants to step up?

**Comment by MrMxyzptlk** [comment]
I will close this as well. After re-downloading my mags, everything is working swimmingly.
Thank you for looking into this 'issue'.
