### ISSUE TITLE
Magazine renaming issue with poorly named PDF's.

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#367]
Using GQ as an example again. If LL downloads GQ and the filename is "GQ March 2015.pdf" it will rename the file "GQ - 03-01-2015.pdf". If LL downloads a file named "GQ-3-1-2015.march.-2015.pdf" or something screwy like that, it will leave the name alone as well as create a new 'root' entry in magazines, called "GQ-3-1-2015.march.-2015.pdf"; rather than putting it in the GQ entry.

**Comment by philborman** [comment]
Can you post a debug log for one that fails, looking through the code it seems badly named ones like your example should fail the date matching routine and not get auto-downloaded

**Comment by MrMxyzptlk** [comment]
I will post a log this week.

**Comment by MrMxyzptlk** [comment]
So I decided to re-download the few magazines with international versions...and everything is working well. Not sure why I had the issue before? I download all GQ mags and LL successfully processed them and only created 1 folder "GQ".
