### ISSUE TITLE
Matching magazine titles too broadly

### ISSUE THREAD

**Issue by AndyHazz** [DobyTang/LazyLibrarian#368]
If I search for a magazine called 'Edge' I end up getting 3 downloads:

Edge TruePDF-July 2016
Pacific Edge-April June 2016
Living Edge TruePDF-May 2016

... is there a way to avoid getting those broader matches?

Perhaps if the magazine title you enter must be found at the beginning of the release name?

**Comment by philborman** [comment]
You could add pacific, living to reject words list

**Comment by AndyHazz** [comment]
Thanks, that seems to have done the trick :+1: 

I noticed there's a 40 char limit on the reject list though which could get filled quite quickly if many reject words are needed ...

**Comment by philborman** [comment]
Yes,  dont know whether we actually need a maxlength,  seems quite
arbitrary.  Size is used for display layout but I don't think maxlength is
actually used, the python list variables don't care. Rather than increase
the limit I might just remove it.

**Comment by sukhysall** [comment]
I have the same issue with Edge magazine. However I have a queryL: If you place the words "pacific" and "living" in the reject list, how does that affect books with either of those two words in the title?

**Comment by philborman** [comment]
LL doesn't reject words that are in the title you asked for,  or in the
author name.
