### ISSUE TITLE
magazine cover processing error

### ISSUE THREAD

**Issue by sukhysall** [DobyTang/LazyLibrarian#370]
LL version: d181a0af4a73d0c134df7503d74e46c74585e07e 

I don't know why given it seemed to work last time but I get an error during a library scan for generating a cover for a very recently downloaded mag. Debug log shows:

gsconvert.py reports: Using gs [/usr/syno/bin/gs] version 8.71 Failed: Command '['/usr/syno/bin/gs', '-sDEVICE=jpeg', '-dNOPAUSE', '-dBATCH', '-dSAFER', '-dFirstPage=1', '-dLastPage=1', '-sOutputFile=/volume1/magazines/Maximum PC/2016-05-01/2016-05-01 - Maximum PC.jpg', '/volume1/magazines/Maximum PC/2016-05-01/2016-05-01 - Maximum PC.pdf']' returned non-zero exit status 1

**Comment by philborman** [comment]
The version of ghostscript you are using cannot create a cover from the pdf.  
Gs version 8.71 is quite old,  and some versions don't handle pdf well,  if at all. 
I would try upgrading your version of gs,  there is a link to version 9.18 in the wiki

**Comment by sukhysall** [comment]
I have looked at the wiki. Thank you for bringing it to my attention. I don't think I've ever navigated to it ever.

Thanks. Post processing is working great again.
