### ISSUE TITLE
Providers tab in settings doesn't show when clicked.

### ISSUE THREAD

**Issue by hjgarron** [DobyTang/LazyLibrarian#373]
Providers tab in settings doesn't show when clicked. I am not sure how to submit a git change but I found the error in LazyLibrarian/data/interfaces/default/config.html and corrected it on my pc. It is has 2 semicolons in one spot and is missing one further down the code for tab-4 . 

difference:
$('#tabs7').removeClass('active');;  <----has 2 ;;
$('#tabs8').removeClass('active')  <---- missing ;

**Comment by philborman** [comment]
Many thanks for that. Just submitted a fix for the typo - well, cut and paste error really!

**Comment by philborman** [comment]
Think this can be closed now

**Comment by philborman** [comment]
Could you please use the thread tools to mark this closed if it's now sorted.  I think it is,  but i don't have write access to close the thread.  Thanks
