### ISSUE TITLE
Torznab Not Working with IPT

### ISSUE THREAD

**Issue by vmcosco** [DobyTang/LazyLibrarian#375]
Set up Jackett and have it configured with my tracker.  Works with Headphones so I am confident I have it set up correctly.  I added a book as "Wanted" in LL that I confirmed is available on my tracker.  I forced a search and got the following warning (I removed my API info):

Error fetching torrent from url: http://127.0.0.1:8009/dl/iptorrents/TorznabAPI, HTTP Error 404: Not Found

**Comment by philborman** [comment]
What version of Jackett,  anything useful in the jackett logs? 
Working here with Jackett Version 0.6.26.0
My jackett supplied url is very different to yours, http://192.168.0.2:9117/torznab/torrentz
Not sure quite what's going on without debug log to go at,  but it looks like the 404 error comes from the download function where LL is trying to get the torrent,  it's already talked to jackett,  asked for a list of matches and chosen the one it wants to grab.

**Comment by vmcosco** [comment]
Jackett Version 0.7.277.0

My Jackett supplied url is http://127.0.0.1:8009/torznab/iptorrents (I manually changed the port to fit in port schema).  The "very different" url is pasted directly from the debug log.  As you indicated, LL is finding a torrent it wants to download, and  then throwing the error when it tries to grab the torrent.  There are no other "Warning" lines in the debug log.

Looks like there might be something in the Jackett logs but I can't find the logs on my Windows system and the ones I access through the WebUI don't go far enough back.

**Comment by philborman** [comment]
I don't have an iptorrents account,  so can't check,  but it seems  iptorrents or later versions of jackett are returning information in a different layout to what LL is expecting. 
Your debug line http://127.0.0.1:8009/dl/iptorrents/TorznabAPI is shorter than we need,  should be more like http://127.0.0.1:8009/dl/iptorrents/TorznabAPI/145269845247755236/t.torrent
Unless when you edited out your api you edited the rest too :-) 
The number after your api is a reference in jackett database to the torrent you want. 
You should be able to put the whole line from http to t.torrent into your browser search bar and jackett will feed you the torrent file. 

If you didn't edit out the end of the line i woukd need to see what data iptorrents / jackett sent us in response to the query,  this would mean adding a line to providers.py to print the full set of results out so we can see whats going on

**Comment by vmcosco** [comment]
I double-checked and the reference number and t.torrent are not part of the address.  I pasted below the exact line from the log. 

2016-06-07 02:59:37	WARNING	Error fetching torrent from url: http://127.0.0.1:8009/dl/iptorrents/myTorznabAPI, HTTP Error 404: Not Found

 I can send you the log from Jackett if that would help.  If so, should I delete out any info for security or is that not necessary?

**Comment by philborman** [comment]
The most useful would be the data received by lazylibrarian
If you could edit your providers.py file,  line 615 just above
        if searchType == "book":
            resultFields = {

put
        logger.debug(nzbdetails)

Python is very fussy about whitespace and the 'l' of 'logger' needs to be
directly above the 'i'  of 'if search' using spaces not tabs to line up. It
should look like...
        logger.debug(nzbdetails)
        if searchType == "book":
            resultFields = {

Then send me the bit of debug log from
   '[NewzNabPlus] searchType [%s] with Host [%s] mode [%s] using api [%s]
for item [%s]'

to

    '[NewzNabPlus] - result fields from NZB are '

If you are posting the results on git,  overwrite your api with xxxxxxx
(and your ip address,  unless it's your local network 127.xxx or 192.xxx)

or email direct to me at phil dot borman at gmail dot com

**Comment by vmcosco** [comment]
Log is attached
[LL log.txt](https://github.com/DobyTang/LazyLibrarian/files/302738/LL.log.txt)

**Comment by philborman** [comment]
Thanks for that, but it doesn give us enough info. My bad.
The logger.debug(nzbdetails) line is just giving us a summary, not the 
full details
Can you take that line back out, and at line 382 change
      try:
           data = ElementTree.parse(resp)

to

      try:
           logger.debug(resp)
           data = ElementTree.parse(resp)

so we get the full response in the log

**Comment by vmcosco** [comment]
When I insert the logger.debug(rep) at line 383, the LL process starts and immediately stops.  I can see it happen in Process Explorer

**Comment by philborman** [comment]
yes, revert back to original source, I have found the problem and will 
push a fix in a few minutes.
Thanks.

**Comment by philborman** [comment]
As iptorrents is invite-only it was difficult to debug without help, any idea how I can get an invite, or is it just keep trying until they release some?
