### ISSUE TITLE
https://www.nzbfinder.ws/ - No such function (book)

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#376]
Reoccuring issue with nzbfinder provider.

It was working...now I keep getting the following error in the logs: https://www.nzbfinder.ws/ - No such function (book)

**Comment by philborman** [comment]
nzbfinder.ws does not have a dedicated book search. Most other newznab clients do.

In the lazylibrarian config page,  categories tab,  find the nzbfinder.ws entry and remove the word "book"  from the book search field,  then tick the lock to save settings. Don't forget the Save changes button  at the bottom of the page.

**Comment by MrMxyzptlk** [comment]
That worked; thank you!
