### ISSUE TITLE
Add support for magazines released by issue number

### ISSUE THREAD

**Issue by AndyHazz** [DobyTang/LazyLibrarian#378]
Some magazines are released by issue number rather than date - these are currently ignored and LL can't really process them ...

GamesTM is a good example, it'll be released with names like 'GamesTM.TruePDF-Issue.174.2016' or 'GamesTM.HQ.PDF-No.169.2016'

I've also seen specials released by volume - e.g. 'Retro.GamesTM.Collection.TruePDF-Vol.8'

It'd be good if there was a way to set specific magazines to use numerical release vs date, and look for a number immediately following 'Issue.', 'No.' or 'Vol.'. Or maybe instead of a user toggle setting, if no releases are found by date, fall back to using issue number.

**Comment by philborman** [comment]
Ok, just pushed a fix for this. Uses Issue/Vol/No/ if no date found. Rejects as "old" any issues where there is a year and it's earlier than the current year. Not perfect as a lot don't give a year in the title and we pull old issues in cos we don't know they're old.

Also it doesn't distinguish between  issue vol or no, so if it's important to you you might need to add words to the exclusion filters.  From your example, Retro.GamesTM.Collection.TruePDF-Vol.8 gets placed in the same folder as all the other  GamesTM  unless you put Retro or Collection or Vol as exclusion words to allow you to treat it as a separate magazine.

**Comment by AndyHazz** [comment]
Great! That's working for me now :+1:

**Comment by maxcore** [comment]
work pefect !! nice job @philborman :)
