### ISSUE TITLE
Filesize filter causes _everything_ to be rejected if set above 0

### ISSUE THREAD

**Issue by AndyHazz** [DobyTang/LazyLibrarian#388]
Not sure if this was missed as I was commenting on a closed issue #383, but the new filesize filter doesn't seem to work.

If you set a size greater than 0, everything is rejected. I've tried 4, 400, 4000, 400000 but they all fail to download a 3mb file that's successfully snatched if I disable the filesize filter by setting it to 0.

**Comment by philborman** [comment]
Sorry, my fault, was comparing _after_ I added " MB" to the string so it mucked up the comparison. Should be fixed now, I run with 200 as the limit to stop audiobooks being downloaded, but some pdf magazines can reach 100mb or more

**Comment by AndyHazz** [comment]
ah! Good stuff, thanks
