### ISSUE TITLE
Image path for loading spinner 'Getting author's books'

### ISSUE THREAD

**Issue by AndyHazz** [DobyTang/LazyLibrarian#390]
No big deal, but an image is missing for the loading spinner when refreshing an author's books.

It's using ../images/loader_black.gif
when it should be images/loader_black.gif

This might only be an issue because I'm using a web root?

**Comment by philborman** [comment]
Ffixed without web root now. Can you let me know if it works with a web root.
Thanks

**Comment by AndyHazz** [comment]
yes, also fixed if using webroot
