### ISSUE TITLE
Match Ratio not in effect

### ISSUE THREAD

**Issue by BenBeyond** [DobyTang/LazyLibrarian#397]
Hello,

I have set my match Ratio to 75%, but when I download books and get a match above 75%, LL will still say there is no match. A recent download and related debug log line:

> No match (88%) A Leaf on the Wind of All Hallo - Diana Gabaldon.epub for Diana Gabaldon - A Leaf on the Wind of All Hallows (Outlander #8 5)

Maybe I am reading the debug log line incorrectly, but it seems like it has found a 88% match, but still doesn't think it has found a match...

**Comment by philborman** [comment]
Ah - different match ratio. The one you can configure is the "search name match" ratio.
That message is the "downloaded name match" ratio which is currently not configurable.
It's hard-coded to 95% in postprocess.py line 139 if you want to tweak it. 

Normally the provider sends you the same name you asked for, and we look for 95% match to allow a bit of wiggle room for unicode or accented character differences.

I'm in the middle of reorganising the function calls at the moment so can't issue a fix for a few days as my source is radically different to the last update.

I will add a "downloaded name match" ratio option to the config in the next release though.

**Comment by BenBeyond** [comment]
Excellent! Thank you for the help!

**Comment by philborman** [comment]
If this is now working,  could you use the thread tools to mark it closed,  thanks
