### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by philborman** [DobyTang/LazyLibrarian#408]
Is anyone interested in package files for LazyLibrarian?
Seems it would be fairly easy to generate .deb and .rpm packages from our existing sources, in fact I've got versions built here that seem to be ok. Not sure how easy it is to create other formats yet. Snap packages are supposed to be able to run on all linux variants, but seem hard to create for python programs, I need to look into them again.

For deb and rpm packages we would just have to create a download area, which github can provide. The packages wouldn't have an internal update mechanism (like the git versions do) but we could create repositories for each packaging format, which is more work. We would have to create a new deb/rpm after each change, and could probably warn deb/rpm users that they were out of date and need to upgrade, though the upgrade couldn't be done from inside LazyLibrarian, it would need to be done from the relevant package manager.  

Feedback would be appreciated

**Comment by daktak** [comment]
Gentoo ebuild here http://data.gpo.zugaina.org/gentoo-htpc/net-nntp/lazylibrarian/

**Comment by philborman** [comment]
Do you have a build script that you are willing to share?
I have asked DobyTang if he can set up a webpage linked to the git repository where we can make all the various packages available for download. It would be better if we can keep all the packages in sync, so each time the repository changes we can rebuild the  deb rpm ebuild aur snap ... and any variants.

**Comment by fryfrog** [comment]
I made an AUR package for Arch Linux here https://aur.archlinux.org/packages/lazylibrarian-git/, but since there are no actual version releases... its just a git package. :/

**Comment by philborman** [comment]
My deb and rpm packages just use the date, eg lazylibrarian_20160828-1_amd64.deb
I have asked DobyTang to set up a webpage linked to the github site (github provide one, but needs to be set up by the owner). Once this is up and running we can put the packages all in one spot. Would be good if we could automate rebuilding the packages whenever source files change.

**Comment by famewolf** [comment]
@philborman I couldn't figure out how to send you a private message and your forked repo doesn't allow me to open an "issue".   I cloned your repo and have it where I can change a symbolic link to swap between yours and dobytang's.  I noticed yours keeps insisting I'm 5 commit's behind where dobytang's says I'm up to date.  After looking at it, it's looking at:  http://github.com/DobyTang/LazyLibrarian/compare/23948bedaeb007b43b274a289b3bece1f2de32cc...8ac4b4d0714f77ede2ac736be1fd2aa59ae704db

What do I need to change to have the updater look at YOUR repo rather than DobyTang's?

**Comment by philborman** [comment]
Yes the updater is built in. We store the repo in config.ini
Maybe changing that will be enough to switch you between repos I'm not sure,  never tried it.

**Comment by famewolf** [comment]
Thank you.  I tracked it down to a freenas issue as the config.ini was moved to /var/db/lazylibrarian.  Once updated there it worked fine.  It was more of a learning exercise than anything else.  Now that I understand how to swap github's for this I can do it for other freenas plugins so I really appreciate the help.  Now my only issue is that my book image cache appears to be all broken images..I think I initially had an ancient version installed that may not even have had images.  I guess at this point I'd have to redo everything to get the images and given that choice I'll just stick with broken images.

**Comment by philborman** [comment]
You can easily refresh the images from the api
Enable api on the config page,  and use it from your browser like this...
localhost:port/api?apikey=your_api_key&cmd=

The commands you want (one at a time)  are  cleanCache,  getBookCovers,
getAuthorImages

For magazines, to refresh cover images use forceMagazineScan

**Comment by famewolf** [comment]
Thanks for the commands.  I tried them and a few images filled in but the vast majority remained broken....I attached a screenshot as an example.

![ll](https://cloud.githubusercontent.com/assets/4558832/19247538/aefeebf0-8ef9-11e6-9446-98bf26f0d3b0.png)

**Comment by philborman** [comment]
The commands can take a while to run,  check the log to see if they
completed.

On Mon, 10 Oct 2016, 20:57 famewolf, <notifications@github.com> wrote:

Thanks for the commands. I tried them and a few images filled in but the
vast majority remained broken....I attached a screenshot as an example.

[image: ll]
<https://cloud.githubusercontent.com/assets/4558832/19247538/aefeebf0-8ef9-11e6-9446-98bf26f0d3b0.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DobyTang/LazyLibrarian/issues/408#issuecomment-252712344>,
or mute the thread

**Comment by famewolf** [comment]
Thank you.  I'm sure I was not leaving enough time for each command to complete but all I keep getting is variations on this:

10-Oct-2016 15:59:41 - WARNING :: API-CLEANCACHE : Database Error: database is locked
10-Oct-2016 16:00:07 - WARNING :: SEARCHRSS : Database Error: database is locked
10-Oct-2016 16:00:08 - WARNING :: SEARCHRSS : Database Error: database is locked
10-Oct-2016 16:00:09 - WARNING :: SEARCHRSS : Database Error: database is locked
10-Oct-2016 16:00:10 - WARNING :: SEARCHRSS : Database Error: database is locked
10-Oct-2016 16:00:11 - WARNING :: SEARCHRSS : Database Error: database is locked
10-Oct-2016 16:00:33 - WARNING :: CRON-POSTPROCESS : Database Error: database is locked
10-Oct-2016 16:00:55 - WARNING :: CRON-POSTPROCESS : Database Error: database is locked
10-Oct-2016 16:01:17 - WARNING :: CRON-POSTPROCESS : Database Error: database is locked
10-Oct-2016 16:01:39 - WARNING :: CRON-POSTPROCESS : Database Error: database is locked
10-Oct-2016 16:02:01 - WARNING :: CRON-POSTPROCESS : Database Error: database is locked
10-Oct-2016 16:02:02 - WARNING :: API-CLEANCACHE : Database Error: database is locked
10-Oct-2016 16:02:03 - WARNING :: API-CLEANCACHE : Database Error: database is locked
10-Oct-2016 16:02:04 - WARNING :: API-CLEANCACHE : Database Error: database is locked
10-Oct-2016 16:02:05 - WARNING :: API-CLEANCACHE : Database Error: database is locked
10-Oct-2016 16:02:06 - WARNING :: API-CLEANCACHE : Database Error: database is locked
10-Oct-2016 16:02:07 - DEBUG   :: API-CLEANCACHE : Cover missing for Nova Science Fiction Series /usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/data/images/cache/497277.jpg
10-Oct-2016 16:02:29 - WARNING :: CRON-POSTPROCESS : Database Error: database is locked


Now I've restarted lazylibrarian a couple of times..shouldn't that free up the database or do I have to recyle the whole jail? (Jail on freebsd is kinda like a virtual machine).

**Comment by philborman** [comment]
I think stopping it should free the database.
You can check the log for completion of each command,  or add &wait to the
api commands so that the browser stops until the command completes. Except
for the getAuthorImages command,  which does not have a wait option. Should
do,  I will add it.  For that one keep checking the log until it says how
many images it updated.
On my large database of 12000 books the getBookCovers command can take a
few hours :-)

**Comment by famewolf** [comment]
Thanks so much for the help...finally got things straightened out...I had to be much more patient...given I'm on slow internet even though it said I had "only" 5000 books it still took running overnight to get all the book images and the clean cache ran rather long...and that was only with 50 authors.  Some of them such as "Alex Bledsoe" still show the goodreads ? for every book cover but others such as Anne Mccaffrey  are filled out.  The author 50 images only took a few minutes this morning. ;)
