### ISSUE TITLE
Magazines on low resolutions

### ISSUE THREAD

**Issue by perezbalen** [DobyTang/LazyLibrarian#409]
Hi

I found it's imposible to add new magazines on the iphone, as the textbox is not shown. I found that on the iPad it's only shown on landscape mode; and not on portrait mode. I believe that it's resolution dependant.

**Comment by philborman** [comment]
Yes, the default interface is not very good on small screens, and really bad on very small screens.
Don't know if this can be fixed, would need someone with good html knowledge.

The bookstrap theme works very well on small screens, ideal for phones and tablets. You can easily switch from the config page. It's under  "Appearance", "Interface"

**Comment by TommyE123** [comment]
Hi, 
I'm currently looking at starting to help out a bit by making a few tweaks to some of the layouts to make orientation better on smaller devices. I'll add this to my list of things to look at.

Tom

**Comment by philborman** [comment]
That would be great thanks!

**Comment by maxcore** [comment]
Nice!
