### ISSUE TITLE
KAT.cr no longer returning results

### ISSUE THREAD

**Issue by bncorbet** [DobyTang/LazyLibrarian#414]
KAT.cr is no longer returning results being it has been shutdown.  What are people using for Torrent providers?  I have tried a few different URLs in the KAT host config, but nothing is finding anything.

Any suggestions?

**Comment by philborman** [comment]
try kickass.cd

**Comment by bncorbet** [comment]
I get a 403 Forbidden in the logs, but I am able to access the URL from the logs directly and download the torrent, so I don't think my firewall is blocking it.

**Comment by philborman** [comment]
I've seen 403 errors on another site before, might be because we don't supply a user agent. Original KAT didn't need one. I have added user-agent to latest build, hopefully this will fix it, can you let me know.
Thanks

**Comment by bncorbet** [comment]
![image](https://cloud.githubusercontent.com/assets/17185883/17415581/89ea4e8e-5a58-11e6-9997-08422b35a030.png)

Here is the Link for the KAT results:
http://kickass.cd/usearch/Sherry%20Thomas%20The%20Burning%20Sky/?category=books&field=seeders&rss=1&sorder=desc

The results say 0 found, but the link shows 1 available.  Seems like the parsing is not finding it maybe.

**Comment by philborman** [comment]
It's finding it,  but rejecting as there are no seeders 
This is expected behaviour but I will improve the log messages

**Comment by bncorbet** [comment]
Even if I have the minimum seeders setting to "0"

**Comment by philborman** [comment]
Ah - seems kickass.cd is sending us a html result instead of a feed which KAT used to send.
This will take a bit of work...

**Comment by philborman** [comment]
Just added html parsing for kickass, and added piratebay mirrors too.
Currently working with https://piratebays.co  and   kickass.cd

**Comment by Arcanemagus** [comment]
kickass.cd(.am, .mx) is apparently just a mirror.... but not of the old KAT content, instead of TPB: https://torrentfreak.com/popular-kat-mirror-is-in-reality-a-dressed-up-pirate-bay-mirror-160805/

This is why you should _never_ trust those clones that pop up after a popular site dies 😕.

**Comment by philborman** [comment]
Ah, thanks for that.
Any other sites worth adding instead?  zooqle.com,  torrentdownloads.me
