### ISSUE TITLE
Config page save changes button always puts you to first tab

### ISSUE THREAD

**Issue by coleberhorst** [DobyTang/LazyLibrarian#418]
Clicking save changes always reloads you to the first tab on the config page.

**Comment by philborman** [comment]
Yes, would be useful if we could always take you back to the tab you were last on, but it's beyond my programming skills :-(

I can see how to make the config page show a specific tag on page-load, just can't figure out how to tell which tab we're currently on, or how to store and recall it. Maybe storage could be in a lazylibrarian global variable, another user suggested it could be done using cookies, but I don't know how.

We need some input from a user with experience in html and javascript/jquery

**Comment by coleberhorst** [comment]
Ok I will try and look at it. I'm not the best either haha

**Comment by philborman** [comment]
I've just got it working with the default interface using switch statements and click functions, working on the bookstrap interface at the mo.
there is probably a better way of doing it, seems a bit over complicated to me ;-/

**Comment by philborman** [comment]
Can't get it to work with bookstrap at all. Seems the click functions and switch statement just get ignored.
In the default interface for each tab I've put this,  with #current_tab  being a lazylibrarian.global
so we can keep the value in the python code when we hit "save config" ...
            $('#tabs1').click(function(){
                $("#current_tab").val('1');
                $('#tabs ul li').removeClass('active');
                $('.table_wrapper').hide();
                $('.tabs-1').parent().show();
                $('#tabs1').addClass('active');
            })

and a case statement like this, with default being tab1 
            switch ($("#current_tab").val())
            {
               case "2":
                   $('#tabs ul li').removeClass('active');
                   $('.table_wrapper').hide();
                   $('.tabs-2').parent().show();
                   $('#tabs2').addClass('active');
                   break;

any idea why this doesn't work in the bookstrap/config.html?
default interface only has two fields,  id= and href=
bookstrap uses id= href= role= data-toggle= aria-controls=
it's beyond me ;-/

**Comment by philborman** [comment]
ok, got this sorted now. Just needs a bit more testing...

**Comment by coleberhorst** [comment]
works like a charm on live. Good job figuring this one out! :+1:
