### ISSUE TITLE
Add Author Not Adding Author

### ISSUE THREAD

**Issue by relder251** [DobyTang/LazyLibrarian#42]
Steps:
   1. Click the "Authors" button
   2. Type name of Author in search field and hit enter
   3. After results are presented, click "Add Author"

Results: Image of author not shown; continuous search loop 

1. 
![image](https://f.cloud.github.com/assets/615187/2288181/0de708d6-9ff7-11e3-80ac-a156b723da91.png)
2. 
![image](https://f.cloud.github.com/assets/615187/2288190/25681978-9ff7-11e3-831c-15ceadabe84f.png)
3. 
![image](https://f.cloud.github.com/assets/615187/2288226/72f75a82-9ff7-11e3-9118-185437b03fa4.png)

Results: 
![image](https://f.cloud.github.com/assets/615187/2288276/ca7d6e72-9ff7-11e3-8830-d8eaa78047b0.png)

**Comment by rodgarcia1** [comment]
Have this been solved? I'm having the same problem but the error is the following:
Error fetching authorid: undefined entity: line 51, column 36
