### ISSUE TITLE
Torrent Support

### ISSUE THREAD

**Issue by coolius** [DobyTang/LazyLibrarian#43]
Hi DolbyTang,

Thanks alot for taking ownership of this project.

I was hoping that it would be possible to add bittorrent support to LazyLibrarian in addition to the existing NZB support.

I know that allanon2 implemented some basic support for this in his branch some months ago and perhaps if this could be merged into this branch it would be a good starting point.

I am hopefully that I will be able to contribute to this myself when I have the time as I would love to see this project reaching the same level as its more popular cousins.

**Comment by solspire** [comment]
what 's new ?
