### ISSUE TITLE
[Req] Add option to remove mag or book

### ISSUE THREAD

**Issue by maxcore** [DobyTang/LazyLibrarian#431]
Hi ,

Its possible to add option for remove book or magazine permanently ? The remove option is only for the LazyLibrarian db not for the source (hard drive)

thx :)

**Comment by philborman** [comment]
Can do, but needs some thinking about. Simple enough for magazines, delete the magazine and all issues of it, and all the cover images, then delete the empty directories. Or if you only delete one issue, delete one cover image and one directory.
Books are more of a problem, especially if it's a shared calibre library, or if more than one format of a book. Should we delete all copies (epub/mobi/azw/pdf) or only the one in our database. Should we delete the cover image and metadata files (which might not be ours) or the directories which might not be ours either.

**Comment by philborman** [comment]
I think I will add a delete option with a confirmation prompt and leave it up to the user to decide.
"Remove" will remove from database, "Delete" will remove from disc and database

**Comment by maxcore** [comment]
like sickrage ! nice  ;)

**Comment by maxcore** [comment]
@philborman work perfectly ! ;)
