### ISSUE TITLE
https://nzbfinder.ws - No such function (book)

### ISSUE THREAD

**Issue by perezbalen** [DobyTang/LazyLibrarian#433]
Hi 

I'm getting this error: https://nzbfinder.ws - No such function (book)

But https://recordnotfound.com/LazyLibrarian-DobyTang-15602/issues repots it beinng fixed 3 months ago.

**Comment by philborman** [comment]
Yes, if you follow the instructions in the reply it is fixed.
Auto-detection fails for some broken sites, and you need to manually override the autodetected settings.
Sadly lots of sites don't correctly report their capabilities, and I think it's better to allow the user to override than try to keep track of which sites are broken. Who knows,maybe one day they'll fix it :-)
