### ISSUE TITLE
Question: How do you make the Calibre import program work please?

### ISSUE THREAD

**Issue by sukhysall** [DobyTang/LazyLibrarian#445]
Hi

So just to test it out, I have LL running on my Windows 10 machine. Also have Calibre installed.
In the LL config, I have placed the full path name to the calibredb. What I've entered is:

"C:\Program Files\Calibre2\calibredb" (without the speech marks)

My LL base destination folder is in the same directory as Calibre library. I would search for a book in LL, it would go away and find it and upon post processing, LL would send a request to Calibre to add it which I could see occur in real-time in Calibre and also in the logs (set to Debug).

HOWEVER, oddly enough, the book that LL had gone away and found for me would appear in Calibre but not necessarily in LL itself:

Example: I added the author Sam Sisavath to LL. After the author update I then set all 10 books to wanted. 

A few minutes later, I now have 10 Sam Sisavath books sitting in Calibre, however in LL, I have 4 books listed as "open", 2 listed as "snatched" and 4 listed as "wanted".

So I check Calibre and yes there is an issue whereby not all the books have the same author naming convention as some of the books have the author listed back to front and there is inconsistency in the titles.

Is this correct behavior so far?

**Comment by sukhysall** [comment]
Just to add, I have Calibre's library in the same folder that LL looks at.

**Comment by philborman** [comment]
Calibredb is used when you download a new book to make sure lazylibrarian
and calibre share the one download. We ask calibre to import the book,
then update our library to match.  Should show up in the debug log if it's
not working. Use the librarysync button to import an existing calibre
library into lazylibrarian

**Comment by philborman** [comment]
Update
There seems to be no way to get calibre to read the metadata file for info. Other calibre users have asked for this feature over the years, but no joy. Calibre will either read from data embedded in the bookfile, or by parsing the books filename, but default is to read the embedded data.
This will need further thought. For now, use the calibre metadata editor to correct the data, then tell lazylibrarian to rescan the library and pick up the changed data.

**Comment by forge33** [comment]
could be possible to write the metadata ourselves so Calibre knows what we're dealing with?
https://github.com/aerkalov/ebooklib

**Comment by philborman** [comment]
Would work for epub only. Would be better if we had a more generic solution for mobi,pdf,azw3 etc
We currently read epub and mobi tags, pdf generally aren't useful (missing/incomplete/wrong) but metadata.opf is usually ok. There is conflicting advice on the web about calibre and opf files,  Kovid Goyal (calibre author) say it works, users disagree. Maybe we should try it as that's the simplest/cleanest solution.

That epub library looks quite neat though, I might replace the existing code in LL to use it.

**Comment by forge33** [comment]
I've tried to use calibre for my library management with LL doing the bulk of the work and it just didnt work out with calibre. So I hardly use it now

**Comment by philborman** [comment]
UPDATE
The ebooklib  library is quite fragile and breaks on books with incomplete metadata, so I'm sticking with the current ebook reading code for now. Works with epub and opf files. Have uploaded a version of LL that creates  a metadata file for calibre before calling calibredb, would be interesting to know if it works on authors that it failed with before (eg Sam Sisavath)   Tried it here but my nzb/torrent providers can only find one book of his.

**Comment by philborman** [comment]
ok, so calibre doesn't work as described.
Ignores book_name.opf files (author says this should work)
Ignores it's own metadata.opf files (author says this should work too)
Ignores command line switches --author and --title (only works if no embedded metadata)

Best we can do is configure calibre to ignore metadata completely and supply a filename that it can parse.
In Calibre -> Preferences -> Import/Export -> Adding Books  
untick "Read metadata from file contents rather than filename"   and click "Apply"

Works fine with Sam Sisavath now, _except_ you will need to increase LL Search Match Ratio to 90
(Config -> Processing -> Search Match Ratio) so it can distinguish between 
The Fields of Lemuria (Purge of Babylon #3.2)
The Walls of Lemuria (Purge of Babylon #3.1)

and don't ask calibre to update metadata for the books you imported, it will change the filenames and possibly the author name so LL can't find them

**Comment by philborman** [comment]
With latest release,  after using calibre to update metadata you can rescan individual authors to pick up the new filenames.  Think maybe this can be closed now?

**Comment by sukhysall** [comment]
Hi. Yes it's good to be closed. 

Regards

Sukhjinder Sall

**Comment by Telecart** [comment]
I think I'm running into the same issue:
I just started using LL and set it up to update calibredb. I then noticed after downloading a book, it would show up multiple times in calibre - exact duplicate copies. I think what was happening is that it would update calibre but not LL of the new download it found, and so the status remained "wanted". 

Assuming this is the issue, the remedy for it is...To manually refresh the author after downloading? 
Is there a way to automate that?

**Comment by philborman** [comment]
The original issue was fixed a while ago. Not sure what might be going wrong, a debug log would probably help. Calibre should have duplicate detection enabled by default and we pick up any error messages from it, so the log should show what's going on. Status "wanted" for a book means lazylibrarian search tasks have not found a copy yet, so nothing should have gone to calibre anyway?

**Comment by Telecart** [comment]
Well, it definitely is in calibre and definitely still showed up as 'wanted' when I looked for it.

Here's a log dump


`04-Mar-2017 10:10:51 - DEBUG :: POSTPROCESS : Processing book 22613
04-Mar-2017 10:10:51 - DEBUG :: POSTPROCESS : Importing Simulacra and Simulation - Jean Baudrillard into calibre library
04-Mar-2017 10:10:51 - DEBUG :: POSTPROCESS : [u'/Applications/calibre.app/Contents/MacOS/calibredb', 'add', '-1', u'--with-library=/Volumes/drive/eBooks/Library', u'/Volumes/drive/Books-Unsorted/Jean Baudrillard - Simulacra and Simulation LL.(22613)']
04-Mar-2017 10:10:52 - DEBUG :: POSTPROCESS : /Applications/calibre.app/Contents/MacOS/calibredb reports: Backing up metadata
Added book ids: 195
Notifying calibre of the change

04-Mar-2017 10:10:52 - DEBUG :: POSTPROCESS : Calibre ID: 195
04-Mar-2017 10:10:52 - DEBUG :: POSTPROCESS : [u'/Applications/calibre.app/Contents/MacOS/calibredb', 'set_metadata', '--field', u'authors:Jean Baudrillard', '--with-library', u'/Volumes/drive/eBooks/Library', '195']
04-Mar-2017 10:10:53 - DEBUG :: POSTPROCESS : /Applications/calibre.app/Contents/MacOS/calibredb author reports: Title               : Jean Baudrillard - Simulacra And Simulation (ingles)
Title sort          : Jean Baudrillard - Simulacra And Simulation (ingles)
Author(s)           : Jean Baudrillard [Baudrillard, Jean]
Publisher           : ePub Bud (www.epubbud.com)
Languages           : eng
Timestamp           : 2017-03-04T15:10:52+00:00
Published           : 2011-04-04T04:00:00+00:00
Identifiers         : epubbud:http://www.epubbud.com/epubs/N/5/N5RMU7SV/Jean_Baudrillard___Simulacra_And_Simulation__ingles_.epub
Formats             : EPUB
Backing up metadata
Notifying calibre of the change

04-Mar-2017 10:10:53 - DEBUG :: POSTPROCESS : [u'/Applications/calibre.app/Contents/MacOS/calibredb', 'set_metadata', '--field', u'title:Simulacra and Simulation', '--with-library', u'/Volumes/drive/eBooks/Library', '195']
04-Mar-2017 10:10:54 - DEBUG :: POSTPROCESS : /Applications/calibre.app/Contents/MacOS/calibredb book reports: Title               : Simulacra and Simulation
Title sort          : Jean Baudrillard - Simulacra And Simulation (ingles)
Author(s)           : Jean Baudrillard [Baudrillard, Jean]
Publisher           : ePub Bud (www.epubbud.com)
Languages           : eng
Timestamp           : 2017-03-04T15:10:52+00:00
Published           : 2011-04-04T04:00:00+00:00
Identifiers         : epubbud:http://www.epubbud.com/epubs/N/5/N5RMU7SV/Jean_Baudrillard___Simulacra_And_Simulation__ingles_.epub
Formats             : EPUB
Backing up metadata
Notifying calibre of the change

04-Mar-2017 10:10:54 - DEBUG :: POSTPROCESS : [u'/Applications/calibre.app/Contents/MacOS/calibredb', 'set_metadata', '--field', u'identifiers:goodreads:22613', '--with-library', u'/Volumes/drive/eBooks/Library', '195']
04-Mar-2017 10:10:54 - DEBUG :: POSTPROCESS : /Applications/calibre.app/Contents/MacOS/calibredb identifier reports: Title               : Simulacra and Simulation
Title sort          : Jean Baudrillard - Simulacra And Simulation (ingles)
Author(s)           : Jean Baudrillard [Baudrillard, Jean]
Publisher           : ePub Bud (www.epubbud.com)
Languages           : eng
Timestamp           : 2017-03-04T15:10:52+00:00
Published           : 2011-04-04T04:00:00+00:00
Identifiers         : goodreads:22613
Formats             : EPUB
Backing up metadata
Notifying calibre of the change

04-Mar-2017 10:10:55 - INFO :: POSTPROCESS : Scanning ebook directory: /Volumes/drive/eBooks/Library/Jean Baudrillard/
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : [/Volumes/drive/eBooks/Library/Jean Baudrillard/] Now scanning subdirectory Simulacra and Simulation (190)
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : book meta [] [en] [None] [Jean Baudrillard - Simulacra And Simulation (ingles)] [epub]
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : file meta [] [eng] [Jean Baudrillard] [Simulacra and Simulation] [22613]
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : Exact match [Simulacra and Simulation]
04-Mar-2017 10:10:55 - WARNING :: POSTPROCESS : Updating book location for Jean Baudrillard Simulacra and Simulation from /Volumes/drive/eBooks/Library/Jean Baudrillard/Simulacra and Simulation (194)/Simulacra and Simulation - Jean Baudrillard.epub to /Volumes/drive/eBooks/Library/Jean Baudrillard/Simulacra and Simulation (190)/Simulacra and Simulation - Jean Baudrillard.epub
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : Jean Baudrillard Simulacra and Simulation matched BookID 22613, [Jean Baudrillard][Simulacra and Simulation]
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : [/Volumes/drive/eBooks/Library/Jean Baudrillard/] Now scanning subdirectory Simulacra and Simulation (191)
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : book meta [] [en] [None] [Jean Baudrillard - Simulacra And Simulation (ingles)] [epub]
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : file meta [] [eng] [Jean Baudrillard] [Simulacra and Simulation] [22613]
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : Exact match [Simulacra and Simulation]
04-Mar-2017 10:10:55 - WARNING :: POSTPROCESS : Updating book location for Jean Baudrillard Simulacra and Simulation from /Volumes/drive/eBooks/Library/Jean Baudrillard/Simulacra and Simulation (190)/Simulacra and Simulation - Jean Baudrillard.epub to /Volumes/drive/eBooks/Library/Jean Baudrillard/Simulacra and Simulation (191)/Simulacra and Simulation - Jean Baudrillard.epub
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : Jean Baudrillard Simulacra and Simulation matched BookID 22613, [Jean Baudrillard][Simulacra and Simulation]
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : [/Volumes/drive/eBooks/Library/Jean Baudrillard/] Now scanning subdirectory Simulacra and Simulation (192)
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : book meta [] [en] [None] [Jean Baudrillard - Simulacra And Simulation (ingles)] [epub]
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : file meta [] [eng] [Jean Baudrillard] [Simulacra and Simulation] [22613]
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : Exact match [Simulacra and Simulation]
04-Mar-2017 10:10:55 - WARNING :: POSTPROCESS : Updating book location for Jean Baudrillard Simulacra and Simulation from /Volumes/drive/eBooks/Library/Jean Baudrillard/Simulacra and Simulation (191)/Simulacra and Simulation - Jean Baudrillard.epub to /Volumes/drive/eBooks/Library/Jean Baudrillard/Simulacra and Simulation (192)/Simulacra and Simulation - Jean Baudrillard.epub
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : Jean Baudrillard Simulacra and Simulation matched BookID 22613, [Jean Baudrillard][Simulacra and Simulation]
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : [/Volumes/drive/eBooks/Library/Jean Baudrillard/] Now scanning subdirectory Simulacra and Simulation (193)
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : book meta [] [en] [None] [Jean Baudrillard - Simulacra And Simulation (ingles)] [epub]
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : file meta [] [eng] [Jean Baudrillard] [Simulacra and Simulation] [22613]
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : Exact match [Simulacra and Simulation]
04-Mar-2017 10:10:55 - WARNING :: POSTPROCESS : Updating book location for Jean Baudrillard Simulacra and Simulation from /Volumes/drive/eBooks/Library/Jean Baudrillard/Simulacra and Simulation (192)/Simulacra and Simulation - Jean Baudrillard.epub to /Volumes/drive/eBooks/Library/Jean Baudrillard/Simulacra and Simulation (193)/Simulacra and Simulation - Jean Baudrillard.epub
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : Jean Baudrillard Simulacra and Simulation matched BookID 22613, [Jean Baudrillard][Simulacra and Simulation]
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : [/Volumes/drive/eBooks/Library/Jean Baudrillard/] Now scanning subdirectory Simulacra and Simulation (194)
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : book meta [] [en] [None] [Jean Baudrillard - Simulacra And Simulation (ingles)] [epub]
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : file meta [] [eng] [Jean Baudrillard] [Simulacra and Simulation] [22613]
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : Exact match [Simulacra and Simulation]
04-Mar-2017 10:10:55 - WARNING :: POSTPROCESS : Updating book location for Jean Baudrillard Simulacra and Simulation from /Volumes/drive/eBooks/Library/Jean Baudrillard/Simulacra and Simulation (193)/Simulacra and Simulation - Jean Baudrillard.epub to /Volumes/drive/eBooks/Library/Jean Baudrillard/Simulacra and Simulation (194)/Simulacra and Simulation - Jean Baudrillard.epub
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : Jean Baudrillard Simulacra and Simulation matched BookID 22613, [Jean Baudrillard][Simulacra and Simulation]
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : [/Volumes/drive/eBooks/Library/Jean Baudrillard/] Now scanning subdirectory Simulacra and Simulation (195)
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : book meta [] [en] [None] [Jean Baudrillard - Simulacra And Simulation (ingles)] [epub]
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : file meta [] [eng] [Jean Baudrillard] [Simulacra and Simulation] [22613]
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : Exact match [Simulacra and Simulation]
04-Mar-2017 10:10:55 - WARNING :: POSTPROCESS : Updating book location for Jean Baudrillard Simulacra and Simulation from /Volumes/drive/eBooks/Library/Jean Baudrillard/Simulacra and Simulation (194)/Simulacra and Simulation - Jean Baudrillard.epub to /Volumes/drive/eBooks/Library/Jean Baudrillard/Simulacra and Simulation (195)/Simulacra and Simulation - Jean Baudrillard.epub
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : Jean Baudrillard Simulacra and Simulation matched BookID 22613, [Jean Baudrillard][Simulacra and Simulation]
04-Mar-2017 10:10:55 - INFO :: POSTPROCESS : 0/6 new/modified books found and added to the database
04-Mar-2017 10:10:55 - INFO :: POSTPROCESS : 18 files processed
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : Updating bookcounts for 1 author
04-Mar-2017 10:10:55 - INFO :: POSTPROCESS : Library scan complete
04-Mar-2017 10:10:55 - ERROR :: POSTPROCESS : Postprocessing for Simulacra and Simulation - Jean Baudrillard has failed: Unable to import book to /Volumes/drive/eBooks/Library/Jean Baudrillard/
04-Mar-2017 10:10:55 - ERROR :: POSTPROCESS : Warning - Residual files remain in /Volumes/drive/Books-Unsorted/Jean Baudrillard - Simulacra and Simulation LL.(22613).fail
04-Mar-2017 10:10:55 - ERROR :: POSTPROCESS : Unable to rename /Volumes/drive/Books-Unsorted/Jean Baudrillard - Simulacra and Simulation LL.(22613), [Errno 66] Directory not empty
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : Book with id: 22613 found in download directory
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : Skipping BookID 22613, already exists
04-Mar-2017 10:10:55 - INFO :: POSTPROCESS : 1 book/mag processed.
04-Mar-2017 10:10:55 - INFO :: POSTPROCESS : Nothing marked as snatched.
04-Mar-2017 10:10:55 - DEBUG :: POSTPROCESS : Stop processDir job
`

**Comment by philborman** [comment]
ok, so that makes a bit of sense now.

Calibre is not realising the books are duplicates as the embedded book
metadata is incorrect, so lazylibrarian feeds the correct author/title in
afterwards. You can see that clearly in the log. Next time your
postprocessor runs it sends the book again, calibre thinks its a new book
as the metadata is different, lazylibrarian amends the author/title again...

Lazylibrarian thinks postprocessing failed, but to stop the postprocessor
repeating the failed books on each run we rename failed books by adding
.fail to the end of the directory name.Unfortunately it seems this doesn't
work on MacOS, we get error 66, directory not empty. Didn't know you can't
rename a directory with files in it, you can on linux/windows. I can work
around that easily enough, just wasn't expecting it.

The reason lazylibrarian thinks postprocessing has failed: Unable to import
book to /Volumes/drive/eBooks/Library/Jean Baudrillard/  is not clear.
Seems lazylibrarian runs libraryscan on that directory and doesn't find
anything new in there (0 new and 6 modified books). I will have to think on
that a bit.

The final quirk is that lazylibrarian is remarking the "failed" download as
"wanted" so we try and download another copy from somewhere else. The
"failed" one will be blacklisted. This is because sometimes the download
will be passworded or faulty, or only contains formats you don't want.

**Comment by Telecart** [comment]
Interesting. I didn't know you couldn't rename a directory in OSX which contains files either!
I think earlier on this thread you suggested changing calibre to not read metadata from the files. I assume this would help? Not ideal for me as I do add from other sources at this point but as I shift over to LL it'll make more sense for this to be streamlined.

FWIW it just happened again with another book. Looks much the same, as it just repeats itself again and again. Manually fixed the metadata, deleted the duplicate, and refreshed the author and LL marked it as done (bubble changed to "open" form "wanted").

**Comment by philborman** [comment]
Shouldn't need to change calibre to not read metadata from the files now,
we pass calibre the correct metadata afterwards, so solves that issue.  I
just need to figure out why the libraryscan of
/Volumes/drive/eBooks/Library/Jean Baudrillard/ is not finding the new
book.  Libraryscan counts how many new/modified books it finds, and if
there is a new book in the folder it thinks postprocessing succeeded. If no
new book it failed. Calibre has imported it, tells us it's calibre ID 195,
goodreads ID 22613. We scan the calibre directory and think it's not
there???

Looking at the code we seem to think status is "Open" as anything else will
set the "new book" flag. "Wanted" certainly should flag it as a new book.
Is there more than one entry in lazylibrarian database for that book? Just
can't see why we're missing it at the mo...

**Comment by Telecart** [comment]
Anything I can do in the meantime? Verbose logging doesn't seem to add much info unfortunately.

**Comment by philborman** [comment]
Just pushing a new version with more debugging messages in the postprocessor calibre section. Hopefully this will help track it down.

**Comment by Telecart** [comment]
Perfect. Will update as soon as I'm home.
