### ISSUE TITLE
base.html % endif

### ISSUE THREAD

**Issue by stoofz** [DobyTang/LazyLibrarian#461]
missing % endif on line #121 in base.html was causing 

SyntaxException: Unterminated control keyword: 'if' in file 'C:/LazyLibrarian/data/interfaces/default/base.html' at line: 96 char: 1

**Comment by sacretagent** [comment]
got same issue
Error !

SyntaxException: Unterminated control keyword: 'if' in file '/opt/lazylibrarian/data/interfaces/default/base.html' at line: 96 char: 1

**Comment by philborman** [comment]
Sorry about that, don't know how it crept in. Fixed now
