### ISSUE TITLE
SyntaxException: Unterminated control keyword: 'if' in file 

### ISSUE THREAD

**Issue by Gunrunner101** [DobyTang/LazyLibrarian#465]
The follow error I get after updating to the recent version. Any help would be much appreciated. 

> Error !

SyntaxException: Unterminated control keyword: 'if' in file '/home/lazyl/LazyLibrarian/data/interfaces/default/base.html' at line: 96 char: 1

<body> <div id="container"> <div id="ajaxMsg"></div> % if lazylibrarian.INSTALL_TYPE != 'win': % if not lazylibrarian.CURRENT_VERSION: <div id="updatebar"> You're running an unknown version of lazylibrarian. <a href="update">Update</a> or <a href="#" onclick="$('#updatebar').slideUp('slow');">Close</a> </div>
/home/lazyl/LazyLibrarian/mako/lexer.py, line 264:
self.control_line[-1].pos, self.filename)
/home/lazyl/LazyLibrarian/mako/template.py, line 657:
node = lexer.parse()
/home/lazyl/LazyLibrarian/mako/template.py, line 677:
generate_magic_comment=template.disable_unicode)
/home/lazyl/LazyLibrarian/mako/template.py, line 399:
filename)
/home/lazyl/LazyLibrarian/mako/template.py, line 322:
module = self._compile_from_file(path, filename)
/home/lazyl/LazyLibrarian/mako/lookup.py, line 321:
**self.template_args)
/home/lazyl/LazyLibrarian/mako/lookup.py, line 256:
return self._load(srcfile, uri)
/home/lazyl/LazyLibrarian/mako/runtime.py, line 793:
return lookup.get_template(uri)
/home/lazyl/LazyLibrarian/mako/runtime.py, line 762:
template = _lookup_template(context, uri, calling_uri)
/home/lazyl/LazyLibrarian/data/interfaces/default/index.html, line 1:
<%inherit file="base.html"/>
/home/lazyl/LazyLibrarian/mako/runtime.py, line 805:
ret = template.module._mako_inherit(template, context)
/home/lazyl/LazyLibrarian/mako/runtime.py, line 863:
(inherit, lclcontext) = _populate_self_namespace(context, tmpl)
/home/lazyl/LazyLibrarian/mako/runtime.py, line 829:
**_kwargs_for_callable(callable_, data))
/home/lazyl/LazyLibrarian/mako/template.py, line 445:
return runtime._render(self, self.callable_, args, data)
/home/lazyl/LazyLibrarian/lazylibrarian/webServe.py, line 50:
return template.render(**kwargs)

>

**Comment by philborman** [comment]
Yes there is a bug.  Fixed it yesterday.
Easiest way to get round it is to edit your config.ini
Change http_look from default to bookstrap
That will get you up and running. You can then go to the config page,
 check for latest version (which includes the fix) and update.
