### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by jestes** [DobyTang/LazyLibrarian#466]
Would I be possible to have a backup of settings and authors that can be saved offline.?

**Comment by philborman** [comment]
There is no offline backup built into the program, but all your settings are stored in config.ini which you can easily backup offline. You can also save a wishlist of wanted books. 
Everything else is just stored in lazylibrarian.db which can be saved offline or rebuilt from your existing books and magazines.
Depending what you are running lazylibrarian on, you can probably use a cron job or similar to backup  config.ini and lazylibrarian.db to a google drive or dropbox folder.

**Comment by jestes** [comment]
Thanks for the support I will set up.  I lost all settings author data when I reloaded the package to fix the last error.  Next time I will have a backup

**Comment by philborman** [comment]
Sorry about that.
New version has a command line switch to force an update if anything
similar happens again.

LazyLibrarian.py --update

You could also use
LazyLibrarian.py --datadir=whatever_your_home_directory_is
so your config and database are kept separate from the program

Phil
