### ISSUE TITLE
Error on my RSS search

### ISSUE THREAD

**Issue by maxcore** [DobyTang/LazyLibrarian#467]
````
2016-09-09 21:51:58	DEBUG	No data returned from http://******t/rss.php?feed=sdl&cat=23&rsskey=*************
2016-09-09 21:51:58	ERROR	Error opening url: global name 'feedparser' is not defined
2016-09-09 21:51:58	DEBUG	[IterateOverRSSSites] - http://*********/rss.php?feed=sdl&cat=23&rsskey=******************
```````
hi phill
its why i found nothing in my rss feed ?

**Comment by maxcore** [comment]
@philborman ok now i have no error but nothing found  in my Rss .. i test a book is already on the feed and lazy find nothing .. strange ?

**Comment by philborman** [comment]
Just added "full" and "short" booksearch to rss, used to be more strict
name matching. Try with the new version. If it still fails to find a book
you know is there, please post a debug log

**Comment by maxcore** [comment]
````
2016-09-10 11:02:08	DEBUG	RSS http://******* returned 25 results
2016-09-10 11:02:08	DEBUG	Parsing results from http://ethor.net/rss.php?feed=sdl&cat=23&rsskey=************
2016-09-10 11:02:08	DEBUG	[IterateOverRSSSites] - http://********t/rss.php?feed=sdl&cat=23&rsskey=***************
2016-09-10 11:02:08	INFO	RSS Searching for 1 book
`````

nothing found ..

you need more info ?

**Comment by philborman** [comment]
looks like it got 25 results, but the book you wanted was not one of those
25. You should have lines like...
10-Sep-2016 17:19:06 - DEBUG :: SEARCHRSS : Parsing results from
https://api.nzbgeek.info/rss?t=7020&num=10&r=xxxxxxxxxxxxxxxxxxxxxxx
10-Sep-2016 17:19:06 - DEBUG :: SEARCHRSS : RSS http://api.nzbgeek.info/
returned 10 results
10-Sep-2016 17:19:06 - DEBUG :: SEARCHRSS : RSS Author/Title Match: 11/30
for Star Trek DTI Time Lock Christopher L Bennett retail epub
10-Sep-2016 17:19:06 - DEBUG :: SEARCHRSS : RSS Author/Title Match: 24/10
for Sybil Bartel Uncompromising Neil epub
10-Sep-2016 17:19:06 - DEBUG :: SEARCHRSS : RSS Author/Title Match: 25/32
for Rob Harrell Life of Zarf Troll Overboard retail epub
10-Sep-2016 17:19:06 - DEBUG :: SEARCHRSS : RSS Author/Title Match: 19/33
for S C Stephens Furious Rush epub
10-Sep-2016 17:19:06 - DEBUG :: SEARCHRSS : RSS Author/Title Match: 19/34
for Michele Torrey Chronicles of Courage Voyage of Ice retail epub
10-Sep-2016 17:19:06 - DEBUG :: SEARCHRSS : RSS Author/Title Match: 18/36
for Michele Torrey Chronicles of Courage Voyage of Midnight retail epub
10-Sep-2016 17:19:06 - DEBUG :: SEARCHRSS : RSS Author/Title Match: 18/32
for Michele Torrey Chronicles of Courage Voyage of Plunder retail epub
10-Sep-2016 17:19:06 - DEBUG :: SEARCHRSS : RSS Author/Title Match: 100/100
for Mary Woodbury Flight of the Tiger Moth retail epub
10-Sep-2016 17:19:06 - DEBUG :: SEARCHRSS : RSS Author/Title Match: 27/42
for Michele Torrey To the Edge of the World retail epub
10-Sep-2016 17:19:06 - DEBUG :: SEARCHRSS : RSS Author/Title Match: 15/18
for B B Hamel Barone Crime Family Bow Down epub
10-Sep-2016 17:19:06 - INFO :: SEARCHRSS : Best RSS match (98%): Mary
Woodbury Flight of the Tiger Moth retail epub using full search

where "Best match" is the one it will download

**Comment by maxcore** [comment]
ok my feed its not a nzb rss feed its a torrent rss feed

**Comment by philborman** [comment]
Should not matter, the code that looks for name-matches does not care 
about the source.

Once you find a matching name we send it to a different downloader, nzb 
or tor

**Comment by maxcore** [comment]
give me your mail i will send you the feed with the book name

**Comment by philborman** [comment]
phil.borman@gmail.com
