### ISSUE TITLE
Request for libgen.io as a source.

### ISSUE THREAD

**Issue by idlesHand** [DobyTang/LazyLibrarian#471]
hi I don't code so don't know if it is technically feasible or worth the time to add support for libgen. I personally think the site is great. I tend to have much more luck finding technical and academic texts. Problem is it is not a torrent tracker as far as I can tell, I personally use direct downloads through browser but it does provide torrents files and magnet links. Great work so far. Lovely LazyLibrarian. 👍

**Comment by philborman** [comment]
It looks like it has an rss feed for recent additions, that can be used,
but I can't find any documentation on it's api for search purposes.

**Comment by budbudha** [comment]
Thanks for taking a look. A couple of things I found: this repository last updated only 5 months ago and has a libgen  api in python, apparently (although I looked at it all and it appears to be doing something with libgen, it's mirrors, the urls, fields for author, date, title etc which to my non programming mind seems pertinent but could all be for totally unrelated/unusable results ) https://github.com/mmarquezs/libgen-python-api 

Also I joined their forums and had a look around but all I could find regarding APIs is to do with syncing local databases with the official one.

**Comment by philborman** [comment]
Actually I have found a simple search page, we can scrape  data from the
table of results like we do for some of the other torrent providers. Just
testing it now.

**Comment by philborman** [comment]
ok, we can't use the torrent links from libgen as they don't provide the filename, just an md5 reference. You end up downloading books with filenames like 1F60A0ABA50D9CA07EC36C5CF5DD885A
so when that arrives in the download directory we have no idea what the file is called or what type it is (mobi, epub, pdf)
The direct download links look more promising though.
