### ISSUE TITLE
Torrent blackhole creates magnets instead of torrent files

### ISSUE THREAD

**Issue by mlg9000** [DobyTang/LazyLibrarian#476]
All torrent clients I am aware of require .torrent files to in their watch folders to work.  Magnet files are just ignored.  You can put together your own scripts to convert them, but LL should really do that for you.

**Comment by philborman** [comment]
The torrent downloaders all have libraries now to access them directly, 
so using blackhole should not really be necessary. Plus when we grab 
files to download we don't know what downloaders might be available and 
enabled, could be on a different machine, so if there is a magnet and a 
torrent available we choose the magnet. Maybe we should choose the 
torrent instead?

I don't know how to convert a magnet to a torrent in python - could look 
into it though.

**Comment by mlg9000** [comment]
>  The torrent downloaders all have libraries now to access them directly,

There isn't a downloader for rtorrent which is a pretty big one.

> Maybe we should choose the torrent instead?,

That would definitely make the blackhole work but I'm not sure what the implications are otherwise.

> I don't know how to convert a magnet to a torrent in python - could look into it though.

There are python programs like https://github.com/danfolkes/Magnet2Torrent which do this (which is what I use to convert the magnet files to torrents... works sometimes).  I think that CP/Sickrage and maybe some of the others use iptorrents.org or similar to convert the hash into a torrent.

**Comment by philborman** [comment]
A few problems...
Some of the torrent providers only provide magnet links, not torrent files.
Some provide both, but we only have one slot for storage so have to choose
which.

magnet2torrent uses an architecture specific library which is a problem as
we would either need to get the user to install the library for their
architecture, or provide and ship  several different libraries, or provide
some sort of compilation script. Probably not worth the effort as most
torrent downloaders (rtorrent included) natively handle magnet links

rtorrent api documentation is proving a stumbling block. Can't see how to
do the simplest thing with the xmlrpc, just need to be able to add a new
torrent and get an "ok" response back.
