### ISSUE TITLE
.flac not renaming properly.

### ISSUE THREAD

**Issue by lavaguy1** [DobyTang/LazyLibrarian#479]
Hi,

I'm having an interesting problem with "optional" tags in the renaming patterns. When I use:

{CD$Disc - }$Track. $Artist - $Album [$Year] - $Title

in the Advanced Settings "file format" field, the {CD$Disc - } never triggers. But, if I set the re-encoding options to "on" (for mp3 versions of the .flacs), then it works.

ex. Flac files:
01. Prince - Sign “☮” the Times [1987] - Sign O' The Times.flac
01. Prince - Sign “☮” the Times [1987] - U Got The Look.flac

mp3 files:
CD1 - 01. Prince - Sign “☮” the Times [1987] - Sign “☮” the Times.mp3
CD2 - 10. Prince - Sign “☮” the Times [1987] - U Got the Look.mp3

In the original folder, the .flac files (including ID3 tags) are:

101-prince-sign_o_the_times.flac (track tagged as 1, disc number is empty in ID3)
201-prince-u_got_the_look.flac (track tagged as 1, disc number is empty in ID3

and are in a single folder. 

My goal with the {CD$Disc - } is to have it put CD1 etc. at the beginning of multi-disc albums, but nothing if there is only a single disc. Which seems to ignore the "{}" optional tags and numbers sequentially with the re-encoded mp3 files. Am I doing something wrong?

Currently using Version: 5a2082ede523160f853e09731a3ca1b1a851294e of Headphones on Ubuntu Server.

Thanks for your help!

**Comment by philborman** [comment]
Ah, think you are on the wrong list :-)

**Comment by lavaguy1** [comment]
geez! so sorry! my mistake.
