### ISSUE TITLE
Bug with transmission

### ISSUE THREAD

**Issue by maxcore** [DobyTang/LazyLibrarian#481]
When i get a magazine from Torrent source transmission get the Magazine with no problem .

The problem is all my stuff in transmission move in the magazine folder was create .

My snatched magazine is: 
![capture d ecran 2016-09-20 21 45 05](https://cloud.githubusercontent.com/assets/4043787/18694853/97bf6f4c-7f7b-11e6-8a00-36f3594a09a2.png)

look my all ready download stuff : 
![capture d ecran 2016-09-20 21 44 44](https://cloud.githubusercontent.com/assets/4043787/18694863/a819e78c-7f7b-11e6-8c76-ec5d5970cea2.png)

![capture d ecran 2016-09-20 21 44 13](https://cloud.githubusercontent.com/assets/4043787/18694868/add6ea80-7f7b-11e6-9473-2f815546b881.png)

![capture d ecran 2016-09-20 21 47 45](https://cloud.githubusercontent.com/assets/4043787/18694891/e39d2170-7f7b-11e6-978c-0728c8ac46fc.png)

all my stuff was move it to : /volume1/Downloads/EBOOK/Star Systeme  16 Septembre 2016

**Comment by philborman** [comment]
Should only move valid magazine type, so any pdf in that folder. Can you post a debug log of when the postprocessor runs

**Comment by philborman** [comment]
ok, found the problem. Transmission was returning a hash instead of an id. Fixed now, also reworked single files so they have a temporary folder, which fixes the "transmission doesn't do labels" problem.ç

You might have to restart transmission daemon to reset it's download folder

**Comment by maxcore** [comment]
very nice job work perfect thx @philborman !!!
