### ISSUE TITLE
init.d

### ISSUE THREAD

**Issue by Riechao** [DobyTang/LazyLibrarian#482]
I'm trying to copy the initd on Ubuntu to get this to start with the server, but I can't seem to get the service to work. I edited the default to point to my git clone and installed it with update-rc but it errors:

 lazyLibrarian.service - LSB: starts instance of LazyLibrarian
   Loaded: loaded (/etc/init.d/lazyLibrarian; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2016-09-21 08:13:22 JST; 4s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 4301 ExecStart=/etc/init.d/lazyLibrarian start (code=exited, status=1/FAILURE)
lazyLibrarian[4301]:  * LazyLibrarian: Can't read settings, aborting. See /etc/default/lazylibrarian

**Comment by philborman** [comment]
Which version of ubuntu are you running on, in case it's relevant. It's 
working here on 16.04 and 15.10 but haven't tried any other versions.

I just did this...

sudo cp /opt/lazylibrarian/ubuntu.default /etc/default/lazylibrarian

sudo cp /opt/lazylibrarian/ubuntu.initd /etc/init.d/lazylibrarian

Should just work out of the box (as long as your git clone is in 
/opt/lazylibrarian). If not you just need to edit 
/etc/default/lazylibrarian  so the APP_PATH points to the right place. 
Note that paths are case sensitive. In your message you have 
/etc/init.d/lazyLibrarian  ( lazy Librarian ) mixed case is probably wrong.

**Comment by Riechao** [comment]
I git cloned to ~/.lazyLibrarian 
(*digression* sorry I like the ... ... ... not quite camel case? I forget what it's called */digression* ) 
then I edited the default to point to /home/myuser/.lazyLibrarian for the paths
then tried to update-rc and failed, did it many times.... until my wife said it sounded like I was very angry at my keyboard.

**Comment by philborman** [comment]
The camelCase is fine as long as its intentional,  I use it for variable
and function names all the time, I just wondered if it was a typo. Ok,
what happens if you just type
sudo /etc/init.d/lazyLibrarian

Im not sure if recent Ubuntu still use update-rc  you might need to use
systemctl instead

**Comment by philborman** [comment]
Last message should say /etc/init.d/lazyLibrarian start

**Comment by Riechao** [comment]
I'll try again. 
I just did:
sudo update-rc.d -f lazyLibrarian remove
sudo rm /etc/default/lazyLibrarian 
sudo rm /etc/init.d/lazyLibrarian
and
sudo rm -rf /home/myuser/lazyLibrarian

**Comment by Riechao** [comment]
From .lazyLibrarian directory I'm doing:
 sudo cp init/ubuntu.default /etc/default/lazyLibrarian
 sudo cp init/ubuntu.initd /etc/init.d/lazyLibrarian
the edit /etc/default/lazyLibrarian to point to home/user/.lazyLibrarian:
APP_PATH=/home/user/.lazyLibrarian

# [optional] change to 1 to enable daemon
ENABLE_DAEMON=1

# [required] user or uid of account to run the program as:
RUN_AS=user

# [optional] change to 1 to enable updating from webinterface
# this changes ownership of /opt/lazylibrarian to user set @ RUN_AS
WEB_UPDATE=1

# [optional] full path to the configuration file of your choice;
# otherwise, the default location (~/.lazylibrarian) is used:
CONFIG=/home/user/.lazyLibrarian
APP_PATH=/home/user/.lazyLibrarian

# [optional] change to 1 to enable daemon
ENABLE_DAEMON=1

# [required] user or uid of account to run the program as:
RUN_AS=user

# [optional] change to 1 to enable updating from webinterface
# this changes ownership of /opt/lazylibrarian to user set @ RUN_AS
WEB_UPDATE=1

# [optional] full path to the configuration file of your choice;
# otherwise, the default location (~/.lazylibrarian) is used:
CONFIG=/home/user/.lazyLibrarian

 $ sudo chmod a+x /etc/init.d/lazyLibrarian 
$ sudo update-rc.d lazyLibrarian defaults 
$ sudo service lazyLibrarian start

**Comment by philborman** [comment]
APP_PATH should be where the program is (where you put the git files)
CONFIG is ok as /home/user/.lazyLibrarian, that's where you will store your
config.ini and database

Might also need to edit the /etc/init.d/lazyLibrarian so it points to the
right settings file as it's expecting lowercase

**Comment by Riechao** [comment]
Thanks, that's probably what i missed!

**Comment by Riechao** [comment]
yep, it worked to change 3 lines from lowercase to lowerCamelCase. I'll add some authors later and see if it works. I think the init.d files should be updated to take more variables than just run_as... maybe the path too? anyway, thanks for your help, this seems solved
