### ISSUE TITLE
Unable to check Git for update

### ISSUE THREAD

**Issue by Gamer106** [DobyTang/LazyLibrarian#487]
Issue began recently, log shows:

2016-10-03 15:58:34	INFO	Unable to get latest version from GitHub
2016-10-03 15:58:34	WARNING	(getLatestVersion_FromGit) Could not get the latest commit from github

**Comment by philborman** [comment]
There have been a few reports of this behaviour, but I've been unable to track it down.
There is a lot more debugging code in the git routines now to try and locate the problem. 
If you go to the "logs" screen and turn debug logging on, then go to "config" and hit "check version" it will run the whole "connect to git and report back" routine and give much more info that should tell us what's going wrong.

**Comment by Gamer106** [comment]
Haha, I went to Logs to enable the debug option, and see that I'm 9 commits behind, so something fixed.
