### ISSUE TITLE
Add email notification

### ISSUE THREAD

**Issue by ezar** [DobyTang/LazyLibrarian#496]
Please add email notification!
Regards,

**Comment by philborman** [comment]
There is a version in my git at https://github.com/philborman/LazyLibrarian.git
with email notification  support. 
Only tested with ssl to gmail so far.  If you would like to give it a try and report back... 
If it checks out okay  I will push it to the master branch.

**Comment by ezar** [comment]
Seems works perfect! I'm using with gmail TLS.
Regards.

**Comment by philborman** [comment]
ok thanks for testing. Pushing it to master branch tonight.
