### ISSUE TITLE
Torznab and torrent client?

### ISSUE THREAD

**Issue by darknessgp** [DobyTang/LazyLibrarian#506]
I have Transmission setup and I believe working correctly, LazyLibrarian says it can connect successfully. I also have a torrent site setup in Torznab via Jackett.

However, when I search for a wanted book, I get the error message "No download method is set, use SABnzbd/NZBGet or blackhole, check config" with no real search happening. 

I would think my setup should work correctly. Why is LazyLibrarian thinking I should have NZB downloader when I'm using Torznab?

**Comment by philborman** [comment]
Torznabs use the same communication as nzb for searching, so use the same
code, but return torrents. Turning on an nzb downloader will suppress the
message without affect anything else so is a quick fix for now. I will have
a look at the code and see how to issue a more useful message.

**Comment by philborman** [comment]
Had a look at the code and it is just a warning message, you should still be able to search and get results. I will remove the message completely on the next release as it's not really needed.  Can you turn debug logging on to check the search happens?  I haven't used torznab for a while as they dropped all the free access sites,  so it's possible something is broken

**Comment by philborman** [comment]
The capability xml looks ok,  should parse.  Tricky to debug without a working torznab here. 
Can you try running lazylibrarian with debug from a terminal? 
If the search or capabilities thread crash you might get additional output in a terminal

**Comment by darknessgp** [comment]
Yes, there is a crash... Here's the output from running it with debug in terminal...
```
19-Oct-2016 19:49:40 - DEBUG :: SEARCHNZB : Parsing xml for capabilities of https://[redacted]/jackett/torznab/myanonamouse/api?t=caps&apikey=[redacted]
Exception in thread SEARCHNZB:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/software/LazyLibrarian/lazylibrarian/searchnzb.py", line 72, in search_nzb_book
    resultlist, nproviders = providers.IterateOverNewzNabSites(book, 'book')
  File "/software/LazyLibrarian/lazylibrarian/providers.py", line 192, in IterateOverNewzNabSites
    provider = get_capabilities(provider)
  File "/software/LazyLibrarian/lazylibrarian/providers.py", line 145, in get_capabilities
    if len(search):
TypeError: object of type 'NoneType' has no len()

```

**Comment by philborman** [comment]
ok, think this should be fixed now. Removed the redundant warning and fixed the ElementTree parsing problem that stopped reading capabilities. Please check this works for you as I don't have a working torznab to try. Thanks.

**Comment by darknessgp** [comment]
I can confirm that the latest release corrects both the issues I was having. Thank you!
