### ISSUE TITLE
extratorrent.cc SSL Handshake Failure

### ISSUE THREAD

**Issue by famewolf** [DobyTang/LazyLibrarian#510]
I'm seeing this in the log for every call to extratorrent.cc:

21-Oct-2016 04:38:18 - WARNING :: SEARCHTOR : Error fetching torrent from url: http://extratorrent.cc/download/5068489/Jay+Allan+-+Shadows+of+the+Gods+%28Crimson+Worlds+Refugees+%232%29.torrent, [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:581)

At first I thought it might be an issue with using privoxy as an http proxy inside lazylibrarian so I removed it but the error still occurred.

**Comment by philborman** [comment]
Interesting. Why is it using ssl at all, it's a http connection, not https 
There are some odd compatibility issues between the various ssl versions.
Do you know what versions of python and ssl you are running,  and what platform? 
There was another user with an ssl issue on a nas device that just needed the ssl library updating.

**Comment by famewolf** [comment]
I'm running lazylibrarian in a jail under freenas so basically freebsd....I'm doing an update of all packages which included an update of python27: 2.7.11_1 -> 2.7.12. Looks like openssl is openssl-1.0.2j,1 

The problem appears to be intermittent as well.  No idea why openssl is involved as 1/2 the time it was using an http proxy to make the requests.   A brief cat of the log with grep on extratorrent.cc shows some getting the error and others not:

22-Oct-2016 16:50:16 - DEBUG   :: CRON-SEARCHTOR : [IterateOverTorrentSites] - extratorrent.cc
22-Oct-2016 16:50:17 - DEBUG   :: CRON-SEARCHTOR : Parsing results from <a href="http://extratorrent.cc/rss/?search=Jay++Allan+Shadows+of+the+Gods+%28Crimson+Worlds+Refugees+2%29&type=search&s_cat=2">Extratorrent</a>
22-Oct-2016 16:50:19 - WARNING :: CRON-SEARCHTOR : Error fetching torrent from url: http://extratorrent.cc/download/5068489/Jay+Allan+-+Shadows+of+the+Gods+%28Crimson+Worlds+Refugees+%232%29.torrent, [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:581)
22-Oct-2016 16:50:43 - DEBUG   :: CRON-SEARCHTOR : [IterateOverTorrentSites] - extratorrent.cc
22-Oct-2016 16:50:45 - DEBUG   :: CRON-SEARCHTOR : Parsing results from <a href="http://extratorrent.cc/rss/?search=Jay++Allan+Shadows+of+the+Gods&type=search&s_cat=2">Extratorrent</a>
22-Oct-2016 16:50:46 - WARNING :: CRON-SEARCHTOR : Error fetching torrent from url: http://extratorrent.cc/download/5068489/Jay+Allan+-+Shadows+of+the+Gods+%28Crimson+Worlds+Refugees+%232%29.torrent, [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:581)
22-Oct-2016 16:51:15 - DEBUG   :: CRON-SEARCHTOR : [IterateOverTorrentSites] - extratorrent.cc
22-Oct-2016 16:51:16 - DEBUG   :: CRON-SEARCHTOR : Parsing results from <a href="http://extratorrent.cc/rss/?search=Jay++Allan+Tombstone+%28Crimson+Worlds+0.5%29&type=search&s_cat=2">Extratorrent</a>
22-Oct-2016 16:51:43 - DEBUG   :: CRON-SEARCHTOR : [IterateOverTorrentSites] - extratorrent.cc
22-Oct-2016 16:51:44 - DEBUG   :: CRON-SEARCHTOR : Parsing results from <a href="http://extratorrent.cc/rss/?search=Jay++Allan+Tombstone&type=search&s_cat=2">Extratorrent</a>
22-Oct-2016 16:52:16 - DEBUG   :: CRON-SEARCHTOR : [IterateOverTorrentSites] - extratorrent.cc
22-Oct-2016 16:52:18 - DEBUG   :: CRON-SEARCHTOR : Parsing results from <a href="http://extratorrent.cc/rss/?search=Jay++Allan+Funeral+Games+%28Far+Star+Trilogy+3%29&type=search&s_cat=2">Extratorrent</a>
22-Oct-2016 16:52:49 - DEBUG   :: CRON-SEARCHTOR : [IterateOverTorrentSites] - extratorrent.cc
22-Oct-2016 16:52:50 - DEBUG   :: CRON-SEARCHTOR : Parsing results from <a href="http://extratorrent.cc/rss/?search=Jay++Allan+Funeral+Games&type=search&s_cat=2">Extratorrent</a>
22-Oct-2016 16:53:12 - DEBUG   :: CRON-SEARCHTOR : [IterateOverTorrentSites] - extratorrent.cc
22-Oct-2016 16:53:13 - DEBUG   :: CRON-SEARCHTOR : Parsing results from <a href="http://extratorrent.cc/rss/?search=Jay++Allan+Enemy+in+the+Dark+%28Far+Star+Trilogy+2%29&type=search&s_cat=2">Extratorrent</a>
22-Oct-2016 16:53:34 - DEBUG   :: CRON-SEARCHTOR : [IterateOverTorrentSites] - extratorrent.cc
22-Oct-2016 16:53:35 - DEBUG   :: CRON-SEARCHTOR : Parsing results from <a href="http://extratorrent.cc/rss/?search=Jay++Allan+Enemy+in+the+Dark&type=search&s_cat=2">Extratorrent</a>
22-Oct-2016 16:53:58 - DEBUG   :: CRON-SEARCHTOR : [IterateOverTorrentSites] - extratorrent.cc
22-Oct-2016 16:54:00 - DEBUG   :: CRON-SEARCHTOR : Parsing results from <a href="http://extratorrent.cc/rss/?search=Jay++Allan+Blackhawk+%28Far+Stars+Legends+1%29&type=search&s_cat=2">Extratorrent</a>
22-Oct-2016 16:54:31 - DEBUG   :: CRON-SEARCHTOR : [IterateOverTorrentSites] - extratorrent.cc
22-Oct-2016 16:54:34 - DEBUG   :: CRON-SEARCHTOR : Parsing results from <a href="http://extratorrent.cc/rss/?search=Jay++Allan+Blackhawk&type=search&s_cat=2">Extratorrent</a>
22-Oct-2016 16:55:05 - DEBUG   :: CRON-SEARCHTOR : [IterateOverTorrentSites] - extratorrent.cc
22-Oct-2016 16:55:06 - DEBUG   :: CRON-SEARCHTOR : Parsing results from <a href="http://extratorrent.cc/rss/?search=Jay++Allan+Homefront+%28Portal+Wars+3%29&type=search&s_cat=2">Extratorrent</a>
22-Oct-2016 16:55:33 - DEBUG   :: CRON-SEARCHTOR : [IterateOverTorrentSites] - extratorrent.cc
22-Oct-2016 16:55:34 - DEBUG   :: CRON-SEARCHTOR : Parsing results from <a href="http://extratorrent.cc/rss/?search=Jay++Allan+Homefront&type=search&s_cat=2">Extratorrent</a>
22-Oct-2016 16:56:06 - DEBUG   :: CRON-SEARCHTOR : [IterateOverTorrentSites] - extratorrent.cc
22-Oct-2016 16:56:07 - DEBUG   :: CRON-SEARCHTOR : Parsing results from <a href="http://extratorrent.cc/rss/?search=Jay++Allan+Stars++Empire+2&type=search&s_cat=2">Extratorrent</a>
22-Oct-2016 16:56:35 - DEBUG   :: CRON-SEARCHTOR : [IterateOverTorrentSites] - extratorrent.cc
22-Oct-2016 16:56:39 - DEBUG   :: CRON-SEARCHTOR : Parsing results from <a href="http://extratorrent.cc/rss/?search=Thomas+DePrima+Clidepp+Deja+Vu+%28A+Galaxy+Unknown+-+Border+Patrol+3%29&type=search&s_cat=2">Extratorrent</a>
22-Oct-2016 16:57:05 - DEBUG   :: CRON-SEARCHTOR : [IterateOverTorrentSites] - extratorrent.cc
22-Oct-2016 16:57:06 - DEBUG   :: CRON-SEARCHTOR : Parsing results from <a href="http://extratorrent.cc/rss/?search=Thomas+DePrima+Clidepp+Deja+Vu&type=search&s_cat=2">Extratorrent</a>
22-Oct-2016 16:57:32 - DEBUG   :: CRON-SEARCHTOR : [IterateOverTorrentSites] - extratorrent.cc
22-Oct-2016 16:57:33 - DEBUG   :: CRON-SEARCHTOR : Parsing results from <a href="http://extratorrent.cc/rss/?search=Heather+Brewer+Soulbroken+%28Legacy+of+Tril+2%29&type=search&s_cat=2">Extratorrent</a>
22-Oct-2016 16:57:57 - DEBUG   :: CRON-SEARCHTOR : [IterateOverTorrentSites] - extratorrent.cc
22-Oct-2016 16:57:58 - DEBUG   :: CRON-SEARCHTOR : Parsing results from <a href="http://extratorrent.cc/rss/?search=Heather+Brewer+Soulbroken&type=search&s_cat=2">Extratorrent</a>

**Comment by philborman** [comment]
Not sure if it's coincidence, but all the ones that failed have a hash character in them , eg Crimson Worlds Refugees #2  where the hash gets converted to %23. Not sure what we can do about it though, as the hash character is part of the torrent name. Maybe the hash encoding needs looking at?

**Comment by famewolf** [comment]
So perhaps it's causing the title to be broken with the remainder falling into the ssl logic?  Would putting the title in quotes or using logic to insert escape characters before the #'s in the title help?

**Comment by philborman** [comment]
Just tried the link for crimson worlds from a browser and got this... 
![screenshot_20161025-155922](https://cloud.githubusercontent.com/assets/12158777/19688996/2c288ed2-9acc-11e6-8e01-4ddac8ea93b3.png)

So it seems the http redirects to a https with a faulty certificate. I guess we can't do anything about it, it's a broken link.
