### ISSUE TITLE
error processing name

### ISSUE THREAD

**Issue by maxcore** [DobyTang/LazyLibrarian#511]
hey phill , i have problem with this files name : Jeux Video Magazine N190 - Novembre 2016 lazy cant process this file .

```
2016-10-23 13:20:17	WARNING	Jeux Video Magazine N190 - Novembre 2016 was sent to transmission 10 hours ago
2016-10-23 13:20:17	INFO	No snatched books/mags have been found
2016-10-23 13:20:17	DEBUG	Closest match (86%): /volume1/Downloads/EBOOK/Video Gamer - Novembre 2016
2016-10-23 13:20:17	DEBUG	Snatched torrent Jeux Video Magazine N190 - Novembre 2016 is not in download directory
2016-10-23 13:20:17	DEBUG	Looking for Jeux Video Magazine N190 - Novembre 2016 in /volume1/Downloads/EBOOK
2016-10-23 13:20:17	INFO	Checking 45 downloads for 1 snatched file
2016-10-23 13:20:17	DEBUG	Checking [/volume1/Downloads/EBOOK] for files to post process
````

**Comment by philborman** [comment]
Did the file get downloaded by transmission? 
If so,  is it in the right directory and under the right name,  as lazylibrarian thinks the file is not there.

**Comment by maxcore** [comment]
yes the file get download by transmission and this is from torrent and only this name file was not processs

**Comment by maxcore** [comment]
![capture d ecran 2016-10-24 20 31 46](https://cloud.githubusercontent.com/assets/4043787/19668877/ebca63d6-9a28-11e6-992f-c3279d4452ac.png)
humm number + month not a good mix ?

**Comment by maxcore** [comment]
strange : admin@NAS-MAXCORE:/volume1/@appstore/lazylibrarian/var$ sqlite3 lazylibrarian.dbError: unable to open database "lazylibrarian.db": unable to open database file

**Comment by philborman** [comment]
Not sure where the database is on your system,  same folder as the config.ini file usually.

**Comment by philborman** [comment]
Seems we asked for Jeux Video Magazine N190 - Novembre 2016
and were sent Jeux Vidéo magazine No 190 000000.pdf
LazyLibrarian does not realise these are the same,  not sure if I would either ;-)
Transmission should have sent us the new name,  but I would like to check the database to be sure.

**Comment by philborman** [comment]
Not sure where the database is on your system,  same folder as the
config.ini file usually.

**Comment by philborman** [comment]
yes, it says it's not in downloads. Is it there, but under a different name?

**Comment by maxcore** [comment]
the torrent name is : Jeux Vidéo magazine N°190 000000.pdf.torrent

but on the site the name of the torrent is Jeux Vidéo Magazine N°190 - Novembre 2016 , the uploade has not put the good name on the torrent file , i think was the bug .

**Comment by philborman** [comment]
Is the file still in your download directory and still in transmission
I so, we can try some new rename code

**Comment by maxcore** [comment]
ok , tell me what i can do

**Comment by philborman** [comment]
New version in my git with extra debugging code. Please run "Force postprocessing" from the magazine page and send the log output.

**Comment by maxcore** [comment]
humm @philborman  its hard to do its a RSS snatch and i use your git on my mac .. you can put on the original git ?

**Comment by philborman** [comment]
Pushed to DobyTang git. Let me know if it works!

Also - do you have deluge or qbittorrent on your Synology?  
Another synology user is trying to get libtorrent installed, which I think might be included in the synology builds.

**Comment by maxcore** [comment]
I try when i come home in few minutes

**Comment by maxcore** [comment]
![capture d ecran 2016-10-28 22 13 29](https://cloud.githubusercontent.com/assets/4043787/19826574/1c3e9394-9d5c-11e6-947a-83dbfc7328d3.png)

**Comment by maxcore** [comment]
yes i have deluge on my synology but i dont use now , you need to do some test ?

**Comment by philborman** [comment]
Just one quick test if you don't mind. Save this as "test.py" and run 
it  "python test.py".

I'm hoping it says "pass"  ;-)


#!/usr/bin/python
try:
     import libtorrent
     print "pass"
except:
     print "fail"

**Comment by philborman** [comment]
This is the problem...

 >>  getTorrentFolder: No response from transmission

I will have to think about it.

**Comment by philborman** [comment]
ok, fixed it in the next release, but it won't correct any that are already downloaded with the wrong name. 
Transmission changes the filename when the torrent completes. Easiest fix for you is to manually rename the downloaded file to Jeux Vidéo Magazine N°190 - Novembre 2016  so lazylibrarian matches the name properly.

**Comment by maxcore** [comment]
admin@NAS-MAXCORE:/tmp$ python test.py
fail
admin@NAS-MAXCORE:/tmp$

**Comment by philborman** [comment]
That's a shame. Deluge must keep its own private copy of libtorrent. I wonder if we can just copy it?
Do you have "locate" on the synology?  If so, could you try "locate libtorrent"

**Comment by maxcore** [comment]
admin@NAS-MAXCORE:~$ locate libtorrent
-sh: locate: command not found
admin@NAS-MAXCORE:~$
