### ISSUE TITLE
Support Synology Download Station

### ISSUE THREAD

**Issue by overdrive69** [DobyTang/LazyLibrarian#512]
Hello I installed LL an a Synology NAS, like many other people here I think.
So it would be nice if LL supports the Synology Download Station.

For example, Sickrage supports the download station. Maybe the code from there can be used.

**Comment by maxcore** [comment]
+1

**Comment by philborman** [comment]
Very hard to do without a synology to test it on.  The sickrage code is a good starting point but would need quite a bit of modification to work with lazylibrarian

**Comment by overdrive69** [comment]
If you consider to include it, for sure i can test, provide logs and so on.

**Comment by philborman** [comment]
I am away for a few days but might look into this when I get back

**Comment by overdrive69** [comment]
Do you had time to check the sickrage implementation of the synology download station?
Download station supports magnet links when they are send direkt to the downloade station and not via a watch folder (like blackhole).

**Comment by philborman** [comment]
Yes that's right, most torrent downloaders these days accept magnet links.
The only one we have problems with is rtorrent.  It should be ok, but just
stops the transfer once the magnet is resolved. Can't figure out why, so we
convert magnet to torrent to get round the problem. All the other
downloaders we support in lazylibrarian are fine.

I had a look at the sickrage code, looks like we should be able to get
download station support but it will probably take a few attempts to get it
right.

We only need a few functions adding...
1. Auth - can we talk to it
2. Send magnet/torrent/nzb and get id returned
3. Get stats on a running download (name, percentage done)
4. Set download folder for torrent

I would like to try sending files to download station and checking the
responses. Torrent,  magnet and nzb, as it should handle all three.  Are
you willing to run some test code,  as I don't have a synology? If so,
email me on phil.borman@gmail.com and I will send you some small python
scripts to check I'm on the right track.

**Comment by overdrive69** [comment]
I am really to run some test. But i think this means a have to create the LL package for the Synology on my own. Because i use the LL package from https://synocommunity.com/package/lazylibrarian
 If this is the case, I first need to check/learn how to do this.

**Comment by philborman** [comment]
Not necessary yet. The first few tests will be a separate program.
Once it is tested and working I will add it to the main lazylibrarian

**Comment by philborman** [comment]
Added DiskStation support. Many thanks to @overdrive69  for all the days of testing and assisting with debugging

**Comment by overdrive69** [comment]
Thank you very much for this. I made an update and at the moment I test it directly :-)

**Comment by maxcore** [comment]
thx for this one @philborman
