### ISSUE TITLE
ERROR Unable to import libtorrent

### ISSUE THREAD

**Issue by overdrive69** [DobyTang/LazyLibrarian#513]
At the moment I use blackhole for downloading, but the conversion from magnet to torrent didnt work.
I get following errors when only magnet links are found.

`2016-10-25 01:26:37    ERROR   Failed to download torrent from BLACKHOLE, magnet:?xt=urn:btih:9a2ca754a11cbe9e109b2574cf8b0de88f385d28&dn=Stephen+King+-+Finders+Keepers+%28Bill+Hodges+Trilogy+%232%29&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969
2016-10-25 01:26:37 ERROR   Unable to import libtorrent, disabling magnet conversion`

**Comment by philborman** [comment]
Libtorrent is not shipped with lazylibrarian as it is architecture specific.  If your system does not have it installed as standard you will need to add it manually to do magnet conversion.

I don't know what system you are running lazylibrarian on,  but on linux your package manager most likely has libtorrent available.

**Comment by overdrive69** [comment]
Ok, thank you for your help.
A have i running on an Synology NAS DSM6.0 (Armadaxp).
I will search if a found a package to install.

**Comment by philborman** [comment]
Instructions for building libtorrent here,  could not find a package 

https://forum.synology.com/enu/viewtopic.php?f=38&t=21716&start=45

**Comment by philborman** [comment]
Libtorrent is not shipped with lazylibrarian as it is architecture
specific.  If your system does not have it installed as standard you will
need to add it manually to do magnet conversion.

I don't know what system you are running lazylibrarian on,  but on linux
your package manager most likely has libtorrent available.

**Comment by philborman** [comment]
Just out of curiosity, why are you using blackhole to download torrents rather than sending them straight to a torrent downloader?

**Comment by overdrive69** [comment]
Because I want to use Synology Download Station.

**Comment by philborman** [comment]
Ah, I see. So if we can get Download Station support in lazylibrarian you won't need the blackhole ;-)
I thought it was probably either a downloader we don't support yet, or a vpn issue.

Any luck finding or building libtorrent for synology?  It seems Download Station is built to use deluge for torrents, and deluge uses libtorrent (as does qbittorrent). Whoever built the deluge package for libtorrent probably put a libtorrent library in the package too. This means that somewhere on your synology there is a libtorrent library we can copy and use.

**Comment by overdrive69** [comment]
Yeah, thats right.
I installed delug and I had access to the webinterface. But I wasnt able to connect LL to it.
And I wasnt able to install libtorrent.

But any way, i didnt want to use BH or any ohter downloader in the long term.
So, lets talk about the integration of the synology download station in the right thread.
