### ISSUE TITLE
unable to set port on rTorrent

### ISSUE THREAD

**Issue by techitch** [DobyTang/LazyLibrarian#514]
It seems we're able to specify a port for the download client for all other services however we're lacking the option for rTorrent.

I get this error on "test":
`rTorrent login FAILED
Check debug log`

The debug unsurpisingly shows: 
`xmlrpclib error: [Errno 111] Connection refused`

I've also tried setting rtorrent_port in the config with no avail.

**Comment by philborman** [comment]
We talk to rtorrent via xmlrpc  so the port is set in the xmlrpc server, not in lazylibrarian.

It's a relatively new feature and the documentation is lagging behind.
so in /etc/apache2/apache2.conf put 
SCGIMount /RPC2 127.0.0.1:5000
and in .rtorrent.rc 
scgi_port = 127.0.0.1:5000
then in lazylibrarian config the rtorrent host is set to localhost (or you could put 127.0.0.1)

**Comment by philborman** [comment]
We talk to rtorrent via xmlrpc  so the port is set in the xmlrpc server, 
not in lazylibrarian.

It's a relatively new feature and the documentation is lagging behind.

so in /etc/apache2/apache2.conf put
SCGIMount /RPC2 127.0.0.1:5000
and in .rtorrent.rc
scgi_port = 127.0.0.1:5000
then in lazylibrarian config the rtorrent host is set to localhost (or 
you could put 127.0.0.1)

**Comment by philborman** [comment]
Documentation updated in wiki now.
