### ISSUE TITLE
Override old setting on magazines 

### ISSUE THREAD

**Issue by glberen** [DobyTang/LazyLibrarian#516]
Is there a way to override the the old setting in magazines so that LazyLibrarian will go ahead and download issues from the past couple of years? I didn't see anything in the UI or in the config file. 

Thanks!

**Comment by philborman** [comment]
No there isn't, but old issues that the searches found are listed in the "past issues" tab.
You can select them for download from there.

**Comment by glberen** [comment]
That's perfect. Thank you! Sorry I didn't suss that out myself.
