### ISSUE TITLE
Unable to get NZBGet and Transmission to work

### ISSUE THREAD

**Issue by kcprophecy** [DobyTang/LazyLibrarian#517]
Hi, I just installed lazylibrarian on ubuntu 16.04 and ran into a problem when trying to configure NZBGet and Tranmission, all are on the same box.

I have tried multiple ways of adding nzbget using localhost, 127.0.0.1, IP and no matter what combination I do I always get the same error:

"ERROR	Please check your NZBget host and port (if it is running). NZBget is not responding to this combination: [Errno -5] No address associated with hostname"

Debug shows same error. Everything is working with NZBGet, have headphones and mylar working fine with it.

I then tried to configure transmission and the error I get when configuring this is:

"Request raised exception: Invalid URL u'http://:0//transmission/rpc': No host supplied"

Any assistance would be much appreciated!

**Comment by philborman** [comment]
I guess this is the response from the "test"  buttons.  If so,  it looks like you haven't saved the config changes after entering the host and port values? 
LazyLibrarian won't update to use the new values until you save them.

**Comment by overdrive69** [comment]
I think the reply wasnt for me.


Gesendet: Mittwoch, 02. November 2016 um 09:46 Uhr
Von: philborman <notifications@github.com>
An: DobyTang/LazyLibrarian <LazyLibrarian@noreply.github.com>
Betreff: Re: [DobyTang/LazyLibrarian] Unable to get NZBGet and Transmission to work (#517)


I guess this is the response from the "test" buttons. If so, it looks like you haven't saved the config changes after entering the host and port values?
LazyLibrarian won't update to use the new values until you save them.

**Comment by kcprophecy** [comment]
LOL thanks man, should of caught that. Appreciate you taking the time to respond, everything is working fine!
