### ISSUE TITLE
rTorrent

### ISSUE THREAD

**Issue by sea3pea0** [DobyTang/LazyLibrarian#522]
I haven't been able to get rTorrent working for me other than using a blackhole. It probably has something to do with the way my rTorrent is set up. The way I set it up with other apps such as couchpotato or sonarr is: 
host:
localhost
port:
443
url path:
user/sea3pea0

I've tried various different ways to configuer LL such as putting https://localhost/user/sea3pea0, but haven't got anything to work. Any suggestions or perhaps is there something that can easily be changed to accommodate this kind of rTorrent configuration? Thanks

**Comment by philborman** [comment]
I followed the guide below to get rtorrent working.
I tried the method you describe first, as it should work, but I just kept getting "connection refused" errors.
Would be better if we could do it the same way as the other torren downloaders. The actual commands sent the rtorrent are the same, just the method of connection is different. May have been a problem with my rtorrent config file?  How do you define port, user, password in your rtorrent.rc ?
 
https://github.com/rakshasa/rtorrent/wiki/RPC-Setup-XMLRPC

**Comment by sea3pea0** [comment]
My mistake, I meant rutorrent, not rtorrent. In my rtorrent.rc I have: scgi_port = 127.0.0.1:5000. I'm using apache2 to serve rutorrent. 
So if I followed the rtorrent guide and put "ProxyPass /RPC2 scgi://127.0.0.1:5000" in my sites apache config file and added basic auth to protect /RPC2 then it should work for me if I filled in "https://mysite.com" for host? Or would I put  "https://mysite.com/RPC2"? Will LL work with SSL? I will mess around a little bit with these later and report back about what I get working. I'm sure my problem was that I missed the fact that LL was connecting to rtorrent and not rutorrent.

Thanks for looking into this for me

**Comment by philborman** [comment]
It looks like rtorrent have updated their guide recently. When I wrote the code for lazylibrarian it didn't have different settings for apache 2.2 and apache 2.4, just one apache setting
SCGIMount /RPC2 127.0.0.1:5000
which is what I've got in my apache2.conf even though I'm on 2.4
For lazylibrarian I just put host as localhost  (no http(s) or /RPC2) and I didn't bother with any auth as its only accessible from localhost, not listening on other interfaces. Another user has reported it works with basic auth though. I guess you use .htaccess files for this?  Not sure about ssl either. LL works with ssl on torrent providers that need it, so it might be worth a try, but I guess easiest toget it working "vanilla" first. Would be good to have feedback on what works and what doesn't.

Easiest way to check it's working is to start rtorrent with scgi_port = 127.0.0.1:5000 
then from a terminal  
xmlrpc localhost system.client_version
rTorrent should report it's version number

**Comment by sea3pea0** [comment]
When I tried that from the command line I get:

Failed.  Call failed.  HTTP response code is 302, not 200.  (XML-RPC fault code -504)

However if I enter this in the terminal:

xmlrpc https://myhost.com/user/sea3pea0 system.client_version

I get:

Result:

String: '0.9.6'

I have a feeling since the url path isn't the standard /RPC2, that's what is causing the problem. If there were an option to change that it might work as long as LL doesn't mind that it's accessed through port 443/SS

This is what I have in my apache.conf file regarding rtorrent:

SCGIMount /user/sea3pea0 127.0.0.1:5000

**Comment by philborman** [comment]
Easy enough to try.
In lazylibrarian config, put rtorrent host as  https://myhost.com/user/sea3pea0 
LL uses the host as supplied, unless user and pass are defined so leave those blank, otherwise LL will change it to https://user:pass@myhost.com/user/sea3pea0 
Save the settings, then try the "test" button

**Comment by sea3pea0** [comment]
Well I've tried all the obvious things. My guess is one of a number of things could be going wrong:

1. Maybe it's https
2. Maybe it's the url path
3. Maybe it's that I have special characters in my password
4. Maybe it's that I'm using Digest Authentication

I've run out of time to try and figure this out at the moment as I'm going to be busy for the next 2 weeks but I will revisit this later. I'm ok since nzb providers seem have better results in general anyway. Black hole works sometimes, others not depending I think on whether it's dealing with magnet links or not. Thanks for your help troubleshooting the matter!

**Comment by philborman** [comment]
Well,  its not the non-standard url, point 2 above.  Tried it here with /RPC2 changed to /test and it still worked. LL host set to localhost/test.   Don't think https should be a problem either if xmlrpc works from the command line. 
As for points 3,4  maybe get it working without auth first.  Certainly no auth is known to work  here,  and another user has reported that basic auth works.
