### ISSUE TITLE
nzbget 

### ISSUE THREAD

**Issue by gilly65** [DobyTang/LazyLibrarian#523]
I have LL set to use torrents or newsgroups, for the last while it hasn't used the newsgroups, I looked into it today, this is the error I get while trying to test nzgbet connectivity:
NZBget connection FAILED
Check debug log

I have tried with debug on and of and this is the only message I see:
ERROR	Please check your NZBget host and port (if it is running). NZBget is not responding to this combination: [Errno -2] Name or service not known

I am using the proper name, password, url and port.
I'm not sure where to go from here.

nzbget still works with SickRage, CouchPotato, Headphones and Mylar, so I am thinking it's an LL issue.

Thanks

**Comment by philborman** [comment]
Might be a lazylibrarian config issue,  the message is a socket error. 
I will improve the error message to help track it down,  what do you have as host and  port for Nzbget?

**Comment by gilly65** [comment]
Thanks, I figured it out and was on my way here to post it.

I had the url as http://localhost , I changed it to just localhost and it's working now.
It used to work with http:// , so it threw me off.

I appreciate the quick response, I like LL and am very happy to see it progressing.

**Comment by philborman** [comment]
Ah - just noticed that bit of code is broken, It should allow http, https or if neither default to http.
Fixed in next release. I'll mark this as closed.
