### ISSUE TITLE
File/Folder permissions created by LazyLibrarian under Linux

### ISSUE THREAD

**Issue by WzL** [DobyTang/LazyLibrarian#526]
Having LazyLibrarian running on a Linux Target (Debian) for the last months is going well, updates are getting pushed well which is truly great. I have an issue though with interoperatebility between for example Torrent download client Transmission and LazyLibrarian. All folders created by LazyLibrarian give only Read/Write/Execute permissions to the LazyLibrarian daemon user, in my case lazylib. Folders created by LazyLibrarian are always 700 which is only readable by owner of the file. For example:

```
ls
drwx------  2 lazylib             monkey      4096 Nov 24 11:06 Crazy little monkey (Wacky Guide) - 6th Edition (2016)
```

Is it possible that umask is configurable within LazyLibrarian and that I can set it to "007" for example. So the resulting folders created by LazyLibrarian will look like the following example:

```
ls
drwxrwx---  2 lazylib             monkey      4096 Nov 24 11:06 Crazy little monkey (Wacky Guide) - 6th Edition (2016)
```

**Comment by philborman** [comment]
We do not explicitly set any rwx permissions, just use the system defaults. 
You might need to look at the permissions of the parent directory 
gid and acl should let you change it to how you want it to be.

**Comment by DarkSir23** [comment]
I'm not using acls, and strangely, when I first set things up, it was creating folders with 755, but as of a few days ago, it started doing them as 700.  Not sure what has changed.

**Comment by WzL** [comment]
@DarkSir23 Which operating system is you using?

**Comment by philborman** [comment]
Testing here on ubuntu 16:10 and Raspberry pi osmc (both debian derivatives) . As I said in an earlier reply, we don't explicitly set file or directory permissions (though I could easily add it)

@DarkSir23 just a thought, you say it was working until a few days ago, last commit was 12 days ago. Nothing in it that I can see that should affect file permissions. Any changes to your os around then? Could be a difference in a library or system setting somewhere? ( I upgraded my ubuntu 16:04 to 16:10 a few weeks ago and a few older programs didn't work after the upgrade).

**Comment by DarkSir23** [comment]
Well, "A few days ago" may be a bit short.  I'm running FreeNAS with FreeBSD jails.  Nothing that I know of has changed.  It's not a big deal for me, I just noticed that the permissions on new folders don't match the earlier created ones.    Just wanted to weigh in on the discussion, in case something DID change recently.

**Comment by DarkSir23** [comment]
@philborman To follow up, if I create a folder as the user the lazylibrarian process runs as (with sudo), it creates with permissions 0755.  If I create a file, it creates it with 0644.  But when LazyLibrarian creates a folder, it's 0700, and files are 0600.  It's like it has stopped using the defaults.

**Comment by philborman** [comment]
Certainly looks like something has changed in LazyLibrarian if it's affecting multiple distributions.I hoped it was something simple like a change in debian defaults, but I guess I've broken something. No idea what. I might resort to adding explicit chmod calls after each file/folder create if I can't find it.

**Comment by WzL** [comment]
I cannot confirm if the behaviour/f unctionality changed since a moment in
Time. I Just noticed that file permissions were strict (700).

Op 2 dec. 2016 11:45 a.m. schreef "philborman" <notifications@github.com>:

**Comment by philborman** [comment]
Should be fixed in latest release. I have added chmod calls to set directories rwxr-xr-x and files rw-r--r--
