### ISSUE TITLE
How to search for exact String

### ISSUE THREAD

**Issue by bernddd** [DobyTang/LazyLibrarian#527]
Hi,

when I search for ct magazin I get all results that contain "ct" in it (like AD Architectural Digest Magazin)
How can I search for the exact string "ct magazin" (I have already tried to search for "ct magazin" and 'ct magazin' but it did not help 

Greetings Bernd

**Comment by philborman** [comment]
Try the search term computertechnik instead of ct

Not ideal, very short titles are a problem. We pass the search term to the usenet/torrent providers and then try to filter the replies, rejecting the ones we don't want. Filtering should remove the bad matches as we look for "words", so the word "ct" needs to have "non-word" characters either side of it, spaces, dots, underscore. Problem is the providers only send us the ones _they_ think match, and some only send a limited number of matches.
I will see if I can find a better solution.

**Comment by bernddd** [comment]
Hello,

thank you for your quick response (and sorry for my late answer) I thought
I would get a email notification.

Your suggestion unfortunately did not help. The whole name of ct is "ct magazin für computertechnik" 
but in my nzb indexer it is always called "ct magazin" so I can not find anything if i search for 
computertechnik. But lazy librarian works good with all my other magazines. Would be great if there was a better solution in the future. 

(This is my first "issue" on github- should I close It now?)
Greetings Bernd

**Comment by philborman** [comment]
Which nzb indexer are you using, might be we can adjust the query we send.  Torrents are often bad for searching, but some of the nzb indexers are quite good. oznzb and nzbgeek work well, drunkenslug and nzbplanet give lots of irrelevant results

You can close the issue if you wish, but leaving it open will remind me I need to look at it again

**Comment by bernddd** [comment]
Hello,

I use https://newz-complex.org (the best I found for german content) and I have a nzb.is account
I also have a oznzb account.. but premium expired a few weeks ago.

Greetings Bernd

**Comment by philborman** [comment]
I can't log on to them, they don't have a free trial account. Do you know if they have an extended search capability?  For example in DrunkenSlug you can put   ^ct  to search for titles that _start with_ ct

**Comment by bernddd** [comment]
Hello,

yes searching for  ^ct  only shows titles that start with ct. That eleminates a lot of wrong results. But it also shows: ctulu, ctrlz2ta, ctu counter terrorism. 
If I could "tell" the indexer that after the ^ct  should be a space all results would be ok. (It also finds ct make, ct security, ct wissen, ct sonderheft) But I do not mind they are all interesting for me

Greetings Bernd

**Comment by philborman** [comment]
In DrunkenSlug you can do that using brackets, so (^ct )  with a space after the 't' might work
I think in lazylibrarian we would need an extra field in the magazine config options so the names don't appear in the listings with the extra characters.

**Comment by bernddd** [comment]
Hello, 

the brackets do not work with newz complex (or I do it wrong) I have a invite to newz complex (I do not know if this means the account is for free) Do you want it for testing? 

Greetings Bernd

**Comment by philborman** [comment]
Might be useful, but before we try that can you check your debug log for a "Search parameters" line like this, just in case we are not passing the correct parameters. The important bit is the 'q': u'(^ct )'

04-Dec-2016 10:48:06 - DEBUG   :: SEARCHMAG : [NewzNabPlus] - nzb Search parameters set to {'q': u'(^ct )', 'apikey': u'xxxxxxxxxxxxxxxxxxxxxxxxxxx', 't': u'search', 'extended': u'1', 'cat': u'7010'}

**Comment by bernddd** [comment]
Hello,

the debug log:`
`2016-12-05 04:48:55	INFO	Search for magazines complete
2016-12-05 04:48:55	DEBUG	Adding magazine (^ct ) to queue.
2016-12-05 04:48:55	DEBUG	Found 0 nzb at http://newz-complex.org/www for: (^ct )
2016-12-05 04:48:55	DEBUG	Parsing results from http://newz-complex.org/www
2016-12-05 04:48:55	ERROR	Database error: near "ct": syntax error
2016-12-05 04:48:55	DEBUG	[NewzNabPlus] - nzb Search parameters set to {'q': u'(ct )', 'apikey': u'', 't': 'search', 'extended': '1', 'cat': '7010'}
2016-12-05 04:48:55	DEBUG	[NewzNabPlus] searchType [mag] with Host [http://newz-complex.org/www] mode [nzb] using api [] for item [{'searchterm': '(^ct )', 'bookid': u'(^ct )'}]
2016-12-05 04:48:55	DEBUG	[IterateOverNewzNabSites] - http://newz-complex.org/www
2016-12-05 04:48:55	DEBUG	Using stored capabilities for http://newz-complex.org/www
2016-12-05 04:48:55	INFO	Searching for 1 magazine
2016-12-05 04:48:55	DEBUG	Removing old magazine search results
2016-12-05 04:48:55	DEBUG	Searching for magazine with title: (^ct )
2016-12-05 04:48:40	ERROR	Database error: near "ct": syntax error
2016-12-05 04:48:33	INFO	Log cleared, level set to [2]- Log Directory is []``

Greetings

**Comment by philborman** [comment]
Well, the database error is expected, we need to have a title for the database, and a different  searchterm. Seems newz-complex returned no results for that search term though.
Maybe that invitation would be useful after all. If you want you can email me at phil.borman@gmail.com
Thanks, Phil.

**Comment by philborman** [comment]
Thanks for the invite link, very useful.
It seems newz-complex search capabilities are quite limited and does not accept ^ however I have managed to get a lot closer to what we want using a search string of ( ct magazin )  and a reject word list but I am only locating old issues. 
The free account only allows 5 api searches per 24hrs so I will have to continue tomorrow.

**Comment by philborman** [comment]
Just pushed a new version that seems to work ok here - please check and see if it works for you.
New config options in the filters tab, for ct I put a reject list of fotografie and a search expression of ct_magazin  (no brackets or ^ needed)
The only issues in 2016 seem to be 01 2016 and 02 2016 which lazylibrarian thinks are January and February, so too old to download. You can select them for download from the "past issues" tab.

**Comment by philborman** [comment]
Actually one of the search filters has an indent error. I should push a new version tonight, just need a bit more testing.

**Comment by bernddd** [comment]
Hello,


api key is unchanged .. feel free to use it for testing.


Greetings


Am 06.12.2016 um 10:09 schrieb philborman:
