### ISSUE TITLE
Windows locale error

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#532]
Unable to load requested locale [en_US.utf8] unsupported locale setting

I've been getting this issue since installation.
Do you know how to 'fix' this?

I believe it's something to do with Python and the Windows locale that it 'sees'.

**Comment by philborman** [comment]
On linux, locale -a gives a list of known locales. Not sure what the equivalent command would be in windows.

**Comment by MrMxyzptlk** [comment]
Like I said I think it probably has nothing to do with Windows; more than likely it's Python in Windows that can't 'see' the EN locale. 

I will see if the Python forums have a fix.

Thank you for this Kick Ass app!

**Comment by philborman** [comment]
Could be something as simple as a spelling difference,  lazylibrarian looks
for an exact case dependent match.

**Comment by philborman** [comment]
You can find what locales python can see if you can get to a python terminal (at the windows command prompt, enter python). The following lines will list all variants of the "US" locale that it can find...

import locale
locale_list = locale.locale.alias
for item in locale_list:
    if 'us' in item.lower():
        print item,locale_list[item]

**Comment by MrMxyzptlk** [comment]
Thanks for the update.
