### ISSUE TITLE
An error occurred in the torrentdownloads parser: unknown url type: /torrent/

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#533]
I'm getting these errors lately. Here is one of many, searching for magazine Harpers Bazaar.

An error occurred in the torrentdownloads parser: unknown url type: /torrent/1660397795/Harper%E2%80%99s+Bazaar+UK+%E2%80%93+September+2015

**Comment by philborman** [comment]
Looks like they have changed the html layout on their site. We scrape the page rather than do a proper api query. I will look at this and get it working again in the next day or two.

**Comment by MrMxyzptlk** [comment]
Danke!

**Comment by philborman** [comment]
Should be fixed now, they changed the html page, but only slightly.

**Comment by MrMxyzptlk** [comment]
Thanks! Working great...
