### ISSUE TITLE
Library Scan with Calibre

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#535]
When I do a Library Scan, with the hopes of picking up anything newly added to Calibre, I am getting a lot of WARNING	Updating book location and WARNING	Failed to match book errors.  The "Updating Location" errors seem to be on books that LazyLibrarian says I don't have, though they are there.   The "Failed to Match" book errors seem to happen when the book has more than one author listed in Good Reads.  The book shows up if I search for it, but not if I open the author.  I know this probably doesn't make any sense, but it's what I've got so far.  

Is there anything I can do in Calibre to make them match up with LL better?

**Comment by philborman** [comment]
The warnings are a new feature as i noticed some of my books were matched incorrectly. 
Updating location message (if you have not moved the book) means the book was previously matched incorrectly on a scan.  If you are getting the message repeatedly on the same book it's getting matched twice to different books. Matching is done from the book author and title. Maybe find which ones it's matching (should be in debug log i think) and moodify the title or author of the one thats wrong? 

Failed to match is when we couldn't find the book under the correct  author. If the book is by several authors, it's metadata might have one name as the author but goodreads lists it under one of the others.  Not sure if we can get round that easily. I will have to think about it.

**Comment by DarkSir23** [comment]
Would that happen in places where I have ePub and Mobi versions of the same book?  I thought that might be possible.

**Comment by DarkSir23** [comment]
Ok, I'm seeing some things that make sense.    Is there an address or IRC or something where I can send you some information?  I don't really wanna paste logs here :)

**Comment by DarkSir23** [comment]
I'm seeing books that have similar titles, like ones from a series, all matching the same book.   As an example, many Agatha Christie books are matching like this:

`
07-Dec-2016 20:43:11 - WARNING :: LIBRARYSYNC : Updating book location for Agatha Christie The Clocks (Hercule Poirot Series Book 34)
07-Dec-2016 20:43:11 - DEBUG   :: LIBRARYSYNC : Agatha Christie The Clocks (Hercule Poirot Series Book 34) matched BookID 538605, [Agatha Christie][Hercule Poirot]
`
I'm just not sure what to do about that.   I'd love to see some manual matching capabilities, but that's a bit beyond the scope of my question here :)

**Comment by philborman** [comment]
There are ways of manually doing this,  but not within lazylibrarian yet.  Might be worth adding at some point. You can email logs to me at phil.borman@gmail.com if you want. I can email you some details on how the matching works and what you can do in calibre or with a text editor to improve matching capabilities.

**Comment by DarkSir23** [comment]
I did email you, but mail from my server sometimes gets dumped into gmail's spam.  Thanks again :)  I'm making progress, albeit slow progress

**Comment by philborman** [comment]
No email received, just the messages in this issue.
Some thoughts on your earlier comments...

Goodreads matching isbn rarely works, though we do try. The reason is that each book can have multiple isbn, one per edition/reprint. There is a LibraryThing tool that can list associated/linked isbn but the list isnt complete. Usually matching to author and title works.

Books that are not listed on the author page but you can find with a goodreads search...
lazylibrarian will reject any that don't match the language(s) you want, or if the language is unknown, ie the book metadata is incomplete (maybe add Unknown to the list of valid languages in your LL config)
Also some books on goodreads that have an audiobook available have the author incorrectly set to the narrator. eg Agatha Christie Mrs McGintys Dead  has a goodreads author of Hugh Fraser

The ebook and mobi (of the same book) shouldn't be a problem as usually both will have the same metadata, especially if calibre converted them.

**Comment by philborman** [comment]
Had a play with calibre/lazylibrarian integration and made a few changes. New version has better name matching capabilities with calibre libraries, and I've improved the author name consistency for books with multiple authors. Hopefully this will improve things.  Calibre has quite extensive editing facilities, but it moves books and directory names to match the edited results. This will confuse lazylibrarian, as it won't know they've moved. You will need to do a LL libraryscan after you finish calibre editing. You can libraryscan a single author if not much has changed. You can also edit lazylibrarian database entries for each book from their authors page (we only change the database, we don't move the books!)

**Comment by DarkSir23** [comment]
This all sounds very exciting.  Checking it out posthaste!

**Comment by DarkSir23** [comment]
Looking good! I've switched my Calibre to use Goodreads metadata, and am testing it out with a handful of books.  Will see how the library scan goes :)

**Comment by philborman** [comment]
Ah - didn't realise you could do that, it's not installed on mine, it's an
extra. Just running calibre now on my main library,  then I'll reimport
into lazylibrarian. If it works better with that setting it's worth
mentioning it in the wiki.

Thanks for the tip!

**Comment by philborman** [comment]
Switching calibre to use goodreads didn't really improve anything much for me. The problems I encountered with my library were either no language, or a different author to the metadata.
i.e. Robert Ludlum, the Bourne series.  He only wrote the first few, the rest were written by Eric Van Lustbader, bit goodreads still lists them under Robert Ludlum. Yuo can edit the metadata in calibre or lazylibrarian (or externally with a text editor) to get around this.

Missing language can be worked around by editing the book metadata to supply a language, or editing the unknown books in lazylibrarian, or adding "Unknown" or "All" to the languages you want lazylibrarian to allow in the config. "Unknown" will pull in quite a lot of foreign language books that don't declare a language. "All" will allow all languages, but is much faster. Personally I use methods 1 and 2 so the library doesn't get cluttered up with foreign language versions of my books.

**Comment by DarkSir23** [comment]
I'm closing this since it's being addressed in #549 now
