### ISSUE TITLE
Request: Variable for Log File Length

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#536]
Would be nice to up the size of the log files for easier searching for problems.  Right now it seems to be locked at 200k before rolling over.  I'd like to make it at least 10 or 20M, personally.

**Comment by philborman** [comment]
Already in the config file, but not configurable from the web interface. 
I think the variables are called LOGSIZE and  LOGFILES,  just edit the config file with a text editor. 
LOGLIMIT is the other logging variable, thats the number of lines to keep in memory. That one is configurable on the web interface .

**Comment by DarkSir23** [comment]
Awesome, thanks.  I should have thought to look there.
