### ISSUE TITLE
Setting for max. download file size

### ISSUE THREAD

**Issue by overdrive69** [DobyTang/LazyLibrarian#537]
Hello, do you think there is a way to add a Option to setup the max. size for a download file. 
Because LL often download Files with more then 100 MB.

**Comment by philborman** [comment]
There is an option to do this in config->Filters,  but its not perfect.
Usenet is ok, but torrents and torznab do not always report a size, or report the size as zero.
Also current version uses the same limit for books and magazines. Next release will have them separate as epub and mobi books are usually a lot smaller than magazines which are pdf
