### ISSUE TITLE
Feature request: Hold off on processing empty folders or folders with *.bts files in them

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#539]
When checking snatched folders, it would be great if LL didn't do anything to them if they're empty or have .bts files in them.  

Scenario:  My downloads go to a different machine than my LL.  I use BTSync to sync those folders up.  If LL runs postprocessing on that folder before BTSync is finished, it renames the folder to *.fail and BTS stops trying to work.  

What would be great is if, when LL checks the receiving folder, if it hits a folder that's empty or has a .bts file in it, just hold off, and try again next time.   Ideally, this would be something that it could try X number of times before failing, but it could just never run.

Hope I described the scenario adequately :)

**Comment by philborman** [comment]
Folder with .bts is easy to add. Empty folder is more difficult as we can't tell if the files that should be in it have already been processed  and moved. I will add .bts check in later today, maybe you could report back if this is enough or if we need to figure out some way of doing an extra check on an empty folder.

**Comment by DarkSir23** [comment]
A thought that might solve that:  If the empty folder is more than, say, two hours old?

**Comment by philborman** [comment]
We could create a file in the folder on first postprocessor run, and on
next run delete the folder if its still empty (apart from our special
file), or keep track of empty folders in the database on first run and
delete them if still empty on second run.
Or maybe we don't do anything at all with empty folders, just leave them
hoping they fill up later. If they don't fill up then the postprocessor
will eventually complain about a failed task and we can tidy up then, or
leave the user to tidy up. Quite a few options.
Maybe we won't hit an empty folder anyway, unless we're really unlucky. I
would expect that btsync creates the folder and then starts to populate it
straight away so it won't be empty for long.

Did you try the version with .bts checking?

**Comment by DarkSir23** [comment]
Downloading it now.   Will try and report back.

**Comment by DarkSir23** [comment]
Ok, mostly the same result.  BTSync only populates the folder with bts files as it's sending the files, but it creates the directories immediately.  So the folders are empty until the file starts transferring.   To test I pulled down 10 items, and throttled my transfer speed a bit.  When my hourly (I put it hourly to reduce the chances of this happening) post processing happened, it renamed 7 empty folders with .fail, and then BTSync crapped out. :)

**Comment by philborman** [comment]
ok, just added "ignore empty folders", lazylibrarian will eventually
complain about a failed download if the empty folder doesn't get populated.
Will post the new  version tonight.

**Comment by philborman** [comment]
Hopefully this version fixes it for you. If not let me know. If it's all working correctly now, please close the ticket.

**Comment by DarkSir23** [comment]
It looks good.  I'll go ahead and close it, and revisit if I see any weirdness.  Thanks so much, this will help a lot!
