### ISSUE TITLE
Post Processing...

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#542]
I tried to reopen the previous one, but it wouldn't let me.

The latest update didn't fix the issue. It finds the mag, downloads the mag, but completely ignores it during post processing?

...also it is looking for 94 snatched items that were previously downloaded, but I deleted...is there a way to clear this out so LL doesn't attempt to post process these anymore

**Comment by MrMxyzptlk** [comment]
OK, I decided to delete my .db file and let LL scan my mag and book library. After it completed, I tried searching for the Harpers Bazaar India and it finally processed it.

**Comment by philborman** [comment]
Ok, glad its fixed.
Guess I need to do a bit more work on checking the database entries, looks like something wrong in the database was causing issues?  
The 94 snatched items left in the database _should_ get tidied up at the end of the postprocessor run. Once postprocessing is complete and it prints the " nn books/mags processed" message it then scans for anything still marked "snatched" in the database. If it finds any, it complains if they are more than a few hours old and deletes them.  Can you confirm if you are getting the "nn books/mags processed" message now?   Thanks again for your help debugging this.

**Comment by MrMxyzptlk** [comment]
OK, problem has returned. So after I added Harpers Bazaar USA, it found the current issue, downloaded with SABnzbd, and it post processed and shows as 1 issue in LL. The problems began again when I went to back issues, and then selected past issues, it sent them to SABnzbd, SABnzbd downloaded them, and they are in the same directory as the 1 current issue that was post processed  OK...however the logs are showing exactly the same as before...LL is not looking for these downloaded past issues or attempting to post process them?

**Comment by philborman** [comment]
I presume they are marked as snatched in history as before?

Do you get the "x books/mags were processed" message at the end of the 
postprocessor run?

If not, the postprocessor is getting stuck again. We might need another 
test version if you're up for it...

**Comment by MrMxyzptlk** [comment]
Yes they are all marked as snatched.
No I do not see that message in the log. I did after the 1 current issue post processed.

Sure I'm always game for tech...

**Comment by philborman** [comment]
ok, the postprocessir isn't completing its run. Either crashing or getting
stuck waiting for a reply.
Do you know which downloaders were used for the files waiting to
postprocess?

**Comment by MrMxyzptlk** [comment]
I just emailed you today's LL logs.

**Comment by MrMxyzptlk** [comment]
It's looking good...thanks for the VERY quick updates.
