### ISSUE TITLE
Another GoodReads scanning question

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#543]
Heya, thanks for all the help so far.  I was just noticing something about the way LL scans GoodReads titles that might make a difference.

If LL encounters a : in the title, it splits it.  Even if the : is in the middle of a parenthetical. So

Book Title (Series: Subseries Book 1) 

Would split the title as

Book Title (Series
Subseries Book 1)

Suggestion:  Before trying to split on the :, see if there's a ( and split there, either including both parenthesis in the subtitle (my preference), or stripping the opening and closing parenthesis completely.

I think that will help a lot with book matching as well.

I think the above splitting is why a lot of books match solely on "Star Trek" or "Star Wars" instead of their actual book title.   If I manually edit the book to split at the parenthesis, they match when I library scan.

Thanks,

**Comment by philborman** [comment]
Good idea. Will add that in next release.
