### ISSUE TITLE
Not an issue:  Database editing

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#548]
Do you know if a way that I can clear out the Authors and Books sections of the database (so I can start over), without affecting the Magazines?

**Comment by philborman** [comment]
You can do it from within lazylibrarian, but it's time consuming.
Go to each authors page in turn and select "Remove Author"
Alternatively use sqlite3 to do it in one go, and very quick...

sqlite3 .lazylibrarian.db
delete from authors;
delete from books;
.quit
