### ISSUE TITLE
Question: How do I have LL regenerate book or author thumbnails?

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#550]
Question: How do I have LL regenerate book or author thumbnails?

I had accidentally deleted my cache when I had reinstalled LL.

**Comment by philborman** [comment]
Use the api,  something like...

http://localhost:5299/api?apikey=your_api_key&cmd=getBookCovers&wait

when that returns ok, do

http://localhost:5299/api?apikey=your_api_key&cmd=getAuthorImages&wait

**Comment by MrMxyzptlk** [comment]
Worked like a charm!
