### ISSUE TITLE
Feature Request: Show Magazine Covers like Books and Authors.

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#551]
Feature Request: Show Magazine Covers like Books and Authors.

**Comment by philborman** [comment]
We already do.
You need to have a magazine cover in the same folder as the magazine issue, with the same name as the issue but a .jpg extension. LazyLibrarian can generate the covers for you if you  have imagemagick and ghostscript installed on the machine running lazylibrarian. See the wiki for details.
![screenshot from 2016-12-23 09-37-51](https://cloud.githubusercontent.com/assets/12158777/21450077/f6969592-c8f3-11e6-82bd-660c25bfa9f1.png)

**Comment by MrMxyzptlk** [comment]
Thanks!

**Comment by MrMxyzptlk** [comment]
I setup gsconvert.py and it is working great other than no magazine covers. So I deleted my .db again and then let LL scan my book and magazine libraries. LL is creating Author and Book covers, but appears to no create / recreate magazine covers (over 500 magazines). I looked through all your API commands, and didn't see any to scan current magazines and recreate covers. Did I miss something?

**Comment by philborman** [comment]
The magazine libraryscan will create the covers as it adds each issue to 
the database, if it can.

Looks like you have a problem with either ghostscript or the interface 
to it.

In order to track this down...

Are you on windows, mac or linux?

Do you have a recent versions of ghostscript and/or imagemagick installed?

**Comment by MrMxyzptlk** [comment]
Windows 2012R2, I just installed the latest version of GhostScript.
I then copied the directory, which was already named "gs", and put it in the root of LL.
I changed the config for the cover creation options from 'blank' to "gsconvert.py".
I see no errors in my logs. I downloaded some new magazines which LL successfully added, but still no covers?

**Comment by philborman** [comment]
I haven't tried it under Windows myself, but had reports it works.  I think gsconvert.py expects to find the executable in your system path or in the lazylibrarian folder,  ie not in a gs folder. 
If you run the magazine scan with debug log on you should get some progress and error messages

**Comment by MrMxyzptlk** [comment]
OK, I will try and move the exe.

**Comment by MrMxyzptlk** [comment]
I tried gsconvert.py on the command line but it always says it can't find 'gs'.
I have a gs folder in LL, I tried moving the gswin32c.exe to LL root, I tried renaming it "gs".

Nothing is working? I'm googling solutions right now...

**Comment by MrMxyzptlk** [comment]
Ok, i have got GhostScript working from the Windows command prompt, by adding the gs bin directory to the Windows PATH. When I type "gs" on the command line GhostScript starts.
When I attempt to run gsconvert.py from the command line is states that it can't find 'gs'?

**Comment by philborman** [comment]
Do you have a "which" command in windows?

What do you get if you type

which gs


gsconvert tries to find gs in the current working directory (same 
directory as gsconvert.py) but it just looks for a file called gs not gs.exe

If it's not there, it tries to run "which gs" to find it.

**Comment by MrMxyzptlk** [comment]
Oh, OK...let me try and rename the exe to just gs...I had renamed it gs.exe.

**Comment by MrMxyzptlk** [comment]
That as it!
When you rename it for Windows, you can't leave the extension name on the filename.

**Comment by MrMxyzptlk** [comment]
Sorry! I shouldn't have closed it so fast.
Not working in LL.

2016-12-23 10:38:10	DEBUG	Unable to create cover for Z:\Anthony\Magazine\Magazines\Loaded\Loaded - 2014-11-01.pdf using convert
2016-12-23 10:38:10	DEBUG	Creating cover Z:\Anthony\Magazine\Magazines\Loaded\Loaded - 2014-11-01.jpg for Z:\Anthony\Magazine\Magazines\Loaded\Loaded - 2014-11-01.pdf using gsconvert.py
2016-12-23 10:38:10	DEBUG	Found Issue Loaded - 2014-11-01.pdf

**Comment by MrMxyzptlk** [comment]
But it works in Windows?

**Comment by philborman** [comment]
When you say that it works in Windows, do you mean that it successfully
creates a cover image?   If so we just need to figure out the right paths
to the programs

**Comment by MrMxyzptlk** [comment]
Yes, I put one of my mags in the LL root, and ran from the Windows command line "gsconvert.py "Name of mag.pdf" test.jpg

It created a working cover in the LL root.

**Comment by philborman** [comment]
Ok, interesting. Wonder why gsconvert.py finds it then,  but not from
within ll. so on a Windows command line,  what do you get from
(gsm gs).Path

Another thought, did the magazine name contain spaces as per your example,
could be relevant?

**Comment by philborman** [comment]
Oops,  sorry,  should be (gcm gs).Path   not gsm!

**Comment by MrMxyzptlk** [comment]
I'm not sure where to type that? Is that from a Python prompt on Windows command prompt?

Also I just noticed if you look at the cover creation error in LL that I posted, it says it's using 'convert'? Isn't that the default for ImageMagick?

**Comment by MrMxyzptlk** [comment]
If I change the conversion to 'convert', here is error that I get, when I scan.

2016-12-23 11:03:28	DEBUG	ImageMagick "convert" failed Invalid Parameter - -
2016-12-23 11:03:28	DEBUG	[u'convert', 'Z:\\Anthony\\Magazine\\Magazines\\Esquire\\Esquire - 2015-08-01.pdf[0]', 'Z:\\Anthony\\Magazine\\Magazines\\Esquire\\Esquire - 2015-08-01.jpg']
2016-12-23 11:03:28	DEBUG	Creating cover Z:\Anthony\Magazine\Magazines\Esquire\Esquire - 2015-08-01.jpg for Z:\Anthony\Magazine\Magazines\Esquire\Esquire - 2015-08-01.pdf using convert
2016-12-23 11:03:28	DEBUG	Found Issue Esquire - 2015-08-01.pdf

**Comment by philborman** [comment]
Windows command prompt
If that works i can add it to gsconvert.py

The final error message just means it tried to create the cover using
whatever was entered in the "convert program" config box.
Strangely there are no error messages from gsconvert.py
The latest message where you tried imagemagick is because imagemagick
doesn't like spaces in the magazine names,  don't know how to get around
that. Simply adding quotes doesn't work.

Since you have imagemagick, another option is to add the python wand or
pythonmagick libraries and leave the convert entry blank.

On Fri, 23 Dec 2016, 17:02 MrMxyzptlk, <notifications@github.com> wrote:

I'm not sure where to type that? Is that from a Python prompt on Windows
command prompt?

Also I just noticed if you look at the cover creation error in LL that I
posted, it says it's using 'convert'? Isn't that the default for
ImageMagick?

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/DobyTang/LazyLibrarian/issues/551#issuecomment-269010429>,
or mute the thread

**Comment by MrMxyzptlk** [comment]
Windows didn't recognize (gcm gs).Path? Can you give me verbatim what I should type? I'm unsure...

**Comment by MrMxyzptlk** [comment]
It appears someone is using a caret symbol to escape space with ImageMagick?
Here is the link...look at the last post?

https://github.com/Monnoroch/ColorHighlighter/issues/201

**Comment by philborman** [comment]
Interesting, hadn't heard of that before, will be easy enough to try.

**Comment by MrMxyzptlk** [comment]
OK, I changed it, and no I have the 32 bit version of ImageMagick installed.
What exactly should be in the 'text box' for conversion? Currently I have "gsconvert.py"

Do I need to rename the gswin32.exe to remove the .exe?

**Comment by philborman** [comment]
No, shouldn't need to.
Hopefully gsconvert.py will call "where gswin32" and be given a result of something like
c:\Program Files\gs\gs9.20\gswin32.exe
It should then try to use that program and report it's version number

**Comment by MrMxyzptlk** [comment]
Same results. I restarted LL beforehand as well.

2016-12-23 13:36:46	DEBUG	Unable to create cover for Z:\Anthony\Magazine\Magazines\Elle\Elle - 2016-02-01.pdf using convert
2016-12-23 13:36:46	DEBUG	Creating cover Z:\Anthony\Magazine\Magazines\Elle\Elle - 2016-02-01.jpg for Z:\Anthony\Magazine\Magazines\Elle\Elle - 2016-02-01.pdf using gsconvert.py
2016-12-23 13:36:46	DEBUG	Found Issue Elle - 2016-02-01.pdf

**Comment by philborman** [comment]
ok, I will post a version with extra debugging info to try and track it down.

**Comment by philborman** [comment]
Think I may have found it, seems the windows version of gs doesn't like the --version parameter that we use to report back.
Still leave the  "where" and "gswin32" change in place, but delete lines 19, 20 and 21 
            params = [GS, "--version"]
            res = subprocess.check_output(params, stderr=subprocess.STDOUT)
            print("Using gs [%s] version %s" % (GS, res))

**Comment by MrMxyzptlk** [comment]
I feel like it's sooo close...that didn't work. Exact same debug log.

**Comment by MrMxyzptlk** [comment]
I don't know that it is even using gsconvert.py
I renamed it, because I was suspicious, and sure enough the debug log didn't change?

**Comment by philborman** [comment]
Wait for the new version with extra debugging and try again.  Might have to
be tomorrow though,  I made the mistake of starting a windows update on my
laptop and it is taking hours.

I normally run linux,  dual boot,  and can't get back to it until the
windows update completes.

**Comment by MrMxyzptlk** [comment]
No worries...

**Comment by philborman** [comment]
Just posted a new version with extra debugging. There are two versions of gs shipped in the windows packages, gswin32.exe which works in it's own window, and gswin32c.exe which doesn't open a window, runs as a commandline program. The problem with the --version parameter was that it only works with gswin32c.exe   Hopefully this will get gsconvert.py working on Windows, or if not it should at least give us more debugging info.

**Comment by MrMxyzptlk** [comment]
I'm going to try it now...

**Comment by MrMxyzptlk** [comment]
Here is the debug error after the cover creation is attempted.

Exception in magazinescan: Traceback (most recent call last): File "Z:\Applications\LazyLibrarian\lazylibrarian\magazinescan.py", line 59, in create_cover res = subprocess.check_output(params, stderr=subprocess.STDOUT) File "C:\Python27\lib\subprocess.py", line 566, in check_output process = Popen(stdout=PIPE, *popenargs, **kwargs) File "C:\Python27\lib\subprocess.py", line 710, in __init__ errread, errwrite) File "C:\Python27\lib\subprocess.py", line 958, in _execute_child startupinfo) WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by philborman** [comment]
Is that all you got in debug? There should be a line just before that which says 
"Creating cover <name.jpg> for <name.pdf> using <program>"
It looks like whatever is in <program> is not recognised by windows.

**Comment by MrMxyzptlk** [comment]
2016-12-24 10:37:49	DEBUG	Unable to create cover for Z:\Anthony\Magazine\Magazines\Z Tattoo\Z Tattoo - 2017-01-01.pdf using convert

**Comment by philborman** [comment]
Ok so windows doesn't like whatever is in the "conversion program" box in
config. Maybe you need full path there,
eg c:\Program Files\LazyLibrarian\gsconvert.py

When you run lazylibrarian, do you give full path to that?
Also is python.exe in your path. (try where python to find out)

**Comment by MrMxyzptlk** [comment]
C:\Python27

Z:\Applications\LazyLibrarian\gsconvert.py

**Comment by philborman** [comment]
Scrapped using gsconvert.py for windows, added code to call ghostscript directly within lazylibrarian

**Comment by MrMxyzptlk** [comment]
Thanks! Merry Christmas!!!

**Comment by MrMxyzptlk** [comment]
Bingo! I had to install the 64 bit version of GhostScript, and then copy the gswin64c.exe from C:\Program Files\gs\bin to the root install of LL. I then renamed the .exe to gswin64c.

I now have magazine covers!!!! Thanks for tracking this down...let me know if I can help troubleshoot anything else.
