### ISSUE TITLE
Magazines status, changed several mags from skipped to ignored...

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#552]
The log showed that the status was changed to ignored, but all of the ones I changed still show under skipped and none under ignored?

**Comment by philborman** [comment]
We don't have skipped or ignored for magazines,  i think?

**Comment by MrMxyzptlk** [comment]
OK thanks. The log states that they have been changed to ignored, but I guess it is actually not doing this.

**Comment by philborman** [comment]
Ah, found it. It's the "past issues" table. Forgot you could do that, 
fixed in next release.

**Comment by MrMxyzptlk** [comment]
Perfect!
