### ISSUE TITLE
Fix numbering on author page

### ISSUE THREAD

**Issue by OmgImAlexis** [DobyTang/LazyLibrarian#555]
The num column should have be centered with `vertical-align: middle; text-align: center;`.

![screen shot 2016-12-26 at 1 23 36 pm](https://cloud.githubusercontent.com/assets/6525926/21474411/a145a5ba-cb6e-11e6-9637-2e9f0bf5b8d1.png)
![screen shot 2016-12-26 at 1 23 24 pm](https://cloud.githubusercontent.com/assets/6525926/21474412/a16e0640-cb6e-11e6-87b8-2aea899df840.png)

**Comment by philborman** [comment]
Ah, thanks. Guess this is in the css somewhere. I had a quick look but couldn't see where to add it, seems you found it from your second image, could you submit a patch? css isn't really my thing.

**Comment by philborman** [comment]
Found it and fixed that one. Similar problem in the book page has me beat though. That table is generated on the fly by datatables and I can't seem to get that to justify the columns.

**Comment by OmgImAlexis** [comment]
Sorry for not getting to the PR in time. Had issues with another project.
What section of the books are you talking about?

**Comment by philborman** [comment]
No worries. Found the issue on the authors page and fixed it (css referred
to seriesOrder, should be seriesNum)
but theres a similar problem on the "books" page where all the columns are
left justified and would be better centered. Problem is the books table is
generated by datatables serverside processing. There is code in webServe.py
getbooks function which adds html to the raw database results, but I think
the css doesn't get processed?  Probably need to do the justification in
datatables columndefs but I don't know how. Not a biggie, it's always been
like that ;-)
