### ISSUE TITLE
indices must be integers, not str

### ISSUE THREAD

**Issue by OmgImAlexis** [DobyTang/LazyLibrarian#556]
When trying to import an epub I'm getting this issue.

The file name is `Leigh Bardugo - [Grisha Trilogy 01] - Shadow and Bone (The Gathering Dark) (epub).epub` and it's added the author fine but it's not importing the book.

```
Unhandled exception in importBook: Traceback (most recent call last): File "/app/lazylibrarian/lazylibrarian/postprocess.py", line 590, in import_book notify_download("%s from %s at %s" % (global_name, was_snatched['NZBprov'], now())) TypeError: list indices must be integers, not str
```

**Comment by OmgImAlexis** [comment]
Import should really be used as similarly to how sickbeard/sickrage handle manual post processing. It shouldn't rely on a file needing to be snatched and that's basically what happened within the function this is erroring in.

**Comment by philborman** [comment]
Thanks for that, might account for the error in  #531 too.  I have added your patch to master. 
We have an alternate directory option for adding books that aren't snatched, which might be why this hasn't been picked up before. The alternate directory import adds the authors and books to the database, doesn't need them to already be there and marked "wanted"

**Comment by OmgImAlexis** [comment]
If you're okay with it I'll start adding PRs to fix broken issues I get.
It'd be great to see a little more documentation to help out new users and developers.

**Comment by philborman** [comment]
That would be great, thanks
