### ISSUE TITLE
Sabnzbd test not using input from form

### ISSUE THREAD

**Issue by OmgImAlexis** [DobyTang/LazyLibrarian#557]
I'm trying to add Sabnzbd and I've tried both with and without `http://` in the host box and both times it searches without taking into account the data I've typed in.

Host: http://192.168.1.150
Port: 8080

```
Unable to connect to SAB with URL: http://:0/api?output=json&mode=auth, [Errno -2] Name does not resolve
```

**Comment by OmgImAlexis** [comment]
Okay, it looks like you need to actually save the form before testing will work. I also noticed you're not sanatising or validating any of the form inputs as adding a trailing slash to the host box causes it to try `http://192.168.1.150/:8080/api?output=json&mode=auth`.

**Comment by OmgImAlexis** [comment]
The test button also doesn't seem to give any feedback whatsoever unless there's an error.

**Comment by philborman** [comment]
Yes, the form validation is quite inconsistent. Lazylibrarian is a mix of code from different authors, some lifted from other projects, some parts better written than others! It's slowly getting cleaned up, but at the moment the only contributor seems to be me, and I tend to just work on the bits that interest me, or on bug reports. Not sure why you're not getting a response from the test button. I get this...
![testbutton](https://cloud.githubusercontent.com/assets/12158777/21485096/9e750d10-cb9d-11e6-9b04-4b6c855ace7a.jpg)

**Comment by philborman** [comment]
Added some code to check for trailing slash.
