### ISSUE TITLE
Github being spammed with checks for new versions

### ISSUE THREAD

**Issue by OmgImAlexis** [DobyTang/LazyLibrarian#559]
If you edit any file within lazylibrarian and restart it then the container keeps checking over and over again. In the last 5 minutes I've had 100s of requests being sent out. This should detect changes in the local git repo and stop checking Github as the person is probably editing the files for a reason. 

There should also be a backoff timer that slowly increases the time between checks since checking over and over seconds after each other isn't going to just fix the issue.

**Comment by OmgImAlexis** [comment]
Looks like this is mainly an issue with restarting it while it's inside of a docker container.

**Comment by OmgImAlexis** [comment]
Since it checked over and over again I'm now hitting the rate limit. Maybe also suggest people add in their Github details to help with this as once logged in the rate limit is increased. This is what we do in Medusa(sickrage fork).

```
{
  "message": "API rate limit exceeded for 111.220.32.148. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by philborman** [comment]
Might be simpler to just add a timer to the git check function. We have rate limiting for some of the api calls so could do something similar here. Maybe base it on the configured version check interval, with the "check version" button or a reboot resetting the timer. I'll have a look over the next day or two. Thanks for the suggestion.
