### ISSUE TITLE
New Book Status

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#563]
Is there a way to differentiate between new books that are created with adding an author and new books that are created when rescanning?  I'd like to set new books to wanted, but i don't want every book an author has written when I add a new one.  Just the ones that are added after the author is present.

**Comment by philborman** [comment]
I think you can just set newbook status to skipped when you add an author, then set to wanted to auto-add any new books. Refreshing the author will not update the status on books already in the database as it skips over existing ones to avoid creating duplicate entries.

**Comment by DarkSir23** [comment]
Mostly asking for when it auto adds a new author that I've added to the library manually.  

Example:  I add a new book to Calibre, and I don't already have anything else by that author.  Now, the next time I do a library scan, to catch anything that I've added manually, LL adds the author, and currently sets all of their books to Wanted.  I can change the setting in config before I run the manual scan, but I wanted to be sure I wasn't missing a feature that wasn't already there. :)

**Comment by philborman** [comment]
Would be easy enough to separate out, we could have a "New Author" status, and a "New Book" status so in your case you would set newauthor to "skipped" and newbook to "wanted".  Had a quick look at the code and it's only a few minor changes.

**Comment by DarkSir23** [comment]
Cool, It would definitely be helpful, but isn't a dire necessity.  A side note, I've switched over to your repository.  Is that a relatively safe thing to do?

**Comment by philborman** [comment]
I tend to break it regularly ;-)

I use it for testing new code out, then push changes to the DobyTang one 
when I'm fairly happy with them. If I do break it, it's usually not for long

**Comment by DarkSir23** [comment]
I'll risk it.  Thank you, by the way, for continuing this project.

**Comment by philborman** [comment]
I'm enjoying the challenge!

Added new author books option to the version in my git if you want to try it...

**Comment by DarkSir23** [comment]
Looks good, thanks again!
