### ISSUE TITLE
Error message when setting book to 'Wanted'

### ISSUE THREAD

**Issue by sukhysall** [DobyTang/LazyLibrarian#565]
Running version:  c77af7f4141aee3de8aed6704d13917d87dd462e

Hi

When I set a book to 'Wanted' I get the following error. Now as far as I knowm the search does appear to continue using my other providers (I have 3 NZB indexers) but I still get this message:

Unhandled exception in search_nzb_book: Traceback (most recent call last): File "/volume1/@appstore/LazyLibrarian/lazylibrarian/searchnzb.py", line 87, in search_nzb_book resultlist, nproviders = providers.IterateOverNewzNabSites(book, 'book') File "/volume1/@appstore/LazyLibrarian/lazylibrarian/providers.py", line 182, in IterateOverNewzNabSites resultslist += NewzNabPlus(book, provider, searchType, "nzb") File "/volume1/@appstore/LazyLibrarian/lazylibrarian/providers.py", line 358, in NewzNabPlus result, success = fetchURL(URL) File "/volume1/@appstore/LazyLibrarian/lazylibrarian/cache.py", line 45, in fetchURL resp = urllib2.urlopen(request, timeout=30) File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen return opener.open(url, data, timeout) File "/usr/lib/python2.7/urllib2.py", line 429, in open response = self._open(req, data) File "/usr/lib/python2.7/urllib2.py", line 447, in _open '_open', req) File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain result = func(*args) File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open context=self._context) File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open r = h.getresponse(buffering=True) File "/usr/lib/python2.7/httplib.py", line 1183, in getresponse response.begin() File "/usr/lib/python2.7/httplib.py", line 457, in begin version, status, reason = self._read_status() File "/usr/lib/python2.7/httplib.py", line 421, in _read_status raise BadStatusLine(line) BadStatusLine: ''

**Comment by philborman** [comment]
Looks like a badly formed url. I would need the debug line just before the traceback...
[NewzNabPlus] searchType [%s] with Host [%s] mode [%s] using api [%s] for item [%s]

**Comment by sukhysall** [comment]
Hi

I recreated the issue and here's the debug line as well:

2016-12-28 09:00:14	
ERROR	Unhandled exception in search_nzb_book: Traceback (most recent call last): File "/volume1/@appstore/LazyLibrarian/lazylibrarian/searchnzb.py", line 87, in search_nzb_book resultlist, nproviders = providers.IterateOverNewzNabSites(book, 'book') File "/volume1/@appstore/LazyLibrarian/lazylibrarian/providers.py", line 180, in IterateOverNewzNabSites resultslist += NewzNabPlus(book, provider, searchType, "nzb") File "/volume1/@appstore/LazyLibrarian/lazylibrarian/providers.py", line 357, in NewzNabPlus result, success = fetchURL(URL) File "/volume1/@appstore/LazyLibrarian/lazylibrarian/cache.py", line 45, in fetchURL resp = urllib2.urlopen(request, timeout=30) File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen return opener.open(url, data, timeout) File "/usr/lib/python2.7/urllib2.py", line 429, in open response = self._open(req, data) File "/usr/lib/python2.7/urllib2.py", line 447, in _open '_open', req) File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain result = func(*args) File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open context=self._context) File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open r = h.getresponse(buffering=True) File "/usr/lib/python2.7/httplib.py", line 1183, in getresponse response.begin() File "/usr/lib/python2.7/httplib.py", line 457, in begin version, status, reason = self._read_status() File "/usr/lib/python2.7/httplib.py", line 421, in _read_status raise BadStatusLine(line) BadStatusLine: ''

2016-12-28 09:00:14	
DEBUG	[NewzNabPlus] URL = https://www.usenet-crawler.com//api?author=Valmore+Daniels&apikey=<REMOVED MY API>&t=book&cat=7000%2C7020%2C7022%2C7021%2C7023&title=Angel+Tears+%28Fallen+Angels+4%29

**Comment by philborman** [comment]
So usenet-crawler is back, thought they had closed down.

ok, problem seems to be a http communication error. Is it always
usenet-crawler or other nzb providers too?
I can easily trap and bypass the error, but would be useful to know why we
get it.
The python docs say BadStatusLine is
Raised if a server responds with a HTTP status code that we don’t
understand.

but the request looks ok, and entering it in a browser (with added apikey)
gives a valid response

**Comment by sukhysall** [comment]
Thank you

I'll remove Usenet Crawler as a provider and try it with the oznzb and drunkenslug one at a time. will update with my findings.

**Comment by philborman** [comment]
Actually, I think it's probably an invalid api in your config for
usenet-crawler.
I deliberately knocked a character off my apikey, and got exactly the error
you're getting.
Needs trapping properly in lazylibrarian and probably print a warning
message. Could you doublecheck your api key as that seems quite likely to
be the culprit.

**Comment by philborman** [comment]
UPDATE
nope, seems it's an intermittent error talking to usenet-crawler. Their site doesn't always respond to queries.

**Comment by DarkSir23** [comment]
Yeah, it's been flakey for a while.

**Comment by sukhysall** [comment]
Haven't seen message again since I disabled usenet crawler. Incidentally I get better book snatching results as well using oznzb and drunken slug. 

Thanks. 

Regards

Sukhjinder Sall

**Comment by philborman** [comment]
Ok, I've altered lazylibrarian so it prints a warning about "no data returned", I'll close this issue now.
