### ISSUE TITLE
Suggestion for adding books with calibredb

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#570]
Adding identifiers for the book on calibre import would be helpful:  --identifier goodreads:###### or --identifier google:###### based on which ID system you're using.  That would guarantee that when calibre scans against the metadata agent, it'll get the same version of the book that LL is using.

**Comment by philborman** [comment]
You _sort of_ can, using the bookid.
Googlebooks bookid is always 12 characters of alphanumeric
Goodreads is variable length but all digits
I haven't found a googlebooks id that's all digits (yet)

**Comment by DarkSir23** [comment]
Well, even if it was just:

if (using goodreads): add --identifier goodreads:<bookid> 

Would help me, I just mentioned google to be complete :)

**Comment by philborman** [comment]
Not sure I follow what you're after here. Where do you want this adding,
pass it to calibredb as a parameter?  If that's the case I'm not sure it
would even get through, calibredb seems to ignore --title  and --author
parameters, either it's broken or we're not passing them correctly.

On Thu, 29 Dec 2016 at 15:58 DarkSir23 <notifications@github.com> wrote:

Well, even if it was just:

if (using goodreads): add --identifier goodreads:

Would help me, I just mentioned google to be complete :)

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/DobyTang/LazyLibrarian/issues/570#issuecomment-269641613>,
or mute the thread

**Comment by DarkSir23** [comment]
I haven't tried it, but yeah, adding --identifier \<whatever:whatever\> is supposed to add the identifier when calibredb imports.  I can try it locally, and see what happens.

**Comment by DarkSir23** [comment]
Ok, by changing all calls for processDestination to include BookID:

`if processDestination(pp_path, dest_path, authorname, bookname, global_name, book['BookID']):`

or just using bookID, depending on which call was used...

and  changing processDestination to accept bookid=None as a parameter...

`
            # so we have to configure calibre to parse the filename for author/title
            # and rename the book to the format we want calibre to use
            for bookfile in os.listdir(pp_path):
                filename, extn = os.path.splitext(bookfile)
                # calibre does not like quotes in author names
                os.rename(os.path.join(pp_path, filename + extn), os.path.join(
                    pp_path, global_name.replace('"', '_') + extn))
                params = [lazylibrarian.IMP_CALIBREDB,
                      'add',
                      # '--title="%s"' % bookname,
                      # '--author="%s"' % unaccented(authorname),
                      '-1',
                      '--with-library',
                      processpath, pp_path
                      ]
            logger.debug(str(params))
            res = subprocess.check_output(params, stderr=subprocess.STDOUT)
            if res:
                logger.debug('%s reports: %s' % (lazylibrarian.IMP_CALIBREDB, unaccented_str(res)))
                if 'already exist' in res:
                    logger.warn('Calibre failed to import %s %s, reports book already exists' % (authorname, bookname))
                if 'Added book ids' in res:
                    calibre_id = res.split("book ids:",1)[1].split("\n",1)[0]
                    logger.debug('Calibre ID: %s' % calibre_id)
                    authorparams = [lazylibrarian.IMP_CALIBREDB,
                        'set_metadata',
                        '--field',
                        'authors:%s' % unaccented(authorname),
                        '--with-library',
                        processpath,
                        calibre_id
                        ]
                    logger.debug(str(authorparams))
                    authorres = subprocess.check_output(authorparams, stderr=subprocess.STDOUT)
                    titleparams = [lazylibrarian.IMP_CALIBREDB,
                        'set_metadata',
                        '--field',
                        'title:%s' % bookname,
                        '--with-library',
                        processpath,
                        calibre_id
                        ]
                    logger.debug(str(titleparams))
                    titleres = subprocess.check_output(titleparams, stderr=subprocess.STDOUT)
                    if lazylibrarian.BOOK_API == "GoodReads" and bookid:
                        metaparams = [lazylibrarian.IMP_CALIBREDB,
                            'set_metadata',
                            '--field',
                            'identifiers:goodreads:%s' % bookid,
                            '--with-library',
                            processpath,
                            calibre_id
                            ]
                        logger.debug(str(metaparams))
                        metares = subprocess.check_output(metaparams, stderr=subprocess.STDOUT)
            # calibre does not like quotes in author names
            calibre_dir = os.path.join(processpath, unaccented_str(authorname.replace('"', '_')), '')
`

It will import the book, check the output for the calibre bookID, then set the Author and Title (moving it to the right folder if the author is screwed up) and then, if using GoodReads, set the goodreads ID.

This should generate exact matches for book hunting in the next step.

**Comment by DarkSir23** [comment]
Ouch ,that's very ugly.  Maybe I should just fork your repository and send a pull request for you to look at :)
I'll try to do that when I get home.

**Comment by philborman** [comment]
Hard to read, but I see where you're going, couple of thoughts...  
1. If lazylibrarian.BOOK_API == "GoodReads"    isn't necessarily true. You might have been on google when you imported the book, but are on goodreads now. Might be better to use  if bookid.isdigit()  
If true, goodreads. If false, googlebooks.  If we ever add another provider we can add another column to the books table to identify the source. Could add it quite easily now, but seems overkill with just the 2 providers. 

2. Won't calibre have already processed the book before you send the goodreads id, or is there a way to get calibredb to reload the metadata (I could look, but thought you might know)

Oh, and couldn't see any documentation on what the valid values are for --identifier
Documentation mentions asin and isbn but not goodreads or googlebooks, I've guessed "googlebooks" but it could just be "google"  Had a go at including it in the version in my git with just a single call to calibredb. Seems to work here on a quick test, but out of time tonight. Will revisit tomorrow.

**Comment by DarkSir23** [comment]
Add doesn't seem to take the authors/title/identifiers parameters, if you're using -1 to scan a whole folder.  So what I did was let it add the book as normal, then catch the calibre book id when it completes, and then change the author, title, and possibly the goodreads ID to the values that we want it to have.

So that's what's accomplishing #2 above.  I'll make the change to #1 and see how it goes.
