### ISSUE TITLE
How fix this with FREENAS

### ISSUE THREAD

**Issue by maxcore** [DobyTang/LazyLibrarian#572]
i juste switch to synology to freenas and i want update the lazy but i have this message ... what i can do for update ..

![capture d ecran 2016-12-30 14 21 31](https://cloud.githubusercontent.com/assets/4043787/21571264/98b6be68-ce9b-11e6-9e37-c2ff170b602e.png)

**Comment by philborman** [comment]
click "check version" on config page. Might be you could not connect to
github temporarily at startup?

**Comment by maxcore** [comment]
i dont know why is only lazy i get this msg check the logs

![capture d ecran 2016-12-30 16 16 28](https://cloud.githubusercontent.com/assets/4043787/21572792/69e3f83e-ceab-11e6-9590-05911d6e2ae7.png)

**Comment by philborman** [comment]
Log definitely shows a problem talking to github. May just be a temporary
issue.
Try with debugging on and if still not working post the debug log

**Comment by DarkSir23** [comment]
Weird, I had the same problem this morning.  I re-pulled the repository from git to clean it up.  

Stop lazylibrarian
Go into /usr/pbi/lazylibrarian/share/lazylibrarian
moved LazyLibrarian folder to LazyLibrarian-Old
git clone https://github.com/DobyTang/LazyLibrarian
make sure the permissions are right, start it up again.

**Comment by maxcore** [comment]
i got the problem its was my network with the bad ip nameserver it the freenas plugin jail , now all run smoothly!
