### ISSUE TITLE
Stupid request, kinda...

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#573]
Could you point me to the bit of code you added to post processing that skips empty folders and ones that contain BTS files?

**Comment by philborman** [comment]
It's in a few spots, there is this...
                            if os.path.isdir(pp_path):
                                logger.debug('Found folder (%s%%) %s for
%s' % (match, pp_path, matchtitle))
                                if not os.listdir(pp_path):
                                    logger.debug("Skipping %s, folder is
empty" % pp_path)
                                elif bts_file(pp_path):
                                    logger.debug("Skipping %s, found a .bts
file" % pp_path)

and also parts that check extn = os.path.splitext(fname)[1]
                    if not extn or extn not in skipped_extensions:

as .bts is one of the entries in the skipped_extensions list

**Comment by DarkSir23** [comment]
Thanks, I'm going to try to implement the same somewhere else, I just wanted to know an efficient starting point :)

**Comment by philborman** [comment]
Wouldn't say mine is necessarily efficient, I¡m no python expert. The code I use to check extensions is in common.py 

`def any_file(search_dir=None, extn=None):
    # find a file with specified extension in a directory, any will do
    # return full pathname of file, or empty string if none found
    if search_dir is None or extn is None:
        return ""
    # ensure directory is unicode so we get unicode results from listdir
    if isinstance(search_dir, str):
        search_dir = search_dir.decode(lazylibrarian.SYS_ENCODING)
    if extn and search_dir and os.path.isdir(search_dir):
        for fname in os.listdir(search_dir):
            if fname.endswith(extn):
                return os.path.join(search_dir, fname)
    return ""
`
