### ISSUE TITLE
unhandled exception error while searching for a book

### ISSUE THREAD

**Issue by VarunChugh** [DobyTang/LazyLibrarian#576]
Get the following error when searching for a book:

Unhandled exception in search_nzb_book: Traceback (most recent call last): File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/searchnzb.py", line 89, in search_nzb_book found = processResultList(resultlist, book, "book") File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/searchnzb.py", line 212, in processResultList if newValueDict['nzbmode'] == "torznab": KeyError: 'nzbmode'

**Comment by brunhil** [comment]
I ran into this issue last night as well.

**Comment by brunhil** [comment]
I have started working on a fix... Will submit a merge request when I am done.

**Comment by philborman** [comment]
The recent change to that file was on line 130   if matches[]:    
It used to just say  if matches:
Pycharm complained as it thought matches was boolean so I changed it to matches[] to make it clearer.
Maybe try reverting that line and see if that fixes it. To stop pycharm complaining you could probably also use if len(matches):

**Comment by philborman** [comment]
Ah, found it. It's me being stupid. Not sure why we haven't hit it before though...
Line 212 should say newValueDict['NZBmode']  not newValueDict['nzbmode']
as the keys are case dependant.

**Comment by brunhil** [comment]
Yup @philborman was fixing it and submitting pull request while you found it 😄

**Comment by philborman** [comment]
Yes, the previous version of the code wrongly used the nzbmode from the last match found, not the highest (most preferred) match. Fixed now.
