### ISSUE TITLE
Feature Request:  Multiple Authors with the same name

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#595]
Even if this is just added to the API it would be useful.  If search for an author by book, it gives you an Add Author link, which is a search by the author's name.  Unfortunately, that means that it adds the first author who matches the name, not necessarily the one that is linked to that book.

My suggestion is to change the Add Author link on the book search page (and anywhere else that it's relevant)  from

`http://server:port/addAuthor?AuthorName=John+Doe`
to
`http://server:port/addAuthor?AuthorGRID=54565434`

And then use the AuthorGRID or AuthorGBID to import a specific author rather than a name match.

This would also be useful in the API, as I mentioned earlier :)

**Comment by philborman** [comment]
Had a quick look at the code, and think it should be easy enough to add. 
Hopefully if you have multiple authors in the search results on the 
search page they should have different author IDs. If that's the case we 
jus need to link the buttons to the authorid rather than the author 
name, I will have a closer look in a day or two, bit short of time at 
the mo. Might be as simple as modifying the searchresults.html page

**Comment by DarkSir23** [comment]
I didn't see a method in addAuthor to add by I'd. I'll look at it too :)

**Comment by DarkSir23** [comment]
Observation:  RefreshAuthor takes in an AuthorID, but then re-adds the author to the DB using a name search, which it pulled from the DB.

**Comment by philborman** [comment]
Yes, I've just got some code up and running to do authorid or authorname. Testing it now.
Actually wasn't that tricky to do, just hope I didn't break anything in the process...

**Comment by philborman** [comment]
ok, working fine with goodreads, just need to find how to do it with googlebooks now.
Problem is to get the goodreads id and author info when using googlebooks interface, we use the authorname to look them up, and could hit the same problem of getting the wrong one.
I don't think googlebooks api lets us get the author info we need. Any thoughts?

**Comment by DarkSir23** [comment]
I was wondering about that, too.  I couldn't find decent author info on Google Books.  I wonder how many users actually use Google Books over GoodReads

**Comment by philborman** [comment]
Don't know, but we can use authorid on goodreads and fall back to using
name on googlebooks? No worse than now on google, and better on goodreads.

**Comment by philborman** [comment]
Can this bw closed now,  I think its working here?

**Comment by DarkSir23** [comment]
I believe so :)
