### ISSUE TITLE
PostProcessing Extra Spaces

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#596]
It appears that when a book is moved into a subfolder and renamed for importing to Calibre, it's adding an extra space between the Author's first and last name.  This is causing the book to import into Calibre ok, but then failing to find the book's folder because it's searching for 'First<space><space>Last' instead of 'First<space>Last'

Not sure if the better fix is to make sure there aren't multiple spaces when the book is moved into the temporary folder, or make sure that LL strips out extra spaces when searching for folders :)

**Comment by DarkSir23** [comment]
Caveat:  This has only happened to me with one author, but it happened with every book by the author, regardless of the download source.

**Comment by philborman** [comment]
I think sometimes GoodReads has an extra space in the authors name, 
which might be the source of the problem. Easy enough to strip out, I think.

**Comment by philborman** [comment]
Think I've found all the likely places, probably some un-necessary ones too, but can't harm.
Won't change existing entries, so you may need to remove that one author and reimport.
Probably won't push the new version until tomorrow, but my own git should have it soon.
