### ISSUE TITLE
Windows Version Error

### ISSUE THREAD

**Issue by rutskiuk** [DobyTang/LazyLibrarian#597]
I have noticed that upon my most recent update the installed version has changed from a build number to the word windows. I am running this on another machine and a few days later had the same problem.
I tried reinstalling and had the same problem

From the config page:
Repo: https://github.com/dobytang/lazylibrarian : Branch: Windows
Current Version: Windows Install : Latest Version: WINDOWS INSTALL

Request for an update:
LazyLibrarian is unknown version
Windows Install is not recognised at
https://github.com/dobytang/lazylibrarian Branch: Windows

I have looked at the version.txt file and that shows Windows Install also
Any idea what may have caused this?

**Comment by philborman** [comment]
There was a change to the way version detection was done a few days ago, but should have been fixed after a few hours. Maybe you managed to download the broken version in that short window of opportunity!
I think an upgrade to latest version should fix it, but you may have to upgrade manually.

**Comment by danfozzy** [comment]
Has this happened again? I'm just no receiving errors about running a local version and to push chances to the git. I am not.

Version now says unknown?

**Comment by danfozzy** [comment]
Scratch that I've just restart my system and it's now popped up that it's 2 commits behind. Updated and all good

**Comment by MrMxyzptlk** [comment]
I finally gave up on the internal update mechanism.
I backed up my configuration, and reinstalled LL with the git repository, using 'git clone'.
I now just run 'git pull' to update.

**Comment by philborman** [comment]
Version "unknown" is a new message. We now don't automatically check git on every startup as git has a limit on how often you can check. See issue #559 
We now check the "version.txt" file on startup, and if it's recently been updated we don't ask git if there is a new version until the "new version check" timer goes off, or until you hit the "check version" button on config page.

The internal update mechanism has been changed recently and should be much more robust.

The wierd error that @danfozzy hit pops up from time to time, I've never managed to track it down. It seems your local git program _thinks_ you have modified something, but you haven't.  Usually a git pull (or update) resets your git copy and it's all ok.
