### ISSUE TITLE
Delete magazine deleting more than selected in GUI.

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#601]
Latest Windows Version, logs indicate magazine files deleted and removed from database.

I have upwards of 40 magazines (hundreds of issues).
When the delete is complete LL has deleted the files for the last 20 or so magazines alphabetically from my hard drive, not just the single magazine I had selected in LL.

This has happened before; luckily I have backups of everything.

**Comment by philborman** [comment]
Not enough info to go on,  would probably need to see the logs.

**Comment by MrMxyzptlk** [comment]
Unfortunately it happens randomly, and the debug log isn't normally turned on.
The 'info' log, only listed that the delete was successful; 2 different entries, 1 for removal from hard drive, and 1 for deletion from database.

**Comment by MrMxyzptlk** [comment]
After restoring my accidentally deleted magazines, I tried the whole process again; with debug logging on.
Nothing new in the debug log...this is all LL shows. I have also attached 2 screenshots from my Windows Explorer. The single selection and deletion in LL (VIP Brazil), deleted all magazines after Maxim South Africa (Alphabetically), and kept all of the other magazines.

2017-01-17 07:40:21	INFO	Magazine VIP Brazil removed from database
2017-01-17 07:40:21	INFO	Magazine VIP Brazil deleted from disc

![deleted](https://cloud.githubusercontent.com/assets/1753001/22020970/e43273e6-dc88-11e6-938b-938a364d476c.PNG)
![not deleted](https://cloud.githubusercontent.com/assets/1753001/22020969/e4325f8c-dc88-11e6-8468-de7d6ccc813f.PNG)

**Comment by philborman** [comment]
Puzzled by this, can't reproduce it. Will post a new version with extra debugging messages to try and track it down.

**Comment by philborman** [comment]
Is this issue still happening, if so then debug log should give us more info now

**Comment by MrMxyzptlk** [comment]
I will try deleting a mag again today....

**Comment by MrMxyzptlk** [comment]
I have tried 2 separate deletions and no other magazines were deleted...so I will close this ticket.
This only happens occasionally, so without the debug log on constantly...which I may do, there is no way to know what happened.
