### ISSUE TITLE
Feature Request: Single magazine issues cover photo

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#602]
On magazines where only 1 issue is downloaded, it would be nice to 'drill down' one level in the GUI, and see a magazine cover, just like magazines with multiple downloads; instead of just the "Open", button.

Thank you for this excellent app!!!!

**Comment by philborman** [comment]
Just added code to do this, will post it tonight.
It's switchable, new option in the config settings "Appearance" section of the interface tab.
Default is the old behaviour, untick (and save) to drill down on magazines with single issues

**Comment by MrMxyzptlk** [comment]
Thanks.

**Comment by MrMxyzptlk** [comment]
Working like a charm! Thanks!!!
