### ISSUE TITLE
Feature request: Case insensitive magazine searches and folders...

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#603]
Example: If I search for a new magazine VIP it will not find any if the poster has not capitalized any of the letters. LL will also create a new magazine and folder that is case sensitive. In other words If I search for VIP and Vip it will create 2 different magazines as well as affecting the search.

Would it be possible to make all of this case insensitive?

**Comment by philborman** [comment]
Not easy. LL will create a folder with the name you first give it in the search box, so if you capitalise it the way you want it will stay that way. I can add a check for trying to create a second entry with different capitalisation easy enough, but we have no control over the case sensitivity of the search providers. I think most are case insensitive anyway, and there is no way of specifying in the search methods.

**Comment by MrMxyzptlk** [comment]
I don't necessarily mind that LL creates it with the case sensitivity that I originally type.
The real issue is that when it searches for VIP, and it finds Vip it doesn't match it, or vice versa (Vip to VIP).
Can that issue be fixed easily? I.E. When I search it doesn't matter what case the poster posted the files...

**Comment by philborman** [comment]
Just added code to do a quick case insensitive check before adding new magazines to database so we don't create duplicates, but we have no control over case sensitivity of the search providers.
For example if we ask  dognzb for VIP and it chooses not to send us Vip. If it sends us a mix of VIP and Vip and viP or whatever that's fine as we have always checked the results sent back in a fuzzy case insensitive manner, but as far as I know there is no way of telling dognzb to treat the search term as case insensitive. I think it should automatically be case insensitive anyway. Seems to be that way on the providers I regularly use here. Are you hitting this problem with multiple search providers, or just one (which one?) maybe their search api is different?

**Comment by MrMxyzptlk** [comment]
Ahhh, I now understand the issue. I didn't look into which providers are or are not case sensitive.
I will see if I can find the answer....
