### ISSUE TITLE
Feature request: Option to ignore date 01-01-1970, or edit it before Post Processing

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#605]
If I download a magazine, in this example VIP, and it downloads 3 issues.
Dec 2016, Nov 2016, and Jan 2017. Only 1 is 'entered' in LL, as the date provided for the issues by Usenet is 01-01-1970 for all 3 (I believe that means, none of them had a date associated with them.

I know if would be difficult to parse the dates from the magazine names, especially if the are in a foreign language. That being the case, would it be possible to have a step in the download process where we could manually enter the date, before postprocessing. 

Please let me know if I didn't explain this very well..

**Comment by philborman** [comment]
We do parse the magazine names to extract dates. From what you say above it seems we correctly identified 3 issues by name and downloaded them, but then failed to postprocess?
Full debug log of the postprocessor run should show us whats going on.

If the magazine month names are not English, you will need to add the correct language to lazylibrarian config (in the Importing tab)

**Comment by MrMxyzptlk** [comment]
Yes, exactly what you said.
I don't have that language setup, that must be the problem.
I will add it (Brazil, Spanish?), and let you know.

**Comment by MrMxyzptlk** [comment]
OK, I added all the locales that I wanted, but LL can't 'find' them.
2017-01-17 12:30:24	WARNING	Unable to get a list of alternatives, [Error 2] The system cannot find the file specified
2017-01-17 12:30:24	WARNING	Unable to load requested locale [ru.utf8] unsupported locale setting

I'm not sure how to install these in Python...any idea?

**Comment by philborman** [comment]
If you are on linux you can just do "locale -a" on the command line to get
a list of installed locales. Not sure what the equivalent is for Windows (I
think you're on windows?)
I did find this page on the web, says you need to put the "long" name in
some versions of windows, ie "portuguese-brazil"  not  "ptb"

https://msdn.microsoft.com/en-us/library/39cwe7zf%28vs.71%29.aspx

**Comment by MrMxyzptlk** [comment]
That did it!
Freaking MS always has to do things different than everyone else...

**Comment by philborman** [comment]
That's great, could you write exactly what you had to do and we can add it
to the wiki to help others.

**Comment by MrMxyzptlk** [comment]
LL Windows Locales. This is a newer Microsoft document. https://msdn.microsoft.com/en-us/library/39cwe7zf(v=vs.140).aspx

Look for the language(s) you want from the 'Language string' column, and type them into the 'Languages for month names', under the importing tab in LL. Separate the languages with commas.
Save in LL, then restart LL. Look in the log, it should show that it loaded your various languages.

Example: russian, czech, swedish

**Comment by MrMxyzptlk** [comment]
The first of the test downloads has finished and it is still not processing based on the name.
The date is showing as 1970-01-01 even though the magazine shows "Vip Brazil - Janeiro 2017 - True PDF - 3062 [ECLiPSE]"

**Comment by philborman** [comment]
Date is showing as 1970-01-01 where exactly, in the magazine filename or on the issues page?
I  guess we correctly identified the issues to download unless you did that part manually,  
So did we not get the filename right,  or somehow put the wrong date into the database.

**Comment by MrMxyzptlk** [comment]
Under the latest issue column, but if you look at the filename it was a different date.

Vip Brazil	1	2017-01-17	1970-01-01	Active

**Comment by philborman** [comment]
ok, found the problem, just not sure what to do about it yet.
"Vip Brazil - Janeiro 2017 - True PDF - 3062 [ECLiPSE]"

The parser throws away anything at the end in square brackets [usually posters sig]
throws away certain keywords including True and PDF, and any punctuation, which leaves
Vip Brazil Janeiro 2017 3062 

We then try to get a name and a date or an issue number from what's left, and are not expecting 3062 

I will think about it...

**Comment by MrMxyzptlk** [comment]
Ok Thanks.

**Comment by MrMxyzptlk** [comment]
That did the trick! I successfully downloaded and processed 3 issues from Vip Brazil.
