### ISSUE TITLE
LL appears to be ignoring minimum seeder option?

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#606]
I have a lot of torrent downloads, with 1 or 0 seeders, that LL sent to Deluge, even though I have the option in LL set to minimum of 4?

**Comment by philborman** [comment]
The information on the number of seeders is provided by the search provider, and unfortunately its often out of date, ie the search provider found there were that many seeders last time it looked, but there aren't now.

**Comment by MrMxyzptlk** [comment]
Ok. Thanks.
