### ISSUE TITLE
Feature request: auto refresh for log 'screen'.

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#608]
Headphones has the ability from a dropdown, to enable / disable, and how often the log 'screen' refreshes in the GUI. Currently in LL it is static...

**Comment by philborman** [comment]
There used to be an auto refresh facility in lazylibrarian logger, in fact the code is still in there but blocked out.

Not sure why it got removed, guess someone didn't like it. If I can figure out how to make it switchable I will add it back in. 

If you want to enable the autorefresh yourself to try it, it's at the bottom of the logs.html file, lines masked out with // at the front. 10000 is the timer value in thousandths of a second

         {
             // Refresh the log table
             setInterval(function() {
                 $('#log_table').dataTable().fnDraw();
             }, 10000);
         }

**Comment by MrMxyzptlk** [comment]
Uncommenting and restarting LL or reloading the log page doesn't do anything.
I'm assuming that 10000 is 10 seconds.

**Comment by MrMxyzptlk** [comment]
You could always look at the HeadPhones code base...I believe LL was originally based off of it?

**Comment by philborman** [comment]
Well, that was straightforward enough.

**Comment by MrMxyzptlk** [comment]
Which part? The look at HeadPhones code or...
