### ISSUE TITLE
Separate issues / same magazine have the same cover photo with different front pages?

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#610]
I've had this issue for a while, but since your killing it, I figured I would throw it out.
Using the example of Amped Asia I have 3 or 4 issues that show the same cover photo in LL, but if you open the PDF's they are all different. If I open all of the issues for this mag with Calibre, it shows all the correct cover photos?

**Comment by MrMxyzptlk** [comment]
Nevermind...I believe these are the same issue with different filenames post names.

On another cover creation note. I'm running what worked before...to re create covers...and I'm getting an error: 500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "Z:\Applications\lazylibrarian\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "Z:\Applications\lazylibrarian\cherrypy\lib\encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "Z:\Applications\lazylibrarian\cherrypy\_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "Z:\Applications\lazylibrarian\lazylibrarian\webServe.py", line 1839, in api
    from lazylibrarian.api import Api
  File "Z:\Applications\lazylibrarian\lazylibrarian\api.py", line 616
    addAuthorToDB('', refresh=False, self.id)
SyntaxError: non-keyword arg after keyword arg

**Comment by philborman** [comment]
Yep, that's a bug. Strangely it doesn't happen here. Maybe some versions of
python are more fussy than others?
What version python are you running, just in case its not that.

**Comment by MrMxyzptlk** [comment]
2.7.10

**Comment by philborman** [comment]
Maybe it's that, I'm on 2.7.9
Bug needed fixing anyway,  I have done that one, just looking if there are
any other similar ones lurking.
