### ISSUE TITLE
Missing a list of dependencies that are required to run and use LazyLibrarian on any linux machine

### ISSUE THREAD

**Issue by ziggyke** [DobyTang/LazyLibrarian#613]
Hi DobyTang

I would like to create an unRAID plugin for your project, but I seem to be missing which dependencies that need to be installed for LazyLibrarian to work?

Like found on the SickrageTV project:
https://github.com/SiCKRAGETV/SiCKRAGE/blob/master/requirements.txt

This is needed, because I manually have to point out to the unRAID system which packages that are being used by LazyLibrarian.

Is it possible to provide a bare minimum list of the dependencies with SSL enabled?
I think that the following is needed, but don't know what minimum version:
```
- curl
- python
- git
- sqlite
- openssl
- pyopenssl
- ndg_httpsclient
```
Is this correct or totally wrong?

Thanks for the development and your work!

regards

Kristof

**Comment by philborman** [comment]
Sorry, I have no idea how to do this.
LazyLibrarian needs python v2.7.x 
It is shipped with its own copies of some other libraries, but only because we can't rely on all systems having them installed
It does not need curl or ndg_httpsclient as far as i am aware
git is optional
it uses sqlite3 but nothing very complex, so i think any 3.x version will do.

**Comment by MrMxyzptlk** [comment]
You could always look at the requirements for HeadPhone, as LazyLibrarian is based of the same code.

https://github.com/rembo10/headphones

**Comment by philborman** [comment]
The code diverged from headphones years ago, and we use features headphones doesn't need, like reading the contents of epub mobi or pdf files. You could use the headphones list as a starting point but it could be far from correct.

**Comment by ziggyke** [comment]
ok thx a lot for the comments and feedback, but be sure that the plugin installs and afterwards will work, I need to make sure that all the required libraries, packages, ... are mentioned.

This because my unRAID OS is based on linux Slackware 14.2 and this is the bare minimum of linux distro and you need to point out yourself what the dependencies are for an application that you want to make it work.

So the packages/libraries that I already mentioned are the minimum, but maybe more that is required to make it install on the unRAID OS. Let alone to make it run.

I'll need to make contact with the developers of unRAID if it is possible to grab a debug log if there are still packages/libraries necessary when I try to install and run the created plugin for LayLibrarian.

I could make it much simpler for me and just use the docker version of LazyLibrarian, but in the meantime I want to learn to program normal plugins for unRAID. Instead of using a docker plugin.

**Comment by philborman** [comment]
Hi,
I've been chatting to the guys at docker, and got this suggestion. Hope it helps...

"He can take a look at the Dockerfile for the LazyLibrarian docker and the Dockerfile for the base image, it's using Alpine Linux, so that should cover all the dependencies."

**Comment by ziggyke** [comment]
Hi

Ow great! That's nice to know.
I think that could help and point me out in the correct direction!

I would also make contact with another plugin developer for unRAID which has ported headphones and many others, but unfortunately he disappeared a while now and nobody knows if he's coming back or what happened to him...

For the record, I've already tried with the dependencies I already mentioned, that makes it install and work well in the menu of unRAID OS. Except starting lazylibrarian doesn't work and I haven't been able to know where to look in which log file what is causing to fail to start lazylibrarian... Is it failing because the start script is faulty or is it failing because of missing dependencies... ;-)

I love the support, knowledge, sharing, ... so far that I'm getting from the community!

**Comment by philborman** [comment]
Might be worth running lazylibrarian with debug on, and see if anything 
useful shows in the lazylibrarian logs?

You can pass --debug as a command line option

**Comment by Code-Slave** [comment]
Ok i was bored and parsed through the libraries that are included in /lib for version info


cherrypy v3.6.0
(current is 10.21) https://github.com/cherrypy/cherrypy

apscheduler v2.0.0 rc2
(current is 3.3.1) https://github.com/agronholm/apscheduler

deluge_client
(no version)	   https://github.com/JohnDoee/deluge-client (maybe)

feedparser v5.1.3
(current 5.2.1)    https://github.com/kurtmckee/feedparser

fuzzywuzzy v0.14.0
(current 0.15.0)   https://github.com/seatgeek/fuzzywuzzy						

httlib2	uknown(OLD)
(current 0.10.3 )  https://github.com/httplib2/httplib2				

mobi	uknown

oauth2 1.0
(current 1.0)	   https://github.com/joestump/python-oauth2

pynma v1.0
(current 1.0)	   https://github.com/uskr/pynma

pythontwitter 1.0.1
(current 3.2.1)	   https://github.com/bear/python-twitter	

requests 2.12.4
(current 2.13.0)   https://github.com/kennethreitz/requests

simplejson	3.10.0
(current 3.10.0)   https://github.com/simplejson/simplejson

unrar 0.3
(current 0.3)	   https://github.com/matiasb/python-unrar

BeautifulSoup 3.2.1
(current 4.5.3)	   https://www.crummy.com/software/BeautifulSoup/#Download

configobj 4
validate 1.0.1
(current 5.0.6)	   http://www.voidspace.org.uk/python/configobj.html

csv
No Idea part of standard install?

zipfile
No Idea

**Comment by philborman** [comment]
Not that simple unfortunately. Not all library versions are compatible. For example Beautifulsoup v4.x.x is not compatible with lazylibrarian.

**Comment by Code-Slave** [comment]
Oh I understand. Was just taking the time to compile the versions LL is using and current versions with links. I firmly believe in the dont fix what aint broke. If there is no compelling reason to upgrade then it shouldnt be done

**Comment by philborman** [comment]
Yes, I agree entirely.
Several of the libraries could be easily upgraded (fuzzywuzzy, feedparser,
requests) just pretty much drop in replacements.
twitter is harder and I'm unable to test it (don't have a twitter account)
apscheduler needs a little tweaking to work but I think there's no
advantage in updating, it's fairly trivial improvements to the scheduler
and some additional features we don't use/need
deluge, httplib2 and configobj are already on current versions
cherrypy and beautifulsoup need considerable changes to lazylibrarian to
get them to work. Not sure if it's worth it, there could be security and
bugfixing advantages to upgrading but it's not a priority. Main problem is
that they both pull in additional libraries that the earlier versions don't
use, and we would need to include those libraries in lazylibrarian too as
we can't be sure the target systems will have them included as standard. In
particular many NAS systems are well out of date and run bare minimum
software.
