### ISSUE TITLE
Error on API magazine cover creation

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#614]
I'm running what worked before...to re create covers...and I'm getting an error: 500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
File "Z:\Applications\lazylibrarian\cherrypy_cprequest.py", line 670, in respond
response.body = self.handler()
File "Z:\Applications\lazylibrarian\cherrypy\lib\encoding.py", line 217, in call
self.body = self.oldhandler(*args, **kwargs)
File "Z:\Applications\lazylibrarian\cherrypy_cpdispatch.py", line 61, in call
return self.callable(*self.args, **self.kwargs)
File "Z:\Applications\lazylibrarian\lazylibrarian\webServe.py", line 1839, in api
from lazylibrarian.api import Api
File "Z:\Applications\lazylibrarian\lazylibrarian\api.py", line 616
addAuthorToDB('', refresh=False, self.id)
SyntaxError: non-keyword arg after keyword arg

**Comment by MrMxyzptlk** [comment]
I checked my Python version 2.7.10 so I upgraded to the latest v2.
2.7.13

Still getting the same error...

**Comment by philborman** [comment]
I guess the problem is that the version of python I have is not so fussy.
I've fixed the bug and pushed a new version of lazylibrarian

**Comment by MrMxyzptlk** [comment]
Are you using 3.x instead of 2?

**Comment by philborman** [comment]
2.7.9
I might try upgrading to 2.7.13 here.
Lazylibrarian won't work on python 3, too many changes needed. 
I did look at porting it over but gave up!

As I said earier, the bug needed to be fixed anyway, done now. If you upgrade to latest lazylibrarian it should be ok.

**Comment by MrMxyzptlk** [comment]
OK, now it ran successfully. It appears to have created the missing covers, but it didn't update in the GUI. I tried running a library scan, but no go. Your thoughts?

**Comment by MrMxyzptlk** [comment]
I'm going to close this and just use the 1 issue you are working now, as I'm certain that issue 'Pattern matching' is causing the cover creation issue for certain mag issues.
