### ISSUE TITLE
Feature request: Covers on 'Author' page and Home page...

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#618]
On the 'books' page you have a book cover in the first column.
How about an author cover on the 'author' page in the first column, and on the LL home screen how about author and book covers in the appropriate columns (maybe an additional column before author and book)?

It would make it more consistent across the pages?

**Comment by philborman** [comment]
Tried that, but it looked too cluttered for me, it's a simple change to the html but I didn't think it looked good.

**Comment by MrMxyzptlk** [comment]
OK....

**Comment by philborman** [comment]
Had another look at this and did a mockup, what do you think? First one is bookstrap, second default interface

![screenshot from 2017-01-21 12-29-01](https://cloud.githubusercontent.com/assets/12158777/22174071/5bc4cb6c-dfd5-11e6-9732-2bfa7609d4b1.png)
![screenshot from 2017-01-21 12-29-45](https://cloud.githubusercontent.com/assets/12158777/22174072/5bc5e826-dfd5-11e6-8fd2-7c16d3308197.png)

**Comment by MrMxyzptlk** [comment]
Yeah, it does look kind of busy. What if you do it just like the 'Books' page.
Where you have the cover column as the first column, and it is a book cover.

On the 'Authors' page, make just the first column the cover column, and make it an author cover.
It will be consistent with the book page, and less busy, IMO?

**Comment by philborman** [comment]
ok done now. Also added magazine latest issue cover on magazine page

**Comment by MrMxyzptlk** [comment]
That looks perfect! Not cluttered and consistent interface, thanks.

The last comment I would have on this matter, is that your home page and the author page are one and the same. Do you need both? Maybe the landing page is authors, and the LazyLibrarian link at the top left goes to github?

**Comment by philborman** [comment]
Actually they are not quite the same. The landing page is only Authors
after startup is complete. Before that it links to a "database is
upgrading" page

**Comment by MrMxyzptlk** [comment]
Got it!

Thanks for everything...LL is now rocking!
