### ISSUE TITLE
Missing JPGs

### ISSUE THREAD

**Issue by hctancredi** [DobyTang/LazyLibrarian#628]
Hi.

I noticed that I got a few Author and Books images. Is there a way to refresh it without deleting and adding the book/author again?

Thanks

**Comment by hctancredi** [comment]
I've tried to refresh author but no lucky btw.

**Comment by philborman** [comment]
There are some api commands to refresh the images, the wait parameter is
recommended as they can take a while to run.
 If you haven't used the api before, see the wiki for help. Shouldn't
normally need to use these commands though, the covers and images should be
created automatically. Probably either a database upgrade failed to
complete, or network connectivity issues.  The "get" commands fetch from
the internet, the "create" one reads the magazine file and extracts from
that.

getBookCovers&wait
getAuthorImages&wait
createMagCovers&wait

**Comment by hctancredi** [comment]
Followed your instructions. I had to clear cache before though. thanks a lot.
