### ISSUE TITLE
LL not creating mag covers with API command

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#634]
So as you know we worked through this a couple of week ago, and mag cover creation was working.

I have a few magazines that don't have covers, or have the wrong cover.
So I ran the API command, and it is 'stuck' on creation now for almost an hour?

Here is the debug log, it never gets to completed.

2017-02-01 10:25:49	INFO	Checking covers for 582 issues
2017-02-01 10:25:49	INFO	Received API command: createMagCovers {}

**Comment by philborman** [comment]
ok, there is progress reporting if it hits a problem, but no progress
reports if its ok until the end.
I will add more debug lines to see where its getting stuck. Can't reproduce
it here.

**Comment by MrMxyzptlk** [comment]
Thanks...it's still running by the way.

**Comment by philborman** [comment]
New version in my git has extra debugging messages in the log during cover
creation. If you turn debug logging on before running the api
createMagCovers command we should see what's going wrong.

**Comment by Code-Slave** [comment]
May be related but this error gets thrown when its trying to do covers

Unhandled exception in processDir: Traceback (most recent call last): File "/Volumes/mcb10tb/_code/LazyLibrarian/lazylibrarian/postprocess.py", line 434, in processDir "LatestCover": os.path.splitext(dest_file)[0] + '.jpg', UnboundLocalError: local variable 'dest_file' referenced before assignment

**Comment by philborman** [comment]
@Code-Slave 
You are not on latest update, that bug was fixed 8 days ago with commit 43c573c  8 days ago :-)

I think the bug reported by MrMxyzptlk is related to cbr or cbz files but need more debugging info to fix it. Possibly an unreadable archive?

**Comment by MrMxyzptlk** [comment]
I ran gswin64c manually on the command line, using the switches that we had used previously.
It created the covers for all 4 issues no problem?

I will go ahead and close this for the moment, as it is a very minor 'issue'.
