### ISSUE TITLE
Freenas update

### ISSUE THREAD

**Issue by VarunChugh** [DobyTang/LazyLibrarian#653]
The freenas version of Lazy Librarian is not updating. On clicking update, the update runs in the background but the update doesn't actually happen. The current version remains the same.

**Comment by philborman** [comment]
Debug log might help track it down, freenas is a 3rd party package though, maybe auto update is disabled and you need to upgrade the freenas package rather than use the internal upgrade?

**Comment by VarunChugh** [comment]
Have always used the internal update to-date. The issue has only started recently, says I am 95 commits behind, was fine before that.

**Comment by VarunChugh** [comment]
Think the last discussion on this thread talks about this - https://forums.freenas.org/index.php?threads/lazylibrarian-in-9-2.16813/

**Comment by philborman** [comment]
95 is a __Long__ way behind. Guess something is wrong with the version file?
A debug log of the upgrade attempt would help.

**Comment by VarunChugh** [comment]
so I tried the below steps (found in the link shared above) and everything works fine now and version is uptodate. Thanks

`service lazylibrarian onestop

rm -r /usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian

fetch --no-verify-peer "https://github.com/DobyTang/LazyLibrarian/archive/master.tar.gz"

tar xzf master.tar.gz

mv LazyLibrarian-master /usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian

chown -R media:media /usr/pbi/sickrage-amd64/share/lazylibrarian/LazyLibrarian

rm master.tar.gz

service lazylibrarian start`

**Comment by philborman** [comment]
Thanks, I will add that to the wiki for other users.
Would be better if we could find the problem and fix it though.
