### ISSUE TITLE
Request: Expanded torrent downloaders

### ISSUE THREAD

**Issue by ATor69** [DobyTang/LazyLibrarian#658]
Any chance to expand the torrent providers for LL to include book specific providers, such as MAM.

**Comment by philborman** [comment]
Possibly. Do you have a url for them, and are they open for new accounts?
If they have an api that would be easiest, otherwise we can scrape the html pages for results.

**Comment by ATor69** [comment]
MAM is a private tracker, but they do have bi-weekly IRC invites/interviews.  Took a quick look and it doesn't appear to have any API in place.

Site is:

https://www.myanonamouse.net/

Invite/Interview Information is:

https://www.myanonamouse.net/inviteapp.php

**Comment by philborman** [comment]
Ok,  thanks for the info. I'll try to get an invite and have a look at how to implement it.

**Comment by neilicious** [comment]
@ATor69 it is possible to search MAM at the moment if you set set it up using [jackett](https://github.com/Jackett/Jackett) and then add it as a torznab provider.

@philborman if you'd like an invitation to join MAM let me know and I'll be happy to send you one

**Comment by philborman** [comment]
Would be useful, I missed the last invite window.
Actually if you don't mind, probably all I need is an example search string and a html page of results?
The search string can be read from the debug log, a line like this...
Parsing results from <a href="https://drunkenslug.com/api?q=+The+Abominable+Showman&apikey=XXXXX&t=search&extended=1">https://drunkenslug.com</a>
or 
Parsing results from <a href="http://limetorrents.cc/searchrss/other/?q=+The+Abominable+Showman">Limetorrent</a>
and if you feed the bit between quotes into a browser, select "view source" and save the resulting page that would do. I can then scan the search string and html and extract the bits lazylibrarian needs.

**Comment by neilicious** [comment]
I think because I'm using jackett as an intermediary I can't get the information you need from my debug logs. All of the searches shown in it just refer back to the psuedo-api that jackett creates rather than a search string for the site itself. Sorry.
If you can let me know your email address I'll have an invite sent across this afternoon.

**Comment by philborman** [comment]
Ah yes, of course.   An invite would be useful then, my email is
phil.borman@gmail.com

Thanks

**Comment by philborman** [comment]
@neilicious thanks for the invite. Unfortunately !'m having no luck getting searches working outside of the web browser. Looks like they do something clever with the html pages, as the source page doesn't include the table info that we need to extract search results from. It's on screen, but not in the page source, not sure how to get around that. Lazylibrarian seems to be working with the myanonamouse rss feeds though. Might be the best we can do for now. I'll have a look around if anyone else has managed to do it.

**Comment by philborman** [comment]
Well, I've spent quite a bit of time trying to get this to work with no joy. The only bit that's working are the rss feeds. It's too far outside my experience, so I think it's best to leave this to jackett or the rss feeds, sorry.  Maybe someone with more html experience could get it going...
