### ISSUE TITLE
Multiple authors, one book?

### ISSUE THREAD

**Issue by wizzy99** [DobyTang/LazyLibrarian#659]
Scenario is a book has two authors.  Author A was added to LL first, so book is associated with that author profile, however Author B is the first "named" author in the ebook metadata.  LL fails because it can't find the book under Author B, and the book cannot be added to Author B because it's already associated with Author A in the database.  Searching for the book via the search box in the far upper right hand corner shows the author as Author B.

The log file entry was 
	Failed to match book [Book Name] by [Author B] in database
When refreshing Author B to get the missing book
       Rejecting bookid 123456 for [Author B][Book Name] already got bookid for [Author A][Book Name]

Is the only approach to log in the debug log and then update the metadata?  Any chance that a book can be associated with multiple authors?

**Comment by philborman** [comment]
You can "move" the book from author A to author B manually using the edit
feature on author A page.  At the moment that's the best lazylibrarian can
do.

I hit this problem with cookery books by  a couple of motorcycle
enthusiasts called "The Hairy Bikers".  Some of their books have the author
as "Si King and Dave Myers", some "Dave Myers & Si King", some only have
one of them named in the metadata but both on the cover,  and some have the
author as "The Hairy Bikers".  Not sure how to automate this, any
suggestions welcome!

**Comment by alagave** [comment]
This sounds like a "translation database" opportunity. i see it similar to the issue of changed legal names or criminal aliases. Decades ago this would have been treated as a circular linked list but now databases hide all that complexity. Essentially, in this case, The Hairy Bikers is the primary entry and it has two sub entries, Si King and Dave Myers. Any query involving both children, in any order, will point back to the alias of Hairy Bikers so they can be recognized as aliases. This also allows a reference to one author to be investigated as a possible match to the primary entry.

This can perhaps also be used to address the "Writing as" author problem. Even though we know author A wrote as author B during a certain time period, books are still reissued with one or the others name depending  on the publishers whim.

To get really complicated, how about known ghost writers? Interesting problem best left for another day - or decade.

**Comment by philborman** [comment]
Development has moved to [GitLab](https://lazylibrarian.gitlab.io/)
All open issues have been moved over to [LazyLibrarian Issues](https://gitlab.com/LazyLibrarian/LazyLibrarian/issues)
Please open any new issues or comments on the new repo as the old one is no longer maintained, thanks
