### ISSUE TITLE
Request - Possible to search Providers without series name 

### ISSUE THREAD

**Issue by sbelongie** [DobyTang/LazyLibrarian#663]
It seems that by default LazyLibrarian searches the providers as Author - book - series 
I have found that I am not able to get many results this way.  When trying to search my providers manually with Author - book I get a lot more results.
If there is a better way of searching the provider let me know if I am missing something

**Comment by philborman** [comment]
Lazylibrarian does several searches, and stops when it gets a result that's
over the "percentage match" threshold.
first search looks in the "books" categories for the author and full title
as stored in the database. This may or not include the series depending on
the database entry.
If no results we try searching the books categories again using just the
author surname and the book title without series.
If still no results we try a "general" search ignoring book categories.

The idea was that the searches get less specific, so we hopefully get the
closest match by preferring results with the most matching data. There is a
bit more to it than that, fuzzy word matching, downgrading results with
excess words in the title, but overall we should get the closest match.

If you put debug logging on you should see the various searches logged.
They are named book, shortbook, general, shortgeneral.

If there is a better way of refining the results I'm open to suggestions.
Still learning.

**Comment by sbelongie** [comment]
ok I will look at the debug log to see if I can come up with some more ideas.
Thanks for the rundown on how the search works.

**Comment by Code-Slave** [comment]
This is where I have been looking at the code. For a book search on say TPB if its just a title search ill find it (by hand) but LL doesnt as it adds author to the search. I see the reasoning behind it for sure Im just trying to come up with a way to filter the trash out

**Comment by philborman** [comment]
I could add another search. Only use it if no results from the earlier
searches? Might end up with the right title but wrong author though.

**Comment by sbelongie** [comment]
could you add a search function that is like sonarr or radarr that you could pick from a list of results?

**Comment by philborman** [comment]
ok, added that. Just a bit more testing, should be ok to release a new version tomorrow.
To manually search, select "manual" for the book you want, you can edit title / change author etc, and also search for matches on author/title or just title, or just author. Searches can take a while, no updates until searches are complete, then select "snatch" next to the one you want to download.

**Comment by sbelongie** [comment]
I must be dumb or something. I don't see the manual search.

**Comment by philborman** [comment]
You need to be on latest version

Go to "books"  (you can also do it from each authors page of books)

  Under each book title there is GoodReads LibraryThing Manual

Not all 3 are available for all books.  Click on Manual to get the edit 
page for that book.

Top of edit page are search buttons.

**Comment by Code-Slave** [comment]
Yea thats the challenge with the torrent search. However doing some tests by hand I dont see many "duplicate" titles by different authors in responses. Granted it depends on the book of course
