### ISSUE TITLE
Parameter issue  - snatching audiobooks

### ISSUE THREAD

**Issue by Hydro-guy** [DobyTang/LazyLibrarian#664]
Me again - with dognzb.cr indexer - getting incorrect parameter error on initial search.  General search returns match but on audiobook - would have thought maxsize would kill that.

23-Feb-2017 10:42:26 - INFO    :: WEBSERVER : Status set to "Wanted" for "Wind Riders Oath"
23-Feb-2017 10:42:26 - INFO    :: WEBSERVER : Status set to "Wanted" for "Oath of Swords"
23-Feb-2017 10:42:26 - INFO    :: WEBSERVER : Status set to "Wanted" for "The War Gods Own"
23-Feb-2017 10:42:26 - INFO    :: WEBSERVER : Status set to "Wanted" for "War Maids Choice"
23-Feb-2017 10:42:27 - INFO    :: SEARCHNZB : NZB Searching for 4 books
23-Feb-2017 10:42:27 - DEBUG   :: SEARCHNZB : Using stored capabilities for http://mynzbs4u.com
23-Feb-2017 10:42:27 - DEBUG   :: SEARCHNZB : [IterateOverNewzNabSites] - http://mynzbs4u.com
23-Feb-2017 10:42:27 - DEBUG   :: SEARCHNZB : [NewzNabPlus] searchType [book] with Host [http://mynzbs4u.com] mode [nzb] using api [XX] for item [{'bookSub': u'(War God, #3)', 'searchterm': u'David Weber Wind Riders Oath: (War God, #3)', 'bookName': u'Wind Riders Oath', 'authorName': u'David Weber', 'bookid': u'17320'}]
23-Feb-2017 10:42:27 - DEBUG   :: SEARCHNZB : [NewzNabPlus] - nzb No matching search parameters
23-Feb-2017 10:42:27 - DEBUG   :: SEARCHNZB : Using stored capabilities for http://api.nzb.su
23-Feb-2017 10:42:27 - DEBUG   :: SEARCHNZB : [IterateOverNewzNabSites] - http://api.nzb.su
23-Feb-2017 10:42:27 - DEBUG   :: SEARCHNZB : [NewzNabPlus] searchType [book] with Host [http://api.nzb.su] mode [nzb] using api [XX] for item [{'bookSub': u'(War God, #3)', 'searchterm': u'David Weber Wind Riders Oath: (War God, #3)', 'bookName': u'Wind Riders Oath', 'authorName': u'David Weber', 'bookid': u'17320'}]
23-Feb-2017 10:42:27 - DEBUG   :: SEARCHNZB : [NewzNabPlus] - nzb Search parameters set to {'author': u'David Weber', 'apikey': u'XX', 't': u'book', 'cat': u'7000,7020', 'title': u'Wind Riders Oath'}
23-Feb-2017 10:42:27 - DEBUG   :: SEARCHNZB : [NewzNabPlus] URL = http://api.nzb.su/api?author=David+Weber&apikey=XX&t=book&cat=7000%2C7020&title=Wind+Riders+Oath
23-Feb-2017 10:42:27 - DEBUG   :: SEARCHNZB : Parsing results from <a href="http://api.nzb.su/api?author=David+Weber&apikey=XX&t=book&cat=7000%2C7020&title=Wind+Riders+Oath">http://api.nzb.su</a>
23-Feb-2017 10:42:27 - DEBUG   :: SEARCHNZB : Found 0 nzb at http://api.nzb.su for: David Weber Wind Riders Oath: (War God, #3)
23-Feb-2017 10:42:27 - DEBUG   :: SEARCHNZB : Using stored capabilities for https://api.dognzb.cr
23-Feb-2017 10:42:27 - DEBUG   :: SEARCHNZB : [IterateOverNewzNabSites] - https://api.dognzb.cr
23-Feb-2017 10:42:27 - DEBUG   :: SEARCHNZB : [NewzNabPlus] searchType [book] with Host [https://api.dognzb.cr] mode [nzb] using api [XX] for item [{'bookSub': u'(War God, #3)', 'searchterm': u'David Weber Wind Riders Oath: (War God, #3)', 'bookName': u'Wind Riders Oath', 'authorName': u'David Weber', 'bookid': u'17320'}]
23-Feb-2017 10:42:27 - DEBUG   :: SEARCHNZB : [NewzNabPlus] - nzb Search parameters set to {'author': u'David Weber', 'apikey': u'XX', 't': u'book', 'cat': u'7000,7020', 'title': u'Wind Riders Oath'}
23-Feb-2017 10:42:27 - DEBUG   :: SEARCHNZB : [NewzNabPlus] URL = https://api.dognzb.cr/api?author=David+Weber&apikey=XX&t=book&cat=7000%2C7020&title=Wind+Riders+Oath
23-Feb-2017 10:42:28 - DEBUG   :: SEARCHNZB : Parsing results from <a href="https://api.dognzb.cr/api?author=David+Weber&apikey=XX&t=book&cat=7000%2C7020&title=Wind+Riders+Oath">https://api.dognzb.cr</a>
23-Feb-2017 10:42:28 - ERROR   :: SEARCHNZB : https://api.dognzb.cr - Incorrect parameter
23-Feb-2017 10:42:28 - DEBUG   :: SEARCHNZB : No nzb's found for [David Weber Wind Riders Oath: (War God, #3)] using searchtype book
23-Feb-2017 10:42:28 - DEBUG   :: SEARCHNZB : Using stored capabilities for http://mynzbs4u.com
23-Feb-2017 10:42:28 - DEBUG   :: SEARCHNZB : [IterateOverNewzNabSites] - http://mynzbs4u.com
23-Feb-2017 10:42:28 - DEBUG   :: SEARCHNZB : [NewzNabPlus] searchType [general] with Host [http://mynzbs4u.com] mode [nzb] using api [XX] for item [{'bookSub': u'(War God, #3)', 'searchterm': u'David Weber Wind Riders Oath: (War God, #3)', 'bookName': u'Wind Riders Oath', 'authorName': u'David Weber', 'bookid': u'17320'}]
23-Feb-2017 10:42:28 - DEBUG   :: SEARCHNZB : [NewzNabPlus] - nzb Search parameters set to {'q': u'David Weber Wind Riders Oath: (War God, #3)', 'apikey': u'XX', 't': u'search', 'extended': u'1'}
23-Feb-2017 10:42:28 - DEBUG   :: SEARCHNZB : [NewzNabPlus] URL = http://mynzbs4u.com/api?q=David+Weber+Wind+Riders+Oath%3A+%28War+God%2C+%233%29&apikey=XX&t=search&extended=1
23-Feb-2017 10:42:28 - DEBUG   :: SEARCHNZB : Parsing results from <a href="http://mynzbs4u.com/api?q=David+Weber+Wind+Riders+Oath%3A+%28War+God%2C+%233%29&apikey=XX&t=search&extended=1">http://mynzbs4u.com</a>
23-Feb-2017 10:42:28 - DEBUG   :: SEARCHNZB : Found 0 nzb at http://mynzbs4u.com for: David Weber Wind Riders Oath: (War God, #3)
23-Feb-2017 10:42:28 - DEBUG   :: SEARCHNZB : Using stored capabilities for http://api.nzb.su
23-Feb-2017 10:42:28 - DEBUG   :: SEARCHNZB : [IterateOverNewzNabSites] - http://api.nzb.su
23-Feb-2017 10:42:28 - DEBUG   :: SEARCHNZB : [NewzNabPlus] searchType [general] with Host [http://api.nzb.su] mode [nzb] using api [XX] for item [{'bookSub': u'(War God, #3)', 'searchterm': u'David Weber Wind Riders Oath: (War God, #3)', 'bookName': u'Wind Riders Oath', 'authorName': u'David Weber', 'bookid': u'17320'}]
23-Feb-2017 10:42:29 - DEBUG   :: SEARCHNZB : [NewzNabPlus] - nzb Search parameters set to {'q': u'David Weber Wind Riders Oath: (War God, #3)', 'apikey': u'XX', 't': u'search', 'extended': u'1'}
23-Feb-2017 10:42:29 - DEBUG   :: SEARCHNZB : [NewzNabPlus] URL = http://api.nzb.su/api?q=David+Weber+Wind+Riders+Oath%3A+%28War+God%2C+%233%29&apikey=XX&t=search&extended=1
23-Feb-2017 10:42:29 - DEBUG   :: SEARCHNZB : Parsing results from <a href="http://api.nzb.su/api?q=David+Weber+Wind+Riders+Oath%3A+%28War+God%2C+%233%29&apikey=XX&t=search&extended=1">http://api.nzb.su</a>
23-Feb-2017 10:42:29 - DEBUG   :: SEARCHNZB : Found 0 nzb at http://api.nzb.su for: David Weber Wind Riders Oath: (War God, #3)
23-Feb-2017 10:42:29 - DEBUG   :: SEARCHNZB : Using stored capabilities for https://api.dognzb.cr
23-Feb-2017 10:42:29 - DEBUG   :: SEARCHNZB : [IterateOverNewzNabSites] - https://api.dognzb.cr
23-Feb-2017 10:42:29 - DEBUG   :: SEARCHNZB : [NewzNabPlus] searchType [general] with Host [https://api.dognzb.cr] mode [nzb] using api [XX] for item [{'bookSub': u'(War God, #3)', 'searchterm': u'David Weber Wind Riders Oath: (War God, #3)', 'bookName': u'Wind Riders Oath', 'authorName': u'David Weber', 'bookid': u'17320'}]
23-Feb-2017 10:42:29 - DEBUG   :: SEARCHNZB : [NewzNabPlus] - nzb Search parameters set to {'q': u'David Weber Wind Riders Oath: (War God, #3)', 'apikey': u'XX', 't': u'search', 'extended': u'1'}
23-Feb-2017 10:42:29 - DEBUG   :: SEARCHNZB : [NewzNabPlus] URL = https://api.dognzb.cr/api?q=David+Weber+Wind+Riders+Oath%3A+%28War+God%2C+%233%29&apikey=XX&t=search&extended=1
23-Feb-2017 10:42:31 - DEBUG   :: SEARCHNZB : Parsing results from <a href="https://api.dognzb.cr/api?q=David+Weber+Wind+Riders+Oath%3A+%28War+God%2C+%233%29&apikey=XX&t=search&extended=1">https://api.dognzb.cr</a>
23-Feb-2017 10:42:31 - DEBUG   :: SEARCHNZB : [NewzNabPlus] - result fields from NZB are {'bookid': u'17320', 'nzbmode': 'nzb', 'nzbdate': 'Mon, 16 Mar 2015 11:07:52 -0600', 'nzbtitle': 'David.Weber.-.War.God,.Bk.3.-.Wind.Riders.Oath.NMR', 'nzbsize': '725658384', 'nzburl': 'https://dognzb.cr/fetch/653fd39194b7b83bc4b8f605d645a667/XX', 'nzbprov': u'https://api.dognzb.cr'}
23-Feb-2017 10:42:31 - DEBUG   :: SEARCHNZB : Found 1 nzb at https://api.dognzb.cr for: David Weber Wind Riders Oath: (War God, #3)
23-Feb-2017 10:42:31 - DEBUG   :: SEARCHNZB : NZB author/book Match: 100/100 for David Weber War God Bk Wind Riders Oath NMR
23-Feb-2017 10:42:31 - INFO    :: SEARCHNZB : Best NZB match (96%): David Weber War God Bk Wind Riders Oath NMR using general search
23-Feb-2017 10:42:31 - DEBUG   :: SEARCHNZB : David Weber War God Bk Wind Riders Oath NMR adding to wanted

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

**Comment by philborman** [comment]
Looks like mynzbs4u.com does not support "book" search. If you go to their entry in config -> parameters you can disable booksearch for them. We check for several messages like "unknown parameter" to try and trap this, but I guess we don't check for  "No matching search parameters" which is what mynzbs4u sends us. I will add this.

Second point is the audiobook. We don't send the restrictions (size, extension etc) to the search providers as most don't offer that capability. We send a plain search term, then filter the results , so it should reject if the nzbsize is too large or too small. What are your configured settings for book size?

**Comment by Hydro-guy** [comment]
It was dognzb that was throwing the parameter error.  Given that this is one of the recommended indexers - I wondered what the issue was.  Couldn’t tell from log if it was an specification error or just an unsupported call.  

 

Audiobooks – will be ignored from now on – set the book size.  Had seen variable in code when looking at a merge – assumed hard coded and didn’t follow up.  My bad and you can close issue.

 

Thanks John
