### ISSUE TITLE
Request: Add Provider Preference

### ISSUE THREAD

**Issue by neilicious** [DobyTang/LazyLibrarian#669]
It would be handy if it were possible to control where LL downloads from when a matching result is found at more than one provider. 
I'm assuming that currently LL is generating a score for each match and that it then takes whichever is highest. But if it were feasible it would be great to have something akin to the couchpotato system where you can add an amount to the score for each provider so that you have more control as to where your downloads are coming from. This could be checked after the download match ratio has been met so that the additional scoring doesn't cause you to snatch something that you wouldn't have otherwise.

**Comment by philborman** [comment]
Not so easy to do. We run nzb, torrent and rss searches concurrently in separate tasks, and pick the best match from whichever search completes first. Also rss search runs more often than nzb/tor as the rss feeds change more frequently. We could prefer one nzb source over another, one tor over another, but hard to prefer a tor over nzb or vice-versa without a fairly major rewrite of the search results code.

**Comment by neilicious** [comment]
Yeah, I'd forgotten that each of the search types run separately. I think if you start putting in preferences per type then the interface maybe gets a bit messy so probably best to leave as is. Thanks for giving it a look though.
