### ISSUE TITLE
Feature request : Add the possibility to not download book not yet published

### ISSUE THREAD

**Issue by yongbi85** [DobyTang/LazyLibrarian#671]
Hello,

Goodreads is full of article on books yet to be published which pollutes the database.
Would it be possible to add an option so when you add an author it checks and only load books with publishing date NULL or < datetime()
Whenever it refreshes author it would anyway load any books which was published meanwhile.

Thanks for your hard work.

**Comment by philborman** [comment]
Maybe. Not sure if goodreads includes that info in the json responses I
would have to check.

**Comment by philborman** [comment]
Looks like googlebooks and goodreads both allow future publication date  but both will return no publication date for "unknown" which is not good. We put "0000" for any books that goodreads doesn't supply a date. I did a quick check on my database and found I have over 200 ebooks in my library where goodreads doesn't know the publication date, but the book has obviously been published, I've got it.
The following sql query will show the problem if you want to try it...
select count('bookid') as counter from books where bookdate is "0000" and bookfile is not null and bookfile is not "";

Might be worth adding "ignore future dates" but adding a check for NULL is going to cause problems.

**Comment by yongbi85** [comment]
Well if you can add ignore future dates that would still be great. Thanks again.

**Comment by philborman** [comment]
ok, that's in the next version. Running some tests overnight, will push a new version tomorrow assuming the tests are all ok.

**Comment by philborman** [comment]
Included in latest release. If its working for you as expected, can this issue be closed now?
Thanks

**Comment by yongbi85** [comment]
Hello, not sure if it is working at least it is not on refresh author. Will test by adding a new author and see what it does.

**Comment by philborman** [comment]
Ok thanks. I tried it here by deleting a couple of authors and re-adding
them and it seemed to be working.
