### ISSUE TITLE
Issue with pushbullet notifications

### ISSUE THREAD

**Issue by AndyHazz** [DobyTang/LazyLibrarian#675]
Whenever a pushbullet notification is triggered (either clicking the 'Test pushbullet' button in notification settings, or by an event setup to trigger notification), the notification doesn't get sent and this error appears in the logs:

`Unhandled exception in processDir: Traceback (most recent call last): File "/opt/lazylibrarian/lazylibrarian/postprocess.py", line 492, in processDir notify_download("%s from %s at %s" % (global_name, book['NZBprov'], now())) File "/opt/lazylibrarian/lazylibrarian/notifiers/__init__.py", line 52, in notify_download n.notify_download(title) File "/opt/lazylibrarian/lazylibrarian/notifiers/pushbullet.py", line 93, in notify_download self._notify(message=title, event=notifyStrings[NOTIFY_DOWNLOAD]) File "/opt/lazylibrarian/lazylibrarian/notifiers/pushbullet.py", line 81, in _notify return self._sendPushbullet(message, event, pushbullet_token, pushbullet_deviceid) File "/opt/lazylibrarian/lazylibrarian/notifiers/pushbullet.py", line 58, in _sendPushbullet push = pb.pushNote(pushbullet_deviceid, str(event), str(message)) File "/opt/lazylibrarian/lazylibrarian/notifiers/pushbullet2.py", line 89, in pushNote return self._request("POST", HOST + "/pushes", data) File "/opt/lazylibrarian/lazylibrarian/notifiers/pushbullet2.py", line 42, in _request auth=HTTPBasicAuth(self.apiKey, "")) File "/opt/lazylibrarian/lib/requests/api.py", line 56, in request return session.request(method=method, url=url, **kwargs) File "/opt/lazylibrarian/lib/requests/sessions.py", line 488, in request resp = self.send(prep, **send_kwargs) File "/opt/lazylibrarian/lib/requests/sessions.py", line 609, in send r = adapter.send(request, **kwargs) File "/opt/lazylibrarian/lib/requests/adapters.py", line 423, in send timeout=timeout File "/opt/lazylibrarian/lib/requests/packages/urllib3/connectionpool.py", line 594, in urlopen chunked=chunked) File "/opt/lazylibrarian/lib/requests/packages/urllib3/connectionpool.py", line 350, in _make_request self._validate_conn(conn) File "/opt/lazylibrarian/lib/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn conn.connect() File "/opt/lazylibrarian/lib/requests/packages/urllib3/connection.py", line 330, in connect cert = self.sock.getpeercert() File "/opt/lazylibrarian/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert 'subjectAltName': get_subj_alt_name(x509) File "/opt/lazylibrarian/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 166, in get_subj_alt_name cert = _Certificate(openssl_backend, peer_cert._x509) AttributeError: 'X509' object has no attribute '_x509'`

Maybe /opt/lazylibrarian/lib/requests/packages/urllib3/contrib/pyopenssl.py needs updating?

### Source of your LazyLibrarian installation (git)

**Comment by philborman** [comment]
That's odd, i use pushbullet all the time. I'm on a raspberry pi 3 running osmc (debian jessie) 
I will trap the error and warn about it for now while I look into it. 

You should be using the same libraries as here,  so not sure what's going on yet.

**Comment by AndyHazz** [comment]
Other factors might be that I'm using nginx reverse proxy to serve lazylibrarian from a webroot, with letsencrypt ssl.

I have other packages running on the same server (including headphones that I think lazylibrarian was originally based on?) that can send pushbullet messages ok ...

**Comment by philborman** [comment]
Could be the let's encrypt ssl, I haven't tried ssl with lazylibrarian

**Comment by philborman** [comment]
UPDATE
Looks like it might be a missing a python module, cryptography. Maybe it's
not installed by default in raspbian?
It's not installed with lazylibrarian and is only used in ssl communication
in pushbullet and maybe deluge. Might be as simple as installing the
missing module with "pip install cryptography"

**Comment by AndyHazz** [comment]
I've just installed that, looks like it wasn't previously installed, but I'm still getting the same error. Might there be any other missing modules?

**Comment by AndyHazz** [comment]
maybe not exactly the same error - here's what I'm getting now:

`Unhandled exception in search_nzb_book: Traceback (most recent call last): File "/opt/lazylibrarian/lazylibrarian/searchnzb.py", line 97, in search_nzb_book found = processResultList(resultlist, book, "book") File "/opt/lazylibrarian/lazylibrarian/searchnzb.py", line 238, in processResultList (newValueDict["NZBtitle"], newValueDict["NZBprov"], now())) File "/opt/lazylibrarian/lazylibrarian/notifiers/__init__.py", line 57, in notify_snatch n.notify_snatch(title) File "/opt/lazylibrarian/lazylibrarian/notifiers/pushbullet.py", line 89, in notify_snatch self._notify(message=title, event=notifyStrings[NOTIFY_SNATCH]) File "/opt/lazylibrarian/lazylibrarian/notifiers/pushbullet.py", line 81, in _notify return self._sendPushbullet(message, event, pushbullet_token, pushbullet_deviceid) File "/opt/lazylibrarian/lazylibrarian/notifiers/pushbullet.py", line 58, in _sendPushbullet push = pb.pushNote(pushbullet_deviceid, str(event), str(message)) File "/opt/lazylibrarian/lazylibrarian/notifiers/pushbullet2.py", line 89, in pushNote return self._request("POST", HOST + "/pushes", data) File "/opt/lazylibrarian/lazylibrarian/notifiers/pushbullet2.py", line 42, in _request auth=HTTPBasicAuth(self.apiKey, "")) File "/opt/lazylibrarian/lib/requests/api.py", line 56, in request return session.request(method=method, url=url, **kwargs) File "/opt/lazylibrarian/lib/requests/sessions.py", line 488, in request resp = self.send(prep, **send_kwargs) File "/opt/lazylibrarian/lib/requests/sessions.py", line 609, in send r = adapter.send(request, **kwargs) File "/opt/lazylibrarian/lib/requests/adapters.py", line 423, in send timeout=timeout File "/opt/lazylibrarian/lib/requests/packages/urllib3/connectionpool.py", line 594, in urlopen chunked=chunked) File "/opt/lazylibrarian/lib/requests/packages/urllib3/connectionpool.py", line 350, in _make_request self._validate_conn(conn) File "/opt/lazylibrarian/lib/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn conn.connect() File "/opt/lazylibrarian/lib/requests/packages/urllib3/connection.py", line 330, in connect cert = self.sock.getpeercert() File "/opt/lazylibrarian/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert 'subjectAltName': get_subj_alt_name(x509) File "/opt/lazylibrarian/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 166, in get_subj_alt_name cert = _Certificate(openssl_backend, peer_cert._x509) AttributeError: 'X509' object has no attribute '_x509'`

**Comment by AndyHazz** [comment]
`sudo pip install pyopenssl --upgrade` installed/upgraded a bunch of related packages, but that hasn't helped either

**Comment by philborman** [comment]
Maybe try using your systemwide version or requests rather than the lazylibrarian one?
Try editing 2 lines near the top of pushbullet2.py  taking the references to "lib" out so it reads...
import requests
from requests.auth import HTTPBasicAuth

**Comment by AndyHazz** [comment]
I think that did the trick, notifications are working for me now ...

**Comment by philborman** [comment]
Ok, good to know that.
I'm not sure whether to try adding cryptography to lazylibrarian, or just
put a note of the solution in the wiki. It probably only affects a few
incomplete debian based systems so I'm leaning towards the wiki.

I run osmc on my pi which has quite a bit not installed by default, i used
to run raspbian which was not quite so bad. Some of the linux based NAS
devices out there are also very limited, or have very old versions of
software installed which is why lazylibrarian ships with its own copy of a
lot of libraries. Saves expecting users to find and install the bits
lazylibrarian needs to run.

**Comment by philborman** [comment]
I think the changes we made to get pushbullet to work will stop the auto-update process working. If you are git based you will need to "git checkout" the original files before update.

I have added some code to pushbullet.py to try loading the system-wide versions of the requests library first, and fall back to the lazylibrarian copy if no system-wide one loaded. Hopefully this will fix it.

**Comment by AndyHazz** [comment]
Sounds good, I did wonder about that - I am git based but no git expert ... does this look ok?

```
pi@raspberrypi:/opt/lazylibrarian $ git checkout
M       lazylibrarian/notifiers/pushbullet2.py
Your branch is up-to-date with 'origin/master'.
```

... notifications are still working.

**Comment by philborman** [comment]
git has given you a list of what has changed, so just the one file we expected, it hasn't actually reverted the changes. You need to do...
git checkout lazylibrarian/notifiers/pushbullet2.py

At that point the pushbullet notifier will stop working. Once you upgrade (either within lazylibrarian  or with git pull)  it should start working again. The new version of lazylibrarian will probably be out tomorrow, just running some tests overnight. A lot of changes this time round.

**Comment by AndyHazz** [comment]
ah, makes sense, done.
Thanks for the help :)

**Comment by AndyHazz** [comment]
I've updated to the latest, and notifications are working again :)
