### ISSUE TITLE
Monitor GoodReads RSS Feeds for new books

### ISSUE THREAD

**Issue by Hughlander** [DobyTang/LazyLibrarian#692]
#193 talks about importing from Good Reads, but I'd like a scheduled job that just watches my to-read  RSS feed and adds anything new as wanted.

**Comment by philborman** [comment]
I guess we could create a "wishlist" from the rss feed and import the wishlist, we already have most of that functionality in lazylibrarian.
Question - if the rss feed has a book by an author you don't have, do you add the author to the database and get a list of all their books, or just grab the one book in the rss feed and ignore the rest of the authors books?

**Comment by Hughlander** [comment]
I eventually did the goodreads export and csv import but since there were 5k+ books on the read list it took awhile to import...

I would expect it to add the books and follow the default for the 'New Authors Book Status' section.

I know that my use case is I'll frequently add the first book of a series to my 'to-read' as a mental placeholder to read the series at some point.

**Comment by philborman** [comment]
Using the "new author book status" currently what we do. 
I
Why I wondered about only adding the one book rather than the whole author back-catalogue is it would make importing a wishlist  _much_ faster as your 5k+ books were probably by 4.5k+ authors, each with maybe average 10 books, so 45k+ books to get data for, cover images, which series they belong to etc.  If we only import the one book per author that's 5k vs 45k, roughly 9x faster at the expense of not listing the other books. If you like the first book you can always rescan that one author (or one series) separately?

**Comment by Code-Slave** [comment]
I think from a feed like that you just add the author and that one book. we could then rescan and grab all books if we want more. I do similiar and if i dont like the book then not likely to want the full catalouge

**Comment by philborman** [comment]
ok, that's in the new version.
Is it easy to create the wishlist on goodreads, or do you have to turn the rss feed into a wishlist manually. If necessary we could add an option to monitor the rss feed and auto download the books in it, but if goodreads can give you a ready made wishlist we could just stick with that?

**Comment by Hughlander** [comment]
It's incredibly simple.  You just mark the book as to-read and it's added to the RSS feed for 'to-read' which is created automatically.  I have a plugin that adds a button to amazon pages to add it to the to-read list, I have the goodread app that will add it if you take a picture of the cover, I have a calibre plugin that will flag it, (And remove the flag when the book is read.) etc...  For my workflow at least it's going to be a really cool feature.  I'll give it a try now.  Thanks!

**Comment by Hughlander** [comment]
Hi, I've looked for the option in  git diff b35e6e9675936e7a9cb829b65a14accaec7aa3f1..0496624a27edf335f1d611683812e26f8dfd66a9 and I don't see anything referring to it nor see a way to add it to the UI.  Can you point me in the right direction?

**Comment by philborman** [comment]
At the moment you still need to download a wishlist, but when you import it
we only grab the books in it and don't list the rest of the authors books
(unless the author is already in the library of course)

I'm adding an option to do this directly from the rss feed but it is not
quite finished yet.

**Comment by philborman** [comment]
ok, test version in my git if you want to try it, https://github.com/philborman/LazyLibrarian.git
Should auto-detect a goodreads rss feed and flag everything in it as "wanted" when the next rss search runs, adding minimal author and book entries as required. Debug log will show the process working. Only tested with goodreads for now, could expand it if required.

**Comment by philborman** [comment]
ok, this is in the latest version
