### ISSUE TITLE
Error sending torrent to Deluge

### ISSUE THREAD

**Issue by chaosking121** [DobyTang/LazyLibrarian#696]
Copy-pasting from the relevant issue on the Headphones repo, since I'm getting the same error in LazyLibrarian: 

---------------------------------------------------------------------------------------------------------------------------------

Seems as though a recent deluge update has broken at least one other app for me. In this case the app was posting json as content type "text/plain" instead of "application/json."

It appears this is a similar issue. From a full protocol decode tcpdump of the request from Headphones to Deluge:
```

POST /json HTTP/1.1
Host: xxxxxxxxx:8112
Content-Length: 59
User-Agent: python-requests/2.7.0 CPython/2.7.6 Linux/x.xx.x-xxx-generic
Connection: keep-alive
Accept: */*
Accept-Encoding: gzip, deflate

HTTP/1.1 500 Internal Server Error
Date: Thu, 09 Mar 2017 20:20:25 GMT
Content-Length: 0
Content-Type: text/html
Server: TwistedWeb/13.2.0
```
I don't see a content-type specified, but the Deluge API docs say you must specify "application/json":

"Make requests with valid JSON (including ‘Accept: application/json’ and ‘Content-Type: application/json’ HTTP headers)." (from http://deluge-webapi.readthedocs.io/en/latest/quickstart.html).

**Comment by philborman** [comment]
Lazylibrarian doesn't use deluge-webapi, we talk direct to the daemon, deluged
or we use the built in webui, not the deluge-webapi plugin.

Unfortunately I don't have a working deluge to try this with, but could easily add headers if the core features need it, but I think that's probably not necessary?

**Comment by chaosking121** [comment]
Looks like you're right. Sorry for that. I saw a JSON error message and after dealing with the same issue this past few days in both Headphones and Radarr with a similar error message, I assumed it was the same issue here. Thanks for the quick reply, closing now.
