### ISSUE TITLE
mp3's are erroneously downloading 

### ISSUE THREAD

**Issue by ethanopp** [DobyTang/LazyLibrarian#698]
File format settings are "epub, mobi, pdf" but mp3s are still downloading primarily from Stephen King books.

**Comment by philborman** [comment]
We use the words in the format settings to reject nzb/torrent titles that contain those words, but often the name of the torrent or nzb doesn't tell you the format(s). You can also use the size limits to reject mp3 files, they are usually much larger than an ebook, maybe set a maximum book size of 10mb. This might reject some pdf files too as they can be quite large, but that might not be a bad thing if there's a smaller epub or mobi available. Sadly some torrents don't give you a size either, so we can't tell until after the download completes. Well, we could scan the torrent file list I suppose, might look into that. 

As a last resort, if we unpack an nzb or torrent and don't find a book in a format we want, we mark it as failed and blacklist it.  You would still have an mp3 downloaded, but not entered in the library, but the next time the search tasks run they will try to grab a different copy which hopefully isn't mp3.

**Comment by ethanopp** [comment]
Great tip with the size! Didn't even think of that... I noticed that overnight the .fails piled up but it finally did find the correct file to download.

Manually deleting the .fails and giving the size limit filter a try now...

Thanks again!
