### ISSUE TITLE
Version Check Failure

### ISSUE THREAD

**Issue by rutskiuk** [DobyTang/LazyLibrarian#699]
Hi there,

I'm having problems with version checking on LazyLibrarian. I get a persistent notification at the bottom that says I am running a local updated  version. The version I am running is the master. I tried manually updating by downloading a zip, shutting down the service and copying to the program folder but still afterwards I get the same prompt at the bottom of the screen, using the version checker returns a LazyLibrarian unknown version.
I am running this on Windows 10 through the default interface on my browser (FireFox):
Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: not checked : Latest Version: b35e6e9675936e7a9cb829b65a14accaec7aa3f1

Any ideas what's happened?

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

**Comment by philborman** [comment]
This crops up from time to time when the version checker can't connect to git to check the latest version. I think if you turn debug logging on and try the "version check" button on the config page you should see some status messages. The "unknown version" would seem to indicate this too, though that can also mean a locally modified version, hence the warning message. 

When you first install a zip, we don't know what version you are running as github creates the zip and does not include the version in the zipfile, so usually on a first run we do an automatic upgrade to latest version from git. If this isn't happening either it looks like communication issues. Debug log will probably confirm this.

**Comment by rutskiuk** [comment]
I had a look through the logs and it shows:

15-Mar-2017 18:53:08 - DEBUG   :: WEBSERVER : Set Install Type, Current & Latest Version and Commit status
15-Mar-2017 18:53:08 - DEBUG   :: WEBSERVER : (getInstallType) [source] install detected. Setting Branch to [master]
15-Mar-2017 18:53:08 - DEBUG   :: WEBSERVER : (updateVersionFile) Updating [C:\Users\Alex\Documents\Downloads\Lazy Librarian\version.txt] with value [not checked]
15-Mar-2017 18:53:08 - DEBUG   :: WEBSERVER : (getCurrentVersion) - Install type [source] Local Version is set to [not checked] 
15-Mar-2017 18:53:08 - DEBUG   :: WEBSERVER : (getLatestVersion_FromGit) Retrieving latest version information from github command=[https://api.github.com/repos/dobytang/lazylibrarian/commits/master]
15-Mar-2017 18:53:10 - DEBUG   :: WEBSERVER : (getLatestVersion_FromGit) Branch [master] Latest Version has been set to [b35e6e9675936e7a9cb829b65a14accaec7aa3f1]
15-Mar-2017 18:53:10 - INFO    :: WEBSERVER : [VersionCheck] -  Comparing currently installed version with latest github version
15-Mar-2017 18:53:10 - DEBUG   :: WEBSERVER : (getCommitDifferenceFromGit) -  Check for differences between local & repo by [https://api.github.com/repos/dobytang/LazyLibrarian/compare/not checked...b35e6e9675936e7a9cb829b65a14accaec7aa3f1]
15-Mar-2017 18:53:10 - WARNING :: WEBSERVER : (getCommitDifferenceFromGit) -  Could not get commits behind from github. Can happen if you have a local commit not pushed to repo or no connection to github
15-Mar-2017 18:53:10 - INFO    :: WEBSERVER : [VersionCheck] -  You are running an unknown version of lazylibrarian. Run the updater to identify your version
15-Mar-2017 18:53:10 - DEBUG   :: WEBSERVER : (getCommitDifferenceFromGit) - exiting with commit value of [-1]
15-Mar-2017 18:53:10 - DEBUG   :: WEBSERVER : Update check complete

**Comment by philborman** [comment]
Something got out of sync somewhere. If you stop lazylibrarian, delete the
'version.txt' file and restart lazylibrarian you should force an update and
get the correct version info loaded.

**Comment by rutskiuk** [comment]
Perfect, that has done it. Thank you
