### ISSUE TITLE
Library Scan not working

### ISSUE THREAD

**Issue by jangrewe** [DobyTang/LazyLibrarian#703]
### LazyLibrarian version number (at the bottom of config page)
f8682a43b766d9cb7d88503e812e5e83b857175a ( =latest)

### Operating system used (windows, mac, linux, NAS type)
Debian stretch

### Interface in use (default, bookstrap)
bookstrap / paper

### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
git

### Relevant debug log with api keys and any passwords redacted
```
18-Mar-2017 14:40:47 - INFO    :: LIBRARYSYNC : Scanning ebook directory: /mnt/blockbox/media/ebooks
18-Mar-2017 14:40:47 - ERROR   :: LIBRARYSYNC : Unhandled exception in libraryScan: Traceback (most recent call last):
  File "/opt/lazylibrarian/lazylibrarian/librarysync.py", line 349, in LibraryScan
    pattern = re.compile(matchString, re.VERBOSE)
  File "/usr/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
error: unexpected end of regular expression

```

**Comment by philborman** [comment]
Very strange. Nothing has changed in that section of code for several months. Maybe longer, I only looked back as far as the beginning of January. It's a fairly simple bit of code, but it does include your list of valid book types. What do you have set as ebooks file format in your config (importing tab)

**Comment by jangrewe** [comment]
The file types are empty, and the destination path is `/mnt/blockbox/media/ebooks`

**Comment by philborman** [comment]
Right, it's the empty filetypes that is causing the error. We try to match the downloaded files against a list of "acceptable" types and the pattern matching fails if there's nothing to match to. I guess nobody has tried that before!  I will add some error trapping to warn about it, but I think it would be quite difficult to make the code run without any filetypes at all.

**Comment by jangrewe** [comment]
Right, that makes sense. I've left it empty because the input description says `Default: epub, mobi, pdf`.
The scan works fine when i set some filetypes, so feel free to close this issue unless you'd like to keep it open until you've added the warning.

**Comment by philborman** [comment]
I've added some code to make sure the fields that need a value can't be empty. If you put an empty string it will get replaced by the default value, which is more sensible. New version out tonight hopefully.

**Comment by jangrewe** [comment]
Thanks, that sounds like a good solution.
