### ISSUE TITLE
'logger' is not defined

### ISSUE THREAD

**Issue by jangrewe** [DobyTang/LazyLibrarian#704]
### LazyLibrarian version number (at the bottom of config page)
f8682a43b766d9cb7d88503e812e5e83b857175a 

### Operating system used (windows, mac, linux, NAS type)
Debian stretch

### Interface in use (default, bookstrap)
bookstrap

### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
git

### Relevant debug log with api keys and any passwords redacted

```
18-Mar-2017 16:30:42 - ERROR   :: LIBRARYSYNC : Unhandled exception in libraryScan: Traceback (most recent call last):
  File "/opt/lazylibrarian/lazylibrarian/librarysync.py", line 469, in LibraryScan
    author, new = addAuthorNameToDB(author)  # get the author name as we know it...
  File "/opt/lazylibrarian/lazylibrarian/importer.py", line 38, in addAuthorNameToDB
    author = formatAuthorName(author)
  File "/opt/lazylibrarian/lazylibrarian/formatter.py", line 337, in formatAuthorName
    logger.debug('Stripped authorname [%s] to [%s %s]' % (author, forename, surname))
NameError: global name 'logger' is not defined
```

**Comment by philborman** [comment]
Fixed that one yesterday, I moved that piece of code into a different file, it's now in "common.py" which does have logger defined. The other changes to day look ok so I've just pushed the update. If you upgrade to current version you should get all the fixes in one go.

**Comment by jangrewe** [comment]
Confirmed working, thanks!
