### ISSUE TITLE
Search Results incorrectly returning/matching

### ISSUE THREAD

**Issue by ATor69** [DobyTang/LazyLibrarian#712]
LL Version: d5c2771a97b36db01708c9e5bebaefb5db927c8e
OS: Debian Jessie
Interface: Bootstrap
API: Goodreads
Install: GIT

Logs
Timestamp	Level	Message
2017-03-24 18:23:28	INFO	NZBSearch for Wanted items complete, found 0 books
2017-03-24 18:23:28	INFO	NZB Searches for Luke Scull The Grim Company: (The Grim Company, #1) returned no results.
2017-03-24 18:23:28	INFO	Nearest NZB match (29%): The Vikings by Else Roesdahl using book search for Luke Scull The Grim Company
2017-03-24 18:23:27	INFO	NZB Searching for 1 book

When I search for the above mentioned book (Using Jackett) you can see it finds an unrelated book, which is not a match.  When using allegedly the same query in Jackett manually (see image) I am finding two results both of which would match close to 100%

Seems like what the logs are stating the query is, is not exactly the query being sent.

Image of manual search with supposed query from Logs:

https://ibb.co/mxTtOv

**Comment by ATor69** [comment]
Looks like this is because Jackett (torznab) isn't parsing author and title.  If LL were instead to pass the author/title combo as "query" the results would match what is expected.

**Comment by philborman** [comment]
If you remove "book" search for your torznab instance LazyLibrarian will use q= as you want. I think. If not, debug log would be useful. LazyLibrarian will prefer a "book" search if one is available where it passes author and title as separate parameters. If book search is not enabled it will fall back to a general search. You can configure this per-provider in the config->categories tab

**Comment by ATor69** [comment]
Interesting, that seems to have worked in forcing the query search, and matched the book at 97%.  Maybe a better place for this "fix" would be on the Jackett end to actually allow parsing of book titles and authors as separate parameters.
