### ISSUE TITLE
LL misinterprets parentheses in book title

### ISSUE THREAD

**Issue by wizzy99** [DobyTang/LazyLibrarian#714]
Current Version: d5c2771a97b36db01708c9e5bebaefb5db927c8e

It looks like Goodreads typically has the Series/book in parentheses, but in some cases the parentheses are part of the book title and LL doesn't handle that well.  Example [here](https://www.goodreads.com/book/show/34523605-robert-ludlum-s-tm-the-bourne-initiative).  

What gets saved as the book title is "Robert Ludlum's" with "(TM) The Bourne Initiative" as the second line.  Searches only look for "Robert Ludlum's" rather than the actual book name.  There are several other books by this same author that fall into the same scenario due to the (TM) in the title.

**Comment by philborman** [comment]
Yes I see the problem. Any idea how to get around it?  I could easily add an exclusion list of words in parentheses to ignore, but is there a better way...

**Comment by philborman** [comment]
I have added a bit more code to ignore single words in brackets, which gets round the (tm) problem. I found a couple of similar issues with (Annotated) or other single words in braces. Might be enough? 
It's in the new version, can be tweaked more if needed.
