### ISSUE TITLE
When deleting single or multiple magazine issues ... remove or delete. The entire magazine gets deleted.

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#715]
When deleting single or multiple magazine issues ... remove or delete. The entire magazine gets deleted.

This occurs with any magazine. 

If I go to a magazine and then select some of the issues, and either click the remove or delete the selected issues; the whole magazine gets deleted?

**Comment by philborman** [comment]
That's a hangover from when each magazine issue had to be in a separate folder. We just delete each issues folder. Just testing a fix for the problem now, expect a new version later today

**Comment by MrMxyzptlk** [comment]
Thanks!
