### ISSUE TITLE
Sort By Downloaded Proportion

### ISSUE THREAD

**Issue by rutskiuk** [DobyTang/LazyLibrarian#717]
Hi,

I have noticed that when I sort by downloads it sorts by the number of downloads, not the proportion meaning that sorting by this field arbitrarily separates authors that simply have more downloads for regardless of whether you are missing any. Sorting by this field is handy for showing which authors you a missing books from and if you have a large library it would mean one author missing books might be on a different page from another. Sorting by the proportion of downloads is the standard behaviour for sickbeard, sickrage and headphones. Is this a mistake or something that could be added?

Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 131525f3db5e7ffa9d7056c676543ddf6a1432fa

**Comment by philborman** [comment]
Should be easy enough to add. You want the proportion (eg 10/123) converting to a percentage and sort on the percentage. I think there's probably some standard datatables code to do that.

**Comment by rutskiuk** [comment]
Yes, that's what I was looking for exactly. Thank you :)
