### ISSUE TITLE
Calibre import

### ISSUE THREAD

**Issue by VarunChugh** [DobyTang/LazyLibrarian#720]
I got this error while running Calibre import (full scan):

Unhandled exception in libraryScan: Traceback (most recent call last): File "/app/lazylibrarian/lazylibrarian/librarysync.py", line 469, in LibraryScan author, new = addAuthorNameToDB(author) # get the author name as we know it... File "/app/lazylibrarian/lazylibrarian/importer.py", line 39, in addAuthorNameToDB author = formatAuthorName(author) File "/app/lazylibrarian/lazylibrarian/common.py", line 59, in formatAuthorName if author[1] in '. ': IndexError: string index out of range

A few lines before this error:

2017-04-01 12:44:05	DEBUG	Already cached Lang [eng] ISBN [006]
2017-04-01 12:44:05	DEBUG	Found Language [eng] ISBN [9780061057908]
2017-04-01 12:44:05	DEBUG	file meta [9780061057908] [eng] [-] [Acorna's Quest] []
2017-04-01 12:44:04	DEBUG	book meta [9780061057908] [UND] [-] [Acorna's Quest] [epub]
2017-04-01 12:44:04	DEBUG	[/books] Now scanning subdirectory /-/Acorna's Quest (3598)

**Comment by philborman** [comment]
Looks like the author name is only one character long :-)
No name given in the file metadata, and the book metadata says the author is called "-"
The code that's failing is a bit that reformats initials into a consistent format to make name matching more reliable (J.R.R.Tolkien and J R R Tolkien are the same person). 
Lazylibrarian tries to reject books with no author, so probably should reject this book too. I will push a fix later today.
