### ISSUE TITLE
Cannot use deluge

### ISSUE THREAD

**Issue by Na3blis** [DobyTang/LazyLibrarian#722]
I tried setting up deluge and when I test I get the following in the debug logs:
2017-04-02 20:28:44	DEBUG	Deluge: Connection FAILED Check debug log
2017-04-02 20:28:44	DEBUG	Deluge: auth.login returned Invalid URL 'http:/:0/json': No schema supplied. Perhaps you meant http://http:/:0/json?
2017-04-02 20:28:44	DEBUG	Deluge: Authenticating...
2017-04-02 20:28:44	DEBUG	Deluge: Checking connection

I am using the latest LinuxServer docker image on my mac mini.

**Comment by philborman** [comment]
Looks like you have not filled in the host and port values for deluge, or maybe not saved the values before you hit the test button?

**Comment by Na3blis** [comment]
Ah, you are correct. I think that the test button should trigger a save on those elements. It seems unnatural to have to hit save then test.

**Comment by philborman** [comment]
Yes I agree. It's unfortunately a side-effect of the way the config settings are passed from the web interface to the main python code, they all get passed in one big list when you save changes. That's the way the original author designed it. There should be a way of doing it each time an entry gets changed, but it's beyond my programming ability at the moment. We could do with a developer who knows his way around html.

**Comment by philborman** [comment]
Looks like there is a "half way" solution, I think we can temporarily  save the settings, run the test, then permanently save if the test is successful. Might get it in the next version, looking hopeful.

**Comment by Na3blis** [comment]
Awesome. I may take a look at it when I have more time, but I'm more experienced on backend work, and not html
