### ISSUE TITLE
Sort by Downloaded Proportion

### ISSUE THREAD

**Issue by rutskiuk** [DobyTang/LazyLibrarian#725]
Previously raised issue #717

Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: aae438311c9421721c0eec42af51c27731e12dcc

I am running the latest build after the update but the sort by Downloaded field is only sorting by the first digit of the downloads, not the proportion of downloads as mentioned before. I did a quick screenshot with the current sort order and as you can see the sort order is wrong.

![download proportions](https://cloud.githubusercontent.com/assets/25068977/24682706/00d8c5bc-1993-11e7-81f1-1ef031189aea.PNG)

**Comment by philborman** [comment]
Seems to be working on bookstrap interface, but not on the default interface. Not sure why as the code is the same. I will look into it :-)

**Comment by philborman** [comment]
ok, found and fixed that. Not pushed the fix yet as working on another default interface problem. Maybe a few hours. For now you can always switch to bookstrap...
