### ISSUE TITLE
Downloading some books in NL instead of EN? 

### ISSUE THREAD

**Issue by dmz94** [DobyTang/LazyLibrarian#727]
To help with identifying and fixing issues, please include as much information as possible, including:

Version: 2fa91b6d16a8ecaa7f42e1437f9bc2fadff3e851
OS: linux (unRAID 6.2.3) running via dcker
Interface: Default I think.....
API: Goodreads
Source: unRAID app installer for dockers

I am trying to download Eragon (The Inheritance Cycle #1), by Christopher Paolini
http://www.goodreads.com/book/show/113436.Eragon
http://amzn.eu/2bvNriz

Have tried downloading via author and ISBN. 

I have English specified in my configuration but I keep getting a version in Dutch. 

Logs attached....happy to provide further details and debug information from both LL and nzbGet.

Many thanks!
[LL Log.txt](https://github.com/DobyTang/LazyLibrarian/files/908363/LL.Log.txt)

**Comment by philborman** [comment]
Problem is that the nzb and the book title don't give any indication of language, so lazylibrarian can't tell. There are several matches at 100%, so you can work around the problem by cancelling the download in nzbget. Lazylibrarian will eventually notice that the download has failed and blacklist it. The next time the search tasks run they will try to get a different copy (next highest match in the list). Not ideal, but the best we can do I think.

**Comment by dmz94** [comment]
That makes sense. Thanks for explaining the process and providing a workaround.

**Comment by philborman** [comment]
Actually there is another way, you can manually search for it which will be
quicker.
You still won't definitely know the language, but you could select a few
and discard the wrong ones after download.
To do this...
Find the book using the search filter on the book tab (not the top search
box, the lower one)
Under the book title (and subtitle if there is one) you should see
"GoodReads  LibraryThing  Manual"
Click on Manual
On the next screen you can edit the book details if needed (probably don't
need to in your case),
or use the buttons at the top to search for the book manually by author
and/or title
When the search completes, click the "Snatch" button next to any likely
looking matches. Hopefully one of them will be in English.

**Comment by dmz94** [comment]
That works for me - Thanks!!
