### ISSUE TITLE
Deluge connection

### ISSUE THREAD

**Issue by snpster** [DobyTang/LazyLibrarian#731]
Docker container https://github.com/linuxserver/docker-lazylibrarian
Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 3635160354db79f2969554fce168a3e6d8e35f75 : Latest Version: 3635160354db79f2969554fce168a3e6d8e35f75

2017-04-17 13:38:10	DEBUG	Deluge: Connection successful
2017-04-17 13:38:10	DEBUG	Deluge: Checking connection

Even when purposefully putting in incorrect details lazylibrarian reports the deluge connection successful.
(this applied to ip/port/username/password) it seems even putting in invalid IP addresses it still connects.

**Comment by philborman** [comment]
Looks like this might be docker specific as it's working correctly on a git install. Not sure why though, you go straight from "checking" to "success" so lazylibrarian seems to think you are already logged in to deluge, no attempt to try and connect. I will have a dig around and try a docker myself.

**Comment by snpster** [comment]
I checked the deluge logs and a username wasn't coming through, so i cleared it and re-entered it, its now working, but if you send any information with a blank field it reports a successful connection.

**Comment by philborman** [comment]
Thanks for the update. I will add some code to tidy up after a failed
attempt. It looks like the current code keeps the failed details and the
next attempt sees there are some details left over and assumes they're
valid.

**Comment by philborman** [comment]
Should be fixed in latest version, please close this issue if it's resolved. Thanks
