### ISSUE TITLE
Question: How to prevent ALL books by an author being added on initial scan.

### ISSUE THREAD

**Issue by simonm** [DobyTang/LazyLibrarian#734]
Not an issue - this is a question. I hope it's OK I ask using this method.

When doing an initial "Library Scan" where the books directory is pointing to an existing (and very large) Calibre library, LazyLibrarian is looking up every single book released by every author.

How can I simply add the books and authors I already have to the local DB?

Who knew Asimov had 716 released works?

**Comment by philborman** [comment]
The idea behind lazylibrarian is that it looks for other books by the
authors you have, and optionally tries to download them automatically. If
you don't want to include books you don't have...
Before scanning your calibre library, in config, processing tab, set "New
Authors Book Status" to "Ignored"
This means that as the author is added to the database, book data is
grabbed but not shown in the webpages.
Books you have in your library are changed to "open" and will appear, the
rest won't.

You can also do it retrospectively by marking books as "ignored" after
import, so go to Asimov author page, set "rows per page" to "all", use the
"search" filter to select status "Skipped", use the toggle button to select
all rows, and then set  "Mark selected as" to "Ignored" and hit "go"

**Comment by simonm** [comment]
Thank you so much for the explanation. This is exactly what I needed.
