### ISSUE TITLE
Calibre Auto Add & Magazines

### ISSUE THREAD

**Issue by peddlerguy** [DobyTang/LazyLibrarian#739]
I installed LazyLibrian and have been getting it set up to my liking and have come across an issue - I have the books download into a specific directory, and have LL copy them into another directory (the directory which Calibre "watches") and it's been working great - I love the automation of LL making a copy and Calibre watching the directory and importing as a book becomes available.

Today I decided to grab some magazines - LL put most of them in a _magazine folder, inside the same folder that it puts the books, and a few magazines it created their own folder the way it does the books (not inside the _magazine folder) - but it didn't make a copy of any of them in the "watch" folder, so they didn't get auto added to Calibre.

Does it just not copy the magazines to the auto add folder,, or is there a setting I need to change?

Current Version: 6918a5c89a2cdb97bf1c679aff7fbd025df683c4

Windows 8

Bookstrap

**Comment by philborman** [comment]
There are a couple of interesting issues here...
LazyLibrarian should put all the magazines into the _magazines folder, with each magazine in a sub-folder, and the default is to put each issue in a sub-sub-folder. It's controlled by settings in the config->processing tab. The default is something like  _Magazines/Magazine_Name/Issue_Number/Issue_Magazine.pdf
If they are not all ending up in _Magazines it would be good to find out why, a debug log should help.

LazyLibrarian only puts books into the watch folder, not magazines. I have never tried calibre with magazines, but it could probably be added easily enough. Do you know if calibre needs the magazine names in any special format? With a book it reads the metadata to get author/title, with a magazine ther isn't usually any metadata.

**Comment by peddlerguy** [comment]
I had initially hoped that the magazines could be imported automatically like the books - I can import them manually, and as it turns out I have to be at the computer anyway to edit the meta data because the Titles aren't the way that I want - so not being able to have them auto add isn't a big problem like I first thought - so now I'll just import manually, edit the titles, then grab my iPad and use Calibre Companion to copy them over, and then read them :-)

there was only 1 magazine that didn't get put into the _magazines folder - I turned on the debug log in case it happens again

**Comment by philborman** [comment]
Anything unusual in the magazine name that didn't get put into _magazines?
Maybe an accented character, or a single word title, something a bit out of
the ordinary?

To set the titles the way you want, you can use the settings in
lazylibrarian config->processing tab.
The one you probably  want to change is ...
"Magazine Issue Filename:

**Comment by peddlerguy** [comment]
The magazine file name that didn't get put into the magazines folder was like this:

magazine.name.usa.truepdf-May.2017.pdf - the actual name of the magazine was normal:  Magazine Name

the title setting in the processing tab is:

$IssueDate - $Title

A few of the mags that I had to rename showed a url in the title and author fields in Calibre - I don't remember what the url was, I renamed it to the name of the magazine - yet the actual filename was correct - don't know where it got the url from

**Comment by philborman** [comment]
I would guess calibre reads metadata from the magazine file contents and
picks up the URL that way. Lazylibrarian doesn't bother reading pdf
metadata as it's almost always missing or wrong. Often has the "author" set
to the software used to create the pdf, or the uploaders sig. Lazylibrarian
asks for a magazine issue to be downloaded and watches for it arriving, so
it knows what the title should be and renames the file when the download
completes.

**Comment by peddlerguy** [comment]
yesh, I noticed the url was in the tags column, so I went to it (in a sandboxed browser LOL) and it looks like it might be the uploader's site

**Comment by peddlerguy** [comment]
now if it's possible to add the auto add feature for magazines, that would be great - less for me to do, I'd just have to rename them

but all in all, I love this program am glad I found good instructions for installing it!  I found a post on reddit where someone gave a link to installing headphones, and said just to replace anything related to headphones with LazyLibrarian, and I got it installed easily once I did that

**Comment by philborman** [comment]
You might be able to do what you want by setting the magazine download
directory (currently  _magazines) to the same directory that calibre is
watching. Full path to the calibre watch directory, starting with the drive
letter. If not I will look into auto-add for magazines too. I had a quick
look at calibre earlier and could not see magazines mentioned in the menus,
just books and news sources. Is magazines done with an add-on?

**Comment by peddlerguy** [comment]
thanks, I'll try that!

There might be some add ons for Calibre that lets you do fancy things with magazines, but I don't bother - the mags are in pdf format - some books come in pdf format as well, and with books you'd want to convert the pdfs to kindle or kobo formats, but you'd want to leave the mags as pdfs - I transfer them to my ipad and open them with iBooks,  and the mags look like the real thing

so you can just leave the pdfs as is in Calibre - you can filter by file format, so when I choose to only see the PDFs, all I see are the magazines in the list - I guess as far as Calibre is concerned, they're just books in PDF format

**Comment by peddlerguy** [comment]
Ok, I changed the watch directory - grabbed some magazines and they ended up in the books directory like that other magazine did (not in the magazine directory)

looking at the log, it looks like it tried to create the watch directory inside the books directory - for example, I have the base destination folder:

c:\lazylibooks

and the watch directory:

c:\books\

I changed the magazine download directory to:

c:\books\

but looking at the log, it shows errors saying it couldn't create directory:

c:\lazylibooks\_c:\books\:thefilename blah blah syntax is incorrect (paraphrasing that last bit)

**Comment by philborman** [comment]
You also need to untick the "magazines inside book folder" option on the
config->processing page.
Sorry, forgot about that.

**Comment by peddlerguy** [comment]
it worked!  awesome!

thanks for your help!
