### ISSUE TITLE
Add ability to change default directory/file permissions on imported files

### ISSUE THREAD

**Issue by AevumDecessus** [DobyTang/LazyLibrarian#754]
When importing a book via calibredb, there is no option to change the directory or file permissions after import, so all of my files are imported into a directory of chmod 700 and a file permission of 600, owned by the lazylibrarian user, which doesn't work if a library is shared via unix group permissions, such as in a samba share.

**Comment by philborman** [comment]
LazyLibrarian tries to set files to 644 and directories to 755, the settings for this are in config.ini but not changeable via the web interface, only by editing the config.ini file.  I guess it's calibredb setting the permissions here though, can you check if the downloaded files are the right permissions before calibredb moves them? 

Either lazylibrarian does not have the permission to set new file/directory permissions on the download directory, or calibredb changes the permissions when it moves them.  If necessary (and if we have the permission to do it) we can reset the permissions after calibredb finishes.

**Comment by AevumDecessus** [comment]
I did some more digging.

Directories in the sabnzbd completed downloads directory are chmod 777, and files are chmod 666 by Sabnzbd upon download, owned by the same user as the lazylibrarian user, this user belongs to the "media" group.

When calibredb is run by lazylibrarian on the completed files, directories are created in /media/calibre owned by the same user as before, chmod 700 on directories and 600 on files. All directories above this are chmod 770, with them all being owned by the "media" group, as it's used as a read/write samba share for the human users in the "media" group.

It definitely seems like it's the calibredb import that's setting the permissions more restrictively than I would like, so if there is a way to attempt to have lazylibrarian reset the file/folder permissions after import, that would be greatly appreciated.

**Comment by philborman** [comment]
I've added some code to set permissions after calibredb imports the books, can you check if it's working correctly and report back. Thanks.  If it's not working as expected, set your debug level to 4 and lazylibrarian will print more details in the log. Thanks

**Comment by AevumDecessus** [comment]
I've tested it, and it looks like the default permission strings sent to os.chmod are invalid

`28-Apr-2017 15:20:45 - DEBUG   :: POSTPROCESS : Failed to set perms 0o755 for /media/calibre/<AUTHOR>/<TITLE> (3109) : an integer is required`

**Comment by philborman** [comment]
Ah, that's me being stupid!
Need to convert the octal values to an int first. Should be fixed now, sorry about that.

**Comment by AevumDecessus** [comment]
I can confirm that directories and files are correctly set to the values specified in config.ini for file_perm and dir_perm

**Comment by philborman** [comment]
Great, thanks for your help and patience, still learning :-)

**Comment by AevumDecessus** [comment]
#761 fixes a related issue to the settings for file_perm and dir_perm getting deleted.
