### ISSUE TITLE
Select author then series, pick one and update status on some books but remains in skipped status

### ISSUE THREAD

**Issue by famewolf** [DobyTang/LazyLibrarian#763]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
Most recent
### Operating system used (windows, mac, linux, NAS type)
Freenas
### Which api (Goodreads, GoogleBooks, both)
Goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
Freenas/Self updating

When I update status on the main screen for an author it works fine however if you select "series" under that author then pick a series changing any of the status to wanted or have just gets ignored.  I believe it may also not work when selecting an entire series from previous page but haven't tested that part thoroughly.  This was done while the author was still in a "getting books" status.

**Comment by philborman** [comment]
While author is still in "getting books" any changes to status will be lost. When the book is found on a goodreads scan it will be set to whatever status the author/series had when the scan started. It would be much slower if we checked the status every time.

The other issue, changing status for books in a series, should be fixed now. Was only a problem in default interface I think. Bookstrap seems ok. Will push a fix for that in the next hour or two, just testing a bit more first.

**Comment by philborman** [comment]
Took a bit longer than I thought, but should be fixed now. Found a few other issues in the html that needed fixing as well.
