### ISSUE TITLE
Parsing custom RSS providers crashes

### ISSUE THREAD

**Issue by adilei** [DobyTang/LazyLibrarian#766]
Hi,

When searching for a book on a custom RSS feed, search fails with:

`AttributeError: 'list' object has no attribute 'lower'`

This seems to be related to line 261 in searchrss.py, as (I think) lists do not support the "lower" method.

Line 261: `wordlist = wordlist.lower()`

Thanks!

**Comment by philborman** [comment]
Yes, absolutely right. The lower() needs to be on the line above, before we split it into a list!
Will push a fix in an hour or two, just trying to didy up some other bits.

**Comment by adilei** [comment]
Cheers!
