### ISSUE TITLE
Latest git pull disabled web gui

### ISSUE THREAD

**Issue by MechEng70** [DobyTang/LazyLibrarian#770]
![screenshot from 2017-05-07 14-12-14](https://cloud.githubusercontent.com/assets/11697710/25783735/3de2b822-332f-11e7-8476-bec0441eea5a.png)
To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

When accessing the webgui the following is displayed:
`Error !

AttributeError: 'module' object has no attribute 'CONFIG'

102
                    "sInfoEmpty":"Showing 0 to 0 of 0 authors",
103
                    "sInfoFiltered":"(filtered from _MAX_ total authors)"},
104
                "aLengthMenu": [[5, 10, 15, 25, 50, 100, -1], [5, 10, 15, 25, 50, 100, "All"]],
105
                "iDisplayLength": ${lazylibrarian.CONFIG['DISPLAYLENGTH']},
106
                "sPaginationType": "full_numbers",
107
                "aaSorting": [[1, 'asc']],
108
            });
109
        $('.dataTables_filter input').attr("placeholder", "Search table here");
110
    });
/home/plex/.lazylibrarian/data/interfaces/default/index.html, line 105:
105
                "iDisplayLength": ${lazylibrarian.CONFIG['DISPLAYLENGTH']},
/home/plex/.lazylibrarian/data/interfaces/default/base.html, line 81:
81
    ${next.javascriptIncludes()}
/home/plex/.lazylibrarian/mako/runtime.py, line 890:
890
callable_(context, *args, **kwargs)
/home/plex/.lazylibrarian/mako/runtime.py, line 864:
864
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/home/plex/.lazylibrarian/mako/runtime.py, line 829:
829
**_kwargs_for_callable(callable_, data))
/home/plex/.lazylibrarian/mako/template.py, line 445:
445
return runtime._render(self, self.callable_, args, data)
/home/plex/.lazylibrarian/lazylibrarian/webServe.py, line 62:
62
try:`

**Comment by philborman** [comment]
Very odd, can't reproduce it here. 
Looks like it can't access the config table, but nothing has changed in that code (I think) for quite a while. Do you have a valid looking config.ini file, although defaults should kick in if not

Can you try forcing an update from the command line (LazyLibrarian.py --update)

**Comment by MechEng70** [comment]
i just did the git pull the other day and there seemed to be quite a few files that were updated.

I did try forcing it.  see attached.
[lazylibrarian.txt](https://github.com/DobyTang/LazyLibrarian/files/981861/lazylibrarian.txt)

**Comment by MechEng70** [comment]
where is the config.ini file located?  I have a lazylibrarian.ini.new file.

**Comment by philborman** [comment]
Looks like config.ini on your system is in /home/plex/.lazylibrarian
The entries in your log show a version 9 database which is _very_ old, looks like you havent updated for quite a while.  
In your lazylibrarian Logs directory ( which might be /home/plex/.lazylibrarian/Logs/ ) there should be a file dbupgrade.log which might help.
Also on the last line of the log it looks like you had more than one copy of lazylibrarian running?

**Comment by MechEng70** [comment]
stopped the service.  
copied the lazylibrarian.ini.new to lazylibrarian.ini and config.ini.  (lazylibrarian.ini is in the service executables)
restarted the service.
gui is up and converting the database...
