### ISSUE TITLE
Reddit

### ISSUE THREAD

**Issue by Code-Slave** [DobyTang/LazyLibrarian#771]
@philborman 
I created a reddit sub for LL i hope you dont mind. Since development is going really well I just thought to open a community.

head over to https://www.reddit.com/r/LazyLibrarian/
if you like.

**Comment by philborman** [comment]
Thanks Sam,
I will add it to the lazylibrarian ReadMe and wiki

**Comment by Code-Slave** [comment]
Great. Idea is to maybe take some support load away. I see it being asked about all the time on reddit

**Comment by Code-Slave** [comment]
There may be an influx of users heh.
