### ISSUE TITLE
Author images on/off

### ISSUE THREAD

**Issue by Code-Slave** [DobyTang/LazyLibrarian#772]
Can you add a flag to turn them on and off? or a dropdown for different grid types in general. pic on/off?

**Comment by philborman** [comment]
Adding a setting in config is easiest, one for author images, one for books.

You can already disable magazine images by setting "None" in the image 
converter box, but I might tidy that up to use a tickbox in config too.

**Comment by Code-Slave** [comment]
Yea in config is best i agree.

**Comment by philborman** [comment]
It's done, might push the new version later today, just wondering if I can
do the other optional things the same way, magazine tab, series tab,
magazine covers. All those can be optionally hidden but at moment all are
done differently.

**Comment by philborman** [comment]
ok that's all done now.
Please try it, and close the issue if all ok

**Comment by Code-Slave** [comment]
looks great. thanks
