### ISSUE TITLE
SAB 2.0 error

### ISSUE THREAD

**Issue by ParsonsGlory** [DobyTang/LazyLibrarian#777]
Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 75f62c76b59ddec9ac14c106584f859d39c997f5 : Latest Version: 75f62c76b59ddec9ac14c106584f859d39c997f5

Synology
Bookstrap - slate theme
Which api  -Goodreads,
Synology package)

Relevant debug log with api keys and any passwords redacted

2017-05-11 11:30:32
INFO
Search for magazines complete
2017-05-11 11:30:32
ERROR
Failed to download nzb @ SABNZBD
2017-05-11 11:30:32
DEBUG
Result text from SAB: {u'status': True, u'nzo_ids': [u'SABnzbd_nzo_pCdYpw']}
2017-05-11 11:30:32
DEBUG
Request url for SABnzbd
2017-05-11 11:30:32
INFO
Found 22 results for XXXXXXXXXXXX. 1 new, 21 old, 0 fail date, 0 fail name, 0 rejected: 1 to download

LL actually sends nzb to SAB which correctly downloads it and processes it however LL has thrown an error so marks it as failed and doesn't post process. I'm using SAB 2.0. Something in the txt return from SAB is telling LL the download has failed when in fact its hasn't.

**Comment by philborman** [comment]
I'm wondering if it might be the magazine name itself that's causing the problem.
There could maybe be an issue with accented characters that's not getting trapped?
From your log and a quick look at the code you get a successful result (status=True) and then leap straight to "Failed to download", and the only path through that doesn't print an intervening message seems to be the title check.  There are a couple of special cases if the title starts with "Test" or "Delete", but failing that accented characters is my best guess. Would need to add more debugging if that's not the case.

**Comment by ParsonsGlory** [comment]
Tried a few other titles with the same outcome so probably not special characters. The result txt from SAB2 seems to indicate a fail to LL though in fact it works fine. NZBGet and Synology downloader works fine so something specific to SAB. Noted a comment elsewhere that someone was using SAB2 without an issue so probably a configuration issue within SAB though I'm  on default settings

**Comment by ParsonsGlory** [comment]
Works fine now thanks
