### ISSUE TITLE
Request: Allow rescanning of magazines to get older issues

### ISSUE THREAD

**Issue by Code-Slave** [DobyTang/LazyLibrarian#778]
I would like an option to rescan magazines to grab older issues. Say I change the number of days to search for. Add a way to "backfill" maybe a button when you are inside a specific magazine (so it doesnt backfill all of them)

**Comment by philborman** [comment]
It's fairly easy to do from the "past issues" button. Use the filter to pick out the magazine title you want, sort on issue date, tick the ones you want and change to "wanted"

**Comment by Code-Slave** [comment]
is that repopulated or refreshed after a scan?

**Comment by Code-Slave** [comment]
Ok forced search repopulated manage history. One suggestion is to make the search box there not case sensitive

**Comment by philborman** [comment]
Fixed the case insensitive bit, regex is harder though (for me). 
Search results are cleared on each scan as I found otherwise the table got way too large and slow. That was a while ago and much of the table generation code has been speeded up so might not need to be cleared now. I will have a play. Regex probably won't happen unless I can find an easy example somewhere. The filter code uses a lambda construct that I don't understand.

**Comment by Code-Slave** [comment]
im fairly good with regex etc and decent in python. if you point me to relevant bits i can have a look. Im trying to get familiar with the codebase (studying etc)

**Comment by philborman** [comment]
It's in webServe.py  there are four occurrences of the same expression, first one is line 138
filtered = filter(lambda x : sSearch.lower() in str(x).lower(), rows) 
so filter the rows returning only those that contain the searchterm (now lowercased :-) 
It does as-you-type filtering

**Comment by Code-Slave** [comment]
FYI
http://www.python-course.eu/lambda.php
the lamba is just a stub thats needed for the filter() function

also
https://docs.python.org/2/library/re.html

**Comment by Code-Slave** [comment]
Ill start poking around

**Comment by Code-Slave** [comment]
So changing the case really fixed anything I had with this. i think the filter() works just fine here.Ill close this. I actually would prefer messing with the magazine and book matching. I think regexes or some tweaking there may be more helpful
