### ISSUE TITLE
Request: Ability to sort books by date added

### ISSUE THREAD

**Issue by chriscraig-nb** [DobyTang/LazyLibrarian#779]
It would be great to be able to sort the Books table by date added.  It would make it easy to find books that were recently added.

**Comment by philborman** [comment]
We only keep that information in the history tab. There is a "book added" date in the main book table, but that's when the book details were added, not when the book was downloaded/imported.
Might be a useful addition though.

**Comment by philborman** [comment]
Ok, added code to keep the "added to library" date, just need to figure out where to put it on screen. Might add another column to the "books" table, but the screen is already quite cluttered. Maybe we should use the  "status" column for this, when you sort on status it shows most recent additions first, or groups all the "open" books together and then secondary sorts on the date? Or maybe we lose the "released" column and use that screen space instead? Do we just do this on the "books" table, or also on the "manage" and "author" pages too 
What do you think?

**Comment by chriscraig-nb** [comment]
The table may be a bit cluttered, but I think the Date Added column deserves it's own spot.  Perhaps being able to toggle the columns you want to see would help with this?

**Comment by Code-Slave** [comment]
I think a last added in authors page a good addition too

**Comment by Code-Slave** [comment]
latest push looks good

**Comment by chriscraig-nb** [comment]
Perfect!

**Comment by philborman** [comment]
Just added toggle columns to the latest release, but only for the bookstrap interface. The default one uses an old version of datatables that doesn't support it.

**Comment by Code-Slave** [comment]
should we keep both template systems? just more to maintain

**Comment by philborman** [comment]
Personally I think the toggle buttons are better, they use state saving so
remembers your preferences,  and you can override the configured options
temporarily without having to go back to the config screen.

It would be fairly easy to add another config option to hide the toggle
buttons though, which would then look and behave like the old template.

**Comment by Code-Slave** [comment]
Yea what I was getting at is the "default" template set. your maintaining two seperate html codebases. is that really necessary?

**Comment by Code-Slave** [comment]
I love the toggles btw. very clean

**Comment by philborman** [comment]
Personally I think the default interface could probably go and switch the default to bookstrap, but a lot of users are usind the default simply because it's the default. Maybe the answer is to stop development on the default interface and only put new features into the bookstrap one? This is already happening more by chance than design. For example the toggle buttons are not available on the default interface (needs datatables 1.10.x). Rewriting the default interface to use a more recent version of datatables is quite a bit of work, I think.

**Comment by Code-Slave** [comment]
I think if you say its being phased out, and make bookstrap the default moving forward it "shouldnt" cause to big an issue. Much better interface than the old one. and yea two html codebases um no..
