### ISSUE TITLE
Past issues screen missing issues if post process job kicks off

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#784]
Past issues screen missing issues if post process job kicks off after searching for a mag and finding past issues.

**Comment by philborman** [comment]
Would need to prevent postprocessor running while past issues screen is showing, which is tricky. They are sharing the same table info but the past issues screen is a snapshot of the database when the screen started. Refresh past issues once postprocessor complete will sort it.

**Comment by MrMxyzptlk** [comment]
I temporarily set the post processing 'timer' to a VERY large value.
Maybe a checkbox to enable / disable the various LL jobs?

Then I could just disable the post process job, if I'm filling many back logs.

**Comment by philborman** [comment]
In config, first page, you can restart all the jobs (reset the timer so starts counting down from now)  
Or on the config processing tab you can set  the timer to zero for any job to disable it
Could add a pause button fairly easily, maybe with preselected times to pause for?

**Comment by MrMxyzptlk** [comment]
A pause 'button' would be good.
Maybe also have some text right above the jobs as well, that state a '0'
disables the job?

**Comment by philborman** [comment]
Added a "stop" button rather than pause, there is already a restart button.
Will push it out later today
