### ISSUE TITLE
Enhancement: Magazine search refinement

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#786]
I will use an example of FHM Portugal
The only download that was not rejected and automatic was the following: Downloading Portugal Night 2009 + Orbital Dance Hits Vol 2 Selected by Dj Fernando 2009 from Limetorrent.

Obviously this download has nothing to do with FHM Portugal.

Can we either have the search look for all expressions in a search i.e. both FHM and Portugal, or have the first search add this to the 'search term' for the newly added magazine.

**Comment by Code-Slave** [comment]
one thing i have found is to see how the title is usually posted on the indexer or site. then add the phrase exactly like that. It can be a bit hit or miss at times

**Comment by philborman** [comment]
When you first add a magazine it uses the title you gave it (fhm portugal)  and looks for all the words in the title plus a sensible looking date. The example you gave looks like something over 50% name and a year. Setting your match% higher or size limits will block the false match but won't help find any correct ones. 

You can also refine the search term used in config/filters or add words to reject. In the search term you can use anything accepted by the search provider, eg drunkenslug.com allows you to use caret/dollar for start/end, part word match* eg fish* matches fishing , << between words to set word order eg portugal << fhm fails as the word to left of << must come first

Debug log will show what got rejected and why, and setting log level to 4 will give more detail on match percentages

**Comment by MrMxyzptlk** [comment]
OK, will do. Thank you for your time.
