### ISSUE TITLE
Unhandled exception in search_nzb_book:

### ISSUE THREAD

**Issue by nncrypted** [DobyTang/LazyLibrarian#796]
Branch: master
Current Version: 91cc727b92a86c46aab9d8967a330c209966b0d9 : Latest Version: 91cc727b92a86c46aab9d8967a330c209966b0d9
Debian OMV 2.2.14
Bookstrap
Goodreads
Git

Unhandled exception in search_nzb_book: Traceback (most recent call last): File "/opt/LazyLibrarian/lazylibrarian/searchnzb.py", line 89, in search_nzb_book resultlist, nproviders = providers.IterateOverNewzNabSites(book, 'book') File "/opt/LazyLibrarian/lazylibrarian/providers.py", line 179, in IterateOverNewzNabSites provider = get_capabilities(provider) File "/opt/LazyLibrarian/lazylibrarian/providers.py", line 84, in get_capabilities data = ElementTree.fromstring(source_xml) File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML parser.feed(text) File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed self._raiseerror(v) File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror raise err ParseError: syntax error: line 1, column 0

**Comment by philborman** [comment]
Seems we got a valid html response from the provider but couldn't read the capabilities. I will add code to trap it, but which provider was it, in case we can extract some useful info from the response?
I read that extratorrent has gone now :-(

**Comment by nncrypted** [comment]
Tried with NZBHYDRA and Usenet Crawler.

**Comment by philborman** [comment]
ok, nzbhydra is working here (check your api key?)
and usenet crawler gives me a timeout, maybe they are down?
Debug log might help

**Comment by nncrypted** [comment]
All fixed my URL had a slash after the port number and when it checks it adds a slash. My bad thank you.
