### ISSUE TITLE
Unicode in file names

### ISSUE THREAD

**Issue by adamgoldberg** [DobyTang/LazyLibrarian#806]
What's the right way to deal with non-ASCII-mappable unicode characters in filenames?

```
27-May-2017 17:06:56 - ERROR :: POSTPROCESS : Unhandled exception in processDir: Traceback (most recent call last):
  File "/root/LazyLibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 299, in processDir
    if os.path.isfile(pp_path):
  File "/usr/local/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 56: ordinal not in range(128)

```
The file in question ends with "[BЯ]" (left bracket, B, backwards-R, right bracket).  I wonder if prior to line 299 in postprocess.py there should be code which renames the file simply omitting non-ASCII characters?

**Comment by philborman** [comment]
Unicode is a bit of a problem. There doesn't seem to be a "standard" way of
handling it. There is a lot of code dotted around lazylibrarian  converting
ascii to unicode, stripping out accents etc. The one you have hit is a new
one, I guess it's the reverse R that's the issue, not getting trapped
properly.

Just above the line generating the error is some code that converts the
filename into your system encoding (usually utf-8), but then it depends on
the filesystem you're using as to whether that character is acceptable in a
filename or not. Many file systems allow non ascii characters as long as
they are utf-8 encoded. This particular error is checking whether the
download is a single file or a directory of files, and the name has the
reverse R character in it. If we strip the reverse R out the name then
isn't the same, so won't be found.  Needs thinking about...

**Comment by philborman** [comment]
Just had a quick look at the code, there is a "try_rename" function that
gets called to deal with this sort of issue, if you still have the file can
you try setting debug level in config to 3 , then on the "books" page force
postprocessing, and post the debug log. Might show us why it's failing.
Thanks.

**Comment by adamgoldberg** [comment]
Not entirely sure what this shows, doesn't seem to be any additional information.

```
28-May-2017 10:35:18 - DEBUG :: POSTPROCESS : Found match (100%): /media/torrent_complete/Library of Souls (Miss Peregrines Peculiar Children #3) by Ransom Riggs (epub) for Library of Souls (Miss Peregrine’s Peculiar Children #3) by Ransom Riggs (epub) {OLQ} [BЯ]
28-May-2017 10:35:18 - DEBUG :: POSTPROCESS : Processing book 24120519
28-May-2017 10:35:18 - DEBUG :: POSTPROCESS : One format import, best match = epub
28-May-2017 10:35:18 - DEBUG :: POSTPROCESS : Ignoring unwanted file: BookRangers.nfo
28-May-2017 10:35:18 - DEBUG :: POSTPROCESS : Ignoring unwanted file: Thumbs.db
28-May-2017 10:35:18 - DEBUG :: POSTPROCESS : Copying cover.jpg to directory /media/books/Ransom Riggs/Library of Souls
28-May-2017 10:35:18 - DEBUG :: POSTPROCESS : Failed to set permission 0o644 for /media/books/Ransom Riggs/Library of Souls/Library of Souls - Ransom Riggs.jpg : [Errno 1] Operation not permitted: '/media/books/Ransom Riggs/Library of Souls/Library of Souls - Ransom Riggs.jpg'
28-May-2017 10:35:18 - DEBUG :: POSTPROCESS : Copying Library of Souls (Miss Peregrine\xe2\x80\x99s Peculiar Children #3) by Ransom Riggs.epub.epub to directory /media/books/Ransom Riggs/Library of Souls
28-May-2017 10:35:18 - ERROR :: POSTPROCESS : Unhandled exception in processDir: Traceback (most recent call last):
  File "/root/LazyLibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 499, in processDir
    logger.error('Postprocessing for %s has failed: %s' % (global_name, dest_file))

```

**Comment by philborman** [comment]
Well, it shows the problem isn't the backwards R, it's the apostrophe in
Peregrine's
And it also shows the "try_rename" function isn't getting called.
Next question is why isn't the function being called. I'll get back to
you...

**Comment by philborman** [comment]
ok, just added extra code to check/convert/debug in the relevant part of postprocessor. Can you try again with debug level 3 . Thanks.

**Comment by adamgoldberg** [comment]
It might've worked.  But I had a hard time recreating...

**Comment by adamgoldberg** [comment]
Yea, nope.

And not much in way of logging, either.

```
30-May-2017 09:32:15 - DEBUG :: POSTPROCESS : 99% match Library of Souls (Miss Peregrine's Peculiar Children #3) by Ransom Riggs (epub) {OLQ} [B] : Library of Souls (Miss Peregrine’s Peculiar Children #3) by Ransom Riggs (epub) {OLQ} [BЯ]
30-May-2017 09:32:15 - ERROR :: POSTPROCESS : Unhandled exception in processDir: Traceback (most recent call last):
  File "/root/LazyLibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 299, in processDir
    if os.path.isfile(pp_path):
  File "/usr/local/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 56: ordinal not in range(128)

```

**Comment by philborman** [comment]
What do you have as your SYS_ENCODING setting ?  Should be printed in the logfile just after startup

**Comment by adamgoldberg** [comment]
```
02-Jun-2017 11:06:37 - INFO :: MAIN : Config file loaded
02-Jun-2017 11:06:37 - INFO :: MAIN : SYS_ENCODING is UTF-8
02-Jun-2017 11:06:37 - INFO :: MAIN : Database is version 20, integrity check: ok
```

**Comment by adamgoldberg** [comment]
```
02-Jun-2017 16:39:39 - ERROR :: POSTPROCESS : Unhandled exception in processDir: Traceback (most recent call last):
  File "/root/LazyLibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 292, in processDir
    fname = try_rename(download_dir, fname)
  File "/root/LazyLibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 153, in try_rename
    logger.debug("try_rename %s %s" % (type(pp_path), repr(pp_path)))
NameError: global name 'pp_path' is not defined

```

**Comment by philborman** [comment]
Thanks, at least we know the rename code is getting called now!
I have just fixed the rename bug, but the original fault is probably still there.
