### ISSUE TITLE
Unhandled exception during library scan

### ISSUE THREAD

**Issue by jefffaust** [DobyTang/LazyLibrarian#807]
I think this broke with the change "Moved author name formatting into formatter.py"

To fix: formatter.py needs to import 'logger'

To help with identifying and fixing issues, please include as much information as possible, including:
LazyLibrarian version number: 88f9f169fc06e1f93174655a93942fe8e6503550
Operating system used: Docker + Synology NAS
Interface in use: Library Scan
Which api: n/a
Source of your LazyLibrarian installation: linuxserver.io docker package
Relevant debug log:

ERROR	Unhandled exception in libraryScan: Traceback (most recent call last): File "/app/lazylibrarian/lazylibrarian/librarysync.py", line 474, in LibraryScan author, authorid, new = addAuthorNameToDB(author) # get the author name as we know it... File "/app/lazylibrarian/lazylibrarian/importer.py", line 42, in addAuthorNameToDB author = formatAuthorName(author) **File "/app/lazylibrarian/lazylibrarian/formatter.py", line 347, in formatAuthorName logger.debug('Stripped authorname [%s] to [%s %s]' % (author, forename, surname)) NameError: global name 'logger' is not defined**

**Comment by philborman** [comment]
Thanks for the bug report.  It's a bit more complicated than that,
formatter can't import logger as there are circular dependencies problems.
I think we need to specify the full path to logger.  I will push a fix
shortly...
