### ISSUE TITLE
Another Unhandled exception in libraryScan

### ISSUE THREAD

**Issue by Viper911** [DobyTang/LazyLibrarian#809]
28-May-2017 16:31:18 - ERROR :: LIBRARYSYNC : Unhandled exception in libraryScan: Traceback (most recent call last):
  File "C:\LazyLibrarian\lazylibrarian\librarysync.py", line 633, in LibraryScan
    copyfile(coverimg, cacheimg)
  File "c:\python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: u'C:\\LazyLibrarian\\cache\\book\\18168082.jpg'

Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 90cb03b5513a75e71b9bdec037381ed232550391 : Latest Version: 90cb03b5513a75e71b9bdec037381ed232550391

**Comment by Viper911** [comment]
Seems if I add blank folders for book and author it would run farther..

**Comment by jefffaust** [comment]
I'm seeing the same exception. Adding the 'book' directory seemed to help.

**Comment by philborman** [comment]
Seems to be a long standing bug. The cache images all used to be in one
folder, but a few months ago this was changed to separate subfolders but
the sub-folders are not always created. Will push a fix in a few days.
Creating the "book" and "author" folders manually will fix it for now. The
folders should not get deleted again.

**Comment by philborman** [comment]
Fixed in latest version
