### ISSUE TITLE
Search results only 20

### ISSUE THREAD

**Issue by Viper911** [DobyTang/LazyLibrarian#810]
Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 90cb03b5513a75e71b9bdec037381ed232550391 : Latest Version: 90cb03b5513a75e71b9bdec037381ed232550391

When searching for new authors and books, I only get 20 results ever (no multiple pages or more than 20 even when I make filter show 100)

**Comment by philborman** [comment]
Goodreads only returns 20 results per search. Not sure if this can be worked around, I will have a look.

**Comment by philborman** [comment]
Should be fixed in latest version, please close this ticket if it works as expected. Thanks
