### ISSUE TITLE
Update setting

### ISSUE THREAD

**Issue by maxcore** [DobyTang/LazyLibrarian#812]
hey @philborman 
again i have problem with api excess the 60 token (again). When i stop lazy all run good .
In the setting was in hours but i think is for minutes ... you can check if this in the code ?

<img width="611" alt="capture d ecran 2017-05-29 13 51 30" src="https://cloud.githubusercontent.com/assets/4043787/26558406/6fcca76e-4476-11e7-8716-467202e4ce38.png">
i put 60 and all run good if i check with 
curl -i https://api.github.com/users/whatever

**Comment by philborman** [comment]
It is definitely hours. If you go to config, settings page, there is a "Show Jobs" button that gives more details

**Comment by maxcore** [comment]
ok i will Investigation on my unraid server
