### ISSUE TITLE
File being used by another process

### ISSUE THREAD

**Issue by Viper911** [DobyTang/LazyLibrarian#813]
I let it run over night and I just get hundred of these errors (with different book IDs).  The files are just sitting in the complete/books NZBGet folder so not sure what "other process" is using them??

30-May-2017 08:28:32 - DEBUG :: POSTPROCESS : Book with id: 29895095 found in download directory
Traceback (most recent call last):
  File "c:\python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "c:\python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process

**Comment by philborman** [comment]
Not sure what the "other process" would be either. Unfortunately I don't have a windows system handy to try it on, but others report it working ok on windows.  Can you try turning debug level up to 4 and run the postprocessor again. The section of log you posted doesn't give enough info to know where we might be failing.  Are you up to editing the python code to get more info?

**Comment by philborman** [comment]
Extra debugging in latest version may help track it down?  Needs debug level set to 3

**Comment by Viper911** [comment]
It looks like it happens after a code update.  My guess is the original process isn't shut down after the upgrade so two process end up running.

**Comment by philborman** [comment]
Might be windows specific, on linux the running copy downloads the upgrade, launches a new process, and then kills itself.  I think we use the same upgrade system as sickbeard/headphones and others. I will have a look how they do it now as their code may be newer than ours.
