### ISSUE TITLE
[Question/Request] NZB Indexer Balence

### ISSUE THREAD

**Issue by Viper911** [DobyTang/LazyLibrarian#814]
Not sure how this works now.  When a book is being search for on the indexers, does it look at all configured indexers and then looks for the books in the results, or just it run through them in some priority and stop once the first indexer finds matching results?

Depending on the answer the problem I have is some of the indexers I am hitting my daily API limit.  Would be good to limit searching to each until a match is made if its searching all of them every time, and also include some sort of round robin approch so the first one it looks at is different for each new search.

Lastly, in terms of error handling, you might consider skipping an indexer if the error returned is max daily API limit reached so prevent it from hitting it.  Maybe not 24 hours, but skip that indexer for a few hours at least or something rather than hitting it 1000 during a particular update.

**Comment by Viper911** [comment]
On a similar note, not sure if the NewsNab API lets you do it, but would be great if it let you take all outstanding books wanted and search for all of them in 1 API call, rather than 1 per book.

**Comment by philborman** [comment]
Yes it searches all indexers together, collates the results, and picks the
"best" match. If an indexer is over the api limit then no results are
returned, but the failed attempts don't count towards your limit either, so
there is not much advantage in monitoring the error messages, i think.
If you are over your limit now, it doesn't mean you will still be in 5
minutes time, depends when the provider resets it. Midnight every day, or
is there a more smart system that tracks your last n requests and uses the
n-th time as the limit. Plus lazylibrarian might not be the only thing
using nzb on your machines, so we can't track usage ourselves. Tricky to do
correctly, and probably not worth the effort

**Comment by Viper911** [comment]
In terms of stooping the requests, I wouldn't even put a timer on it, but if I am requesting 500 books in a scheduled run and the first errors out with that then I think its safe to assume the other 499 will.  Then on the next run you can try again (rather than waiting for x time as you noted).

My motivation is I know some of the index providers flip out if they see people misusing the API.  I don't know if sending 1000 requests every few hours knowing your over your limit counts as "misuse", but didn't want to temp fate.  Also, its processing (time and CPU cycles) that you know will error out on a single run that seem to be preventable.

**Comment by philborman** [comment]
I'm away for a few days but will look at this when I get back. Might be
simplest to add a short timeout, maybe an hour? Nzbhydra does something
similar

**Comment by Viper911** [comment]
Thanks, no rush.  On a side note, it would be nice to see a count next to each indexer in terms of which one ultimately was used.  Certainly a nice to have and no real functionality, but would be good to know of my 5 indexers, 99% of the books I get are from 1 or 2 of them. - Maybe I could down select my indexers to the ones that count.  Again, just a thought if someone is board one day.

**Comment by philborman** [comment]
The history page shows which provider, but not totals. Would be easy enough
to add somewhere. Also the notifications show the provider, i think.

**Comment by philborman** [comment]
Latest version has an automatic blocklist, block any provider returning an error for one hour. The blocklist is viewable from a button on the config->providers page.

Also basic download stats are available from a button on the History page. Simple count of how many successful downloads by each provider.

**Comment by philborman** [comment]
To implement a sort-of round robin approach to providers, we could use the block list. When searching for several books, first search scans all enabled providers. Whichever one gives the best match is used, and then that provider is blocked for a few seconds so the next search doesn't ask the successful provider. 
What do you think?  If the blocked provider is the only one that could provide a book, it will get used on next search run.

**Comment by Viper911** [comment]
This sounds like a good start.  You might also create priority groups as well, so it searches all priority 1 indexers (maybe 2-3 of them with the approach you mention below), then priority 2 items.

**Comment by philborman** [comment]
Round robin searches are proving troublesome. Often seem to block the only provider that can supply a book, or block a provider with 100% match so we end up accepting 90% match from somewhere else. Probably not worth the effort, so will leave as-is for now.
