### ISSUE TITLE
libgen.io file not downloaded properly

### ISSUE THREAD

**Issue by stockmax** [DobyTang/LazyLibrarian#815]
### LazyLibrarian version number (at the bottom of config page)
90cb03b5513a75e71b9bdec037381ed232550391
### Operating system used (windows, mac, linux, NAS type)
linuxserver/docker-lazylibrarian docker image on Ubuntu 16.04
### Interface in use (default, bookstrap)
bookstrap
### Which api (Goodreads, GoogleBooks, both)
Goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
linuxserver/docker-lazylibrarian
### Relevant debug log with api keys and any passwords redacted

The download finishes with no erroros, but there is only the content from ads.php inside the pdf file.
I guess libgen changed something with their website. 

Overview with mirrors: http://libgen.io/ads.php?md5=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Acutal pdf file: http://libgen.io/get.php?md5=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&key=YYYYYYYYYYYYYYYY

**Comment by barbequesauce** [comment]
Thank you for this... I'm new to LL and I've been banging my head against the wall with this for a week, assuming it was something I did...

**Comment by philborman** [comment]
Should be working in latest update. Please check it, and if it's ok please close this ticket.

**Comment by stockmax** [comment]
It does not work for me.
I unchecked nzb and torrent, only ckecked libgen. 
When I search for a book I get:
Warning no torrent providers are available
Tor searching for 1 book
searching for book with id: xxxx

**Comment by philborman** [comment]
Seems to be working here. Couple of immediate thoughts...
Did you save config after changing settings?
Can you turn debug log on and try again, might show us more info.

**Comment by stockmax** [comment]
I tried again today with version  210a72b3df6220994cce4c6496b2f8c3a2821965.
it works like a charm. Thank you!

**Comment by barbequesauce** [comment]
Much more better - thank you!
