### ISSUE TITLE
Separate Magazines Directory

### ISSUE THREAD

**Issue by glberen** [DobyTang/LazyLibrarian#817]
Any chance of getting a separate magazine destination directory? Right now, the destination for books and magazines has to be the same as I understand it, with an option to store all magazines in _magazines. 

I'd like to be able to have LL handle something like

/media/books
/media/magazines
/media/audiobooks

Thanks for working on this software.

**Comment by philborman** [comment]
You can already do that, just put /media/magazines into the magazine directory entry in config->processing and untick "Magazines inside book folder"

**Comment by glberen** [comment]
I apologize if I'm being particular dense, but I don't see a magazine directory option? I see foldername and filename pattern for magazines. 
![magazine_directory](https://cloud.githubusercontent.com/assets/9060576/26745411/f905738a-47af-11e7-8796-19a1499d4a8e.JPG)

**Comment by philborman** [comment]
Magazine folder name pattern is the one, you probably want something like
/media/Magazines/$Title

**Comment by glberen** [comment]
Thank you!
