### ISSUE TITLE
Author pages shows no books - but books in database

### ISSUE THREAD

**Issue by adamgoldberg** [DobyTang/LazyLibrarian#819]
Just now version, 6686364ec14a19533763ffeca7da6f0138018966.

There are books ... clicking on "books" shows them, but clicking on an author yields page with no books (as if the author has never written anything).
![clipboard01](https://cloud.githubusercontent.com/assets/3258831/26745739/139e59e6-47ba-11e7-8ef0-5f73418e781b.jpg)

Maybe my database is screwed up?

**Comment by philborman** [comment]
Hmm, I've probably broken something. Can you try the bookstrap interface
and see if that works.

**Comment by adamgoldberg** [comment]
What's a bookstrap interface?

**Comment by adamgoldberg** [comment]
Oh, ok, yea, it looks right in the bookstrap interface.

**Comment by philborman** [comment]
Ok, found and fixed that in default interface. One of the new settings used in audiobook support was causing issues as the default interface didn't know about it. The default interface is obsolete, or at least not having any active development at the moment. All the new features are in the bookstrap interface. It's a lot of work retrofitting the changes to the old interface, and some bits aren't possible as the older versions of libraries don't support all the features the new interface uses. Also the new interface is much better on smaller screens (tablets, phones)

**Comment by adamgoldberg** [comment]
Yea, this fixes it in the old interface.  But given the new interface is "where it's at", I'm switching.  :)
