### ISSUE TITLE
Redirects to 127.0.0.1 when setting webroot

### ISSUE THREAD

**Issue by ChronoStriker1** [DobyTang/LazyLibrarian#830]
To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Version:  210a72b3df6220994cce4c6496b2f8c3a2821965
OS:  Unraid 6.3.5
Interface:  Default
Source:  Linux.io docker

When setting webroot (ex. setting it to ll) and attempting to load the page the site will redirect to 127.0.0.1/ll It will do this regardless if proxy is enabled or not.  Also host name is set currently as 0.0.0.0 but occurs when having it as the actual ip of the server.

**Comment by ChronoStriker1** [comment]
Changing to bootstrap seems to have fixed the issue

**Comment by philborman** [comment]
Ah - think the default interface was missing an "id" parameter. The webroot setting had a "name" but not an "id" and it needs both. Should be fixed in next release.
