### ISSUE TITLE
Finding torrent downloads that drop without a subfolder

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#831]
Noticing this with audiobooks, but I've seen it happen with others, too.  If the torrent contains a single file, and doesn't go into its own subdirectory, lazylibrarian has trouble finding the downloaded file and processing it.

I'm not sure what to suggest for it, though, since the downloaded file may not have the same name as the torrent title (and it appears this happens when they don't).

For the moment, I'm manually creating the directories that LL is looking for and moving the files into them, so LL should process them.

**Comment by philborman** [comment]
It already tries to do that for ebooks. I hadn't come across an audiobook in one file, thought they were always in "chapters". I've just added single-file audiobook as well. Probably won't get a new version out for a day or two as I'm working on reorganising to allow provider priorities (prefer downloads from one nzb provider over another, prefer torrents over nzb, etc)

If we come across a single file (audio)book we try to move it into a subdirectory before processing. Debug log should show it happening if you put loglevel > 2 but only for ebooks on the version you've got.

The download name from torrents usually doesn't match the book title we asked for, but we try to ask the torrent downloader what filename it is going to send us and then look for it arriving. Again debug log should show the torrent rename. Which torrent downloader are you using,  as the name may have been changed once magnet resolved, or download started or completed depending on torrent downloader. Usenet doesn't change the name. We like usenet.

**Comment by DarkSir23** [comment]
Actually, I've only seen that happen a couple of times, and I'm not sure which method it used.  I like usenet too, but it's usually been kinda awful for audio.

**Comment by philborman** [comment]
Just to clarify, the process outlined above only works if lazylibrarian is talking to the torrent downloader, not if you're using blackhole, in case that's relevant.

**Comment by DarkSir23** [comment]
I am using black hole. I have not successfully gotten rtorrent settings to work.

**Comment by philborman** [comment]
Blackhole is always going to be problematic with torrents. Often the torrent filename is nothing like the actual book title, or contains lots of random junk (uploader sig, etc) which makes matching harder. If we are communicating with the downloader we can ask it for the name of the file it is sending us, as the downloader gives us a unique id for each download.

If you could get rtorrent communication working life would be much easier ;-)
there are instructions in the lazylibrarian wiki.

Failing that, how about using a different downloader? rtorrent is particularly difficult to set up and use. 
All the others we support (transmission/deluge/qbittorrent/utorrent) are much easier, and freely available

**Comment by DarkSir23** [comment]
I can try it.  I'm kinda stuck with rtorrent, since it's remotely hosted...  I'll let you know how it goes.

**Comment by DarkSir23** [comment]
I successfully got rtorrent set up, so I'll see how that does.  I think this can be closed, but I'll let you make that call :)
