### ISSUE TITLE
Post Processing issue

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#833]
`07-Jun-2017 13:41:03 - ERROR   :: POSTPROCESS : Database error: no such table: downloads
07-Jun-2017 13:41:03 - ERROR   :: POSTPROCESS : Failed query: [SELECT Count FROM downloads where Provider="manually added"]
07-Jun-2017 13:41:03 - ERROR   :: POSTPROCESS : Database error: no such table: downloads
07-Jun-2017 13:41:03 - ERROR   :: POSTPROCESS : Failed query: [INSERT into downloads (Count, Provider) VALUES  (1, "manually added")]
07-Jun-2017 13:41:03 - ERROR   :: POSTPROCESS : Unhandled exception in importBook: Traceback (most recent call last):
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 823, in import_book
    update_downloads(snatched_from)
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 52, in update_downloads
    myDB.action('INSERT into downloads (Count, Provider) VALUES  (%s, "%s")' % (1, provider))
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/database.py", line 46, in action
    sqlResult = self.connection.execute(query)
OperationalError: no such table: downloads
`

I'm getting this repeatedly while trying to process audiobooks.  Repeatedly because it's not finishing the postprocessing part, and removing the books from the lazylibrarian folder.  

Caveat: This is happening on books that I moved into properly named folders, but that doesn't appear to be related, from the error itself.

Let me know if you'd like me to turn up the debug logging or anything.

**Comment by philborman** [comment]
looks like your database is out of sync with the software.
What do you have for database version (it's in the log just after startup)
Also you should have a dbupgrade.log in your log directory, what are the last 5 or 6 lines?

**Comment by DarkSir23** [comment]
`Fri Jun  2 09:56:11 2017 v0: Updating database to version 21, current version is 20
Fri Jun  2 09:56:11 2017 v20: Adding AudioBook support to book table
Fri Jun  2 09:56:17 2017 v20: Adding AudioBook support complete
Fri Jun  2 09:56:17 2017 v20: complete
Fri Jun  2 09:56:17 2017: Cleaning Database
Fri Jun  2 09:56:22 2017: Database upgraded to version 21
`

07-Jun-2017 21:02:33 - INFO    :: MAIN : Database is version 21, integrity check: ok

**Comment by DarkSir23** [comment]
And I did just open up the database, there is definitely no 'downloads' table :(

**Comment by philborman** [comment]
No line about creating the downloads table in your upgrade log.
I think you're using the philborman brance, and may have grabbed an upgrade that wasn't complete?
Simple fix is to create the downloads table manually, you won't get existing history imported, but it will still add new ones

sqlite3 /wherever/lazylibrarian.db
CREATE TABLE downloads (Count INTEGER, Provider TEXT);
.quit

**Comment by DarkSir23** [comment]
Extremely possible.  S'what I get for wanting to be on the bleeding edge :) Done.
