### ISSUE TITLE
Request: Importing to-read list from goodreads

### ISSUE THREAD

**Issue by rvansoest** [DobyTang/LazyLibrarian#835]
Can you implement a way to automatically import books from a shelf in goodreads? Similair to the imdb /couchpotato implementation.

**Comment by philborman** [comment]
You can do this using the goodreads rss feed. It's at the bottom of each goodreads bookshelf page.
If you put this link into lazylibrarian as an rss provider, lazylibrarian will try to import all the books in the list - note that it's a booklist not an authorlist, so any authors that are not already in your library won't be automatically added, just the book(s) in the rss list and enough author info to store them. If you want to get a list of all the books by those authors you need to either add the authors to your library before importing the bookshelf, or rescan the authors from their individual author pages in lazylibrarian. This is to save importing lots of book details for authors you don't yet know if you want ;-)

I have only tried it with a "to-read" bookshelf, but it should work with any goodreads rss bookshelf feed as long as the rss feed name contains "goodreads" and "list_rss"

**Comment by rvansoest** [comment]
I'll try that. Thank you, also for the application as I was looking for something like this for years.

**Comment by justagame** [comment]
This works perfectly.  Great work.
for the newbies, click on the RSS icon at the bottom of the Goodreads|My Books|to-read bookshelf page, then copy the URL of the RSS page (the one that opens when you click on the RSS icon) and paste that into the RSS providers line...
![image](https://user-images.githubusercontent.com/27988823/26996492-6f54a0f2-4d27-11e7-9c05-aa73624710a5.png)

**Comment by barbequesauce** [comment]
I'm a little stuck on this...  

I assed the rss to LL this morning after philborman posted... checked it an hour later and I have exactly 100 books listed under ebooks. My Goodreads to-read list has 160. I checked to make sure the screen is set to show all, not show 100; no idea what else could be wrong... nothing funky in the logs. 

thoughts?

**Comment by philborman** [comment]
Debug log would help.
I wonder if goodreads limits the size of its rss lists, maybe only allows max 100 entries per list? I've only tried with a list of 40 or so books.
Other option is a bug in the rss feed parser, but that's unlikely to just occur on book 100, could be any book. Again debug log would help.

**Comment by barbequesauce** [comment]
Yep, just pulled the RSS feed - you're right, 100 items...

Now to close the gap manually...

Thanks -you can close this issue.
