### ISSUE TITLE
convert books during addition to calibre library when processed by LL

### ISSUE THREAD

**Issue by justagame** [DobyTang/LazyLibrarian#837]
Sorry for the delay - finally figured out the problems and solutions to #746

Now using Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 5abff5a509d2caf317625b0455c614090bd9acc1 : Latest Version: 5abff5a509d2caf317625b0455c614090bd9acc1
I have LL installed on my main server (ubuntu 16 something), my calibre library on a Synology NAS drive and nzbget runs on a raspberry pi 3 with openVPN.

Solutions:
- changed to the bookstrap interface just by selecting it from the Interface|interface: options makes reading the screen items much, much easier
- using SMB, so I made the following changes (Processing|Folders|eBook Library Folder) to point to the calibre library folder "/mnt/SynMediaFiles/Books/MyBooks".  The IP address and volume1 wasn't needed  as it wasn't networking that way.... 
- In addition, for some quirky reason, only after I renamed the library "MyBooks" from "My-Books"  did it work correctly.
- Also found out that the Downloaders|Download Directory has to include the category name - so after changing that to "/mnt/SynMediaFiles/OAMS/Downloads/nzbget/completed/**Books**"
- and finally, used "whereis calibredb" to find out where the calibre command line program (aka calibredb) was located on my main server.  This provided two options:  /usr/bin/calibredb and /opt/calibre/bin/calibredb  .  Because my calibre library and lazylibrarian books are in the same location on the NAS, I wanted LL to process moving the downloaded books from the download directory to the shared calibre-LL library.  Of course, the first one I used "/opt/calibre/bin/calibredb" gave me this error: "error while loading shared libraries: libcalibre-launcher.so: cannot open shared object file: No such file or directory".  When directly logged into a terminal on the server, running "/opt/calibre/bin/calibredb list" gives the exact same error.  But running "/usr/bin/calibredb list" worked fine, generating a list of my books.  So I plugged "**/usr/bin/calibredb**" as the location for Processing|Folders|Calibredb import program: and it works perfectly!

Now, my next request is, when books are added to calibre, can they be converted automatically into the format I have set in my preferences for additions?
![image](https://user-images.githubusercontent.com/27988823/26997160-3a91842a-4d2c-11e7-8835-ea7d2ab7adc1.png)

**Comment by philborman** [comment]
I dont think calibredb has he option to do this automatically, at least I cant see anything in the options to do it, and I dont think you can query calibre to find out what it's current output format is.

You can use a  "custom notifier"  to get the same effect though using calibres "ebook-convert" program. There is an example_ebook_convert.py program in the lazylibrarian files that uses it to check for epub and mobi versions of each new addition and convert between the two if needed.
