### ISSUE TITLE
(Question) - Rename file

### ISSUE THREAD

**Issue by maxcore** [DobyTang/LazyLibrarian#839]
@philborman 
you know if is possible to rename magazine again if i change my config ? ( I dont what space in the file name for https://forums.lime-technology.com/topic/45306-support-magrack-magazine-viewer/#comment-445396 ) if have no option i will scrap again my library with a new one.

**Comment by philborman** [comment]
Easy.
1 In lazylibrarian magazines, select the one you want to rename and Mark it as "remove". This takes it out of lazylibrarian database but does not delete the files
2. Rename the magazine folder without any spaces
3. Magazine page libraryscan to reload with the new name

You might also need to change issue name format in config->processing->magazine filename pattern as the default includes spaces

**Comment by philborman** [comment]
Actually I've just had a quick look at the link you gave to magrack - there is already something similar for mags and books in the next release of lazylibrarian, you might want to wait ;-)
![screenshot from 2017-06-10 20-47-41](https://user-images.githubusercontent.com/12158777/27005400-5269d4d8-4e1e-11e7-9e67-dd0941b95952.png)

**Comment by maxcore** [comment]
Wow thx phill !!! 😄😄

**Comment by maxcore** [comment]
I will wait !!

**Comment by philborman** [comment]
Just pushed the new version

**Comment by maxcore** [comment]
very nice!!! i love this feature! , you know if we can read the magazine in the web browser ? or only download the magazine ?

**Comment by philborman** [comment]
Depends on your browser addons. You should be able to view it if your
browser has a pdf viewer
