### ISSUE TITLE
Magnet Link Problem With Deluge?

### ISSUE THREAD

**Issue by SCRPD** [DobyTang/LazyLibrarian#841]
It seems Deluge is having errors with Magnet Links. I've had no problems with some torrents and others just don't work.

Current Version: 7e664bf89a53de29486eee8bfcef22deda9b9a6f
Windows 10
Bootstrap
GoodReads
Git Source

Log:
```
2017-06-11 08:46:35	ERROR	Failed to download torrent from DELUGEWEBUI, magnet:?xt=urn:btih:4dc6ba7e8852aa23fdc8a10d3fcc08bb8ee7accb&dn=Astrophysics+for+People+in+a+Hurry+%282017%29+by+Neil+deGrasse+Tyson&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969

2017-06-11 08:46:35	INFO	Deluge returned status None

2017-06-11 08:46:34	INFO	Requesting AudioBook download: 99% KAT: Astrophysics for People in a Hurry by Neil deGrasse Tyson

2017-06-11 08:46:34	INFO	Found TOR result: audio 99%, KAT priority 0
```

Debug:
```
2017-06-11 09:00:02	ERROR	Failed to download torrent from DELUGEWEBUI, magnet:?xt=urn:btih:4dc6ba7e8852aa23fdc8a10d3fcc08bb8ee7accb&dn=Astrophysics+for+People+in+a+Hurry+%282017%29+by+Neil+deGrasse+Tyson&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969

2017-06-11 09:00:02	INFO	Deluge returned status None

2017-06-11 09:00:01	DEBUG	Deluge: Response was None

2017-06-11 09:00:00	DEBUG	Deluge: Adding magnet

2017-06-11 09:00:00	DEBUG	Deluge: Got a magnet link: magnet:?xt=urn:btih:4dc6ba7e8852aa23fdc8a10d3fcc08bb8ee7accb&dn=Astrophysics+for+People+in+a+Hurry+%282017%29+by+Neil+deGrasse+Tyson&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969

2017-06-11 09:00:00	DEBUG	Sending Neil deGrasse Tyson - Astrophysics for People in a Hurry LL.(32191710) to Deluge
```

Is it just a bad grab? or possibly something else.
I checked my Deluge connection in LL & it says "Deluge: Connection successful"

Thanks.

**Comment by philborman** [comment]
Seems the magnet link is good, just adde dit manually to deluge and it works.
I'll have a look at the deluge code...

**Comment by philborman** [comment]
11-Jun-2017 16:10:02 - DEBUG :: SEARCHBOOK : [IterateOverTorrentSites] - kickass.cd
11-Jun-2017 16:10:03 - DEBUG :: SEARCHBOOK : Parsing results from <a href="http://kickass.cd/usearch/Neil%20deGrasse%20Tyson%20Astrophysics%20for%20People%20in%20a%20Hurry/?category=books&field=seeders&sorder=desc">KAT</a>
11-Jun-2017 16:10:03 - DEBUG :: SEARCHBOOK : Found Astrophysics for People in a Hurry (2017) by Neil deGrasse Tyson. Size: 3837788
11-Jun-2017 16:10:03 - DEBUG :: SEARCHBOOK : Found 1 result from KAT for Neil deGrasse Tyson Astrophysics for People in a Hurry
11-Jun-2017 16:10:03 - DEBUG :: SEARCHBOOK : TOR author/book Match: 100/100 for Astrophysics for People in a Hurry by Neil deGrasse Tyson at KAT
11-Jun-2017 16:10:03 - INFO :: SEARCHBOOK : Best TOR match (99%): Astrophysics for People in a Hurry by Neil deGrasse Tyson using audio search, priority 0
11-Jun-2017 16:10:03 - INFO :: SEARCHBOOK : Found TOR result: audio 99%, KAT priority 0
11-Jun-2017 16:10:03 - INFO :: SEARCHBOOK : Requesting AudioBook download: 99% KAT: Astrophysics for People in a Hurry by Neil deGrasse Tyson
11-Jun-2017 16:10:04 - DEBUG :: SEARCHBOOK : Sending Neil deGrasse Tyson - Astrophysics for People in a Hurry LL.(hx5DDQAAQBAJ) to Deluge
11-Jun-2017 16:10:04 - INFO :: SEARCHBOOK : Connecting to 127.0.0.1:58846
11-Jun-2017 16:10:04 - DEBUG :: SEARCHBOOK : Connected to Deluge, logging in
11-Jun-2017 16:10:04 - DEBUG :: SEARCHBOOK : Calling reqid 1 method 'daemon.login' with args:(u'phil', u'dent1964') kwargs:{}
11-Jun-2017 16:10:04 - DEBUG :: SEARCHBOOK : Logged in with value 10
11-Jun-2017 16:10:04 - DEBUG :: SEARCHBOOK : Calling reqid 2 method 'core.add_torrent_magnet' with args:('magnet:?xt=urn:btih:4dc6ba7e8852aa23fdc8a10d3fcc08bb8ee7accb&amp;dn=Astrophysics+for+People+in+a+Hurry+%282017%29+by+Neil+deGrasse+Tyson&amp;tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&amp;tr=udp%3A%2F%2Fzer0day.ch%3A1337&amp;tr=udp%3A%2F%2Fopen.demonii.com%3A1337&amp;tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&amp;tr=udp%3A%2F%2Fexodus.desync.com%3A6969', {'name': u'Neil deGrasse Tyson - Astrophysics for People in a Hurry LL.(hx5DDQAAQBAJ)'}) kwargs:{}
11-Jun-2017 16:10:04 - DEBUG :: SEARCHBOOK : Calling reqid 3 method 'label.set_torrent' with args:('4dc6ba7e8852aa23fdc8a10d3fcc08bb8ee7accb', u'books') kwargs:{}
11-Jun-2017 16:10:04 - DEBUG :: SEARCHBOOK : Calling reqid 4 method 'core.get_torrent_status' with args:('4dc6ba7e8852aa23fdc8a10d3fcc08bb8ee7accb', {}) kwargs:{}
11-Jun-2017 16:10:04 - WARNING :: SEARCHBOOK : DELUGERPC: name contains hash, probably unresolved magnet
11-Jun-2017 16:10:04 - INFO :: SEARCHBOOK : Downloading AudioBook Neil deGrasse Tyson - Astrophysics for People in a Hurry LL.(hx5DDQAAQBAJ) from KAT
11-Jun-2017 16:10:04 - DEBUG :: SEARCHBOOK : Pushbullet: Sending notification AudioBook Neil deGrasse Tyson - Astrophysics for People in a Hurry LL.(hx5DDQAAQBAJ) from KAT at 2017-06-11 16:10:04

**Comment by philborman** [comment]
Well, seems the web interface link is working here too...
11-Jun-2017 16:32:55 - DEBUG :: SEARCHBOOK : Parsing results from <a href="http://kickass.cd/usearch/Neil%20deGrasse%20Tyson%20Astrophysics%20for%20People%20in%20a%20Hurry/?category=books&field=seeders&sorder=desc">KAT</a>
11-Jun-2017 16:32:55 - DEBUG :: SEARCHBOOK : Found Astrophysics for People in a Hurry (2017) by Neil deGrasse Tyson. Size: 3837788
11-Jun-2017 16:32:55 - DEBUG :: SEARCHBOOK : Found 1 result from KAT for Neil deGrasse Tyson Astrophysics for People in a Hurry
11-Jun-2017 16:32:55 - DEBUG :: SEARCHBOOK : TOR author/book Match: 100/100 for Astrophysics for People in a Hurry by Neil deGrasse Tyson at KAT
11-Jun-2017 16:32:55 - INFO :: SEARCHBOOK : Best TOR match (99%): Astrophysics for People in a Hurry by Neil deGrasse Tyson using audio search, priority 0
11-Jun-2017 16:32:55 - INFO :: SEARCHBOOK : Found TOR result: audio 99%, KAT priority 0
11-Jun-2017 16:32:55 - INFO :: SEARCHBOOK : Requesting AudioBook download: 99% KAT: Astrophysics for People in a Hurry by Neil deGrasse Tyson
11-Jun-2017 16:32:55 - DEBUG :: SEARCHBOOK : Sending Neil deGrasse Tyson - Astrophysics for People in a Hurry LL.(hx5DDQAAQBAJ) to Deluge
11-Jun-2017 16:32:55 - DEBUG :: SEARCHBOOK : Deluge: Got a magnet link: magnet:?xt=urn:btih:4dc6ba7e8852aa23fdc8a10d3fcc08bb8ee7accb&amp;dn=Astrophysics+for+People+in+a+Hurry+%282017%29+by+Neil+deGrasse+Tyson&amp;tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&amp;tr=udp%3A%2F%2Fzer0day.ch%3A1337&amp;tr=udp%3A%2F%2Fopen.demonii.com%3A1337&amp;tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&amp;tr=udp%3A%2F%2Fexodus.desync.com%3A6969
11-Jun-2017 16:32:55 - DEBUG :: SEARCHBOOK : Deluge: Adding magnet
{"params": ["magnet:?xt=urn:btih:4dc6ba7e8852aa23fdc8a10d3fcc08bb8ee7accb&amp;dn=Astrophysics+for+People+in+a+Hurry+%282017%29+by+Neil+deGrasse+Tyson&amp;tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&amp;tr=udp%3A%2F%2Fzer0day.ch%3A1337&amp;tr=udp%3A%2F%2Fopen.demonii.com%3A1337&amp;tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&amp;tr=udp%3A%2F%2Fexodus.desync.com%3A6969", {}], "method": "core.add_torrent_magnet", "id": 2}
11-Jun-2017 16:32:55 - DEBUG :: SEARCHBOOK : Deluge: Response was 4dc6ba7e8852aa23fdc8a10d3fcc08bb8ee7accb
11-Jun-2017 16:32:55 - INFO :: SEARCHBOOK : Deluge: Torrent sent to Deluge successfully  (4dc6ba7e8852aa23fdc8a10d3fcc08bb8ee7accb)
11-Jun-2017 16:32:55 - DEBUG :: SEARCHBOOK : Deluge: Setting label
11-Jun-2017 16:32:55 - DEBUG :: SEARCHBOOK : Deluge: books label added to torrent
11-Jun-2017 16:32:55 - DEBUG :: SEARCHBOOK : Deluge label returned: True
11-Jun-2017 16:32:55 - DEBUG :: SEARCHBOOK : Deluge: Get torrent folder name
11-Jun-2017 16:33:00 - DEBUG :: SEARCHBOOK : DELUGEWEBUI setting torrent name to [Astrophysics for People in a Hurry by Neil deGrasse Tyson.epub]
11-Jun-2017 16:33:00 - INFO :: SEARCHBOOK : Downloading AudioBook Neil deGrasse Tyson - Astrophysics for People in a Hurry LL.(hx5DDQAAQBAJ) from KAT
11-Jun-2017 16:33:00 - DEBUG :: SEARCHBOOK : Pushbullet: Sending notification AudioBook Neil deGrasse Tyson - Astrophysics for People in a Hurry LL.(hx5DDQAAQBAJ) from KAT at 2017-06-11 16:33:00

**Comment by SCRPD** [comment]
Weird. 
I was 1 Deluge version behind so I updated & I still got the error.

Shut down LL again and retried & now it works... what?

```
2017-06-11 10:56:38	INFO	Deluge: Torrent sent to Deluge successfully (4dc6ba7e8852aa23fdc8a10d3fcc08bb8ee7accb)
2017-06-11 10:56:35	INFO	Requesting AudioBook download: 99% KAT: Astrophysics for People in a Hurry by Neil deGrasse Tyson
2017-06-11 10:56:35	INFO	Found TOR result: audio 99%, KAT priority 0
2017-06-11 10:56:35	INFO	Best TOR match (99%): Astrophysics for People in a Hurry by Neil deGrasse Tyson using audio search, priority 0
```

**Comment by philborman** [comment]
katcr.co needs a captcha and login now, just retuns 404 not found otherwise. I have applied for registration so I can test it. I guess if we login outside lazylibrarian we might still be able to search, depends how they implement the sign-in. Hopefully logs the ip address. If it's done using cookies we might have a problem...

**Comment by SCRPD** [comment]
I figured that would be a problem. 

Have you tried adding worldwidetorrents.eu? It's from some of the staff at the old KAT. I would really try getting that provider added.

**Comment by barbequesauce** [comment]
Big upvote for WWT...

**Comment by SCRPD** [comment]
Probably best If just stick to my NZBHydra setup & LibGen for now. Seem it's more reliable for finding items.

**Comment by philborman** [comment]
Actually WWT looks very easy to set up, and has a pretty good search system. Easy search string, returns a html table we can simply read, and best of all it has specific categories for audiobook/ebook/magazine where most torrent providers only have "book" category. Shouldn't take long...

**Comment by philborman** [comment]
ok, found the deluge problem.  Deluge is in two parts, a webui and a daemon. You can either do everything through the daemon, or upload/download through the webui. All authentication is still handled by the daemon though.  The lazylibrarian "check deluge" button can successfully authenticate, but then if you stop the webui you can't send torrents or magnets to it and lazylibrarian doesn't know. Well, it does now. Error messages will appear in the log.

**Comment by philborman** [comment]
Also just added WWT

**Comment by SCRPD** [comment]
Nice!

**Comment by adamgoldberg** [comment]
See issue #843, I think something in this broke initialization...
