### ISSUE TITLE
ConfigParser.py: ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by adamgoldberg** [DobyTang/LazyLibrarian#843]
At 5:02 PM EDT 6/11/2017

`root@radarr:/LazyLibrarian/LazyLibrarian # git pull firstguy master
From https://github.com/DobyTang/LazyLibrarian
 * branch            master     -> FETCH_HEAD
Already up-to-date.

root@radarr:/LazyLibrarian/LazyLibrarian # nohup python LazyLibrarian.py -d
Traceback (most recent call last):
  File "LazyLibrarian.py", line 231, in <module>
    main()
  File "LazyLibrarian.py", line 150, in main
    lazylibrarian.initialize()
  File "/root/LazyLibrarian/LazyLibrarian/lazylibrarian/__init__.py", line 419, in initialize
    CONFIG[key.upper()] = check_setting(item_type, section, key.lower(), default, log=False)
  File "/root/LazyLibrarian/LazyLibrarian/lazylibrarian/__init__.py", line 371, in check_setting
    my_val = CFG.getint(cfg_name, item_name)
  File "/usr/local/lib/python2.7/ConfigParser.py", line 359, in getint
    return self._get(section, int, option)
  File "/usr/local/lib/python2.7/ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))
ValueError: invalid literal for int() with base 10: ''
root@radarr:~/LazyLibrarian/LazyLibrarian #
`

**Comment by philborman** [comment]
Looks like a corrupted config.ini file. The corrupt value is in one of 'LOGLIMIT', 'LOGFILES', 'LOGSIZE'. Defaults are 500,10,204800 all of which are integers. I think its worth checking your config.ini and maybe if its very corrupt either restore from backup (lazylibrarian keeps one config.ini.bak) or delete config.ini and reset your changed values in the web interface.

**Comment by adamgoldberg** [comment]
Well, loglimit is good (500).  The others are blank.  Would that cause the error?
```
root@radarr:~/LazyLibrarian/LazyLibrarian # head config.ini
[General]
loglimit = 500
logfiles =
logsize =
loglevel = 3
proxy_host =
cache_age = 30
name_postfix =
reject_magsize = 0
imp_monthlang =
root@radarr:~/LazyLibrarian/LazyLibrarian #

```

**Comment by adamgoldberg** [comment]
Ok, well, so I edited in the defaults (500, 10, 204800) and now get this:

```
11-Jun-2017 18:11:51 - DEBUG :: MAIN : General : https_cert ->
Traceback (most recent call last):
  File "LazyLibrarian.py", line 231, in <module>
    main()
  File "LazyLibrarian.py", line 150, in main
    lazylibrarian.initialize()
  File "/root/LazyLibrarian/LazyLibrarian/lazylibrarian/__init__.py", line 450, in initialize
    config_read()
  File "/root/LazyLibrarian/LazyLibrarian/lazylibrarian/__init__.py", line 624, in config_read
    CONFIG[key.upper()] = check_setting(item_type, section, key.lower(), default)
  File "/root/LazyLibrarian/LazyLibrarian/lazylibrarian/__init__.py", line 371, in check_setting
    my_val = CFG.getint(cfg_name, item_name)
  File "/usr/local/lib/python2.7/ConfigParser.py", line 359, in getint
    return self._get(section, int, option)
  File "/usr/local/lib/python2.7/ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))
ValueError: invalid literal for int() with base 10: ''

```

**Comment by philborman** [comment]
https_cert is ok, that's the last one it successfully read. Problem is another expected integer. Can't tell which comes after https_cert as they are not in any particular order at this point. There was a change to config parser a week or so ago that tightened up on invalid values, it used to just silently use the default if it got an error. The idea was it would now warn if it got a bad value, but it just stops instead.  There is an easy fix to get it to start with your current config.ini, if you don't mind a bit of editing...
In lazylibrarian/__init__.py  line 372, except ConfigParser.Error:
change to except Exception:
Should then startup ok, default values replacing your missing ones. From lazylibrarian config page save the config, quit lazylibrarian, and put except ConfigParser.Error:  back

**Comment by adamgoldberg** [comment]
The next line is api_key, also blank.
