### ISSUE TITLE
Detecting Wrong Book Title

### ISSUE THREAD

**Issue by rsanch1** [DobyTang/LazyLibrarian#844]
I'm having trouble with it detecting some of my books correctly. One of the books is Dark Disciple by Christie Golden. I have it in my Books directory inside the author folder Golden, Christie and then inside that I have another folder named Dark Disciple. Then inside that I have an epub, jpg and an opf files all named as Dark Disciple - Christie Golden. But for some reason it keeps getting detected by LL as Star Wars: The Fate of the Jedi. Running the debug log I see this..

- 2017-06-10 21:15:50 DEBUG   Status set to "Skipped" for "Star Wars"
- 2017-06-10 21:16:03 DEBUG   Found Language [en-US] ISBN [9781473517868]
- 2017-06-10 21:16:03 DEBUG   book meta [9781473517868] [en-US] [Christie Golden] [Star Wars: Dark Disciple] [epub]
- 2017-06-10 21:16:03 DEBUG   [/books/Golden, Christie] Now scanning subdirectory /Dark Disciple
- 2017-06-10 21:16:03 INFO    Scanning eBook directory: /books/Golden, Christie
- 2017-06-10 21:16:04 INFO    Library scan complete
- 2017-06-10 21:16:04 DEBUG   Updating bookcounts for 1 author
- 2017-06-10 21:16:04 INFO    3 files processed
- 2017-06-10 21:16:04 INFO    1/0 new/modified eBook found and added to the database
- 2017-06-10 21:16:04 DEBUG   Fuzz match partial [98] [Star Wars: Dark Disciple] [Star Wars]
- 2017-06-10 21:16:04 DEBUG   Fuzz left change, prefer [Star Wars] over [Dark Disciple] for [Star Wars: Dark Disciple]
- 2017-06-10 21:16:04 DEBUG   Already cached Lang [en-US] ISBN [147]

I'm using a docker on unRaid by Linuxserver.io.
I'm using the Master Branch version 7e664bf89a53de29486eee8bfcef22deda9b9a6f

**Comment by philborman** [comment]
Couple of issues here. Author and Title.
The title is "Star Wars: Dark Disciple"  and the colon causes issues. 
Lots of books are named "Title: subtitle"
so we think the title is "Star Wars" and the subtitle is "Dark Disciple". 
We try to match on the full "Star Wars: Dark Disciple" first, and find no match because googreads has it down as "Dark Disciple (Star Wars)", so then we use the split version. Not easy to get round this without breaking lots of other books.

Author is another issue. For some reason we think the author is "Star Wars" when it should be "Christie Golden". I think if we can fix this the title problem will go away as the "partial name" scan only gets run on books by the right author.  I guess you have an author in your database called "Star Wars" and we're matching against their books?

Just need to figure out why we think the author of this book is "Star Wars" in the first place...

**Comment by philborman** [comment]
Added more debugging messages in the latest version, won't fix the problem but should give more info on what's going wrong with getting the author name.

**Comment by adamgoldberg** [comment]
Just my $0.02:

It seems like "Title: subtitle" and "Subtitle (Title)" should be synonyms... but it gets more complicated.  Consider "Heir to the Empire (Star Wars: The Thrawn Trilogy #1)".   Hierarchically, this should really be (Heir to the Empire, The Thrawn Trilogy, Star Wars).

**Comment by philborman** [comment]
Yes, tricky, there is no real consistency in goodreads. Googlebooks is
better in this respect as they have a definite subtitle field, but no
series info. It's usually series info in (trailing braces)

We currently use the whole lot first "Heir to the Empire The Thrawn Trilogy
Star Wars"
and then try everything up to the first colon or open brace "Heir to the
Empire"
We match the words in any order using a fuzzy expression matching library,
so in the first search "Heir to the Empire Star Wars The Thrawn Trilogy"
and  "Heir to the Empire The Thrawn Trilogy Star Wars"  are exactly the
same.
In the second search we just look for "Heir to the Empire" and lose a point
for each extra word, so 100% Heir to the Empire, less 5 extra words is a
95% match.  BUT we need the author to match as well.

**Comment by rsanch1** [comment]
I updated to the latest commit.  But no new changes to the log.  I also tried editing the database but each time I refreshed or ran a new scan it would change right back.

**Comment by philborman** [comment]
Should be extra messages in the debug log showing author name at each point in the import process. Trying to track down at what point we decide to change it. The author name is correct in the book metadata, but wrong by the time we search.

**Comment by rsanch1** [comment]
Sorry...no new info. Here is the latest log.

- 16-Jun-2017 19:11:18 - INFO    :: WEBSERVER : Log cleared, level set to [2]- Log Directory is [/config/log]
- 16-Jun-2017 19:11:34 - INFO    :: WEBSERVER : Debug log display ON, loglevel is 2
- 16-Jun-2017 19:11:43 - INFO    :: AUTHOR_SCAN : Scanning eBook directory: /books/Golden, Christie
- 16-Jun-2017 19:11:43 - DEBUG   :: AUTHOR_SCAN : [/books/Golden, Christie] Now scanning subdirectory /Dark Disciple
- 16-Jun-2017 19:11:43 - DEBUG   :: AUTHOR_SCAN : book meta [9781473517868] [en-US] [Christie Golden] [Star Wars: Dark Disciple] [epub]
- 16-Jun-2017 19:11:43 - DEBUG   :: AUTHOR_SCAN : Found Language [en-US] ISBN [9781473517868]
- 16-Jun-2017 19:11:43 - DEBUG   :: AUTHOR_SCAN : Already cached Lang [en-US] ISBN [147]
- 16-Jun-2017 19:11:43 - DEBUG   :: AUTHOR_SCAN : Searching database for [Star Wars: Dark Disciple] by [Christie Golden]
- 16-Jun-2017 19:11:43 - DEBUG   :: AUTHOR_SCAN : Found 54 books by [Christie Golden] in database
- 16-Jun-2017 19:11:44 - DEBUG   :: AUTHOR_SCAN : Fuzz left change, prefer [Star Wars] over [Dark Disciple] for [Star Wars: Dark Disciple]
- 16-Jun-2017 19:11:44 - DEBUG   :: AUTHOR_SCAN : Fuzz match partial [98] [Star Wars: Dark Disciple] [Star Wars]
- 16-Jun-2017 19:11:44 - INFO    :: AUTHOR_SCAN : 1/0 new/modified eBook found and added to the database
- 16-Jun-2017 19:11:44 - INFO    :: AUTHOR_SCAN : 3 files processed
- 16-Jun-2017 19:11:44 - DEBUG   :: AUTHOR_SCAN : Updating bookcounts for 1 author
- 16-Jun-2017 19:11:44 - INFO    :: AUTHOR_SCAN : Library scan complete

**Comment by philborman** [comment]
Actually that's very useful. Shows we have got the author name correct, directory says "Golden, Christie" book says "Christie Golden", we search through database for "Christie Golden" and find 54 books.
Seems the partial name match at 98% is the problem, presumably the full name match is less than the threshold so we use the partial match as the "best" match.  I think we need to tweak the way we calculate the percentage on partial matches, and maybe drop the "fuzz left" preference as well. It was put in to reduce the chance of matching a single book against an omnibus edition, but there is already a scoring system that downgrades matches with extra words, which would have almost the same effect.
If you run the new version with debug level set to 3 (in config page) it will print the percentage match for each book it compares to. 54 books, 3 matches each, so lots of messages, but should help with tweaking the scoring system.

**Comment by rsanch1** [comment]
Wow! Awesome, it finally got it right.  Log Level set to 3.

- 17-Jun-2017 15:31:23 - INFO    :: WEBSERVER : Log cleared, level set to [3]- Log Directory is [/config/log]
- 17-Jun-2017 15:31:30 - INFO    :: AUTHOR_SCAN : Scanning eBook directory: /books/Golden, Christie
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : [/books/Golden, Christie] Now scanning subdirectory /Dark Disciple
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : book meta [9781473517868] [en-US] [Christie Golden] [Star Wars: Dark Disciple] [epub]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Found Language [en-US] ISBN [9781473517868]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Already cached Lang [en-US] ISBN [147]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Searching database for [Star Wars: Dark Disciple] by [Christie Golden]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Found 54 books by [Christie Golden] in database
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 72 [star wars: dark disciple][dark disciple]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 100 [star wars: dark disciple][dark disciple]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 44 [star wars][dark disciple]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 35 [star wars: dark disciple][arthas. rise of the lich king]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 29 [star wars: dark disciple][arthas. rise of the lich king]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 44 [star wars][arthas. rise of the lich king]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 35 [star wars: dark disciple][rise of the horde]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 24 [star wars: dark disciple][rise of the horde]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 22 [star wars][rise of the horde]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 7 [star wars: dark disciple][omen]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 29 [star wars: dark disciple][omen]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 0 [star wars][omen]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 15 [star wars: dark disciple][lord of the clans]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 21 [star wars: dark disciple][lord of the clans]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 20 [star wars][lord of the clans]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 21 [star wars: dark disciple][allies]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 44 [star wars: dark disciple][allies]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 33 [star wars][allies]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 25 [star wars: dark disciple][ascension]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 38 [star wars: dark disciple][ascension]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 24 [star wars][ascension]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 24 [star wars: dark disciple][the shattering. prelude to cataclysm]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 33 [star wars: dark disciple][the shattering. prelude to cataclysm]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 35 [star wars][the shattering. prelude to cataclysm]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 35 [star wars: dark disciple][jaina proudmoore. tides of war]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 31 [star wars: dark disciple][jaina proudmoore. tides of war]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 59 [star wars][jaina proudmoore. tides of war]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 42 [star wars: dark disciple][war crimes]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 50 [star wars: dark disciple][war crimes]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 56 [star wars][war crimes]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 30 [star wars: dark disciple][thrall. twilight of the aspects]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 20 [star wars: dark disciple][thrall. twilight of the aspects]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 40 [star wars][thrall. twilight of the aspects]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 28 [star wars: dark disciple][vampire of the mists]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 35 [star wars: dark disciple][vampire of the mists]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 50 [star wars][vampire of the mists]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 6 [star wars: dark disciple][homecoming]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 14 [star wars: dark disciple][homecoming]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 0 [star wars][homecoming]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 35 [star wars: dark disciple][the farther shore]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 35 [star wars: dark disciple][the farther shore]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 44 [star wars][the farther shore]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 19 [star wars: dark disciple][warcraft]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 50 [star wars: dark disciple][warcraft]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 50 [star wars][warcraft]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 25 [star wars: dark disciple][firstborn]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 33 [star wars: dark disciple][firstborn]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 40 [star wars][firstborn]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 32 [star wars: dark disciple][shadow hunters]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 36 [star wars: dark disciple][shadow hunters]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 43 [star wars][shadow hunters]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 35 [star wars: dark disciple][dance of the dead]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 33 [star wars: dark disciple][dance of the dead]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 22 [star wars][dance of the dead]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 19 [star wars: dark disciple][twilight]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 31 [star wars: dark disciple][twilight]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 25 [star wars][twilight]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 37 [star wars: dark disciple][on fire's wings]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 27 [star wars: dark disciple][on fire's wings]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 50 [star wars][on fire's wings]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 35 [star wars: dark disciple][spirit walk]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 45 [star wars: dark disciple][spirit walk]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 56 [star wars][spirit walk]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 20 [star wars: dark disciple][enemy of my enemy]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 11 [star wars: dark disciple][enemy of my enemy]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 11 [star wars][enemy of my enemy]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 24 [star wars: dark disciple][devils' due]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 27 [star wars: dark disciple][devils' due]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 27 [star wars][devils' due]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 31 [star wars: dark disciple][the murdered sun]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 38 [star wars: dark disciple][the murdered sun]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 17 [star wars][the murdered sun]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 22 [star wars: dark disciple][seven of nine]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 23 [star wars: dark disciple][seven of nine]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 22 [star wars][seven of nine]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 34 [star wars: dark disciple][warcraft official movie novelization]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 38 [star wars: dark disciple][warcraft official movie novelization]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 33 [star wars][warcraft official movie novelization]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 18 [star wars: dark disciple][flashpoint]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 15 [star wars: dark disciple][flashpoint]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 25 [star wars][flashpoint]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 50 [star wars: dark disciple][chronicles of war]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 29 [star wars: dark disciple][chronicles of war]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 59 [star wars][chronicles of war]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 19 [star wars: dark disciple][marooned]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 25 [star wars: dark disciple][marooned]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 25 [star wars][marooned]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 21 [star wars: dark disciple][the enemy within]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 25 [star wars: dark disciple][the enemy within]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 22 [star wars][the enemy within]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 41 [star wars: dark disciple][ghost dance]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 36 [star wars: dark disciple][ghost dance]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 35 [star wars][ghost dance]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 36 [star wars: dark disciple][cloak and dagger]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 44 [star wars: dark disciple][cloak and dagger]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 33 [star wars][cloak and dagger]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 31 [star wars: dark disciple][shadow of heaven]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 25 [star wars: dark disciple][shadow of heaven]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 33 [star wars][shadow of heaven]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 28 [star wars: dark disciple][no man's land]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 38 [star wars: dark disciple][no man's land]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 27 [star wars][no man's land]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 36 [star wars: dark disciple][in stone's clasp]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 31 [star wars: dark disciple][in stone's clasp]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 33 [star wars][in stone's clasp]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 15 [star wars: dark disciple][assassin's creed]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 27 [star wars: dark disciple][assassin's creed]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 33 [star wars][assassin's creed]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 22 [star wars: dark disciple][assassin's creed. heresy]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 26 [star wars: dark disciple][assassin's creed. heresy]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 33 [star wars][assassin's creed. heresy]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 26 [star wars: dark disciple][the last roundup]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 31 [star wars: dark disciple][the last roundup]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 33 [star wars][the last roundup]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 18 [star wars: dark disciple][hard crash]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 50 [star wars: dark disciple][hard crash]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 56 [star wars][hard crash]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 21 [star wars: dark disciple][fable]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 40 [star wars: dark disciple][fable]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 20 [star wars][fable]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 34 [star wars: dark disciple][instrument of fate]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 33 [star wars: dark disciple][instrument of fate]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 44 [star wars][instrument of fate]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 37 [star wars: dark disciple][kindred spirits]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 24 [star wars: dark disciple][kindred spirits]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 38 [star wars][kindred spirits]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 22 [star wars: dark disciple][assassin's creed iv black flag. blackbeard. the lost journal]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 24 [star wars: dark disciple][assassin's creed iv black flag. blackbeard. the lost journal]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 33 [star wars][assassin's creed iv black flag. blackbeard. the lost journal]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 24 [star wars: dark disciple][under sea's shadow]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 33 [star wars: dark disciple][under sea's shadow]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 40 [star wars][under sea's shadow]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 31 [star wars: dark disciple][invasion america]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 35 [star wars: dark disciple][invasion america]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 38 [star wars][invasion america]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 14 [star wars: dark disciple][assassin's creed unity. abstergo entertainment. employee handbook]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 25 [star wars: dark disciple][assassin's creed unity. abstergo entertainment. employee handbook]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 44 [star wars][assassin's creed unity. abstergo entertainment. employee handbook]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 23 [star wars: dark disciple][king's man and thief]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 33 [star wars: dark disciple][king's man and thief]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 44 [star wars][king's man and thief]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 32 [star wars: dark disciple][the accidental knight]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 26 [star wars: dark disciple][the accidental knight]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 33 [star wars][the accidental knight]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 36 [star wars: dark disciple][fantastic worlds]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 38 [star wars: dark disciple][fantastic worlds]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 56 [star wars][fantastic worlds]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 19 [star wars: dark disciple][untitled]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 40 [star wars: dark disciple][untitled]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 13 [star wars][untitled]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 22 [star wars: dark disciple][inferno squad]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 24 [star wars: dark disciple][inferno squad]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 29 [star wars][inferno squad]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 56 [star wars: dark disciple][star wars]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 100 [star wars: dark disciple][star wars]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 100 [star wars][star wars]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 36 [star wars: dark disciple][valerian and the city of a thousand planets]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 25 [star wars: dark disciple][valerian and the city of a thousand planets]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 44 [star wars][valerian and the city of a thousand planets]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Ratio 31 [star wars: dark disciple][starcraft]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartialRatio 56 [star wars: dark disciple][starcraft]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : PartName 56 [star wars][starcraft]
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Fuzz match partial [98] [Star Wars: Dark Disciple] [Dark Disciple]
- 17-Jun-2017 15:31:30 - INFO    :: AUTHOR_SCAN : 1/0 new/modified eBook found and added to the database
- 17-Jun-2017 15:31:30 - INFO    :: AUTHOR_SCAN : 3 files processed
- 17-Jun-2017 15:31:30 - DEBUG   :: AUTHOR_SCAN : Updating bookcounts for 1 author
- 17-Jun-2017 15:31:30 - INFO    :: AUTHOR_SCAN : Library scan complete

**Comment by philborman** [comment]
Woo Hoo !!

ok, you can put your debug level back down to 1 ;-)
