### ISSUE TITLE
Fail following last update

### ISSUE THREAD

**Issue by wantle** [DobyTang/LazyLibrarian#851]
C:\LazyLibrarian>lazylibrarian.py
Traceback (most recent call last):
  File "C:\LazyLibrarian\LazyLibrarian.py", line 13, in <module>
    import lazylibrarian
  File "C:\LazyLibrarian\lazylibrarian\__init__.py", line 30, in <module>
    from lazylibrarian import logger, postprocess, searchbook, searchrss, librarysync, versioncheck, database, \
  File "C:\LazyLibrarian\lazylibrarian\postprocess.py", line 35, in <module>
    from lazylibrarian.notifiers import notify_download, custom_notify_download
  File "C:\LazyLibrarian\lazylibrarian\notifiers\__init__.py", line 22, in <module>
    import prowl
  File "C:\LazyLibrarian\lazylibrarian\notifiers\prowl.py", line 51
    response = http_handler.getresponse()
           ^
SyntaxError: invalid syntax

**Comment by peddlerguy** [comment]
can someone tell me how to apply the fix?  LL won't open now - I have the dobytang version, and use python on windows 8.1

**Comment by philborman** [comment]
From a command line,  python LazyLibrarian.py - - update
or if you re using git you can just git pull

**Comment by wantle** [comment]
This never works for me. So, try a solution that did work for me.

From philborman:

_from a terminal, change directory into your lazylibrarian folder (the one
containing LazyLibrarian.py)
and git pull from there.

Otherwise if your user data (database, config.ini, caches) are _not_ in the
same folder as LazyLibrarian.py you could just reinstall. Or move them out,
reinstall, put them back. **There are only three things you need to keep,
lazylibrarian.db  config.ini  and the cache directory**, although the cache
is just for speed, it would eventually rebuild itself anyway._
