### ISSUE TITLE
libraryScanAuthor?AuthorID= Missing parameters: library

### ISSUE THREAD

**Issue by daktak** [DobyTang/LazyLibrarian#852]
404 when running scan author on any athor

To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
8c53a90f8f6d13053a89d9d6a072ee120188a69e
### Operating system used (windows, mac, linux, NAS type)
linux
### Interface in use (default, bookstrap)
default
### Which api (Goodreads, GoogleBooks, both)
goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
git
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

**Comment by philborman** [comment]
Default interface only handles ebooks, and doesn't know about some of the extra features added in audiobook support. I thought I'd caught all the links but missed this one.  If you switch to bookstrap interface it will all work. I will push a fix for the default interface later today.
