### ISSUE TITLE
Best way to import a book

### ISSUE THREAD

**Issue by daktak** [DobyTang/LazyLibrarian#854]
I used to place the book in the download dir with "Author - Title LL.(number)" and then "force post processing"
This appears to now only work with "snatched" books? is this correct?

What is the best way to import a book?

**Comment by philborman** [comment]
We try to only postprocess books we asked for, so we know what we are expecting. If we find a "Author - Title LL.(number)" that we didn't ask for, did we want the ebook or the audiobook. Without a "snatched" entry in the database we don't know. 

Best way to import a book that lazylibrarian didn't snatch is to put it into the "alternate import" directory 
and import it using the button on the "manage" page. The idea is that if you do it manually from there, you know what you're doing.

**Comment by daktak** [comment]
Ok, perfect.
