### ISSUE TITLE
Feature request: separate categories for downloaders 

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#856]
Feature request: separate categories for downloaders.

I.E. Would be nice if LL sent SABnzbd or Deluge a different category or label depending on what we were downloading...books, mags, or audio books.
Let us decide the category / label names if you make this an option.

Thank you.

**Comment by philborman** [comment]
Another user asked for that a while ago, but I don't see any advantage?
At the moment all the downloaders put their files into one directory, and the postprocessor takes it from there. If you had multiple directories it would make the postprocessor more complicated, plus not all downloaders have ctegories/labels so they would still need to put everything in one directory.  The feature can be added, just wonder why it might be worth it?

**Comment by MrMxyzptlk** [comment]
I actually have categories set in SABnzbd and Labels+ in Deluge that put completed downloads in entirely different directories. 

I download so many different items, it would be complete chaos for me if I didn't segregate the downloads according to their type. Many times I have to manually (me) process files, and when all of the books / mags / audio books are in the same directory it just makes it 10 times more difficult.

**Comment by philborman** [comment]
Yes I do too for manual downloads, but for lazylibrarian I put all the downloads in one folder with a "lazylibrarian" label.

**Comment by MrMxyzptlk** [comment]
I guess if we can figure out why audio book searches are still downloading extensions that I have excluded it would make it much easier. Right now with the single download directory I have to go into every download to see whether it downloaded audio or an ebook.

**Comment by MrMxyzptlk** [comment]
I am closing this as audio books appear to be working 'again' for me.
