### ISSUE TITLE
New errors in log file after manual book post process on 1 book

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#857]
2017-06-14 10:27:03	ERROR	Failed query: [SELECT AuthorID FROM authors WHERE BookID="34430839"]
2017-06-14 10:27:03	ERROR	Database error: no such column: BookID

The book was renamed and moved properly....

**Comment by philborman** [comment]
Bug. There used to be a duplicated column, should look in the books table for authorid, not the authors table. Just pushed a fix for this.

**Comment by MrMxyzptlk** [comment]
Thanks, I'll close this after I see that it worked.

**Comment by MrMxyzptlk** [comment]
All of a sudden: 8:48 - ERROR :: MAIN : (RunGit)Git returned bad info. Are you sure this is a git installation?
14-Jun-2017 11:08:48 - ERROR :: MAIN : (RunGit)Git returned bad info. Are you sure this is a git installation?
14-Jun-2017 11:08:48 - ERROR :: MAIN : (getCurrentVersion) Couldn't find latest git installed version.
14-Jun-2017 11:08:49 - WARNING :: MAIN : (getLatestVersion_FromGit) Could not get the latest commit from github

But I was able to update from the command line?

**Comment by MrMxyzptlk** [comment]
Notify Icon LazyLibrarian Update
Unable to get latest version from GITHub

**Comment by MrMxyzptlk** [comment]
It is now working again for no apparent reason?
I'm closing this one...
