### ISSUE TITLE
Post-processing not seeing files

### ISSUE THREAD

**Issue by barbequesauce** [DobyTang/LazyLibrarian#863]
For some reason, post-processing isn't seeing files in transmission's completed folder. Accordingly, its re-snatching and sitting in an endless loop. Any ideas why?

Log shows this:

`2017-06-14 21:06:25	DEBUG	Snatched torrent Neal Stephenson - The Mongoliad Book One LL.(12853147) is not in download directory`

But in real life...

`-rwxrwxrwx   1 debian-transmission debian-transmission   527308 Jun 12 13:48 Stephenson_Neal-Mongoliad__Book_One_The.epub`

Not sure when it started - it only became apparent now that I'm getting Prowl notifications :)
Using blackhole and torrents, I'm on master (174a).

**Comment by philborman** [comment]
Debug log would help, loglevel 3 for best info.
Immediate thought is the name not matching sufficiently closely.
Normally we ask the provider (transmission) to give us the filename associated with the download id, and rename it to include (LL_bookid) for easier identification. Looks like this didn't happen. It also looks like the non-renamed filename isn't a sufficiently close match for the fuzzy name matching to pick it up. 
Code probably can be tweaked to get around it, but would need debug log to see where to tweak.
Thanks.

**Comment by barbequesauce** [comment]
Changed it from blackhole to Transmission RPC... now LL is learning filenames from T-BT, bypassing the need for fuzzy matching and making the problem go away.

Thanks.
