### ISSUE TITLE
Feature Request: Filter by 'Status'

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#866]
Feature Request: Filter by 'Status', so that I can change status on some books from 'Snatched' back to 'Wanted'. At the moment if there are hundreds of books I have to individually click to select them.

If we could filter by 'Status' or be able to select a range, this would resolve the issue.

Thank you....

**Comment by philborman** [comment]
You can put "Snatched" into the results filter, it will filter on all
columns, I think.

**Comment by MrMxyzptlk** [comment]
I tried that...no go.

Let me know if I'm wrong....

**Comment by philborman** [comment]
I don't have any currently snatched to try, but works with open and wanted, see screenshot...
![screenshot from 2017-06-15 20-58-07](https://user-images.githubusercontent.com/12158777/27197120-6214b91e-520d-11e7-9c4d-490273baf69a.png)

**Comment by philborman** [comment]
Is this working for you now, if so I will close the issue
