### ISSUE TITLE
How to avoid multiple downloads request to SABnzb ?

### ISSUE THREAD

**Issue by opennas** [DobyTang/LazyLibrarian#867]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
Current Version: c58662e54fab3cacd8ae7e5865af9c71fd2fc521

### Operating system used (windows, mac, linux, NAS type)
Synology NAS

Currently LazyLibrarian is trying to download multiple same edition of same file.
Example same edition of same Magazine (ie. Time)
How to avoid this multiple request to SABznb from LazyLibrarian?

**Comment by opennas** [comment]
Currently LazyLibrarian is trying to download multiple same edition of same file.
Example same edition of same Magazine (ie. Time)
How to avoid this multiple request to SABznb from LazyLibrarian?

**Comment by philborman** [comment]
Shouldn't happen, if LL marks a magazine issue as wanted, it shouldn't search again unless it can't be found. What do you have in your History page, should show one entry per issue?

**Comment by opennas** [comment]
This scenario happens for searching magazines. LL snatching same magazine same month many times. Result from this is snatched many times same download to SABnzb queue.
I don't know how to change setup in LL.

**Comment by DarkSir23** [comment]
This happened to me for a while, and I found out that one of the files being downloaded had a strange unicode character in the title, and it was causing the post processor to crash.  Once I fixed that one file, post processing finished, and the issues stopped trying to download.

**Comment by philborman** [comment]
debug log would be really useful, should show exactly what's going on.

**Comment by realcanadrian** [comment]
I just discovered I'm having the same issue. In some cases, LazyLibrarian seems to have added the exact same book to my Calibre library about 1000 times. Are debug logs safe to attach here, or should they be anonymized somehow?

**Comment by philborman** [comment]
Should be ok if you redact api keys, otherwise you can email me direct phil.borman@gmail.com

**Comment by philborman** [comment]
If you want to wait a day or so and then upgrade, the new version of lazylibrarian has a feature on the log page that saves a debug log, redacts any passwords and api keys, and zips it up for easy uploading. Just testing it a bit more before release.

**Comment by realcanadrian** [comment]
Thanks, I upgraded to the latest release, and I'll try sending the zipped
redacted log when LL downloads some more books.

**Comment by realcanadrian** [comment]
@philborman When I click the "save debug log" in my browser, apparently nothing happens - which is to say the page reloads, but no zip downloads, and no link is presented to download a zip. I logged into my remote server via ssh and saw a zip has been created in the "log" folder, but when I unzip it and look at it, it seems to just have info about the installation and no logs. So I zipped up my "log" and "Logs" folders and I'll email them to you manually.

**Comment by philborman** [comment]
Lazylibrarian doesn't automatically upload the zip file, just creates it for you to attach manually, or browse before uploading. 
The log is created backwards from the point where you click "save log" until the first line saying "debug log on" so you don't have to upload loads of old log details. Sounds like you turned debug logging on just before saving it? or maybe turned it off and on and then saved?
Thanks for the zip upload, I will  work through it and report back. Shows the problem quite well, just need to figure out what's going on.

**Comment by philborman** [comment]
ok, think I've found the problem, just not sure what to do about it. Several lines like this...
ERROR   :: POSTPROCESS : Unable to rename /home/canadrian/Downloads/complete/ebooks/Stephen King - UR LL.(6251012).2, [Errno 39] Directory not empty

Since when did linux stop you renaming a directory that's not empty?
Had a report a while back about this being an issue on a mac, but on linux???

Problem is that we try to rename the directory by adding  .fail  to the end so we don't keep reprocessing it. If that doesn't work we will process it again on every run, which seems to be what's happening. Also we don't flag the book as processed, so the downloaders think it failed and grab another copy.

Need to think about it.

**Comment by DarkSir23** [comment]
I get the same error on FreeBSD, though it's [Errno 66], but appears to be in the same point in the procedure.

**Comment by philborman** [comment]
@DarkSir23 do you still have one of the folders that can't be renamed, could you try some python from a terminal as I don't have the problem here to be able to work out how to get around it

**Comment by DarkSir23** [comment]
At the moment I don't. But I'll keep an eye out

**Comment by philborman** [comment]
Actually I think I may have found it. There are a couple of issues related to calibredb and already existing books which might cause os.rename to fail. I've reworked the calibredb code, and switched to shutil.rmtree followed by shutil.move. Will be interesting to see if that fixes it. Even if not, it might give more info on where it's failing.

**Comment by realcanadrian** [comment]
@philborman I currently use the LazyLibrarian docker container
from thraxis/lazylibrarian-calibre (though upgrading LazyLibrarian inside
the container seems to work), as this container includes calibredb. I
haven't upgraded my Calibre install from 2.x since they moved to 3.x, as I
was worried this would break LazyLibrarian's use of the calibredb included
in that container. Is that an issue I should be concerned with? Would your
calibredb-related code changes work better or worse if I upgrade to the
latest version of calibre?

**Comment by philborman** [comment]
No idea, I'm on 2.75.1 and haven't updated for a while. It used to offer auto-update but hasn't lately.  I will upgrade my calibre version tomorrow and have a play.

**Comment by philborman** [comment]
Well, I upgraded my calibre to v3.4 with no problems, calibredb still works ok. Not sure about the docker version as I don't use it, but the calibredb from v2.75.1 still talks to the existing calibre database, as does the new calibredb from v3.4   (I upgraded one machine at a time and tried mixing new and old) so there don't seem to be any compatibility changes in the limited set of commands we use. I had a quick look, and it seems the current thraxis/lazylibrarian-calibre is using calibre3.4 anyway.

The recent changes in lazylibrarian related to calibredb were to do with what happened when calibredb returned an error (eg "book already exists"), not actually changes in how we talk to calibredb, and the syntax of calibredb has not altered.

Just for reference, to get lazylibrarian to use calibredb , I guess you put the full path into lazylibrarian config, ie /opt/calibre/calibredb  or can you just put  calibredb
I will need to write it up in the wiki for reference. Thanks
