### ISSUE TITLE
Alternate import does not change status

### ISSUE THREAD

**Issue by daktak** [DobyTang/LazyLibrarian#868]
Alternate import successfully identified author and bok, moved to directory, but did not change the status from Wanted.

To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
c58662e54fab3cacd8ae7e5865af9c71fd2fc521
### Operating system used (windows, mac, linux, NAS type)
linux
### Interface in use (default, bookstrap)
default
### Which api (Goodreads, GoogleBooks, both)
gr
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
git
### Relevant debug log with api keys and any passwords redacted
Successfully processed:

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

**Comment by philborman** [comment]
Found the bug, just done a major reorganisation of postprocessor cleaning up after successful import, it was a bit messy with all the additions. I think depending on whether calibre was being used we could miss setting status and also miss updating the authors bookcounts. Should be fixed now, will test a bit more and push a fix later today.
