### ISSUE TITLE
Manual Search and Snatch doesn't add to History

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#869]
With the newest phiborman build, if I go to Manual on a book, and search by Title, find a match, and Snatch it, it doesn't go into Snatched and never looks for it to process.  The snatch works fine, downloads where it should.  But LL doesn't do anything with it.

**Comment by philborman** [comment]
Used to download into a directory with LL.(123456)  in the directory name, which the postprocessor looks for. Is the directory name not in the right format?  No reason why it can't be added to history as well, so just added that.

**Comment by DarkSir23** [comment]
In this case it didn't download to a directory, it was a single file with no folder.

**Comment by philborman** [comment]
Ah ok. I think adding to history should help then, as that gets checked first.

**Comment by DarkSir23** [comment]
It's adding to history, but it's marking Audiobook downloads as eBook. :)

**Comment by philborman** [comment]
That's because you can only manually snatch ebooks :-) 
I need to add another button or drop down selector to add audiobook options.
The searches for audiobook are different (search different categories) so it's not easy to combine both together.

**Comment by DarkSir23** [comment]
That would be a good reason why :)
