### ISSUE TITLE
Feature request: Library Genesis searching

### ISSUE THREAD

**Issue by redopanda** [DobyTang/LazyLibrarian#877]
Would it be possible to have an option to search "foreign fiction" (ie. English fiction) section of Library Genesis - http://libgen.io/foreignfiction/index.php ?
 
This often contains ebooks that are not found when searching default LibGen (Sci-Tech) search http://libgen.io/search.php

**Comment by philborman** [comment]
Easy enough to add, as long as you don't want to keep switching from one to another. If that's needed it would take a bit more work...

New version has a box in config where you can put the search. Should not start with  '/' and should end with .php, eg foreignfiction/index.php

**Comment by philborman** [comment]
Actually it is a little more complicated than I thought, the table contents is different for the index.php results. I will have a look at it tomorrow. Just needs tweaking to cope with both table layouts

**Comment by redopanda** [comment]
Thanks for taking a look.
I only want to be able to set to the index.php (won't want to switch back and forth)

**Comment by philborman** [comment]
ok, should work now, let me know if it's ok or needs tweaking.
You can put either search.php or foreignfiction/index.php  as an extra libgen option in config->providers
I haven't tried any other options. As long as any other options follow the same 2 page layouts they may work.
As libgen can produce many pages of results, there is an extra option in config->processing to limit the number of pages of search results, zero to disable and accept all results.
I tried "agatha christie" and got nearly 7000 results, so put a limit in.
Limit also applies to goodreads and tpb. Never hit a problem with tpb, but an unlimited search on goodreads for "star wars"  gives thousands of results too.

**Comment by redopanda** [comment]
Thanks, its now searching foreignfiction/index.php
Search is finding a book, but not snatching

2017-06-22 21:28:03	DEBUG	Error fetching data from libgen: Not Found
2017-06-22 21:28:03	DEBUG	http://fiction.libgen.pw/book/detail/hash/ab15288d4685eb529fc020c360d9e7f7

**Comment by philborman** [comment]
I think that may be a broken link at libgen.  I have a small test library that I use, only 6 books, but some with accented author names or odd characters in book titles etc. and all 6 were found ok.
This is the link to "Agatha Christie And Then There Were None"
http://fiction.libgen.pw/book/detail/hash/d5ceed082ebd9799951745afeb5f6e6a
which looks exactly the same layout, and works as expected. I might be able to filter the broken links out, will have a look.

**Comment by philborman** [comment]
Seems theres more than one link on some foreign book pages, one in the same format as the search.php page, and one in a different format. Should be able to handle both now, hopefully.

**Comment by redopanda** [comment]
Working perfectly now
Thanks

**Comment by philborman** [comment]
Was useful, found a couple of books I've had on my wanted list for a while. Thanks for your help.
