### ISSUE TITLE
(BUG) Can't uncheck Torrent provider

### ISSUE THREAD

**Issue by maxcore** [DobyTang/LazyLibrarian#880]
i get this when i save

<img width="983" alt="capture d ecran 2017-06-20 18 07 32" src="https://user-images.githubusercontent.com/4043787/27358221-9c80bcf4-55e3-11e7-9718-4f1b78782b7b.png">

the provider https://www.limetorrents too many fake i want uncheck this and i can't

EDIT:
i can't save any config .....

**Comment by philborman** [comment]
Problem seems to be an invalid character in a magazine name not getting converted properly. Just added some code that might help. If not, there should be a warning message in the log that would help. 
"Unable to convert title [some magazine name]"
