### ISSUE TITLE
Private Torrent Tracker Support

### ISSUE THREAD

**Issue by xthursdayx** [DobyTang/LazyLibrarian#885]
Hi, I was wondering if you were considering including support for private trackers like Bibliotik? Thanks!

**Comment by philborman** [comment]
Probably not, it's a massive amount of work, and Jackett / Cardigann already do this. No point in duplicating all that effort.  I think the two projects are merging, cardigann is unsupported as of a couple of months ago, but the current build still works. I use it in preference to Jackett as it's much more lightweight. Both are torznab providers, so lazylibrarian can talk to them.
https://github.com/Jackett/Jackett
https://github.com/cardigann/cardigann

**Comment by xthursdayx** [comment]
Yeah Jackett and Cardigann were my first thoughts as well, but unfortunately neither support Bibliotik... I guess I might see if Jackett can add Bibliotik as a supported site.
