### ISSUE TITLE
magazine metadata

### ISSUE THREAD

**Issue by Code-Slave** [DobyTang/LazyLibrarian#886]
So thoughts on magazines and calibre. Im synching mags to a seperate calibre database. The issue is metadata. Its horrid in general. Im wondering if we can generate opf files for them? or maybe add meta data?

**Comment by philborman** [comment]
Metadata in pdf files is pretty nonexistent and if it's there it's often wrong. Uploaders often include their details, or the software used rather than the magazine details we need. We know the magazine issue and title but nothing else.  We can easily create opf files, just don't know what has to be in them. Do you have an example magazine one from calibre I can copy?

**Comment by Code-Slave** [comment]
Im researching the metadata in pdfs now. It looks like without opf file its very basic like title publisher etc. Let me research a bit more. May be to include a pdf lib and write the info we know into the relevant pdf fields. A lot of the mags i get have urls or just crap data there. Im also looking for online metadata like goodreads etc for mags. I dont think it exists so far heh

**Comment by philborman** [comment]
Found several libraries for reading pdf metadata, but not writing. Not sure whether we should be writing metadata anyway, we don't for books. We read the data either from the book or opf file, add in the data from goodreads etc, and use that in our library. If there isn't an opf file we create one, but we leave the original source alone. 

We had code to read pdf metadata in an earlier version of lazylibrarian, but I never found a single pdf book with useful metadata so took it out. The library used then isn't in github now, but there is a neat little library at github.com/aanari/metapdf

I had a look through the pdf metadata in my mags, and almost all are useless. Just a handful had a title field which was magazine name and issue. Opf is probably the best option, but would be useful to follow calibre format, assuming that's what it does.

**Comment by Code-Slave** [comment]
Just started vacation so Im at the beach and will play with the opf when I get back :). Im not sure if calibre will import that for pdfs or not. Just have to test it. If it does then I agree thats a much better way of handling it to get some useful info there

**Comment by philborman** [comment]
Well, next release has magazine opf files created, only has title and issue number/date but that's all the info we have. Cover image should get imported by calibre too.  Magazine title appears as "author name" and the issues are "books" by that author. If you find a good 3rd party source of magazine metadata, let me know!
