### ISSUE TITLE
Notify Snatch Failed - Possible issue with email notification

### ISSUE THREAD

**Issue by adamgoldberg** [DobyTang/LazyLibrarian#890]
Current version, post-snatch I get this in the log:

30-Jun-2017 10:21:37 - WARNING :: WEBSERVER : Notify snatch failed: string indices must be integers

I wonder, my email setup does not include login information (nor encryption, it's just plain, ordinary, SMTP from c.1995).  Perhaps there's some error checking on username or password?

**Comment by philborman** [comment]
Nothing new in the notify snatch  code, only the email notify download code changed. Was snatch email notifier working for you before the update?  Anything else in the log?

**Comment by philborman** [comment]
Ok, think I've found it, me being stupid. Trying to print debug messages before the values are known.
Should be fixed now.

**Comment by adamgoldberg** [comment]
Did you pull changes?  git shows my local version up-to-date (no changes since before I complained).

**Comment by philborman** [comment]
Sorry my internet was down for a while, should be fixed now
