### ISSUE TITLE
Request: specify epub or mobi preference

### ISSUE THREAD

**Issue by AndyHazz** [DobyTang/LazyLibrarian#893]
When multiple matches are found, it doesn't look like there's a way to weight the result you'd want to download by filetype (e.g. .mobi or .epub)?

I'd always prefer .mobi as it saves having to convert .epub and maybe not getting the best formatted version for my use, but more often than not epubs are downloaded when I know .mobi files are available ...

If possible, one way this might be achieved would be to treat the existing 'Importing > File formats > eBooks' field as ordered by preference ('mobi, epub, pdf' would download .mobi files first).

Or alternatively, add a new 'Preferred' field to the filters settings next to Book Reject List, where you could put any words you'd like to increase weight (e.g. 'mobi, illustrated').

**Comment by philborman** [comment]
The  'Importing > File formats > eBooks'  is weighted for preference when processing downloads, but not on searching as most downloads don't include the filetypes in the name and we don't know the contents until the download completes. It's possible to query torrents for their contents, but not nzb, I think. We do a little weighting for preferred filetypes, add a point for each wanted format, but a 100% match without extra words will be a closer match than a 95% match with one or two matching formats. Weighting on title is tricky. Needs more thought.

**Comment by philborman** [comment]
Just a thought, have you tried specifying mobi as the only wanted format so epub gets rejected? If there is a mobi available lazylibrarian should find it, though it might take a few attempts. If there isn't a mobi found after a few tries you can do a manual search from the book page.

**Comment by AndyHazz** [comment]
That makes sense - I've not been able to try it out yet though as my provider has stopped working (logged a separate ticket #906)

**Comment by AndyHazz** [comment]
This seems to work ok 👍
