### ISSUE TITLE
You must install pyOpenSSL

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#894]
Here's what I'm getting trying to run in https mode:

 ` File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/LazyLibrarian.py", line 231, in <module>
    main()
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/LazyLibrarian.py", line 203, in main
    'https_key': lazylibrarian.CONFIG['HTTPS_KEY'],
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/webStart.py", line 111, in initialize
    cherrypy.server.start()
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/_cpserver.py", line 167, in start
    self.httpserver, self.bind_addr = self.httpserver_from_self()
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/_cpserver.py", line 158, in httpserver_from_self
    httpserver = _cpwsgi_server.CPWSGIServer(self)
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/_cpwsgi_server.py", line 64, in __init__
    self.server_adapter.ssl_certificate_chain)
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/wsgiserver/ssl_pyopenssl.py", line 169, in __init__
    raise ImportError("You must install pyOpenSSL to use HTTPS.")
ImportError: You must install pyOpenSSL to use HTTPS.
`

I have verified that pyopenssl is installed, but I'm guessing that it's actually something else.  

Thanks,

**Comment by DarkSir23** [comment]
And now that I've updated all my py27 stuff, when I switch back to non https, I get this on startup:  
`Error getting bookstrap themes : [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:581)`

**Comment by DarkSir23** [comment]
I should probably separate these, but I think they're related.  The SSL error in bookstrap showed up after I updated python2.7 -- Does LL use its own python environment?

**Comment by philborman** [comment]
Not in the git and zip versions, though some 3rd party ones do, eg docker.
Lazylibrarian uses its own requests library, which talks to the system versions of pyopenssl and related cryptography/certificates etc. I think it's done this way because some nas devices don't include fully compatible requests libraries. This is the bit of code throwing the import error...

try:
    from OpenSSL import SSL
    from OpenSSL import crypto
except ImportError:
    SSL = None

so you need both base OpenSSL and the crypto module, which could be a separate file?
I have cryptography and pycrypto listed in my python installation, you might be missing these?
If you use pip, you can "pip list" to see if they are installed.

**Comment by DarkSir23** [comment]
Ok, I got the openssl thing fixed.  The FreeNAS version (that I started from) had it's own python environment, so I got openssl installed to that, and everything is fine.

So, all that's left is the bookstrap themes error, which doesn't appear to be related after all. :)  Should I create a new ticket?

**Comment by DarkSir23** [comment]
`06-Jul-2017 09:14:32 - DEBUG   :: MAIN : SearchScan : searchrss_interval -> 20
06-Jul-2017 09:14:32 - INFO    :: MAIN : Config file loaded
06-Jul-2017 09:14:32 - INFO    :: MAIN : SYS_ENCODING is UTF-8
06-Jul-2017 09:14:33 - INFO    :: MAIN : Database is version 21, integrity check: ok
06-Jul-2017 09:14:33 - DEBUG   :: MAIN : Error getting bookstrap themes : [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:581)
06-Jul-2017 09:14:33 - DEBUG   :: MAIN : Set Install Type, Current & Latest Version and Commit status
06-Jul-2017 09:14:33 - DEBUG   :: MAIN : (RunGit)Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian
06-Jul-2017 09:14:33 - DEBUG   :: MAIN : (RunGit)Git output: [master]
06-Jul-2017 09:14:33 - DEBUG   :: MAIN : (getCurrentGitBranch) Current local branch of repo is [master] 
06-Jul-2017 09:14:33 - DEBUG   :: MAIN : (getInstallType) [git] install detected. Setting Branch to [master]
06-Jul-2017 09:14:33 - DEBUG   :: MAIN : (RunGit)Trying to execute: "git rev-parse HEAD" with shell in /usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian
`

Unfortunately, that's the only line in DEBUG that seems relevant :(

**Comment by DarkSir23** [comment]
http://bootswatch.com/api/3.json appears to redirect to https:// -- So it's something in the fetchURL, but that's not very helpful of me :)

**Comment by DarkSir23** [comment]
I tracked down fetchURL to cache.py, and did some extra logging, but nothing additionally useful came up.  I did check to make sure the server COULD reach bootswatch.com, and was able to download 3.json with wget, so it's not that :/

**Comment by philborman** [comment]
ok, did a quick google search and got...
"If you're getting this error while using urllib2, you'll need to upgrade to python 2.7.9 or later too."
We _are_ using urllib2, my python is 2.7.13  maybe you're on an earlier version?

**Comment by DarkSir23** [comment]
Let me give that a shot

**Comment by DarkSir23** [comment]
Looks like I'm using 2.7.9 -- Little leery about trying to upgrade it.  My base system is running 2.7.13, but I'm really not sure how to best upgrade a localized installation.

**Comment by philborman** [comment]
The message says "2.7.9 or later" so I would have thought 2.7.9 should be ok
Similar problems on stackoverflow were fixed by installing cryptography,  or both pyasn1  and ndg-httpsclient which might not be part of the default install. I have all three installed, though I think it was automatic...

pip install cryptography
pip install pyasn1 ndg-httpsclient

**Comment by DarkSir23** [comment]
I just abandoned the localized install altogether.  Same issue with 2.7.13 -- I'll try these.... They're already installed.  However some are outdated.  Trying to update them. 

...aaaand that did it.    

Thanks for the tips.  Lifesavers :) (If theming can be considered lifesaving)
