### ISSUE TITLE
Manual search and torznab

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#897]
It appears that manual search with torznab sources cut off the URL on the snatch link after the API key.  I can test further if you like.

**Comment by philborman** [comment]
Debug log would be useful, seems to be working here with magnet links, haven't tried torrents though.

**Comment by DarkSir23** [comment]
`05-Jul-2017 16:35:23 - DEBUG   :: WEBSERVER : [IterateOverTorzNabSites] - https://torznab.url
05-Jul-2017 16:35:23 - DEBUG   :: WEBSERVER : [NewzNabPlus] searchType [book] with Host [https://torznab.url] mode [torznab] using api [torznab-api] for item [{'searchterm': 'Timothy Jay We Did What?! Offensive and Inappropriate Behavior in American History', 'bookSub': u'', 'authorName': u'Timothy Jay', 'bookName': u'We Did What?! Offensive and Inappropriate Behavior in American History', 'bookid': u'33252491'}]
05-Jul-2017 16:35:23 - DEBUG   :: WEBSERVER : [NewzNabPlus] - torznab Search parameters set to {'q': u'Timothy Jay We Did What Offensive and Inappropriate Behavior in American History', 'apikey': u'torznab-api', 't': u'search', 'cat': u'8000,8010'}
05-Jul-2017 16:35:23 - DEBUG   :: WEBSERVER : [NewzNabPlus] URL = https://torznab.url/api?q=Timothy+Jay+We+Did+What+Offensive+and+Inappropriate+Behavior+in+American+History&apikey=torznab-api&t=search&cat=8000%2C8010
05-Jul-2017 16:35:24 - DEBUG   :: WEBSERVER : Parsing results from <a href="https://torznab.url/api?q=Timothy+Jay+We+Did+What+Offensive+and+Inappropriate+Behavior+in+American+History&apikey=torznab-api&t=search&cat=8000%2C8010">https://torznab.url</a>
05-Jul-2017 16:35:24 - DEBUG   :: WEBSERVER : [NewzNabPlus] - result fields from NZB are {'nzbmode': 'torznab', 'nzbdate': 'Tue, 04 Jul 2017 14:06:21 +0200', 'bookid': u'33252491', 'nzbtitle': 'We Did What?!: Offensive and Inappropriate Behavior in American History by Timothy Jay', 'nzbsize': '4928307', 'nzburl': 'http://torznab.url/torznab-api?path=aHR0cHM6Ly93d3cubXlhbm9uYW1vdXNlLm5ldC90b3IvZG93bmxvYWQucGhwP3RpZD0zNzk3Njk1&file=We+Did+What%3F!:+Offensive+and+Inappropriate+Behavior+in+American+History+by+Timothy+Jay.torrent', 'nzbprov': u'https://torznab.url', 'priority': 10}
05-Jul-2017 16:35:24 - DEBUG   :: WEBSERVER : Found 1 nzb at https://torznab.url for: Timothy Jay We Did What?! Offensive and Inappropriate Behavior in American History
05-Jul-2017 16:35:24 - DEBUG   :: WEBSERVER : Found 1 book results for Timothy Jay We Did What?! Offensive and Inappropriate Behavior in American History
05-Jul-2017 16:35:59 - DEBUG   :: WEBSERVER : snatch bookid 33252491 mode=torznab from https://torznab.url url=[http://torznab.url/torznab-api]
05-Jul-2017 16:36:00 - WARNING :: WEBSERVER : Error fetching torrent from url: http://torznab.url/torznab-api, Not Found`

**Comment by DarkSir23** [comment]
The actual url should have been:  `http://torznab.url/torznab-api?path=aHR0cHM6Ly93d3cubXlhbm9uYW1vdXNlLm5ldC90b3IvZG93bmxvYWQucGhwP3RpZD0zNzk3Njk1&file=We+Did+What%3F!%3A+Offenzsive+and+Inapzpropriate+Behavior+in+American+History+by+Timzothy+Jzay.torrent`

**Comment by philborman** [comment]
Thanks for that. Found the problem, but don't understand it, there is code in there to split the url on the first '?' but I'm not sure why. I've taken it out for torznab, so we'll have to see if it breaks anything.

**Comment by DarkSir23** [comment]
Manual grabbing is working (kinda), so I'll close this.  But, there's another Torznab issue open now, so if this DID break something, I'll reference it there.

#900
