### ISSUE TITLE
 calibredb failed, Access is denied

### ISSUE THREAD

**Issue by Baldrdk** [DobyTang/LazyLibrarian#898]
To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Hello
When I add a path to calibredb, I get "calibredb failed, Acess is denied" message in the log, and all import fails.
Do I need to enable anything in Calibre or set some permissions??
Im running 64bit calibre installed in C:\Program Files\Calibre2\

**Comment by philborman** [comment]
Probably permissions. Calibredb is run by the lazylibrarian process, and needs access to the calibre database and also the folder containing the book library. Calibre might have set them with restricted access. Try making the database and folder read/write for everyone.
