### ISSUE TITLE
LazyLibrarian no longer searching

### ISSUE THREAD

**Issue by llamadog123** [DobyTang/LazyLibrarian#901]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
e57cf1308279e137a438c057bc2694fd5f5e4a67 
### Operating system used (windows, mac, linux, NAS type)
Ubuntu Ubuntu 16.04.2 LTS
### Interface in use (default, bookstrap)
Bookstrap
### Which api (Goodreads, GoogleBooks, both)
Both
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
Git
### Relevant debug log with api keys and any passwords redacted
`
2017-07-06 17:58:26 | ERROR | Unhandled exception in GR.find_results: Traceback (most recent call last):
  File "/home/media/LazyLibrarian/lazylibrarian/gr.py", line 84, in find_results
    authorNameResult = author.find('./best_book/author/name').text
AttributeError: 'NoneType' object has no attribute 'text'
2017-07-06 17:58:26 | DEBUG | CacheHandler:
 Returning CACHED response for 
http://www.goodreads.com/search.xml?q=lost+in+a+book&key=ckvsiSDsuqh7omh74ZZ6Q&page=70
2017-07-06 17:58:26 | DEBUG | CacheHandler:
 Returning CACHED response for 
http://www.goodreads.com/search.xml?q=lost+in+a+book&key=ckvsiSDsuqh7omh74ZZ6Q&page=69
2017-07-06 17:58:26 | DEBUG | CacheHandler:
 Returning CACHED response for 
http://www.goodreads.com/search.xml?q=lost+in+a+book&key=ckvsiSDsuqh7omh74ZZ6Q&page=68
2017-07-06 17:58:26 | DEBUG | CacheHandler:
 Returning CACHED response for 
http://www.goodreads.com/search.xml?q=lost+in+a+book&key=ckvsiSDsuqh7omh74ZZ6Q&page=67
2017-07-06 17:58:26 | DEBUG | CacheHandler:
 Returning CACHED response for 
http://www.goodreads.com/search.xml?q=lost+in+a+book&key=ckvsiSDsuqh7omh74ZZ6Q&page=66
2017-07-06 17:58:26 | DEBUG | CacheHandler:
 Returning CACHED response for 
http://www.goodreads.com/search.xml?q=lost+in+a+book&key=ckvsiSDsuqh7omh74ZZ6Q&page=65
2017-07-06 17:58:26 | DEBUG | CacheHandler:
 Returning CACHED response for 
http://www.goodreads.com/search.xml?q=lost+in+a+book&key=ckvsiSDsuqh7omh74ZZ6Q&page=64
2017-07-06 17:58:26 | DEBUG | CacheHandler:
 Returning CACHED response for 
http://www.goodreads.com/search.xml?q=lost+in+a+book&key=ckvsiSDsuqh7omh74ZZ6Q&page=63
2017-07-06 17:58:26 | DEBUG | CacheHandler:
 Returning CACHED response for 
http://www.goodreads.com/search.xml?q=lost+in+a+book&key=ckvsiSDsuqh7omh74ZZ6Q&page=62
2017-07-06 17:58:26 | DEBUG | CacheHandler:
 Returning CACHED response for 
http://www.goodreads.com/search.xml?q=lost+in+a+book&key=ckvsiSDsuqh7omh74ZZ6Q&page=61
2017-07-06 17:58:26 | DEBUG | CacheHandler:
 Returning CACHED response for 
http://www.goodreads.com/search.xml?q=lost+in+a+book&key=ckvsiSDsuqh7omh74ZZ6Q&page=60
2017-07-06 17:58:26 | DEBUG | CacheHandler:
 Returning CACHED response for 
http://www.goodreads.com/search.xml?q=lost+in+a+book&key=ckvsiSDsuqh7omh74ZZ6Q&page=59
2017-07-06 17:58:26 | DEBUG | CacheHandler:
 Returning CACHED response for 
http://www.goodreads.com/search.xml?q=lost+in+a+book&key=ckvsiSDsuqh7omh74ZZ6Q&page=58
2017-07-06 17:58:26 | DEBUG | CacheHandler:
 Returning CACHED response for 
http://www.goodreads.com/search.xml?q=lost+in+a+book&key=ckvsiSDsuqh7omh74ZZ6Q&page=57
2017-07-06 17:58:26 | DEBUG | CacheHandler:
 Returning CACHED response for 
http://www.goodreads.com/search.xml?q=lost+in+a+book&key=ckvsiSDsuqh7omh74ZZ6Q&page=56
2017-07-06 17:58:26 | DEBUG | CacheHandler:
 Returning CACHED response for 
http://www.goodreads.com/search.xml?q=lost+in+a+book&key=ckvsiSDsuqh7omh74ZZ6Q&page=55
2017-07-06 17:58:26 | DEBUG | CacheHandler:
 Returning CACHED response for 
http://www.goodreads.com/search.xml?q=lost+in+a+book&key=ckvsiSDsuqh7omh74ZZ6Q&page=54
2017-07-06 17:58:26 | DEBUG | CacheHandler:
 Returning CACHED response for 
http://www.goodreads.com/search.xml?q=lost+in+a+book&key=ckvsiSDsuqh7omh74ZZ6Q&page=53
`

Currently unable to do any searches therefore not able to download any books :)

This issue has been prevalent through the last couple of updates. 

Any help would be appreciated.

Just wondering if I am doing something wrong.

**Comment by philborman** [comment]
No, nothing you're doing. There is an error in page 70 of the search results. GoodReads is sending us a malformed page. I will add a fix later today.
