### ISSUE TITLE
Error requesting goodreads

### ISSUE THREAD

**Issue by tscibilia** [DobyTang/LazyLibrarian#904]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
Current Version: 1207bf081ad416f247ada834e5a4ec868379f371
### Operating system used (windows, mac, linux, NAS type)
Ubuntu 16.04.2
### Interface in use (default, bookstrap)
default
### Which api (Goodreads, GoogleBooks, both)
Goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
git
### Relevant debug log with api keys and any passwords redacted
```
2017-07-09 18:25:12 | INFO | Nothing marked as snatched. Stopping postprocessor.
2017-07-09 18:25:12 | INFO | 0 books/mags processed.
2017-07-09 18:16:43 | INFO | Library scan complete
2017-07-09 18:16:43 | INFO | 70 files processed
2017-07-09 18:16:43 | INFO | 0/0 new/modified eBooks found and added to the database
2017-07-09 18:16:43 | WARNING | Failed to match book [...book name and author...] in database
2017-07-09 18:16:43 | ERROR | Error finding rescan results: Traceback (most recent call last): File "/opt/lazylib/lazylibrarian/librarysync.py", line 664, in LibraryScan if not len(rootxml): TypeError: object of type 'NoneType' has no len()

**REPEAT WARN AND ERROR FOR EACH BOOK**

2017-07-09 18:16:39 | INFO | Missing eBooks will be marked as Wanted
2017-07-09 18:16:39 | INFO | Scanning eBook directory: /mnt/books/Novels
2017-07-09 18:15:11 | INFO | Starting LazyLibrarian web server on http://0.0.0.0:5299/
2017-07-09 18:15:11 | INFO | Starting LazyLibrarian on port: 5299, webroot "/lazylib"
2017-07-09 18:15:11 | INFO | Database is version 21, integrity check: ok
2017-07-09 18:15:11 | INFO | SYS_ENCODING is UTF-8
2017-07-09 18:15:11 | INFO | Config file loaded
2017-07-09 18:15:11 | INFO | Screen Log set to INFO/WARN/ERROR
2017-07-09 18:15:11 | INFO | Log level set to [0]- Log Directory is [/opt/lazylib/.lazylibrarian/Logs] - Config level is [0]
```

I saw the issue #901 and you made a fix with merge request #902 
Since I installed this after that fix, I'm not sure what's causing the error because it seems related. Any help would be appreciated. Thanks!

**Comment by philborman** [comment]
Silly bug,  think I've been bitten by that one before too. 
The xml function returns None if no results. None doesn't have a size. I thought it returned empty, which has size zero.
Just pushed a fix.  Thanks for the bug report,

**Comment by tscibilia** [comment]
thanks for the fix (I'm not getting the 'NoneType' error) but I am still having a problem with GoodReads.
The logs state "failed to match book" & "error requesting goodreads for..."
Do I need to change the goodreads api key? or do you think it's some other issue with goodreads?

I also pinged google.com and goodreads.com from my terminal and it didn't lose any packets so I know the connection is possible.

```
2017-07-11 14:14:11 | INFO | Library scan complete
2017-07-11 14:14:11 | INFO | 70 files processed
2017-07-11 14:14:11 | INFO | 0/0 new/modified eBooks found and added to the database
2017-07-11 14:14:10	WARNING	Failed to match book [Grimms Fairy Tales] by [Wilhelm Grimm] in database
2017-07-11 14:14:10	WARNING	Error requesting GoodReads for Wilhelm Grimm Grimms Fairy Tales
**REPEAT WARN FOR EACH BOOK**
2017-07-11 14:14:04 | INFO | Scanning eBook directory: /mnt/books/Novels
2017-07-11 14:09:29 | INFO | Starting LazyLibrarian web server on http://0.0.0.0:5299/
2017-07-11 14:09:29 | INFO | Starting LazyLibrarian on port: 5299, webroot "/lazylib"
2017-07-11 14:09:28 | INFO | Database is version 21, integrity check: ok
2017-07-11 14:09:28 | INFO | SYS_ENCODING is UTF-8
2017-07-11 14:09:28 | INFO | Config file loaded
2017-07-11 14:09:28 | INFO | Screen Log set to INFO/WARN/ERROR
```

**Comment by philborman** [comment]
Would need more information. The log you have provided is a basic summary.
If you turn debug logging on you will have much more information on what
might be going wrong. Unlikely to be the goodreads api key unless you have
modified it, the default key should be fine. Different with googlebooks,
each user needs their own key for that.

**Comment by tscibilia** [comment]
@philborman sorry for the delay, I didn't get notified of your reply. Attached is the debug log, I hope it helps.
[debug.log](https://github.com/DobyTang/LazyLibrarian/files/1341980/debug.log)

**Comment by philborman** [comment]
Looks like a connectivity error. We get an error fetching the pages from goodreads like this...

Got error response for http://www.goodreads.com/api/author_url/Alexander%20C.%20Schreyer?key=<redacted>: '' 

I have added more debugging messages in the next version to  give more info as the error message after your redacted key is empty.  You could also try setting debug level to 3 which will print a bit more info in the next version

**Comment by tscibilia** [comment]
thanks, I attached a new debug log at level 3. I don't know if it matters but I'm connecting through my own nginx remote proxy server using a subfolder (not subdomain). I connect to it without browser errors so I assume that's not it.
[debug_171004.log](https://github.com/DobyTang/LazyLibrarian/files/1357579/debug_171004.log)

**Comment by philborman** [comment]
Even stranger. We're getting an exception from the urllib2 library, but it doesn't tell us what the exception is (returns an empty string). I did a quick google for this and came up with nothing.

What happens if you try entering the url directly in a browser...
https://www.goodreads.com/api/author_url/Alexander%20C.%20Schreyer?key=<redacted>

**Comment by tscibilia** [comment]
Thanks, 

If I browse to the URL you provided I get a web page stating "invalid API key."
If I browse to the URL with the API key provided in lazylibrarian, I get a valid XML response.
I also tried to curl the link with the API key from the VM I'm running lazylibrarian on and I get the same XML response.

```
<GoodreadsResponse>
<Request>
<authentication>true</authentication>
<key>
<![CDATA[ ckvsiSDsuqh7omh74ZZ6Q ]]>
</key>
<method>
<![CDATA[ api_author_link ]]>
</method>
</Request>
<author id="14554682">
<name>
<![CDATA[ Alexander C. Schreyer ]]>
</name>
<link>
https://www.goodreads.com/author/show/14554682.Alexander_C_Schreyer?utm_medium=api&utm_source=author_link
</link>
</author>
</GoodreadsResponse>
```

I also couldn't save a zip of the log like I normally do (I got an error, see below) but here's what I could get from the lazylibrarian.log file...
[lazylibrarian.log](https://github.com/DobyTang/LazyLibrarian/files/1368522/lazylibrarian.log)

```
Traceback (most recent call last):
  File "/opt/lazylib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/lazylib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/lazylib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/lazylib/lazylibrarian/webServe.py", line 2624, in saveLog
    result = saveLog()
  File "/opt/lazylib/lazylibrarian/common.py", line 553, in saveLog
    header += "sqlite3: %s\n" % lazylibrarian.SQLITE3
AttributeError: 'module' object has no attribute 'SQLITE3'
```

**Comment by philborman** [comment]
Well we're finally getting somewhere. We get a "BadStatusLine" exception, whatever that means. Will need to do some digging around.

The inability to save the log is a separate bug, I renamed a variable to avoid a clash, and missed one copy. Should say SQLITEVERSION instead of SQLITE3. Fixed now, will push a new version later today once I've looked into the badstatusline a bit, Thanks for your help.

**Comment by philborman** [comment]
BadStatusLine seems quite hard to debug. Basically means either we got an error response from goodreads that we don't understand, or we sent something with broken/invalid headers. 
It looks like the only header we add ourselves is the user agent, which in your case will be something like "LazyLibrarian (Linux 4.13.0-12-generic)" so nothing that should cause a problem. I see you are running behind nginx - do you have anything set in lazylibrarian config for proxy host and proxy type, or do you have Enable http proxy checkbox ticked?

**Comment by tscibilia** [comment]
ok, thanks for looking into this more (i feel like it's an issue I'm creating somehow because you have so many working installations). I'll explain my setup below (I'm probably going overboard but I just want to cover my bases in case anything looks odd to you). I don't have the "enable http proxy" or "enable https access to lazylibrarian" checked, I only modified the "web root" field to match my subdirectory in the nginx config below and the "proxy host" field to match my server domain name.

I'm running an Ubuntu 16.04.3 LXC on Proxmox 4.4 (which has the Debian Jessie Linux kernel). The VM is running a single core, 1 Gb ram, 16 Gb hd. In a separate VM (also Ubuntu on the same Proxmox node) I'm running an Nginx reverse proxy server with basic auth with the following configuration (among other configs):

```
server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name <my-server>;

  include /etc/nginx/snippets/strong-ssl.conf;
  ssl_certificate /etc/letsencrypt/live/<my-server>/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/<my-server>/privkey.pem;
  root /var/www/html;

  location /lazylib {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://<my-internal-ip>:5299;
  }
}
```

If I curl my external URL (so you can get a sense of what;s in my strong-ssl.conf file)...

```
curl -v https://<my-server>/lazylib
*   Trying <my-external-ip>...
* Connected to <my-server> (<my-external-ip>) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 692 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: <my-server> (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: CN=<my-server>
*        start date: Tue, 26 Sep 2017 19:39:00 GMT
*        expire date: Mon, 25 Dec 2017 19:39:00 GMT
*        issuer: C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3
*        compression: NULL
* ALPN, server accepted to use http/1.1
> GET /lazylib HTTP/1.1
> Host: <my-server>
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Server: nginx
< Date: Tue, 10 Oct 2017 20:20:15 GMT
< Content-Type: text/html
< Content-Length: 6359
< Connection: keep-alive
< Keep-Alive: timeout=5
< Www-Authenticate: Basic realm="LazyLibrarian"
< Strict-Transport-Security: max-age=63072000; includeSubdomains
< X-Xss-Protection: 1; mode=block
<
```

**Comment by philborman** [comment]
ok, so you have proxy_host set, but not proxy_type? 
A couple of suggestions...  well three actually...
1. Try with proxy_type http (not sure how httplib handles requests without type)
2. Try without proxy host or proxy type set (could be nginx transparent proxy doesn't need them)
3. New version out in a day or so has been rewritten to drop httplib and use a more modern requests library and also allows multiple proxy types (http, https, socks5) because goodreads is dropping plain http requests in December.

**Comment by tscibilia** [comment]
Ok I'll look for that update but can you be a bit clearer on the proxy_type? I don't see that in the nginx docs and I'm not sure of the variable/value you had in mind. 

https://nginx.org/en/docs/http/ngx_http_proxy_module.html

Are you thinking:
proxy_set_header Content-Type "text/html";

**Comment by philborman** [comment]
It's the settings in lazylibrarian config, 
![screenshot from 2017-10-11 13-31-10](https://user-images.githubusercontent.com/12158777/31438521-b13875bc-ae88-11e7-8303-ec335bf2ea60.png)
I would suggest trying with both host and type empty, as nginx is quite good at transparent proxying so does not need them, and if that fails set both host and type and try again. I think from what you said earlier you have host set, but not type.  In the screenshot above it says type is a comma separated list, but in the version of lazylibrarian you are running it only supports a single type.

**Comment by tscibilia** [comment]
son of a b!tch, it worked!
when I removed the values from both _proxy host_ and _proxy type_ it started adding authors and books. 

Thanks for the help, sorry for the trouble (i thought those fields should be filled). Maybe add some additional info on the [wiki page](https://github.com/DobyTang/LazyLibrarian/wiki/Configuration#proxy-details) about this for future reference.

**Comment by philborman** [comment]
I think you need either both boxes filled, or none. Depends on your proxy. Next version of lazylibrarian uses a different library and rejects any proxy settings with an unrecognised or missing type.

**Comment by tscibilia** [comment]
Great news, but does that mean this might break on me in the future since I now have both fields blank?

**Comment by philborman** [comment]
No, should be fine with nginx
