### ISSUE TITLE
Downloading Audiobooks

### ISSUE THREAD

**Issue by abarber229** [DobyTang/LazyLibrarian#907]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
    - Says I'm on the latest version
### Operating system used (windows, mac, linux, NAS type)
    - Windows
### Interface in use (default, bookstrap)
    - Bootstrap
### Which api (Goodreads, GoogleBooks, both)
    - I'm assuming both as I left it as the default
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
    - Zip download
### Relevant debug log with api keys and any passwords redacted
    - Logs show that it's looking for eBook and finding the eBook to download and process. 

I see that there is an Audiobook/eBook filter on the right hand side of the author page. However, I do I specify for it to search/download the Audiobook and not the eBook. I'm sure I'm just missing a config or not searching properly. Any help is much appreciated. Thank you!

**Comment by philborman** [comment]
Put the "Library" select box (AudioBook/Ebook) to Audiobook, and select the titles you want by ticking the boxes on the left column. Then put the "Mark Selected As" select box to Wanted and hit Go
LazyLibrarian will go off and search, and try to find audiobooks.
Not all providers tell us what's an audiobook or an ebook, so you might also need to use the filters in config. NZB is usually ok, but torrents are quite bad at telling us what's in them. Where possible lazylibrarian will reject on words in the title or filesize being too large or too small, but some providers or uploaders don't include details in the title, or give a filesize.

**Comment by goldharv** [comment]
My objective is to have LazyLibrarian only search and download audiobooks. I saw a post that said to change the config ebook file type to mp3 and wav. This seems to be working, but I'm getting 2 copies of the same audiobook.

Is there a better way to eliminate the download of ebooks and to only download one copy of the audiobook?

**Comment by philborman** [comment]
I have never tried it, but I think if you set ebook type to something you are not going to get, say .xyz should stop any ebooks arriving as nothing will match.

I think the post you saw suggesting setting it up that way was before lazylibrarian got a proper audiobook mode.  At the moment there is no way to disable ebooks completely (as you can with audiobooks or mags) but that might get added. For now you will just have to make sure you set the library selector on the authors page to Audiobook each time before marking books as wanted.
