### ISSUE TITLE
Magazine search past issues not showing any results even though log shows 7

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#908]
Found 127 results for Solis. 0 new, 13 old, 108 fail date, 0 fail name, 6 rejected: 0 to download

The debug log entry above indicates that LL found 13 past issues correct?
When I go to 'Past Issues' nothing is populated in the list? Oddly, nothing shows for Skipped, Have, or Ignored.

**Comment by philborman** [comment]
Should all appear under "skipped" but there's a bug. Fixed now, will push a new version shortly.

**Comment by MrMxyzptlk** [comment]
Thanks.
