### ISSUE TITLE
Possible bug? Magazine past issues 'Have' not showing any magazines?

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#911]
Not sure if this is a 'feature' or bug?

Your latest fix now is showing skipped and ignored magazine past issues, in manage.
'Have' is not showing any magazines; shouldn't that show all of my past issues that are in LL?

**Comment by philborman** [comment]
Not really a bug, more a pointless design feature. It's like the "books" options,  where "have" is used to tell lazylibrarian "I've got this book, don't download another copy". Useful if you have the paperback, or you have the ebook but it's not in the lazylibrarian library. It's pointless for magazine past issues as the list is generated fresh each scan. I have removed it.
