### ISSUE TITLE
Skipped magazines changing status to wanted issue...

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#914]
When I select magazines under back issues, and changed some skipped issues to wanted; LL downloads and adds the mags, but they still show under skipped?

**Comment by philborman** [comment]
Yes, the "wanted" list is in a separate table. "past issues" list is discarded and reloaded on each magazine search so it shows what was skipped by the postprocessor. Although we could change the status in the "past issues"  table when you manually select a magazine, it's probably not worth it.

**Comment by MrMxyzptlk** [comment]
No problem, if it's not a simple change don't worry about it.
I just thought it was funny after changing a few past skipped issues to wanted that they still show as skipped.
