### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#915]
Just saying thanks for how much time you are putting into this.

Coincidentally, after the last LL update; LL started removing finished jobs from both SABnzbd and Deluge?
Not sure what changed...

**Comment by philborman** [comment]
No problem, I'm enjoying the challenge!
The sab/deluge change was fixed a few weeks ago. nzbget still isn't quite right, it reports that it doesn't recognise the delete command, but deletes it anyway :-)
