### ISSUE TITLE
Feature Request: Sync GoodReads shelf to search for books

### ISSUE THREAD

**Issue by ethanopp** [DobyTang/LazyLibrarian#917]
It would be great to just mark a book in goodreads.com as "Want to Read" and then LazyLibrarian add that book as Wanted and start searching for it!

**Comment by philborman** [comment]
You already can. If you look at the bottom of your goodreads shelf there should be an orange RSS link.
Put this link into lazylibrarian as an rss provider and it will add all the books into your lazylibrarian library and mark them as wanted.
Note - it does not automatically add the authors. If the author is not already in your library they get added as an ignored author, and lazylibrarian does not ask for a list of all their books, just the books in the goodreads list. The idea is you maybe don't know if you like the author yet, you can always change them from ignored to active if you do.

**Comment by ethanopp** [comment]
Ah Awesome!! If I add some family members RSS feeds as well, can it handle duplicate books between our shelves and know not to add twice?

**Comment by philborman** [comment]
Of course. It needs to be able to handle duplicates because next time it grabs your goodreads list the same books will still in it, unless you removed them.

**Comment by ethanopp** [comment]
Great got it working! Thanks
