### ISSUE TITLE
Request:Magazine Metadata

### ISSUE THREAD

**Issue by Code-Slave** [DobyTang/LazyLibrarian#919]
When writinf the opf file can you add magazine title as series name? this will help in calibre for sorting and grouping tremendously. The stuff there works well for importing as long as you do one mag directory at a time but thats a calibre issue.

**Comment by philborman** [comment]
Do you have an example of how calibre stores series details in metadata, or any calibre documentation on it's metadata.opf layout?  It would be easy enough to add, but need to stay compatible with what calibre expects. I had a quick look at my calibre library but couldn't find any series info.

**Comment by philborman** [comment]
ok, found an example.
we now create metadata like this...
```
<?xml version="1.0"  encoding="UTF-8"?>
<package version="2.0" xmlns="http://www.idpf.org/2007/opf" >
    <metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
        <dc:title>Craft Beer and Brewing - April 2017</dc:title>
        <creator>Craft Beer and Brewing</creator>
        <dc:language>eng</dc:language>
        <dc:identifier scheme="GoogleBooks">278ecd5169e82300ca27d836a4cd4517f835fa26</dc:identifier>
        <dc:date>2017-06-10</dc:date>
        <meta content="Craft Beer and Brewing" name="calibre:series"/>
        <meta content="2017-04-01" name="calibre:series_index"/>
        <guide>
            <reference href="2017-04-01.jpg" type="cover" title="Cover"/>
        </guide>
    </metadata>
</package>
```
Creator (author) and Series are both set to magazine title, but the Title field (normally the book title) is set to magazine name and date. Hopefully the issue date will work as a series index.

**Comment by Code-Slave** [comment]
sorry. Was away. Thanks. Works perfect
