### ISSUE TITLE
Guest requests / guest account

### ISSUE THREAD

**Issue by xthursdayx** [DobyTang/LazyLibrarian#920]
Hi, there, first, thanks for all you're done for this. It's really amazing so far. I just have two questions which might help to improve functionality.

First, I was wondering what the non-functioning [import CSV wishlist] button at /manage/ is for? Is there a way to import the .CSV from my Goodreads bookshelves into LazyLibrarian? That would be really useful as a way to import the books/authors on my 'too read' shelf and then find then books.

Second, I know that this is probably crazy to even think about implementing, but I was wondering if there is a way to give a guest access (even within the local network if necessary) in order to request a title, something like PlexRequests. I have no idea how to implement something like this, but since my wife is also a ravid reader, it would be awesome if she could just like enter a book title or author name into a form from a simple local webpage, which would then get transmitted as an 'add' request to LazyLibrarian. Thoughts?

**Comment by philborman** [comment]
The [import CSV wishlist] is used to import a wishlist of books from lazylibrarian/goodreads/other sites
eg if you export your list of currently wanted books from lazylibrarian to reimport into another lazylibrarian. It should also work with goodreads wishlists, certainly used to work, though I haven't tried it recently. It just needs the csv file to contain columns called "Author" and "Title", with optional isbn or other id. Anything else gets ignored.

If you want to import a goodreads bookshelf, eg your "want to read" page, you can use the rss button at the bottom of the goodreads webpage. Put that into lazylibrarian as an rss provider and it will try to grab those books, and then monitor the feed for changes.

Not sure about guest requests, I don't use plex so don't know what it does. If you can log into a web page to send a request, why not just log into lazylibrarian and do it directly? Not sure I understand the purpose.

**Comment by philborman** [comment]
The import csv function looks in your "alternate directory" for a csv file, you do not get the option to input a filename. If you use the bookstrap interface and there is no csv file found, you get a popup telling you. Default interface doesn't have this feature, but I think it prints a message in the log?

**Comment by philborman** [comment]
The guest request thing would be hard to implement in lazylibrarian, for me at least, but a separate program  could do it. All the required features are available in the lazylibrarian api. Just need a program that hosts a webpage with login, and talks to lazylibrarian api to do searches and request books.

**Comment by MrMxyzptlk** [comment]
Try talking to the dev of Organizr: https://github.com/causefx/Organizr
I use this app to great success, and it combines all of my apps.

I had already requested that he add LL to his app...go check it out and +1

**Comment by philborman** [comment]
I use muximux for this, https://github.com/mescon/Muximux
you add your own apps, no extra config required.

**Comment by MrMxyzptlk** [comment]
I tried MuxiMux, but couldn't find anyway to aggregate the plex media / calender / search on the home page dashboard?

**Comment by philborman** [comment]
Back to the guests request thing again. 
I'm playing with a version here that has user accounts, where you can show/hide/change options depending on  who is logged in and what permission you have granted them. ie you could grant access to ebooks but not magazines, look but can't download, etc. Started as a simple "admin" or "guest" login, but it might be getting over complicated now.

At the moment you can restrict users so they can see what's in the database, and send an email to the administrator (you) requesting anything that's not there. I'm thinking of changing the "skipped" button to "request" for users with insufficient permissions. Maybe also change "Open" to request so they can't download without permission. Is that the sort of thing you mean?

**Comment by philborman** [comment]
Basic guest accounts added to latest version, bookstrap interface only, see wiki page for instructions.
Probably best to set up some restricted accounts yourself and see what you can/can't do.
