### ISSUE TITLE
Problem with accent 

### ISSUE THREAD

**Issue by zobi** [DobyTang/LazyLibrarian#921]
Hello, 

i'm french and i have a problem with french title of ebook, lazy debug who me an error when i try to insert a book with accent (éèàù ...) this is the log 

18-juil.-2017 16:16:37 - INFO    :: SEARCHBOOK : Requesting eBook download: 99% http://192.168.2.103:9117/torznab/XXXXXX: Marc Levy La Derniere des Stanfield FRENCH Epub NoGrp
18-juil.-2017 16:16:39 - DEBUG   :: SEARCHBOOK : Sending Marc Levy - La derniere des Stanfield LL.(34540520) to blackhole
18-juil.-2017 16:16:39 - ERROR   :: SEARCHBOOK : Unhandled exception in downloadResult: Traceback (most recent call last):
  File "/XXX/XXX/LazyLibrarian/lazylibrarian/resultlist.py", line 238, in downloadResult
    controlValueDict["NZBurl"], auxinfo)
  File "/XXX/XXX/LazyLibrarian/lazylibrarian/downloadmethods.py", line 261, in TORDownloadMethod
    logger.debug("Failed to write torrent to file %s, %s" % (tor_path, str(e)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 32: ordinal not in range(128)

18-juil.-2017 16:16:39 - INFO    :: SEARCHBOOK : Search for Wanted items complete, found 0 books

Thanks a lot for your help

**Comment by philborman** [comment]
This will be fixed in the next version.
Blackhole is generally not recommended, it is better to use the torrent downloaders directly if you can.

**Comment by zobi** [comment]
Thanks a lot, 

unfortunately i can't use direct download torrent, my torrent client isn't on the same computer

**Comment by zobi** [comment]
same problem with the upgrade, i don't know if it's really accent's problem...

**Comment by philborman** [comment]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 32: ordinal not in range(128)
The error report is definitely an accent problem, 0xc3 is an accented character, the next byte says which character, eg 0xc3 0xa9 is e-acute. We are failing to write the torrent to a file, and then failing to correctly print the error message saying what the problem was. I fixed (I think) the write error, I will add some code to strip the accent out of the error message to see if we can get more info.

**Comment by sscraggles** [comment]
Here's a related error I just had, which causes a manual library scan to exit. 
Latest LazyLibrarian version, OS= Debian 9.

`20-Jul-2017 13:35:04 - DEBUG   :: AUDIO_SCAN : [/media/Audio Books] Now scanning subdirectory /Clark Ashton Smith/The Maze of Maâl Dweb
20-Jul-2017 13:35:04 - ERROR   :: AUDIO_SCAN : Unhandled exception in libraryScan: Traceback (most recent call last):
  File "/opt/LazyLibrarian/lazylibrarian/librarysync.py", line 525, in LibraryScan
    book = book.decode(lazylibrarian.SYS_ENCODING)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe2 in position 14: invalid continuation byte
`

**Comment by zobi** [comment]
Here the new debug log : 

p
20-juil.-2017 18:26:45 - DEBUG   :: SEARCHBOOK : Sending Marc Levy - La derniere des Stanfield LL.(34540520) to blackhole
20-juil.-2017 18:26:45 - DEBUG   :: SEARCHBOOK : Failed to write torrent to file: 'ascii' codec can't decode byte 0xc3 in position 322: ordinal not in range(128)
20-juil.-2017 18:26:45 - DEBUG   :: SEARCHBOOK : Progress: Opening Writing
20-juil.-2017 18:26:45 - DEBUG   :: SEARCHBOOK : Filename [u'/Dropbox/Toto/Bouquins/Marc_Levy_-_La_derniere_des_Stanfield_LL.(34540520).torrent']
20-juil.-2017 18:26:45 - INFO    :: SEARCHBOOK : Search for Wanted items complete, found 0 books

File .torrent is created in the good directory but the file isn't a torrent file just an empty file

**Comment by philborman** [comment]
Seems the torrent files should not use utf-8
I have removed the encoding line and tried with accented torrent here, "Henri Charrière, Papillon" and it seems to work, can you try the new version.

**Comment by zobi** [comment]
Nice Job ! 
It works ;)
Thanks a lot for your work
