### ISSUE TITLE
Request: method to ignore directories from library scan

### ISSUE THREAD

**Issue by sscraggles** [DobyTang/LazyLibrarian#925]
### LazyLibrarian version number (at the bottom of config page)
latest
### Operating system used (windows, mac, linux, NAS type)
Debian 9
### Interface in use (default, bookstrap)
bookstrap
### Which api (Goodreads, GoogleBooks, both)
Goodreads, its great
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
git clone
### Relevant debug log with api keys and any passwords redacted

I've got a bunch of stuff in my audio book directory tree which won't ever get indexed, is there a way to have LazyLibrarian ignore it from library scan?  For my player, mpd can have a .mpignore file, so perhaps something like .llignore ?

**Comment by philborman** [comment]
At the moment we ignore directories starting with underscore, which is why magazine folders in the library have to start with underscore. I think it should be easy enough to change though, or use both methods so we don't break existing users.

**Comment by sscraggles** [comment]
Yes, the underscore is ideal for magazines as calibre will ignore it.  Having a dotfile would help not re-organise great swathes of my library causing problems in other applications.

**Comment by philborman** [comment]
ok, that's in the next version. Put a file called .ll_ignore in each directory you want to skip.

**Comment by sscraggles** [comment]
.ll_ignore only seems to work on primary directories off the audio_dir and not sub-directories therein.

**Comment by philborman** [comment]
Seems to work here, knocks out whole authors with one .ll_ignore file ?

**Comment by sscraggles** [comment]
I tested again, I can exclude at author level directory, but not at book level.
As an example, I have an Author "Alan Watts", with numerous book directories within.  I can exclude "Alan Watts" by placing a .ll_ignore file, but I can't exclude the book "Alan Watts/lectures" by creating the file in that subdirectory.
The author has a large range of books, but also a large body of unpublished lectures.

**Comment by philborman** [comment]
Ok, that's fixed now. Was using the wrong base in the path for directory.  Using your example, it was looking for /library/lectures/.ll_ignore instead of /library/Alan Watts/lectures/.ll_ignore
Will push this in the new version later today.

**Comment by sscraggles** [comment]
Yep, that's doing it's job nicely.
