### ISSUE TITLE
library scan fails on files with accent

### ISSUE THREAD

**Issue by sscraggles** [DobyTang/LazyLibrarian#926]
### LazyLibrarian version number (at the bottom of config page)
latest
### Operating system used (windows, mac, linux, NAS type)
Debian 9
### Interface in use (default, bookstrap)
bookstrap
### Which api (Goodreads, GoogleBooks, both)
Goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
git clone
### Relevant debug log with api keys and any passwords redacted

`20-Jul-2017 13:35:04 - DEBUG   :: AUDIO_SCAN : [/media/Audio Books] Now scanning subdirectory /Clark Ashton Smith/The Maze of Maâl Dweb`
`20-Jul-2017 13:35:04 - ERROR   :: AUDIO_SCAN : Unhandled exception in libraryScan: Traceback (most recent call last):
  File "/opt/LazyLibrarian/lazylibrarian/librarysync.py", line 525, in LibraryScan
    book = book.decode(lazylibrarian.SYS_ENCODING)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe2 in position 14: invalid continuation byte
`

**Comment by sscraggles** [comment]
Another example..

`20-Jul-2017 14:12:05 - INFO    :: AUDIO_SCAN : Scanning Audio directory: /media/Tosh3/Audio Books`
`20-Jul-2017 14:12:05 - DEBUG   :: AUDIO_SCAN : [/media/Tosh3/Audio Books] Now scanning subdirectory /Erich Von Däniken/Chariots of the Gods
20-Jul-2017 14:12:05 - ERROR   :: AUDIO_SCAN : Unhandled exception in libraryScan: Traceback (most recent call last):
  File "/opt/LazyLibrarian/lazylibrarian/librarysync.py", line 527, in LibraryScan
    author = author.decode(lazylibrarian.SYS_ENCODING)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 11: invalid continuation byte
`

**Comment by philborman** [comment]
I'm really beginning to hate unicode. Accented characters are a pain.
It looks like the mp3 files have tags where author/title  accented characters are not utf-8, and can't be decoded to utf-8. This will need some looking into. 
I don't suppose you can email me one of the files with an accented tag in it so I can have a look, or a link to a site where I can download one?  If I can reproduce the problem I can probably fix it, but looking at the code it seems we think the tags are 8 bit ascii and can't decode them properly.

**Comment by sscraggles** [comment]
I sent you a file in email reply.  I recall that headphones uses beets, which in turn uses mutagen for variations in id3 version differences.

**Comment by philborman** [comment]
Found a nice small library that reads id3 tags, just trying it out now. Nothing arrived by email, maybe email size limit issue? If the library looks ok I will push a new version in the next hour or two, maybe you can try and report back?

**Comment by sscraggles** [comment]
Sure, I'm ready and happy to test something.
I sent an attachment and also a link to sendfiles.net.  Maybe mail relays on my side, just resent through the proper path.

**Comment by philborman** [comment]
Still no email, but I tried the new library on some of my music files with accented artists and titles, all seems ok, so I have uploaded the new version

**Comment by sscraggles** [comment]
Yep, I repeated the test in a small test instance with just the problem files and the search completes and matches one of the audio books.  I'll look later into what's going on with the other, maybe tags on the multiple files it contains?
