### ISSUE TITLE
Authors page / home page slow to load

### ISSUE THREAD

**Issue by sscraggles** [DobyTang/LazyLibrarian#929]
### LazyLibrarian version number (at the bottom of config page)
latest today, 9b5daf82e4f1a54fa192f671e79acb42e4330f7e
### Operating system used (windows, mac, linux, NAS type)
Debian 9
### Interface in use (default, bookstrap)
Bookstrap
### Which api (Goodreads, GoogleBooks, both)
Goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
Git clone
### Relevant debug log with api keys and any passwords redacted

With 800+ authors indexed, the home/authors page is slow to load, it takes some 5s on my creaky notepad.  Looks like all the authors are within the downloaded HTM as the page is ~5MB.  Will this be paginated off the server in future.

**Comment by philborman** [comment]
Can be done, several other pages use server-side processing already for this reason. I've only got 200 or so authors and it's not that slow. Might take a day or two to get it added, bit more of a challenge.  For now maybe disable author images to speed it up?

**Comment by philborman** [comment]
The bookstrap interface has column toggles, so you can toggle them on/off at will, which overrides the "disable author images" config button. Can probably be changed.
I just got server-side author page sorted out, wasn't too hard. Just a bit more testing and might push it later today.

**Comment by sscraggles** [comment]
Awesome!

**Comment by sscraggles** [comment]
Tried the new release, that makes a tremendous difference.  Great stuff!
