### ISSUE TITLE
No "Authors" link, and Ajax error

### ISSUE THREAD

**Issue by PearsonFlyer** [DobyTang/LazyLibrarian#932]
After the most recent LL update, I have no "Authors" tab.  When I click on the LazyLibrarian link at the top of the page, or restart the service, a box pops up with this text in it:

> DataTables warning: table id=author_table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

There are no entries in the log, even with debug running.

LL version: ddb9d30e4ac9327d02fce276a91f6e6d72e6b1f1
OS: Windows 10, creators
Interface: Bookstrap
API: GoogleBooks
Source: Git

There are no entries in the log containing any errors or warnings, it does not appear to be logging even my attempt to locate the "Authors" page.  The other tabs are all populated with the proper entries, so I know the Authors are there.

**Comment by philborman** [comment]
The authors tab was removed as the lazylibrarian homepage does exactly the same thing, seemed a waste of screen space having two buttons pointing to the same page. The ajax error is a bit more of a problem,  particularly without any logging. Usually means we are not passing enough columns to the table, but at the moment I can't see how as it's working here.  I see you are on googlebooks, does the error also happen on goodreads. Also do you have column toggles enabled, author images enabled?  Just trying to narrow down where to start looking!  The log does not show what pages you view, so that's normal, but not too helpful in this case.

**Comment by philborman** [comment]
Actually I think I might know what's going on here. I think the old pre-upgrade lazylibrarian might still be running and that's the one you are seeing. Lazylibrarian upgraded, hence the new html page, but the old code is still running and doesn't send data in the way the new page expects. If the old one is still running then the new one will not start as the port is in use.  If you go to config (which should still work, no ajax needed) and select "Shutdown" and then start again it should get you going.

**Comment by PearsonFlyer** [comment]
I've stopped and started the program, and still get the same error on the "main" screen (which is supposed to list authors, but just has the headers and no authors now).  I do have column toggles enabled, and author images enabled.

I switched to GoodReads API, and still the same error. I switched to the default interface, and it doesn't throw the error on the screen, but also the Authors (and LazyLIbrarian) page is empty except for the table headers.

**Comment by philborman** [comment]
Ok, then I guess we are getting an error in the new table generator function, but I'm unable to reproduce it here. I will add some extra debugging messages into that routine and post a new version, should help narrow it down. The "traceback" code we use in other parts of lazylibrarian doesn't work in the webserver, unfortunately.

**Comment by philborman** [comment]
Just pushed a new version with verbose debugging messages in the author page generator. If you turn debug level up to 4 and then try to display the author page we should get an idea what's going on.

**Comment by PearsonFlyer** [comment]
I updated and turned the debug level up to 4, and displayed the author page a couple of times with other pages.  Here's the debug log (with my host and api redacted)

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1168218/debug.zip)

**Comment by philborman** [comment]
Ah, that's found it thanks.
23-Jul-2017 12:34:57 - DEBUG   :: CP Server Thread-4 : getIndex 50: [u'cache/author/566.jpg', u'Paulo Coelho', u'The Paulo Coelho Collection', u'2017', u'Active', u'http://www.goodreads.com/author/show/566.Paulo_Coelho', u'http://www.goodreads.com/book/show/31144272-the-paulo-coelho-collection', None, None, u'566']

The two "None" entries are causing the issue, these are the "have" and "total" book counts. I need to trap these and change them to zero. Not sure how they are None, default is zero.

**Comment by PearsonFlyer** [comment]
After updating to this latest version, LL refuses to start up.  I use an nssm service, and it keeps trying to start it back up.  In my event log, I get "Program c:\python27\python.exe for service Librarian exited with return code 1.", and there are no LL logs for this.

**Comment by philborman** [comment]
Can you try it from a command prompt? Should get some logging to the console then.
cd into the LazyLibrarian folder and then...
c:\python27\python.exe  LazyLibrarian.py

**Comment by PearsonFlyer** [comment]
I just grabbed the very latest version, stopped the nssm service, unzipped in place, and restarted, and now it seems to be working. Must have had something go wrong with the in-page update.  The authors page is back, and I'm all good.  Closing this issue. Thank you for all of your help!
