### ISSUE TITLE
Fails to create magazine cover images

### ISSUE THREAD

**Issue by sscraggles** [DobyTang/LazyLibrarian#936]
I'm observing that cover images are failing to create, there are some present, but its either sporadic or not recent.
```
23-Jul-2017 18:25:59 - DEBUG   :: POSTPROCESS : Creating cover for /srv/booktest/_Magazines/Professional Motorsport World/2016/2016 - Professional Motorsport World.pdf
23-Jul-2017 18:25:59 - DEBUG   :: POSTPROCESS : Unable to create cover for /srv/booktest/_Magazines/Professional Motorsport World/2016/2016 - Professional Motorsport World.pdf using pythonmagick interface
23-Jul-2017 18:25:59 - DEBUG   :: POSTPROCESS : Exception in gs create_cover: Traceback (most recent call last):
  File "/opt/LazyLibrarian.test/lazylibrarian/magazinescan.py", line 198, in create_cover
    img.read(issuefile + '[0]')
ArgumentError: Python argument types in
    Image.read(Image, unicode)
did not match C++ signature:
    read(Magick::Image {lvalue}, Magick::Blob, Magick::Geometry, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
    read(Magick::Image {lvalue}, Magick::Blob, Magick::Geometry, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
    read(Magick::Image {lvalue}, Magick::Blob, Magick::Geometry, unsigned int)
    read(Magick::Image {lvalue}, Magick::Blob, Magick::Geometry)
    read(Magick::Image {lvalue}, Magick::Blob)
    read(Magick::Image {lvalue}, Magick::Geometry, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
    read(Magick::Image {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)

```

but I can create them manually using a snippet of the code (slowly learning little bits)
and it will appear in the front end if I delete the cached image.
```
import PythonMagick
inputfile = "/srv/booktest/_Magazines/Professional Motorsport World/2016/2016 - Professional Motorsport World.pdf"
outputfile = "/srv/booktest/_Magazines/Professional Motorsport World/2016/2016 - Professional Motorsport World.jpg"
img = PythonMagick.Image()
img.read(inputfile + '[0]')
img.write(outputfile)
```

**Comment by philborman** [comment]
Problem here is unicode. PythonMagick expects the filename to be a str, not unicode, but magazine titles with accents in or hyphens/quotemarks that are not standard ascii will not work. I can put an ascii conversion in, but it might break some filenames. Seems to be a pythonmagick restriction, the wand interface works with unicode, as does ghostscript.

**Comment by sscraggles** [comment]
I hear how you read the error message, but I don't understand how I can subsequently use the same code with success.  Maybe it's a timing thing, with the file not fully copied from one disk to another before the image is attempted? 
I tried to configure /usr/bin/convert but that seems to create one image each for every page of the PDF.

**Comment by philborman** [comment]
Your code is using strings by default. 
Lazylibrarian uses unicode to allow accented names, eg "Québec L'Actualité"
You can make your example above fall over with exactly the same error message by forcing inputfile to be unicode. This should do it...
inputfile = "/srv/booktest/_Magazines/Professional Motorsport World/2016/2016 - Professional Motorsport World.pdf".decode('utf-8')

**Comment by philborman** [comment]
I put a fix in for unicode with pythonmagick - just strips accents and converts to ascii. Not perfect, but will only break on magazines with accented characters I think.  ImageMagick convert should still work, but needs a small wrapper around it. I used to use it all the time before I added ghostscript. There were problems with some NAS systems not including imagemagick. 
The wrapper command would look like...
convert magazine.pdf[0] image.jpg
The [0] on the end means just convert page zero, so your wrapper would need to add the [0] to the end of the first parameter. It gets passed 2 parameters, input.pdf, output.jpg
In bash you would do something like...
#!/bin/bash
/usr/bin/convert $1[0] $2

You could add more lines to error trap it, but for your own use this would probably do. Just save it as "mycovercreator.sh"  and put that name into lazylibrarian config

Alternatively there is a gsconvert.py program supplied with lazylibrarian that uses ghostscript to do the same thing. Overkill, as ghostscript internally calls imagemagick,  but again useful for nas systems without either imagemagick or ghostscript installed. Just install ghostscript using the instructions in the lazylibrarian wiki and off you go.

**Comment by sscraggles** [comment]
```
26-Jul-2017 18:10:22 - DEBUG   :: POSTPROCESS : Creating cover for /home/scraggles/booktest/_Magazines/modern mini/2016-10-01/2016-10-01 - modern mini.pdf
26-Jul-2017 18:10:25 - DEBUG   :: POSTPROCESS : Unable to create cover for /home/scraggles/booktest/_Magazines/modern mini/2016-10-01/2016-10-01 - modern mini.pdf using pythonmagick interface
26-Jul-2017 18:10:25 - DEBUG   :: POSTPROCESS : Exception in create_cover: Traceback (most recent call last):
  File "/opt/LazyLibrarian.test/lazylibrarian/magazinescan.py", line 202, in create_cover
    img.write(coverfile)
ArgumentError: Python argument types in
    Image.write(Image, unicode)
did not match C++ signature:
    write(Magick::Image {lvalue}, Magick::Blob*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int)
    write(Magick::Image {lvalue}, Magick::Blob*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
    write(Magick::Image {lvalue}, Magick::Blob*)
    write(Magick::Image {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
```

I've uninstalled PythonMagic and allowed LazyLibrarian to revert to gs.  Deleted cached images in ~/.lazylibrarian/cache/magazines/ and the problem has gone away for me.

**Comment by philborman** [comment]
ok, I might remove PythonMagick as an option. Not really needed now anyway.
