### ISSUE TITLE
LL not starting on windows

### ISSUE THREAD

**Issue by Luminaii** [DobyTang/LazyLibrarian#940]
I couldn't start the program on windows using the latest files (I just cloned the repo). The error I got was that there was no module named 'lazylibrarian'. Turns out because the folder name is capitalized ('LazyLibrarian') it can't load the module. After renaming the folder to 'lazylibrarian' it started just fine.

**Comment by philborman** [comment]
Well that's really odd. I just checked the repo and it's definitely lowercase there. Top level folder is LazyLibrarian, but the module inside is lowercase as it should be.

**Comment by Luminaii** [comment]
From my experience with python on Windows the folder name is the module name. So it doesn't really matter what's inside it if it can't find the module to begin with.

**Comment by philborman** [comment]
The structure of the git, and zip is...
LazyLibrarian/
    LazyLibrarian.py      <--- python executable
    lazylibrarian/            <--- module
        __init__.py           <--- start of main program

so LazyLibrarian.py  references the module lazylibrarian using lowercase

**Comment by Luminaii** [comment]
Yeah that's what got me thinking it was a case sensitivity issue. I just cloned it and it is indeed full lowercase but when I cloned it yesterday I got a module named 'LazyLibrarian' not 'lazylibrarian'. Not sure what happened then.
