### ISSUE TITLE
Custom Search Terms

### ISSUE THREAD

**Issue by Luminaii** [DobyTang/LazyLibrarian#942]
I would love to see a possibility for adding custom search terms.

**Comment by philborman** [comment]
Do you mean altering the per-provider search terms, eg how we talk to the piratebay,  nzbgeek or whatever, or do you mean how we search for a book? 

Modifying the per-provider query is fraught with problems as if you get the parameters wrong you will get back an error page, or irrelevant results. 

Modifying the book search can be done from the manual search page, search by author/title, search by author only, search by title only. There is also a "general" search that doesn't use book categories, and you can modify the book title or author before searching

**Comment by Luminaii** [comment]
I meant the second one. For example I tried to search for the books in the Horus Heresy series from WH40K. They are all books by different authors and the downloads usually don't contain the author, just the name of the book and Horus Heresy. So what I would like is to be able to add custom fields to the search so I can send a search request to an indexer like title + horus heresy. 

I am however interested in the manual search page, I tried to look for it but I can't seem to find it.

**Comment by philborman** [comment]
Manual search page for each book is under each book on each authors page, or on the eBooks tab. Click the word "Manual" under the book title.

On the manual page, add Horus Heresy to the title and select type of search using the dropdown menu

**Comment by Luminaii** [comment]
Ahh I see, well that does it. Thank you!
