### ISSUE TITLE
LL not starting SyntaxError: non-keyword arg after keyword arg

### ISSUE THREAD

**Issue by mgaulton** [DobyTang/LazyLibrarian#944]
Noticed today that LL wasn't started, appears theres an error causing it to not start.

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted
server6:/opt/LazyLibrarian-1-master # mv lazylibrarian.db ../LLconfig/
'lazylibrarian.db' -> '../LLconfig/lazylibrarian.db'
server6:/opt/LazyLibrarian-1-master # mv config.ini ../LLconfig/
'config.ini' -> '../LLconfig/config.ini'
server6:/opt/LazyLibrarian-1-master # rm -rf ./* ; rm -rf ./.* ; git clone https://github.com/DobyTang/LazyLibrarian.git .
rm: refusing to remove '.' or '..' directory: skipping './.'
rm: refusing to remove '.' or '..' directory: skipping './..'
Cloning into '.'...
remote: Counting objects: 13793, done.
remote: Compressing objects: 100% (209/209), done.
remote: Total 13793 (delta 229), reused 244 (delta 139), pack-reused 13445
Receiving objects: 100% (13793/13793), 10.19 MiB | 2.49 MiB/s, done.
Resolving deltas: 100% (9615/9615), done.
server6:/opt/LazyLibrarian-1-master # cp ../LLconfig/lazylibrarian.db .
server6:/opt/LazyLibrarian-1-master # cp ../LLconfig/config.ini .
server6:/opt/LazyLibrarian-1-master # ./LazyLibrarian.py
Traceback (most recent call last):
  File "./LazyLibrarian.py", line 14, in <module>
    import lazylibrarian
  File "/opt/LazyLibrarian-1-master/lazylibrarian/__init__.py", line 31, in <module>
    from lazylibrarian import logger, postprocess, searchbook, searchrss, librarysync, versioncheck, database, \
  File "/opt/LazyLibrarian-1-master/lazylibrarian/postprocess.py", line 996
    processIMG(dest_path, bookimg=data['BookImg'], global_name)
SyntaxError: non-keyword arg after keyword arg
server6:/opt/LazyLibrarian-1-master #

**Comment by hidefog** [comment]
Same problem here after performing an update.  I see this during its failed start up.

Traceback (most recent call last):
  File "/opt/lazylibrarian/LazyLibrarian.py", line 14, in <module>
    import lazylibrarian
  File "/data/media/.opt/lazylibrarian/lazylibrarian/__init__.py", line 31, in <module>
    from lazylibrarian import logger, postprocess, searchbook, searchrss, librarysync, versioncheck, database, \
  File "/data/media/.opt/lazylibrarian/lazylibrarian/postprocess.py", line 996
    processIMG(dest_path, bookimg=data['BookImg'], global_name)
SyntaxError: non-keyword arg after keyword arg

**Comment by mgaulton** [comment]
@philborman  thanks for the quick fix

**Comment by philborman** [comment]
Thanks for that, silly error. Didn't get picked up by pycharm either. Fixed now. 
LazyLibrarian.py --update   will get you up and running again.

**Comment by mgaulton** [comment]
awesome, thanks.
