### ISSUE TITLE
FR: sync author list with goodreads/google

### ISSUE THREAD

**Issue by mgaulton** [DobyTang/LazyLibrarian#948]
I discovered an issue with my database where it wasn't showing any books at all so I'm rebuilding from scratch. Just wondering if LL uploads the list to goodreads and follows the authors when they're added or not.
This would save a lot of hassle down the road if rebuilds are needed.

**Comment by philborman** [comment]
No it doesn't, I don't know if goodreads lets you?
What lazylibrarian does do is allow you to save a wishlist of the "wanted" books in your library.  
A bit late for you now, unless you kept a copy of the old database.
You can  rebuild your database by doing a librarysync to import your existing books and authors, and then re-import the wishlist to add back the "wanted" books and authors.

**Comment by mgaulton** [comment]
Sadly, a drive failure a while back nuked my book collection so its pretty small lol I've now manually synced authors with goodreads, but i still think this is a good idea. Similar to SB/Trakt

**Comment by philborman** [comment]
I see how you can upload a list to goodreads as a csv file, and there is an api where you can automate it from inside lazylibrarian, but I think each user would need a developer key. At the moment there is one "lazylibrarian" key used to search goodreads for books, but it's not tied to a user, so you can't access your bookshelves from lazylibrarian.

If there is a way to automate this, what information would you want to upload to goodreads?
Goodreads doesn't seem to have any system of uploading authors, only books.

Which books should we upload, just the ones you have or also ones you want, and  do you put them on separate goodreads shelves?  Would you use the default goodreads shelves, or should we create our own.

We could for example create shelves called "lazylibrarian wanted", "lazylibrarian have", "lazylibrarian skipped" etc.

Or we could put books you have onto the default "read" shelf, and books marked wanted onto the "to-read" shelf and ignore skipped books?

I guess if we can automate it we should upload any changes every few days so we stay fairly in-sync

**Comment by MrMxyzptlk** [comment]
Just to jump in...the 2nd to last sentence gets my vote. 

"Or we could put books you have onto the default "read" shelf, and books marked wanted onto the "to-read" shelf and ignore skipped books?"

**Comment by mgaulton** [comment]
I believe you're right about the dev key for api, but we already do that for Mylar / comicvine or SB/trakt, its not a huge shift for users to have to have one extra step for functionality.

I was specifically thinking that if you added a author to LL, then you call this https://www.goodreads.com/api/index#author_following.create to also follow them on Goodreads to keep the two in sync.

I also endorse this "Or we could put books you have onto the default "read" shelf, and books marked wanted onto the "to-read" shelf and ignore skipped books?"

**Comment by philborman** [comment]
I've got some working code for goodreads sync, but not using the "author_following" link you gave above. That just seems to opt you in to receiving blog posts, news about the author etc. Maybe you get details of any new books, but no idea what format the message would be, so no use to us.

Current version needs your own goodreads api key/secret, not the default supplied lazylibrarian one, and uses a separate program to generate the goodreads oauth key/secret. Would be good to do it all inside lazylibrarian, but I can't figure that part out yet. The authorisation program is goodreads_auth.py 
run it from a terminal giving your goodreads key and goodreads secret as parameters, eg...

python goodreads_auth.py 12345678 qwertyuiopasdfghjklzxcvbnm

and it will ask you to go to a goodreads webpage to authorise, then print out your oauth key/secret to feed into lazylibrarian config.

The sync happens when you hit the button on the lazylibrarian manage page. I might add an automated task later. Maybe sync every few days?

When you first run it, put debug log on so you can see it running. First time takes a while as there is a goodreads limit of one hit per second, so that's a minimum 1 second for each book we need to add to a shelf, and a few more seconds for downloading the shelf (100 books per page, so that part is quicker)

We sync "Wanted" to your goodreads "to-read" shelf, and sync "Open/Have" to your goodreads "owned" shelf. Anything in "to-read" that's marked in lazylibrarian as "Open/Have" gets moved from the "to-read" shelf to "owned".

The sync is a "merge" so a book in either lazylibrarian or goodreads ends up in both. This means if you delete a book from your goodreads shelf you also need to change it's status in lazylibrarian, otherwise on next sync lazylibrarian will put it back on the shelf.

Just a bit more testing, if it all looks ok I will post the new version in an hour or two.

**Comment by sscraggles** [comment]
Seems to works well, though I did kill it before completing so I could clean up my shelves in GR how I prefer them.
It would be good if the config could be more granular to determine which sync's take place.
For example..
I've got books I haven't read yet, so would prefer not to have them moved from 'to-read' to 'owned'.
Also, it would be preferable to me to not sync books to the 'owned' shelf.  More likely that I've 'borrowed' for 'appraisal' with a snatch from usenet or torrent than strictly owning it.

**Comment by philborman** [comment]
Would be easy enough to make the shelves configurable.  
LL moves anything you own (anything marked Have or Open) to the one shelf as it doesn't know what you've read, only what you own. I take them out of 'to-read' as it seems goodreads won't let you keep the same book in both "to-read" and "read" and it thinks "owned" have been read?

If we move them to a shelf called "lazylibrarian", for example, that might work ok. 
I will look into how to create shelves.

**Comment by philborman** [comment]
Seems you can't create shelves using the api, have to do it on the webpage.
I have added options to configure which shelves to sync to. Wanted books sync to one shelf, Open/Have sync to another, or if you leave a shelf blank, that sync doesn't happen.

**Comment by sscraggles** [comment]
Partial success.  I left the Open/have shelf blank and it didn't add my whole collection into owned. 
 But did still move books from to-read to owned.

**Comment by philborman** [comment]
There is no switch to stop that, but I could add one. It seems goodreads does not allow you to keep the same book in "to-read" and "owned", but it might allow "to-read" and another shelf, would need to check.

**Comment by sscraggles** [comment]
Might be worth looking at the code for the [Goodreads Sync plugin](https://www.mobileread.com/forums/showthread.php?t=123281) to Calibre.

It has the feature to create shelves in goodreads, and also allows books to be on both owned and to-read shelves.

**Comment by philborman** [comment]
Wow thats a comprehensive addon. I don't think we need to be quite so complicated, at least to start with. 
The "create shelf" function is a useful example, very similar to the other functions we use for goodreads, so easy to add. Also found the documentation for it. Easy when you know the name, it's called user_shelves, which sounds like it gives you a list.  One of the options you pass when you create the shelf is a flag called "exclusive", which might mean if a book is on this shelf, it can't also be on another shelf. Might explain the to-read/owned differences, maybe my to-read shelf is set to "exclusive". 

Won't be able to play with this for a few days, trying to get a working calibre compiled on my raspberry pi first.

**Comment by philborman** [comment]
ok, found this on goodreads about exclusive shelves...

> exclusive shelves: All members have three default shelves (read, currently-reading, and to-read), which are mutually exclusive, meaning a book can only be on one of them. Members can create as many additional shelves as they like, and books can be on as many non-exclusive shelves as you desire. This may be useful for shelves such as "reference" or "gave-up-on."


so it seems we should be able to have a book in "owned" and "to-read" without conflict, I must have been getting an error return for a different reason. We can set/clear the exclusive flag on our own shelves, but not on the default ones.

**Comment by sscraggles** [comment]
Retried sync of to-read and wanted, without updating 'owned' shelf into Goodreads with 9a9e03e14a625dcdb5bf2afc8bc152ea270bab71

Observed all working well, new book brought in to Lazylibrarian wanted, no change to owned shelf, and pop-up appears confirming number of syncs.
Also test in config page pop-up appearing correctly.  
Love your work Phil :)

**Comment by mgaulton** [comment]
So i still don't see a button in my UI, i've done the configuration through the INI directly since i dind't have the UI elements but now i'm wondering if something is up.
git says i'm up to date on master.

**Comment by philborman** [comment]
Button is on the taskbar of the "manage" page, should look like this...
![screenshot from 2017-08-22 20-10-57](https://user-images.githubusercontent.com/12158777/29580388-2ce6b816-8776-11e7-9ab7-1ca032a43508.png)

If you don't have that button I would guess you are not up to date in spite of what git says,
you could try cd into your git directory and do a "git pull"

Once you've got that button showing, try running with debug log in a different tab so you get some progress messages in the log. If you have the log in a different tab to the "manage" page, the manage page will get a popup on completion showing the totals.

**Comment by philborman** [comment]
Actually another thought - the button only appears on the manage page if goodreads sync is enabled in config. No point in offering the button if you don't want to sync!
Also it's a bookstrap interface feature so it won't appear in the default interface either.

**Comment by mgaulton** [comment]
ah ha, nice catch. I was not using the bootstrap UI, didn't even realize i had options lol. I have the button now :) thanks.

**Comment by billbo99** [comment]
Could syncing be automated when books are marked "Wanted" or "Open"

**Comment by philborman** [comment]
Could be, but you would also need to sync on delete, sync on successful download (status changes from wanted to open).
 
Would be simpler to have a scheduled task that runs every n hours, that way you would also pick up changes made at the goodreads end. Could just add a "Goodreads sync interval" option in the config and another cron task.

**Comment by philborman** [comment]
Added a scheduled task for this now.

**Comment by mgaulton** [comment]
So did this address the original question of following authors on GR that are in LL?
it morphed into a nice new feature, i just wanted to loop back.
did the api call for "follow_author" ever work/test?

**Comment by philborman** [comment]
The api part is ok, can send the command to follow individual authors, but there are a few things I need to think about. Some more info would be useful...

1. How/why would you use it.
It seems that "follow" just links you into the authors blog, news etc. Doesn't send you anything back in the api response, you just get the blog(s) in your goodreads homepage, unless I'm missing something. If that's all it does, is it even useful to do this in lazylibrarian, or are you better doing it directly in goodreads. 

2. Automating
Would you automatically follow every author you have in lazylibrarian, or select whether to follow each author with a button on their individual lazylibrarian page?

3. Unfollow
When you follow an author, goodreads sends you a "follow" token that you use to unfollow them. We would need to store that token. Why they can't just use the same authorid that you used to follow them is beyond me. Anyway, would need a database column, or maybe even a new table adding for storage in case you delete the author but still want to follow them. If you lose the token you can only unfollow from within goodreads. 

4. Syncing
We would need to somehow sync authors you followed/unfollowed from within lazylibrarian
comparing them to the ones you followed/unfollowed on the goodreads page, taking deletions into account. There doesn't seem to be an api call to get a list of authors you are following, only details on each author that you have a "follow" token for.

**Comment by mgaulton** [comment]
I found that if i follow an author on goodreads, it syncs to LL, as long as
the author is followed on GR.
My use case is
1 if i add an author to LL, and the author isn't followed on GR, it gets
added. this keeps the author lists in sync. By following the authors on GR,
you also get notified of new releases etc automagic.
2. This would be a sync, if in LL add to GR and vice versa. This might get
dangerous if autoadd new authors is enabled as it might bloat.
3. agreed, i figured this might need a schema change as it seems it might
be a net new function.
4. does this do the list of authors of specific author? i thought it was
list. https://www.goodreads.com/api/index#author_following.show

**Comment by philborman** [comment]
That's the only api call I could find,  
URL: http://www.goodreads.com/author_followings/AUTHOR_FOLLOWING_ID?format=xml
you need to give it  AUTHOR_FOLLOWING_ID, which is the token you get back from goodreads when you follow the author, you get a different token for each author, and it's different each time you follow the author. This is the same token you use to unfollow the author, and the results page you get back is just for that one author. There doesn't seem to be a way to get a list of who you are following.

**Comment by mgaulton** [comment]
It appears as if it's a following list at the below link, but the way its worded, i'm wondering if https://www.goodreads.com/api/index#user.following is the function you'd need.

https://www.goodreads.com/user/17770080-mark-gaulton/following

**Comment by mgaulton** [comment]
ohhh i found this which gives a xml file of followed people.
https://www.goodreads.com/user/17770080/following.xml

**Comment by billbo99** [comment]
https://www.goodreads.com/api/index#user.following

**Comment by philborman** [comment]
Yes, but that xml is people, not authors. Friends, people with similar reading lists etc.
Some of them may also be authors, but the id given in the xml is not the authorid, it's their userid for blogs/messages etc. eg the only id on the Stephen King section in the xml is 26367680 but as an author his books are under id 3389

**Comment by billbo99** [comment]
The XML gives you a listing of users that ID is following
[https://www.goodreads.com/user/17770080/following.xml](https://www.goodreads.com/user/17770080/following.xml)

In there we get a link for each person being followed
[https://www.goodreads.com/user/show/42713521-neal-stephenson](https://www.goodreads.com/user/show/42713521-neal-stephenson)

If we grab hold of the integer part of the URL we can query the user with the API
[https://www.goodreads.com/user/show/42713521.xml?key=API_KEY](https://www.goodreads.com/user/show/42713521.xml?key=API_KEY)

This in turn has an XML node that tells you if the user is an author
``` xml
<author>
  <id type="integer">545</id>
  <name>Neal Stephenson</name>
</author>
```

Which can be used to get the authors list of books 
[https://www.goodreads.com/author/show/545?format=xml&key=API_KEY](https://www.goodreads.com/author/show/545?format=xml&key=API_KEY)

**Comment by philborman** [comment]
Ok so if all the users you follow are in the first xml list we can use it. Just filter out the ones who aren't authors. We just need a list of author id's that you are following on goodreads to compare to lazylibrarian list.

The follow/unfollow code is already there, just need to add ID Storage and some sync code now.

**Comment by billbo99** [comment]
Moving from LL to GR

Using a list of AuthorID's in LL it is possible to find out their UserID
[https://www.goodreads.com/author/show/38550?format=xml&key=API_KEY](https://www.goodreads.com/author/show/38550?format=xml&key=API_KEY)

``` xml
<user>
   <id type="integer">3145554</id>
</user>
```

Since the UserID is static, it can probably be stored in the Authors table as an extra field.  To make syncing from followers end point easier to process.

Question how should the data be used.
- Use LL to add/remove authors being followed in GR to match LL "Active" / "Ignore" status.
  - I believe @philborman said that means we need to track Author Tokens
  - Which might be a problem for existing Followed authors to remove

- Use GR as an index of Authors that LL should mark as 'Active' and auto-add their books.
  - Simplest option

- Use "Active" Authors in LL as an index to tell GR to "Follow" them.
  - Maybe we can ignore the Author Token here and have the user manually Un-Follow authors if they so desire

**Comment by philborman** [comment]
Another option is to ignore the authors user ID and just store the author token for those you follow from lazylibrarian. You would also be able to unfollow those from lazylibrarian as we know the token. We can't get at the token for authors you follow outside LL, or if you change the status outside LL as our stored token won't be valid. 

You might only want to follow a few authors in your library rather than all of them, and this would reduce api hits. Goodreads limits you to 1 api call per second and a daily limit too.

**Comment by philborman** [comment]
Just pushed a version with "follow" and "unfollow" to play with.
Two options in config, one adds a button to the author page to follow/unfollow on goodreads, the other automatically tries to follow new authors when you add them to LL.  No sync yet, there are problems...
1. You can only follow an author from LL if they are not already marked followed on goodreads
2. You can only unfollow an author from LL if they were marked followed from LL
3. If you change the follow/unfollow status on goodreads, LL will be unable to change it

**Comment by philborman** [comment]
There is also an api call to mark all your existing authors as "follow" subject to the limitations mentioned earlier...  grFollowAll
also individual authors...
grFollow&authorid
grUnfollow&authorid
yes it is authorid for both, not the follow token. We use the authorid to look up the token.
