### ISSUE TITLE
Import does not import audio books...

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#950]
Is this by design or a bug?

**Comment by philborman** [comment]
I guess you mean the "Import Books" button on the "manage" page?
That's a mix of design and inertia.

All the functions on the  "manage" page are just for books. Magazines don't have anything equivalent, nor do audiobooks.  It's quite a bit of work to get the manage page to function with audio and magazines, and I don't know how useful it is really to be able to import from somewhere else, you can add new magazines/audiobooks into lazylibrarian by dropping them into the right folders and using "libraryscan" to pick them up.

**Comment by MrMxyzptlk** [comment]
I was hoping to have LL 'organize' the folders / naming during the audio book / magazine import process so as to not have to manually rename hundreds of folders.

I understand if the work involved is not worth the end result.
Thanks anyway...

**Comment by philborman** [comment]
The main problem with audiobooks and mags is the lack of metadata which can make renaming impossible. At least if we download ourselves we know what each download should contain
