### ISSUE TITLE
Issue/Question on Pseudonym authors and books

### ISSUE THREAD

**Issue by TheHatter13** [DobyTang/LazyLibrarian#955]
To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

I am using version 6897010783cbdea9bf2a35e551fc5e332c235227 on a FreeNAS system running 11.0-U2. It was installed via FreeNAS interface and updated in Web UI since. I am using bookstrap and the Goodreads api.

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1185221/debug.zip)

I am trying to add an author that is actually a pseudonym. When I search it came up fine and I was able to add them but no books showed up under the author. I do a refresh of the author and nothing shows up. I got the books manually and added them in to my folder that the library searches and moves new books to. I then did a library scan. It saw one of the 3 books that I added. I scanned again and while it does the scan the book that was previously found shows as wanted again until the scan finishes. 

The log is of a refresh of the author and then a library scan.

I am also not sure if it has something to do with an apostrophe in the title as the 2 books that don't work at all both have that.

**Comment by philborman** [comment]
Looks like we are being too strict with name matching.
We currently reject books unless goodreads says the "role" is Author, Main Author, Primary Author, Secondary Author.  This is so we can avoid listing a book where the named person is just Illustrator, Narrator, or only mentioned as Foreword by, Edited by and similar. Stops us listing so many books under the "wrong" author.
I will add Pseudonym as a valid role in the next release, maybe tomorrow now. Hadn't come across pseudonym as an entry in goodreads author table before.

**Comment by TheHatter13** [comment]
Ok. That sounds good. It's strange that one book kind of works but the others are rejected. I was thinking based off of Beauty's vs Beautys. I tried renaming them but that didn't work. Hopefully the pseudonym fixes it.

**Comment by philborman** [comment]
The goodreads page for A.N. Roquelaure lists 
The Claiming of Sleeping Beauty (Sleeping Beauty, #1)
Beauty's Punishment (Sleeping Beauty, #2)
Beauty's Release (Sleeping Beauty, #3)
Sleeping Beauty Box Set
Beauty's Kingdom (Sleeping Beauty #4)
至上の愛へ、眠り姫
All have the role as pseudonym (or Pseudonym) except the japanese one which is rejected because of language settings, so all get rejected at the moment.

The one that gets sort-of added later is because the embedded metadata in the book (or it might be the book.opf file, not sure) says the author is Anne Rice, not A.N. Roquelaure. I think you might still have problems with that one, but you can move it manually within lazylibrarian  by changing the author from Anne Rice to A.N.Roquelaure after importing it.

**Comment by TheHatter13** [comment]
Might be. I see the metadata files all have Anne Rice in them.

**Comment by TheHatter13** [comment]
I just did the update and that fixed the adding author but not adding the files. They do not show up under either name.

**Comment by TheHatter13** [comment]
It looks like it was the metadata in the book itself. Its strange though that I thought I saw in the logs that it looked for it with the metadata and then with the LL data and it still was not matched on either.

I removed the metadata file but that did not help so I found a small program just to edit the metadata and changed it with that. After that they are showing up correctly.

**Comment by philborman** [comment]
I thought that might be a problem.
You scan in the author A.N. Roquelaure and get a list of her books, then you try to match the books you have in her directory against the list you just loaded.  The books you have say they are by Anne Rice, not A.N. Roquelaure, so lazylibrarian thinks they are not the right book.  The goodreads page for Anne Rice does not mention the books you are trying to import as according to goodreads she did not write them, A.N. Roquelaure did.
Goodreads tells us A.N. Roquelaure is a pseudonym, but not who she is a pseudonym for.
Lazylibrarian does not know either, so can't correct it for you.

The "correct" way round it, as you found,  is to edit the books so they say they are by A.N. Roquelaure

There are several ways of doing it, easiest is to edit the metadata in the opf file as that's simple text. Lazylibrarian reads the book data and the metadata file, but if there is no metadata file in the download then lazylibrarian creates the metadata file from the embedded book data.

You can edit the book metadata directly (as you did), or use calibre to edit the book metadata, or force lazylibrarian to import the books under the name Anne Rice and then use lazylibrarian manual edit page to change the author.

**Comment by TheHatter13** [comment]
Thank you
