### ISSUE TITLE
Snatched Results Beyond Max Retention

### ISSUE THREAD

**Issue by rutskiuk** [DobyTang/LazyLibrarian#957]
Hi there,

I've noticed what might be a minor misconfiguration issue or possible bug when it comes to snatching downloads. I added an author and LL searched my indexers and added the downloads to SABnzbd but most of them failed because they were much older than my usenet provider allows for.

I checked the settings and can see I have set the maximum retention age:

![image](https://user-images.githubusercontent.com/25068977/28752673-f90b4d2e-751c-11e7-8a2b-c8b9a58f9cf5.png)

But when I look at the failures in my downloads on SABnzbd I see:

![image](https://user-images.githubusercontent.com/25068977/28752678-222a7eaa-751d-11e7-8990-3cbfac285a01.png)

Am I getting something wrong?

OS: Raspbian (headless)
Mode: normal
Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 270470d72ce782ef338d0da2850a02b0268c340d

**Comment by philborman** [comment]
Can you try with debug log on and see if you get any messages about "maxage"  or "retention"
We pass the parameter to sabnzbd, but not to nzbget. I think it would be more use to use it as a filter on search results, ie if the nzb is older than this date, reject it. At the moment there is no code to do this, it's only passed to sabnzbd with the nzb we want to grab. Seems a bit pointless then. Would be easy enough to add as a search results filter though.

**Comment by rutskiuk** [comment]
I do see references to maxage but not retention:

30-Jul-2017 11:23:35 - DEBUG   :: SEARCHBOOK : Request url for <a href="http://localhost:8080/api?nzbname=Jon+Ronson+-+Them+LL.%281823%29&apikey=[my SAB API]&name=https%3A%2F%2Fwww.usenet-crawler.com%2Fgetnzb%2F270ad5f03b443e94b765d6e9a5c1336b.nzb%26i%3D177664%26r%3D[my usenet-crawler API]&maxage=1100&cat=books&mode=addurl&output=json">SABnzbd</a>
30-Jul-2017 11:23:35 - DEBUG   :: SEARCHBOOK : Result text from SAB: {u'status': True, u'nzo_ids': [u'SABnzbd_nzo_ostqSb']}
30-Jul-2017 11:23:35 - INFO    :: SEARCHBOOK : Jon Ronson - Them LL.(1823) sent to SAB successfully.

**Comment by philborman** [comment]
So it seems we are sending maxage=1100 to sabnzbd
sabnzbd is not complaining about the parameter, so presumably accepts it
but still tries to download the file anyway.

Not really sure how his is meant to work. 
I think it is better if we filter out nzb results older than maxage so they don't get sent to sab at all.

**Comment by TheHatter13** [comment]
I just noticed that I am having the same issue. Sabnzbd shows a red error message about not complete so I was thinking that part of teh files were not there so I did not look much further. I just noticed that they are outside of the retention.

I thought that that parameter was used when searching the indexer but it sounds like it is not.

**Comment by philborman** [comment]
It is now ;-)
