### ISSUE TITLE
RTorrent torrents not starting

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#961]
When I send a torrent to rTorrent, it's ending up either in "Paused" or "Stopped" mode (usually stopped).   Does LL have to send a start command to rtorrent after loading?    I remember seeing somewhere that if you set the directory option, you have to start the torrent AFTER it's loaded.  Could that be causing an issue?

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report.

**Comment by philborman** [comment]
I don't have a working rtorrent server to test, but it's been reported working by others.
rtorrent is quite difficult to use as it doesn't return error codes, it doesn't work with magnets, at least not as documented when I last looked, and it needs pauses between commands. 

You are right that you have to send a start command after loading the torrent if using a directory, we do. 
The code in lazylibrarian is quite simple and is all in one file. If you want to have a play with some print statements you can see what it's doing. Might throw up some useful info.

**Comment by DarkSir23** [comment]
I'll take a look at it. I know Mylar is using a different rtorrent processor, based on the one couch potato uses. Ill do some digging?

**Comment by philborman** [comment]
That would be great thanks. Could be they are sending extra commands, debugging it is tricky though, with no error messages and always returning status code zero!

**Comment by DarkSir23** [comment]
I'm having trouble getting the problem to replicate, but I'll keep an eye out.

**Comment by philborman** [comment]
I had a quick look at mylars rtorrent module, it's fairly similar to ours, but they send the start command at the very end, we send it after the load command. Might be worth moving ours to the end, simply move lazylibrarian/rtorrent.py  line 92 down to line 100.

Also they seem to have magnets working, I could never get that to work with rtorrent, and at the time there were lots of issues raised on slashdot and other sites about rtorrents magnet capabilities. General consensus was that it just didn't work, but maybe rtorrent has been fixed now?

**Comment by philborman** [comment]
Update - seems moving the start command to the end also makes magnets work, at least on current rtorrent version from the github page.  I'm tempted to comment the magnet conversion code out and see if it works reliably - I only tried a couple of books and they both started ok. Maybe you could test further and report back?  

Move rtorrent.py line 92 to line 100
comment out (or just delete) lines 68 to 76

**Comment by DarkSir23** [comment]
Running with it now, I'll let you know how it goes

**Comment by philborman** [comment]
Can this be closed now?

**Comment by DarkSir23** [comment]
Yes, I think so
