### ISSUE TITLE
Does not start after upgrading today

### ISSUE THREAD

**Issue by TheHatter13** [DobyTang/LazyLibrarian#964]
After trying to upgrade to the latest commit today, LL does not start up. If I log in on my FreeNAS jail and try to start the service I get the error below.

38424f71d609c0c4d01d7afe0b4ddc2691460594

[LLLog.zip](https://github.com/DobyTang/LazyLibrarian/files/1195602/LLLog.zip)

root@lazylibrarian_1:/ # service lazylibrarian start                            
Starting lazylibrarian.                                                         
Traceback (most recent call last):                                              
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/LazyLibra
rian.py", line 15, in <module>                                                  
    from lazylibrarian import webStart, logger, versioncheck, dbupgrade         
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibra
rian/webStart.py", line 20, in <module>                                         
    import requests                                                             
ImportError: No module named requests                                           
/usr/local/etc/rc.d/lazylibrarian: WARNING: failed to start lazylibrarian       
root@lazylibrarian_1:/ #

**Comment by philborman** [comment]
Sorry about that, the requests module isn't installed as standard. 
We don't need it in that file anyway, so  I have just pushed a fix with that line removed.
It was added for some other stuff I was working on related to user accounts, but that's not ready yet.

**Comment by TheHatter13** [comment]
How do you update manually? I am used to the web ui.

**Comment by philborman** [comment]
It's a little more complicated as you are in a freenas jail with a custom python version. 

log into your freenas jail and run the following command, all on one line (cut and paste if you can to save typing). First bit is your custom python version, then the LazyLibrarian startup file, then the update command, then the startup parameters for the new version 

`/usr/pbi/lazylibrarian-amd64/bin/python2.7   /usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/LazyLibrarian.py   --update   --datadir=/var/db/lazylibrarian   -d   -p   /var/run/lazylibrarian/lazylibrarian.pid   --nolaunch`

**Comment by TheHatter13** [comment]
That did not work. It seems like it hits that module first even when trying to upgrade.

root@lazylibrarian_1:/ # /usr/pbi/lazylibrarian-amd64/bin/python2.7 /usr/pbi/laz
ylibrarian-amd64/share/lazylibrarian/LazyLibrarian/LazyLibrarian.py --update --d
atadir=/var/db/lazylibrarian -d -p /var/run/lazylibrarian/lazylibrarian.pid --no
launch                                                                          
Traceback (most recent call last):                                              
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/LazyLibra
rian.py", line 15, in <module>                                                  
    from lazylibrarian import webStart, logger, versioncheck, dbupgrade         
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibra
rian/webStart.py", line 20, in <module>                                         
    import requests                                                             
ImportError: No module named requests                                           
root@lazylibrarian_1:/ #                                                        
root@lazylibrarian_1:/ #

**Comment by philborman** [comment]
Right, might have to hand edit that module first.
"/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/webStart.py", line 20,
Just put a hash symbol   #  at the start of the line and try again.

**Comment by TheHatter13** [comment]
That did not allow for me to manually update. It gave me this.

INFO LazyLibrarian is updating...                                               
INFO (update) Downloading update from: https://github.com/dobytang/lazylibrarian
/tarball/master                                                                 
root@lazylibrarian_1:/ # INFO (update) Extracting file/usr/pbi/lazylibrarian-amd
64/share/lazylibrarian/LazyLibrarian/master                                     
INFO (update) Deleting file/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/Lazy
Librarian/master                                                                
WARN LazyLibrarian failed to update: 'LATEST_VERSION'. Restarting.              
INFO LazyLibrarian is restarting ...                                            
DEBUG Restarting LazyLibrarian with ['/usr/pbi/lazylibrarian-amd64/bin/python2.7
', '/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/LazyLibrarian
.py', '--datadir=/var/db/lazylibrarian', '-d', '-p', '/var/run/lazylibrarian/laz
ylibrarian.pid', '--nolaunch']                                                  
INFO LazyLibrarian is exiting                                                   
Lazylibrarian is starting up...

But since I saw no error after the service starting, I did the update through the web UI and that updated.

**Comment by philborman** [comment]
Yes, we forced it into downloading a new copy that was essentially the same as your hand edited copy, so the upgrade code thought the upgrade wasn't needed, but if we hadn't upgraded your checksum (version number) would be wrong, which might cause issues with future updates.
