### ISSUE TITLE
Magazine Covers

### ISSUE THREAD

**Issue by peddlerguy** [DobyTang/LazyLibrarian#967]
I installed ImageMagick but I can't figure out how to get it to create the magazine covers.  I tried leaving the field blank, but that didn't work - so I put in the full path to convert (the only convert file I could find has an html extension?) but that didn't work either - I also tried just entering ImageMagick

I run windows 8 so I used the ImageMagick-7.0.6-5-Q8-x64-dll.exe install file

Current Version: e64102d666eb2149505e130525d806a4f441816b : Latest Version: e64102d666eb2149505e130525d806a4f441816b

**Comment by philborman** [comment]
Sounds like your imagemagick installation is not complete. Ghostscript seems to be a better solution for most people, and creates smaller image files too. Download it from link below, should just work out of the box,  usually no extra lazylibrarian config needed.

https://www.ghostscript.com/download/gsdnld.html

**Comment by peddlerguy** [comment]
am I supposed to put anything in the Cover Creation Program text box?

Right now I still have no magazine covers - I installed ghost script - no covers; then uninstalled imagemagick, leaving only Ghostscript - still no covers; then I reinstalled ImageMagick AND Ghostscript - and yet there's no covers

What am I missing?

**Comment by philborman** [comment]
No, nothing in cover creation program, there are a few things it could be...
1. Ghostscript should be in your system path. We look for gswin64c.exe or gswin32c.exe in your system path using "which" command, or if not found, we try in your lazylibrarian directory. 
1. LazyLibrarian creates covers as it loads the magazines into the library, so you may need to run libraryscan from the magazines page to refresh it. 
2. You need "show magazine covers" enabled in config
3. If you are on the bookstrap interface with column toggles enabled, you might need to click the cover toggle.

I would try turning debug logging on and running libraryscan from the magazine page. Should show what's going on.

**Comment by peddlerguy** [comment]
the ghostscript exe is in this directory (I let it install with the defaults):

C:\Program Files\gs\gs9.21\bin

I ran the library scan, show covers is enabled, and the column is enabled - all I see is black boxes with question marks - the directory for the black boxes is my port/cache/ etc

I checked the log after running a library scan and the entries all say that a cover exists

I also tried putting the path in the cover creation program box, but still no covers

**Comment by brinkdogg** [comment]
I'm getting the following error 
MAGAZINE_SCAN : Pattern match failed for "blahblahblahmagazine title" 

Is there a special format I need to place Magazine?

**Comment by philborman** [comment]
Pattern match failed is because we need the magazine to be named following the folder and issue name patterns in config  - this is the pattern lazylibrarian will use itself, if you add your own mags you need to follow the same pattern. The reason for this is that most magazines don't have any useful metadata embedded in them giving the title and issue number/date so we have to work it out from the folder and filename.  The default is folder _Magazines/$Title/$IssueDate, the default filename is $IssueDate - $Title  so you end up with something like "_Magazines/The Magpi/July 2017/July 2017 - The Magpi.pdf"

**Comment by brinkdogg** [comment]
Ok got it!!! Thanks!

**Comment by philborman** [comment]
@peddlerguy 
It doesn't matter where ghostscript is, as long as we can find it. Can you open a windows command prompt and try  "which gswin64c"
Hopefully it will find it, or use "which gswin32c"  if you are using the 32bit version.

If we think there is already a cover there, we won't create one, so can you try deleting all the old covers and running librarysync again.  You can delete them from a file manager, or you can force lazylibrarian to recreate the covers using the api. It's not a commonly needed function so is only in the api.

If you want to go the api route, enable api in config, then in your browser go to...
http://localhost:5299/api?apikey=yourapikey&cmd=createMagCovers&refresh&wait

**Comment by brinkdogg** [comment]
Ok one more dumb ass question - under Cover creation what is the syntax for ImageMagick? Do I need to add the complete path I.E. /usr/bin/imagemagick etc?

**Comment by peddlerguy** [comment]
I deleted the existing covers and ran library scan - that caused firefox to shut down

got LL going again, so I tried the api route - it recreated the same black boxes

and when I opened the command prompt to enter the which command, it said that "which" isn't recognized as a valid command

**Comment by philborman** [comment]
@brinkdogg 
It's easier to use ghostscript than imagemagick, unless you already have the python interfaces to imagemagick installed.

Ghostscript is just install and go, no config needed, as long as ghostscript is in your system path

**Comment by philborman** [comment]
@peddlerguy 
sorry, my bad.  "which gswin64c"  is the linux/mac command.  Windows needs  "where gswin64c"
but if the api command just recreated the empty images it looks like we can't find it. Did you put debug log on, if so you should see messages saying it tried to find gswin64c and failed.

**Comment by peddlerguy** [comment]
yep, it can't find it - the where command doesn't find it either

how can that be?  it's in the program directory - I even tried installing the 32bit as well as the 64bit - that's 2 chances to find it, and it doesn't!

**Comment by philborman** [comment]
It needs to be in your system path, or it won't be found. Some programs add themselves into the path automatically, some don't. Some give you an option when they install, some don't

In your downloaded ghostscript I think there should be a gswin64c.exe  and a gswin64.exe
If so, copy the gswin64c to your top level lazylibrarian directory (the one with LazyLibrarian.py in it).
I think we should be able to pick it up as a private copy. Then run the api command again and see what debug log says.

**Comment by peddlerguy** [comment]
still nothing

I found instructions for adding the exe to my system path - so now the "where" works, the log doesn't say it can't find gswin64c, but there's still the black boxes

so I tried your suggestion by copying the exe to the LL directory - still black boxes

yet the log says the covers are found

has anyone been able to get the covers?

**Comment by philborman** [comment]
If the log says the covers are found then lazylibrarian won't try to create them again, except for the api command with "&refresh"   If you are getting a message saying "Cover for xyz exists"  then lazylibrarian won't look for gswin64c as it doesn't need it.
Do you get a message in the log saying "Creating covers for xxx issues"
or does it say "Checking covers for xxx issues"
Maybe post a debug log showing the api command running?

**Comment by peddlerguy** [comment]
oh wait - it created 1 cover - it 'said' it created 27, but it only created 1

I have a magazine with a cover - yay!

the log says "creating" - here's a portion of the log:

04-Aug-2017 15:45:21 - INFO    :: API : Received API command: createMagCovers {'refresh': u'', 'wait': u''}
04-Aug-2017 15:45:21 - INFO    :: API : Creating covers for 27 issues
04-Aug-2017 15:45:21 - DEBUG   :: API : Creating cover for C:\lazybooks\_Magazines/canadian living/2017-05-01\2017-05-01 - canadian living.pdf
04-Aug-2017 15:45:21 - DEBUG   :: API : Found local gswin64c [C:\LazyLibrarian\gswin64c.exe] version 9.21

04-Aug-2017 15:45:22 - DEBUG   :: API : Created cover for C:\lazybooks\_Magazines/canadian living/2017-05-01\2017-05-01 - canadian living.pdf using local gswin64c version 9.21

04-Aug-2017 15:45:22 - DEBUG   :: API : Creating cover for C:\lazybooks\_Magazines/canadian living/2017-04-01\2017-04-01 - canadian living.pdf
04-Aug-2017 15:45:22 - DEBUG   :: API : Found local gswin64c [C:\LazyLibrarian\gswin64c.exe] version 9.21

04-Aug-2017 15:45:22 - DEBUG   :: API : Created cover for C:\lazybooks\_Magazines/canadian living/2017-04-01\2017-04-01 - canadian living.pdf using local gswin64c version 9.21

04-Aug-2017 15:45:22 - DEBUG   :: API : Creating cover for C:\lazybooks\_Magazines/food network/2017-05-01\2017-05-01 - food network.pdf
04-Aug-2017 15:45:22 - DEBUG   :: API : Found local gswin64c [C:\LazyLibrarian\gswin64c.exe] version 9.21

04-Aug-2017 15:45:23 - DEBUG   :: API : Created cover for C:\lazybooks\_Magazines/food network/2017-05-01\2017-05-01 - food network.pdf using local gswin64c version 9.21

***

and it just continues like that - creating cover/found gswin/created cover

**Comment by philborman** [comment]
So it thinks the covers were created. Are the covers there, should be next to each issue file with the same name as the pdf, but a jpg extension.  If the covers are all there and look ok in a file manager, I guess it could be a problem with the cache?  Try deleting all the images in cache/magazine/

**Comment by peddlerguy** [comment]
success!  I don't know what finally triggered it, but I deleted the cache again, and I have covers!  They look SO much nicer than the black squares!

thank you for all your help!

**Comment by philborman** [comment]
No problem
