### ISSUE TITLE
Problem with Calibre directory creation when author name ends with Jr.

### ISSUE THREAD

**Issue by Hydro-guy** [DobyTang/LazyLibrarian#968]
Another problem with authors name ending with Jr.  – postprocessor fails.  downloaded one new book and got a failure - log below.

LL is updated to Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: e64102d666eb2149505e130525d806a4f441816b : Latest Version: e64102d666eb2149505e130525d806a4f441816b.  Win10 default goodreads

When I checked I found two L.E. Modesitt subdirectories existing in the calibre library 
D:\XX\Documents\Ebooks\Calibre Library\Calibre Library - XXX\L.E. Modesitt, Jr_  (apparently created in Feb on initial testing of LL ) and
D:\XX\Documents\Ebooks\Calibre Library\Calibre Library - XXX\L.E. Modesitt Jr_ ( probably created in June on postprocessing one book)

However error is “Failed to locate calibre author dir [D:\XX\Documents\Ebooks\Calibre Library\Calibre Library - XXX\L.E. Modesitt Jr.\]”

Removed modesitt from calibre db (calibre deleted both directories) and redownloaded via LL – got same error but snatched files are copied to a newly created calibre library anyway but name is wrong – seems to be looking for a “.” and not an “_”
Found post processed books in D:\XX\Documents\Ebooks\Calibre Library\Calibre Library - XXX\L.E. Modesitt Jr_ but obviously LL didn’t clean up.

John

05-Aug-2017 11:33:19 - DEBUG :: POSTPROCESS : Checking 1 file in D:\XX\Documents\Ebooks\Kobo\LazyLibrarian
05-Aug-2017 11:33:19 - DEBUG :: POSTPROCESS : Found 1 file marked "Snatched"
05-Aug-2017 11:33:19 - DEBUG :: POSTPROCESS : L E  Modesitt Jr  - Assassins Price LL.(31702756) was sent to NZBGET
05-Aug-2017 11:33:19 - INFO :: POSTPROCESS : Looking for eBook L E  Modesitt Jr  - Assassins Price LL.(31702756) in D:\XX\Documents\Ebooks\Kobo\LazyLibrarian
05-Aug-2017 11:33:19 - DEBUG :: POSTPROCESS : Found folder (100%) [D:\XX\Documents\Ebooks\Kobo\LazyLibrarian\L E  Modesitt Jr  - Assassins Price LL.(31702756)] for eBook L E  Modesitt Jr  - Assassins Price
05-Aug-2017 11:33:19 - DEBUG :: POSTPROCESS : Found match (100%): D:\XX\Documents\Ebooks\Kobo\LazyLibrarian\L E  Modesitt Jr  - Assassins Price LL.(31702756) for eBook L E  Modesitt Jr  - Assassins Price LL.(31702756)
05-Aug-2017 11:33:19 - DEBUG :: POSTPROCESS : Processing eBook 31702756
05-Aug-2017 11:33:19 - DEBUG :: POSTPROCESS : Importing Assassins Price - L.E. Modesitt Jr. into calibre library
05-Aug-2017 11:33:19 - DEBUG :: POSTPROCESS : [u'calibredb', 'add', '-1', u'--with-library=D:\\XX\\Documents\\Ebooks\\Calibre Library\\Calibre Library - XXX', u'D:\\XX\\Documents\\Ebooks\\Kobo\\LazyLibrarian\\L E  Modesitt Jr  - Assassins Price LL.(31702756)']
05-Aug-2017 11:33:22 - DEBUG :: POSTPROCESS : calibredb reports: Added book ids: 964

05-Aug-2017 11:33:22 - DEBUG :: POSTPROCESS : Calibre ID: 964
05-Aug-2017 11:33:22 - DEBUG :: POSTPROCESS : Saved metadata to: D:\XX\Documents\Ebooks\Kobo\LazyLibrarian\L E  Modesitt Jr  - Assassins Price LL.(31702756)\Assassins Price - L.E. Modesitt Jr..opf
05-Aug-2017 11:33:22 - DEBUG :: POSTPROCESS : [u'calibredb', 'set_metadata', '--with-library', u'D:\\XX\\Documents\\Ebooks\\Calibre Library\\Calibre Library - XXX', '964', u'D:\\XX\\Documents\\Ebooks\\Kobo\\LazyLibrarian\\L E  Modesitt Jr  - Assassins Price LL.(31702756)\\Assassins Price - L.E. Modesitt Jr..opf']
05-Aug-2017 11:33:24 - DEBUG :: POSTPROCESS : calibredb set opf reports: Title               : Assassins Price
Title sort          : Assassins Price
Author(s)           : L.E. Modesitt Jr.
Publisher           : Tor Books
Languages           : eng
Timestamp           : 2017-08-05T15:33:22+00:00
Published           : 2017-08-15T04:00:00+00:00
Identifiers         : isbn:0765390477, goodreads:31702756
Comments            : Assassin's Price is the eleventh book in the bestselling epic fantasy series the Imager Portfolio by L. E. Modesitt Jr. and the third book in a story arc which began with Madness in Solidar and Treachery's Tools.Six years have passed since the failed uprising of the High Holders and the man behind the conspiracy is where the rex and Maitre Alastar can keep an eye on him.Charyn has come of age and desperately wants to learn more so he can become an effective rex after his father but he s kept at a distance by the rex. So Charyn sets out to educate himself circumspectly.When Jarolian privateers disrupt Solidar s shipping someone attempts to kill Charyn s younger brother as an act of protest. Threatening notes following in the wake of acts of violence against the rex and his family demanding action build more ships or expect someone to die.The Imager Portfolio#1 Imager / #2 Imager s Challenge / #3 Imager s Intrigue / #4 Scholar / #5 Princeps / #6 Imager s Battalion / #7 Antiagon Fire / #8 Rex Regis / #9 Madness in Solidar / #10 Treachery s Tools / #11 Assassin s Price (forthcoming)Other series by this author: The Saga of RecluceThe Corean ChroniclesThe Spellsong CycleThe Ghost BooksThe Ecolitan Matter"

05-Aug-2017 11:33:24 - ERROR :: POSTPROCESS : Postprocessing for Assassins Price - L.E. Modesitt Jr. has failed: Failed to locate calibre author dir [D:\XX\Documents\Ebooks\Calibre Library\Calibre Library - XXX\L.E. Modesitt Jr.\]
05-Aug-2017 11:33:24 - WARNING :: POSTPROCESS : Residual files remain in D:\XX\Documents\Ebooks\Kobo\LazyLibrarian\L E  Modesitt Jr  - Assassins Price LL.(31702756).fail
05-Aug-2017 11:33:24 - INFO :: POSTPROCESS : 0 books/mags processed.
05-Aug-2017 11:33:24 - INFO :: POSTPROCESS : Nothing marked as snatched. Stopping postprocessor.
05-Aug-2017 11:33:24 - DEBUG :: POSTPROCESS : Stop processDir job

© 2017 GitHub, Inc. Terms Privacy Security Status HelpTo help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report.

**Comment by Hydro-guy** [comment]
font formatting seems to have removed the _ from the error msg.  when the post processing fails it still created the calibre subdirectory D:\XX\Documents\Ebooks\Calibre Library\Calibre Library - XXX\L.E. Modesitt Jr_ but is looking for one ending with Jr.

**Comment by philborman** [comment]
Calibre created the directory ending with Jr_  as it does not like diretories ending with a dot. I think it's there because of a windows filename restriction. 

Just added a fix, will upload shortly.

**Comment by Hydro-guy** [comment]
Many thanks – thought it would be easy for you to stomp on.

 

John

**Comment by Hydro-guy** [comment]
After upgrading to new version still an error in postprocessing cleanup of files.  

 

Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 8bc4bedf8d70146e891b57cef7fc05008be397bb : Latest Version: 8bc4bedf8d70146e891b57cef7fc05008be397bb

 

Does create a directory D:\John\Documents\Ebooks\Calibre Library\Calibre Library - Janie\L.E. Modesitt Jr_ and transfers epub to it but cleanup of download directory ends up with .fail 

 

John

 

06-Aug-2017 11:34:58 - DEBUG :: SEARCHBOOK : NZB sent to NZBget successfully

06-Aug-2017 11:34:58 - DEBUG :: SEARCHBOOK : Nzbfile has been downloaded from 

06-Aug-2017 11:34:58 - INFO :: SEARCHBOOK : Downloading eBook L E  Modesitt Jr  - Cyadors Heirs LL.(18490587) from http://api.nzb.su

06-Aug-2017 11:34:58 - DEBUG :: SEARCHBOOK : Start processDir job, already scheduled

06-Aug-2017 11:34:58 - INFO :: SEARCHBOOK : Search for Wanted items complete, found 1 book

06-Aug-2017 11:36:01 - DEBUG :: POSTPROCESS : Checking 1 file in D:\XX\Documents\Ebooks\Kobo\LazyLibrarian

06-Aug-2017 11:36:01 - DEBUG :: POSTPROCESS : Found 1 file marked "Snatched"

06-Aug-2017 11:36:01 - DEBUG :: POSTPROCESS : L E  Modesitt Jr  - Cyadors Heirs LL.(18490587) was sent to NZBGET

06-Aug-2017 11:36:01 - INFO :: POSTPROCESS : Looking for eBook L E  Modesitt Jr  - Cyadors Heirs LL.(18490587) in D:\XX\Documents\Ebooks\Kobo\LazyLibrarian

06-Aug-2017 11:36:01 - DEBUG :: POSTPROCESS : Found folder (100%) [D:\XX\Documents\Ebooks\Kobo\LazyLibrarian\L E  Modesitt Jr  - Cyadors Heirs LL.(18490587)] for eBook L E  Modesitt Jr  - Cyadors Heirs

06-Aug-2017 11:36:01 - DEBUG :: POSTPROCESS : Found match (100%): D:\XX\Documents\Ebooks\Kobo\LazyLibrarian\L E  Modesitt Jr  - Cyadors Heirs LL.(18490587) for eBook L E  Modesitt Jr  - Cyadors Heirs LL.(18490587)

06-Aug-2017 11:36:01 - DEBUG :: POSTPROCESS : Processing eBook 18490587

06-Aug-2017 11:36:01 - DEBUG :: POSTPROCESS : Importing Cyador's Heirs - L.E. Modesitt Jr. into calibre library

06-Aug-2017 11:36:01 - DEBUG :: POSTPROCESS : [u'calibredb', 'add', '-1', u'--with-library=D:\\XX\\Documents\\Ebooks\\Calibre Library\\Calibre Library - XXX', u'D:\\XX\\Documents\\Ebooks\\Kobo\\LazyLibrarian\\L E  Modesitt Jr  - Cyadors Heirs LL.(18490587)']

06-Aug-2017 11:36:03 - DEBUG :: POSTPROCESS : calibredb reports: Added book ids: 975

 

06-Aug-2017 11:36:03 - DEBUG :: POSTPROCESS : Calibre ID: 975

06-Aug-2017 11:36:03 - DEBUG :: POSTPROCESS : Saved metadata to: D:\XX\Documents\Ebooks\Kobo\LazyLibrarian\L E  Modesitt Jr  - Cyadors Heirs LL.(18490587)\Cyador's Heirs - L.E. Modesitt Jr..opf

06-Aug-2017 11:36:03 - DEBUG :: POSTPROCESS : [u'calibredb', 'set_metadata', '--with-library', u'D:\\XX\\Documents\\Ebooks\\Calibre Library\\Calibre Library - XXX', '975', u"D:\\XX\\Documents\\Ebooks\\Kobo\\LazyLibrarian\\L E  Modesitt Jr  - Cyadors Heirs LL.(18490587)\\Cyador's Heirs - L.E. Modesitt Jr..opf"]

06-Aug-2017 11:36:04 - DEBUG :: POSTPROCESS : calibredb set opf reports: Title               : Cyador's Heirs

Title sort          : Cyador's Heirs

Author(s)           : L.E. Modesitt Jr.

Publisher           : Tor Books

Languages           : eng

Timestamp           : 2017-08-06T15:36:02+00:00

Published           : 2014-08-15T04:00:00+00:00

Identifiers         : isbn:0765374773, goodreads:18490587

 

06-Aug-2017 11:36:04 - ERROR :: POSTPROCESS : Postprocessing for Cyador's Heirs - L.E. Modesitt Jr. has failed: Failed to locate calibre author dir [D:\XX\Documents\Ebooks\Calibre Library\Calibre Library - XXX\L.E. Modesitt Jr.\]

06-Aug-2017 11:36:04 - WARNING :: POSTPROCESS : Residual files remain in D:\XX\Documents\Ebooks\Kobo\LazyLibrarian\L E  Modesitt Jr  - Cyadors Heirs LL.(18490587).fail

06-Aug-2017 11:36:04 - INFO :: POSTPROCESS : 0 books/mags processed.

06-Aug-2017 11:36:04 - INFO :: POSTPROCESS : Nothing marked as snatched. Stopping postprocessor.

06-Aug-2017 11:36:04 - DEBUG :: POSTPROCESS : Stop processDir job

**Comment by philborman** [comment]
Failed to locate calibre author dir [D:\XX\Documents\Ebooks\Calibre Library\Calibre Library - XXX\L.E. Modesitt Jr.\]    it doesn't end in '.'  it ends in '.\'

Should be fixed now.

**Comment by Hydro-guy** [comment]
Worked fine.  Thank you.

 

Have you considered populating the Calibre “Series” database field when postprocessing a file?

 

John

**Comment by philborman** [comment]
There are problems with calibre series, in that it only stores one per book, and it gets it's info from different sources to us so they don't always match up.
 eg  
Terry Pratchett - Wyrd Sisters
is Discworld book 6
and also
Discworld Witches book 2
Calibre can only store one of them, which do we choose?
 
Agatha Christie -  The Adventure of the Christmas Pudding
is Poirot 32.5 according to Goodreads, but Poirot 33 according to Calibre

**Comment by Hydro-guy** [comment]
Usually I find that Calibre is sorta useless when it comes to series numbering from downloaded metadata and that I have to add or correct numbering anyway.  Becomes a personal choice on which Series name or number is correct.  

If I look at Goodreads for the Discworld series they seemed to have a main and subseries listing – giving Discworld as the main and witches as the sub.

That being so – why not default to populate Calibre with the Goodreads main series name and number initially on postprocessing and if there is a mismatch on subsequent calibre library scans assume that this is a user generated change.  Change series name and numbering in LL to mirror Calibre (colour change to text and popup with Goodreads name/series number??) 

 

Just a thought and could just as easily only do the initial main Calibre populating and ignore any subsequent user changes to Calibre.

 

John

**Comment by philborman** [comment]
I will have a look, but Goodreads only gives us series name and number in the metadata pages via the goodreads api, not the full web page info. I'm fairly sure we don't get anything about sub-series

**Comment by Hydro-guy** [comment]
Thank you.  I didn’t know how the api results would be formatted – but looking at how LL displayed the Discworld series and how the Goodreads web version of the Discworld series was reported it looked like the api data had the main being reported first and the sub was reported second.

 

This isn’t a big thing to worry about – just a nice to have if it could work.

 

Much appreciated for all the work you have put into this!!

 

John

**Comment by philborman** [comment]
Latest version now sends first series details to calibre in the opf file. 
Tried it with a few books here that are part of multiple series and it seems OK.

**Comment by Hydro-guy** [comment]
Tried it twice on Modesitt downloading an single book (Imager Portfolio series) at a time – with book 8 and book 6.  The series name was correct in calibre but the series number seemed to default to #1 each time even though correct in LL.  Renamed 8 but left 6 named as #1.

 

Downloaded 3 from (Chorean series) at one time – Calibre ignored the missing #1 in series.  2,3,4 numbered correctly.

 

Downloaded  #7 in (imager portfolio) series – calibre named it #1 again. Now there are two with same series number. Hmm bit strange – Don’t think calibre would have named them the same – that points to postprocessor.

 

Downloaded #4 in (spellsinger series) calibre named it #4. No others downloaded in series – just this one.

 

Strange – problem seems to be only with Imager Portfolio numbering – but looks normal in LL??

 

Then wondered if Calibre was changing the numbering because of the large gap in series numbering – didn’t have any less than #6 and the two #1’s.

 

Tried #4 in Imager Portfolio – Calibre numbered it correctly.

 

Then fixed series naming metada in Calibre – renamed the two books incorrectly named #1 to their correct series#.

 

Downloaded #2 in Imager Portfolio – worked correctly.

 

Downloaded #3 in Imager Portfolio – named it #1. Huh.

 

Then realized that there was text on the second line of the series number in LL “Book 3”.  Similiarly – all the other failures.  Calibre seems to delete text and default to 1.

 

Filter? Series is unlikely to exceed 50 in numbering – perhaps discard everything except numbers inside of a band >0<50 or test for text “Five” and convert to numeric.  Null case = 1

 

Or – if non numeric concantenate and pass as series name – would be easy to edit.

 

Otherwise – worked well.

 

Many thanks

 

John

**Comment by philborman** [comment]
Makes sense, and stripping the text / validating the numbers should be easy enough to add. 
The text-to-numeric conversion could be more of a problem, and I think it might be better to only pass series/number if we have both, so rather than default to number 1, don't pass any series info.

**Comment by Hydro-guy** [comment]
When I was updating Calibre manually for series info I found myself going to LL more for the series number (less likely for series name if I already had several other books).  Was doing this because I maintain LL for my wife’s authors and I have no knowledge of the romance/historical fantasy genres/authors that she reads.  However – when she gets interested in an author she wants to read them in order.

 

Passing the number info as text into the series name field if it failed validation testing would make this process easier – I’d be able to skip the refer to LL or internet searches and manually update info in Calibre.

 

The downside of course is that it isn’t as clean as not passing anything and – not knowing the size of the series name field in the Calibre db or whether it truncates text if too long for field – one might introduce other errors into process.

 

I’d be happy either way – I typically only download a series at a time and mass editing series name in Calibre is fairly easy.

 

John

**Comment by sscraggles** [comment]
> When I was updating Calibre manually for series info I found myself going to LL more for the series number (less likely for series name if I already had several other books). 

@Hydro-guy Maybe worth using the [Goodreads](https://www.mobileread.com/forums/showthread.php?t=130638) metadata plugin for Calibre?  I switched to it and find it good enough that I've disabled other metadata sources.
