### ISSUE TITLE
Authors Directory created with permission 700 (not 755 as config.ini suggest)

### ISSUE THREAD

**Issue by Xhelliom** [DobyTang/LazyLibrarian#972]
### LazyLibrarian version number (at the bottom of config page)
 f2de3c16aa2b4417a4a6097868f301ff64a3ee92
### Operating system used (windows, mac, linux, NAS type)
Linux : Alpine OS
### Interface in use (default, bookstrap)
Bookstrap (slate)
### Which api (Goodreads, GoogleBooks, both)
Goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
Git
### Relevant debug log with api keys and any passwords redacted
No information about folder permission or error about directory creation.

Hello,

I have an issue when the post processing is creating the folder for the author : 
In my configuration, i have under eBook/AudioBook Foldername Pattern:
 **$Author/$Title**

So it's creating : 
- The folder "Authors" with permission 700 (not readeable by group or public)
- The folder "Title" with permission 755 (which is good => Define in config.ini)

Any Idea :/ ?
Thank you in advance
Thanks for that amazing job.

**Comment by philborman** [comment]
We make the directories in one step using os.makedirs which is supposed to default to 777 but seemingly doesn't always.  It should create the folder you ask for, and any intermediate folders as well.
Then we "downgrade" the title folder to 755 with os.chmod (and set files to 644)
Maybe we don't have permission to create the author folder as 755 ? Might depend on the settings of it's parent folder? 

Maybe we can create the folder structure in stages, author first, set perm, create title folder, set perm.
Or maybe we can send an extra parameter to os.makedirs to set 755 as default (rather than 777), but I don't know if that would help.

**Comment by Xhelliom** [comment]
Thank you for the fast answer.
As you said, i'll try first to change the parent directory to 777, was 775.
For a little bit more explanation, i move (process) books from linux alpineOS folder (where LL is installed) to an NFS (Nas4free NAS). The NFS is mount read/write with root.
I don't think that the NFS is the issue, but a prefer to tell.

I also did a test to do "mkdir - p author/book" into NFS (parent dir is 777 now) from alpineOS and the result is a directory with 755 (author and book). 

Maybe to create the folder structure in stages could be the trick, i don't know, but i feel that my issue might be not here ...

Well, i'll try some more test and i'll keep in touch.
Thanks for the help

**Comment by philborman** [comment]
Can you try running this short program for me, it will let me know which method(s) work. Change the "base" to point to your book folder.  It creates some directories and  then deletes them. 
Method 1 is the way we currently do it (just to make sure it still fails)
Method 2 is an easy solution if it works
Method 3 is more complicated
Thanks.

```
#!/usr/bin/python
#
import os
import shutil

base = '/home/phil/Test_Library'

authorfolder = os.path.join(base, "dummy authorname")
bookfolder = os.path.join(authorfolder, "dummy bookname")
# method 1, current style
os.makedirs(bookfolder)
print "Method 1, Author folder: ", oct(os.stat(authorfolder)[0])
print "Method 1, Book   folder: ", oct(os.stat(bookfolder)[0])
shutil.rmtree(authorfolder)
#
# method 2, pass permission to makedirs
os.makedirs(bookfolder, 0o755)
print "Method 2, Author folder: ", oct(os.stat(authorfolder)[0])
print "Method 2, Book   folder: ", oct(os.stat(bookfolder)[0])
shutil.rmtree(authorfolder)
#
# method 3, force permission separately
os.makedirs(bookfolder)
os.chmod(authorfolder, 0o755)
os.chmod(bookfolder, 0o755)
print "Method 3, Author folder: ", oct(os.stat(authorfolder)[0])
print "Method 3, Book   folder: ", oct(os.stat(bookfolder)[0])
shutil.rmtree(authorfolder)
```

The output on mine is...
Method 1, Author folder:  040755
Method 1, Book   folder:  040755
Method 2, Author folder:  040755
Method 2, Book   folder:  040755
Method 3, Author folder:  040755
Method 3, Book   folder:  040755

I hope yours will be different.

**Comment by Xhelliom** [comment]
Hello philborman,
Thank you for that short program but il got the same result as you : 

Method 1, Author folder:  040755
Method 1, Book   folder:  040755
Method 2, Author folder:  040755
Method 2, Book   folder:  040755
Method 3, Author folder:  040755
Method 3, Book   folder:  040755

I only changed : 
base = '/home/phil/Test_Library'
to
base = '/mnt/nfs/partage/medias/livres' (its my nfs share where by books are stored)

i've start downloading a new author from LL, with new perm on parent dir, i'll tell you if it works.

**Comment by Xhelliom** [comment]
So, still not working with new parent's perms.
I guess it's an isolated issue on my server / maybe an AlpineOS / NFS issue ...
I suggest, we can close the topic, I don't want to bother you with that.
I have a workaround, i'll do a cron job that correct the permissions of my folder.

Thank you very much for your help. If something change or i found the issue, I'll told you.

Continue the great job :)

**Comment by philborman** [comment]
Ok thanks.
