### ISSUE TITLE
Req: when delete in Lazylibrarian, also remove from calibredb

### ISSUE THREAD

**Issue by sscraggles** [DobyTang/LazyLibrarian#974]
Deleting books in LazyLibrarian currently leaves them in Calibre and it seems there's no easy way to find missing files in Calibre short of moving the library.
Is it even feasible to have calibredb remove the files?  I see it needs an id number which you may not have?

**Comment by philborman** [comment]
It's feasible, we can ask calibre for the id. If we uploaded the book to calibre we know it anyway, as it tells us the id in it's reply. Also we can get the id from the calibre book folder name (it's the number in braces on the end).
I think calibredb has a delete command. Would have to check.

**Comment by philborman** [comment]
ok, that seems to be working, though I can't test the url access part myself.

**Comment by sscraggles** [comment]
Great, I can see that's working when the server isn't configured.
