### ISSUE TITLE
req: create meta data with author file-as

### ISSUE THREAD

**Issue by sscraggles** [DobyTang/LazyLibrarian#981]
Current meta data creation doesn't include author-sort, which leaves it labelled as Unknown within Calibre.

The result of this is when I subsequently use calibre to copy files onto my e-reader, they are stored in a single directory called Unknown.

**Comment by philborman** [comment]
Should be easy enough to add, just need to see what calibre does.

**Comment by philborman** [comment]
This isn't as simple as I hoped. The "file-as" part needs the author name in "surname, firstname" format.
Easy if there is only two words, "Agatha Christie" -> "Christie, Agatha"
but what do you do with "Phyllis Pellman Good", is it "Good, Phyllis Pellman"  or "Pellman Good, Phyllis"
as we would need to do it the same way as Calibre. 

Maybe we cheat and only do "file-as" when it's easy. 

I will have a dig around in calibre and see if I can find their routine as an example.

**Comment by sscraggles** [comment]
Calibre takes the last word as surname.

eg.
"Thich Nhat Hanh" becomes "Hanh, Thich Nhat"
"John le Carré" becomes "Carré, John le"
"Richard J. Herrnstein" becomes "Herrnstein, Richard J."
"G. A. Borgese" becomes "Borgese, G. A."

**Comment by philborman** [comment]
Hmmm, not quite that simple.
J. Michael Springmann Jr.   should end up as   Springmann Jr., J. Michael
(actually, not sure if we should drop the dot on the end of Jr. Looks wrong as ., )

Took 6 lines of code, not 4 ;-(

**Comment by sscraggles** [comment]
Theres probably a bunch of those you *could* cater for..

author_name_suffixes = ('Jr', 'Sr', 'Inc', 'Ph.D', 'Phd', 'MD', 'M.D', 'I', 'II', 'III', 'IV', 'Junior', 'Senior')
author_name_copywords = ('Corporation', 'Company', 'Co.', 'Agency', 'Council', 'Committee', 'Inc.', 'Institute', 'Society', 'Club', 'Team')

found at https://manual.calibre-ebook.com/customize.html

**Comment by philborman** [comment]
We currently just do Jr Sr Jnr Snr Phd, but the string is configable. We strip the dots and lowercase before comparison so Phd matches Ph.D and Phd, Jr matches Jr. etc

Just pushed the new version with "file-as" surname, fornames

**Comment by sscraggles** [comment]
Just tested, "file-as" is now set though is missing the comma..

```
14-Aug-2017 21:11:31 - DEBUG   :: POSTPROCESS : [u'/usr/bin/calibredb', 'set_metadata', '--with-library', u'http://localhost:9000', '11', u'/home/scraggles/Downloads/LazyLibrarian/Jack Higgins - Lucianos Luck LL.(564505)/Lucianos Luck - Jack Higgins.opf']
14-Aug-2017 21:11:34 - DEBUG   :: POSTPROCESS : /usr/bin/calibredb set opf reports: Title               : Lucianos Luck
Title sort          : Lucianos Luck
Author(s)           : Jack Higgins [Higgins Jack]
Publisher           : Stein & Day Pub
Rating              : 3
Timestamp           : 2017-08-14T20:11:30.235994+00:00
Published           : 1981-06-01T00:00:00+00:00
Identifiers         : goodreads:564505
Comments            : <h3>From Library Journal</h3><p>Dove Audio goes to the head of the pack with this exciting, unabridged rendition of Higgins's (Sheba, Audio Reviews, LJ 2/15/95) story of an Allied plan to release Lucky Luciano from prison. Luciano is slated to join a team that includes the granddaughter of Luciano's Mafia counterpart in Sicily and a crack Special Services operative. Their objective: to persuade the Don to rally the people of Sicily to aid the Allies in their effort to run the Axis forces off the island, paving the way for the Allied invasion of Italy. The action builds to a riveting climax and concomitant bloody conclusion. British actor and former Avenger Patrick Macnee is required to juggle Sicilian, German, American, and Ukrainian accents and does so superbly. Best of all, this unabridged recording is reasonably priced. Recommended for most public libraries.?Mark Pumphrey, Polk Cty. P.L., Columbus, N.C.<br />Copyright 1997 Reed Business Information, Inc. </p><h3>Review</h3><p>"Jack Higgins is the master." Tom Clancy</p>
```

```
$ grep file-as ~scraggles/booktest/Jack\ Higgins/Lucianos\ Luck\ \(11\)/Lucianos\ Luck\ -\ Jack\ Higgins.opf
        <dc:creator opf:file-as="Higgins Jack" opf:role="aut">Jack Higgins</dc:creator>
```

**Comment by philborman** [comment]
The new function generates the name properly, but for some reason later in the code there is a dictionary that strips/replaces some characters, one of which is comma. Don't know what it's for. I've left the dictionary in, but taken comma out of it. It must be there for a reason...

**Comment by sscraggles** [comment]
Yep, that solved it :+1: 

```
14-Aug-2017 23:05:48 - DEBUG   :: POSTPROCESS : [u'/usr/bin/calibredb', 'set_metadata', '--with-library', u'/home/scraggles/booktest', '12', u'/home/scraggles/Downloads/LazyLibrarian/Jack Higgins - Lucianos Luck LL.(564505)/Lucianos Luck - Jack Higgins.opf']
14-Aug-2017 23:05:50 - DEBUG   :: POSTPROCESS : /usr/bin/calibredb set opf reports: Title               : Lucianos Luck
Title sort          : Lucianos Luck
Author(s)           : Jack Higgins [Higgins, Jack]
Publisher           : Stein & Day Pub
Rating              : 3
Timestamp           : 2017-08-14T22:05:46+00:00
Published           : 1981-06-01T00:00:00+00:00
Identifiers         : goodreads:564505
```

```
$ grep file-as ~scraggles/booktest/Jack\ Higgins/Lucianos\ Luck\ \(12\)/Lucianos\ Luck\ -\ Jack\ Higgins.opf 
        <dc:creator opf:file-as="Higgins, Jack" opf:role="aut">Jack Higgins</dc:creator>
```
