### ISSUE TITLE
cover import is cropping full cover image

### ISSUE THREAD

**Issue by sscraggles** [DobyTang/LazyLibrarian#982]
Lazy librarian seems to be creating square cover images.
Image in Open Library is 128x198px, but Lazylibrarian is resizing it square to 250x250px.

**Comment by philborman** [comment]
There is no image resizing code in lazylibrarian.
Calibre has a good book cover search routine that lets you pick a cover from a list of results, we just look for book cover images in various places, taking the first result we find...
1. Local file cached from goodreads/googlebooks when book was imported
2. cover.jpg if we have the book
3. LibraryThing whatwork
4. Goodreads search if book was imported from goodreads
5. Google images search

You can override the chosen cover using the book "manual edit" feature.

**Comment by sscraggles** [comment]
Ah, okay I can see that the cropped images are coming from librarything.

example.
Title/Author/ISBN search for "Moby-Dick or, The Whale"
result page returned with images from goodreads..
Clicked add-book on the result with the most realistic date (1851) and a suitable cover
Book page returned with (different) cropped image from librarything

```
14-Aug-2017 10:41:32 - DEBUG   :: GR-RESULTS : Now searching GoodReads API with searchterm: Moby-Dick or, The Whale
14-Aug-2017 10:41:33 - DEBUG   :: GR-RESULTS : CacheHandler: Storing XML for http://www.goodreads.com/search.xml?q=Moby-Dick+or%2C+The+Whale&key=ckvsiSDsuqh7omh74ZZ6Q
14-Aug-2017 10:41:34 - DEBUG   :: GR-RESULTS : CacheHandler: Storing XML for http://www.goodreads.com/search.xml?q=Moby-Dick+or%2C+The+Whale&key=ckvsiSDsuqh7omh74ZZ6Q&page=2
14-Aug-2017 10:41:35 - DEBUG   :: GR-RESULTS : CacheHandler: Storing XML for http://www.goodreads.com/search.xml?q=Moby-Dick+or%2C+The+Whale&key=ckvsiSDsuqh7omh74ZZ6Q&page=3
14-Aug-2017 10:41:36 - DEBUG   :: GR-RESULTS : CacheHandler: Storing XML for http://www.goodreads.com/search.xml?q=Moby-Dick+or%2C+The+Whale&key=ckvsiSDsuqh7omh74ZZ6Q&page=4
14-Aug-2017 10:41:36 - DEBUG   :: GR-RESULTS : CacheHandler: Storing XML for http://www.goodreads.com/search.xml?q=Moby-Dick+or%2C+The+Whale&key=ckvsiSDsuqh7omh74ZZ6Q&page=5
14-Aug-2017 10:41:36 - DEBUG   :: GR-RESULTS : Found 68 results with keyword: Moby-Dick or, The Whale
14-Aug-2017 10:41:36 - DEBUG   :: GR-RESULTS : The GoodReads API was hit 4 times for keyword Moby-Dick or, The Whale
14-Aug-2017 10:42:10 - DEBUG   :: GR-BOOK : CacheHandler: Storing XML for http://www.goodreads.com/book/show/153747?key=ckvsiSDsuqh7omh74ZZ6Q
14-Aug-2017 10:42:10 - DEBUG   :: GR-BOOK : Searching for author with name: Herman Melville
14-Aug-2017 10:42:10 - DEBUG   :: GR-BOOK : CacheHandler: Storing XML for http://www.goodreads.com/api/author_url/Herman%20Melville?key=ckvsiSDsuqh7omh74ZZ6Q
14-Aug-2017 10:42:11 - DEBUG   :: GR-BOOK : CacheHandler: Storing XML for http://www.goodreads.com/author/show/1624.xml?key=ckvsiSDsuqh7omh74ZZ6Q
14-Aug-2017 10:42:11 - DEBUG   :: GR-BOOK : [Herman Melville] Processing info for authorID: 1624
14-Aug-2017 10:42:12 - INFO    :: GR-BOOK : Moby-Dick or, The Whale by Herman Melville added to the books database
14-Aug-2017 10:42:15 - DEBUG   :: GR-BOOK : getBookWork: Caching workpage for /home/htpc/.lazylibrarian/cache/WorkCache/153747.html
14-Aug-2017 10:42:16 - DEBUG   :: GR-BOOK : getBookCover: Caching librarything cover for 153747
14-Aug-2017 10:42:16 - DEBUG   :: GR-BOOK : Updated cover for Moby-Dick or, The Whale to cache/book/153747.jpg
14-Aug-2017 10:42:16 - DEBUG   :: GR-BOOK : getBookWork: Returning Cached entry for 153747 Series
14-Aug-2017 10:42:16 - DEBUG   :: GR-BOOK : getBookWork: Returning Cached entry for 153747 Workpage
```

Librarything work page has cropped images in the metadata, which is what is getting used in Lazylibrarian and subsequently stored into the filesystem:
![Zoomed/Cropped image](http://pics.cdn.librarything.com/picsizes/8d/ed/8ded42400b7d98361776c7a5251443641506f41.jpg)
`<meta property="og:image" content="http://pics.cdn.librarything.com/picsizes/8d/ed/8ded42400b7d98361776c7a5251443641506f41.jpg"   />`


There is also an un-zoomed/cropped version later in the Librarything page..
![uncropped image](http://pics.cdn.librarything.com/picsizes/58/1b/581bd38ffc5fd9f59776c7a5251434f414f4141.jpg)
`<img width="142" id="mainCover" class="workCoverImage" src="http://pics.cdn.librarything.com/picsizes/58/1b/581bd38ffc5fd9f59776c7a5251434f414f4141.jpg" alt="Moby Dick by Herman Melville" data-adaptive-background="1">`

**Comment by philborman** [comment]
ok, couple of changes to do...
1. try goodreads before librarything
2. scan for the later librarything image

**Comment by sscraggles** [comment]
Re-tested, full covers are now coming in via goodreads.  They do often seem to have lots of white space surrounding them, though *I* can live with that.  Looks like goodreads also have a different image in the meta header to what they use in the page body.

![lucianos luck image with borders](https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1331526172i/564505._UY630_SR1200,630_.jpg)
`<meta property="og:image" content="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1331526172i/564505._UY630_SR1200,630_.jpg"/>`



![lucianos luck image without borders](https://images.gr-assets.com/books/1331526172l/564505.jpg)
`<img id="coverImage" alt="Luciano&#39;s Luck" src="https://images.gr-assets.com/books/1331526172l/564505.jpg" />`

**Comment by philborman** [comment]
The second one is probably a better choice, no white borders, but it's a smaller image. 
I will alter the code to prefer that one.

**Comment by philborman** [comment]
Is this working better now?

**Comment by sscraggles** [comment]
Yep, working great.
