### ISSUE TITLE
two variations of authors name - no way to combine.

### ISSUE THREAD

**Issue by Hydro-guy** [DobyTang/LazyLibrarian#983]
This author Ann H. Gabhart has two variations of her name - A.H. Gabhart and Ann H. Gabhart.  
In LL only 29 of her books are found - Goodreads shows 35 books on web - the 3 below have both variations of her name listed as author.

Look at these 3 books to see issue 

Murder is No Accident,
Murder Comes by Mail, 
Murder at the Courthouse

LL does not find them under Ann H. Gabhart - guessing that this is another case where the api does not return the same results as a Goodreads web search?

Goodreads does have A.H. Gabhart listed separately as well as author of just these 3 novels.

Not sure how often this situation occurs - but this caused me to wonder how pen names should be handled.  Agatha Christie writing as Mary Westmacott for example.

Wondered if a forced match of authors names would handle variations and pen names - but on second thought the complexity this might introduce isn't worth the results.

So the question then is - did the api fail to return both variations of the authors name?  I thought that the book count would have been more correct.  Manually checked.

Looked at her books on Goodreads - one was in German - so remove one from count.  Another was by multiple authors including Ann - with a match of 53.  added it manually and refreshed author books - count up to 30.  added a second  (59%) to reach 31 - all accounted for.

The missing titles were "One Century Wellesley Families Collect. an exhibition celebrating the centennial of Wellesley College"and  "Freak of the Week"

Just a bit of an unexpected behaviour with the names and book count and you would be a better judge of whether this is expected.

Just close this if this is expected (or as good as could be expected)

John

**Comment by philborman** [comment]
Goodreads data isn't perfect, sadly.
Pen names are an issue for several reasons
1. lazylibrarian (currently) only stores one author per book
2. book uploaders won't always use the pen name, or might include both names
3. book metadata might have the "wrong" author name, eg lots of Robert Ludlum books, where the actual author is Eric Van Lustbader have metadata saying Robert Ludlum

LazyLibrarian lets you manually alter the author name or group authors together, but there isn't an automated way to do it. Not sure if one could be devised.

For example, in the UK there are a couple of bearded motorcycle enthusiasts that write cookery books. They are called "The Hairy Bikers"
Some of their books have the author as "The Hairy Bikers"
Some have the author as "Si King and Dave Myers"
Some have "Dave Myers & Si King"
and some just have "Si King"
but it's all the same "author" and should probably be grouped together.

Ann H. Gabhart  api pages say there are 36 books, but as you said one is in German.
Another has the author as "Diamond Books" so gets rejected
Murder is No Accident
Murder Comes by Mail
Murder at the Courthouse
One Century Wellesley Families Collect
Freak of the Week
are all on page 2 of the results, so should be included unless they are rejected later (blocked keyword, isbn says wrong language)

Would be interesting to see what debug log throws up for those 5 titles.

**Comment by MrMxyzptlk** [comment]
Would it be possible to do what Plex does with movies? It will group (if you let it), multiple versions of a movie into one 'item'. You can then click on the 'item' and see all the versions, or the overview just shows one. It works very well.

Would that work for the authors / book titles that are the same but have different spellings / titles?

**Comment by philborman** [comment]
Seems Freak of the Week and One Century Wellesley Families Collect both have language "unknown" so they get filtered out. You can add them manually by searching for them in lazylibrarian. They should come up in the search results as "Have Author" and "Add Book". Click "Add Book". If you already have the book in your library, next time you libraryscan Ann H. Gabhart, lazylibrarian will notice it and link it in correctly. You can force a libraryscan of her books from her author page in lazylibrarian. If you don't already have those books, clicking "Add Book" will start searching for them. If you don't want this, untick "search when added" in config.

The other 3 "Murder" titles, as you said, are attributed to A.H. Gabhart. The api page only gives the one author name, so we reject them as it seems to be the wrong author.  I could probably add some code to give a "close match" acceptance on the name, but as there are only 3 books the alternative is to add A.H. Gabhart to your lazylibrarian library and then move the books manually to Ann H. Gabhart using the "manual" button under each book title on the A.H. Gabhart page. Once you have changed those 3 books to Ann H. Gabhart you can either mark A.H. Gabhart as "ignored" so she doesn't show up in lists, or remove her from your library.

The "close match" option might cause more problems than it's worth, eg where more than one family member is an author, such as Faye Kellerman, Jesse Kellerman, Jonathan Kellerman
The fuzzy library says the 3 Kellerman names are 79% the same, whereas A. H. Gabhart and Ann H. Gabhart are 82% the same. Not much difference between a "right" match and a "wrong" one. It's looking a bit tight. Just Ann Gabhart ( no H. ) is only a 73% match so I don't know of "close match" is actually going to be useful.

**Comment by Hydro-guy** [comment]
I agree – thought that it would introduce too much complexity.  The manual move way seems to be the way to go.

 

Thanks

 

John
