### ISSUE TITLE
Error when searching for Стольник magazine

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#985]
This is the error in the log:

Unhandled exception in search_magazines: Traceback (most recent call last): File "Z:\Applications\lazylibrarian\lazylibrarian\searchmag.py", line 199, in search_magazines if nzbtitle_formatted[0] == '[' and nzbtitle_formatted[-1] == ']': IndexError: string index out of range
--

**Comment by philborman** [comment]
The unhandled exception is easily fixable. The underlying problem isn't.
The cherrypy webserver we use encodes everything in latin-1 and when we strip all the non latin-1 characters out of the magazine title there is nothing left.

I don't know if the latin-1 restriction in cherrypy can be worked around, or if we would need a new webserver. Either way it's a lot of work and probably beyond my capabilities.

**Comment by MrMxyzptlk** [comment]
Thanks for looking into it.
