### ISSUE TITLE
getting books that arent even marked downloaded.

### ISSUE THREAD

**Issue by xcasex** [DobyTang/LazyLibrarian#988]
### git
 
Well. 
61 new authors, i have no idea how that happened, but alas, its not something ive set up to happen i.e marked as wanted, and yet here we are.
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1226593/debug.zip)

**Comment by philborman** [comment]
The debug log doesn't show any authors being added, just lots of searching for books via rss feeds. 
Are the authors maybe part of a series you marked "Wanted" ?

**Comment by xcasex** [comment]
i have a hard time seeing myself reading vivienne westwood... 
i'm in the process of setting up another instance of it, to see if i can replicate it.

**Comment by philborman** [comment]
There are a few occasions where we download authors that you have not explicitly asked for...
1. Series authors
2. Wishlists
3. CSV files

If you mark a series as "wanted", we collect all the authors that contributed to that series, and grab the author details and the books in that series they contributed to. Depending on config settings we can include other books by those authors too.

Similar procedure with wishlists (eg a goodreads reading list) or a csv file (eg New York Times Best Sellers), you can grab all the authors in the list, and optionally other books by those authors.

There is of course option 4, a bug.

**Comment by xcasex** [comment]
unable to reproduce, found another unrelated bug.
