### ISSUE TITLE
Magazine scan removing new item and never adding new folders

### ISSUE THREAD

**Issue by brinkdogg** [DobyTang/LazyLibrarian#989]
LazyLibrarian version number (Repo: https://github.com/dobytang/lazylibrarian : Branch: master

Current Version: 7e7b55060d347c6f98a7bb4faebf8e616ec5858d : Latest Version: 7e7b55060d347c6f98a7bb4faebf8e616ec5858d

Operating system used (Ubuntu 16.04)
Interface in use (bookstrap)
Which api (both)
Source of your LazyLibrarian installation (git)

I add a magazine via the search section it adds it below section like normal. if I scan library it disappears. 
I've even created the folder in the correct location and formatted it correctly. Magazine Foldername Pattern: _Magazines/$Title/$IssueDate Magazine Filename Pattern: $IssueDate - $Title

No matter what when it scan it removes the newly added Magazine and never finds the new folder.

Here is the output:
6-Aug-2017 11:26:42 - INFO :: MAGAZINE_SCAN : Magazine scan complete, found 26 magazines, 72 issues

same Found and issues even after I've added the new folder

**Comment by brinkdogg** [comment]
I also just notice I move some magazines from one folder labeled "something" to "something US" and its not inventorying those that were moved.

**Comment by philborman** [comment]
This is all (probably) normal.
You don't need to create the directories yourself, lazylibrarian will create them when it processes a successful download.  Libraryscan will remove empty directories (magazines with no issues). It's tidying up, as you might have deleted some magazines outside lazylibrarian. No point in leaving empty directories lying around ;-)

When you run LibraryScan, it goes through all the magazines you have got and creates entries in the database for them using the settings in config for "magazine folder name" and "magazine issue name". 
If you rename magazine folders, lazylibrarian will notice you have moved the issues from "something" to "something US" and will update the links to the new location - if you put debug log on you should see messages saying this. If you want to rename the magazine in the database, you probably need to rename the magazine issue files, not just the folder name. The magazine issue name might include the magazine title "something", not "something US", it depends on your config settings.

**Comment by brinkdogg** [comment]
Yep I just figured that out. Was heading back here to update the post as I Screwed up and my formatting wasn't correct on the file name. 

Can LL post-process and mov, rename the directory and files?

**Comment by philborman** [comment]
No, but it will pick up the new names and correct the pointers to the files if you move them, so the "open" buttons get the new location.

Since you're on linux, the bulk file rename is simple using "find" and "sed" from the commandline, or pyrenamer if you prefer a gui.

**Comment by brinkdogg** [comment]
Thanks! you can close this
