### ISSUE TITLE
POSTPROCESS not checking on SABNZBD job status for snatched files

### ISSUE THREAD

**Issue by billbo99** [DobyTang/LazyLibrarian#991]
To help with identifying and fixing issues, please include as much information as possible, including:
LazyLibrarian version: f26db96a370055c1255c69be745b7d1719f731e1 
OS: QNAP 4.3.3
Interface: bookstrap
api: Goodreads

Is there no logic within POSTPROCESS to look at outstanding "Snatched" jobs and check their status against their assigned "Downloader" ?  

The Job for this "Snatched" file is showing as failed withing SABNZBD with the below error message
"Terry Pratchett - Eric LL.(64218) - Aborted, cannot be completed - https://sabnzbd.org/not-complete"

When LL performed its original search there were 10 matches,  in my mind it should remember which ones have failed and try to download the next best match.

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1236923/debug.zip)

**Comment by philborman** [comment]
There is code for this, but it's not nearly as sophisticated as it could be. It's a simple time based blacklist. Anything marked snatched that has not completed in 2hrs is assumed to be failed. 

The postprocessor deletes the failed task from the downloader,  changes the book from snatched to wanted, and puts an entry in the history saying which download failed so the search tasks know to avoid it and try another next time. 

Could definitely be improved, eg could monitor torrent download percentage and not cancel if it's just slow, but with 8 different downloaders all with different methods of talking to them its a lot of work.

**Comment by billbo99** [comment]
I have been looking at the 'Newznab' API format, and its a shame that they don't give the list of files inside the NZB.  If we could get a file list we could then parse for matching "eBooks File Formats", and blacklist NZB those with undesired formats.

The 2x NZB indexers that I subscribe too have a https://.../details/GUID page which lists the files inside the NZB, but each has a totally different HTML output.  With no common ID tags to anchor on to grab the file list from.

**Comment by philborman** [comment]
Yes it's not that helpful. Same with torrents, although you can sometimes get a list of what's in the torrent (depending on the downloader) you have to start the download first to get at the list of what's in it.
