### ISSUE TITLE
Downloaded files renamed. Unable to seed torrents.

### ISSUE THREAD

**Issue by shobhitsinghal624** [DobyTang/LazyLibrarian#994]
### Source of your LazyLibrarian installation: git

Downloaded files are renamed to match the LL format, which creates error while seeding. Ideally the downloaded files should be left intact, and all renames should happen to the ones copied to the ebooks folder.

Example: 
Original folder structure:
```
Labyrinths (628)
    Labyrinths - Borges, Jorge Luis.mobi
    cover.jpg
    metadata.opf
```
After processing:
```
Labyrinths (628)
    Labyrinths - Jorge Luis Borges.jpg
    Labyrinths - Jorge Luis Borges.mobi
    Labyrinths - Jorge Luis Borges.opf
```

Here are the relevant LL settings

```
Downloader: Transmission
Download Directory: /downloads/lazylibrarian
ebooks Library folder: /books
Keep original files: checked
Calibredb import program: /opt/calibre/calibredb
```

**Comment by philborman** [comment]
The folder Labyrinths (628)  looks like a calibre library folder. 628 being the calibre id for that book in your calibre library.

The original download by transmission would be into Download Directory: /downloads/lazylibrarian
and as you have Keep original files: checked there should be the original copy in there, which transmission will still seed from?

**Comment by shobhitsinghal624** [comment]
Folder name is just a coincidence. Getting the same issue with folders without ids. Yes, the original download by transmission is still in the downloads directory, just renamed. The rename is causing the error in transmission.

**Comment by philborman** [comment]
Found it, should be fixed now. Too many different ways to talk to calibre ;-)
