### ISSUE TITLE
AudiobookScan all books for all authors are "undefined". Can't change them.

### ISSUE THREAD

**Issue by goldharv** [DobyTang/LazyLibrarian#997]
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
Current Version: c51d1cbc59257a5d1d0f241f553663811387f605
### Operating system used (windows, mac, linux, NAS type)
linux (Ubuntu 16.04)
### Interface in use (default, bookstrap)
bookstrap
### Which api (Goodreads, GoogleBooks, both)
Goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
git
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report. 

Unable to create debug.zip. Only 2 buttons are on the log page "Clear Log" and "Start/Stop Debug Log" Looking at the log, the UI functionality doesn't seem to get logged to the log anyhow.

My primary issue is that no AudioBook Scan web page shows anything but undefined for any Status. The "Mark Selected" function doesn't seem to work for AudioBooks.

**Comment by philborman** [comment]
Your lazylibrarian version c51d1cb is a couple of months out of date, there have been a lot of changes since. Can you update to latest and see if the problem is still there?  Your debug log buttons are the same problem. Newer versions just say "Start debug log" and the "Stop" and "Save" buttons only appear when the debug log is on.
